### ISSUE TITLE
using a global logger for all `print`

### ISSUE THREAD

**Issue by sonichi** [microsoft/autogen#10]
Maybe considering using a global logger for all `print` ?

_Originally posted by @LittleLittleCloud in https://github.com/microsoft/FLAML/pull/1154#discussion_r1278934636_

**Comment by NeoRyang** [comment]
import sys
import logging

class LoggerWriter:
    def __init__(self, level):
        self.logger = logging.getLogger()
        self.level = level
        self.message = '' 

    def write(self, message):
        if '\n' in message:
            self.message += message.rstrip('\n')
            if self.message:
                self.logger.log(self.level, self.message)
            self.message = ''
        else:
            self.message += message

    def flush(self):
        pass
    
    def isatty(self):
        return False

# handler = logging.FileHandler('myapp.log', 'w')
console_handler = logging.StreamHandler(sys.stdout)
console_handler.setFormatter(logging.Formatter('%(message)s'))

file_handler = logging.FileHandler('myapp.log', 'w')
file_handler.setFormatter(logging.Formatter('%(message)s'))

logger = logging.getLogger()
logger.setLevel(logging.INFO)
logger.addHandler(console_handler)
logger.addHandler(file_handler)

fmt = 'Thinking .... - %(message)s'
formatter = logging.Formatter(fmt)
file_handler.setFormatter(formatter)

sys.stdout = LoggerWriter(logging.INFO)
sys.stderr = LoggerWriter(logging.ERROR)

**Comment by NeoRyang** [comment]
`import sys
import logging

class LoggerWriter:
    def __init__(self, level):
        # 创建 logger
        self.logger = logging.getLogger()
        self.level = level
        self.message = '' 

    def write(self, message):
        if '\n' in message:
            self.message += message.rstrip('\n')
            if self.message:
                self.logger.log(self.level, self.message)
            self.message = ''
        else:
            self.message += message

    def flush(self):
        pass
    
    def isatty(self):
        return False

# 创建一个 FileHandler
# handler = logging.FileHandler('myapp.log', 'w')
console_handler = logging.StreamHandler(sys.stdout)
console_handler.setFormatter(logging.Formatter('%(message)s'))

file_handler = logging.FileHandler('myapp.log', 'w')
file_handler.setFormatter(logging.Formatter('%(message)s'))

logger = logging.getLogger()
logger.setLevel(logging.INFO)
logger.addHandler(console_handler)
logger.addHandler(file_handler)

fmt = 'Thinking .... - %(message)s'
formatter = logging.Formatter(fmt)
file_handler.setFormatter(formatter)

sys.stdout = LoggerWriter(logging.INFO)
sys.stderr = LoggerWriter(logging.ERROR)`

**Comment by NeoRyang** [comment]
`import sys
import logging

class LoggerWriter:
    def __init__(self, level):
        # 创建 logger
        self.logger = logging.getLogger()
        self.level = level
        self.message = '' 

    def write(self, message):
        if '\n' in message:
            self.message += message.rstrip('\n')
            if self.message:
                self.logger.log(self.level, self.message)
            self.message = ''
        else:
            self.message += message

    def flush(self):
        pass
    
    def isatty(self):
        return False

console_handler = logging.StreamHandler(sys.stdout)
console_handler.setFormatter(logging.Formatter('%(message)s'))

file_handler = logging.FileHandler('myapp.log', 'w')
file_handler.setFormatter(logging.Formatter('%(message)s'))

logger = logging.getLogger()
logger.setLevel(logging.INFO)
logger.addHandler(console_handler)
logger.addHandler(file_handler)

fmt = 'Thinking .... - %(message)s'
formatter = logging.Formatter(fmt)
file_handler.setFormatter(formatter)

sys.stdout = LoggerWriter(logging.INFO)
sys.stderr = LoggerWriter(logging.ERROR)`

**Comment by NeoRyang** [comment]
`
import sys
import logging

class LoggerWriter:
    def __init__(self, level):
        self.logger = logging.getLogger()
        self.level = level
        self.message = '' 
    def write(self, message):
        if '\n' in message:
            self.message += message.rstrip('\n')
            if self.message:
                self.logger.log(self.level, self.message)
            self.message = ''
        else:
            self.message += message
    def flush(self):
        pass
    def isatty(self):
        return False

console_handler = logging.StreamHandler(sys.stdout)
console_handler.setFormatter(logging.Formatter('%(message)s'))

file_handler = logging.FileHandler('myapp.log', 'w')
file_handler.setFormatter(logging.Formatter('%(message)s'))

logger = logging.getLogger()
logger.setLevel(logging.INFO)
logger.addHandler(console_handler)
logger.addHandler(file_handler)

fmt = 'Thinking .... - %(message)s'
formatter = logging.Formatter(fmt)
file_handler.setFormatter(formatter)

sys.stdout = LoggerWriter(logging.INFO)
sys.stderr = LoggerWriter(logging.ERROR)

if __name__ == '__main__':
    print("This will go", end=" ")
    print("to the log file")
`

**Comment by JieyuZ2** [comment]
My solution is

```
class Transcript(object):

    def __init__(self, filename):
        self.terminal = sys.stdout
        self.logfile = open(filename, "w")

    def write(self, message):
        self.terminal.write(message)
        self.terminal.flush()
        self.logfile.write(message)
        self.logfile.flush()

    def flush(self):
        # this flush method is needed for python 3 compatibility.
        # this handles the flush command by doing nothing.
        # you might want to specify some extra behavior here.
        pass


def start(filename):
    """Start transcript, appending print output to given filename"""
    sys.stdout = Transcript(filename)


def stop():
    """Stop transcript and return print functionality to normal"""
    sys.stdout.logfile.close()
    sys.stdout = sys.stdout.terminal


start('filename')

main()

stop()
```

**Comment by sinwoobang** [comment]
Any updates? I am interested in contribution.

**Comment by ekzhu** [comment]
@sinwoobang currently we are using IOStream utility for printing to console and to web sockets. If you are interested in contributing, you can take a look at our roadmaps. 

https://aka.ms/autogen-roadmap

Specifically, the persistence and documentation roadmaps need some work.

**Comment by rysweet** [comment]
I don't think further changes for this issue are pending for 0.2 and 0.4 has Otel support throughout. Closing, please reopen if you plan on working on this.
