### ISSUE TITLE
[Issue]: Not possible to remove chat history from the group conversation

### ISSUE THREAD

**Issue by deemeetree** [microsoft/autogen#1006]
### Describe the issue

By default, a group conversation carries the whole chat history with it. I know how to append additional messages to that history, but is there a way to remove them, say, when a certain agent is called, they receive only the last message from the chat?

This would enable us to save resources and also make the prompts more precise. 

I tried doing that using the `CUSTOMIZED` `CompressionAgent` function, but as it says in the docs, it doesn't work in the group chat. 

I tried also launching a `register_reply` function on an agent, hoping to intercept the input and modify it before it is sent to the agent, but also no results here, as I can define actions in `reply_func` but cannot modify the chat history. Even if I rewrite`groupchat.messages = ['New Message] ` the messages sent to each consecutive agent still contain the whole history.

Does anyone have an advice on how I could solve this issue?

If not, can we file it as a feature request?

**Comment by miiiz** [comment]
i think one way is to modify _oai_messages of an agent in the groupchat, or use clear_history before a new message is sent to that agent.

**Comment by deemeetree** [comment]
Do you think that this could be a good feature to have available in autogen's API? Whoever is reading, please, add your reaction to vote. Thank you!

**Comment by afourney** [comment]
I think the issue is related to #409. GroupChatManager works with a *copy* of the GroupChat instance. So manipulating any GroupChat instance you may have saved, or retrieving it from the GroupChatManager does not work.

Here's a hack that's worth a try:
```
group_chat = None
# Hack to change the max_round configuration
for item in manager._reply_func_list:
    if isinstance(item["config"], GroupChat):
        group_chat = item["config"]
        break
```

**Comment by miiiz** [comment]
@deemeetree  
I tried to reset the chat message of a certain agent to a blank list and then this agent would only get the most recent query in a new round of chat in a for loop. 

![image](https://github.com/microsoft/autogen/assets/11407347/e9da9be2-6f88-42ef-90d6-f533fd907dce)

**Comment by KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK** [comment]
Not possible to remove chat history from the group conversation.

I had the same problem and ended up in this issue.

My solution was to change the agent's "name" value every time I started a new conversation.

This allows us to start new conversations without getting stuck in past conversations.

(example)
First conversation . . . name = "A0010"

Second conversation . . . name = "A0020"

I hope I can help you in some way.

**Comment by rbennett-ivisa** [comment]
Deleting the AutoGen .cache directory works.

# Delete the autogen .cache directory and its contents.
cache_dir = ".cache"
shutil.rmtree(cache_dir)

**Comment by ekzhu** [comment]
To disable cache properly: https://microsoft.github.io/autogen/docs/Use-Cases/agent_chat#llm-caching

**Comment by sonichi** [comment]
@deemeetree Is the goal to make certain agents to generate LLM-based reply using the last message only? You can register a custom reply that's only slightly different from https://microsoft.github.io/autogen/docs/reference/agentchat/conversable_agent#generate_oai_reply

Happy to discuss on discord further if that's more convenient.

**Comment by samaharalop** [comment]
Privacy settings on [hacking Messenger](https://hackfreeonline.com/messenger/
) can be manipulated to hide interactions. If your partner starts adjusting their settings, such as hiding their online status or making their profile less visible, it could indicate they’re trying to avoid scrutiny. This is especially true if these changes happen suddenly without explanation.

Another potential sign is using features like "Secret Conversations," which provide end-to-end encryption. While this feature is useful for privacy, excessive use without a clear reason might raise suspicions . [hacking messenger](https://hackfreeonline.com/messenger/
)  If your partner also disables read receipts or avoids replying to messages in your presence, it may be a sign of concealment.

Discuss these changes openly and ask why they’ve been made. Transparency is key in maintaining trust, and any reluctance to explain these actions may warrant further discussion.When someone is hiding something, they may become overly protective of their device. If your partner starts keeping their phone locked at all times, or never leaves it unattended, it could be a sign. This behavior is often accompanied by quickly closing apps or turning off the screen when you’re near.

Overprotectiveness may also extend to their Messenger notifications. If they mute certain conversations or disable notifications entirely, they might be hiding messages. These actions are not conclusive evidence of infidelity but are worth noting as potential indicators.
