### ISSUE TITLE
run_in_executor used for asynchronous calls to openai wrapper

### ISSUE THREAD

**Issue by bitnom** [microsoft/autogen#1009]
In regards to:

https://github.com/microsoft/autogen/blob/dd4a2da20495d1282b6a1efb71640bb6fee2f073/autogen/agentchat/conversable_agent.py#L648

Is this meant to be a permanent solution for a reason I'm not aware of?

**Comment by thinkall** [comment]
@bitnom what's your concerns?

**Comment by thinkall** [comment]
@sonichi fyi

**Comment by rysweet** [comment]
OP let go stale, not sure I see the problem
