### ISSUE TITLE
Install error: Failed building wheel for aiohttp

### ISSUE THREAD

**Issue by vanetreg** [microsoft/autogen#101]
Trying to install pyautogen on a destop with:
Windows 10, VSC, Python 3.12.0
installation can not be completed, having error:
'''
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for aiohttp
Failed to build aiohttp
ERROR: Could not build wheels for aiohttp, which is required to install pyproject.toml-based projects
'''
Any help is appreciated, thank you!

**Comment by ElliotKetchup** [comment]
Hello, I had the same issue.

> Windows 10, VSC, Python 3.12.0


The aiohttp project has not implemented python 3.12 yet, trying with python 3.11 should solve the issue. The aiohttp team is working on the[ 3.12 release](https://github.com/aio-libs/aiohttp/issues/7639) right now.

**Comment by vanetreg** [comment]
@ElliotKetchup 
OK, thanks a lot, I close it.
