### ISSUE TITLE
[Issue]: AutoGen Web UI, unable to edit, delete a new User Skill

### ISSUE THREAD

**Issue by abc-africa** [microsoft/autogen#1013]
### Describe the issue

I was successful with User skill creation and tested, it worked now came a time to edit or even to delete it, not possible.

### Steps to reproduce

Create a new skill from web ui.

**Comment by abc-africa** [comment]
@victordibia I believe you can resolve this.

**Comment by deweyai** [comment]
I have this same issue. I wasn't sure if I was missing something.

**Comment by abc-africa** [comment]
Hello @victordibia sorry fro this issue, after going through the documentation at https://github.com/microsoft/autogen/tree/main/samples/apps/autogen-assistant#capabilities it clearly explains that you will find the skills saved under autogen/samples/apps/autogen-assistant/autogenra/web/skills both global and user skills, you can edit them or delete

**Comment by abc-africa** [comment]
I think we need this feature directly embedded in the UI

**Comment by tikserziku** [comment]
rm /home/user/.local/lib/python3.10/site-packages/autogenra/web/skills/user/198fb9b77fb10d10bae092eea5789295/new_skill.py

**Comment by Cotspheer** [comment]
Why is this closed? I was like "WTF why can't I edit skills?!". This should be in the web interface. I started to plan skills I need and started to add placeholders just to find out I can't edit them. Please make this possible in the interface.

**Comment by victordibia** [comment]
Hi @Cotspheer ,

This has been implemented in the recent version of autogenstudio. See #1442 


https://github.com/microsoft/autogen/assets/1547007/58a32ece-792f-4eba-9195-953b78494158


## References

- [AutoGen studio](https://github.com/microsoft/autogen/tree/autogenstudio/samples/apps/autogen-studio) is the emerging reference example of using AutoGen with a web interface. 
- Roadmap for AutoGen Studio is here #737
