### ISSUE TITLE
[Feature Request]: Optional separate embedding models for documents vs queries

### ISSUE THREAD

**Issue by Codys12** [microsoft/autogen#1015]
### Is your feature request related to a problem? Please describe.

I would like to use a separate embedding model for the query to match against the document embeddings with RAG assistants. This would enable enhanced results in the RAG pipeline.

### Describe the solution you'd like

I would like to add an optional parameter 'query_embeding_function' to 'retrieve_config' 

### Additional context

Enables the use of Siamese Networks for RAG

**Comment by thinkall** [comment]
Hi @Codys12 , it doesn't seem to make much sense to have  different embedding functions for documents and queries. Did I miss something?

**Comment by thinkall** [comment]
Close as no active response for a long time. Please reopen it or create a new issue if needed.
