### ISSUE TITLE
Add tool call to agent and compressible agent

### ISSUE THREAD

**Issue by kevin666aa** [microsoft/autogen#1024]
### Is your feature request related to a problem? Please describe.

Support the latest tool call functionality of openai package.

1. Changes needed in client.py, conversable_agent.py, add a test of the generate_tool_calls functionality
2. Adding token count util for too calls and tests. Can be done concurrently.
3. After 1 and 2, continue the compressible_agent PR

```[tasklist]
### Tasks
- [ ] #974
- [ ] https://github.com/microsoft/autogen/pull/1004
- [ ] https://github.com/microsoft/autogen/pull/1005
```

**Comment by yenif** [comment]
#974 is just conversable agent and client.py
#1004 is compressible agent and token_count_utils
#1005 is compressible agent refactor, new tests, and LLM Lingua

Seems like I can't chain cross fork PRs, so each is a full diff against main and thus includes the changes in the prior PRs

**Comment by kevin666aa** [comment]
Thanks!

**Comment by kevin666aa** [comment]
This is addressed.
