### ISSUE TITLE
[Bug]: Duplicated model property in llm_config in conversible agent

### ISSUE THREAD

**Issue by yashwanth-namora** [microsoft/autogen#1025]
### Describe the bug

@afourney, I and Soham were debugging the default model with some logs interestingly the conversible agent logs gave the below JSON(PFA). Containing the 2 models in the llm_config. Mostly when the agent config contains the function calls. 

### Expected Behavior

Expect to be only one model defined in the config.

### Screenshots and logs

<img width="621" alt="Screenshot 2023-12-19 at 4 01 29 PM" src="https://github.com/microsoft/autogen/assets/148343545/63e34c7e-1693-4709-b226-f2e9aa45f492">

### Additional Information

I think this is happening coz of this piece of code in ConversableAgent line number 114. I might be wrong as well

```
if llm_config is False:
    print("LLM_CONFIG FALSE CASE")
    self.llm_config = False
    self.client = None
else:
    self.llm_config = self.DEFAULT_CONFIG.copy()
    if isinstance(llm_config, dict):
        self.llm_config.update(llm_config)
        print("LLM_CONFIG NOT FALSE CASE")
    self.client = OpenAIWrapper(**self.llm_config)
```

**Comment by afourney** [comment]
Again, I do hope that key is old and revoked.

Here, I think the config_list will copy over the model at the time we make the OpenAI call. @sonichi to config.

But ideally, we would not have that "gpt-4" default in there, since it's asking for problems.

**Comment by rickyloynd-microsoft** [comment]
> But ideally, we would not have that "gpt-4" default in there, since it's asking for problems.

Definitely.

**Comment by afourney** [comment]
Yeah we are in agreement there. I'll submit a pr to remove it.

**Comment by afourney** [comment]
@yashwanth-namora @rickyloynd-microsoft  this PR removes the dangerous default: https://github.com/microsoft/autogen/pull/1072
