### ISSUE TITLE
[Issue]: No module named agent_builder

### ISSUE THREAD

**Issue by PriyaBrataSen** [microsoft/autogen#1030]
### Describe the issue

I am trying to use agentbuilder. i am following this article 
https://microsoft.github.io/autogen/blog/2023/11/26/Agent-AutoBuild/

However, when i am trying to import agentbuilder, there is no module called agent_builder. VS code underlines the import command. Please let me know where is the issue. I am using azure openai and pyautogen 0.2.0.below is my code and answer 

### Steps to reproduce

import autogen
from autogen.agentchat.contrib.agent_builder import AgentBuilder

config_path = autogen.config_list_from_json(env_or_file="OAI_CONFIG_LIST")
default_llm_config = {
    'temperature': 0
}

builder = AgentBuilder(config_path=config_path, builder_model='gpt-4-8k', agent_model='gpt-4-8k')

building_task = "Find a paper on arxiv by programming, and analyze its application in some domain. For example, find a latest paper about gpt-4 on arxiv and find its potential applications in software."

agent_list, agent_configs = builder.build(building_task, default_llm_config, coding=True)

def start_task(execution_task: str, agent_list: list, llm_config: dict):
    config_list = autogen.config_list_from_json(config_path, filter_dict={"model": ["gpt-4-8k"]})

    group_chat = autogen.GroupChat(agents=agent_list, messages=[], max_round=12)
    manager = autogen.GroupChatManager(
        groupchat=group_chat, llm_config={"config_list": config_list, **llm_config}
    )
    agent_list[0].initiate_chat(manager, message=execution_task)

start_task(
    execution_task="Find a recent paper about gpt-4 on arxiv and find its potential applications in software.",
    agent_list=agent_list,
    llm_config=default_llm_config
)

### Screenshots and logs

raceback (most recent call last):
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\autobuild.py", line 3, in <module>
    from autogen.agentchat.contrib.agent_builder import AgentBuilder
ModuleNotFoundError: No module named 'autogen.agentchat.contrib.agent_builder'

### Additional Information

python 3.11.3

**Comment by rickyloynd-microsoft** [comment]
@PriyaBrataSen There were changes to agent builder in the latest version of pyautogen==0.2.2. Upgrading to that may help.

**Comment by PriyaBrataSen** [comment]
thank you. I install the 2.2.2 version now. When i am trying to find the agent_builder module under contrib. It doesn't show up. It only shows agent_configs, agent_list and agent_model. This is where i get stuck as i am unable to import AgentBuilder
**from autogen.agentchat.contrib.**

**Comment by rickyloynd-microsoft** [comment]
Are you saying that you cloned the repo locally, and the agent_builder directory doesn't exist on your machine? If so, you need to do `git pull`.

**Comment by PriyaBrataSen** [comment]
ohh no. i didn't clone the repo. I just installed pyautogen into a virtual environment and tried to run autobuilder.

**Comment by rickyloynd-microsoft** [comment]
@LinxinS97

**Comment by PriyaBrataSen** [comment]
@rickyloynd-microsoft i found a youtube video. I installed "pip install git+https://github.com/microsoft/autogen.git " in my virtual environment and now it is running fine.

**Comment by rickyloynd-microsoft** [comment]
Seems like that shouldn't be necessary. What exactly was your pip install command before?

**Comment by PriyaBrataSen** [comment]
it was pip install -r requirements.txt. 
I still don't see the agent_builder module but it runs now

i have these in the txt file
python-dotenv
pyautogen==0.2.2
yfinance
openai
xgboost
requests

**Comment by rickyloynd-microsoft** [comment]
The public pip install command is `pip install pyautogen`.

**Comment by PriyaBrataSen** [comment]
okay will change that to pyautogen

**Comment by Nucs** [comment]
When using Python 3.12, the AgentBuilder is not present. Use a lower python version.

**Comment by ekzhu** [comment]
@Nucs currently Python 3.12 is not supported by autogen

**Comment by cuoicungtui** [comment]
Hi team,

I'm using Python 3.10.2 and have installed the latest pyautogen package (version 0.10.0).
I noticed that the module autogen.agentchat.contrib.agent_builder is missing, and I get this error:

ModuleNotFoundError: No module named 'autogen.agentchat.contrib.agent_builder'

I’ve seen older examples using AgentBuilder, but I’m not sure if it’s still supported in 2025 or has been deprecated/renamed.

Could you please clarify whether AgentBuilder is still available?
If yes, how should I properly import or use it with the current version?

Thanks in advance!
