### ISSUE TITLE
[Issue]: Replicate OpenAI assistant function calling and other features

### ISSUE THREAD

**Issue by danialtv** [microsoft/autogen#1031]
How one can generate a replica of the OpenAI assistant interface so that the agents would call functions locally and also have code interpreter enabled?

When I pass the AssistantID to `GPTAssistantAgent` on https://platform.openai.com/assistants, where I have defined manually an assistant with functions, e.g. crawl_web, and code_interpretor ON, then Autogen works flawlessly. However, any attempt such as below has been futile:

```python
def google_search(parameter_1):
    # Placeholder for the original function body
    pass

researcher_functions = [
    {
        "name": "google_search",
        "description": "google search keywords",
        "parameters": {
            "type": "object",
            "properties": {
                "search_keyword": {
                    "type": "string",
                    "description": "A great search keyword that most likely to return result for the information you are looking for",
                }
            },
            "required": ["search_keyword"],
        },
    },
]

minion = GPTAssistantAgent(
    instructions='some prompt that should trigger internal functions',
    name="minion",
    llm_config={
        "timeout": 600,
        "config_list": config_list,
        "cache_seed": None,
        "functions": researcher_functions,
        "tools": [
            {
                "type": "code_interpreter"
            }
        ],
    },
)

minion.register_function(
    function_map={
        "google_search": google_search,
    }
)
```

### Additional Information

`pyautogen==0.2.2` version
Python 3.11.7

**Comment by rickyloynd-microsoft** [comment]
@gagb

**Comment by gagb** [comment]
@danialtv please checkout this nb for function calling with GPTAssistant. Please take a look at how it specifies the functions. Suggest modifying this nb with functions you need. Let us know if it doesn't help.

**Comment by rickyloynd-microsoft** [comment]
> @danialtv please checkout this nb for function calling with GPTAssistant. Please take a look at how it specifies the functions. Suggest modifying this nb with functions you need. Let us know if it doesn't help.

This is probably the nb:  https://github.com/microsoft/autogen/blob/main/notebook/agentchat_oai_assistant_function_call.ipynb

**Comment by gagb** [comment]
was addressed.
