### ISSUE TITLE
[Feature Request]: Add code save logic to execute_code_blocks

### ISSUE THREAD

**Issue by nikawang** [microsoft/autogen#1035]
### Is your feature request related to a problem? Please describe.

sometimes we need to ask auto gen to generate multiple files first in a project folder, after that, we can ask auto gen to execute the code or start the project.

https://github.com/microsoft/autogen/blob/a0288e081bf207baf93c12f3c2376a16f7521164/autogen/agentchat/conversable_agent.py#L1097

### Describe the solution you'd like

At this stage, the agent always executes the code snippet first, and returns errors infinitely since the it fails to execute the code directly.

### Additional context

Please check the output from https://github.com/nikawang/try-autogent/blob/main/daniel-write-simpleapp.ipynb

**Comment by rickyloynd-microsoft** [comment]
Thanks for the feature request @nikawang . The example in your nb fails because autogen agents cannot execute javascript. What exactly are you proposing as the desired behavior in such cases?

**Comment by nikawang** [comment]
Hi @rickyloynd-microsoft, thank you for your prompt response. I would like to request that Autogen implement a web-based Snake Game project, which will consist of multiple files. It appears that Autogen currently attempts to execute single code blocks by default. Could you please advise on how to configure it to handle a multi-file project?

**Comment by nikawang** [comment]
Thanks. got it.
