### ISSUE TITLE
[Issue]: AssistantAgent with Mistral Instruct Models via vLLM - Conversation roles must alternate user/assistant/user/assistant

### ISSUE THREAD

**Issue by Cyb3rWard0g** [microsoft/autogen#1037]
### Describe the issue

I am trying to use [TheBloke/Mistral-7B-Instruct-v0.2-AWQ](https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.2-AWQ) with AssistantAgent for a multi-agent conversation. Every Mistral instruct based agent has the following chat template which does not include or allow a "System" role: https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.2-AWQ/blob/main/tokenizer_config.json#L42

When I run a basic example, I get the following error:

```
BadRequestError: Error code: 400 - {'object': 'error', 'message': 'Conversation roles must alternate user/assistant/user/assistant/...', 'type': 'invalid_request_error', 'param': None, 'code': None}
```

When I remove the `system_message` from the assistant, I believe it gets a default System Message which I believe is using the System role which triggers that error.

### Steps to reproduce

Install the following version:

```
pyautogen 0.2.2
openai 1.6.0
```

Host LLM via vLLM using MistralAI docs: https://docs.mistral.ai/self-deployment/vllm and its official docker image: https://github.com/mistralai/mistral-src/blob/main/deploy/Dockerfile

```
python3 -u -m vllm.entrypoints.openai.api_server --host 0.0.0.0 --model "TheBloke/Mistral-7B-Instruct-v0.2-AWQ" --dtype "half" --max-model-len 8192 --gpu-memory-utilization 0.7 --quantization "awq" --download-dir "/workspace/.cache/huggingface/hub"
```

Then, run the following code:

```python
import autogen

config_list = [
    {
        # 'https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.2-AWQ'
        'model': 'TheBloke/Mistral-7B-Instruct-v0.2-AWQ',
        'api_key' : '...',
        'base_url': 'http://localhost:8000/v1'
    }
]

llm_config={
    "timeout": 600,
    "seed": 42,
    "config_list": config_list,
    "temperature": 0
}

assistant = autogen.AssistantAgent(
    name="assistant",
    llm_config=llm_config,
    system_message="""
    You are a helpful assistant.
    """,
    code_execution_config={"work_dir":"work"}
)

user_proxy = autogen.UserProxyAgent(
    name="user_proxy",
    human_input_mode="NEVER",
    max_consecutive_auto_reply=5
)

task = """
Write python code to output numbers 1 to 100.
"""

user_proxy.initiate_chat(
    assistant,
    message=task
)
```

### Additional Information

```
pyautogen 0.2.2
openai 1.6.0
```

**Comment by rickyloynd-microsoft** [comment]
@victordibia

**Comment by victordibia** [comment]
I have tried a zephyr model (a mistral chat finetune) and get some decent results via vllm.

```bash
python -m vllm.entrypoints.openai.api_server --model TheBloke/zephyr-7B-alpha-AWQ --quantization awq --dtype half  
``` 

I'd recommend starting here.

**Comment by sc-govsin** [comment]
I believe this is something related to template. I added `--chat-template template_alpaca.jinja` in the argument and it fixed this problem.

**Comment by sinwoobang** [comment]
I got a similar issue while using Perplexity. Did anyone fix it?

```
BadRequestError: Error code: 400 - {'error': {'message': 'After the (optional) system message(s), user and assistant roles should be alternating.', 'type': 'invalid_message', 'code': 400}}
```

**Comment by ekzhu** [comment]
@sinwoobang we can get some help on this. Can you create an issue for perplexity support?

**Comment by sinwoobang** [comment]
@ekzhu Alright.

**Comment by ekzhu** [comment]
The solution:

> I believe this is something related to template. I added --chat-template template_alpaca.jinja in the argument and it fixed this problem.

**Comment by sinwoobang** [comment]
@ekzhu I created it. https://github.com/microsoft/autogen/issues/2405
