### ISSUE TITLE
Website improvements

### ISSUE THREAD

**Issue by qingyun-wu** [microsoft/autogen#1041]
@skzhang1 @qingyun-wu, @sonichi   and team, thanks for all the work on a bootstrapped gallery. 
I agree with all the ideas to far, and happy to see all the progress coming together in #850 .

I'd love to continue to work together with you all on a few things we can do (not urgent) to further improve the website for better community interaction.  Some examples 

- upgrade the docs to docusaurus[ 3.0](https://docusaurus.io/blog/releases/3.0) (v 2.4.3), to take advantage of recent advances in the library (we seem to be on v 0.0.0-4193). 
- explore an updated template for better information presentation. For example, something like [dyte](https://github.com/dyte-io/docs) (screenshot below)
- any other ideas 

I am happy to help provide guidance and help along the way. 

What do you all think? 

Thanks again for all the awesome work here @skzhang1 

![Image](https://github.com/microsoft/autogen/assets/1547007/17f04f57-f306-4267-9518-f13036625523)

_Originally posted by @victordibia in https://github.com/microsoft/autogen/issues/830#issuecomment-1839138875_

**Comment by victordibia** [comment]
@qingyun-wu , thanks for following up here! 
I am OOO for the next week, but can start work on this once back!

**Comment by olaoluwasalami** [comment]
Hello @qingyun-wu, I can start work on some the stuff listed here

**Comment by olaoluwasalami** [comment]
@victordibia @qingyun-wu  Started working on updating docusaurus. You can see my progress here https://github.com/microsoft/autogen/pull/1101

**Comment by rysweet** [comment]
new website already rolled.
