### ISSUE TITLE
autogen does not save generated content to file

### ISSUE THREAD

**Issue by TomKomar** [microsoft/autogen#105]
Upon installing autogen on Windows 11, Pycharm venv Python3.8 and generating first sample script (without using code_execution_config parameter for the UserProxyAgent) the script got printed to terminal and file with the script got saved to autogen's installation directory (autogen/extensions/script_name.py). Following attempts did not produce a saved file but only printout to terminal. Specifying code_execution_config={"work_dir":"coding"} did not save the file to coding. Setting work_dir to None did not make it save to the installation directory (the way it is described in line 52 of user_proxy_agent.py), setting it to an absolute path ("D:/t/pycharm/mygpt/coding") did not make a difference. I can't find a way to get autogen to save the generated files, it did that only once on first run.
Is there a solid method of getting the generated file to disk?

**Comment by xsa-dev** [comment]
I can confirm the issue, and I'd like to suggest having a dedicated directory for outgoing code and another for incoming data (in case the data parsing extension is utilized). Ideally, it would be great to have a code sandbox with integrated data storage.

**Comment by nikthecrick** [comment]
Hi, I second this issue. I would like to utilise the output as a file for another python program. 
Also I can not extract the conversation to a variable to use it further in the code for parsing or similar.
Appreciate if anybody has hints how to do this? thank you!

**Comment by TomKomar** [comment]
in Pycharm there's an option to write console output to a file (it overwrites with every script run). You can find it in: Run > Edit Configurations > select your script in left panel > Logs > Save console output to file ...

**Comment by sonichi** [comment]
Does this help? https://microsoft.github.io/autogen/docs/FAQ/#why-is-code-not-saved-as-file

**Comment by TomKomar** [comment]
It does, sometimes :) I tried it before by following the linked FAQ by doing:
`AssistantAgent(system_message="# filename:  filename.py")`
but that failed and now after few different attempts it turned out that it should go into the initial chat message like:
`user_proxy.initiate_chat(recipient=assistant, message="# filename: filename.py; write a python script that will capture today's sunrise and sunset information and print it in terminal, save the code to disk")`
Upon receiving a satisfactory response (that mentions the provided filename) you need to press [enter] for auto-reply (which attempts to run the code, sometimes failing for no good reason as later it works fine when ran manually) and then type `exit`.
Sometimes the response states that the file will be saved under a different name (that corresponds to what the script actually does) but then it won't save anything.

**Comment by dubyabee2** [comment]
I changed the line to:  
```
# Start the conversation
user_proxy.initiate_chat(
    assistant, message="# filename: stock_price_chart.py; Plot a chart of NVDA, AAPL and TESLA stock price change YTD.")
```
It complains about panda_datareader but on second run it substitutes yfinance runs and safes error free

**Comment by sonichi** [comment]
When the default system message is not changed, it should suffice to say "save the plot to a file" or "save the code to a file" depending on what you'd like to save, in the initial message.

**Comment by mribbons** [comment]
As this is still open, I made a script to pull files from the latest conversation:
https://gist.github.com/mribbons/5250a8d1db6bf14d1becafafb00cb892

**Comment by tianyalangzi** [comment]
I have the same problem, how can I fix it！

**Comment by ompanda** [comment]
is there any way autogen creates files in respective folders. ex: after generating code autogen can create files for logical separation and puts them in separate folders like components, utils, etc

**Comment by sonichi** [comment]
Interesting idea. Need to create specialized agents to do this and potentially use function calls to perform the task.
@LinxinS97 @JieyuZ2 can be a task to try for auto build.

**Comment by xsa-dev** [comment]
Will it work on Mac?
