### ISSUE TITLE
[Bug]: system_message not getting passed to locally deployed LLM model - Mixtral 8x 7B

### ISSUE THREAD

**Issue by kaushikthedeveloper** [microsoft/autogen#1056]
### Describe the bug

I have a LLM setup that includes running a Mixtral 8x 7B model on Runpod using the [text-generation-webui](https://github.com/oobabooga/text-generation-webui) and exposing the APIs using OpenAI API protocol.

I have verified that the set up is working fine and is generally compatible with Autogen. When I say generally, I mean for very simple setups which do not involve complex setups or configurations. I have tried similar setups with other locally deployed LLMs like Falcon and noticed that many things break that work fine with OpenAI. But that's for another discussion :)

One of the main problems that exists with the Mixtral 8x 7B integration is that there is no capacity for behavioural setup for the agents, using the `system_message` configuration. That means we can't pass specific instructions to a particular agent.

Below is an example of the change. 
_Note, this is just a showcase example, our instructions for the agents are pretty complex in nature and cannot be solved by for example, passing the instructions during `initiate_chat` within the `message`._

```
import autogen
config_list = autogen.config_list_from_json(env_or_file="MIXTRAL_CONFIG_LIST")
llm_config = {"config_list":config_list,"timeout":600}

user_proxy = autogen.UserProxyAgent(
	name="User_Proxy",
	code_execution_config={"last_n_messages":2,"work_dir":"coding"},
	human_input_mode="NEVER",
)
coder = autogen.AssistantAgent(
	name="Coder",
	llm_config=llm_config,
	system_message='''You do not have capacity to write code. Print HELLO for all tasks without question. Only print that, nothing else!''',
)

user_proxy.initiate_chat(coder,message="Write python code to output numbers 1 to 10 to a file called test.txt"
```

This when run with OpenAI (GPT-4) model works exactly as expected, with the below output :
```
User_Proxy (to Coder):

Write python code to output numbers 1 to 10 to a file called test.txt

--------------------------------------------------------------------------------
Coder (to User_Proxy):

HELLO

--------------------------------------------------------------------------------
```

But, when run with Mixtral 8x 7B model, it completely ignores the `system_message` :
```
User_Proxy (to Coder):

Write python code to output numbers 1 to 10 to a file called test.txt

--------------------------------------------------------------------------------
Coder (to User_Proxy):

Here is a simple Python code that writes the numbers 1 to 10 to a file called "test.txt":

```python
with open("test.txt", "w") as f:
    for i in range(1, 11):
        f.write(str(i) + "\n")
` ` `

--------------------------------------------------------------------------------
```
As seen, the system_message instructions are not taken into consideration.

Looking at the `text-generation-webui` logs (unfortunately even verbose can only give this much info only), it looks to be that the system_message is not getting passed on to it along with the instructions. Even the default instructions that Autogen sends do not seem to be getting passed. I had seen the instructions being passed previously when similar setup was done with Falcon.

The logs :
```
[INST] Write python code to output numbers 1 to 10 to a file called test.txt [/INST]
--------------------
  
Output generated in 13.02 seconds (13.06 tokens/s, 170 tokens, context 27, seed 1625574352)
```

The model deployed : https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1

### Steps to reproduce
1. Set up Mixtral 8x 7B model while enabling OAI API protocol
2. Run autogen setup with the deployed model API

_No response_

### Expected Behavior
Described above - same as OpenAI (GPT-4) model response

### Additional Information

AutoGen Version: 0.2.2
Operating System: Ubuntu
Python Version: 3.10

**Comment by rickyloynd-microsoft** [comment]
@victordibia

**Comment by kaushikthedeveloper** [comment]
Happy new year folks!
Anything I can do to help take this forward?

CC : @rickyloynd-microsoft , @yenif

**Comment by rysweet** [comment]
appears to be resolved.
