### ISSUE TITLE
[Bug] AttributeError: 'UserProxyAgent' object has no attribute 'register_for_execution'

### ISSUE THREAD

**Issue by luohao123** [microsoft/autogen#1061]
The example code have errors

AttributeError: 'UserProxyAgent' object has no attribute 'register_for_execution'

https://github.com/microsoft/autogen/blob/main/notebook/agentchat_function_call_currency_calculator.ipynb

Please edit it avoid misleading new comer users.

**Comment by rickyloynd-microsoft** [comment]
The problem could be that you are using the public pip version `pyautogen=0.2.2`, which doesn't support the function decorators. You can clone the repo then install it with `pip install -e .` from the autogen dir.

**Comment by luohao123** [comment]
@rickyloynd-microsoft When will the latest master code on pypi?

**Comment by luohao123** [comment]
Also, when using default docker run python code, always have this error:

import requests
ModuleNotFoundError: No module named 'requests'

I can not say it's LLM produces error, but requests is just system lib, why it runs error like this

**Comment by rickyloynd-microsoft** [comment]
> @rickyloynd-microsoft When will the latest master code on pypi?

We don't have a date, but almost certainly within 2 weeks.

**Comment by rickyloynd-microsoft** [comment]
> Also, when using default docker run python code, always have this error:
> 
> import requests ModuleNotFoundError: No module named 'requests'
> 
> I can not say it's LLM produces error, but requests is just system lib, why it runs error like this

Are you able to run the sample code [here ](https://github.com/microsoft/autogen/blob/main/samples/simple_chat.py) without docker?

**Comment by luohao123** [comment]
I don't know, but as a common sense, requests should can be used out of box in python3

**Comment by rickyloynd-microsoft** [comment]
To identify your problem, please start with the simple example [here ](https://github.com/microsoft/autogen/blob/main/samples/simple_chat.py) before attempting docker.

**Comment by nise** [comment]
So the code is still not available at pypi?

**Comment by thinkall** [comment]
@nise could you try `pip install -U pyautogen==0.2.29`?

**Comment by LucasTrg** [comment]
> I don't know, but as a common sense, requests should can be used out of box in python3

The requests module has never been a part of the python3 standard library : https://pypi.org/project/requests/
You're probably mixing it up with [urllib.request](https://docs.python.org/3/library/urllib.request.html)

**Comment by rysweet** [comment]
seems to no longer be an issue.

**Comment by MehdiCHEBBAH** [comment]
I actually got the same error, here is a detailed log:
```python
File "/path/to/project/venv/lib/python3.10/site-packages/flaml/autogen/agentchat/conversable_agent.py", line 523, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "/path/to/project/venv/lib/python3.10/site-packages/flaml/autogen/agentchat/conversable_agent.py", line 326, in send
    recipient.receive(message, self, request_reply, silent)
  File "/path/to/project/venv/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 911, in receive
    self._process_received_message(message, sender, silent)
  File "/path/to/project/venv/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 878, in _process_received_message
    if not ConversableAgent._is_silent(sender, silent):
  File "/path/to/project/venv/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 275, in _is_silent
    return agent.silent if agent.silent is not None else silent
AttributeError: 'UserProxyAgent' object has no attribute 'silent'
```
