### ISSUE TITLE
[Bug] handles py code?

### ISSUE THREAD

**Issue by lucasjinreal** [microsoft/autogen#1062]
```
请尝试使用以下更新的代码：
```py
# filename: news_report.py

import requests

url = 'https://newsapi.org/v2/top-headlines?country=us&apiKey=<your_api_key>'
response = requests.get(url)
data = response.json()

headlines = [article['title'] for article in data['articles']]
markdown_report = '\n'.join(['- ' + headline for headline in headlines])

print(markdown_report)
```
在您的计算机上创建一个名为`news_report.py`的新文件，并将此代码粘贴到其中。 然后，请替换`<your_api_key>`为您的News API密钥。 如果您没有密钥，请访问[News API](https://newsapi.org/)注册并获取一个免费的API密钥。
保存文件后，在命令行中运行以下命令以执行脚本：
```
python news_report.py
```
当脚本成功执行时，它将显示新闻标题列表。 请注意，由于API限制和网络延迟，结果可能有所不同。

--------------------------------------------------------------------------------

>>>>>>>> EXECUTING CODE BLOCK 0 (inferred language is py)...
user_proxy (to assistant):

exitcode: 1 (execution failed)
Code output:
unknown language py
```


How to handle py code?

Obviously, py is a valid lan in most markdown format...... and very human knows it's python, why this stupid agent not?

**Comment by rickyloynd-microsoft** [comment]
@lucasjinreal Can you provide a complete example in English only?

**Comment by lucasjinreal** [comment]
For summay, the code can not be executed when LLM produces code in markdown format with `py` code mark.

**Comment by rickyloynd-microsoft** [comment]
@sonichi

**Comment by sonichi** [comment]
Let's add "py" to line 1119 of conversable_agent.py

**Comment by SANTHOSH-MAMIDISETTI** [comment]
@sonichi  is it solved or there is something to be worked on to solve it ?, If yes , I am interested in working on this issue ,

**Comment by sonichi** [comment]
It's not solved. You can assign yourself and work on it.

**Comment by SANTHOSH-MAMIDISETTI** [comment]
> Let's add "py" to line 1119 of conversable_agent.py

@sonichi  can you please elaborate what does this mean,  I have briefly gone through the conversable_agent.py present at [autogen/agentchat/conversable_agent.py](https://github.com/microsoft/autogen/blob/main/autogen/agentchat/conversable_agent.py) and also the line number 1119
![image](https://github.com/microsoft/autogen/assets/92091342/f8d5d3b0-56b5-4116-a3a7-5b551ae7c40b)

It was an else statement.  Maybe I am missing a few more details , I am not quite sure of how to proceed

> Let's add "py" to line 1119 of conversable_agent.py

suggestions are appreciated :)

**Comment by SANTHOSH-MAMIDISETTI** [comment]
I'm currently encountering difficulty in assigning myself.
> It's not solved. You can assign yourself and work on it.

**Comment by rickyloynd-microsoft** [comment]
> I'm currently encountering difficulty in assigning myself.
> 
> > It's not solved. You can assign yourself and work on it.

I just assigned you.

**Comment by sonichi** [comment]
> > Let's add "py" to line 1119 of conversable_agent.py
> 
> @sonichi can you please elaborate what does this mean, I have briefly gone through the conversable_agent.py present at [autogen/agentchat/conversable_agent.py](https://github.com/microsoft/autogen/blob/main/autogen/agentchat/conversable_agent.py) and also the line number 1119 ![image](https://private-user-images.githubusercontent.com/92091342/296498821-f8d5d3b0-56b5-4116-a3a7-5b551ae7c40b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxNjA1NDcsIm5iZiI6MTcwNTE2MDI0NywicGF0aCI6Ii85MjA5MTM0Mi8yOTY0OTg4MjEtZjhkNWQzYjAtNTZiNS00MTE2LWEzYTctNWI1NTFhZTdjNDBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDE1MzcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjNDc1YWJlNjhmZDg0YWI4OGI0OWIzMDdiNTUzZDE0NWE4ZDMyYTMzMTdlYjBlZWRkZTFhOWRhZDY2YTAxMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0mZtr_3cB8ANjZeCZliqHSqy1m8-Xz0Ss6qUp5TNDzI)
> 
> It was an else statement. Maybe I am missing a few more details , I am not quite sure of how to proceed
> 
> > Let's add "py" to line 1119 of conversable_agent.py
> 
> suggestions are appreciated :)

The file is updated. The new line is: https://github.com/microsoft/autogen/blob/44260934f34b2e237fbf6d3da0cedd514642e294/autogen/agentchat/conversable_agent.py#L1395

**Comment by SANTHOSH-MAMIDISETTI** [comment]
Oh  alright, in that case , I believe that the issue has been solved ? @sonichi @rickyloynd-microsoft 

or the same line has to be added even at line 1119 as mentioned in the below 

> Let's add "py" to line 1119 of conversable_agent.py

**Comment by sonichi** [comment]
It hasn't been solved. Just the line number has changed.

**Comment by debianmaster** [comment]
can you also add support for language type "yaml"  for which a file has to be created ?
just guide me so i can change

**Comment by sonichi** [comment]
> can you also add support for language type "yaml" for which a file has to be created ? just guide me so i can change

Two places need to be modified to add an "elif" branch:
https://github.com/microsoft/autogen/blob/44260934f34b2e237fbf6d3da0cedd514642e294/autogen/code_utils.py#L224
https://github.com/microsoft/autogen/blob/44260934f34b2e237fbf6d3da0cedd514642e294/autogen/agentchat/conversable_agent.py#L1406

**Comment by SANTHOSH-MAMIDISETTI** [comment]
In that case, I think , adding  "py" along with python and all other languages mentioned over there completes this issue , is that all ?
