### ISSUE TITLE
[Quesiton] Really hard to predict the behavior from LLM

### ISSUE THREAD

**Issue by luohao123** [microsoft/autogen#1066]
I have an issue:

I want ask agent to search news by a keyword, and write me an article about it.

To break it up, it needs at least: first call my search_engine function to get news url, the parse the url to content, then write article.

BUT now, it looks very weired for me:

<img width="1274" alt="image" src="https://github.com/microsoft/autogen/assets/49749220/f7f1a388-d7c7-47be-b94d-2ecd39de7f9e">

As you can see,  the function called, the urls got. but it just reply me content with simple content, but not an article

this is my require:

```python
assistant = autogen.AssistantAgent(
    name="assistant",
    llm_config=llm_config,
    system_message="You are helpful agent that can select right tools to fullfill users request. DO NOT response rest info except the json format response.",
)

# create a UserProxyAgent instance named "user_proxy"
user_proxy = autogen.UserProxyAgent(
    name="user_proxy",
    # human_input_mode="TERMINATE",
    human_input_mode="NEVER",
    max_consecutive_auto_reply=10,
    # is_termination_msg=lambda x: x.get("content", "").rstrip().endswith("TERMINATE"),
    code_execution_config={"work_dir": "web"},
    # llm_config=llm_config_no_func,
    system_message="""When a link is provided, you should ask the assistant for fetching the content. Reply TERMINATE if the task has been solved at full satisfaction.Otherwise, reply CONTINUE, or the reason why the task is not solved yet.""",
    function_map={
        "exchange_rate": currency_calculator,
        "search_google": search_google_news,
    },
)


# user_proxy.register_function(function_map=)


print(assistant.llm_config)

user_proxy.initiate_chat(
    assistant,
    message="搜索关于哈马斯的新闻内容，并根据新闻检索结果进行汇总，根据这些资料撰写一篇具有自媒体风格的文章，标题一定要具有极大的吸引力。",
)

```

So I want ask:

1. why the behavior far from I expected?
2. How to resolve? Need a using a new writerAssistant with another system message? By how?

**Comment by luohao123** [comment]
the LLM using chatgpt3.5 here

**Comment by rickyloynd-microsoft** [comment]
Two things:
1. Can you provide an example using English only?
2. Please use the templates provided when creating a new issue. The template options should appear when you click New Issue.

**Comment by thinkall** [comment]
@luohao123 ,  what does your function `search_google` do? It should return the url and its contents. Now, you can use sequential chat to split the task into two steps. Step 1 to retrieve contents, Step 2 to write the article based on the retrieved contents.
