### ISSUE TITLE
[Bug]: filename containing invalid characters to be used as docker image name

### ISSUE THREAD

**Issue by sonichi** [microsoft/autogen#1069]
### Describe the bug

https://github.com/microsoft/autogen/actions/runs/7338570361/job/19981290015?pr=925

The first line in the python block is:
`# filename: inequality.py (you can choose your own filename)`
The filename is parsed as `inequality.py (you can choose your own filename)` by:
https://github.com/microsoft/autogen/blob/d583ad833f6a92d5d86e42639db39157d8fb23ee/autogen/agentchat/conversable_agent.py#L1121
It then causes the error in https://github.com/microsoft/autogen/blob/d583ad833f6a92d5d86e42639db39157d8fb23ee/autogen/code_utils.py#L401-L402

### Steps to reproduce

call
`execute_code(filename="inequality.py (you can choose your own filename", use_docker=True, code="")`

### Expected Behavior

An error like https://github.com/microsoft/autogen/actions/runs/7338570361/job/19981290015?pr=925 should occur
at
https://github.com/microsoft/autogen/blob/d583ad833f6a92d5d86e42639db39157d8fb23ee/autogen/code_utils.py#L401-L402

### Screenshots and logs

https://github.com/microsoft/autogen/actions/runs/7338570361/job/19981290015?pr=925

### Additional Information

AutoGen Version: 0.2.2

**Comment by ekzhu** [comment]
Related to #1095. The input filename should be validated and the docker image name should be validated
