### ISSUE TITLE
[Issue]: Unable to Set Cache Directory in Read-Only File System Environments

### ISSUE THREAD

**Issue by alexpwrd** [microsoft/autogen#1074]
### Describe the issue

I am using the Autogen library in an AWS Lambda environment and I am encountering an issue related to the cache directory.

In AWS Lambda, the file system is read-only except for the /tmp directory. However, when I use the GPTAssistantAgent, UserProxyAgent, GroupChat, or GroupChatManager classes in the Autogen library, it seems that they are trying to create a cache directory at .cache/41, which is not writable in AWS Lambda. This results in an OSError: [Errno 30] Cache directory ".cache/41" does not exist and could not be created.

I tried to set the cache directory to /tmp using the Completion.set_cache(cache_path_root="/tmp") method, but it seems that the GPTAssistantAgent, UserProxyAgent, GroupChat, or GroupChatManager classes are creating their own instances of the Completion class, which use the default cache directory .cache.

Unfortunately, the Autogen library does not seem to provide a way to change the cache directory for these classes directly. I would like to ask if there is a way to set the cache directory for these classes to /tmp or if there is a workaround for this issue.

I would appreciate any assistance you could provide.

**Comment by rickyloynd-microsoft** [comment]
@sonichi

**Comment by sonichi** [comment]
try: `OpenAIWrapper.cache_path_root="/tmp"`
`Completion` is deprecated for openai>=1

**Comment by ekzhu** [comment]
This should be part of the llm_config, which we should use a typed class rather than a dict that user must guess it's schema.

**Comment by alexpwrd** [comment]
thanks @sonichi that resolved it

**Comment by TienShinhan-world** [comment]
@alexpwrd & @sonichi could you help me with my code below, please :

`from flask import Flask, request
import os
import autogen
from autogen import AssistantAgent, UserProxyAgent, GroupChat, GroupChatManager, Cache, OpenAIWrapper

app = Flask(__name__)

api_key = os.getenv('AZURE_OPENAI_API_KEY')
azure_endpoint = os.getenv('AZURE_OPENAI_API_ENDPOINT')
api_version = os.getenv('AZURE_OPENAI_API_VERSION')

config_list = [
    {
        "model": "gpt-4",
        "api_key": api_key,
        "api_type": "azure_openai",
        "azure_endpoint": azure_endpoint,
        "api_version": api_version
    }
]

llm_config = {
    "config_list": config_list
    }

class ResumableGroupChatManager(GroupChatManager):
    def __init__(self, groupchat, history, **kwargs):
        print("Initializing ResumableGroupChatManager with history:", history)
        # self.groupchat = groupchat
        if history:
            groupchat.messages = history        
        super().__init__(groupchat=groupchat, **kwargs)
        if history:
            self.restore_from_history(history)

    def restore_from_history(self, history) -> None:
        print("Restoring history...")
        self.groupchat.messages = history
        for message in history:
            print("Replaying message:", message)
            for agent in self.groupchat.agents:
                if agent != self:
                    print(f"Sending to {agent}: {message}")
                    self.send(message['content'], agent, request_reply=False)

@app.route('/query', methods=['POST'])
async def post_query():
    message = request.json.get("message")
    history = request.json.get("history", [])  # Default to an empty list if not provided
    print("Received message:", message)
    print("Received history:", history)
    
    with Cache.disk(cache_path_root="./temp/autogen_cache") as cache:
        assistant = autogen.AssistantAgent(
            name="assistant",
            llm_config=llm_config,
            system_message="You're a helpful assistant.\nIf you need more info, ask the user for anything missing."
        )
        user_proxy = autogen.UserProxyAgent(
            name="user_proxy",
            human_input_mode="NEVER",
            code_execution_config=False,
            is_termination_msg=lambda message: True  # Always True
        )
        weather_assistant = autogen.AssistantAgent(
            name="weather_assistant",
            llm_config=llm_config,
            max_consecutive_auto_reply=3,
            system_message="You're a helpful assistant to get the weather.\nYou ONLY say the weather in Paris is Hot, then return it."
        )    
        chitchat_assistant = autogen.AssistantAgent(
            name="chitchat_assistant",
            llm_config=llm_config,
            max_consecutive_auto_reply=3,
            system_message="You're a helpful assistant for chitchat. \n You answer user's questions about their day."
        )       

        groupchat = autogen.GroupChat(
            agents=[assistant, user_proxy, weather_assistant, chitchat_assistant],
            messages=[]
        )
        manager = ResumableGroupChatManager(
            name="Manager",
            groupchat=groupchat,
            history=history,
            llm_config=llm_config,
        )
        
        new_message = await user_proxy.a_initiate_chat(manager, message=message, clear_history=False, cache=cache)
        print('new_message: ', new_message)

        last_message_content = new_message.chat_history[-1]['content']

        print('last_message_content :', last_message_content)
        print("Final messages in groupchat:", groupchat.messages)

        return {
            "response": groupchat.messages[-1] if groupchat.messages else "No response generated",
            "history": groupchat.messages,
            # "history": new_message.chat_history,
        }

if __name__ == "__main__":
    app.run(debug=True)
`

**Comment by jonmadison-amzn** [comment]
this is still broken for Lambda deployments.  currently investigating.

Thought i had a workaround by monkey patching `Cache.disk` to no avail...

it's something to do with this hardcoded `LEGACY_CACHE_DIR` in the OpenAIWrapper.  If anyone knows offhand what else to look for let me know as i'm still relatively new to Python

**Comment by rritam94** [comment]
I'm having the same issue even with the provided solutions. Has anyone been able to fix it?
