### ISSUE TITLE
[Feature Request]: Allow a new agent join existed chat

### ISSUE THREAD

**Issue by deerleo** [microsoft/autogen#1079]
### Is your feature request related to a problem? Please describe.

Can Autogen allow a new agent join the conversation, interacting with other agents or human? 

### Describe the solution you'd like

Develop the ability to allow a new agent to join the conversation.

**Comment by rickyloynd-microsoft** [comment]
@afourney

**Comment by rajib76** [comment]
Adding my inputs based on the discord discussion.

Rajib — Yesterday at 10:06 PM
I have one question on Autogen and wanted to check if anyone can please clarify. Currently in the framework, we bring the required agents together through the GROUPCHAT abstraction. This GROUPCHAT abstraction currently is static , what I mean by that is I need to predefine the participants within the groupchat. If for example I need to add or remove another assistant in the groupchat, it is not possible without changing the code. Is my understanding correct? If my understanding is correct will making the GROUPCHAT event driven(leveraging for example Kafka) will make it more dynamic?

sonichi — Today at 8:39 AM
Could you give an example of the use case?

Rajib — Today at 11:36 AM
So, it is similar to an event driven architecture. For example lets say I have three agents MATH, PHYSICS and CHEMISTRY. Each of them is capable to consuming an event from kafka and producing an event in kafka. The user proxy asks a question which based on the question classification(lets say it is a MATHS question) goes into the MATH topic. The MATH agent listening to that topic picks up the question and answers it. The answer is then produced in a topic from where the user proxy can consume and send back to the user.

**Comment by rysweet** [comment]
@deerleo @rajib76 - check out the new event-driven autogen 0.4
