### ISSUE TITLE
Infinite Loops

### ISSUE THREAD

**Issue by adriangalilea** [microsoft/autogen#108]
Hello,

https://github.com/JayZeeDesign/microsoft-autogen-experiments/blob/main/content_agent.py

I got a few instances of infinite loops running the above with gpt4.

- An agent, if I recall correctly the admin would start sending blank messages.
- OpenAI rate limit triggered.
- A bunch of calls for no reason 💸 

Don't have the logs sorry.

**Comment by adriangalilea** [comment]
```
--------------------------------------------------------------------------------

>>>>>>>> USING AUTO REPLY...
admin (to chat_manager):



--------------------------------------------------------------------------------

>>>>>>>> USING AUTO REPLY...
admin (to chat_manager):



--------------------------------------------------------------------------------

>>>>>>>> USING AUTO REPLY...
admin (to chat_manager):



--------------------------------------------------------------------------------

>>>>>>>> USING AUTO REPLY...
admin (to chat_manager):



--------------------------------------------------------------------------------

>>>>>>>> USING AUTO REPLY...
admin (to chat_manager):



--------------------------------------------------------------------------------

>>>>>>>> USING AUTO REPLY...
admin (to chat_manager):



--------------------------------------------------------------------------------

>>>>>>>> USING AUTO REPLY...
admin (to chat_manager):



--------------------------------------------------------------------------------

>>>>>>>> USING AUTO REPLY...
admin (to chat_manager):



--------------------------------------------------------------------------------

>>>>>>>> USING AUTO REPLY...
admin (to chat_manager):



--------------------------------------------------------------------------------
[autogen.oai.completion: 10-04 22:44:34] {237} INFO - retrying in 10 seconds...
Traceback (most recent call last):
  File "/Users/adrian/Developer/microsoft-autogen-experiments/venv/lib/python3.11/site-packages/autogen/oai/completion.py", line 209, in _get_response
    response = openai_completion.create(request_timeout=request_timeout, **config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adrian/Developer/microsoft-autogen-experiments/venv/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adrian/Developer/microsoft-autogen-experiments/venv/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/Users/adrian/Developer/microsoft-autogen-experiments/venv/lib/python3.11/site-packages/openai/api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adrian/Developer/microsoft-autogen-experiments/venv/lib/python3.11/site-packages/openai/api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "/Users/adrian/Developer/microsoft-autogen-experiments/venv/lib/python3.11/site-packages/openai/api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: Rate limit reached for default-gpt-4 in organization [REDACTED] on tokens per min. Limit: 40000 / min. Please try again in 1ms. Contact us through our help center at help.openai.com if you continue to have issues.

```

**Comment by LittleLittleCloud** [comment]
@adriangalilea You are exposing an API key from your repo

**Comment by adriangalilea** [comment]
I think you are refering to this: 
https://github.com/JayZeeDesign/microsoft-autogen-experiments/issues/1

It's the original user which I notified and disabled the API keys,

Thank you tho.

**Comment by adriangalilea** [comment]
Btw identified another instance of this:

```
(Note: The blog content has been generated based on the given prompts and has been tweaked to provide a concise step-by-step guide. TERMINATE)

--------------------------------------------------------------------------------
admin (to chat_manager):



--------------------------------------------------------------------------------
admin (to chat_manager):
```

I think the problem is this:

```Python
user_proxy = autogen.UserProxyAgent(
        name="User_proxy",
        code_execution_config={"last_n_messages": 2, "work_dir": "coding"},
        is_termination_msg=lambda x: x.get("content", "") and x.get(
            "content", "").rstrip().endswith("TERMINATE"),
        human_input_mode="NEVER",
        function_map={
            "search": search,
            "scrape": scrape,
        }
    )
```

The endswith part.

**Comment by LittleLittleCloud** [comment]
Yes you are right. the `is_termination_msg` asking for an exact match of `TERMINATE` but admin replies `(...TERMINATE)` or `Terminate.`

@sonichi We would need a more robust method to terminate the chat. How about making it a terminate function for admin to call via `function_call`

**Comment by adriangalilea** [comment]
> Yes you are right. the `is_termination_msg` asking for an exact match of `TERMINATE` but admin replies `(...TERMINATE)` or `Terminate.`
> 
> @sonichi We would need a more robust method to terminate the chat. How about making it a terminate function for admin to call via `function_call`

Do you happen to have any example at hand?

**Comment by LittleLittleCloud** [comment]
@adriangalilea haven't yet. I can create a demo example in #102 to give it a try though.

In the meantime, after a closer look, it seems that the empty message is because `admin` doesn't have a `llm_config`, so it uses its `default_reply` which is an empty string.

**Comment by adriangalilea** [comment]
@LittleLittleCloud Hello,

I've been trying to search for documentation of the llm_config and I didn't find much helpful information.

What would you say it's a good `default_reply` to avoid these kind of errors?

Also, by a terminate function you mean a function that simply outputs TERMINATE?

Thank you so much!

**Comment by afourney** [comment]
FWIW, we've been using:

```
is_termination_msg = lambda x: True if "TERMINATE" in x.get("content") else False,
```

This helps a little with the exact match, or ends with "TERMINATE" problem. 

Finding a more robust means of detecting termination is definitely on our to-do list!

**Comment by adriangalilea** [comment]
There's the chance of it stopping if for whatever reason TERMINATE appears, I think the function approach might be less error prone   at the cost of some context but not sure how to build it, waiting for that example.

**Comment by LittleLittleCloud** [comment]
Not in this case. The group chat will be terminated only when user_proxy replies ‘TERMINATE’. Considering that user_proxy in this example is not backed by LLM and will always return the default message, which is TERMINATE. This makes the exit check logic here quite robust 

things will be different when user_proxy is powered by an LLM, where a function call to finish a group chat would be a preferred way to go. Let me come up with an example on that scenario

**Comment by adriangalilea** [comment]
@LittleLittleCloud oh wow I missed your previous message, will be testing it out, thank you so much.

**Comment by LittleLittleCloud** [comment]
@adriangalilea Yes I'm on discord. I'm the one who respond to you and ask if you could create an issue on github

**Comment by LittleLittleCloud** [comment]
If this issue get resolved I am going to close it. Feel free to reopen it if you have further questions
