### ISSUE TITLE
[Feature Request]: Context window support

### ISSUE THREAD

**Issue by deerleo** [microsoft/autogen#1080]
### Is your feature request related to a problem? Please describe.

In a story writing context, it is important to maintain the context window so would not trigger max token limit. 

### Describe the solution you'd like

1. In a long text generation scene the autogen can automatically handle the context window. Auto summarize it when it reaches the max token limitation. 
2. Provide functions to control which message should be kept in memories.  Can defined the message priorities.

**Comment by rickyloynd-microsoft** [comment]
@kevin666aa  Would you like to add this to #156, or is it redundant?

**Comment by deerleo** [comment]
> redundant

Thanks for your attention. 
It's not quite similar with that issue. My goal is to develop a group chat to write articles, make videos. Mainly focus on creations. So I think it requires a bit of more work then just add some summary method or retrieval method. How to update the task goal and important info, how to assign task to each agent, rather then sending all messages to all agents.

**Comment by thinkall** [comment]
@deerleo 1.) should be already addressed. 2.) you can register a customized reply function in which you modifies the chat history.
