### ISSUE TITLE
[Bug]:  Using the dall-e 3 notebook example code, the request data is too large.

### ISSUE THREAD

**Issue by deerleo** [microsoft/autogen#1087]
### Describe the bug

I tried to integrate the dalle-3 example code to my groupchat bot,  (https://github.com/microsoft/autogen/blob/main/notebook/agentchat_dalle_and_gpt4v.ipynb), 
but after the dalle agent replied with img data in base64 format, the next request encounter an error sad request data too large. 
I think it's because the autogen push the reply data of base64 img to message list, in the next request, there will be a large request body. 

How to exclude some message or truncate it in the group chat? 

![autogen-dalle-error](https://github.com/microsoft/autogen/assets/1190377/57ccf92c-f6fe-4a14-b450-aedd03c6cf86)

**Comment by rickyloynd-microsoft** [comment]
@kevin666aa

**Comment by kevin666aa** [comment]
Hello @deerleo, when you are creating dalle agent, are you using your own customized agents? A quick solution is to process the image in the customized registered reply function. You will take out the image and return a message like: "Placeholder for Image".

**Comment by sonichi** [comment]
@BeibinLi

**Comment by BeibinLi** [comment]
@deerleo  Thanks for the feedback. The recent truncate update might interfere with how we handle LMM. 

I will take a deeper look into this.

**Comment by BeibinLi** [comment]
@deerleo  Can you check: https://github.com/microsoft/autogen/pull/1124 

Also, can you make the chat_manager a MultimodalAgent instead of a conversable agent?

**Comment by afourney** [comment]
@BeibinLi I don't think there is a MultimodalGroupChat?

You can add groupchat manager capabilities to any agent via [registration](https://github.com/microsoft/autogen/blob/1508f53eddd54421a3ee2467b03d437216951bbf/test/agentchat/test_groupchat.py#L232-L259), but I suspect the problem lies with the GroupChat class that handles the orchestration.

**Comment by BeibinLi** [comment]
@afourney Got it. You are correct. I just added an issue (https://github.com/microsoft/autogen/issues/1142) regarding MultimodalGroupChat. I will create a MultimodalGroupChat under the multimodal features.
