### ISSUE TITLE
Put all the tests requiring openai in one place and skip/run them in the pytest command in the workflow

### ISSUE THREAD

**Issue by sonichi** [microsoft/autogen#1088]
In future, we can put all the tests requiring openai in one place and skip/run them in the pytest command in the workflow, instead of skipping each test based on whether openai is installed.

_Originally posted by @sonichi in https://github.com/microsoft/autogen/pull/1052#discussion_r1435895008_

**Comment by sonichi** [comment]
Also see @maxim-saplin's followup comment

**Comment by maxim-saplin** [comment]
I would break it down in 2 parts:
- [] **support `--skip-openai` pytest argument** to allow skipping all tests that depend on OpenAI API endpoints
- [] **consolidate all model endpoints** used by tests in a single file and make sure tests only use models available through that file

**Comment by afourney** [comment]
There may be other requirements that incur similar constraints. E.g., some agents might need the Bing API Key. Others might need access to some non-standard dependencies, etc. Whatever we do we should ensure the design is extensible.
