### ISSUE TITLE
We should make another PR to document the contrib and contrib-openai workflows

### ISSUE THREAD

**Issue by sonichi** [microsoft/autogen#1089]
We should make another PR to document the contrib and contrib-openai workflows @rickyloynd-microsoft @thinkall @BeibinLi @kevin666aa @IANTHEREAL @gagb @afourney

_Originally posted by @sonichi in https://github.com/microsoft/autogen/pull/1052#discussion_r1435894101_

Also see @maxim-saplin's followup comment

**Comment by rysweet** [comment]
has been documented on website and in docs
