### ISSUE TITLE
[Feature Request]: migrate clear_cache in completion.py to client.py

### ISSUE THREAD

**Issue by sonichi** [microsoft/autogen#1094]
### Is your feature request related to a problem? Please describe.

We used to support clear caching in `Completion` for openai<1.
This feature is missing in `OpenAIWrapper` for openai>=1.
There have been questions from discord about this.

### Describe the solution you'd like

Add a `clear_cache` method in `OpenAIWrapper`.

**Comment by rysweet** [comment]
closing as stale please reopen if you intend to work on this.
