### ISSUE TITLE
[Feature Request]: Use Pydantic models for `llm_configs`, `config_list` and `code_execution_config`

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#1095]
### Is your feature request related to a problem? Please describe.

Right now, `config_list`, `llm_configs` and `code_execution_config` are dictionaries, and the schema of these dictionaries are enforced through parser functions. 

### Describe the solution you'd like

A better way to handle this would be to use Pydantic models so parsing, serializing and data validations are handled by Pydantic. This also address many issues related to invalid configs.

### Additional context

[Pydantic](https://docs.pydantic.dev/latest/)

Example of Pydantic models already used in our repo: https://github.com/microsoft/autogen/blob/main/autogen/function_utils.py

Existing issues to address data validation:
https://github.com/microsoft/autogen/pull/1082
https://github.com/microsoft/autogen/pull/1026
https://github.com/microsoft/autogen/issues/1074
#1069

**Comment by afourney** [comment]
Arguably I would add `code_execution_config` to that as well.
