### ISSUE TITLE
[Bug]: Only the arm64 docker image is published to dockerhub

### ISSUE THREAD

**Issue by gemmell** [microsoft/autogen#1096]
### Describe the bug

I went to try this out via the easy route as per the instructions:
```
docker pull yuandongtian/autogen:latest
docker run -it -e OPENAI_API_KEY=$OPENAI_API_KEY -p 8081:8081 docker.io/yuandongtian/autogen:latest
```

But only the arm64 image is published, meaning it doesn't run on regular intel machines:
```
$ docker run -it -e OPENAI_API_KEY=$OPENAI_API_KEY -p 8081:8081 docker.io/yuandongtian/autogen:latest
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v4) and no specific platform was requested
exec /venv/bin/autogenra: exec format error
```

And if you look in dockerhub, sure enough, there really is just one architecture supported: `linux/arm64/v8`
https://hub.docker.com/r/yuandongtian/autogen/tags

Need to use docker buildx to cross compile for other architectures.

 

### Steps to reproduce

Try and run the docker image on a intel linux machine.

### Expected Behavior

It runs the docker image.

**Comment by rickyloynd-microsoft** [comment]
@sonichi

**Comment by sonichi** [comment]
@qingyun-wu could you take a look at this issue? I think it's a good idea to provide a quick start point using docker, but the current guidance is incomplete in several aspects: 
1. How to use the docker image in non-web UI interface. 
2. What architecture is supported. 
3. What's the plan to support other architectures.

**Comment by yuandong-tian** [comment]
Hi all, 

I added the docker image and here is the Dockerfile that builds this docker image. We can build the docker under more architectures. 

```
FROM python:3.11-slim

RUN : \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        software-properties-common \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        python3-venv \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && :

RUN python3 -m venv /venv
ENV PATH=/venv/bin:$PATH
EXPOSE 8081

RUN cd /venv; pip install pyautogen autogenra
RUN pip install yfinance numpy scipy matplotlib pandas
RUN pip install beautifulsoup4

ENTRYPOINT ["autogenra", "ui", "--host", "0.0.0.0"]
```

**Comment by qingyun-wu** [comment]
> @qingyun-wu could you take a look at this issue? I think it's a good idea to provide a quick start point using docker, but the current guidance is incomplete in several aspects:
> 
> 1. How to use the docker image in non-web UI interface.
> 2. What architecture is supported.
> 3. What's the plan to support other architectures.

Sure. I will add a corresponding documentation page about this.

**Comment by gemmell** [comment]
If you want some flexibility, highly recommend you set your `ENTRYPOINT` to autogen, and then use `CMD` for the rest. 

That way you can override the command line parameters when you do `docker run` to provide other startup conditions.

https://stackoverflow.com/q/21553353/1284610
