### ISSUE TITLE
_replace is potentially useful in general which can be moved to code_utils.

### ISSUE THREAD

**Issue by sonichi** [microsoft/autogen#11]
This function is potentially useful in general which can be moved to code_utils.

_Originally posted by @sonichi in https://github.com/microsoft/FLAML/pull/1147#discussion_r1276945171_

**Comment by otutsukihyuuga** [comment]
Do u still want to complete this issue? Can u assign it to me if u do need the function to be migrated

**Comment by sonichi** [comment]
@BeibinLi could you please comment?

**Comment by otutsukihyuuga** [comment]
@sonichi it seems that @BeibinLi hasnt replied till now. What should I do?

**Comment by sonichi** [comment]
It probably means that this is not valid any more. Could you find another issue to work on?
I'll close it for now.
