### ISSUE TITLE
[Issue]: test in `contrib-tests.yml` should also use `--skip-openai` to skip the openai test

### ISSUE THREAD

**Issue by LinxinS97** [microsoft/autogen#1112]
### Describe the issue

Test in `contrib-tests.yml` should also use `--skip-openai` instead of `pip uninstall -y openai` to skip the openai test.

This issue is related to #1088 and #1097

**Comment by sonichi** [comment]
I agree. @maxim-saplin for awareness.

**Comment by maxim-saplin** [comment]
> I agree. @maxim-saplin for awareness.

Will take care of the PR
