### ISSUE TITLE
No code or files saved when using non-GPT model

### ISSUE THREAD

**Issue by raynic35** [microsoft/autogen#1114]
Hi,
not sure if it is a bug or im missing something, but everytime im using a non-GPT model as a model for an Agent(User-Proxy or Assistent), no code is saved and also no other files are created when requested in the message. So far i only tried orca2 and codellama models. Using GPT-4, it works fine. What can i try  that this also works with other models?
Thank you,
Ray

**Comment by rickyloynd-microsoft** [comment]
@victordibia

**Comment by victordibia** [comment]
This is an important question.
In general, AutoGen relies on models following instructions on how to generate responses. 

For example, see the default system message for an[ assistant agent](https://github.com/microsoft/autogen/blob/d20bc09cba4f67ea0e6d32818ee66dd3b3513c0c/autogen/agentchat/assistant_agent.py#L17). 

- code execution - the system message expects code in ``` blocks. When this is not done correctly,  code is not extracted or saved.
- also the system message indicates the LLM must add some headers to extracted code and files for them to be executed. 

Smaller models in general do not follow instructions as well as larger models like GPT3.5/4.
One solution is to explore models that are better at writing code or finetuned for similar purposes. Mistral models and derivates (e.g., Zephyr) are good starting points.
