### ISSUE TITLE
How to run multiple local LM's?

### ISSUE THREAD

**Issue by matsuobasho** [microsoft/autogen#1115]
### Describe the issue

One powerful feature of Autogen is the ability to assign different agents to use specific LMs.  Is there a way to run multiple local LMs simultaneously?  

I see the guidance in [this ](https://microsoft.github.io/autogen/blog/2023/07/14/Local-LLMs) tutorial, but my understanding is that the `oai.ChatCompletion.create` API has been deprecated.

I also saw #237 , but this seems similar to the way I'm currently running Autogen using LMStudio - starting a server for a specific model.   

So is there a way to run multiple local language models?

**Comment by sonichi** [comment]
The same method works but the syntax needs to be migrated according to https://microsoft.github.io/autogen/docs/Installation#migration-guide-to-v02
@LeoLjl for awareness.

**Comment by matsuobasho** [comment]
Thanks @sonichi.  I referred back to the blog [post ](https://microsoft.github.io/autogen/blog/2023/07/14/Local-LLMs/) and started from the top, trying to first get one model to work on a server.  

I git cloned FastChat and installed all the libraries it uses.  Then proceeded to download a model from HuggingFace.

I ran `python -m fastchat.serve.controller` successfully.
Then when I run `python -m fastchat.serve.model_worker --model-path path_to_hf_model`  I get error:
`AssertionError: Torch not compiled with CUDA enabled`

This doesn't seem to be the error referenced in [here](https://github.com/lm-sys/FastChat/issues/1641).

I'm running on Windows with CPU, so can't use CUDA.

**Comment by ekzhu** [comment]
This seems like an error related to torch installation. Have you tried re-install torch?

**Comment by LeoLjl** [comment]
> Thanks @sonichi. I referred back to the blog [post ](https://microsoft.github.io/autogen/blog/2023/07/14/Local-LLMs/) and started from the top, trying to first get one model to work on a server.
> 
> I git cloned FastChat and installed all the libraries it uses. Then proceeded to download a model from HuggingFace.
> 
> I ran `python -m fastchat.serve.controller` successfully. Then when I run `python -m fastchat.serve.model_worker --model-path path_to_hf_model` I get error: `AssertionError: Torch not compiled with CUDA enabled`
> 
> This doesn't seem to be the error referenced [here](https://github.com/lm-sys/FastChat/issues/1641).
> 
> I'm running on Windows with CPU, so can't use CUDA.

Did you try adding '--device cpu' to the argument? `python -m fastchat.serve.model_worker --model-path path_to_hf_model --device cpu`

**Comment by mferris77** [comment]
As far as I'm aware, LM Studio runs a single model at a time and you can't switch/choose based on the incoming request like you can with OpenAI (gpt-4 vs gpt-3.5-turbo, etc).  I haven't had a chance to try it yet but Ollama supposedly allows you to run multiple LLMs at the same time.  I'd have to go back and watch the demo video from Matt Berman on youtube but I think you basically run an endpoint for each LLM you want available.  Either way, he was able to run two models locally and then was able to interact with both of them with no noticeable delay beyond what's to be expected of running a local LLM.

**Comment by matsuobasho** [comment]
@LeoLjl thanks for that suggestion, that takes care of that problem.

However, I now encounter an error on the `python -m fastchat.serve.openai_api_server --host localhost --port 8000` [step](https://microsoft.github.io/autogen/blog/2023/07/14/Local-LLMs/).
I also did try commenting out the `finish_reason` line as per the tutorial:

Here is the error:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Bob\Documents\Programming\FastChat\fastchat\serve\openai_api_server.py", line 24, in <module>
    from pydantic import BaseSettings
  File "C:\Users\Bob\.virtualenvs\FastChat-c0Sws4L0\Lib\site-packages\pydantic\__init__.py", line 363, in __getattr__
    return _getattr_migration(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bob\.virtualenvs\FastChat\Lib\site-packages\pydantic\_migration.py", line 296, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.5/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.5/u/import-error
```

@mferris77 , thanks for the suggestion of Berman's video on running multiple open-source lms with LLama.  Unfortunately, I'm on Windows so unable to use that method.

**Comment by LeoLjl** [comment]
@matsuobasho This seems like a typical pydantic version mismatch, I'm not sure how to solve it. I can provide you with a list of package version that works well on my end.
`pydantic==1.10.12
uvicorn==0.23.2
fastapi==0.101.1
nest-asyncio==1.5.1
aiohttp==3.8.4
httpx==0.24.1`

**Comment by mferris77** [comment]
I am on windows as well. You just have to run ollama (and LiteLLM to provide the API) in WSL. It actually runs quite well now that I have it set up. Sent from my iPhoneOn Jan 3, 2024, at 2:28 PM, matsuobasho ***@***.***> wrote:﻿
@LeoLjl thanks for that suggestion, that takes care of that problem.
However, I now encounter an error on the python -m fastchat.serve.openai_api_server --host localhost --port 8000 step.
I also did try commenting out the finish_reason line as per the tutorial:
Here is the error:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Bob\Documents\Programming\FastChat\fastchat\serve\openai_api_server.py", line 24, in <module>
    from pydantic import BaseSettings
  File "C:\Users\Bob\.virtualenvs\FastChat-c0Sws4L0\Lib\site-packages\pydantic\__init__.py", line 363, in __getattr__
    return _getattr_migration(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bob\.virtualenvs\FastChat\Lib\site-packages\pydantic\_migration.py", line 296, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.5/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.5/u/import-error
@mferris77 , thanks for the suggestion of Berman's video on running multiple open-source lms with LLama.  Unfortunately, I'm on Windows so unable to use that method.

**Comment by matsuobasho** [comment]
@LeoLjl I resolved the pydantic issues (had to modify the syntax a little because `BaseSettings` is moved to a separate `pydantic-settings` package in v.2).

So I'm able to run 
`python -m fastchat.serve.openai_api_server --host localhost --port 8000`

CLI logs state that `Uvicorn running on http://localhost:8000`

So should I now be able to run something like the following?

```python
config_list = [
    {
        "base_url": "http://localhost:8000",
        "api_key": "NULL"
    }
]

llm_config = {
    "timeout": 600,
    "seed": 42,
    "config_list": config_list,
    "temperature": 0
}

assistant = autogen.AssistantAgent(
    name="assistant",
    system_message="you are a coder specializing in Python.",
    llm_config=llm_config
)

user_proxy = autogen.UserProxyAgent(
    name="user_proxy",
    human_input_mode="NEVER",
    max_consecutive_auto_reply=10,
    is_termination_msg=lambda x: x.get("content", "").rstrip().endswith("TERMINATE"),
    code_execution_config={"work_dir": "web"},
    llm_config=llm_config,
    system_message="""Reply TERMINATE if the task has been solved at full satisfaction.
    Otherwise, reply CONTINUE, or the reason why the task is not yet solved."""
)

task = """
Write me a summary of this article: https://reason.org/aviation-policy-news/faa-safety-review-reveals-air-traffic-control-dysfunction/
"""

user_proxy.initiate_chat(
    assistant,
    message=task
)
```

Currently get an error
`NotFoundError: Error code: 404 - {'detail': 'Not Found'}`

**Comment by Leekinxun** [comment]
> @LeoLjl I resolved the pydantic issues (had to modify the syntax a little because `BaseSettings` is moved to a separate `pydantic-settings` package in v.2).
> 
> So I'm able to run `python -m fastchat.serve.openai_api_server --host localhost --port 8000`
> 
> CLI logs state that `Uvicorn running on http://localhost:8000`
> 
> So should I now be able to run something like the following?
> 
> ```python
> config_list = [
>     {
>         "base_url": "http://localhost:8000",
>         "api_key": "NULL"
>     }
> ]
> 
> llm_config = {
>     "timeout": 600,
>     "seed": 42,
>     "config_list": config_list,
>     "temperature": 0
> }
> 
> assistant = autogen.AssistantAgent(
>     name="assistant",
>     system_message="you are a coder specializing in Python.",
>     llm_config=llm_config
> )
> 
> user_proxy = autogen.UserProxyAgent(
>     name="user_proxy",
>     human_input_mode="NEVER",
>     max_consecutive_auto_reply=10,
>     is_termination_msg=lambda x: x.get("content", "").rstrip().endswith("TERMINATE"),
>     code_execution_config={"work_dir": "web"},
>     llm_config=llm_config,
>     system_message="""Reply TERMINATE if the task has been solved at full satisfaction.
>     Otherwise, reply CONTINUE, or the reason why the task is not yet solved."""
> )
> 
> task = """
> Write me a summary of this article: https://reason.org/aviation-policy-news/faa-safety-review-reveals-air-traffic-control-dysfunction/
> """
> 
> user_proxy.initiate_chat(
>     assistant,
>     message=task
> )
> ```
> 
> Currently get an error `NotFoundError: Error code: 404 - {'detail': 'Not Found'}`

I also encountered the same problem, autogen has no reaction to this base_url.Have you solved this problem now？

**Comment by LeoLjl** [comment]
@matsuobasho @Leekinxun If you are using openai<1, try changing 'base_url' to 'api_base'.

**Comment by matsuobasho** [comment]
@LeoLjl I'm not using openai <1.  I didn't see the purpose of installing an outdated version of the library with deprecated syntax.  Should I be?

**Comment by LeoLjl** [comment]
@matsuobasho There is no need. I was using openai<1 when writing the blog.

**Comment by matsuobasho** [comment]
This is what I see from the logs after I launch the code referenced above:

```
2024-01-10 10:41:34 | INFO | model_worker | Register to controller
2024-01-10 10:41:34 | ERROR | stderr | INFO:     Started server process [17640]
2024-01-10 10:41:34 | ERROR | stderr | INFO:     Waiting for application startup.
2024-01-10 10:41:34 | ERROR | stderr | INFO:     Application startup complete.
2024-01-10 10:41:34 | ERROR | stderr | INFO:     Uvicorn running on http://localhost:21002 (Press CTRL+C to quit)
2024-01-10 10:41:42 | INFO | stdout | INFO:     ::1:51819 - "POST /chat/completions HTTP/1.1" 404 Not Found
```

**Comment by YinSonglin1997** [comment]
> @matsuobasho @Leekinxun If you are using openai<1, try changing 'base_url' to 'api_base'. Also check fastchat server logs to see if the server is receiving any connections.

it works, thank you.
