### ISSUE TITLE
[Issue]: When I use GPTAssistantAgent to generate a file, how do I get the file id?

### ISSUE THREAD

**Issue by scortLi** [microsoft/autogen#1138]
### Describe the issue

If you generate an image and it prints the file id if you generate a csv file and there is no file id printed out, I guess the wrapped GPTAssistantGPT did not print, then how do I get this file id and download it to the local through this file id

**Comment by victordibia** [comment]
One thing you can do is to monitor the working directory that the agent uses. 
You can conclude that any new files   generated during this period was created   as part of the code execution by the agent.
AutoGen studio uses this [approach](def get_modified_files() to determine which files were created and shows them to the user. 



![Image](https://github.com/microsoft/autogen/assets/1547007/5ba5c660-bb2a-431f-b15f-54d36aa384df)

**Comment by lihui123456** [comment]
@victordibia @rickyloynd-microsoft  thanks  

I modified the GPTAssistantAgent class to get the file id
