### ISSUE TITLE
Issue with 'config_list_from_json'

### ISSUE THREAD

**Issue by jake-burton** [microsoft/autogen#1141]
### Describe the issue

I ran 'pip install --upgrade autogen openai' in terminal in hopes of fixing an unrelated issue. Ran the script again and now I'm getting a "no attribute 'config_list_from_json'" error. Anyone know what could be going on?

### Steps to reproduce

import autogen
from web_scraping import web_scrape

config_list_oai = autogen.config_list_from_json(env_or_file="OAI_CONFIG_LIST")

agent_config = {
    "config_list": config_list_oai, 
    "cache_seed": 42,
    "functions": [
        {
            "name": "web_scrape",
            "description": "Search online via the googlesearch for information later than , if the information could be present in a time after the language model was trained, or if research needs to be conducted, move on if a url is taking too long.",
            "parameters": {
                "type": "object",
                "required": [
                    "google_query"
                ],
                "properties": {
                    "google_query": {
                        "type": "string",
                        "description": "The user's search query term. The term may not be empty."
                    }
                }
            }
        }
    ]
}

termination_msg = lambda x: isinstance(x, dict) and "TERMINATE" == str(x.get("content", ""))[-9:].upper()

assistant = autogen.AssistantAgent(
    name="assistant",
    llm_config=agent_config,
)

user_proxy = autogen.UserProxyAgent(
    name="user_proxy",
    human_input_mode="NEVER",
    max_consecutive_auto_reply=10,
    is_termination_msg=lambda x: x.get("content", "").rstrip().endswith("TERMINATE"),
    code_execution_config={
        "work_dir": "coding",
        "use_docker": False,  # set to True or image name like "python:3" to use docker
    },
)

for agent in [user_proxy, assistant]:
        # register functions for agents.
        agent.register_function(
            function_map={
               "web_scrape": web_scrape
            }
        )

task="""
say hello world
"""

user_proxy.initiate_chat(assistant, message=task)

### Screenshots and logs

Desktop/Tax Strategy/main.py"
Traceback (most recent call last):
  File "/Users/mikaylamathews/Desktop/Tax Strategy/main.py", line 4, in <module>
    config_list_oai = autogen.config_list_from_json(env_or_file="OAI_CONFIG_LIST")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'autogen' has no attribute 'config_list_from_json'

### Additional Information

autogen v0.2.2
python 3.11.5

**Comment by afourney** [comment]
you want to install the "pyautogen" library.  Unfortunately, "autogen" is something else.

**Comment by jake-burton** [comment]
right right, thank you!!

**Comment by afourney** [comment]
No problem. Happy to help!

**Comment by teachable-david** [comment]
pyautogen is upgraded, but I am receiving the same error still:

AttributeError: module 'autogen' has no attribute 'config_list_from_json'

here is the code:

###

import autogen
import json


filter_criteria = {"model": ["lmstudio"]}


config_list = autogen.config_list_from_json(
    env_or_file=".../OAI_CONFIG_LIST.json",
    filter_dict=filter_criteria
)


print(config_list)

assistant = autogen.AssistantAgent(
    name="Assistant Agent",
    llm_config={
        "cache_seed": 43,
        "temperature": 0.7,
        "config_list": config_list
    }
)


user = autogen.UserProxyAgent(
    name="User",
    human_input_mode="ALWAYS",
    is_termination_msg=lambda x: x.get("content", "").rstrip().endswith("TERMINATE"),
    code_execution_config={
        "work_dir": "coding",
        "use_docker": False
    }
)

message = """

Hi there! Please reply with vulgarities.

"""

###

I omitted my file structure, but the path to the config is appropriately stated.

**Comment by parimalamrao** [comment]
getting the same error unable to fix it

**Comment by HadiBoukdir** [comment]
Hi Guys, if you still have the same issue, you must uninstall autogen (NOT pyautogen) from both virtual environment and your machine, then install pyautogen then the issue should be resolved
