### ISSUE TITLE
MultimodalGroupChat

### ISSUE THREAD

**Issue by BeibinLi** [microsoft/autogen#1142]
### Is your feature request related to a problem? Please describe.

The group chat does not work well with multimodal agents, because the group chat manager could not parse image information.

Related Issues:
https://github.com/microsoft/autogen/issues/1087

**Comment by afourney** [comment]
@BeibinLi we should also consider what a universal solution would be here. E.g., similar to #1129, it would be nice if we had a layer somewhere that allowed messages that AutoGen uses diverge from the messages we send to the LLM (e.g., passing only a subset of the fields). This would also help with instrumentation (Cheng is working on that).

**Comment by BeibinLi** [comment]
#1926
