### ISSUE TITLE
[Issue]: Getting error while installing pip install autogenstudio

### ISSUE THREAD

**Issue by amitlals** [microsoft/autogen#1148]
### Describe the issue

Receiving error while running pip install -U autogenstudio

pip show pyautogen   --- No pyautogen install yet
WARNING: Package(s) not found: pyautogen

### Screenshots and logs

![image](https://github.com/microsoft/autogen/assets/37605691/3c541e00-074d-4fb5-ab49-9b71b087fb36)

### Additional Information

I'm using Python 3.12 version and tried 3.11 too, same error.

_No response_

**Comment by rickyloynd-microsoft** [comment]
@victordibia

**Comment by afourney** [comment]
FYI: Chi just pushed 0.2.3. @victordibia I'm curious as to why the requirement is pinned to "pyautogen==0.2.0"?

**Comment by victordibia** [comment]
True.  It’s more of a testing artifact, nothing else.  Current features have been tested with 0.2.0. A future update should address this.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by amitlals** [comment]
> @amitlals ,
> 
> The error message you have suggest that you might have a different version of pyautogen installed than what autogenstudio requires (v - 0.2.0). Two potential options
> 
> * uninstall pyautogen and reinstall autogenstudio
> * create a new virtual env using conda and install autogenstudio
> 
> Let me know if that is helpful

Thanks for your response. Unfortunately it didn't work as suggested, I removed pyautogen and autogenstudio, you can see the screenshot, no package found prior to pip install execution. When I ran in my conda env. setup with python 3.11, still same error.  please advise if something is missing here?

![image](https://github.com/microsoft/autogen/assets/37605691/06b4f78c-30d1-4387-a421-54e5a0f31a0d)

**Comment by victordibia** [comment]
Can you try this with python 3.10, just to rule out a python version mismatch. Can you do the following

- Create and activate a new conda environment with python=3.10 
- pip install -U autogenstudio.

Also, autogen requires [python < 3.12 ](https://github.com/microsoft/autogen/blob/871e9e28b3c4d26d292b865fecb729de675abc2f/setup.py#L63)so we definitely should not be using python 3.12. 

@afourney, any chance this might be a windows related env issue?

**Comment by amitlals** [comment]
I attempted with Python 3.10 again, after re-installing conda. It seems some version conflict autogenstudio and pyautogen version, might required a fix in source.

![image](https://github.com/microsoft/autogen/assets/37605691/d80ab66b-ffc3-453a-a0a8-6e782de1ab43)

**Comment by victordibia** [comment]
Thanks for sharing your updates.
The screenshot you have above suggests you are installing pyautogen ie. `pip install pyautogen` install of running `pip install autogenstudio`

What happens when you follow the instructions above as suggested.

```bash
# Create and activate a new conda environment with python=3.10
pip install -U autogenstudio.
```

note that pip install autogenstudio will install the required version of pyautogen

**Comment by amitlals** [comment]
after running pip install autogenstudio, I am running 

```pip install -e .```

It is automatically calling pyautogen as part of packaging the bundle, perhaps I was able to run autogenstudio now. 

![image](https://github.com/microsoft/autogen/assets/37605691/2d47ecbf-6419-4767-973c-36320dc9e3bf)
