### ISSUE TITLE
Cost, time estimate / task , pls

### ISSUE THREAD

**Issue by flckv** [microsoft/autogen#115]
Hi, thank you for sharing. Maybe others can benefit from having an idea about how much the prebuilt example notebooks would cost. Can you put that in the jupyter documentation?

**Comment by afourney** [comment]
That's a great idea. It will of course vary depending on stochasticity of the LLM responses (which we can mitigate with temperature), but it should be possible to at least report the tokens consumed in the particular traces that are shown in the notebooks etc.

**Comment by sonichi** [comment]
The newly added [`print_usage_summary`](https://microsoft.github.io/autogen/docs/Use-Cases/enhanced_inference#logging-experimental) could be used for doing this now.
