### ISSUE TITLE
Struggling to use autogen studio using Azure Open AI 

### ISSUE THREAD

**Issue by PriyaBrataSen** [microsoft/autogen#1151]
### Describe the issue

Sorry to bother again.. I am trying to use the autogen studio. I installed  autogenstudio-0.0.21a0. After that i ran autogenstudio ui --port 8081 command to open the port. Once i am in the app, i manually included my azure key in the general agent workflow under the built menu. Once i tell it to do stock price demo, i get the following error. 

 **raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable**

Sometimes i get the following error too

**openai.NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}**

From the article, it seems like it works with Azure Open AI. 
Just wondering whether i can get some help on this. Thank you again.

### Screenshots and logs

 error 1:

raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

error 2:

openai.NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}

### Additional Information

pyautogen 0.2.0
Python 3.11.3
autogenstudio-0.0.21a0

**Comment by rickyloynd-microsoft** [comment]
@victordibia

**Comment by victordibia** [comment]
Hi @PriyaBrataSen ,

Thanks for the note.  For azure you will need to set the following

- model - which is the deployment id or engine 
- api key .. from azure
- base url .. from azure
- model type ..  -  "azure" 
- api version ... which must be what you get from azure.

Also note that you should only have this model in your list of models.

![Image](https://github.com/microsoft/autogen/assets/1547007/60a42e46-d692-4e4d-93f0-e415bd295315)

**Comment by PriyaBrataSen** [comment]
thanks a ton!  i had to set it up for both user proxy and primary assistant and then it worked. I had previously multiple models listed for primary and user proxy. thank you again

**Comment by iokinpardo** [comment]
Hi @victordibia  many thanks for your Azure setting suggestions.

I have followed and set all Azure setings for both "**User Proxy**" and "**Primary**" agents . Also removed all models from the list and just set this Azure model created.

Im getting this error. AttributeError: '**NoneType**' object has no attribute '**model_dump**'.
Maybe Im missing something? Thanks in advance.

-------------------------------------------------------------------------------------------
```
az_userproxy (to az_primary_assistant):

hello

--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/xxxx/.local/lib/python3.10/site-packages/autogenstudio/web/app.py", line 68, in add_message
    response_message: Message = chatmanager.chat(
  File "/home/xxxx/.local/lib/python3.10/site-packages/autogenstudio/chatmanager.py", line 29, in chat
    flow.run(message=f"{message_text}", clear_history=False)
  File "/home/xxxx/.local/lib/python3.10/site-packages/autogenstudio/workflowmanager.py", line 196, in run
    self.sender.initiate_chat(
  File "/home/xxxx/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 621, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "/home/xxxx/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 398, in send
    recipient.receive(message, self, request_reply, silent)
  File "/home/xxxx/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 551, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
  File "/home/xxxx/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 1193, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
  File "/home/xxxx/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 716, in generate_oai_reply
    extracted_response = model_dump(extracted_response)
  File "/home/xxxx/.local/lib/python3.10/site-packages/autogen/_pydantic.py", line 37, in model_dump
    return model.model_dump()
AttributeError: '**NoneType**' object has no attribute '**model_dump**'
```

**Comment by ekzhu** [comment]
It looks like the Azure endpoint returned a None value in its response. @yenif @maxim-saplin @sonichi

**Comment by hellangleZ** [comment]
Hi experts:

I have also face this problem by using Azure Openai

INFO:     127.0.0.1:49858 - "GET /page-data/build/page-data.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:49856 - "GET /page-data/gallery/page-data.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:49858 - "GET /component---src-pages-gallery-index-tsx-25eaa0ea2f26f1c4361f.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:49856 - "GET /component---src-pages-build-tsx-3bd5608467a276d90ea7.js HTTP/1.1" 200 OK
Traceback (most recent call last):
  File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogenstudio\web\app.py", line 68, in add_message
    response_message: Message = chatmanager.chat(
  File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogenstudio\chatmanager.py", line 22, in chat
    flow = AutoGenWorkFlowManager(config=flow_config, history=history, work_dir=scratch_dir)
  File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogenstudio\workflowmanager.py", line 37, in __init__
    self.receiver = self.load(config.receiver)
  File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogenstudio\workflowmanager.py", line 158, in load
    agent = self.load_agent_config(agent_spec.config, agent_spec.type)
  File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogenstudio\workflowmanager.py", line 173, in load_agent_config
    agent = autogen.AssistantAgent(**agent_config.dict())
  File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogen\agentchat\assistant_agent.py", line 61, in __init__
    super().__init__(
  File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogen\agentchat\conversable_agent.py", line 126, in __init__
    self.client = OpenAIWrapper(**self.llm_config)
  File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogen\oai\client.py", line 108, in __init__
    self._clients: List[OpenAI] = [
  File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogen\oai\client.py", line 109, in <listcomp>
    self._client(config, openai_config) for config in config_list
  File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogen\oai\client.py", line 149, in _client
    client = OpenAI(**openai_config)
  File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\_client.py", line 93, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

INFO:     127.0.0.1:49856 - "POST /api/messages HTTP/1.1" 200 OK


even I delete all other model in my model list, I still face this problem
![image](https://github.com/microsoft/autogen/assets/15274284/83a0bfb0-80ab-45c6-920f-4cd60157b674)

![image](https://github.com/microsoft/autogen/assets/15274284/f7a0c5c0-ff85-4afd-a215-fa5caa8068ab)

How can I sovle this problem ?

Thanks

**Comment by sunxingrong33** [comment]
> thanks a ton! i had to set it up for both user proxy and primary assistant and then it worked. I had previously multiple models listed for primary and user proxy. thank you again

my error is ：

"Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpcore\_backends\sync.py", line 206, in connect_tcp
    sock = socket.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\autogen\Lib\socket.py", line 851, in create_connection
    raise exceptions[0]
  File "C:\ProgramData\Anaconda3\envs\autogen\Lib\socket.py", line 836, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpx\_transports\default.py", line 67, in map_httpcore_exceptions
    yield
  File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpx\_transports\default.py", line 231, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpcore\_sync\connection_pool.py", line 268, in handle_request
    raise exc
  File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpcore\_sync\connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpcore\_sync\connection.py", line 99, in handle_request
    raise exc
  File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpcore\_sync\connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpcore\_sync\connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpcore\_backends\sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\ProgramData\Anaconda3\envs\autogen\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout: [WinError 10060]。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\openai\_base_client.py", line 885, in _request
    response = self._client.send(
               ^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpx\_client.py", line 915, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpx\_client.py", line 943, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpx\_client.py", line 980, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpx\_client.py", line 1016, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpx\_transports\default.py", line 230, in handle_request
    with map_httpcore_exceptions():
  File "C:\ProgramData\Anaconda3\envs\autogen\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpx\_transports\default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: [WinError 10060]。
"

Do you face this? Try many times, but I still  don't know how to solve.
Thank you very much.

**Comment by chiweng2009** [comment]
> Hi experts:
> 
> I have also face this problem by using Azure Openai
> 
> INFO: 127.0.0.1:49858 - "GET /page-data/build/page-data.json HTTP/1.1" 200 OK INFO: 127.0.0.1:49856 - "GET /page-data/gallery/page-data.json HTTP/1.1" 200 OK INFO: 127.0.0.1:49858 - "GET /component---src-pages-gallery-index-tsx-25eaa0ea2f26f1c4361f.js HTTP/1.1" 200 OK INFO: 127.0.0.1:49856 - "GET /component---src-pages-build-tsx-3bd5608467a276d90ea7.js HTTP/1.1" 200 OK Traceback (most recent call last): File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogenstudio\web\app.py", line 68, in add_message response_message: Message = chatmanager.chat( File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogenstudio\chatmanager.py", line 22, in chat flow = AutoGenWorkFlowManager(config=flow_config, history=history, work_dir=scratch_dir) File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogenstudio\workflowmanager.py", line 37, in **init** self.receiver = self.load(config.receiver) File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogenstudio\workflowmanager.py", line 158, in load agent = self.load_agent_config(agent_spec.config, agent_spec.type) File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogenstudio\workflowmanager.py", line 173, in load_agent_config agent = autogen.AssistantAgent(**agent_config.dict()) File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogen\agentchat\assistant_agent.py", line 61, in **init** super().**init**( File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogen\agentchat\conversable_agent.py", line 126, in **init** self.client = OpenAIWrapper(**self.llm_config) File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogen\oai\client.py", line 108, in **init** self._clients: List[OpenAI] = [ File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogen\oai\client.py", line 109, in self._client(config, openai_config) for config in config_list File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogen\oai\client.py", line 149, in _client client = OpenAI(**openai_config) File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai_client.py", line 93, in **init** raise OpenAIError( openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
> 
> INFO: 127.0.0.1:49856 - "POST /api/messages HTTP/1.1" 200 OK
> 
> even I delete all other model in my model list, I still face this problem ![image](https://private-user-images.githubusercontent.com/15274284/298053276-83a0bfb0-80ab-45c6-920f-4cd60157b674.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyODQzODEsIm5iZiI6MTcwNjI4NDA4MSwicGF0aCI6Ii8xNTI3NDI4NC8yOTgwNTMyNzYtODNhMGJmYjAtODBhYi00NWM2LTkyMGYtNGNkNjAxNTdiNjc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDE1NDgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjNzU0MzkyNGY3YWRlOTBkYzlmOGFjNzM2YjQ5MmNiMGE1YWVkZjdjYzZmYTBiZDU3ZWY2NmI5YjNjZTkxMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HOTwEaUebRbrOdPNnYH49tB5_-87ZsPu_rIbzKzVitI)
> 
> ![image](https://private-user-images.githubusercontent.com/15274284/298053390-f7a0c5c0-ff85-4afd-a215-fa5caa8068ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyODQzODEsIm5iZiI6MTcwNjI4NDA4MSwicGF0aCI6Ii8xNTI3NDI4NC8yOTgwNTMzOTAtZjdhMGM1YzAtZmY4NS00YWZkLWEyMTUtZmE1Y2FhODA2OGFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDE1NDgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmNDkyODE3YWY4YWJhZTUxY2M1NDhlMmUyMDRiODEyZDdlYzEwMzljNDViNTQ3YTljZTIxNzlmMTEyOWFmMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ayKulBCRyU8NR5Z5hyUIE_Y-aKVWQz41Vm9KYpuRiAQ)
> 
> How can I sovle this problem ?
> 
> Thanks ![image](https://private-user-images.githubusercontent.com/15274284/298079347-c04eaf04-7d77-4f13-b4c5-8cf117d6e538.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyODQzODEsIm5iZiI6MTcwNjI4NDA4MSwicGF0aCI6Ii8xNTI3NDI4NC8yOTgwNzkzNDctYzA0ZWFmMDQtN2Q3Ny00ZjEzLWI0YzUtOGNmMTE3ZDZlNTM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDE1NDgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5NDAyODE0ZjIxODBmZTViZmExY2E3MDhkYmFlYmNhNzY4YzQzMTNjOTg2ZmIwNzI1ZWY0MDllMWFjZTFkODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.USkSTMYoNH_9mr8yhCtM2P-yhmxugXLOxQwFumQDAyQ)
> 
> only one model

oh I got the same problem ...  Did you resolve it?

**Comment by hellangleZ** [comment]
> > Hi experts:
> > I have also face this problem by using Azure Openai
> > INFO: 127.0.0.1:49858 - "GET /page-data/build/page-data.json HTTP/1.1" 200 OK INFO: 127.0.0.1:49856 - "GET /page-data/gallery/page-data.json HTTP/1.1" 200 OK INFO: 127.0.0.1:49858 - "GET /component---src-pages-gallery-index-tsx-25eaa0ea2f26f1c4361f.js HTTP/1.1" 200 OK INFO: 127.0.0.1:49856 - "GET /component---src-pages-build-tsx-3bd5608467a276d90ea7.js HTTP/1.1" 200 OK Traceback (most recent call last): File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogenstudio\web\app.py", line 68, in add_message response_message: Message = chatmanager.chat( File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogenstudio\chatmanager.py", line 22, in chat flow = AutoGenWorkFlowManager(config=flow_config, history=history, work_dir=scratch_dir) File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogenstudio\workflowmanager.py", line 37, in **init** self.receiver = self.load(config.receiver) File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogenstudio\workflowmanager.py", line 158, in load agent = self.load_agent_config(agent_spec.config, agent_spec.type) File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogenstudio\workflowmanager.py", line 173, in load_agent_config agent = autogen.AssistantAgent(**agent_config.dict()) File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogen\agentchat\assistant_agent.py", line 61, in **init** super().**init**( File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogen\agentchat\conversable_agent.py", line 126, in **init** self.client = OpenAIWrapper(**self.llm_config) File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogen\oai\client.py", line 108, in **init** self._clients: List[OpenAI] = [ File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogen\oai\client.py", line 109, in self._client(config, openai_config) for config in config_list File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogen\oai\client.py", line 149, in _client client = OpenAI(**openai_config) File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai_client.py", line 93, in **init** raise OpenAIError( openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
> > INFO: 127.0.0.1:49856 - "POST /api/messages HTTP/1.1" 200 OK
> > even I delete all other model in my model list, I still face this problem ![image](https://private-user-images.githubusercontent.com/15274284/298053276-83a0bfb0-80ab-45c6-920f-4cd60157b674.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyODQzODEsIm5iZiI6MTcwNjI4NDA4MSwicGF0aCI6Ii8xNTI3NDI4NC8yOTgwNTMyNzYtODNhMGJmYjAtODBhYi00NWM2LTkyMGYtNGNkNjAxNTdiNjc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDE1NDgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjNzU0MzkyNGY3YWRlOTBkYzlmOGFjNzM2YjQ5MmNiMGE1YWVkZjdjYzZmYTBiZDU3ZWY2NmI5YjNjZTkxMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HOTwEaUebRbrOdPNnYH49tB5_-87ZsPu_rIbzKzVitI)
> > ![image](https://private-user-images.githubusercontent.com/15274284/298053390-f7a0c5c0-ff85-4afd-a215-fa5caa8068ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyODQzODEsIm5iZiI6MTcwNjI4NDA4MSwicGF0aCI6Ii8xNTI3NDI4NC8yOTgwNTMzOTAtZjdhMGM1YzAtZmY4NS00YWZkLWEyMTUtZmE1Y2FhODA2OGFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDE1NDgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmNDkyODE3YWY4YWJhZTUxY2M1NDhlMmUyMDRiODEyZDdlYzEwMzljNDViNTQ3YTljZTIxNzlmMTEyOWFmMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ayKulBCRyU8NR5Z5hyUIE_Y-aKVWQz41Vm9KYpuRiAQ)
> > How can I sovle this problem ?
> > Thanks ![image](https://private-user-images.githubusercontent.com/15274284/298079347-c04eaf04-7d77-4f13-b4c5-8cf117d6e538.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyODQzODEsIm5iZiI6MTcwNjI4NDA4MSwicGF0aCI6Ii8xNTI3NDI4NC8yOTgwNzkzNDctYzA0ZWFmMDQtN2Q3Ny00ZjEzLWI0YzUtOGNmMTE3ZDZlNTM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDE1NDgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5NDAyODE0ZjIxODBmZTViZmExY2E3MDhkYmFlYmNhNzY4YzQzMTNjOTg2ZmIwNzI1ZWY0MDllMWFjZTFkODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.USkSTMYoNH_9mr8yhCtM2P-yhmxugXLOxQwFumQDAyQ)
> > only one model
> 
> oh I got the same problem ... Did you resolve it?

Update to new version
