### ISSUE TITLE
[Feature Request]: 建议增加UI创建虚拟团队，自定义多个智能体角色。

### ISSUE THREAD

**Issue by jackq007** [microsoft/autogen#1157]
### Is your feature request related to a problem? Please describe.

# 缺少UI，不能通过UI创建虚拟团队，和自定义多智能体角色

### Describe the solution you'd like

# 1、增加UI创建虚拟团队，自定义多个智能体角色。
# 2、给指定虚拟团队，下发指令，虚拟团队成员互相协作完成指令。

### Additional context

# 无

**Comment by rickyloynd-microsoft** [comment]
English please.
