### ISSUE TITLE
Potentially invalid token counting

### ISSUE THREAD

**Issue by bitnom** [microsoft/autogen#1164]
### Describe the bug

`completion_tokens += 1` looks like a bad idea. Do we expect a chunk to always be 1 token? I don't think so.

### Expected Behavior

tiktoken

### Additional Information

Will fill this out more as I get to it.

**Comment by rickyloynd-microsoft** [comment]
@kevin666aa fyi

**Comment by bitnom** [comment]
Some fun links to note for potentially upcoming necessities..

https://pypi.org/project/tiktoken/

https://pypi.org/project/tiktoken-async/

https://pypi.org/project/qwen-cpp/

**Comment by qingyun-wu** [comment]
@yiranwu0 could you take a look at this?

**Comment by rysweet** [comment]
seems to be fixed to me
