### ISSUE TITLE
I set streaming to True, but Autogen is still not streaming

### ISSUE THREAD

**Issue by tyler-suard-parker** [microsoft/autogen#1166]
### Describe the bug

I followed the instructions and set streaming to True as described.  However, text is still appearing as blocks in the terminal, not as streaming individual tokens.

### Steps to reproduce

1. Install AutoGen
2. Set the parameter "stream" equal to True
3. Run Autogen

### Expected Behavior

The conversation should be materializing word by word, like when ChatGPT is streaming.  Instead, I am getting whole messages after they have been received.

### Additional Information

Windows, Python 3.9

**Comment by rickyloynd-microsoft** [comment]
@tyler-suard-parker Thank you for creating this issue. Can you add some detail to the steps? In particular, which instructions did you follow, and which code did you run?

**Comment by bitnom** [comment]
possibly related to #1118

**Comment by tyler-suard-parker** [comment]
@bitnom VERY related, thank you.

**Comment by tyler-suard-parker** [comment]
> @tyler-suard-parker Thank you for creating this issue. Can you add some detail to the steps? In particular, which instructions did you follow, and which code did you run?

@rickyloynd-microsoft Thank you for your help on this, it looks like I was trying to use functions and that is a no-no with streaming for right now.

**Comment by bitnom** [comment]
> > @tyler-suard-parker Thank you for creating this issue. Can you add some detail to the steps? In particular, which instructions did you follow, and which code did you run?
> 
> @rickyloynd-microsoft Thank you for your help on this, it looks like I was trying to use functions and that is a no-no with streaming for right now.

#1118 was merged to `main`. You may enable streaming with function calling.
