### ISSUE TITLE
[Feature Request]: add black and ruff formatting to notebooks

### ISSUE THREAD

**Issue by davorrunje** [microsoft/autogen#1170]
### Is your feature request related to a problem? Please describe.

Ruff and black are being run on python files by pre-commit, but not on notebooks. Nbqa can be used to perform the same on the notebooks as well.

### Describe the solution you'd like

Add nbqa to pre-commit.

**Comment by rickyloynd-microsoft** [comment]
@sonichi @ekzhu fyi
