### ISSUE TITLE
[AutoGen Studio] Add instructions for running AutoGen Studio from docker

### ISSUE THREAD

**Issue by qingyun-wu** [microsoft/autogen#1172]
What about removing this part for now? @victordibia or others can add it in another PR and solve the env var issue.

_Originally posted by @sonichi in https://github.com/microsoft/autogen/pull/1111#discussion_r1444079371_

**Comment by gagb** [comment]
Related #1241

**Comment by r3d91ll** [comment]
I just submitted a pull. Updated the dockerfiles for base and full to have autogenstudio autostart.
