### ISSUE TITLE
[Feature Request]: Redesign AgentBuilder's API and saved configs' JSON format

### ISSUE THREAD

**Issue by LinxinS97** [microsoft/autogen#1176]
### Is your feature request related to a problem? Please describe.

- The current version of AgentBuilder requires users to provide a backbone model for `build_manager` and each `agent`. This can reduce user effort when creating agents but will limit the advanced usage.
- The current format of saved JSON files is self-defined, which is not general and may have corruptions with other methods.

Based on the above consideration, I think it is necessary to redesign the AgentBuilder's API and the JSON format for saved configs. I've marked the current API as "Experimental".

**Comment by qingyun-wu** [comment]
@LinxinS97, has this feature been added to the Captin agent? If so, could you close this issue? Thank you!

**Comment by rysweet** [comment]
looks very stale
