### ISSUE TITLE
[Bug]: Teachability Not Working

### ISSUE THREAD

**Issue by kb1flr** [microsoft/autogen#1179]
### Describe the bug

Switched from the original TeachableAgent contribution to the teachability for any agent functionality and I can't seem to resolve the path "autogen.agentchat.contrib.capabilities.teachability" as the capabilities folder is not found in the 0.2.4 build.

### Steps to reproduce

pip install pyautogen[teachable]
import autogen
from autogen.agentchat.contrib.capabilities.teachability import Teachability

### Expected Behavior

Teachability should be imported

### Additional Information

Autogen 0.2.4
Colab Notebook
Python 3.10.12

**Comment by rickyloynd-microsoft** [comment]
You say that the capabilities folder is not found. Is that mentioned in an error message? Did you clone the repo and check directly?

**Comment by kb1flr** [comment]
This line:
from autogen.agentchat.contrib.capabilities.teachability import Teachability
throws the error. Essentially, I can see all of the contrib folder elements but capabilities is not dereferenced. I see it in the repo and the version of autopen seems valid. I have not cloned the repo and built autopen myself, but certainly can try. Everything looks correct, but I won't dereference "capabilities".

**Comment by rickyloynd-microsoft** [comment]
Ok, I'll double check by trying the pip package instead of cloning. This will probably be fixed by #1177.

**Comment by kb1flr** [comment]
Thanks! Let me just compliment you on this feature. I tested the previous version in my project and it worked very well.

**Comment by rickyloynd-microsoft** [comment]
I verified that the contrib/capabilities folder is missing from the pyautogen==0.2.4 package, and adding the folder manually under site-packages after a pip install fixes the problem. Per #1177, this should be fixed in the next pip version 0.2.5. Until then, a workaround is to clone the repo and install locally from the autogen dir:

`pip install -e .[teachable]`

**Comment by rickyloynd-microsoft** [comment]
Fixed now in pyautogen==0.2.5. Thanks for the issue @kb1flr !
