### ISSUE TITLE
[Bug]: Simple chat does not work

### ISSUE THREAD

**Issue by gagb** [microsoft/autogen#1186]
### Describe the bug

When I run `samples/simple_chat.py` I get the following error. 

### Steps to reproduce

I used code space with the repo dev container

Setup config and run `python samples/simple_chat.py`

### Expected Behavior

There should be no errors.

### Screenshots and logs

<img width="965" alt="image" src="https://github.com/microsoft/autogen/assets/13227607/d23b2ff3-203c-48b7-9473-abcfe76f4690">

**Comment by victordibia** [comment]
Is this related to #1174 ?

**Comment by afourney** [comment]
I believe so yes. @gagb Did Chi's hotfix work?

**Comment by gagb** [comment]
Fixed by hot fix
