### ISSUE TITLE
[Feature Request]: Add documentation for registering async reply function in sync chat

### ISSUE THREAD

**Issue by davorrunje** [microsoft/autogen#1195]
### Is your feature request related to a problem? Please describe.

1. If you register a `sync` reply function and initiate an `async` chat, the reply function will be triggered.
2. If you register an `async` reply function and initiate a `sync` chat, the reply function will not be triggered.
3. and 4. if the reply function and chat initiation are either both `sync` or both `async`, then the reply function would be triggered.

### Describe the solution you'd like

I understand the limitation of calling the `async` reply function from a `sync` chat and why it is not supported, but it is not properly documented.  We might raise an Exception in sync chat if an `async` reply function is registered.

**Comment by ekzhu** [comment]
Do you think we might want to raise exception when (2) happens?

**Comment by davorrunje** [comment]
> Do you think we might want to raise exception when (2) happens?

I am not sure is it safe to raise it, we might break the code for many people.

**Comment by davorrunje** [comment]
Actually, raising an exception is probably the best way to go. Silently not using a function is worse.
