### ISSUE TITLE
[Bug]:  cannot use azure credentials on mac

### ISSUE THREAD

**Issue by borisko123** [microsoft/autogen#1196]
### Describe the bug

I run studio (v 0.0.23a).
for configuration , i did what is describe in issue #1151, which is closed
but i got the same error:
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

I wonder if config works on mac

### Steps to reproduce

1.  autogenstudio ui --port 8081
2. select agent
3. remove all models
4. add one model with azure params
6. start default workflow in playground
7. see error

### Expected Behavior

the workflow should work

**Comment by rickyloynd-microsoft** [comment]
@victordibia

**Comment by victordibia** [comment]
@borisko123 ,

Can you confirm that you have added the model to both user proxy and assistant? It should be the only models for both agents

**Comment by borisko123** [comment]
yes , both agents are configured.
please advise how to exactly configure them , using azure credentials

**Comment by victordibia** [comment]
Hi @borisko123  ,

from #1151 

For azure you will need to set the following

- model - which is the deployment id or engine 
- api key .. from azure
- base url .. from azure
- model type ..  -  "azure" 
- api version ... which must be what you get from azure.

Also note that you should only have this model in your list of models. Can you confirm you have set these params?

![Image](https://github.com/microsoft/autogen/assets/1547007/60a42e46-d692-4e4d-93f0-e415bd295315)
