### ISSUE TITLE
[Issue]: Qwen model doesn't match  GroupChat

### ISSUE THREAD

**Issue by zay95** [microsoft/autogen#1203]
### Describe the issue

when I use qwen to run the [autogen](https://github.com/microsoft/autogen/tree/main)/[notebook](https://github.com/microsoft/autogen/tree/main/notebook),I got error :

File "/home/miniconda3/envs/gen/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 643, in create
    return self._post(
  File "/home/miniconda3/envs/gen/lib/python3.10/site-packages/openai/_base_client.py", line 1091, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/miniconda3/envs/gen/lib/python3.10/site-packages/openai/_base_client.py", line 852, in request
    return self._request(
  File "/home/miniconda3/envs/gen/lib/python3.10/site-packages/openai/_base_client.py", line 933, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'detail': 'Invalid request: Incorrect role system.'}

**I can use it run other scripts like function_call_code_exec ..，is it the role only supports [assistant.user]?**

/agentchat_groupchat.ipynb
```
import autogen

config_list = (
    {
        "model": "Qwen-72B-Chat",
        "base_url": "http://XXXXX:XX/v1",
        "api_key": "NULL",
    },
)


llm_config = {
    "config_list": config_list,
}

user_proxy = autogen.UserProxyAgent(
    name="User_proxy",
    system_message="A human admin.",
    code_execution_config={"last_n_messages": 2, "work_dir": "groupchat"},
    human_input_mode="TERMINATE",
)
coder = autogen.AssistantAgent(
    name="coder",
    llm_config=llm_config,
)
pm = autogen.AssistantAgent(
    name="pm",
    system_message="Creative in software product ideas.",
    llm_config=llm_config,
)
groupchat = autogen.GroupChat(agents=[user_proxy, coder, pm], messages=[], max_round=12)
manager = autogen.GroupChatManager(groupchat=groupchat, llm_config=llm_config)


user_proxy.initiate_chat(
    manager,
    message="Find a latest paper about gpt-4 on arxiv and find its potential applications in software."
)
```

**Comment by ekzhu** [comment]
Does Qwen model support "system" role?

**Comment by zay95** [comment]
> Does Qwen model support "system" role?

yes, i think it is. I run the open_api.py in qwen project.
https://github.com/QwenLM/Qwen/blob/29fea23f874e3e021e67312dba1da307a3fb5fee/openai_api.py#L199
