### ISSUE TITLE
[Feature Request]: Unify function decorators for function calling, reply, termination and hook functions

### ISSUE THREAD

**Issue by davorrunje** [microsoft/autogen#1214]
### Is your feature request related to a problem? Please describe.

Add function decorators for registering functions for reply, termination and hook and unify API

### Describe the solution you'd like

Add the following function decorators:
```python
@agent.register.for_execution
@agent.register.for_llm
@agent.register.for_reply
@agent.register.for_termination
@agent.register.for_hook
```

**Comment by rysweet** [comment]
appears to be resolved
