### ISSUE TITLE
[Issue]: ImportError: Please install dependencies first although I already installed them.

### ISSUE THREAD

**Issue by selimhanerhan** [microsoft/autogen#1220]
###  The issue
I use a virtual environment and installed pyautogen[retrievechat] by running `pip install "pyautogen[retrievechat]"` but still getting the error saying that dependency isn't installed

### Screenshots and logs

![image](https://github.com/microsoft/autogen/assets/62727953/22221295-1201-48d9-820c-76d8670b8684)

**Comment by davorrunje** [comment]
@selimhanerhan can you please run the following commands and report outputs:
```
pip list | grep chromadb
pip list | grep pyautogen
```

**Comment by selimhanerhan** [comment]
Hi Sorry for the late reply! 
for grep pyautogen `pyautogen         0.1.14`
I get blank output when I type grep chromadb.
I reinstalled the chromadb and still getting the same output

**Comment by davorrunje** [comment]
The latest version of autogen is 0.2.6. Please install it with:
```
pip install "pyautogen[retrievechat]==0.2.6"
```
Then run the commands again and verify that you have the latest versions:
```
pip list | grep chromadb
pip list | grep pyautogen
```

**Comment by ekzhu** [comment]
Also make sure you are not using Python 3.12. Use Python 3.11.

**Comment by selimhanerhan** [comment]
> Also make sure you are not using Python 3.12. Use Python 3.11. Related #1271

Thank you! this solved my issue.
