### ISSUE TITLE
[Feature Request]: Run docker tests on Github Workflow

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#1228]
### Is your feature request related to a problem? Please describe.

Be able to run docker tests on GitHub Workflow. Currently some docker tests are skipped in the build workflow due to the docker not being installed but this can cause bugs to leak through. 

This is related to discussion in several issues:
#1154 
#1127 
#1103

**Comment by sonichi** [comment]
"Currently docker tests are skipped in the build workflow"
Could you be more specific? They are not skipped in my understanding.

**Comment by ekzhu** [comment]
> Could you be more specific? They are not skipped in my understanding.

Some docker tests are skipped due to docker not installed. Updated.

**Comment by ekzhu** [comment]
This is done with the docker tests now running in action.
