### ISSUE TITLE
[Bug]: Missing 'Delete' Button for Skills in earlier rows on AutoGen Studio Interface

### ISSUE THREAD

**Issue by romgenie** [microsoft/autogen#1249]
### Describe the bug

In the AutoGen Studio's skills management interface, when the number of skills exceeds the capacity of the first row, creating a second row, the 'delete' button fails to appear for the skills that are displayed in this new row. This issue obstructs the ability to remove skills from the first row, limiting the user's management capabilities.

### Steps to reproduce

Navigate to the AutoGen Studio's "Skills" section.
Create enough skills so that they span beyond the first row.
Observe the skills that are above those wrapped to the second row.

### Expected Behavior

Each skill in the interface, regardless of its position, should have a 'delete' button that allows the user to remove the skill.

### Screenshots and logs

![autgenkills](https://github.com/microsoft/autogen/assets/5861166/32d9b8ca-8044-4d24-a999-5bf0b5bb0bf7)

### Additional Information

autogenstudio - (1.0.2)
Python 3.11.7
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22621 N/A Build 22621
Microsoft Edge for Business: Version 120.0.2210.121 (Official build) (64-bit)

**Comment by victordibia** [comment]
Thanks for noting this. Will double check and debug.

**Comment by romgenie** [comment]
No problem at all,
I have also tested this on agents and workflows it has the same result.

**Comment by victordibia** [comment]
Addressed in the `autogenstudio branch`. Thanks again! 



![Image](https://github.com/microsoft/autogen/assets/1547007/2dcf8878-7975-49ab-b522-91865aa5a82f)


![Image](https://github.com/microsoft/autogen/assets/1547007/4855d366-2a25-473f-800b-f1aaf6f2d944)



![Image](https://github.com/microsoft/autogen/assets/1547007/4dce8c97-2fa6-4969-bf8c-c360b6b4d38d)

**Comment by romgenie** [comment]
Upgraded to AutoGen Studio UI CLI version: 0.0.28a using command `pip install -U autogenstudio`.
Tested and confirmed issue is resolved.
