### ISSUE TITLE
An expensive bug GPT4.  no matter what I do

### ISSUE THREAD

**Issue by twobob** [microsoft/autogen#125]
I set this up on a new machine today.
I realised that in 2 games I had suddenly spent 7 dollars instantly.  Pretty steep considering it was supposed to be using 3.5-turbo-16k

Checked over all the setting.  Then parsed the entire source code for ANY reference to default models. anything.  Changed every single reference.  No matter what I set it is using the GPT4 API endpoint.

I have tried; the usual inline declarations; using the built in preferred template; just jamming it in as the hardcoded value to the method that checks it.  So.. unless anyone has any other ideas. I'm all out.

7 bucks is no big shakes but I run systems in parallel and no doubt others batch too. Wouldn't want anyone to get an AMAZON AWS level surprise and not have reported. so. Enjoy. Reported. 

EDIT: It's a linux box but I did install it under windows on there as well and test it (that test is probably the top 50c of the green bar )  It was identical  so "not OS".  and "yes, I also tried that."

**Comment by twobob** [comment]
![image](https://github.com/microsoft/autogen/assets/915232/2028aa19-44ac-4d89-8503-e635773e2d4e)
Green 2 games.  The blue bit, about 10 others....

**Comment by afourney** [comment]
Thanks for reporting and sorry about the spend. It sounds like you did due diligence on debugging, so I’m not sure how it was charged to GPT-4. We’ve not seen it call the wrong models before, so I am very curious to try and replicate this.

**Comment by victordibia** [comment]
To help reproduce, would be great to see 
- Your code 
- Emphasis on how you specify your OAI_CONFIG_LIST (the data structure used to define which LLM is used).

**Comment by LittleLittleCloud** [comment]
Maybe here? Looks like the default model is set to GPT-4


https://github.com/microsoft/autogen/blob/20d77a1039a167139da60e0eed4713039de76956/autogen/code_utils.py#L18

**Comment by afourney** [comment]
@LittleLittleCloud  No I don't think that's it. That default is only accessed from the improve_code, improve_function, and implement calls -- and they aren't part of the main control path.

I am eyeing this: https://github.com/microsoft/autogen/blob/20d77a1039a167139da60e0eed4713039de76956/autogen/oai/openai_utils.py#L331

@twobob How are you loading the config list? Are you using .env?

**Comment by twobob** [comment]
[
    {
        "model": "gpt-3.5-turbo-16k-0613",
        "api_key": "ssdsdsdsdsdxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxA"
    },
    {
        "model": "gpt-3.5-turbo-16k",
        "api_key": "ssdsdsdsdsdxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxA"
    },
    {
        "model": "gpt-3.5-turbo-0613",
        "api_key": "ssdsdsdsdsdxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxA"
    },
    {
        "model": "gpt-3.5-turbo",
        "api_key": "ssdsdsdsdsdxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxA"
    },
    {
        "model": "gpt-4",
        "api_key": "<your Azure OpenAI API key here>",
        "api_base": "<your Azure OpenAI API base here>",
        "api_type": "azure",
        "api_version": "2023-07-01-preview"
    },
    {
        "model": "gpt-3.5-turbo",
        "api_key": "<your Azure OpenAI API key here>",
        "api_base": "<your Azure OpenAI API base here>",
        "api_type": "azure",
        "api_version": "2023-07-01-preview"
    }
]

**Comment by twobob** [comment]
thanks for all the feedback. Yes there is zero reference to the word gpt-4  in my code now so 
DEFAULT_MODEL = "gpt-4" 
would have already been changed.  I literally gutted it

**Comment by twobob** [comment]
> @LittleLittleCloud No I don't think that's it. That default is only accessed from the improve_code, improve_function, and implement calls -- and they aren't part of the main control path.
> 
> I am eyeing this:
> 
> https://github.com/microsoft/autogen/blob/20d77a1039a167139da60e0eed4713039de76956/autogen/oai/openai_utils.py#L331
> 
> ```
>    # Ensure default models are always considered
>     default_models = ["gpt-4", "gpt-3.5-turbo"]
> 
>     for model in default_models:
>         # Only assign default API key if the model is not present in the map.
>         # If model is present but set to invalid/empty, do not overwrite.
>         if model not in model_api_key_map:
>             model_api_key_map[model] = "OPENAI_API_KEY"
> ```
> 
> @twobob How are you loading the config list? Are you using .env?

me@mebuntu:~/repo/autogen$ echo $OPENAI_API_KEY
ssdsdsdsdsdxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxA

my env is indeed setup as well as the config file

**Comment by twobob** [comment]
> To help reproduce, would be great to see
> 
>     * Your code
> 
>     * Emphasis on how you specify your OAI_CONFIG_LIST (the data structure used to define which LLM is used).

hi , which code.  its the default code gutted to not contain any references to gpt_4 pretty much?

**Comment by sonichi** [comment]
Could you show the code that contains `llm_config`? If it contains "config_list" in it, could you also show the code which sets `config_list`?

**Comment by twobob** [comment]
I forgot to mention but I DID do this first on a windows box and wa using bash as my interpreter because "inline commands working for windows would be cool to do for everyone" I thought.  That was when I noticed the bug.

Thought it was /maaaaybe/ the funky bash hack that was causing the error
Hence it being a vanilla ubuntu - like fresh for this job - and a very unhacked autogen other than the gutting.

Like this is the dream support box. literally nothing has happened on it other than this.  since I have installed chatdev on the same box but meh. these tests were before that and nothing has changed in terms of the autogen anyway.

So there. the full sordid details. Honestly not sure where to go from there

It's not account since chatdev can use 3.5 just fine from the ubunutu install (why I installed chatdev after)

**Comment by twobob** [comment]
> Could you show the code that contains `llm_config`? If it contains "config_list" in it, could you also show the code which sets `config_list`?

hi. it is the defaults straight from the readme or from a notebook,  does it write logs anywhere? Ive mounted onto the windows drinve from ubuntu so I can access anything...

**Comment by twobob** [comment]
i ran agentchat_groupchat_research.ipynb afaik

**Comment by twobob** [comment]
> @LittleLittleCloud No I don't think that's it. That default is only accessed from the improve_code, improve_function, and implement calls -- and they aren't part of the main control path.
> 
> I am eyeing this:
> 
> https://github.com/microsoft/autogen/blob/20d77a1039a167139da60e0eed4713039de76956/autogen/oai/openai_utils.py#L331
> 
> ```
>    # Ensure default models are always considered
>     default_models = ["gpt-4", "gpt-3.5-turbo"]
> 
>     for model in default_models:
>         # Only assign default API key if the model is not present in the map.
>         # If model is present but set to invalid/empty, do not overwrite.
>         if model not in model_api_key_map:
>             model_api_key_map[model] = "OPENAI_API_KEY"
> ```
> 
> @twobob How are you loading the config list? Are you using .env?

Hmmm. you know I am certain I did NOT remove that one (I errantly excluded that from the replace)... 
Hmm.. Time for new test then

**Comment by twobob** [comment]
So. i reran it just to make sure it wasnt anything really stupid.  BEFORE I made the above change

![image](https://github.com/microsoft/autogen/assets/915232/7e405cc5-3ed5-4625-bb53-683b4af810a7)
Blue bar is me making 30 games yesterday with chatDev, green bar is just setting up the requirements (basically 4 round of chat) in autogen on "supposed 3.5"  before I stopped it again and waited for the OpenAi usage to catch up.

so. I wasn't going mad it really was doing that.

I made the above change. and only added 3.5 models in the list and ran it again/

Still no change.

I attached my actual notebook.
[agentchat_groupchat_research_That_WAS_ACTUTALLY_USED.zip](https://github.com/microsoft/autogen/files/12838800/agentchat_groupchat_research_That_WAS_ACTUTALLY_USED.zip)

**Comment by twobob** [comment]
maybe I should remove the API key from env?  Any other ideas?

**Comment by twobob** [comment]
@LittleLittleCloud  
![image](https://github.com/microsoft/autogen/assets/915232/8df73c75-2615-4194-a31d-27987534f0ee)

**Comment by twobob** [comment]
> To help reproduce, would be great to see
> 
>     * Your code
> 
>     * Emphasis on how you specify your OAI_CONFIG_LIST (the data structure used to define which LLM is used).

attached the zip

**Comment by twobob** [comment]
In the notbook I attached I had actually increased the engineer to 4 again. Hardly mattered I was already timing out on the got4 token/min before it popped

**Comment by sonichi** [comment]
The code looks good to me. Please make sure:
1. OAI_CONFIG_LIST is either an environment variable, or a file under the same path as the notebook. Please print the `config_list_gpt3` dict to make sure it contains the gpt-3.5 models.
2. make sure `config_list_gpt3` is contained in all the `llm_config`.
3. set `max_consecutive_reply` to 0 for `UserProxyAgent` to make a single-turn conversation. Check your bill.

**Comment by twobob** [comment]
1) it is a file in the root of the path. I didnt realise I could do it as an env... Did I miss a doc? maybe, I shall insert the print
2) Will do. In terms of the llm_configs as you can see in the code I believe that twas the case
3) Ah okay. If its all the same I will probably run up like 50c or so - just so I can FOR SURE see it.

**Comment by twobob** [comment]
Ill do it after midnight. THEN I will for sure see it. it will be the only cost.  *lightbulb*

**Comment by twobob** [comment]
![image](https://github.com/microsoft/autogen/assets/915232/2ddf252c-3546-4eb2-a119-8b20ef0e6b9c)

Ooooookay.   It seems like maybe we have a suspect.

config_list_from_json not actually populating ... hmm.. I DID NOT see that coming. good call.

So... I guess time to make that env...  Better find those docs I guess

**Comment by sonichi** [comment]
The file is supposed be located at:
<img width="246" alt="image" src="https://github.com/microsoft/autogen/assets/4250911/762b268c-4c3b-4bd4-96ff-734e833933ef">

**Comment by twobob** [comment]
I dont run this on colab sir.

**Comment by sonichi** [comment]
ok. then it should be located next to the .ipynb file. otherwise you need to specify `file_location`. https://microsoft.github.io/autogen/docs/FAQ#set-your-api-endpoints

**Comment by twobob** [comment]
Yup ^^^ This ^^^ I was NOT in the notebook. folder. It was one level below.  Ill restest now this is all a bit more "like it should be"

**Comment by twobob** [comment]
![image](https://github.com/microsoft/autogen/assets/915232/08f283a6-65ff-46ec-bd90-a436d326c1c2)


![image](https://github.com/microsoft/autogen/assets/915232/763e7a05-21db-43da-a2a1-c07ebfbeedd2)


That sliver on blue IS A WELCOME SIGHT!

Might I suggest a tweak to the notebooks?  something that actually PRINTS or even CHECKS the content of that array and just refuses to continue otherwise with a warning?

Thanks so much again

**Comment by twobob** [comment]
Engineer (to chat_manager):

As an AI language model, I don't have the capability to actively participate in the development process. However, I can provide guidance and suggestions based on the information provided. If you have any specific questions or need assistance with any particular step of the development process, please let me know and I'll be happy to help!

How unfortunate... Ah well

Yup they spent $1.70 and never wrote a single line of code. Jut kept planning the project over and over despite intervention guiding them not...

23:00
Local time: 8 Oct 2023, 00:00
gpt-3.5-turbo-16k-0613, 38 requests
169,170 prompt + 2,509 completion = 171,679 tokens
23:05
Local time: 8 Oct 2023, 00:05
gpt-3.5-turbo-16k-0613, 23 requests
159,774 prompt + 2,554 completion = 162,328 tokens
![image](https://github.com/microsoft/autogen/assets/915232/eaaa045d-c5c0-4ed2-9df0-255f83b9c85a)

I guess Ill wait until this allows local LLMS

**Comment by sonichi** [comment]
or try some non-coding tasks, or try including a code example in the initial message.

**Comment by kohanzie** [comment]
hello i have been having the same problems. its calling both gpt4 and gpt3.5 even though my code only calls for gpt3.5 these are the docs. i am currently using version 0.1.8
[content.zip](https://github.com/microsoft/autogen/files/12850557/content.zip)

**Comment by afourney** [comment]
Ok, here is my understanding of what's happening:

If the the OAI_CONFIG_LIST is not found, then the config that gets returned is an empty list, (see: https://github.com/microsoft/autogen/blob/4522900487b65766d0f89dd30b10b6021b45e313/autogen/oai/openai_utils.py#L246).   Then https://github.com/microsoft/autogen/blob/4522900487b65766d0f89dd30b10b6021b45e313/autogen/agentchat/conversable_agent.py#L111  populates the config list with a default, then never updates it because the list is empty. Finally OAI's openai library reads the missing key from environment variable.
