### ISSUE TITLE
[Issue]: Error code: 400 - {'error': {'message': "You submitted a length-0 POST body, but must submit a JSON object.

### ISSUE THREAD

**Issue by congliu19** [microsoft/autogen#1253]
### Describe the issue

hello, I'm running the demo of plot the stock price of APPL and TESLA. When I interact with useragent, this error occurs. Why the post body is length-0? How to deal this? Wait for reply~ thx!

**Comment by ekzhu** [comment]
Can you post the complete code you use and print the llm_config (remove the secretes like OPENAI_API_KEY).

**Comment by congliu19** [comment]
the python file 👇

import os

from autogen import AssistantAgent, UserProxyAgent, config_list_from_json
config_list = config_list_from_json(env_or_file="OAI_CONFIG_LIST")

username = os.environ.get('username')
password = os.environ.get('password')

os.environ['https_proxy'] = f"http://{username}:{password}@xxx.com:8080/"

assistant = AssistantAgent(name="assistant", llm_config={"config_list": config_list})

user_proxy = UserProxyAgent(
    name="user_proxy",
    code_execution_config={"work_dir": "sources"}
)

user_proxy.initiate_chat(
    assistant, message="Plot a chart of NVDA and TESLA stock price change YTD."
)

**Comment by congliu19** [comment]
the OAI_CONFIG_LIST👇

[
    {
        "model": "gpt-4",
        "api_key": "06xxxxxxx",
        "base_url": "https://canadaeast4ai.openai.azure.com/",
        "api_type": "azure",
        "api_version": "2023-07-01-preview"
    },
    {
        "model": "GPT-35-Turbo-G", # the name in azure deploy model name
        "api_key": "06xxxx",
        "base_url": "https://switzerlandnorthinstance4ai.openai.azure.com/",
        "api_type": "azure",
        "api_version": "2023-07-01-preview"
    }
]

I have a question that the value of "model" is from the deployment model name in azure or something match what?

**Comment by ekzhu** [comment]
> I have a question that the value of "model" is from the deployment model name in azure or something match what?

Should be deployment name I believe.

> "api_version": "2023-07-01-preview"

Can you use "2023-12-01-preview"?

**Comment by congliu19** [comment]
I have try with 2023-12-01-preview, but it error again after "Successfully installed contourpy-1.2.0 cycler-0.12.1 fonttools-4.47.2 kiwisolver-1.4.5 matplotlib-3.8.2 packaging-23.2 pillow-10.2.0 pyparsing-3.1.1" with the error message below
"raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "You submitted a length-0 POST body, but must submit a JSON object. (HINT: Try submitting an empty object instead, i.e. {}. If you're using curl, you can pass -d '{}' -H 'Content-Type: application/json')", 'type': 'invalid_request_error', 'param': None, 'code': None}}"

**Comment by ekzhu** [comment]
Could you also post your `pyautogen` version, and your Python version?

**Comment by congliu19** [comment]
I get the code by git clone last week. How to find the version? But I just pull the newest, the python script can run longer than before until the stock price chart was plotted. However, when I continue send the new request, such as, "add the BABA to this chart" the same error occurs again.
I guess it should be something null get this, but I can't locate it.
Can u help me?~

**Comment by cheng-tan** [comment]
use `pip list | grep 'pyautogen'` to check autogen version, can you also check openai version?

**Comment by congliu19** [comment]
I'm sorry for the late reply. The pyautogen version is 0.2.7 and openai version is 1.10.0. I have meet the same error in other agent such as crewAI. However, I have not debugged it out yet.

**Comment by aishoot** [comment]
the same question

**Comment by qingyun-wu** [comment]
Hi @congliu19, is the issue addressed?

**Comment by rysweet** [comment]
cannot reproduce- please reopen if you are still having problems.
