### ISSUE TITLE
[Bug]: use of `asyncio.coroutines.iscoroutinefunction` instead of `inspect.iscoroutinefunction`

### ISSUE THREAD

**Issue by davorrunje** [microsoft/autogen#1260]
### Describe the bug

In several places `asyncio.coroutines.iscoroutinefunction` is used instead of `inspect.iscoroutinefunction`.

Both `asyncio.coroutines.iscoroutinefunction` and `inspect.iscoroutinefunction` are used to check if a function is a coroutine function. However, they differ in the types of functions they consider to be coroutine functions.

- `inspect.iscoroutinefunction` considers a function to be a coroutine function if it is either:

   - A function decorated with `async def`
   - A function decorated with `@asyncio.coroutine`
   
- `asyncio.coroutines.iscoroutinefunction` only considers a function to be a coroutine function if it is decorated with `@asyncio.coroutine`. It does not consider functions decorated with `async def` to be coroutine functions.

See e.g. https://stackoverflow.com/questions/59343239/asyncio-iscoroutinefunction-returns-false-for-asynchronous-generator

**Comment by ekzhu** [comment]
Nice catch!

**Comment by davorrunje** [comment]
I spent a day once chasing bug caused by this, that's why I know about it. Weird.
