### ISSUE TITLE
[Issue]: Annoying Toasts in autogenstudio 

### ISSUE THREAD

**Issue by jaschahuisman** [microsoft/autogen#1265]
### Describe the issue

It's very annoying to see the `Workflows retrieved successfully` toast every time navigating to the workflow page, vice versa for the agents and skills page. Please add a feature to disable it in settings, or disable it at all and do this kind of logging in a more user friendly way.

### Screenshots and logs

<img width="276" alt="Screenshot 2024-01-15 at 19 44 36" src="https://github.com/microsoft/autogen/assets/39152972/93f00cea-df9f-459e-8ad9-0a14cd9510b5">

**Comment by ekzhu** [comment]
@victordibia

**Comment by victordibia** [comment]
Thanks for noting this. 
Will work on disabling this or putting this behind some debug flag.

**Comment by victordibia** [comment]
This has been addressed, thanks. 
Closing out. Feel free to re-open as needed.
