### ISSUE TITLE
[Bug]: `generate_oai_reply` cannot handle the None reply

### ISSUE THREAD

**Issue by LinxinS97** [microsoft/autogen#1268]
### Describe the bug

Sometimes, Agents will receive some unexpected responses from non-openai servers (like Azure) like:
```
ChatCompletion(id='...', choices=[Choice(finish_reason='content_filter', index=0, message=ChatCompletionMessage(content=None, role='assistant', function_call=None, tool_calls=None), ...)
```
where the `content`, `function_call`, and `tool_calls` are all `None`. This will further cause the following error in agent conversation:
```
AttributeError: 'NoneType' object has no attribute 'model_dump'
```
which is located in `ConversableAgent.generate_oai_reply`:
```python
...
        if not isinstance(extracted_response, str):
            extracted_response = extracted_response.model_dump(mode="dict")  # error raise in this line
        return True, extracted_response
...
```

### Expected Behavior

Should retry when receive such response.

### Additional Information

pyautogen=0.2.6

**Comment by prithvi2226** [comment]
@LinxinS97 , Is this issue still open to work on?
