### ISSUE TITLE
[Bug]: cost calculation from Azure openai is wrong for new version

### ISSUE THREAD

**Issue by yiranwu0** [microsoft/autogen#1270]
### Describe the bug

Azure OpenAi completion returns the model without version information. The returned model is either 'gpt-35-turbo' or 'gpt-4'. From there, we are calculating the cost based on gpt-3.5-0613: ((0.0015, 0.002) per 1k prompt and completion tokens) and gpt-4-0613: (0.03,0.06). This means the cost is wrong if the user is using the 1106 version of the models from azure OpenAI.

Potential solution: 
One way is to pass the model name specified by the user (instead of the model returned from completion) to calculation cost. However, self-created names (for example, gpt4-11) can result in fail at cost calculation.

**Comment by new4u** [comment]
我也遇到了类似的错误,包括response.cost回复也是报错的,建议去掉cost的计算,或者使其成为一个非必选项I also encountered similar errors, including the error response.cost. It is recommended to remove the calculation of cost, or make it a non-required option.

**Comment by yiranwu0** [comment]
This is closed by #2902. User now can pass in custom prices.

**Comment by Deykeepcomn4me** [comment]
This is hacker please contact fbi
