### ISSUE TITLE
[Issue]: How am I able to group agents together like the travel agent example

### ISSUE THREAD

**Issue by TheMindExpansionNetwork** [microsoft/autogen#1273]
### Describe the issue

I have myself a team of agents that are ready to be used but I am unable to make them inside of a workflow together. 

not sure what I am missing it it how I can deploy the group like I see in the examples below.

![image](https://github.com/microsoft/autogen/assets/77267159/90b7303a-d0bd-4dbd-8f00-2e3ab7a3d4b6)

this is what I see

![image](https://github.com/microsoft/autogen/assets/77267159/955b9695-5090-4a3b-bb1c-cc7c22607cba)

Just the single-page

![image](https://github.com/microsoft/autogen/assets/77267159/51379a3a-69f8-4459-a3f8-8fd5af14ebe0)

![image](https://github.com/microsoft/autogen/assets/77267159/d8370a11-603a-46fa-a912-699d8208f134)

these are my agents.

what am I missing family

### Steps to reproduce

Attempted to restart>same issue
Attempted to change the stuff in travel agent>unable to change

Just need to group them you know

### Screenshots and logs

Put them between

### Additional Information

Newest Studio with my local machine windows 10

**Comment by qingyun-wu** [comment]
@victordibia  is group chat supported in AutoGen Studio?

**Comment by victordibia** [comment]
Support for GroupChat is currently in development.
Expected ETA is end of this week. I'll update here once that is available.  
The current travel example is predefined, however the coming updates will provide the ability to compose multiple agents into group chat.

**Comment by techguydev** [comment]
Thanks, I am also waiting for this, just got stuck in some test

**Comment by TheMindExpansionNetwork** [comment]
Sweetness really looking forward to this amazing project

**Comment by darkness198** [comment]
For those wondering how to get group chatting to work with local models(should work fine with gpt4 also), this is how I did it after some failed tests you all seemed to run into also(note: seems to still be in development but to me seems to be working well enough now this way):

1. Go to where autogenstudio is installed and find the "dbdefaults.json" file in the utils folder(this is what autogenstudio seems to use to initialize the sqlite db upon first startup)

2. Copy the travel agent example object in it's entirety in the "workflows" array, add it to the array of workflows and change the name so you can identify it(I just added "Copy" to the end)

3. Go to the "web" folder and rename "database.sqlite" to "database.sqlite.bak"(you can also delete the file I think, but this is just for safety if you already have things defined, you can switch back by just renaming the file again)

4. restart autogenstudio and it should reload with the "Copy" workflow that was added into the dbdefaults file as a new database.sqlite file is created on startup

5. Add your agents and edit the workflow correctly as you've probably tried to do already

6. I kept getting an OPENAI_API_KEY error even after configuring everything correctly, this was solved by adding a "dummy" value to the OPENAI_API_KEY variable in my conda environment( in my case running on windows this was: conda env config vars set OPENAI_API_KEY=dummy) - I got this idea from a comment on a youtube video

7. Try out the workflow in the playground

If I'm doing something weird or wrong, please excuse me devs - I just started using autogenstudio today and probably missed a lot as I was sifting through docs trying to figure it out. But this seems to work for me, as I get multiple agents seemingly replying to one another in the playground mostly as I'd expect though the delegation may not be perfect. Hope this helps.

**Comment by victordibia** [comment]
@darkness198 ,

Thanks for sharing your process and the feedback so far. 
There is some progress on Creating new GroupChat and adding agents in autogenstudio `0.0.28a`. 

`pip install -U autogenstudio` 

https://github.com/microsoft/autogen/assets/1547007/58e66ce1-3c10-4c5e-b45d-783121d151ec

**Comment by techguydev** [comment]
> @darkness198 ,
> 
> Thanks for sharing your process and the feedback so far. There is some progress on Creating new GroupChat and adding agents in autogenstudio `0.0.28a`.
> 
> `pip install -U autogenstudio`
> 
>  groupchatnew.mp4 
> Note: You might need to delete your database.sqlite file (due to some schema changes)

Thanks a lot  for the hard work Victor I will try it right away.
Thanks a lot @darkness198  for the workaround, nice to have alternatives.

**Comment by victordibia** [comment]
@TheMindExpansionNetwork ,

Does the groupchat UI update address this issue? 
If so, please feel free to close this out!

Thanks again for providing feedback and ideas towards resolution.

**Comment by TheMindExpansionNetwork** [comment]
> @TheMindExpansionNetwork ,
> 
> Does the groupchat UI update address this issue? 
> If so, please feel free to close this out!
> 
> Thanks again for providing feedback and ideas towards resolution.

Most def you all doing amazing work thanks for blessing to give me more time with my family and creating 

I'll post some tutorials as progresses closing ticket

**Comment by BGW1001** [comment]
I have upgraded Autogen Studio - it installed autogenstudio-0.0.33a0 and the group chat manager in workflow is not there.
