### ISSUE TITLE
User input does not show in the UI , instead one has to switch back to terminal. AutogenStudio

### ISSUE THREAD

**Issue by abhishekrai43** [microsoft/autogen#1278]
### Is your feature request related to a problem? Please describe.

This is a bit strange, if the UI has been designed, it should allow for additional human input as well, makes no sense to go back to the terminal. This is the case when the human input is ALWAYS and I believe it will also be the case if the select_speaker will be set to manual.

### Describe the solution you'd like

Human Input and Select mext speaker Must be shown in the UI not in the terminal

**Comment by victordibia** [comment]
Thanks for trying out AutoGen Studio and the feedback. 
Human input model requires streaming infrastructure which is still on the roadmap, but not implemented yet. 
Group Chat support is also in development at the moment (including adding specs for next speaker).

Roadmap [here](https://github.com/microsoft/autogen/issues/737).
PR's and help welcome here too!

**Comment by victordibia** [comment]
Shall we close this out for now, since this issue is being tracked on the roadmap #737 ?
