### ISSUE TITLE
[Issue]: Google Cloud Platform Palm2 API usage with Autogen

### ISSUE THREAD

**Issue by amitkrdutta** [microsoft/autogen#1293]
### Describe the issue

I want to use Autogen with Vertex API for Palm2. I do not have access to the API key. Now I am not able to set the config_list object. 
```
config_list=[
        {
            "model": "text-bison",
            "base_url": "https://us-east4-aiplatform.googleapis.com/v1/projects/<project-id>/locations/us-east4/publishers/google/models/text-bison:predict",
            "api_type": "<>", 
            "api_key": "NULL",
        }
    ]
```
Can anyone point what would be the api type for GCP ?
Not sure how to authenticate here.

Or there may be a better solution to integrate GCP.

**Comment by qingyun-wu** [comment]
@BeibinLi, do you know if these issues are addressed in our latest version?

**Comment by rysweet** [comment]
needs more detail from OP if we are to continue.
