### ISSUE TITLE
[Bug]: Skills in Autogen Studio not being updated (name cached?) + primary agent writes incorrect code instead

### ISSUE THREAD

**Issue by gruffdavies** [microsoft/autogen#1294]
### Describe the bug

When updating a skill, unless the main function named is changed, the skill seems to run the original code, not the newly submitted code (but I may be misinterpreting the trace/debug log).
I thought I'd got an updated skill working by changing it's function name to `search_gscholar` from `search_google_scholar`, However, I've noticed the primary agent is writing code rather than just calling the skill function.  
This may be two separate bugs/issues, or one, I'm not sure.

```text
userproxy (to google_scholar_assistant):

what functions do you have?

--------------------------------------------------------------------------------
google_scholar_assistant (to userproxy):

I have a function available from a file called `skills.py` which can be used to search Google Scholar. The function is called `search_gscholar` and it allows you to search for academic papers, articles, and publications related to a specific query. It uses the `scholarly` library to perform the search and returns a list of dictionaries containing information such as the title, authors, abstract, and URL of each search result.

If you have a specific query or topic you'd like to search for on Google Scholar, please let me know, and I can assist you with that using the `search_gscholar` function. TERMINATE
```

then, I ask a new question, but instead of calling the skill function, it writes new ocde which isn't correct and fail

NB: I've added indents to the code block so it renders inside this nested block - they aren't indented in reality.

```text
userproxy (to google_scholar_assistant):

I would like to find physics papers on vacuum polarisation, especially any that shed light on ways to calculate the phase velocity of EM waves due to this

--------------------------------------------------------------------------------
google_scholar_assistant (to userproxy):

To find physics papers on vacuum polarization that discuss the calculation of the phase velocity of electromagnetic waves due to this effect, I will use the `search_gscholar` function from the `skills.py` file. I will perform a search with a query that targets this specific topic. Let's proceed with the search.

    ```python
    # filename: search_gscholar_vacuum_polarization.py
    from skills import search_gscholar
    
    # Define the search query
    query = "vacuum polarization phase velocity of EM waves"
    
    # Perform the search with a reasonable number of results
    results = search_gscholar(query, max_results=10)
    
    # Print the results
    for paper in results:
        print(f"Title: {paper.get('title', 'Not available')}")
        print(f"Authors: {paper.get('authors', 'Not available')}")
        print(f"Abstract: {paper.get('abstract', 'Not available')}")
        print(f"URL: {paper.get('url', 'Not available')}")
        print(f"Year: {paper.get('year', 'Not available')}")
        print("-" * 80)  # Separator for readability
    ```

Please run the above Python script, and it will output a list of relevant papers on the topic of vacuum polarization and phase velocity of electromagnetic waves. After you run the script, please provide me with the output so I can assist you further if needed.

```

So the code it wrote isn't correct and it's not using the skill.


### Steps to reproduce

1. Create a skill with a known bug line.
2. Run a workflow causing the issue.
3. Delete the skill
4. Recreate the skill fixing the bad line (leave the function name the same)
5. Run the workflow and the old code is called, not the new.

E.g.
```python
import os
import json
import hashlib
from scholarly import scholarly

# NB: change the function name when updating skills or the skill will not be updated (the function name seems to be cached)
def search_gscholar(query, max_results=10):
    """
    Searches Google Scholar for the given query using the scholarly library, then returns the search results.

    Args:
        query (str): The search query.
        max_results (int, optional): The maximum number of search results to return. Defaults to 10.

    Returns:
        jresults (list): A list of dictionaries. Each dictionary contains fields such as 'title', 'authors', 'abstract', and 'url'

    Example:
        >>> results = search_google_scholar("deep learning")
        >>> print(results)
    """

    key = hashlib.md5(("search_gscholar(" + str(max_results) + ")" + query).encode("utf-8")).hexdigest()
    cache_dir = ".cache"
    if not os.path.isdir(cache_dir):
        os.mkdir(cache_dir)

    fname = os.path.join(cache_dir, key + ".cache")

    if os.path.isfile(fname):
        with open(fname, "r", encoding="utf-8") as fh:
            data = json.loads(fh.read())
        return data

    search_query = scholarly.search_pubs(query)
    jresults = []
    for i, result in enumerate(search_query):
        if i >= max_results:
            break
        r = dict()

        # step 1. create skill with this bad code:
        # this likely breaks if bib isn't in result
        # create skill with this code first
        r['title'] = result.bib.get('title')
        r['authors'] = result.bib.get('author')
        r['abstract'] = result.bib.get('abstract')
        r['url'] = result.bib.get('url')
        r['year'] = result.bib.get('year')

        # step 4. recreate the skill replacing block above with this uncommenting it and commenting out the above
        # if 'bib' in result:
        #     r['title'] = result.bib.get('title')
        #     r['authors'] = result.bib.get('author')
        #     r['abstract'] = result.bib.get('abstract')
        #     r['url'] = result.bib.get('url')
        #     r['year'] = result.bib.get('year')

        jresults.append(r)

    with open(fname, "w") as fh:
        fh.write(json.dumps(jresults))

    return jresults
```

### Expected Behavior

1. The new function should run when the skill is deleted and recreated with the same function name.
2. The agent should run the function, not write it's own code to do the same thing (incorrectly).

### Screenshots and logs

![image](https://github.com/microsoft/autogen/assets/2751545/38334e7d-5d15-4ea6-8e7b-1fcf6a7b5638)
![image](https://github.com/microsoft/autogen/assets/2751545/8e5efa1c-d233-4f3d-a2cd-9cf86da839a8)

### Additional Information

WSL2 (Ubuntu 22.04), VSCode

**Comment by victordibia** [comment]
@gruffdavies thanks for reporting this. Definitely looks like a bug. 

In general, here is how skills get used each time a request from the ui is made (user enters text in the text input and hits send)

- the workflow configuration is loaded by the workflow manager
- skills (part of agents in in the workflow config) are all serialized into a file that is saved as skills.py in the agent working directory (we **[_append_](https://github.com/microsoft/autogen/blob/3ea1455103c11f6ade2f43b314bdd8e075b0b5bc/samples/apps/autogen-studio/autogenstudio/utils/utils.py#L227)** to the file if it exists). The skills are also added to the prompt to the LLM is aware of them (and how to use them). This will be optimized to add perhaps only the skill signature in the future.

I believe the bug here is that we append to the file, meaning older skills (not in the ui) are still available to the llm hence the confusion. 

I'll push a fix (overwrite content of skills.py ), do some testing and let you know.

**Comment by victordibia** [comment]
This has been updated and addressed by the fix above. 
Closing this out.

**Comment by unliquid** [comment]
I suspect that removing the append function has broken things. When I have more than one skill, only the second appears in the skills.py file, possibly because it is overwriting the file rather appending the second skill.

**Comment by odeduxi** [comment]
I am facing the same issue, adding new skills are not added to skills.py. How to resolve? I am using AutoGen Studio v0.0.54
