### ISSUE TITLE
[Issue]: problem to make api call to autogenStudio install on server 

### ISSUE THREAD

**Issue by mostafamosa** [microsoft/autogen#1295]
### Describe the issue

i had install autogen on server and i can finde a /api/docs# FASTapi suport but i can not make a reuast 
is there any budy have tried it ? 

### Steps to reproduce

how FAST api work with autogen studio ?

**Comment by mostafamosa** [comment]
you meen at i should all tig to add_message_messages_post

{
  "message": {
    "user_id": "string",
    "role": "string",
    "content": "string",
    "root_msg_id": "string",
    "msg_id": "string",
    "timestamp": "string",
    "personalize": false,
    "ra": "string",
    "code": "string",
    "metadata": "string",
    "session_id": "string"
  },
  "flow_config": {
    "name": "string",
    "description": "string",
    "sender": {
      "type": "assistant",
      "config": {
        "name": "string",
        "llm_config": false,
        "human_input_mode": "NEVER",
        "max_consecutive_auto_reply": 10,
        "system_message": "string",
        "is_termination_msg": true,
        "code_execution_config": true
      },
      "id": "string",
      "timestamp": "string",
      "user_id": "string",
      "skills": [
        {
          "title": "string",
          "file_name": "string",
          "content": "string",
          "id": "string",
          "description": "string",
          "timestamp": "string",
          "user_id": "string"
        }
      ],
      "description": "string"
    },
    "receiver": {
      "type": "assistant",
      "config": {
        "name": "string",
        "llm_config": false,
        "human_input_mode": "NEVER",
        "max_consecutive_auto_reply": 10,
        "system_message": "string",
        "is_termination_msg": true,
        "code_execution_config": true
      },
      "id": "string",
      "timestamp": "string",
      "user_id": "string",
      "skills": [
        {
          "title": "string",
          "file_name": "string",
          "content": "string",
          "id": "string",
          "description": "string",
          "timestamp": "string",
          "user_id": "string"
        }
      ],
      "description": "string"
    },
    "type": "twoagents",
    "id": "string",
    "user_id": "string",
    "timestamp": "string",
    "summary_method": "last"
  }
}

**Comment by victordibia** [comment]
@mostafamosa 

Can you describe what you are attempting to accomplish in more detail? What is your use case, what endpoitn are you trying to call etc?
