### ISSUE TITLE
[Issue]: autogen+IntelliLex

### ISSUE THREAD

**Issue by hherpa** [microsoft/autogen#1297]
### Describe the issue

A global list of updates that IntelliLex offers for autogen:

1. Autogen-conveyor is a fully automated tool that allows you to create a multi-level system for performing complex tasks

2. A new class of agents - ClI_Agent

3. Agent typing; universal precision enhancement agent; autogen universal agent exchange platform

4. Conveyer2Autogen - our application of Autogen-Conveyor technology to automatically create an autogen group chat (single department)

5. Conveyer2Conveyer - our application of Autogen-Conveyor technology to automatically create a conveyor (n-number of departments)

Documentation: https://github.com/hherpa/IntelliLex

@sonichi @LinxinS97 @jieu

**Comment by sonichi** [comment]
@JieyuZ2 is the right id

**Comment by rysweet** [comment]
unclear what the request is here. reopen with more detail if you want to continue
