### ISSUE TITLE
When will AutoGen Studio support agents with RAG

### ISSUE THREAD

**Issue by shanmu-raoyunfei** [microsoft/autogen#1298]
When will AutoGen Studio support agents with RAG

**Comment by gagb** [comment]
Hi @shanmu-raoyunfei supporting contrib agents is on the roadmap https://github.com/microsoft/autogen/issues/737 but it's pending in lieu of other urgent features. Contributions are welcome.

**Comment by fil512** [comment]
I found one here.  Works great!

https://github.com/madtank/autogenstudio-skills/tree/main/rag

**Comment by victordibia** [comment]
Closing for now as not planned.
