### ISSUE TITLE
skill browsing, searching, and uploading

### ISSUE THREAD

**Issue by Darker117** [microsoft/autogen#1299]
### Is your feature request related to a problem? Please describe.

i dont know how to code.

### Describe the solution you'd like

possibly implement a function where you can upload your own functions straight from the autogen studio web ui, others can search for a skill that others have made so they could implement them into their own projects possibly? idk

**Comment by victordibia** [comment]
Hi @Darker117,

Thanks for this, 
We are are working on a way to host a gallery where we can all share skills, and it is on the autogenstudio [roadmap]
(https://github.com/microsoft/autogen/issues/737)

Public gallery for agents, workflows, skills, sessions (logs)

Currently, you can paste in your own function (skills -> new skill). But his could be improved to be more user friendly (e.g., use the LLM to assist in geenerating the skill).

**Comment by Darker117** [comment]
ok and what about the usage of services like LM studio that has local inference servers? how do we use those with the autogen studio. currently thats what im using right  now for my LLMs. just can never seem to find any documentation for anything!

**Comment by alew3** [comment]
> ok and what about the usage of services like LM studio that has local inference servers? how do we use those with the autogen studio. currently thats what im using right now for my LLMs. just can never seem to find any documentation for anything!

Just turn on Local Inference Server on LM Studio and point the endpoint to localhost, it mimicks the OPENAI API. This is a tutorial with an older version of autogen (BTW: I think api type used to be open_ai, and now it is openai) https://www.youtube.com/watch?v=10FCv-gCKug

**Comment by sonichi** [comment]
@jackgerrits for documentation roadmap
