### ISSUE TITLE
Moving function execution out of UserProxyAgent to be an openai util

### ISSUE THREAD

**Issue by yiranwu0** [microsoft/autogen#13]
The `_execute_function` is static and independent of `UserProxyAgent`.  Moving it out doesn't affect the functionality of `UserProxyAgent`, but allow more builds with oai.Completion + function execution. Any comments?

**Comment by varshneydevansh** [comment]
I would love to work on this challenge?  Can you assign this to me @sonichi  =)

**Comment by sonichi** [comment]
> I would love to work on this challenge? Can you assign this to me @sonichi =)

Could you discuss with @kevin666aa about the plan first?

**Comment by varshneydevansh** [comment]
Okay Sonichi =) I will wait for the @kevin666aa for the reply.
