### ISSUE TITLE
Please add "engine" param in OAI_CONFIG_LIST

### ISSUE THREAD

**Issue by arindamcodes** [microsoft/autogen#130]
Please add "engine" param for Azure OpenAI in the "OAI_CONFIG_LIST", else it will give you resource not found error

sample:
[
    {
        "model": "your_model",
        "engine": "your_deployment_name",
        "api_key": "your_api_key",
        "api_base": "your_api_base",
        "api_type": "azure",
        "api_version": "2023-07-01-preview"
    }
]

**Comment by thinkall** [comment]
Hi @arindamcodes , please remove key engine and replace key model with your_deployment_name?

**Comment by arindamcodes** [comment]
@thinkall it worked for me in both way. When I added engine param it worked for me and when I replaced model with deployment name, it also worked for me. Thanks much.
