### ISSUE TITLE
[Issue]: why only access UI through localhost?

### ISSUE THREAD

**Issue by hotsmile** [microsoft/autogen#1302]
### Describe the issue

i use pip to install autogen studio, i can use localhost to access the UI, 
but i can't use the ipv4 to access UI , i want to know the issue ,how to solve it?

**Comment by victordibia** [comment]
Hi @hotsmile, 
Can you provide more details on what you mean by "can't use the ipv4 to access UI" and your broader use case?
AutoGenstudio uses a fastapi underneath. Perhaps articles like [this](https://stackoverflow.com/questions/60098005/fastapi-starlette-get-client-real-ip) might help?

@shhdgit, any thoughts or insights into this issue?

**Comment by mokshablr** [comment]
@hotsmile try using the --host and --port flags
I think you wanted to view the autogenstudio ui from other devices connected to the same network?

Try: `autogenstudio --host <host device's ip address> --port <whatever port you want to host it on>`
Then you can go to the url on any device connected to the same network and view the UI.

**Comment by victordibia** [comment]
Thanks for the note @mokshablr. 
@hotsmile , let us know if that works.

**Comment by penthoy** [comment]
Thank you @mokshablr, took me hours to trouble shoot this until I find your post, I think this should be noted on https://github.com/microsoft/autogen/tree/main/samples/apps/autogen-studio

**Comment by victordibia** [comment]
A note on using the host parameter has been added to the readme. Thanks.
