### ISSUE TITLE
[Bug]: In Autogen Studio all workflows disappeared and can not create new ones

### ISSUE THREAD

**Issue by vanetreg** [microsoft/autogen#1305]
### Describe the bug

After updating Autogen Studio on 16th. Jan. '24 both 2 default workflows and one created by me has disappeared and I'm not able to create a new one.
Terminal message is:
```
INFO:     127.0.0.1:49659 - "GET /page-data/gallery/page-data.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:49659 - "GET /page-data/gallery/page-data.json HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:49659 - "GET /component---src-pages-gallery-index-tsx-25eaa0ea2f26f1c4361f.js HTTP/1.1" 200 OK
1 validation error for AgentWorkFlowConfig
type
  Input should be 'twoagents' or 'groupchat' [type=literal_error, input_value='default', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/literal_error
```
I was able to create a new Skill and a new Agent though.

Note front end error message contains different info than backend terminal, but not able to copy it since it disappears quickly...

### Steps to reproduce

1) update to the referred versions below
2) check your Workflows at Build/ Workflows
3) Try to create a new Workflow

### Expected Behavior

I can see the existing 2, default Workflows and I'm able to create new ones.

### Additional Information

Autogen Studio: 0.0.27a0
Autogen: 0.2.0
Windows 10
Python 3.11.6
Cursor IDE

**Comment by victordibia** [comment]
Hi,

This is related to a change in db schema across versions. 
The solution is delete the db and restart autogenstudio. You can delete the database by uninstalling and reinstalling autogenstudio (creating a brand new virtual environment is recommended.)

Going forward we will implment db versioning (and some migration) to manage schema changes.
