### ISSUE TITLE
[Issue]: speaker selection when specified 

### ISSUE THREAD

**Issue by Srivishnu27feb** [microsoft/autogen#1308]
### Describe the issue

I have a list of agents for example sde1, sd2, TeamManager and I have set max round as 3,  when I ask a query "hey Sd2, Can you help me with somethin", the first speaker selection is right but in the second round another speaker is getting chosen and is replying.. my expected output would be as soon as the sd2 speaks the chat should get terminated..

I am not sure where I am going wrong and need your inputs on this.

### Steps to reproduce

I have a list of agents for example sde1, sd2, TeamManager and I have set max round as 3,  when I ask a query "hey Sd2, Can you help me with somethin", the first speaker selection is right but in the second round another speaker is getting chosen and is replying.. my expected output would be as soon as the sd2 speaks the chat should get terminated..

**Comment by gagb** [comment]
Can you please share your code?
