### ISSUE TITLE
[Bug]: Autogen Studio - Changing Models in Agents

### ISSUE THREAD

**Issue by 3hx** [microsoft/autogen#1310]
### Describe the bug

After changing the model for userproxy, and primary_assistant agents. The agents don't use that model, when creating a new workflow.

Agents:
<img width="1277" alt="image" src="https://github.com/microsoft/autogen/assets/63882468/4e19d920-8d02-4af2-8aac-4331329230e5">

New Workflow:
<img width="1259" alt="image" src="https://github.com/microsoft/autogen/assets/63882468/d97c6cc6-b79e-4b84-a6d8-aa81197aa5f9">

**Comment by victordibia** [comment]
Hi @3hx ,

Thanks for mentioning this. 
New workflow shows a default sender/receiver which you can replace with any of your existing agents. There is a dropdown at the bottom of the screenshot you shared. Selecting an agent there should load the agent config you configured previously.



![Image](https://github.com/microsoft/autogen/assets/1547007/5132cc0d-05ee-4a0b-ac7e-358361eaac7a)


There is a lot of room to still improve this UX, changes/updates coming!

**Comment by monuminu** [comment]
Models are not getting saved in the workflow
