### ISSUE TITLE
[AutoGen Studio]: Error occurred while retrieving workflows

### ISSUE THREAD

**Issue by vipervs** [microsoft/autogen#1326]
### Describe the bug

when clicking on Workflows I get this error "Error occurred while retrieving workflows: 1 validation error for AgentWorkFlowConfig type Input should be 'twoagents' or 'groupchat' [type=literal_error, input_value='default', input_type=str] For further information visit https://errors.pydantic.dev/2.3/v/literal_error"

and it is not possible to add a new workflow

Error occurred while creating workflow: 1 validation error for AgentWorkFlowConfig type Input should be 'twoagents' or 'groupchat' [type=literal_error, input_value='default', input_type=str] For further information visit https://errors.pydantic.dev/2.3/v/literal_error

i have tried to pip uninstall and reinstall autogenstudio with a new Conda env, but no change.

where can I find and delete the db?

**Comment by victordibia** [comment]
This error is due to a some schema differences across versions. 
Please uninstall and reinstall autogenstudio.
