### ISSUE TITLE
[Feature Request]: Add CSV file support to autogenstudio

### ISSUE THREAD

**Issue by pretherford** [microsoft/autogen#1328]
### Is your feature request related to a problem? Please describe.

CSV is a common file format for data exchange that can be easily rendered in react-table. Being able to render (and eventually download) generated CSV in autogenstudio will allow more fluid interaction with 3rd party data and expand the use cases for integrating with legacy APIs and non-API data sources.

### Describe the solution you'd like

I propose adding:
- [ ] CSV_EXTENSIONS file_type to utils/utils.py
- [ ] CsvLoader component to frontend/src/components/atoms.tsx
- [ ] is_csv logic in frontend/src/components/playground/metadata.tsx

### Additional context

![metadata](https://github.com/microsoft/autogen/assets/48058/3da59fc0-31f0-4818-a7e6-ecc85d525719)
![csvloader](https://github.com/microsoft/autogen/assets/48058/957e491f-1f2b-4c46-9631-9eb9c20573b7)
![csv view](https://github.com/microsoft/autogen/assets/48058/e88961a4-e788-43ac-b7f9-4d0309821d65)

**Comment by victordibia** [comment]
@pretherford 
Sounds great!
I think the directions you propose make sense!
Do you want to take this on? I am more than happy to help you, provide reviews along the way!

**Comment by pretherford** [comment]
@victordibia 
Sure!  I will use the autogenstudio branch and create a pull request when it is ready to review. Thanks for your help!

**Comment by pretherford** [comment]
@victordibia I have committed my changes locally and am ready to push the autogenstudio branch. Am I authorized?

**Comment by victordibia** [comment]
Great!
Can you create a PR to merge your changes into the autogenstudio branch? This way, we can discuss any related changes in a clean PR.
What do you think?
