### ISSUE TITLE
[Feature Request]: Define LLM config as a separate build place

### ISSUE THREAD

**Issue by BGW1001** [microsoft/autogen#1329]
### Is your feature request related to a problem? Please describe.

Having to define the same config for a LLM in the Agents and Workflows is clumsy and repetitive. It would be useful to define the LLM config once and then just select them when needed. 

### Describe the solution you'd like

Drop down selection of the created LLM configs.

**Comment by ekzhu** [comment]
Thanks! Can you show an example code snippet to demonstrate?

**Comment by victordibia** [comment]
@BGW1001 ,
Thanks for the note. I am working on adding model as a top level object on the build UI , such that these model configs get reused.
Your feedback helps prioritize this!! 
Thanks

**Comment by victordibia** [comment]
Hi @BGW1001 ,

Thanks for the note. I agree.
We are currently working to make Models a first class object on the build interface to facilitate reuse like you mention. 
I'll keep this issue updated with progress.

**Comment by victordibia** [comment]
This has been addressed. Will close this out now. Thanks.
