### ISSUE TITLE
[Bug]: API version is not optional

### ISSUE THREAD

**Issue by ip999** [microsoft/autogen#1337]
### Describe the bug

When configuring Azure OpenAI model, the dialogue shows API version is optional:

![image](https://github.com/microsoft/autogen/assets/6312443/fd0de541-33bd-43b5-bb86-9e74f1ebe36d)

however when omitting the API version, the following is displayed when using that workflow in a new session in playground

![image](https://github.com/microsoft/autogen/assets/6312443/0b51f07c-6185-4f55-bd8e-a7d67037b55c)

### Steps to reproduce

As above, clean install, configure Azure OpenAI model, try to use workflow

### Expected Behavior

dialogue should indicate that this is not-optional, after setting the API Version - working as expected

**Comment by Therealkorris** [comment]
I encountered a similar problem and resolved it by setting up a temporary API key from OpenAI. I used the terminal command "export OPENAI_API_KEY='yourkey'" to configure the environment with the key. Then delete the API from OpenAI to be sure it is not being used.

**Comment by cheng-tan** [comment]
Hi, for OpenAI models, API version is optional. But it's required for Azure OpenAI models.

**Comment by gagb** [comment]
Closing because it was addressed
