### ISSUE TITLE
[Feature Request]: Render example notebooks in documentation site

### ISSUE THREAD

**Issue by jackgerrits** [microsoft/autogen#1339]
### Is your feature request related to a problem? Please describe.

There are many, very helpful, example notebooks that are linked to from the website but are rendered on github. The content of these notebooks are not searchable with the website search and I don't think are indexed to the same degree website content is.

### Describe the solution you'd like

By rendering the notebooks as part of the website I think they will be more discoverable and usable. 

One possible way of doing this is: https://github.com/outerbounds/nbdoc-docusaurus

There are services such as Colab and Binder which could additionally be used to make the examples runnable in the browser without the user needing to setup an environment. The rendered notebook page could link out to the Binder/Colab version of the same notebook. That way things all stay in sync.

```[tasklist]
### Tasks
- [ ] Test notebooks in PR checks
- [x] Put in place infrastructure to build in website
```

**Comment by jackgerrits** [comment]
This would also be a good opportunity to tackle #852.

I see a number of notebooks have Colab links, so this could be standardized while completing this issue as well.

**Comment by ekzhu** [comment]
Thanks for the issue. Are you interested in taking on this task? One thing we might want to do in conjunction of this is to organize notebooks into subdirectories of topics.

**Comment by jackgerrits** [comment]
Yes I would like to take it on!

**Comment by nitya** [comment]
@ekzhu @jackgerrits - is there interest in having the notebooks alone hosted in a separate repo (e.g., Azure-Samples/autogen-notebooks) so we can reuse them for standalone workshops to teach people usage by asking them to fork the samples and then walk through various notebooks interactively. (Right now they would have to fork the whole autogen repo). 

Would love to help/contribute to make this happen if so.

**Comment by jackgerrits** [comment]
I feel like at the moment keeping the notebooks in this repo makes sense as it allows us to ensure they stay up to date as autogen evolves. Forking autogen is something that people should feel free to do so and it allows them to hack on inner pieces of autogen if they feel like it

**Comment by jackgerrits** [comment]
Thanks I'll get those fixed. Why weren't they caught by the link checker?

**Comment by jackgerrits** [comment]
There is a system in place for this in 0.2, and 0.4 has this natively with myst nb
