### ISSUE TITLE
[Bug]: Unable to see the workflow

### ISSUE THREAD

**Issue by monuminu** [microsoft/autogen#1340]
### Describe the bug

When I click on Workflow tab in the UI i get the below error

Error occurred while retrieving workflows: 1 validation error for AgentWorkFlowConfig type unexpected value; permitted: 'twoagents', 'groupchat' (type=value_error.const; given=default; permitted=('twoagents', 'groupchat'))

**Comment by victordibia** [comment]
Hi @monuminu ,

Does the solution in #1305 address your issue?

**Comment by monuminu** [comment]
I upgraded to autogenstudio-0.0.28a0 and i got this issue. I had to uninstall , clear the folder and install again. My workflow are lost though !

**Comment by victordibia** [comment]
Sorry about that.  
And yes, we will need some good versioning scheme to deal with database schema compatibility issues like this. 
Added to the roadmap #737

**Comment by gagb** [comment]
Closing as we added it to the roadmap as a feature request
