### ISSUE TITLE
[Issue]: Update AutoGen Studio Readme to invite contributions/specify dev contributions

### ISSUE THREAD

**Issue by gagb** [microsoft/autogen#1341]
### Describe the issue

Possible to improve the Studio readme
- Readme doesn't point to studio devcontainer
- Pointed to up to date roadmap
- Actively invite contributions

**Comment by victordibia** [comment]
Good ideas here. 
@gagb  does the readme [here](https://github.com/microsoft/autogen/tree/autogenstudio/samples/apps/autogen-studio#contribution-guide) address some of these?  



![Image](https://github.com/microsoft/autogen/assets/1547007/9bcedfa4-c9c7-4e9f-a185-73f5a2a0c7b2)

 
Associated PR is [here](https://github.com/microsoft/autogen/pull/1319) . Review help welcome

**Comment by victordibia** [comment]
Looks like this is done, closing for now @gagb
