### ISSUE TITLE
[AutoGen Studio] Add database versioning to manage schema compatibility

### ISSUE THREAD

**Issue by gagb** [microsoft/autogen#1342]
And yes, we will need some good versioning scheme to deal with database schema compatibility issues like this. 
Added to the roadmap #737

_Originally posted by @victordibia in https://github.com/microsoft/autogen/issues/1340#issuecomment-1900949152_

**Comment by victordibia** [comment]
@monuminu , following up on our conversation, it would be great to get some help in improving the local db for autogen at the moment.
Some thoughts. 
- Keep track of database version in a db table 
- Keep track of db version in version.py. This gets incremented each time there is a schema update
- On db init or db load, check if the current db version matches some db version.py. If not, run throw a meaningful error message (or run a migration script)

**Comment by rysweet** [comment]
@victordibia is this still an issue?

**Comment by victordibia** [comment]
Current version has a versioning scheme using sqlmodel.
Some additional work needs to be done for automatic migration.

But will close this for now.
