### ISSUE TITLE
[P2] Stream messages from agents to UI as they are generated

### ISSUE THREAD

**Issue by victordibia** [microsoft/autogen#1344]
Currently, AutoGen studio shows the final response of agents.
This issue is meant to discuss approaches to stream intermediate LLM or agent results to the UI, to improve the user experience 

Possibly related to #1290

**Comment by tyler-suard-parker** [comment]
Hello Dr. Dibia.  I found a solution for this.  I am using a singleton class in a file in the autogen/oai directory.  I import that singleton class into my top script, and I store my websocket as a variable in that class.  I also modify autogen/oai/client.py to import that same script and that same websocket, which I can then use to stream data from the _completions_create function in that file.

**Comment by rysweet** [comment]
appears resolved.
