### ISSUE TITLE
[Bug]: After pulish  workflow to gallery, it only shows sccuess, but the website no other things showing

### ISSUE THREAD

**Issue by hellangleZ** [microsoft/autogen#1346]
### Describe the bug

[Bug]: After pulish  workflow to gallery, it only shows sccuess, but the website no other things showing

![image](https://github.com/microsoft/autogen/assets/15274284/9fab08aa-ab07-410d-81d4-8dea6b7ee347)

![image](https://github.com/microsoft/autogen/assets/15274284/fa40a334-d90e-4f0a-9496-b1474a3d6248)

### Steps to reproduce

![image](https://github.com/microsoft/autogen/assets/15274284/8cd1fb94-858a-405b-b8fc-f11ec4c5afe3)

windows 11

**Comment by victordibia** [comment]
@hellangleZ

Can you specify a set of steps you took, e.g., did you create a new session and have chat requests in the session or a brand new session without any requests. 
Also, `autogenstudio` has been updated (currently on v`0.0.32a`), consider updating your version as the issue may already be fixed.

**Comment by hellangleZ** [comment]
> @hellangleZ
> 
> Can you specify a set of steps you took, e.g., did you create a new session and have chat requests in the session or a brand new session without any requests. Also, `autogenstudio` has been updated (currently on v`0.0.32a`), consider updating your version as the issue may already be fixed.

Fixed after update the version, Thanks

**Comment by victordibia** [comment]
Great! Shall we close this out?

**Comment by hellangleZ** [comment]
> Great! Shall we close this out?

sure，thank you
