### ISSUE TITLE
Howto enable verbose logging while executing?

### ISSUE THREAD

**Issue by stevenbaert** [microsoft/autogen#135]
Hi,

Love the project!
Though I didn't find yet howto enable more output logging while the AI is fetching its answers.
You can use autogen.ChatCompletion.start_logging() and then catch logging at the end, but I'd like to see what is doing while it is doing it and what takes time. That way I can optimize/correct the process. Now I don't have any output for 10s of seconds, then the output and then the log. Any manual/ideally chatbot you can point me to for config/docs?

Thanks!
S

**Comment by qingyun-wu** [comment]
@kevin666aa  can you share your experience here?

**Comment by stevenbaert** [comment]
Not sure what you mean explained it in my initial post. Would like to know howto have real-time output and logging of what Autogen is doing and like to know howto do this.

**Comment by kevin666aa** [comment]
Hello,
When you are running a conversation, the conversations are printed out. But when an agent (for example, code execution or openai request) is running, it might need some time before that message is printed out. Do you want a better logging/print, showing that it is waiting for the execution or waiting for API request?

**Comment by stevenbaert** [comment]
Correct, I'd like to see/understand at any time what is happening and how much time that takes.

**Comment by kevin666aa** [comment]
Sure, I will see how to add that feature and let you know when it's ready.

**Comment by sonichi** [comment]
Apparently @kevin666aa is busy with other work and won't be able to do this for a while.
@gagb is aware of this issue. @gagb can this issue be assigned to you?

**Comment by gagb** [comment]
Sounds good -- this is particularly useful for long running jobs.

**Comment by gaborkukucska** [comment]
> Sounds good -- this is particularly useful for long running jobs.
Has this been implemented yet? Thanks!

**Comment by sonichi** [comment]
@gagb could you find somebody to work on this or assign this to a different person?
