### ISSUE TITLE
[Feature Request]: Add a default ChatGPT workflow

### ISSUE THREAD

**Issue by gagb** [microsoft/autogen#1353]
### Is your feature request related to a problem? Please describe.

Current AutoGenStudio ships with complex two agent and group chat workflows. It should also ship with something simpler than these -- a very simple workflow where you can very simply chat with gpt.

### Describe the solution you'd like

- Add ChatGPT agent (use GPT-4, max consecutive reply = 1, very simple system message)
- Add SimpleUserProxyAgent (no code execution, no auto reply)
- Add a default workflow called "ChatGPT workflow" with SimpleUserProxyAgent + ChatGPT agent

This will also serve a basic test to ensure the studio at all time subsumes the simplest version of ChatGPT.

### Additional context

I tried creating a very simple chat workflow with (latest release of) studio and it wasn't easy.

**Comment by gagb** [comment]
cc @victordibia

**Comment by victordibia** [comment]
I really like the idea of a default workflow that works really well! 
This is what the default "General Agent Workflow" was designed to achieve. It has: 

- user proxy with no code execution, human input never and no system message.
- assistant agent with GPT4.  

>  tried creating a very simple chat workflow with (latest release of) studio and it wasn't easy.  

Can we outline the issues here. It perhaps can help us identify better defaults for the General Agent Workflow.

**Comment by gagb** [comment]
Listed some of them here:

https://github.com/microsoft/autogen/pull/1352#issuecomment-1906346730

I think we need to go beyond adding a well tuned workflow -- We need to track user effort to create chatgpt like workflow from scratch. It's almost there!
