### ISSUE TITLE
[Issue]: How to get the output from autogen Agent?

### ISSUE THREAD

**Issue by aaditya25052002** [microsoft/autogen#1354]
### Describe the issue

I have created an autogen file to read the js code and convert that into python but I want to store the output in between a file so that I can use it. Can anyone help me with this?

**Comment by ekzhu** [comment]
If you are using code execution, you can find the file in the directory specified by the `work_dir` parameter in `code_execution_config` of the user proxy agent.

**Comment by aaditya25052002** [comment]
got it, but what if I want to create a chatbot out of it, is there a way to retrieve the message I want?

**Comment by ekzhu** [comment]
If you want to retrieve the file created, you would have to give it a filename. See the doc on code execution config: https://microsoft.github.io/autogen/docs/reference/agentchat/conversable_agent

**Comment by qingyun-wu** [comment]
@aaditya25052002 please refer to examples from this notebook to see how output shall be obtained: https://github.com/microsoft/autogen/blob/main/notebook/agentchat_auto_feedback_from_code_execution.ipynb

And closing this issue, please feel free to re-open an issue if you have more questions. Thanks!
