### ISSUE TITLE
[Feature Request]: Changes made to the llm models in the "Models" tab to carry over everywhere

### ISSUE THREAD

**Issue by AltayYuzeir** [microsoft/autogen#1361]
### Is your feature request related to a problem? Please describe.

When I change a specification for an llm model in the "Models" tab, the change does not carry over to the model specification for the agent or user proxy in the "Agents" and "Workflows" tab. Now, when I make a change in a model in the "Models" tab, I need to go and manually carry over the changes to the already existing agents in the Agents and Workflows tabs. I make 1 change, but need to make the same change in 2 more places. If I double click on the model specification in the Agents or Workflow tab, I can see the old settings for the llm model, and I need to either make the changes manually, or delete the model and assign it again.

### Describe the solution you'd like

I would like all changes made to the llm models made in the Models tab to automatically carry over to the model specifications in the Agents and Workflow tabs, as long as the name of the model is the same. I envision Models tab is the only place where llm model specifications need to be set.

**Comment by gagb** [comment]
@victordibia I added this to the roadmap per our discussion!
