### ISSUE TITLE
[Bug]: Inability to alter the default group chat workflow in Studio

### ISSUE THREAD

**Issue by lydonator** [microsoft/autogen#1363]
### Describe the bug

Whenever I try to add or remove agents in the preconfigured Group Chat Workflow, clicking X to remove them does nothing. 
Editing one of the agents, for example local_assistant, which I get to by just clicking the preconfigured agent within the workflow, doesn't appear to do anything, as once save and I OK out of the flows, going back in just shows the default agents again. 

None of this would be an issue at all if I could create Group Chat Workflows from scratch in Studio, but that doesn't seem to be an option for now.... or is that in itself an issue I'm having?

### Steps to reproduce

1. Click into Workflows
2. Then into Travel Group Chat Workflow
3. Then open the receiver ((group_chat_workflow)
4. Try and add or remove agents

### Expected Behavior

I expect to be able to add and remove agents

### Additional Information

Latest Autogen
Windows 11
Python 3.11.7

**Comment by lydonator** [comment]
Just tried it in Firefox, and seems to be working fine. Chrome issue maybe?

**Comment by victordibia** [comment]
Hi @lydonator ,

As @monuminu mentioned, this issue is fixed in the updated version of autogenstudio.
Please update by 
- creating a new python environement (e..g. using venv or conda). This ensures autogenstudio creates a new version of the db (there are schema updates that may lead to errors)
- reinstalling  `pip install -U autogenstudio`

**Comment by lydonator** [comment]
> Hi @lydonator ,
> 
> As @monuminu mentioned, this issue is fixed in the updated version of autogenstudio. Please update by
> 
> * creating a new python environement (e..g. using venv or conda). This ensures autogenstudio creates a new version of the db (there are schema updates that may lead to errors)
> * reinstalling  `pip install -U autogenstudio`
> 
> Also note that in the updated version, you can create new GroupChat workflows. (see related discussion #1273 )
> 
> * New workflow -> GroupChat
> * Modify the properties of the default group chat, add agents from the list of agenst created in the previous step
> 
>  groupchatnew.mp4

Yes I did all this prior to posting, but thanks for the response. It seems with my setup, the UI will not operate as expected in Chrome. Mozilla browsers seem to be fine. I do more testing with a clean Chrome (no extensions) just to make sure.

**Comment by lydonator** [comment]
Issue seems to have resolved in Chrome after clearing out cache / update to .34 - not sure which if any solved it. Closing bug
