### ISSUE TITLE
Last message in Groupchat doesn't get returned[Issue]: 

### ISSUE THREAD

**Issue by abhishekrai43** [microsoft/autogen#1379]
### Describe the issue

I have registered a function to get real time messages from groupchat, but strangely, the last message is not returned? It does get printed in the terminal, though.

```
        def print_messages(recipient, messages, sender, config):
            if "callback" in config and config["callback"] is not None:
                # Call the provided callback function with the last message
                config["callback"](sender, recipient, messages[-1])
            print("Here is the message")
            print(f"Messages sent to: {recipient.name} | num messages: {len(messages)}")
            return False, None
        # Refresh the chat display 
        self.user_proxy = autogen.UserProxyAgent(self, self.data, self.llm_config)
        self.user_proxy.register_reply(
        [autogen.Agent, None],
        reply_func=print_messages, 
        config={"callback": update_ui_with_new_message},
        )
```

All the rest of the messages are but the last message of the conversation is never there in messages. not sure but Is this a known issue?

**Comment by afourney** [comment]
Does the last message have TERMINATE? Is the GroupChatManager changing the is_termination_msg function?

**Comment by abhishekrai43** [comment]
@afourney No, it's the just like a regular message . use to (chat Manager):  Previously, I was accessing messages with groupchat.messages() that had all the messages, but that shows after the conversation is over, so not very practical. I thought of loggin the chat, but it shows it has been disabled and may be will be re-introduced in some later version of OPEANAIWrapper. 

So, not sure, how to go about fixing this.

**Comment by afourney** [comment]
Can you share the configuration of the GroupChatManager? 

I am particularly curious of the is_terminiation_msg option.

Here are the lines I am eying:
https://github.com/microsoft/autogen/blob/19b5c85034006a8a280b04327cfd0b687712f5f1/autogen/agentchat/groupchat.py#L363C9-L371C80

Notably, the message that has TERMINATE isn't rebroadcast. So, depending on where you are reading messages from, it might be missing (though someone is getting it because it is being printed....probably GroupChatManager)

**Comment by sonichi** [comment]
The last message is not broadcast to other agents. But it is added to `GroupChat.messages`.

**Comment by abhishekrai43** [comment]
@sonichi That's quite an insight. So, that is it then. Thanks a lot , again.

**Comment by dynobo** [comment]
@abhishekrai43 , I'm running into the same issue. How did you solve it for? How do you call your `reply_func` on the last message?

**Comment by sonichi** [comment]
In the latest version, we should have fixed that: the last message is broadcast to every agent. Please report if that's not the case.
