### ISSUE TITLE
RuntimeError: Code execution is set to be run in docker (default behaviour) but docker is not running.

### ISSUE THREAD

**Issue by tyler-suard-parker** [microsoft/autogen#1381]
### Describe the issue

This error appears even when I have no plans to run any code.  It is really annoying, and sometimes I can't set my environment variables to get rid of it.

### Steps to reproduce

Create agents and run them

**Comment by olgavrou** [comment]
Hi @tyler-suard-parker 

This is a recent change that was made for safety around code execution, you can see how to disable the default behaviour [here](https://microsoft.github.io/autogen/docs/FAQ#agents-are-throwing-due-to-docker-not-running-how-can-i-resolve-this) if you wish to do so.

If you are still having trouble can you please add some code so that we can see where the problem is, and let us know your dev operating system, etc

**Comment by sonichi** [comment]
Maybe we can add in the doc about disabling code execution entirely, by setting `code_execution_config=False`

**Comment by tyler-suard-parker** [comment]
Can we just set code execution to be disabled by default?

**Comment by olgavrou** [comment]
This would also be a breaking change; we could consider it for future releases. @sonichi I'll update the documentation

**Comment by ekzhu** [comment]
Code execution should be disabled by default setting `code_execution_config=False` but when in `generate_code_execution_reply` we can put out a logging if code were detected in the incoming message.

**Comment by austinhumes-valtech** [comment]
I just updated to the latest version 0.2.9 and received the error:

```
ERROR: Code execution is set to be run in docker (default behaviour) but docker is not running.
The options available are:
- Make sure docker is running (advised approach for code execution)
- Set "use_docker": False in code_execution_config
- Set AUTOGEN_USE_DOCKER to "0/False/no" in your environment variables
```

even though I had `code_execution_config=False` already, while not using Docker at all. Once I just started Docker Desktop and restarted my Autogen app, it ran without error. Does that mean that Docker just has to be running on the same machine, even if it's not used with Autogen?

**Comment by olgavrou** [comment]
Hi @austinhumes-valtech 
If you had `code_execution_config` set to `False` then it shouldn't complain about docker. Could you provide a sample of your code maybe so that we can investigate?

**Comment by austinhumes-valtech** [comment]
> Hi @austinhumes-valtech If you had `code_execution_config` set to `False` then it shouldn't complain about docker. Could you provide a sample of your code maybe so that we can investigate?

Hi @olgavrou thanks for the quick response! I'm using a group chat. Here's some code samples:

```
class AutogenChat():
    def __init__(self, chat_id=None, websocket=None):
        self.websocket = websocket
        self.chat_id = chat_id
        self.client_sent_queue = asyncio.Queue()
        self.client_receive_queue = asyncio.Queue()  
        
        self.user_proxy = UserProxyWebAgent( 
            name="user_proxy",
            human_input_mode="ALWAYS", 
            system_message="""
                Agent to represent the human user.
                Always provide the user with a easy to understand response, rather than just data. For example, if a large amount of data is returned from a function call, provide the user with a summary of the results instead of the raw API response, for example: 
                1. Item 1
                2. Item 2
                3. Item 3
            """,
            max_consecutive_auto_reply=5,
            is_termination_msg=lambda x: x.get("content", "") and x.get("content", "").rstrip().endswith("TERMINATE"),
            code_execution_config=False
        )

   ...
```
```
class UserProxyWebAgent(autogen.UserProxyAgent):
    def __init__(self, *args, **kwargs):
        super(UserProxyWebAgent, self).__init__(*args, **kwargs)
        self._reply_func_list = []
        self.register_reply([Agent, None], ConversableAgent.generate_oai_reply)
        self.register_reply([Agent, None], ConversableAgent.generate_code_execution_reply)
        self.register_reply([Agent, None], ConversableAgent.generate_function_call_reply)
        self.register_reply([Agent, None], UserProxyWebAgent.a_check_termination_and_human_reply)

    ...
```

Hope that helps! Thanks!

**Comment by ekzhu** [comment]
It only shows the set up for the user proxy, what about the assistant agent? Did you set the `code_execution_config=False` for the assistant agent?

**Comment by sonichi** [comment]
@austinhumes-valtech does this error still occur with the latest version? If so, could you share a little reproducible example?

**Comment by doursand** [comment]
I managed to solved this issue adding a "use_docker": False inside the code_execution_config dict like this : 

`user_proxy = autogen.UserProxyAgent(
    name="user_proxy",
    human_input_mode="NEVER",
    max_consecutive_auto_reply=10,
    is_termination_msg=lambda x: x.get("content", "").rstrip().endswith("TERMINATE"),
    code_execution_config={"work_dir": "web", "use_docker": False},
    llm_config=llm_config_mistral,
    system_message="""Reply TERMINATE if the task has been solved at full satisfaction.
Otherwise, reply CONTINUE, or the reason why the task is not solved yet."""
)`

**Comment by olgavrou** [comment]
Great! this is the intended workaround :) I'll close the issue but feel free to reopen if another issue occurs

**Comment by g-o-o-g-l-e** [comment]
I got RuntimeError: Please ensure Docker is running on your system.

**Comment by g-o-o-g-l-e** [comment]
on the lastest version

**Comment by g-o-o-g-l-e** [comment]
my code is from docker_games import Minecraft

minecraft = Minecraft('creepers_go_boom', '2GB', '/home/stefano/mc_data')
minecraft.add_ports(25565, 25565)
minecraft.accept_license()
minecraft.online_mode()

minecraft.start()

**Comment by ekzhu** [comment]
@g-o-o-g-l-e you need to install docker on your machine

**Comment by honestAnt** [comment]
这是因为autogen集成的docker client走的是默认配置（我的是macos，默认端口是 2375），需要修改DOCKER_HOST来解决。
![image](https://github.com/microsoft/autogen/assets/15356873/87ff98e0-e7df-4cce-b5f1-8cabca966264)

所以可以在环境变量中加入DOCK_HOST配置可以解决
![image](https://github.com/microsoft/autogen/assets/15356873/0aa671c0-5437-43cf-8912-3b2017f4b033)
![image](https://github.com/microsoft/autogen/assets/15356873/981620f2-8895-4fdb-a39d-095fee5eed9c)

**Comment by g-o-o-g-l-e** [comment]
thanks

**Comment by AbhijitManepatil** [comment]
> I managed to solved this issue adding a "use_docker": False inside the code_execution_config dict like this :
> 
> `user_proxy = autogen.UserProxyAgent( name="user_proxy", human_input_mode="NEVER", max_consecutive_auto_reply=10, is_termination_msg=lambda x: x.get("content", "").rstrip().endswith("TERMINATE"), code_execution_config={"work_dir": "web", "use_docker": False}, llm_config=llm_config_mistral, system_message="""Reply TERMINATE if the task has been solved at full satisfaction. Otherwise, reply CONTINUE, or the reason why the task is not solved yet.""" )`

`"use_docker": False ` works
