### ISSUE TITLE
[Bug]: In Autogen Studio I'm not able to add new LLMs to Agents, having "No models found" modal as response

### ISSUE THREAD

**Issue by vanetreg** [microsoft/autogen#1385]
### Describe the bug

In Autogen Studio, after removing all models from an Agent, I'm not able to add new LLMs to Agents, having "No models found" modal as response.
It also happens with userproxy Agent...
( I want to add some LLMs of HF inference )
Terminal messages doesn't contain useful info I think

### Steps to reproduce

Try to create a new Agent, remove all existing LLMs of it and try to add a new one, you won't be able to!

### Additional Information

Autogen: 0.2.7 (latest AS update didn't update it to 0.2.8)
Autogen Studio: 0.0.34a0
OS: Win 10
Python: 3.11.6

**Comment by rajan-chari** [comment]
A few questions that might help trouble-shoot this a bit further:
1) Are you changing the agent under "Agent" tab or the "Workflow" tab?
2) Do you see any errors in the command prompt where you started the ui?

**Comment by vanetreg** [comment]
Hey @rajan-chari 
thanks for your response!

Re:1: In Agent tab, editing my new Agent, I don't have any model added and I can not add more, in Workflow, editing the same Agent, I see one model ( Zephyr-7B from Hugging Face inference, as intended)

Re: 2: no, I don't, even though on Agents tab, if I check primary_assistant, i see all 3 default LLMs ( gpt-4-1106-preview, gpt-3.5-turbo-16k, TheBloke/zephyr-7B-alpha-AWQ )

Re:3: no. 
Pls check:
```
INFO:     Started server process [20092]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8081 (Press CTRL+C to quit)
INFO:     127.0.0.1:52402 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:52402 - "GET /app-cfe43a78b791cec99658.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52403 - "GET /images/svgs/welcome.svg HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:52402 - "GET /framework-0e118549f33203964972.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52403 - "GET /webpack-runtime-afb4fb4bf224baf29a5c.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52402 - "GET /page-data/app-data.json HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:52403 - "GET /page-data/index/page-data.json HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:52403 - "GET /318ce576f236b79fd96f75904c13f6e55c3eee57-5645939949987e6d4382.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52402 - "GET /6c05b3ab656a8bfc225a64b3d73a36a92f83c05e-cd604bbac19007063e65.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52404 - "GET /component---src-pages-index-tsx-2342fef3effa18a4d864.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:52407 - "GET /manifest.webmanifest HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:52403 - "GET /api/sessions?user_id=guestuser@gmail.com HTTP/1.1" 200 OK
INFO:     127.0.0.1:52402 - "GET /api/version HTTP/1.1" 200 OK
INFO:     127.0.0.1:52403 - "GET /api/sessions?user_id=guestuser@gmail.com HTTP/1.1" 200 OK
INFO:     127.0.0.1:52403 - "GET /api/messages?user_id=guestuser@gmail.com&session_id=f3993c04-58f7-4c93-b824-64b8014180c0 HTTP/1.1" 200 OK
INFO:     127.0.0.1:52403 - "GET /api/messages?user_id=guestuser@gmail.com&session_id=f3993c04-58f7-4c93-b824-64b8014180c0 HTTP/1.1" 200 OK
INFO:     127.0.0.1:52469 - "GET /page-data/gallery/page-data.json HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:52470 - "GET /page-data/build/page-data.json HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:52470 - "GET /page-data/gallery/page-data.json HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:52469 - "GET /page-data/build/page-data.json HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:52469 - "GET /component---src-pages-gallery-index-tsx-420b66f4c65df1ff9c5c.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:52470 - "GET /component---src-pages-build-tsx-58ddda806aafef1d02d8.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:52505 - "GET /api/workflows?user_id=guestuser@gmail.com HTTP/1.1" 200 OK
INFO:     127.0.0.1:52505 - "GET /api/models?user_id=guestuser@gmail.com HTTP/1.1" 200 OK
INFO:     127.0.0.1:52556 - "GET /api/agents?user_id=guestuser@gmail.com HTTP/1.1" 200 OK
INFO:     127.0.0.1:52556 - "GET /api/models?user_id=guestuser@gmail.com HTTP/1.1" 200 OK
INFO:     127.0.0.1:52563 - "GET /api/agents?user_id=guestuser@gmail.com HTTP/1.1" 200 OK
INFO:     127.0.0.1:52563 - "GET /api/agents?user_id=guestuser@gmail.com HTTP/1.1" 200 OK
INFO:     127.0.0.1:52563 - "GET /api/models?user_id=guestuser@gmail.com HTTP/1.1" 200 OK
INFO:     127.0.0.1:52575 - "GET /api/agents?user_id=guestuser@gmail.com HTTP/1.1" 200 OK
INFO:     127.0.0.1:52575 - "GET /api/agents?user_id=guestuser@gmail.com HTTP/1.1" 200 OK
INFO:     127.0.0.1:52576 - "GET /api/models?user_id=guestuser@gmail.com HTTP/1.1" 200 OK
INFO:     127.0.0.1:52724 - "GET /api/models?user_id=guestuser@gmail.com HTTP/1.1" 200 OK
INFO:     127.0.0.1:52724 - "GET /api/models?user_id=guestuser@gmail.com HTTP/1.1" 200 OK
INFO:     127.0.0.1:52792 - "GET /api/models?user_id=guestuser@gmail.com HTTP/1.1" 200 OK
```

Re:4: screenshot doesn't add more info to what I've shared.

**Comment by victordibia** [comment]
Hi @vanetreg 

Thanks for noting this issue. We are working to improve the UX for autogenstudio.
The current expected workflow is that 

- Build -> Models ... create a model 
- Build -> Agents ... in the add button under agents, the models created in the previous step show up. It makes a copy of that model and adds it to the agent config. This is the same behavior for adding models in workflows
 
The add model button shows a list of the models that **have been previously created** in the Models tab. Can you confirm that you have models in the models tab? 


https://github.com/microsoft/autogen/assets/1547007/69882e9b-1953-4b76-8adb-6d06bb8c5764

**Comment by vanetreg** [comment]
Hi @victordibia 

no, like I responded to the 2nd question of your colleague: 
Q:
"2. Under Build (on top) -> Models (on left) do you see any models?"
A:
"Re: 2: **no, I don't, even though on Agents tab, if I check default primary_assistant, i see all 3 default LLMs** ( gpt-4-1106-preview, gpt-3.5-turbo-16k, TheBloke/zephyr-7B-alpha-AWQ )"

Ok, I noted the expected workflow and gonna test this way later,
although it's not clear why can I edit an Agent's LLM setting in 2 different places ( 1) Agents > Edit and 2) Workflow > Agent > Edit ), and can save 2 different LLM settings on the 2 areas...

If it remains this way, pls. add this info to hints, error messages etc.

**Comment by victordibia** [comment]
Thanks @vanetreg 
I agree. 
We need to improve the instructions/hints to indicate the right way to use build tab. Your feedback is helpful. 
I'll update here.

**Comment by vanetreg** [comment]
@victordibia 

pls. note I'm not even able to create a model on Build > Models tab, having error:
```
Error running query with query 
            INSERT INTO models (id, user_id, timestamp, model, api_key, base_url, api_type, api_version, description)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
         and args ('bf9de00f-db8f-4fba-b3a0-65b4004357c3', 'guestuser@gmail.com', '2024-01-24T20:43:19.471505', 'gpt-4-1106-preview', None, None, None, None, 'Sample model'): table 
models has no column named description
Traceback (most recent call last):
  File "D:\Projects\AI_testing\AutogenStudio\autogenstudio-venv\Lib\site-packages\autogenstudio\web\app.py", line 372, in create_user_models
    models = dbutils.upsert_model(model=req.model, dbmanager=dbmanager)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\AI_testing\AutogenStudio\autogenstudio-venv\Lib\site-packages\autogenstudio\utils\dbutils.py", line 342, in upsert_model
    dbmanager.query(query=query, args=args)
  File "D:\Projects\AI_testing\AutogenStudio\autogenstudio-venv\Lib\site-packages\autogenstudio\utils\dbutils.py", line 265, in query
    raise e
  File "D:\Projects\AI_testing\AutogenStudio\autogenstudio-venv\Lib\site-packages\autogenstudio\utils\dbutils.py", line 257, in query
    self.cursor.execute(query, args)
sqlite3.OperationalError: table models has no column named description

INFO:     127.0.0.1:64792 - "POST /api/models HTTP/1.1" 200 OK
```

**Comment by victordibia** [comment]
It appears you have an earlier version of autogenstudio . Let us do the following to upgrade your version 

- pip uninstall autogenstudio 
- delete this folder D:\Projects\AI_testing\AutogenStudio\autogenstudio-venv\Lib\site-packages\autogenstudio (use something like the command below ...)
   - D:\Projects\AI_testing\AutogenStudio 
   - rmdir /s /q autogenstudio-venv\Lib\site-packages\autogenstudio
- reinstall - pip install -U autogenstudio  
- run - autogenstudio ui

**Comment by toreon78** [comment]
> Try to create a new Agent, remove all existing LLMs of it and try to add a new one, you won't be able to!

It still says always GPT4 in the title of the base model. Is this still not fixed? This is really frustrating? I cannot even uninstall then reinstall. It still has the wrong context.
