### ISSUE TITLE
[AutoGen Studio] Add Friendly Title to Sessions

### ISSUE THREAD

**Issue by victordibia** [microsoft/autogen#1391]
Currently, sessions in autogenstudio have the associated workflow title and a session id. 
This issue will explore methods to generate a friendly name for each session 
- Allow edition of session names
- Stretch
   - track conversation in UI, if there are more than 2 user messages, 
   - Either use first message as friendly name or generate friendlyname using llm. 
   - Update session data descriiption field in db

**Comment by manasadepu** [comment]
First time contributor here, can I take this?
