### ISSUE TITLE
[Feature Request]: Autogen Studio - Exposing environment variables to certain agents/skills

### ISSUE THREAD

**Issue by mathieu-heyarctic** [microsoft/autogen#1392]
### Is your feature request related to a problem? Please describe.

I need environment variables added to certain agent skills. Things like application secrets, etc.

### Describe the solution you'd like

Simple Key:Value table that allows me to input ENV values that are added on agent skill execution

**Comment by victordibia** [comment]
Thanks @mathieu-heyarctic, 
This could be an excellent first issue.

A couple of solutions come to mind 

## .env Environment Variable File 
- AutoGen Studio currently takes an appdir argument. e.g., `autogenstudio ui --appdir /hom/user/data/mydata`. If this is supplied, it will use that directory as the main directory for storing app files (db, generated files etc). 

## Add secrets to the Skills Object 
- Modify AutoGen studio such that the skills have a secrets field that can be defined in the json spec and UI
- Backend 
   - update Skills data model and dbutils.py, add  a secrets field (array of key value pairs)
   - update workflowmanager such that these secrets are instantiated when skills.py is created
- Frontend
  - Update the new skills UI to also collect an array of secrets (key value pairs) 

I am happy to help/guide this.

**Comment by jtoy** [comment]
I like the suggestion to check the appdir for an .env file. @victordibia should home ~/ also be checked for an .env file?

**Comment by jtoy** [comment]
@victordibia I was just reading the code,  you already implemented this , can we close this issue.

**Comment by victordibia** [comment]
Yes, this has been fixed. 
Thanks for reviewing. We can close this out.

**Comment by prwani** [comment]
hi @victordibia , I have configured "AZURE_OPENAI_API_KEY" in Autogen studio's "Environment Variables" section. Now, when I go to Azure OpenAI model definition page, how can I specify this environment variable under "API_KEY" text box ? If I leave that empty and click on "Test" button in model configuration page , it throws this error - "Error testing model component: Connection error.". Can you please suggest how to use environment variables in model configuration page ? Is this supported today ?

**Comment by victordibia** [comment]
hi @prwani , can you configure AZURE_OPENAI_API_KEY as an environment var **before running autogenstudio**?  Or add it directly in the API.  
The  env variable here is only set just before a task is run (intended for tools), so it may not be available during "test model"

**Comment by prwani** [comment]
Thanks @victordibia for your suggestion. Following steps worked for me -
1. Add "AZURE_OPENAI_API_KEY" as an environment var before running autogenstudio
2. In the model configuration page, remove "api_key" from "JSON Editor" (both key and value need to be removed, just leaving empty value i.e.["api_key":""] also causes error)
3. In the model configuration page, "Test" button works fine
4. "Test team" also works fine.
