### ISSUE TITLE
[Bug]: check_can_use_docker_or_throw is not raising an exception if code is running in docker container

### ISSUE THREAD

**Issue by davorrunje** [microsoft/autogen#1395]
### Describe the bug

If the code is running in docker container, `check_can_use_docker_or_throw` should raise an exception.

### Steps to reproduce

Start VS Code from dev container and call `check_can_use_docker_or_throw(True)`. It should raise an exception but it is not.

**Comment by qingyun-wu** [comment]
Hi @davorrunje, I am just checking if this bug report is still valid? Thanks!

**Comment by davorrunje** [comment]
@qingyun-wu not sure, I'll check it today

**Comment by rysweet** [comment]
looks stale, can't reproduce.
