### ISSUE TITLE
[Bug]: Agents continue conversation after task is solved

### ISSUE THREAD

**Issue by tyler-suard-parker** [microsoft/autogen#1406]
### Describe the bug

Agents don't know when to terminate, and keep talking to each other after the task has been solved.  I am trying to make a chat that is powered by agents, so this behavior is a little distracting for the user.

Example:

Question: What kind of steel fittings should I use for Trichloroethane?

Answer: The search results suggest that for applications involving Trichloroethane fluid, stainless steel fittings are recommended.  Source: Parker Catalog and Documents.CONTINUEI'm here to assist you further. How may I help you with Parker-Hannifin products or any other inquiries you might have?CONTINUEIt seems there might be a misunderstanding. If you have any more questions or need further assistance with Parker-Hannifin products, please let me know how I can help you. If you're done with your inquiries, please let me know, and we can end our session.

### Expected Behavior

The conversation should have ended after the answer was complete.

**Comment by afourney** [comment]
Termination is tricky. It depends at least on:

1. The model (small models often have trouble)
2. The agent system prompts (the AssistantAgent has a default prompt that take care of this, but if you set your own, then ¯\_(ツ)_/¯)
3. The is_termination_msg configuration being used. The default is pretty bad. All the cool kids are using:

```
is_termination_msg=lambda x: x.get("content", "").find("TERMINATE") >= 0
```

Even then, the agents sometimes get it wrong. It's a tough research question, and one we are working on.

**Comment by tyler-suard-parker** [comment]
@afourney thank you for the quick response!  I am doing a RAG process that sometimes requires multiple searches.  As per the notebook example I am using one user proxy agent and one assistant agent.  Would it help the conversation problem if I remove the user_proxy from the chat and only use the assistant?
