### ISSUE TITLE
[Bug]: Incorrect API key provided: sk-samplekey. 

### ISSUE THREAD

**Issue by ruanriqing** [microsoft/autogen#1415]
### Describe the bug

when i use windows condapowershell to set apikey
Report:Error occurred while processing message: Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-samplekey. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

how can i set

**Comment by jackgerrits** [comment]
What method are you using to set your key?

It looks like your API key is set to an example value rather than your own generated key. You can get your OpenAI key using your account [here](https://platform.openai.com/account/api-keys).

There's more documentation about how to configure your LLM endpoints [here](https://microsoft.github.io/autogen/docs/FAQ#set-your-api-endpoints)

**Comment by victordibia** [comment]
The console message above suggests you are using autogenstudio.
You will need to verify the exact key in the agents in your workflow
- if you have OPENAI_API_KEY env variable set and are using openai models, you can leave api key blank in the UI for  your agent in the workflow  
- Set the api_key in the UI for agents in your workflow

**Comment by Clinteastman** [comment]
I had this problem. Delete all your "models" and re-add them with your correct keys.

**Comment by Elle-73** [comment]
hi, I have the same issue. I tried deleting the models and re-added them, I tried new API keys. I also specify the key in env and within the model. But i still get the same error.

**Comment by mgredenberg** [comment]
Same problem here with MacOS. API-Key env variable (OPENAI_API_KEY)  was set correctly before creating virtual environment (Conda) and installing autogen studio.
Also tried to delete all models and add the GPT-4 Model (with and without entering the API Key). Result => Always this error:
Error occurred while processing message: Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-samplekey. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

**Comment by cevatkerim** [comment]
same here. adding the models again or even having the env variable doesnt help.

**Comment by victordibia** [comment]
Thanks for noting this.

If you are seeming `sk-samplekey`, this suggests your workflow is using the default agent key. You can modify this by.

- Build -> Models -> create a new model, **put in your model name and api key**
- Workflow .. go to your workflow, click to edit ... click each agent in the workflow ... remove the model there and add the model you defined in the previous step. 

Go to playground ...

https://github.com/microsoft/autogen/assets/1547007/80b061aa-cabb-411a-9c55-4ab20798c808


Create new session .. select your updated workflow ...

**Comment by mgredenberg** [comment]
victordibia: That doesn't work for me. I did it EXACTLY like in your video.
1) Adding a new Model without entering the API key and I tried also adding a new Model AND entering the API Key.
2) Changed the model in the Agent
3) Tried playground with a new session => Always the same error (sk-samplekey) ;-(

**Comment by mgredenberg** [comment]
victordibia: And as I already mentioned. OPENAI_API_KEY env variable is set correctly and available in the Conda environment.

**Comment by victordibia** [comment]
Thanks.

Two things.

I am investigating a possible bug where the api_key is not read from the env variable correctly in v 0.0.35a (it seems to be set to "" and not read). Can you do a pip install -U autogenstudio to upgrade to latest v0.0.37a.

In my video, I do not put in the api key in the model, but I mention in the instructions that you need to put in **both the model and api key**.  Let me know if you are still having issues.

**Comment by mgredenberg** [comment]
1) I did the upgrade and restarted autogen studio:
Installing collected packages: autogenstudio
  Attempting uninstall: autogenstudio
    Found existing installation: autogenstudio 0.0.35a0
    Uninstalling autogenstudio-0.0.35a0:
      Successfully uninstalled autogenstudio-0.0.35a0
Successfully installed autogenstudio-0.0.37a0

2) I removed all models and added only the GPT4 Model WITH Api Key
<img width="807" alt="Bildschirmfoto 2024-01-26 um 23 56 31" src="https://github.com/microsoft/autogen/assets/21111296/9f445945-1114-415e-a29f-0745793aea0d">


3) I removed the (old) model from the agent and added the new created one:
<img width="803" alt="Bildschirmfoto 2024-01-26 um 23 57 51" src="https://github.com/microsoft/autogen/assets/21111296/dacfc168-1578-4030-8b46-810e7ea98745">

4) Started a new Session in Playground and tried it out:
<img width="1050" alt="Bildschirmfoto 2024-01-27 um 00 00 27" src="https://github.com/microsoft/autogen/assets/21111296/ad1380a9-67a1-4ad1-b03c-7efc9e31f3e5">

Always the same error!

**Comment by saschafitzner-uvw** [comment]
I do the same like mgredenberg, but nothing works with version v0.0.35a and v0.0.37a

**Comment by SaschaFitzner** [comment]
I do the same like mgredenberg, but nothing works with version v0.0.35a and v0.0.37a

**Comment by swojoe** [comment]
Getting the same issue. 
I've tried: 
  - Cleared Cache
  - Tried removing and adding models
  - Created new API key
  - Blew away all my environments and created new ones
  - Upgraded to v0.0.37a

**Comment by Cantstop2023** [comment]
Had the same issues but figured it out, not sure if it would work for you guys.

Create a new model then delete it.

Use the existing model gpt-4-1106-preview - with your api-key

Then make sure to close everything down, reopen it using a new port and magically worked

**Comment by suredream** [comment]
same here. Try what @Cantstop2023 describe but no magic happened.

**Comment by victordibia** [comment]
Hi, @suredream 

## Update AutoGen Studio

First, let us ensure you are on the latest version of autogenstudio 

- pip uninstall autogenstudio 
- pip install -U autogenstudio 
- autogenstudio ui --appdir newdir 

the last command tells autogenstudio to use `newdir` to store files including creating a new db.

## Set Model and API Key in UI

If you are seeming `sk-samplekey`, this suggests that the agenst in your workflow is using the default agent key `sk-samplekey`. You can modify this by.

- Build -> Models -> create a new model, **put in your model name and api key**
- Workflow .. go to your workflow, click to edit ... click each agent in the workflow ... remove the model there and add the model you defined in the previous step. 

Go to playground ... 
Create new session .. select your updated workflow ... 


> IMPORTANT NOTE: Editing your model does not automatically update your workflow. Each time you edit your model, you will need to manually update your workflow (i.e., remove the previous model on your agent in the workflow and add the new model.).  


https://github.com/microsoft/autogen/assets/1547007/da9eaad2-7ad5-4daa-aa0e-098ad5701e1b

**Comment by notedit** [comment]
same here

**Comment by suredream** [comment]
thanks. @victordibia . Not working.

**Comment by quanhuiyuan** [comment]
@victordibia 
hello! I read all Q&A above and I followed your steps strictly, but I still didn't fix it. I found my  problem changed from
 "`Error occurred while processing message: Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-samplekey. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}`"
 to "`Error occurred while processing message: Error code: 401 - {'statusCode': 401, 'message': 'Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com/), or have expired.'}`" 
 could you help me with it?
 Thank you for your time!!!

**Comment by Cantstop2023** [comment]
I figured it out cause it stopped working for me again.

Before proceeding with anything make sure you do the following in powershell type in n-
$env:OPENAI_API_KEY='your_api_key_here'

The in the powershell type in -
$env:OPENAI_API_KEY

This should then show your API KEY back to you.

Once this is done run autogen -

autogenstudio ui --port 8080

Go to Model and delete all of them except - 
gpt-4-1106-preview

Update - gpt-4-1106-preview - with your api key 

Will use one of the current workflows - 
General Agent Workflow

Once you have clicked on -  
General Agent Workflow
Then select  - 
primary_assistant
delete the model then re-add it.

The go to Playground and select New and select one of the green option Stock Price / Sine Wave

If the API KEY error comes again just open another powershell type - $env:OPENAI_API_KEY and see if it stuck as when i opened autogen studio it did dissapear and i just run it again it worked.

**Comment by rbanks1** [comment]
I'm having the same problem. I decided to try Autogen Studio after I'd been playing around with a code sample for [Semantic Kernel](https://learn.microsoft.com/en-us/semantic-kernel/). I'd assumed the "sk" in "sk-samplekey" was something to do with Semantic Kernel, maybe some weird thing it did on install. Anyone else seeing this bug after also installing Semantic Kernel?

**Comment by victordibia** [comment]
@rbanks1,

What happens exactly when you run the following:

- pip uninstall autogenstudio 
- pip install -U autogenstudio 
- autogenstudio ui --port 8081 --appdir newdir 

Note **autogenstudio ui --port 8081 --appdir newdir** ... note the **--appdir newdir** .
Do you still see the sk-samplekey error?

**Comment by rbanks1** [comment]
Actually, I did the same thing you originally suggested (deleting the models and workflows) and that seems to have fixed it.

**Comment by IainKainos** [comment]
I made these changes and now the error reads;

Error occurred while processing message: 'AgentFlowSpec' object has no attribute 'name'

I've checked everything is named, all of the elements are new and I am using the --appdir  --newdir? 

Any ideas?

**Comment by victordibia** [comment]
@IainKainos ,

What is your autogen studio version?
`pip show autogenstudio`
The error suggests you might be on an older version. Current version in `0.0.42a`

**Comment by suredream** [comment]
@victordibia update to `0.0.42a`, remove app_dir and start over. Same.

**Comment by sonichi** [comment]
I hope this issue is resolved now. If not, please consider joining an office hour on discord.

**Comment by engineerakshat** [comment]
Can someone help?
I am on version 0.0.44.
I am getting this error:
`Error occurred while processing message: Error code: 401 - {'error': {'message': 'Incorrect API key provided: ********. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}`

**Comment by victordibia** [comment]
@engineerakshat ,

That error suggests that one or more of your agents have their key set to ******. 
What you can do ...

- Build -> Model ... Create a model config and test it to verify that it works. **Note that simply creating a new model here does not attach it to your config.**
- Build -> Workflow ... Go through each agent config, remove the previous models and then add the new model you created in the previous step.  If your workflow is a groupchat, you will have to do this for each agent in your group chat, and also for the groupchat agent itself.
- Playground -> new session, select the workflow you just updated. 


https://github.com/microsoft/autogen/assets/1547007/d28d6acb-4f61-429a-a88c-eb8364b2ce48

**Comment by engineerakshat** [comment]
Solved!
I deleted all the models, agents and workflows.
And did everything from scratch.

Thank you for help!

@majacinka @victordibia

**Comment by GihanMora** [comment]
This issue persists for me. Any solution? Tried the steps above mentioned but no luck..

**Comment by engineerakshat** [comment]
> This issue persists for me. Any solution? Tried the steps above mentioned but no luck..

Try following steps which worked for me:
1. Delete all models, agents and workflows.
2. Turn off the autogen studio
3. Start autogen studio
4. Create required models, agents and workflows(avoid editing them)

Should work fine then.
