### ISSUE TITLE
[Issue]: Fix stability of git pre-commit format checks.

### ISSUE THREAD

**Issue by afourney** [microsoft/autogen#1418]
Can we please do something to improve the stability of the pre-commit formatting checks?

I'll pull a fresh copy of the repo, edit one line in one file, and end up failing some pre-commit check in an unrelated part of the code. Sometimes there are even errors in files that I haven't edited, causing the commit to succeed, but the server-side check to fail. Easily half my commits are fixes to these kinds of formatting checks.

I have no idea what is causing the instability. But it is maddening. 

Also, pro-tip:

```
pre-commit run --all-files
```

**Comment by gagb** [comment]
Are you having these issues in code spaces?

**Comment by afourney** [comment]
No. My local Ubuntu LTS dev environment.

(Autogenbench I don't think runs in code spaces due to special docker requirement)

**Comment by jackgerrits** [comment]
It's weird because the pre-commit black version is already pinned
https://github.com/microsoft/autogen/blob/1ab2354009f7be0759da5f824e55d0df2d649ead/.pre-commit-config.yaml#L26

**Comment by jackgerrits** [comment]
This repros in a fresh codespace

**Comment by afourney** [comment]
These latest issues I think are related to the notebooks. It uses a different strategy for running black.

**Comment by sonichi** [comment]
@davorrunje or @bitnom do you have a clue?

**Comment by afourney** [comment]
FWIF, I'm still experiencing this instability with some of my commits. 

I've been working around it by running pre-commit on all files, then staging the changes, then uninstalling pre-commit before committing (other they just change back and forth in a loop)

**Comment by davorrunje** [comment]
Sorry for the late reply, I am just catching up with the backlog. I always use
```
pre-commit run --all-files
```
just to be on the safe side.

@sonichi With respect to notebooks, I added black to notebooks using `nbqa` and never had any issue with it before. Is this still happening?

**Comment by ekzhu** [comment]
@afourney Is this already fixed?

**Comment by afourney** [comment]
It has not happened to me in a while. Perhaps safe to close.

**Comment by ekzhu** [comment]
I love closing issues
