### ISSUE TITLE
Error while fetching server API version

### ISSUE THREAD

**Issue by legaltextai** [microsoft/autogen#142]
I keep getting this error : 

```
--> 221     raise DockerException(
    222         f'Error while fetching server API version: {e}'
    223     )

DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

But I only kept gpt4 api key , don't have azure, could that be a problem? 

Thanks

**Comment by thinkall** [comment]
Hi @legaltextai , thanks for reaching out. Do you have docker installed?

**Comment by legaltextai** [comment]
the docker is fixed and running :-) now, it 's stuck after this command (the arxiv paper exampe): 

```
Please run this Python script to extract the title and abstract of the paper. Based on the content, I will then suggest who should read this news.

--------------------------------------------------------------------------------

>>>>>>>> USING AUTO REPLY...

>>>>>>>> EXECUTING CODE BLOCK 0 (inferred language is python)...
Pulling image python:3-alpine
```

**Comment by sonichi** [comment]
This image doesn't allow pip install. If you need to perform package install, please set `use_docker="python:3"`

**Comment by legaltextai** [comment]
Thank you so much. It worked!

**Comment by antoineross** [comment]
> use_docker="python:3"

Hi! How do we set this? Should it be in the main python file?

**Comment by sonichi** [comment]
It's in [`code_execution_config`](https://microsoft.github.io/autogen/docs/reference/agentchat/conversable_agent#__init__)

**Comment by blueeyes08** [comment]
Is this valid? (doesn’t run for me)

> It's in [`code_execution_config`](https://microsoft.github.io/autogen/docs/reference/agentchat/conversable_agent#__init__)

is this valid? (doesn’t work for me)
code_execution_config = (”work_dir”:”web”, use_docker = ”python:3”,),

When I initially go the error it said
code_execution_config = (”work_dir”:”web”, ”docker”:”python:3”,)

**Comment by thinkall** [comment]
> I just make my first try on autogen with panel UI and it displays the same error. My request is very simple: Ask the system to create an empty txt file on d drive. After I read the comment, I don't understand how the whole system works. Is it use docker to create an docker image which runs python3 to create an empty file for me?

Hi @fenixlam , could you please open a new issue, and paste more details of your settings, code and results? Thanks.
