### ISSUE TITLE
Decide on proper casing of AutoGenBench folder names, and make changes as needed.

### ISSUE THREAD

**Issue by afourney** [microsoft/autogen#1424]
See: https://github.com/microsoft/autogen/pull/1048#issuecomment-1911181577

**Comment by jackgerrits** [comment]
I would vote for all lowercase especially since not all OS filesystems support case sensitivity

**Comment by afourney** [comment]
> I would vote for all lowercase especially since not all OS filesystems support case sensitivity

But OS filesystem case sensitivity only matters if there are two or more files of folders with names that differ only by case. We will have upper case or mixed case names like README.md and Dockerfile already.  I think there is a case to be made about standardization, or about what is "pythonic", but I don't think there's any risk of breaking anything.

**Comment by jackgerrits** [comment]
good point, totally agree
