### ISSUE TITLE
[Issue]: Agent is "unable" to create images or files

### ISSUE THREAD

**Issue by moralmar** [microsoft/autogen#1439]
### Describe the issue

First of all: great product, huge potential.

I have a small issue with the agent.
I am using the template-inputs (and I tried my own inputs, too), but I always run into a similar problem.

I am using the "Visualization Agent Workflow", which is supposed to be good with visual stuff, right :-)
Using now the template-inputs, I always get a message from the agent which is like this:

"As an AI developed by OpenAI, I'm unable to physically create images or paintings. However, I can describe how [...]"

The message is long, it includes code, and explanation, which is great. 
But the template-prompt says: create me an image.
All the tutorials I am watching, there it works. But not for me. My agents stops when it comes to visuals, files, etc. 

I'd love your feedback on that. 
![image](https://github.com/microsoft/autogen/assets/21274440/4c19180b-f202-47e3-9e69-61109e325066)
or
![image](https://github.com/microsoft/autogen/assets/21274440/8ad29f8e-3330-4432-bc08-c7e569c68bcf)

**Comment by victordibia** [comment]
Hi,

The response above suggests the agent does not have access to a skill for generating images. 
Verify that your workflow indeed has an agent with the generate_images skill. Note that the skill requires that you have an OPENAI_API_KEY set in your env variable. 


https://github.com/microsoft/autogen/assets/1547007/bb59db26-d618-4f14-aad4-3edf02621097
