### ISSUE TITLE
[Issue]: Editing a Skill

### ISSUE THREAD

**Issue by AndreVianna** [microsoft/autogen#1442]
### Describe the issue

In Studio, to change a skill, I need to delete and add it again with the new code.
Is that by design or did I mess up the installation?
If it is the current state of things, are there plans to add the capability to change the code of a skill through the studio interface?
Is there a work around?

**Comment by victordibia** [comment]
Hi @AndreVianna ,

Thanks for the feedback. The UX for skills still very much a work in progress. What you describe is the current state of affairs.
We have this on our roadmap #737 , and I have attached this issue.   

## Skill Editor 
A rough draft of what will be implemented as part of this issue:

- [ ] Ability to edit skill - on selection of a skill, open an editor and save updates (addresses the main issue above)
- [ ] Skill Maker: Support a chat based UX where users (who prefer not to write code) can describe their intended behaviors in natural language, and an LLM generates the associated code.  

Happy to get thoughts

**Comment by AndreVianna** [comment]
I think it would be good to make it clear in the documentation. I lost a lot of time thinking that the problem was with me and installing and uninstalling the product and searching for missing libraries and researching tutotial in the web.

Also, as temporary a work around would be good to explain in the documentation that all the entities can be found in the sqlite db created by the studio and you that we can edit the entities directly using a SqLite editor.

For those looking for the same as I the sqlite db can be found at:

"~/miniconda3/envs/[your-env-name]/lib/python[your-python-version]/site-packages/autogenstudio/web/database.sqlite"
I am editing it using vscode SQLite3 Editor extension.

see the screen below for an example:
![image](https://github.com/microsoft/autogen/assets/255868/fcfe476e-2c6d-4875-9a3d-273fedbbd3b6)

**Comment by victordibia** [comment]
Skill Editing is now implemented, with a full-featured code editor interface.
@madtank
@gagb 
https://github.com/microsoft/autogen/assets/1547007/3b98709f-b269-4eb7-9a72-538705ad6a93

**Comment by AndreVianna** [comment]
Fantastic!!!!

I've tested it and it is very good with syntax highlighting and collapsing blocks.
Congratulations.
