### ISSUE TITLE
[Bug]: When tools are used, the Tool Id is unnecessarily prepended to the message.

### ISSUE THREAD

**Issue by afourney** [microsoft/autogen#1455]
### Describe the bug

When tool calls are executed, the response always begins with the tool call's uuid:

https://github.com/microsoft/autogen/blob/6cf5bb00869b3ca2b4b824f491b4a6a2f80b13f7/autogen/agentchat/conversable_agent.py#L953

This id then becomes part of the response text, and is incorporated into the context of all downstream agents. However, this information is **random, adds no information, takes up tokens, and could lead to downstream errors**. 

E.g., here is an excerpt from WebSurfer:

```
user_proxy (to web_surfer):

Find Microsoft's Wikipedia page.

--------------------------------------------------------------------------------
>>>>>>>> USING AUTO REPLY...
>>>>>>>> EXECUTING FUNCTION 
navigational_web_search...web_surfer (to user_proxy):

Tool Call Id: call_nMYIXhUGYcxBtdQ3lAQhqzWv
# Microsoft

American multinational technology corporation...
```

### Steps to reproduce

Just use WebSurfer from #1435

### Expected Behavior

Don't prepend Tool Call Ids

**Comment by sonichi** [comment]
@yenif fyi

**Comment by yenif** [comment]
That's really an artifact of the tools api. The tool_call_id is what ties the response to the call and is required in the api response. If you are not using a preview model then you are never getting multi-call so the distinction probably isn't apparent.

For oai_reply, the content value isn't used, so it doesn't make any difference and the tool_response json is required to have the tool_call_id.

For console output, sending to non oai llms, or for whatever reason something is forcing to string and using 'content'; open to suggestions. The native tool response message does not have the called method or args.

**Comment by yenif** [comment]
If you're concern is specifically the output in the console, that formatted string is only used for the console. The actual response sent to oai is the tool_response hash that contains the unmodified tool output separate from the tool_call_id key.

**Comment by afourney** [comment]
No, I'm not concerned with the console. I'm worried that it ends up in the content string of messages that go to other downstream agents. As an example, here is the output I get when print the messages of a downstream agent: 
![image](https://github.com/microsoft/autogen/assets/4017093/2cb51202-53df-4f67-8e03-4cea513734ae)

**Comment by yenif** [comment]
Sure, can make _str_for_tool_response whatever string representation of tool_responses you want. oai_reply only cares about the value in tool_returns, content is just being filled for backward compatibility.

**Comment by afourney** [comment]
Ok, I'll submit a PR. 

This is the value everyone in a group chat, and everyone downstream gets. There could be any mix of models, so max compatibility is important.
