### ISSUE TITLE
[AutoGen Studio] Test Suite for AutoGen Studio

### ISSUE THREAD

**Issue by victordibia** [microsoft/autogen#1456]
## What 

As AutoGen Studio grows in functionality, it would be great to get more principled about how we add features and general reliability.
A good first step would be to start writing a suite of tests for autogenstudio components.

## Potential Work Items
Some example modules to start writing tests for  

- [ ] workflow manager (loading workflows from json specs, instantiating workflows, testing outcomes and behviours). Could be based on the tutorial [notebook](https://github.com/microsoft/autogen/blob/autogenstudio/samples/apps/autogen-studio/notebooks/tutorial.ipynb)
- [ ] web api [tests](https://fastapi.tiangolo.com/tutorial/testing/)
- [ ] database manager (creation edit, migrations etc)
- [ ] other components

Should follow similar pytest convention used in main autogen [tests](https://github.com/microsoft/autogen/tree/main/test).

**Comment by gagb** [comment]
Great idea!

**Comment by ankit-varma10** [comment]
Hello there! I'm new to this repo, but would like to contribute to the test suite.

Could you please assign this to me? Also, are the any code pointers to get a sense of what an integration should look like.

**Comment by victordibia** [comment]
Hi @ankit-varma10 

We can follow the general convention of the tests in the autogen [main](https://github.com/microsoft/autogen/tree/main/test).
We can start with tests for the workflowmanager, following the notebooks.

**Comment by Hk669** [comment]
@victordibia can we unassign this issue from @ankit-varma10 , seems to be inactive. will open for other first time contributors.

**Comment by victordibia** [comment]
Sounds good to me

**Comment by rysweet** [comment]
@victordibia - do we plan to fix this?

**Comment by victordibia** [comment]
AutoGen Studio does have an early test suite (some progress has been made).
Future work here will focus on the 0.4 version support. 

Closing for now.
