### ISSUE TITLE
[Feature Request]: Studio users can Download, Upload, and Copy to Skills, Models, and Agents 

### ISSUE THREAD

**Issue by kmackett** [microsoft/autogen#1457]
### Is your feature request related to a problem? Please describe.

As a AG studio user,
I would like to download, copy, and upload Skills, Models, and Agents in the UI
So I can cut down on copy and paste toil in the UI
AND I can manipulate the primitives as code.

### Describe the solution you'd like

as an MVP, build it out like the Workflows Copy and Download introduced in 0.0.40a (plus import). 
This could be a good building block for community repos and such

**Comment by victordibia** [comment]
Closing as completed
