### ISSUE TITLE
[Issue]: GroupChat keeps calling all the available agent and doesn't stop even after output from one agent is generated

### ISSUE THREAD

**Issue by saurabhgssingh** [microsoft/autogen#1464]
### Describe the issue

When I have multiple agents configured in a group chat. If the question is very specific to one agent [say text to sql], the group chat manager invokes other agents as well even though they are not required. 

![image](https://github.com/microsoft/autogen/assets/58776330/0140315f-ad6a-44c4-8ab7-ca780ae24350)

### Steps to reproduce

groupchat = GroupChat(
        agents=[user_proxy,coding_assistant,simulator_worker_agent,text_2_sql_agent],
        messages=[],
        max_round=24
    )
manager = GroupChatManager(groupchat=groupchat, llm_config=llm_config)

### Additional Information

AutoGen Version: 0.2.9
Python 3.11

**Comment by ekzhu** [comment]
Can you show your llm_config for the group chat manager? Which model are you using?

One thing we are working on is graph-based group chat, which allows user to add constraints to the speaker transition: #857

**Comment by saurabhgssingh** [comment]
[{
        "model" : "minerva-llm",
        "api_key": "key",
        "base_url": "https://endpoint.openai.azure.com/",
        "api_type": "azure",
        "api_version": "2023-07-01-preview"
}]


groupchat = GroupChat(
        agents=[user_proxy,fetch_schema_agent,simulator_agent],
        messages=[],
        max_round=24
    )
manager = GroupChatManager(groupchat=groupchat, llm_config=llm_config) 

**We are using azure gpt4 turbo model**

**Comment by sonichi** [comment]
How are the text2sql and rag agent defined? Is the "description" field used to describe their roles?

**Comment by rysweet** [comment]
closing as stale - missing info from OP. please reopen I you want to update
