### ISSUE TITLE
[Bug]: AutoGen Studio is forcing default system message

### ISSUE THREAD

**Issue by ranfdev** [microsoft/autogen#1474]
### Describe the bug

AutoGen let's users specify a custom system prompt for each Agent. As a user I would expect AutoGen Studio to do the same, but that's not true, because in line https://github.com/microsoft/autogen/blob/8d1d07308a6dc13d5b36148c3ce2a45e9e2abaa9/samples/apps/autogen-studio/autogenstudio/workflowmanager.py#L128 the default system prompt is always added as a prefix.

Putting the default system prompt as a prefix gives it extreme power, and makes defining the custom wanted behavior harder, especially for small open source models.

### Steps to reproduce

Define a custom agent in AutoGen Studio

### Expected Behavior

I should be able to fully change a system prompt of an agent, as in the AutoGen library

### Additional Information

Maybe add a flag in the web ui to let the user choose
[ x ] Add default prompt as prefix

**Comment by victordibia** [comment]
@ranfdev .. True.
Thanks for pointing this out.
In general, adding the default message works out really well for large models, but can interfere with the behavior of small models that do not follow instructions well. I'll push a fix that only uses default system message if none is provided. 
Does that work?

**Comment by ranfdev** [comment]
Sounds good to me. The default message should be visible somewhere though, so that the user has a starting point to write the custom prompt. 
Maybe you can set, and show, the default system message when creating a new agent.

**Comment by victordibia** [comment]
This behavior has been updated 
- default assistant system_message is used for assistant agents 
- system_message is used as-is in the workflow (not concatenated to previous messages)
