### ISSUE TITLE
Update GAIA agents to use gpt-4-1106-preview and report results

### ISSUE THREAD

**Issue by cheng-tan** [microsoft/autogen#1489]

**Comment by cheng-tan** [comment]
TODO: add new agent to token counting utils to calculate the cost. https://github.com/microsoft/autogen/issues/1270 this bug is also related.

**Comment by afourney** [comment]
@cheng-tan The main GAIA workflow pulls from the "society_of_mind_gaia" branch, which is very out of date by now.  Please hold off on this task until I've had a chance to update that branch (which I plan to do today)

**Comment by afourney** [comment]
Closed. First GPT-4-turbo logs are now available in the Feb2 share.
