### ISSUE TITLE
[Issue]: Is there a way to store chat history in normal autogen assistant like there is a way to store the RAG in ragassistant of autogen?

### ISSUE THREAD

**Issue by aaditya25052002** [microsoft/autogen#1492]
### Describe the issue

Is there a way to store the chat history in autogen's normal assistants like RAGassistants, like the threads in assistants api?
I just want to know if how to store the chats here.

**Comment by sonichi** [comment]
@olgavrou Could you please take a note of this thread and inform @aaditya25052002 when you start working on the serialization or find others working on it?
@aaditya25052002 please let @olgavrou know if you are interested in working on this.
cc @thinkall @ekzhu @randombet @victordibia @gagb

**Comment by aaditya25052002** [comment]
Yes, I will contribute.

**Comment by psymbio** [comment]
Hi, is there a way I could contribute to this?

Are there any meetings to attend/tickets managed for the development of this?

**Comment by rysweet** [comment]
plenty of examples of this in the latest code and contributions
