### ISSUE TITLE
Issues with Adding Custom APIs in Auto Generation

### ISSUE THREAD

**Issue by feiran-jia** [microsoft/autogen#15]
When using the custom ChatCompletion API (refer to https://github.com/lhenault/simpleAI), the `oai.ChatCompletion.create` and `oai.ChatCompletion.tune` functions both produce errors.
One example code is
```Python
    response = oai.ChatCompletion.create(
    messages=[{"role": "user", "content": "hi"}],
    config_list=[
        {
            "model": "stablelm-open-assistant",
            "api_key": os.environ.get("OPENAI_API_KEY"),
            "api_base": "http://127.0.0.1:8080",
            "api_version": None,
        },    
    )
```

Error Details:
```
During handling of the above exception, another exception occurred:

APIError                                  Traceback (most recent call last)
File ~/XXX/FLAML/flaml/autogen/oai/completion.py:196, in Completion._get_response(cls, config, eval_only, use_cache)
    195     else:
--> 196         response = openai_completion.create(request_timeout=request_timeout, **config)
    197 except (
    198     ServiceUnavailableError,
    199     APIConnectionError,
    200 ):
    201     # transient error

File ~/.conda/envs/icl3.9/lib/python3.9/site-packages/openai/api_resources/completion.py:25, in Completion.create(cls, *args, **kwargs)
     24 try:
---> 25     return super().create(*args, **kwargs)
     26 except TryAgain as e:
...
--> 205     error_code = err and err.json_body and err.json_body.get("error")
    206     error_code = error_code and error_code.get("code")
    207     if error_code == "content_filter":

AttributeError: 'str' object has no attribute 'get'
```
To address the issue temporarily, I added the name of my custom model, i.e. "stablelm-open-assistant", to the `chat_models `in the `completion.py` file. This modification enabled the `oai.ChatCompletion.create` function to work without any problems. Based on this experience, I suspect that the issue may not affect the completion API.

However, when I tried to use the `oai.ChatCompletion.tune`, I encountered another error. The error information is
```
File ~/ExampleSelection/FLAML/flaml/autogen/oai/completion.py:661, in Completion.tune(cls, data, metric, mode, eval_func, log_file_name, inference_budget, optimization_budget, num_samples, logging_level, **config)
    659 logger.setLevel(logging_level)
...
--> 404 query_cost = (price_input * n_input_tokens + price_output * n_output_tokens) / 1000
    405 cls._total_cost += query_cost
    406 cost += query_cost

TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

This error is caused by the new model not having any prices specified in the price1K dictionary in completion.py. To address this, I added my custom model's name to the `price1K` dictionary along with a default price (slightly > 0.0). With this modification in place, both the `oai.ChatCompletion.create` and `oai.ChatCompletion.tune` functions work without any further issues.

**Comment by AwesomeYuer** [comment]
@AwesomeYuer

**Comment by ekzhu** [comment]
Consider closing this issue due to stall. @sonichi
