### ISSUE TITLE
[Feature Request]: Agent name validation in UI prior creation

### ISSUE THREAD

**Issue by UTMark** [microsoft/autogen#1507]
### Is your feature request related to a problem? Please describe.

Proposal for agent name validation in the User Interface to disallow unsupported naming conventions to prevent the error message "{name} does not match '^[a-zA-Z0-9_-]{1,64}$".

### Describe the solution you'd like

The front-end should verify the same regex `^[a-zA-Z0-9_-]{1,64}$` and prompt the user to fix the name. 

The current regex seems to describe that it is Alpha-numerical with no symbols or spaces with a maximum length of 64 characters and a minimum character length of 1. Underscores and dashes are allowed.

Proposal to first check for length and return length based error if found.
Proposal to then check for "alpha-numerical" condition and return error if found.

If error is found, do not create a new agent.

### Additional context

Provided is a screenshot of said error:

![image](https://github.com/microsoft/autogen/assets/153741058/da984d13-2ed3-4a6d-bc27-df1cd89d0749)

**Comment by victordibia** [comment]
Thanks for mentioning this .. a message is now shown that asks the user to update the agent name

<img width="762" alt="image" src="https://github.com/microsoft/autogen/assets/1547007/dd876efd-21ad-47f5-a3da-671f0bfdc17e">
