### ISSUE TITLE
user proxy agent returns empty message

### ISSUE THREAD

**Issue by muhammed-enes-koroglu** [microsoft/autogen#151]
When the assistant asks something to the user proxy or when it prompts for an answer, sometimes the user proxy keeps giving no answer. 

EXAMPLE: 

Read the snake_game.py. It should be a basic and classical snake game, however the it says 'game over' as soon as the game begins. Why is that? Suggest a fix and implement it.

--------------------------------------------------------------------------------
assistant (to user_proxy):

To understand why the game over message is displayed as soon as the game begins, we need to analyze the code in the `snake_game.py` file. Please provide the content of the `snake_game.py` file so that we can examine it and suggest a fix.

--------------------------------------------------------------------------------

>>>>>>>> USING AUTO REPLY...
user_proxy (to assistant):

--------------------------------------------------------------------------------
assistant (to user_proxy):

I apologize, but I cannot see the content of the `snake_game.py` file. Could you please copy and paste the code here so that I can analyze it and suggest a fix?

--------------------------------------------------------------------------------

>>>>>>>> USING AUTO REPLY...
user_proxy (to assistant):

--------------------------------------------------------------------------------
assistant (to user_proxy):

I'm sorry, but I still don't see the content of the `snake_game.py` file. Could you please provide the code so that I can help you with the issue?

--------------------------------------------------------------------------------

>>>>>>>> USING AUTO REPLY...
user_proxy (to assistant):

--------------------------------------------------------------------------------

**Comment by craighulme** [comment]
i seem to be getting this issue, only started occuring when i switched to groupchats. I also added terminate so it auto executes. but it never allows me to respond back, it skips my response with empty string/response also.

**Comment by sonichi** [comment]
Did you set "human_input_mode" to "NEVER"? If you set it to "ALWAYS", it should allow you to provide input.

**Comment by muhammed-enes-koroglu** [comment]
> Did you set "human_input_mode" to "NEVER"? If you set it to "ALWAYS", it should allow you to provide input.

I don't want to be involved in each back-and-forth between the agents. I just want the end result. Btw, it also has the same problem with simple assistant and user proxy agent. I used the given code example for "agentchat_auto_feedback_from_code_execution".

**Comment by sonichi** [comment]
By default, the user proxy agent replies nothing when no code is suggested. You can enable llm-based reply for user proxy agent by setting its `llm_config` and `system_message`.

**Comment by arnav77** [comment]
Hi @sonichi, I am using GPT-3.5 and have set up a system message. The human_input_mode is 'NEVER'. I am also following the same "agentchat_auto_feedback_from_code_execution" colab notebook as @muhammed-enes-koroglu.
As shown in the example the **user_proxy_agent** executes Python code once but fails because of some error, the assistant provides a fix but **user_proxy_agent** does not respond again. Any thoughts on this behavior?

**Comment by sonichi** [comment]
The default user proxy agent executes code in code blocks. The assistant agent's message doesn't contain code blocks in the required format. So an empty response is returned. For your understanding, please check https://microsoft.github.io/autogen/docs/reference/agentchat/conversable_agent#generate_reply

**Comment by gagb** [comment]
@muhammed-enes-koroglu was your question answered?

**Comment by gagb** [comment]
Closing the issue. Please reopen if you need more help.

**Comment by AugustusLZJ** [comment]
> Hi @sonichi, I am using GPT-3.5 and have set up a system message. The human_input_mode is 'NEVER'. I am also following the same "agentchat_auto_feedback_from_code_execution" colab notebook as @muhammed-enes-koroglu. As shown in the example the **user_proxy_agent** executes Python code once but fails because of some error, the assistant provides a fix but **user_proxy_agent** does not respond again. Would you have any thoughts on this behaviour?
> 
> <img alt="Capture1" width="726" src="https://user-images.githubusercontent.com/45800902/274871370-04bba82a-940a-4285-8ef1-40c99083d9d3.PNG"> <img alt="Capture2" width="731" src="https://user-images.githubusercontent.com/45800902/274871416-ba16655b-ff42-43af-8216-60706cce0198.PNG">

I see the same behaviour when calling initiate_chat. But the link https://microsoft.github.io/autogen/docs/reference/agentchat/conversable_agent#generate_reply is for generate_reply. In my code, I will never call generate_reply. How to let the user_proxy showing the chat content?

**Comment by sonichi** [comment]
`generate_reply` is called automatically after `initiate_chat`. It goes through each registered reply function and if none of them doesn't return a response, a default reply message is returned. The default reply message is empty unless one configures it differently.

**Comment by AugustusLZJ** [comment]
@sonichi Thank you for the reply. I still don't quite understand. For example, in the following image, it is the output of norag_chat() in the notebook https://github.com/microsoft/autogen/blob/main/notebook/agentchat_groupchat_RAG.ipynb. I am using gpt-3.5-turbo. It doesn't show up the replies of Boss. Do you know how to change the codes in this notebook to show the replies of Boss?


![image](https://github.com/microsoft/autogen/assets/33969722/51ff29f4-03b7-4432-a4f4-f38c518e5149)

**Comment by sonichi** [comment]
@thinkall could you answer this question?

**Comment by AugustusLZJ** [comment]
Hi @sonichi, @thinkall, @gagb, could you reopen this issue or could I create a new issue pointing to this one?

Thanks

**Comment by thinkall** [comment]
> Hi @sonichi, @thinkall, @gagb, could you reopen this issue or could I create a new issue pointing to this one?
> 
> Thanks

Hi @AugustusLZJ , the reason for not showing Boss's message is the same as discussed before in the thread. Boss is a UserProxyAgent and its default message is "", so each time it receives a non termination message, it replies "". I'll raise a PR to improve it.

**Comment by thinkall** [comment]
@AugustusLZJ , @sonichi , @gagb please check this PR #688
