### ISSUE TITLE
[Feature Request]: how do we add tools to agents created by AgentBuilder ?

### ISSUE THREAD

**Issue by krishnashed** [microsoft/autogen#1510]
### Is your feature request related to a problem? Please describe.

I want to integrate my custom functions and langchain tools with agents created by AgentBuilder

### Describe the solution you'd like

It should be possible to use custom functions or langchain's tools by these agents, As other UserProxyAgent, GPTAssistantAgent and many have the option to. If this is a feature on which work needs to be started, I can also take it up

**Comment by ekzhu** [comment]
Thanks. We would love to get some help on this. @JieyuZ2 @LinxinS97 for awareness.

**Comment by krishnashed** [comment]
@sonichi any help on this ?

**Comment by JieyuZ2** [comment]
hey @krishnashed it is a good idea to add tools, are you willing to make a first attempt to add this feature by making a PR?

**Comment by krishnashed** [comment]
@JieyuZ2 Sure I would love to contribute!

**Comment by ChristianWeyer** [comment]
Did you ever get to work on this @krishnashed ?

**Comment by krishnashed** [comment]
@ChristianWeyer yes, I'm on it. Will ask for reviewing my PR in a day or two. I was held up with something for a few days.

**Comment by krishnashed** [comment]
I didn't want to raise a PR for incomplete work. But don't you worry. It took me sometime navigating through the code, but got things figured out finally!

**Comment by krishnashed** [comment]
Continuing discussion on autogen's discord, to get few doubts clarified.

**Comment by krishnashed** [comment]
This PR is blocked untill #2414 get completed. Will continue back once #2414 is done

**Comment by rysweet** [comment]
resolved
