### ISSUE TITLE
OPENAI TOKEN API

### ISSUE THREAD

**Issue by adskykaratel** [microsoft/autogen#1512]
### Describe the bug

# import openai
# import random
# # Установите ваш API-ключ от OpenAI
# openai.api_key = '

# def create_chat(messages):
#     # Отправьте запрос к GPT-3 для чата
#     response = openai.ChatCompletion.create(
#         model="gpt-3.5-turbo",
#         messages=messages

        
#     )

#     # Извлеките текст ответа
#     reply = response['choices'][0]['message']['content'].strip()
#     return reply

# # Приветственное сообщение
# print("Этот чат IT-internHUB, готов вам помочь")

# # История чата
# chat_history = []

# while True:
#     # Запросите ввод пользователя
#     user_input = input('Вы: ')

#     # Добавьте сообщение пользователя к истории чата
#     chat_history.append({"role": "user", "content": user_input})

#     # Получите ответ от GPT-3 для чата
#     response_from_chatbot = create_chat(chat_history)

#     # Добавьте сообщение чатбота к истории чата
#     chat_history.append({"role": "chatbot", "content": response_from_chatbot})

#     # Выведите ответ чатбота
#     print(f'IT-internHUB: {response_from_chatbot}')

    

#     # Приветственное сообщение
#     welcome_message = {"role": "chatbot", "content": "Привет! Я здесь, чтобы помочь вам с программированием."}

#     # Вопросы пользователя

# # Вопросы пользователя
#     user_questions= [
#         "Как создать цикл в Python?",
#         "Как работает наследование в объектно-ориентированном программировании?",
#         "Как добавить элемент в список в Python?",
#         "Как создать функцию в JavaScript?",
#         "Как работать с базой данных в SQL?",
#         "Что такое RESTful API?",
#         "Как сгенерировать случайное число в Java?",
#         "Как сделать HTTP-запрос в Python?",
#         "Чем отличаются GET и POST запросы?",
#         "Как работает рекурсия в программировании?",
#                 "Как приготовить омлет?",
#     "Какие фильмы стоит посмотреть в выходные?",
#     "Как выбрать подходящие кроссовки для бега?",
#     "Как правильно ухаживать за комнатными растениями?",
#     "Как выбрать хорошую книгу для чтения?",
#     "Как научиться играть на гитаре?",
#     "Как подготовиться к собеседованию?",
#     "Как выбрать подходящий ресторан для свидания?",
#     "Как сделать домашнюю пиццу?",
#     'Как создать цикл ',
#     "Привет",
#     "Скажи про себя что нибудь",
#         "Добрый вечер",
#     "Пока ",
#         "Спасибо",
#     "Ты лучший",
#         "Напиши мне формулу воды",
#     "Напиши что нибудь про питон ",
#         "Сможешь решить уровнение ",
#     "1+1",
#         "Какой год самый худщий",
#     "Ты понимаешь меня",
#         # Добавьте другие вопросы, которые могут интересовать пользователя
#     ]
#     # Ответы чатбота
#     chatbot_responses = [
#         "В Python циклы создаются с использованием конструкции `for` или `while`.",
#         "Наследование позволяет одному классу наследовать атрибуты и методы другого.",
#         "Для добавления элемента в список в Python используйте метод `append`.",
#         "Для создания функции в JavaScript используйте ключевое слово `function`.",
#         "Для работы с базой данных в SQL используйте операторы `SELECT`, `INSERT`, `UPDATE`, `DELETE`.",
#         "RESTful API - это архитектурный стиль веб-сервисов, следующий принципам REST.",
#         "Для генерации случайного числа в Java используйте класс `Random`.",
#         "Для HTTP-запроса в Python используйте библиотеку `requests`.",
#         "GET и POST - это методы HTTP-запросов, GET используется для получения данных, POST - для отправки данных.",
#         "Рекурсия в программировании - это процесс, при котором функция вызывает саму себя.",
#             "Как приготовить омлет?",
#     "Какие фильмы стоит посмотреть в выходные?",
#     "Как выбрать подходящие кроссовки для бега?",
#     "Как правильно ухаживать за комнатными растениями?",
#     "Как выбрать хорошую книгу для чтения?",
#     "Как научиться играть на гитаре?",
#     "Как подготовиться к собеседованию?",
#     "Как выбрать подходящий ресторан для свидания?",
#     "Как сделать домашнюю пиццу?",
#         "Для приготовления омлета взбейте яйца, добавьте молоко и жарьте на сковороде.",
#     "Попробуйте посмотреть фильмы из жанра драма или комедия, в зависимости от вашего настроения.",
#     "Выбор кроссовок зависит от ваших предпочтений и стиля бега.",
#     "Регулярно поливайте растения и обеспечивайте им достаточно света.",
#     "Прочитайте рецензии и рекомендации перед выбором книги для чтения.",
#     "Изучайте аккорды и начните с простых песен для освоения игры на гитаре.",
#     "Подготовьтесь к собеседованию, изучив информацию о компании и подготовив вопросы.",
#     "Выбирайте ресторан в зависимости от ваших предпочтений в кухне и атмосфере.",
#     "Для домашней пиццы приготовьте тесто, добавьте любимые ингредиенты и запеките.",
#     '2',
#     'Привет друг мой',
#     'Спасибо',
#     'Да я понимаю ',
#     'формула воды это H2O',
#     'По-моему самый худшии год это середина 15-века '
#         # Добавьте другие ответы, соответствующие вопросам пользователя
#     ]

#     combined_chat_history = []

#     user_question = {"role": "user", "content": random.choice(user_questions)}
#     chatbot_response = {"role": "chatbot", "content": random.choice(chatbot_responses)}

#     # combined_chat_history.extend([user_questions, chatbot_responses])

#     # Перемешивание порядка вопросов
#     # random.shuffle(combined_chat_history)

#     # Вывод
#     for idx, item in enumerate(combined_chat_history, start=1):
#         print(f"{idx}. {item['role']}: {item['content']}")

#         # Перемешивание порядка вопросов
#         random.shuffle(combined_chat_history)

#         # Вывод
#         for idx, item in enumerate(combined_chat_history, start=1):
#             print(f"{idx}. {item['role']}: {item['content']}")
#         # Сформируйте историю чата

#     # Отправьте запрос к GPT-3
    

#     # Выведите ответ
#     # print(f'IT-internHUB:')    
heeelp please

**Comment by rickyloynd-microsoft** [comment]
Closing this issue, since this looks like spam. If it's not, please create a new issue using English and the normal font size.
