### ISSUE TITLE
Confusing error message when `llm_config` is not initialized or is `None`.

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#1522]
### Is your feature request related to a problem? Please describe.

Right now, if an agent's `llm_config` is set to None (default in `ConversableAgent` and `AssistantAgent`), or if `config_list` is empty. 

```python
from autogen import UserProxyAgent, AssistantAgent

# assistant = AssistantAgent("assistant", llm_config={"config_list": []})
assistant = AssistantAgent("assistant")
proxy = UserProxyAgent("user")

proxy.initiate_chat(assistant)
```

We get confusing error message from the openai client:  

```
TypeError: Missing required arguments; Expected either ('messages' and 'model') or ('messages', 'model' and 'stream') arguments to be given
```

### Describe the solution you'd like

We should raise an error early if the `llm_config` is None or `config_list` is empty, as it is guaranteed to lead to error as the `model` is not specified. 

Alternatively, we should set `llm_config` by default to false in `ConversableAgent` and make `llm_config` a required argument in `AssistantAgent`. As the current default `None` is always going to cause error. 

### Additional context

Related:

#1210

**Comment by afourney** [comment]
Yeah, this is another case where None or empty is taken as a positive (in this case that you want to use an LLM)

Code_execution_config was the same until late last week. 

At one point the default was to assume gpt-4 and read the key from the OPENAI_API_KEY. So some users setting llm_config to None and getting billed for GPT-4 use... This error is at least better than that!

**Comment by ekzhu** [comment]
@gunnarku here you go.
