### ISSUE TITLE
[Bug]: ConversableAgent's system_message allows List and None types but only str is ever considered in `__init__`

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#1523]
### Describe the bug

The `system_message` argument in `ConversableAgent`, as well as in `AssistantAgent` and `UserProxyAgent` all have default string value and only ever used as such. Also in the `__init__` in `CoversableAgent` there is this following:

```python
self._oai_system_message = [{"content": system_message, "role": "system"}]
```

So if `system_message` is not a `str`, there will be weird error that is hard to detect downstream. 

### Expected Behavior

`system_message` should be only allowed to be a `str` type to match the implementation of `ConversableAgent`. 

### Additional Information

pyautogen 0.2.10

**Comment by sonichi** [comment]
@BeibinLi would suggest otherwise.

**Comment by ekzhu** [comment]
Duplicate with https://github.com/microsoft/autogen/issues/2140
