### ISSUE TITLE
[Feature Request]: Clarifai & Autogen 

### ISSUE THREAD

**Issue by Josephrp** [microsoft/autogen#1525]
### Is your feature request related to a problem? Please describe.

Clarifai is an AI-serve and services provider with an absolutely amazing API.

### Describe the solution you'd like

I'm going to work clarifai into different features in autogen, for example to create system prompts for the agent builder and to be able to discover , compose and use various AI pipelines hosted on the clarifai platform :-)

```[tasklist]
### Tasks
- [ ] create a clarifai custom client with basic functionalities in clarifai
```

**Comment by ekzhu** [comment]
Thanks! Take a look at support for custom client. It has been added in 0.2.10. Maybe a custom client for Clarifai could be a first step.

**Comment by Josephrp** [comment]
great suggestion ! the custom client is long awaited and can be used in many more ways than one , this could be a good example of advanced useage, and hopefully a useful tool too :-)

**Comment by Josephrp** [comment]
hopefully i'll make a cool demo with @ekzhu by the end of this month :-) it could also be related to https://github.com/microsoft/autogen/issues/1519 in the sense that it can go there too.

**Comment by rysweet** [comment]
closing as stale, please reopen if you plan to continue to work on this.
