### ISSUE TITLE
[Bug]: Docs incorrect Dockerfile path

### ISSUE THREAD

**Issue by caudurodev** [microsoft/autogen#1530]
### Describe the bug

docs point to incorrect path for Dockerfile in this link https://microsoft.github.io/autogen/docs/installation/Docker

`docker build -f .devcontainer/base/Dockerfile -t autogen_base_img https://github.com/microsoft/autogen.git`

should be 

`docker build -f .devcontainer/Dockerfile -t autogen_base_img https://github.com/microsoft/autogen.git`

**Comment by sonichi** [comment]
closed by #1425
