### ISSUE TITLE
[Bug]: Fix Links in Documentation

### ISSUE THREAD

**Issue by Yanni8** [microsoft/autogen#1546]
### Describe the bug

A lot of links in the documentation don't work. The cause of this is simple

The problem is that a refresh often adds an additional `/` at the end of the URL

 I already mentioned this in the following pr #1449  (https://github.com/microsoft/autogen/pull/1449#issuecomment-1914829898)

But it seems like that the same issue also affects other urls for example: `https://microsoft.github.io/autogen/docs/reference/agentchat/assistant_agent`

**Comment by jackgerrits** [comment]
The link https://microsoft.github.io/autogen/docs/reference/agentchat/assistant_agent works for me. My browser seems to automatically change it to: https://microsoft.github.io/autogen/docs/reference/agentchat/assistant_agent/

In what environment are you noticing this?

**Comment by Yanni8** [comment]
> The link https://microsoft.github.io/autogen/docs/reference/agentchat/assistant_agent works for me. My browser seems to automatically change it to: https://microsoft.github.io/autogen/docs/reference/agentchat/assistant_agent/
thats the probelm. 

The link works fine. But some links on the page stoped working. For example klick on the `ConversableAgent` link

**Comment by sonichi** [comment]
> > The link https://microsoft.github.io/autogen/docs/reference/agentchat/assistant_agent works for me. My browser seems to automatically change it to: https://microsoft.github.io/autogen/docs/reference/agentchat/assistant_agent/
> > thats the probelm.
> 
> The link works fine. But some links on the page stoped working. For example klick on the `ConversableAgent` link

This can be solved by using a link like [/docs/reference/agentchat/conversable_agent]

**Comment by jackgerrits** [comment]
That conversable agent link is straight up broken. I think it is trying to be a cross reference but those seem to be not working well?

**Comment by jackgerrits** [comment]
I had a go at integrating a tool to try and find these issues automatically but I am really not satisfied with the stability of it as a CI check https://github.com/microsoft/autogen/pull/1547

**Comment by sonichi** [comment]
We can replace all the relative paths with absolute path starting from /

**Comment by Yanni8** [comment]
What would also work is to add a `/` to all links or prevent the server from automatically adding an extra `/` on refresh.
