### ISSUE TITLE
[Feature Request]:  GPTAssistantAgent in autogen studio

### ISSUE THREAD

**Issue by javelintechML** [microsoft/autogen#1560]
### Is your feature request related to a problem? Please describe.

Any ideas how to modify autogen studio to allow the use of GPTAssistantAgent for using openai assistants

**Comment by sonichi** [comment]
I believe seeing this request before. @gagb @victordibia please keep track of who's asked for this and get their reviews and feedback when such work is started by anyone.
cc @IANTHEREAL @ekzhu

**Comment by ekzhu** [comment]
@victordibia should we add this to our studio roadmap?

**Comment by victordibia** [comment]
Its a good idea! There are a few custom parameters that will need to be supported.
I believe this is related to #1364 which is already on the roadmap.

**Comment by rysweet** [comment]
closing as dupe
