### ISSUE TITLE
Add twitter account to start page

### ISSUE THREAD

**Issue by sonichi** [microsoft/autogen#157]
https://twitter.com/pyautogen

https://microsoft.github.io/autogen/docs/getting-started#where-to-go-next
After "chat on discord", add "follow on twitter".

**Comment by vidhula17** [comment]
I would like to work on this. Can you please assign it to me?

**Comment by sonichi** [comment]
There's already a PR for it #159 
Perhaps you can create another PR to update https://microsoft.github.io/autogen/docs/Contribute

**Comment by vidhula17** [comment]
I have created a PR, which resolves this issue.

**Comment by vidhula17** [comment]
> There's already a PR for it #159 Perhaps you can create another PR to update https://microsoft.github.io/autogen/docs/Contribute

Sure. I will do that.

**Comment by vidhula17** [comment]
> There's already a PR for it #159 Perhaps you can create another PR to update https://microsoft.github.io/autogen/docs/Contribute

I have created a PR for this. Kindly check this https://github.com/microsoft/autogen/pull/162.
