### ISSUE TITLE
'NoneType' object has no attribute 'prompt_tokens'

### ISSUE THREAD

**Issue by Compstudent** [microsoft/autogen#1579]
### Describe the bug

Their a problem with Autogen with OperRouter. 'NoneType' object has no attribute 'prompt_tokens'
config_list = [
    {
        "model": "cognitivecomputations/dolphin-mixtral-8x7b",
        "api_key": "Key",
        "base_url": "https://openrouter.ai/api/v1",
    }

AutoGen Version: v0.2.11

### Steps to reproduce

config_list = [
    {
        "model": "cognitivecomputations/dolphin-mixtral-8x7b",
        "api_key": "Key",
        "base_url": "https://openrouter.ai/api/v1",
    }

### Expected Behavior

no error

### Screenshots and logs

![openrouter](https://github.com/microsoft/autogen/assets/5156942/95233ecd-3cf2-4173-806a-403572aebc70)

**Comment by olgavrou** [comment]
this seems to be an incompatibility with OpenAI's chat completion object see [here](https://platform.openai.com/docs/api-reference/chat/object), I'll add a check to the code to check for `usage` being available
