### ISSUE TITLE
[Bug]: AutoGen Studio GroupChat not working

### ISSUE THREAD

**Issue by cyberandy** [microsoft/autogen#1580]
### Describe the bug

I have installed the latest version (Version: 0.0.43a0), while the single agent works the multi-agent does not. 
I am running on Python 3.10.12. 

### Screenshots and logs

_General Agent Workflow works_.
![image](https://github.com/microsoft/autogen/assets/837037/6f353aaf-6659-4811-870d-fdbd655b0d11)

_Default Group Workflow doesn't_.
![image](https://github.com/microsoft/autogen/assets/837037/1759f1e9-9c29-4447-ac64-b8dfb2ddf809)

### Additional Information

Version: 0.0.43a0
MacOSX
Python 3.10.12

**Comment by victordibia** [comment]
Thanks for noting this.
That was a regression with v 0.0.43a. I have now pushed v 0.0.44a which should address the issue.

**Comment by cyberandy** [comment]
Ah this is great to hear! Thanks

**Comment by cyberandy** [comment]
It works now with autogenstudio-0.0.44a0
