### ISSUE TITLE
[Bug]: 建了一个独立开发者交流群，欢迎加入

### ISSUE THREAD

**Issue by win4r** [microsoft/autogen#1593]
### Describe the bug

![image](https://github.com/microsoft/autogen/assets/42172631/f780850d-f870-456b-ae04-d3285969a5ca)

**Comment by rickyloynd-microsoft** [comment]
Clearly spam.

**Comment by ingted** [comment]
WeChat 加不進去啊！！

**Comment by 812406210** [comment]
你好，wechat可以再建一个群不？
