### ISSUE TITLE
[Issue]: Autogen code not communicating to machine through VPN

### ISSUE THREAD

**Issue by Ghostyboy0719** [microsoft/autogen#1598]
### Describe the issue

My autogen is running on a Mac - 10.10.10.1
VPN to Another Machine IP is 10.10.10.5

I m trying to reach the machine 10.10.10.5 on a different network connected via VPN for Autogen to communicate with. It doesnt connect to it, but when I have my mac ping that VPN machine it pings just fine. 

Is there something I can change to ensure that agents can communicate with another machine?

### Additional Information

Latest Autogen Version
MacOS
Python3

**Comment by sonichi** [comment]
Do you mean making an inference call to a remote endpoint? Does it work without using autogen?

**Comment by Ghostyboy0719** [comment]
> Do you mean making an inference call to a remote endpoint? Does it work without using autogen?

Yes it does work without autogen but autogen agents don't communicate with those remote endpoints

**Comment by sonichi** [comment]
Is the same setting passed in `llm_config` of the agents that use the endpoints?

**Comment by Ghostyboy0719** [comment]
> Is the same setting passed in `llm_config` of the agents that use the endpoints?

Fixed it. Created a docker image from the base image of autogen and now the agent communicates over VPN
