### ISSUE TITLE
Add parallel tunning for openAI integration

### ISSUE THREAD

**Issue by thinkall** [microsoft/autogen#16]
It would be useful to support parallel tunning in openAI integration to accelerate the tunning process. Plus, it would be better to support multi-apikeys to mitigate the API call ratio limitation of openAI.

**Comment by wapmaster13** [comment]
[test message](www.divasilver.ro)

**Comment by rysweet** [comment]
@thinkall - I think this is addressed now - please reopen if you disagree, and add more details.
