### ISSUE TITLE
[Feature Request]: Display warning when overwriting tool

### ISSUE THREAD

**Issue by Yanni8** [microsoft/autogen#1607]
### Is your feature request related to a problem? Please describe.

Currently overriding a tool is as simple as

```python
@user_proxy.register_for_execution(name="my-first-tool")
def do_something():
     pass

@user_proxy.register_for_execution(name="my-first-tool")
def do_something_else():
     pass
```

The problem is that it might happen that a user copies the annotation from the first tool without changing the name. In that case, does the first tool function get overridden by the second definition. This might be completely fine in some cases.

But it might also happen that this results in unexpected behaviors. It might make sense to display a warning when the user overrides an existing tool name.

### Describe the solution you'd like

Create a warning in the console when the user overrides an existing tool function

**Comment by ekzhu** [comment]
You are welcome to submit a pr to fix this
