### ISSUE TITLE
[Feature Request]: AutoGen Studio - load custom startup configuration

### ISSUE THREAD

**Issue by Xtrah** [microsoft/autogen#1608]
### Is your feature request related to a problem? Please describe.

AutoGen Studio allows changing the start up configuration by editing the `autogentstudio/utils/dbdefaults.json` file which is used to initialize the database. However, editing dbdefaults.json is not convenient/easily accessible when installing and using AutoGen Studio as a pip package.

### Describe the solution you'd like

Allow loading a custom .json configuration file e.g. `customdb.json` using a flag such as `autogenstudio ui --port 8081 --host 0.0.0.0 --config customdb.json`

If the flag is used, the custom configuration json is loaded on startup with user defined models, skills and workflows, similar to dbdefaults.json.

### Additional context

[samples/apps/autogen-studio/autogenstudio/utils/dbdefaults.json](https://github.com/microsoft/autogen/blob/main/samples/apps/autogen-studio/autogenstudio/utils/dbdefaults.json)
Related FAQ: https://microsoft.github.io/autogen/blog/2023/12/01/AutoGenStudio#faq

**Comment by rysweet** [comment]
@victordibia please review - consider closing wont fix
