### ISSUE TITLE
[Feature Request]: Disable ssl verification

### ISSUE THREAD

**Issue by ahernd2** [microsoft/autogen#1611]
How do I disable ssl verification on autogen. I have tried many solutions but none seem to work. I realize this would be a security issue but it would be very useful to me as we are behind a corporate proxy. The error I am getting continuously is

```
httpx.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1007)
```

### Describe the solution you'd like

Perhaps allow setting a flag much like the requests module 

```python
requests.get('https://kennethreitz.com', verify=False)
```

Maybe something like

```python
user_proxy.initiate_chat(
    assistant,
    message="""What are todays news highlights?""",
    verify=False 
)
```

And for autogenstudio something like

```bash
autogenstudio ui --verify=false --port=8081
```

**Comment by sonichi** [comment]
Are you able to use the standard OpenAI API to perform inference? Any setting required for that can be passed to `llm_config` of an agent too.

**Comment by ahernd2** [comment]
@sonichi Thanks for the response, though I'm not really sure what you mean. Can you give an example of how to pass a setting to the llm_config?

**Comment by ekzhu** [comment]
@ahernd2  https://microsoft.github.io/autogen/docs/llm_configuration for llm_config
