### ISSUE TITLE
AutoGenStudio: recover settings/API interaction examples

### ISSUE THREAD

**Issue by stevenbaert** [microsoft/autogen#1625]
### Is your feature request related to a problem? Please describe.

I love AutoGenStudio but would like to be able to recover settings easily and use without web interface when interface wouldn't run anymore (it is a beta project though I put tons of effort configuring it, would really kill me if it would crash or not work after an upgrade or manipulations). Also I wonder why there is an API for AutoGenStudio, why not directly use the code generated by the GUI?

### Describe the solution you'd like

Have access to the configs made by GUI and reuse without GUI/have clear understanding why AutoGen GUI API is created and no direct code generated by GUI can be used.

Thanks!

**Comment by victordibia** [comment]
Hi @stevenbaert ,

AutoGenStudio lets you download your configurations. You can then import them and use directly in python.

Please see #1287 

Currently, we have an example [notebook](https://github.com/microsoft/autogen/blob/autogenstudio/samples/apps/autogen-studio/notebooks/tutorial.ipynb) that shows how you can load a[ workflow spec (json)](https://github.com/microsoft/autogen/blob/autogenstudio/samples/apps/autogen-studio/notebooks/agent_spec.json) and run tasks against it in python code. 

What we will need to add is the ability to download the workflow created in the UI. 

```python 
import json

from autogenstudio import AgentWorkFlowConfig, AutoGenWorkFlowManager

# load an agent specification in JSON
agent_spec = json.load(open("agent_spec.json"))

# Creat a An AutoGen Workflow Configuration from the agent specification
agent_work_flow_config = AgentWorkFlowConfig(**agent_spec)

# # Create a Workflow from the configuration 
agent_work_flow = AutoGenWorkFlowManager(agent_work_flow_config) 

# # Run the workflow on a task
task_query = "What is the height of the Eiffel Tower?. Dont write code, just respond to the question."
agent_work_flow.run(message=task_query)
```

Does this address the use case you have in mind?


![Image](https://github.com/microsoft/autogen/assets/1547007/2a5d9118-124b-460e-ac1c-8f029e91ffb8)

**Comment by JingPush** [comment]
I think the tutorial notebook is not updated with workflow manager updates in autogen studio, as there is no "AutoGenWorkFlowManager, AgentWorkFlowConfig". 
https://github.com/microsoft/autogen/blob/main/samples/apps/autogen-studio/notebooks/tutorial.ipynb

Where Can I find the updated tutorial?
Tried with workflow as dictionary, but didn't work.

**Comment by victordibia** [comment]
@JingPush 
The tutorial on the autogenstudio branch is updated, 
https://github.com/microsoft/autogen/blob/autogenstudio/samples/apps/autogen-studio/notebooks/tutorial.ipynb thanks to @TheAmazingRoderic 

Will be merged into main soon.

**Comment by Sachin13p** [comment]
Hi @victordibia 

Is the below code still valid? 
_from autogenstudio import AgentWorkFlowConfig, AutoGenWorkFlowManager_

When I am using it, I am getting "not found error for AutoGenWorkFlowManager". So I am using TeamManager class to execute workflow ( based on the code sample provided in AutoGenStudio's Deploy section.)

Unfortunaly this code throws exception on execution of TeamManager.Run  with errror ""<enum 'LogEntryType'> cannot extend <enum 'Enum'>""  Let me know if I am missing anything here.

Here is my Code:

import asyncio
#from autogenstudio import AutoGenWorkFlowManager
#from autogenstudio.teammanager. import WorkflowManager 
from autogenstudio.datamodel import Response
from autogenstudio.teammanager import TeamManager
#from autogenstudio import AutoGenWorkFlowManager, AgentWorkFlowConfig
import json
import os
#import autogen

from fastapi import FastAPI
app = FastAPI()

agent_spec = json.load(open(r"C:\TFS\Deployment API\team-config.json", encoding="utf8"))
#print(agent_spec)
#if workflow_file_path:
    #workflow_manager = WorkflowManager(workflow=workflow_file_path)
#else:
   #raise ValueError("Workflow file must be specified")
#Initialize the TeamManager
manager = TeamManager()
@app.get("/predict/{task}")
async def predict(task: str):
    response = Response(message="Task successfully completed", status=True, data=None)
    try:
        **result_message = await manager.run(task,team_config=agent_spec )**
        response.data = result_message
    except Exception as e:
        response.message = str(e)
        response.status = False
    return response
if __name__ == "__main__":
    asyncio.run(predict("What is weather of Redmond, WA USA"))

**Comment by Sachin13p** [comment]
> Hi [@victordibia](https://github.com/victordibia)
> 
> Is the below code still valid? _from autogenstudio import AgentWorkFlowConfig, AutoGenWorkFlowManager_
> 
> When I am using it, I am getting "not found error for AutoGenWorkFlowManager". So I am using TeamManager class to execute workflow ( based on the code sample provided in AutoGenStudio's Deploy section.)
> 
> Unfortunaly this code throws exception on execution of TeamManager.Run with errror ""<enum 'LogEntryType'> cannot extend <enum 'Enum'>"" Let me know if I am missing anything here.
> 
> Here is my Code:
> 
> import asyncio #from autogenstudio import AutoGenWorkFlowManager #from autogenstudio.teammanager. import WorkflowManager from autogenstudio.datamodel import Response from autogenstudio.teammanager import TeamManager #from autogenstudio import AutoGenWorkFlowManager, AgentWorkFlowConfig import json import os #import autogen
> 
> from fastapi import FastAPI app = FastAPI()
> 
> agent_spec = json.load(open(r"C:\TFS\Deployment API\team-config.json", encoding="utf8")) #print(agent_spec) #if workflow_file_path: #workflow_manager = WorkflowManager(workflow=workflow_file_path) #else: #raise ValueError("Workflow file must be specified") #Initialize the TeamManager manager = TeamManager() @app.get("/predict/{task}") async def predict(task: str): response = Response(message="Task successfully completed", status=True, data=None) try: **result_message = await manager.run(task,team_config=agent_spec )** response.data = result_message except Exception as e: response.message = str(e) response.status = False return response if **name** == "**main**": asyncio.run(predict("What is weather of Redmond, WA USA"))

The issue is resolved. I did not change anything but next day when re run , it worked.
