### ISSUE TITLE
few codes not working with just Azure details

### ISSUE THREAD

**Issue by SushmitaSahuAI** [microsoft/autogen#163]
Hi,
I am trying to execute : [autogen](https://github.com/microsoft/autogen/tree/main)/[notebook](https://github.com/microsoft/autogen/tree/main/notebook)
/agentchat_planning.ipynb . I ahve the OAI_CONFIG_LIST with all the azure details. What am i missing here.
but on running the code i am getting the following error:
187         "No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details."
    188     )

AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.

**Comment by nubgamerz** [comment]
This usually happens if it can't load your config.
In the assistant agent, set the

``` "config_list": autogen.config_list_openai_aoai(exclude="aoai"),```

to

``` "config_list": config_list, ```

In your config_list var, just remove the references to openAI, to only load from your JSON

```config_list = config_list_from_json(env_or_file="OAI_CONFIG_LIST")```

**Comment by SushmitaSahuAI** [comment]
Hi,
I have done that only.
Sharing with you the code snippet:
config_list = autogen.config_list_from_json(
    env_or_file="OAI_CONFIG_LIST",
    filter_dict={
        "model": {
            "gpt-3.5-turbo",
            "gpt-4",
        },
    },
)

**Comment by sonichi** [comment]
What's your OAI_CONFIG_LIST like?

**Comment by patricianist** [comment]
followed the above successfully got rid of the "No API key provided." error, but then I got this:
`InvalidRequestError: Invalid URL (POST /v1/https:/xxxxxxxxxxxx.openai.azure.com/deployments/gpt-4/chat/completions)`

My config_list looks like this 
`config_list = autogen.config_list_from_json(
    env_or_file="OAI_CONFIG_LIST"
)`

assistant agent init like this 
`assistant = autogen.AssistantAgent(
    name="assistant",
    llm_config={
        "seed": 42,  # seed for caching and reproducibility
        "config_list": config_list,  # a list of OpenAI API configurations
        "temperature": 0,  # temperature for sampling
    },  # configuration for autogen's enhanced inference API which is compatible with OpenAI API
)`

and OAI_CONFIG_LIST like this
`[
    {
        "model": "gpt-4",
        "api_key": "xxxxxxxxxxxxxxxxxxxxxxxx",
        "base_url": "https://xxxxxxxxxxxx.openai.azure.com/",
        "api_type": "azure",
        "api_version": "2023-07-01-preview"
    }
]`

**Comment by aavetis** [comment]
i'm seeing the same. it shouldn't be hitting /v1/... for an azure oai endpoint, right?

**Comment by yigitkonur** [comment]
Indeed, this is the root of the issue. The addition of /v1/ as a suffix for Azure should not occur. It's quite strange to observe that it appears Microsoft has not conducted testing of their product on their own platform.

**Comment by sonichi** [comment]
I wonder whether there is a version mismatch. Could you try `pyautogen==0.2.0b3`?

**Comment by patricianist** [comment]
sorry on getting back late, it actually works on pyautogen==0.2.0b3 with Azure OpenAI
