### ISSUE TITLE
Context not loading split document in the correct order for RAG

### ISSUE THREAD

**Issue by pranavvr-lumiq** [microsoft/autogen#1639]
### Describe the issue

I am trying to run a notebook with autogen RAG. I am using a .csv file for docs_path. For some reason, The context does not load the file in the correct order. How do I fix this, and is there any way to reset the context?

**Comment by thinkall** [comment]
Hi @pranavvr-lumiq , if the csv file is not very large, try increase the max_tokens to fit the whole file content into a single chunk. Otherwise, the order can't be guaranteed.

**Comment by thinkall** [comment]
Close as no active response for a long time. Please reopen it or create a new issue if needed.
