### ISSUE TITLE
[Feature Request]: [.Net] bring Graph-based group chat to AutoGen.Net

### ISSUE THREAD

**Issue by LittleLittleCloud** [microsoft/autogen#1648]
### Is your feature request related to a problem? Please describe.

resolve #857 

@ekzhu @joshkyh

**Comment by joshkyh** [comment]
> ### Is your feature request related to a problem? Please describe.
> 
> resolve #753 
> 
> @ekzhu @joshkyh 
> 
> ### Describe the solution you'd like
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

Did you mean extend #857 to .net instead? #753 was abandoned. :)

**Comment by LittleLittleCloud** [comment]
@joshkyh Oh yes, the #857 is the one that I want to introduce to AutoGen for .net

**Comment by LittleLittleCloud** [comment]
Resolved by #1761
