### ISSUE TITLE
[Feature Request]: Add FAQ entry about correct package name

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#1662]
### Is your feature request related to a problem? Please describe.

Many people have encountered issues due to the `autogen` package got installed instead of `pyautogen`. 

### Describe the solution you'd like

Add an FAQ entry to remind people the correct package name. And instructions to remove `autogen` and reinstalling `pyautogen`. 

### Additional context

#1617 
#1398 
#1535

**Comment by 2undvierzig** [comment]
@ekzhu sure, I can do it.

**Comment by ekzhu** [comment]
it looks like some one has already dibbed: #1665
