### ISSUE TITLE
[Issue]: Autogen Studio UI 2.0  Human Input Mode

### ISSUE THREAD

**Issue by Roopesh-Bharatwaj-K-R** [microsoft/autogen#1664]
### Describe the issue

Hi, I'm using Autogen Studio UI 2.0.

I'm creating an Agent which requires Human Input, when I use the Autgen UI studio to create an agent -> I cannot see any options other than 'NEVER' in the Human Input Field.

Kindly Help me with the same and how can i overcome this situation of having Human Input to 'YES' in UI

Installation Process I followed https://microsoft.github.io/autogen/blog/2023/12/01/AutoGenStudio/

<img width="761" alt="Screenshot 2024-02-13 at 13 06 22" src="https://github.com/microsoft/autogen/assets/77121467/90cc418f-fecb-4b3a-9769-d8f94aa9ff26">

**Comment by victordibia** [comment]
Hi @Roopesh-Bharatwaj-K-R ,

We do not yet support Human Input Mode. Its on the roadmap.  
Related #1358

**Comment by Roopesh-Bharatwaj-K-R** [comment]
@victordibia  Can you help me -  If I can use coding for this, pls share some notebook examples.

**Comment by victordibia** [comment]
Sure: Can you try this notebook and let me know if it fits your needs? 
https://github.com/microsoft/autogen/blob/main/notebook/agentchat_human_feedback.ipynb

**Comment by Roopesh-Bharatwaj-K-R** [comment]
Thank you very much for the information, Much appreciated, If I encounter any issues. Will get back to you. Thanks Again !!
