### ISSUE TITLE
[Issue]: Autogen count tokens badly when using served Open Source Models

### ISSUE THREAD

**Issue by Halpph** [microsoft/autogen#1666]
### Describe the issue

I've been using various open source models (using vllm to serve them: Orca-2-7b, Mixtral_11Bx2_MoE_19B, and SOLAR-10.7B-Instruct-v1.0) to implement RAG using Qdrant. These models have been included in my OAI_CONFIG_LIST and appear to function well using autogen. However, I've encountered an issue when introducing larger prompts, the number of tokens are always calculated badly.

Upon inspection of the source code, I've deduced that the token count is calculated using Tiktoken, whereas the open source models employ a different calculation method. This discrepancy seems to be causing issues when the token count surpasses the maximum token length of the model, resulting in a process halt.
I'll come with a PR asap.

### Steps to reproduce

Serve an open source model using vllm, just use it with a big prompt.

### Additional Information

**Comment by gagb** [comment]
@marklysze may have thoughts on this one!

**Comment by marklysze** [comment]
Thanks @gagb :), this would be handy to have. @Halpph, is this still a requirement for you and are you using an updated code-base based on your PR #1701?

**Comment by Halpph** [comment]
I'm using the patched version that I had created when I opened the PR, unfortunately I didn't have much time to write tests and implement it nicely.
But it still works, I'm actually using a duplicated OAI_CONFIG_FILE to specify the alternative tokenizer

**Comment by marklysze** [comment]
Thanks @Halpph, I think it's good to have this information for inference. Although the cost isn't the implication, obviously context windows are more limited with open source models.

Can I ask how you are running your open source models, still vLLM? (or now Ollama / Amazon Bedrock / etc.). I think this would make most sense in something like Amazon Bedrock, Ollama client class, or a dedicated vLLM client class. I feel that the openai client class should be focused on OpenAI specifically, but open to thoughts.

**Comment by Halpph** [comment]
Yeah Indeed I was using vLLM, I think it indeed makes sense to put it in another class.

**Comment by marklysze** [comment]
Do you think a dedicated vLLM class would be useful? I have previously created one but didn't create a PR for it as it was very similar to OpenAI, though I can see value now in adding it if it can cater for token counting.

**Comment by rysweet** [comment]
the related PR has been closed as stale. It could be brought back up to date. Closing this issue and @marklysze @Halpph please reopen if you want to still work on this.
