### ISSUE TITLE
[Issue]: Add additional documentation for running a local LLM in Windows Subsystem for Linux using llama-cpp-python on the GPU.

### ISSUE THREAD

**Issue by nodered** [microsoft/autogen#1668]
### Describe the issue

Couldn't find documentation or running a local open-source LLM on the GPU in Windows Subsystem for Linux.

I don't know how autogen and local LLMs interact at a low level so I'm not sure there is compatibility with autogen.

I haven't tried llama-cpp-python in Windows 11.

### Steps to reproduce

This is just a first pass on installing and running llama-cpp-python on the GPU but it works for me.

Further testing and clean-up of commands is obviously needed!

**Install CUDA Toolkit for WSL 2**

https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=WSL-Ubuntu&target_version=2.0&target_type=deb_local

**Install llama-cpp-python with GPU acceleration**

`export CMAKE_ARGS="-DLLAMA_CUBLAS=on" && pip install llama-cpp-python`

`export CMAKE_ARGS="-DLLAMA_CUBLAS=on" && pip install llama-cpp-python[server]`

**Reinstall llama-cpp-python if you have problems with GPU acceleration**

`export CMAKE_ARGS="-DLLAMA_CUBLAS=on" && pip install llama-cpp-python --upgrade --force-reinstall --no-cache-dir`

`export CMAKE_ARGS="-DLLAMA_CUBLAS=on" && pip install llama-cpp-python[server] --upgrade --force-reinstall --no-cache-dir`

**Open port to WSL 2 as admin in a console**

```netsh interface portproxy add v4tov4 listenport=7860 listenaddress=0.0.0.0 connectport=7860 connectaddress=172.19.100.63```

**Run llama_cpp.server (OpenAI compatible endpoints - /v1/completions /v1/embeddings /v1/chat/completions)**

```python3 -m llama_cpp.server --model ../models/mistral-7b-instruct-v0.2.Q4_K_M.gguf --n_gpu_layers 30 --port 7860 --host 0.0.0.0 --chat_format chatml```

### Additional Information

Looks like a better way to serve local LLMs compared to FastChat???

By using llama-cpp-python (https://github.com/abetlen/llama-cpp-python) you get the ability to use additional models.

llama-cpp-python has embeddings endpoint.

etc. etc.

llama-cpp-python https://github.com/abetlen/llama-cpp-python

Low-level access to C API via ctypes interface.
    High-level Python API for text completion
        OpenAI-like API
        [LangChain compatibility](https://python.langchain.com/docs/integrations/llms/llamacpp)
        [LlamaIndex compatibility](https://docs.llamaindex.ai/en/stable/examples/llm/llama_2_llama_cpp.html)
    OpenAI compatible web server
        [Local Copilot replacement](https://llama-cpp-python.readthedocs.io/en/latest/server/#code-completion)
        [Function Calling support](https://llama-cpp-python.readthedocs.io/en/latest/server/#function-calling)
        [Vision API support](https://llama-cpp-python.readthedocs.io/en/latest/server/#multimodal-models)
        [Multiple Models](https://llama-cpp-python.readthedocs.io/en/latest/server/#configuration-and-multi-model-support)

**Comment by ekzhu** [comment]
@nodered Looks like you have solution. Would you like to join the documentation effort here: #1597? Just comment there and see where your solution fits in there.

**Comment by rysweet** [comment]
closing as stale - OP was invited to crontrib.
