### ISSUE TITLE
[Issue]: Set the actual_usage_summary's key to `actual_total_cost`?

### ISSUE THREAD

**Issue by thinkall** [microsoft/autogen#1673]
### Describe the issue

In the [code](https://github.com/microsoft/autogen/blob/71829f3fdf2389f59d63c7376aa4b055427294e8/autogen/agentchat/chat.py#L27) it says `cost is a tuple of (total_cost, total_actual_cost)`, but the key of both are `total_cost`. It's a little bit confusing. 

What about make cost a dictionary with keys `total_cost` and `actual_total_cost` for easier understanding? Or a tuple (float, float) for easier access?

**Comment by sonichi** [comment]
@kevin666aa @olgavrou @cheng-tan what do you think?

**Comment by kevin666aa** [comment]
If this is named cost, can we just separate it into two class variables: total_cost, actual_cost_with_cache, each is a float?

**Comment by rysweet** [comment]
don't think we are going to do anything with this in 0.2 from here... @thinkall please reopen if you disagree
