### ISSUE TITLE
[Notebook]: bad-looking special blocks

### ISSUE THREAD

**Issue by sonichi** [microsoft/autogen#1683]
### Describe the issue

https://github.com/microsoft/autogen/blob/main/notebook/agentchat_auto_feedback_from_code_execution.ipynb
The beginning section has bad-looking blocks.

**Comment by jackgerrits** [comment]
When rendered on the website it looks like:
<img width="1006" alt="image" src="https://github.com/microsoft/autogen/assets/7558482/89013052-7648-43b4-b5aa-f40d405f99fd">

While I agree these loos ugly in the notebook itself I think the readability improvement on the website makes it worth it. However, if you think the experience in the raw notebook is not acceptable then we can consider different options such as not using admonitions.

**Comment by sonichi** [comment]
Got it. Thanks for confirming that this is not an unintended bug.
