### ISSUE TITLE
 using `bool` type hint for `send_introductions`

### ISSUE THREAD

**Issue by sonichi** [microsoft/autogen#1689]
Perhaps using `bool` type hint? send_introductions doesn't seem to ever be `None`?

_Originally posted by @ekzhu in https://github.com/microsoft/autogen/pull/961#discussion_r1476916151_

**Comment by jackgerrits** [comment]
This was resolved in the PR

**Comment by jackgerrits** [comment]
My mistake, I misinterpreted. The type hint is Optional where it should just be a bool

**Comment by ekzhu** [comment]
@WaelKarkoub do you want to take a look at this once #1729  is merged?
