### ISSUE TITLE
Autogen as replacement for Open Interpreter? 

### ISSUE THREAD

**Issue by stevenbaert** [microsoft/autogen#173]
Hi,

I ve been experimenting somewhat with Autogen and it's impressive!
Now I was using Open Interpreter but I wonder if I could replace it with Autogen easily.

So I know Autogen can probably do it all, but could you give some input on how to achieve this in the most easy/solid way? Iow mimic exactly code Interpreter functionality in Autogen, so later on I could optimize. How many agents to use, what kinds of agents, then a start of autogen with parameter y to make it run automatically but probably with a max to avoid a costly loop. Maybe also set a max of cost and at the end the cost of the execution(?)

I really would like to see how far Autogen can help me optimize my coding and maybe even create cod projects and wanted to do for a long time but didn't find time.

Thanks!

**Comment by qingyun-wu** [comment]
Dear @stevenbaert,

Thank you for your interest and the questions! 

For the task at hand that uses the Open Interpreter, a two-agent system comprising the AssistantAgent and UserProxyAgent is likely sufficient.

For complex tasks in general, this is a great open question. A complete answer is still open and the optimal topology is often application-dependent. However, as a rule of thumb, it's advisable to start with a simple conversation topology. Consider beginning with a two-agent chat or the group chat setup, as they can frequently be expanded with minimal code modifications.

For more detailed guidelines for using AutoGen, please refer to appendix B.1 (pages 16-17) in this technical report: https://arxiv.org/pdf/2308.08155.pdf.

@sonichi  please feel free to chime in if you want to add anything.

**Comment by sonichi** [comment]
[`max_consecutive_auto_reply`](https://microsoft.github.io/autogen/docs/reference/agentchat/conversable_agent#max_consecutive_auto_reply
) can be used to limit the max number of turns. 
To achieve cost control, you can extend https://microsoft.github.io/autogen/docs/reference/agentchat/conversable_agent#generate_oai_reply
to record the [cost](https://microsoft.github.io/autogen/docs/reference/oai/completion#cost) and return "TERMINATE" when budget is reached.

**Comment by stevenbaert** [comment]
> Dear @stevenbaert,
> 
> Thank you for your interest and the questions!
> 
> For the task at hand that uses the Open Interpreter, a two-agent system comprising the AssistantAgent and UserProxyAgent should be sufficient.
> 
> For complex tasks in general, this is a great open question. A complete answer is still open and the optimal topology is often application-dependent. However, as a rule of thumb, it's advisable to start with a simple conversation topology. Consider beginning with a two-agent chat or the group chat setup, as they can frequently be expanded with minimal code modifications.
> 
> For more detailed guidelines for using AutoGen, please refer to appendix B.1 (pages 16-17) in this technical report: https://arxiv.org/pdf/2308.08155.pdf.
> 
> @sonichi please feel free to chime in if you want to add anything.

Thanks! With Open Interpreter installed, you just type interpreter and then go in that "modus", meaning you can ask a question, f.e. look at this code or write code. How would you achieve that with Autogen?

**Comment by sonichi** [comment]
> > Dear @stevenbaert,
> > Thank you for your interest and the questions!
> > For the task at hand that uses the Open Interpreter, a two-agent system comprising the AssistantAgent and UserProxyAgent should be sufficient.
> > For complex tasks in general, this is a great open question. A complete answer is still open and the optimal topology is often application-dependent. However, as a rule of thumb, it's advisable to start with a simple conversation topology. Consider beginning with a two-agent chat or the group chat setup, as they can frequently be expanded with minimal code modifications.
> > For more detailed guidelines for using AutoGen, please refer to appendix B.1 (pages 16-17) in this technical report: https://arxiv.org/pdf/2308.08155.pdf.
> > @sonichi please feel free to chime in if you want to add anything.
> 
> Thanks! With Open Interpreter installed, you just type interpreter and then go in that "modus", meaning you can ask a question, f.e. look at this code or write code. How would you achieve that with Autogen?

I'm not familiar with "modus" but sounds that a function call can be used to do it.

**Comment by nodueck** [comment]
@stevenbaert I think the best way would be to create a custom agent who uses open-interpreter. You could start by [registering a custom reply function](https://github.com/microsoft/autogen/blob/1dd77d8b811ed0b1116f8a8ff318e8bfbbf2430e/autogen/agentchat/conversable_agent.py#L123) that calls open-interpreter. On the open-interpreter side check out the [respond function](https://github.com/KillianLucas/open-interpreter/blob/b451305a5d49f2451e3d506423697002dabd666e/interpreter/core/respond.py#L8). You could try to call it from your custom agent. (You've got to [initialize an Intepreter object](https://github.com/KillianLucas/open-interpreter/blob/b451305a5d49f2451e3d506423697002dabd666e/interpreter/__init__.py#L7) first.

**Comment by sonichi** [comment]
Found this:
https://levelup.gitconnected.com/integrate-autogen-into-your-chatbot-code-interpreter-clone-2ba71e264ad3
https://github.com/ryanshrott/autogen/blob/main/app.py
