### ISSUE TITLE
docstring render error

### ISSUE THREAD

**Issue by thinkall** [microsoft/autogen#1731]
@thinkall Thank you for your reply! Actually in this rag_groupchat case, I have another two issues.

2. I tried to check the retrieve config, but it seems the post is messed up...link: https://microsoft.github.io/autogen/docs/reference/agentchat/contrib/retrieve_user_proxy_agent/
![Screenshot 2024-02-19 153716](https://github.com/microsoft/autogen/assets/43228022/2d612e6f-d323-4d71-ac5e-765e654d54af)

_Originally posted by @szwang-seedtech in https://github.com/microsoft/autogen/issues/1722#issuecomment-1951941611_

**Comment by jackgerrits** [comment]
I have played around with trying to fix this and I have not had much luck. Given that `pydoc-mardown` is not really being maintained it might we worth trying alternatives

**Comment by jackgerrits** [comment]
Still investigating. Naive usage of sphinx and targeting markdown with sphinx-builder-markdown produces not great results

<img width="1656" alt="image" src="https://github.com/microsoft/autogen/assets/7558482/0b3b8276-6d85-4777-b6fc-eefd3ded80ed">
