### ISSUE TITLE
[Issue]: How to connect to azure api gateway through autogen

### ISSUE THREAD

**Issue by ompanda** [microsoft/autogen#1734]
### Describe the issue

azure open ai is hosted behind azure api gateway with custom header to authenticate to gateway. how to connect autogen with api gatway to access azure open ai.

**Comment by BeibinLi** [comment]
See: https://microsoft.github.io/autogen/docs/llm_configuration#oai_config_list-pattern

Search keyword "azure" in the page. There are detailed instructions.

**Comment by ompanda** [comment]
do we need to create rest client for this

**Comment by BeibinLi** [comment]
No, you just need to create a variable `config_list `, which contains the information of your Azure endpoint and key.
