### ISSUE TITLE
[Issue]: About the operation errors of RAG in docker container

### ISSUE THREAD

**Issue by szwang-seedtech** [microsoft/autogen#1737]
### Describe the issue

I was trying to run the RAG sample code, and it worked in my local environment. 

However, when I packed the autogen project into a docker image, with exactly the same config, I got two error: 
The sentence_transformers python package is not installed, and 2. Error: Collection autogen-docs does not exist.

Does anyone know what is going on here, and do I need any additional docker setting if I want the whole project to be operated in a docker container?

**Comment by BeibinLi** [comment]
@thinkall
