### ISSUE TITLE
[Bug]: `RetrieveUserProxyAgent` ignores `customized_prompt`

### ISSUE THREAD

**Issue by PyroGenesis** [microsoft/autogen#1743]
### Describe the bug

`RetrieveUserProxyAgent` is not making use of `customized_prompt`

### Steps to reproduce

1. Create a `RetrieveUserProxyAgent` with a `customized_prompt` in its `retrieve_config`
2. Start a chat using `a_initiate_chat()` with an `AssistantAgent`

### Expected Behavior

The `AssistantAgent` should receive the customized prompt but it doesn't.

### Additional Information

AutoGen: v0.2.14
OS: Windows 10
Python: 3.10.11

We narrowed it down to `a_initiate_chat()` calling `a_generate_init_message()` which is not implemented for `RetrieveUserProxyAgent` so it ends up falling back to `ConversableAgent.a_generate_init_message()` which does not make use of `customized_prompt`

**Comment by gagb** [comment]
@thinkall

**Comment by thinkall** [comment]
Hi @PyroGenesis , I see you've found the root cause. RetrieveUserProxyAgent doesn't support async calls yet. It's on our roadmap. https://github.com/microsoft/autogen/issues/1657

**Comment by PyroGenesis** [comment]
Since the introduction of callable messages, this issue can be resolved by using the `message_generator` callable provided within `RetrieveUserProxyAgent`

```py
await retrieve_user_proxy_agent.a_initiate_chat(
    general_assistant, 
    message=retrieve_user_proxy_agent.message_generator, 
    problem=problem, 
    n_results=10
)
```

This still falls back to `ConversableAgent.a_generate_init_message()` but that's fine because that triggers `message_generator` as a Callable which returns a message with the `customized_prompt` and the vector db context.
