### ISSUE TITLE
[Bug]: "Neither powershell nor pwsh is installed." always printed when code_utils imported

### ISSUE THREAD

**Issue by jackgerrits** [microsoft/autogen#1747]
This print is noisy. It should be sent to the logger instead of just printed.

https://github.com/microsoft/autogen/blob/a34e4cc515ae85c877a5e1ea59cc0bacf1320cd9/autogen/code_utils.py#L232

For example
```python
logger.info(...)
```

Introduced in #1710

**Comment by BeibinLi** [comment]
@abhaymathur21 
@ekzhu 

Any ideas how to fix this?

**Comment by jackgerrits** [comment]
Can replace `print` with `logging.info` or something similar

**Comment by abhaymathur21** [comment]
Can you check if my PR #1758 solves this isue?

**Comment by abhaymathur21** [comment]
No problem!
