### ISSUE TITLE
[Bug]: AttributeError: 'UserProxyAgent' object has no attribute '_human_inputs'

### ISSUE THREAD

**Issue by Sameerk22** [microsoft/autogen#1762]
### Describe the bug

 Notebooks involved:
[1] : https://github.com/microsoft/autogen/blob/main/notebook/agentchat_stream.ipynb
[2] : https://github.com/microsoft/autogen/blob/main/notebook/agentchat_groupchat_research.ipynb

#code throwing error
await acc_manager.a_initiate_chat(firm_manager, message=message) 

- acc_manager = User proxy agent
- firm _manager = autogen agent

Kindly correct it for future users.

**Comment by ayush111111** [comment]
I am able to succesfully execute both the mentioned scripts, please provide further details about the error

**Comment by Sameerk22** [comment]
The issue has been resolved. It was from my end. Sorry for inconvenience.
