### ISSUE TITLE
[Feature Request]: Handle Tool Calls and Responses in Context Handling

### ISSUE THREAD

**Issue by gagb** [microsoft/autogen#1775]
### Is your feature request related to a problem? Please describe.

Current implementation of TransformChatHistory does not handle tool calls and responses.

**Comment by gagb** [comment]
@dkirsche would be fun to add this feature! I'll submit a PR soon for review.

**Comment by gagb** [comment]
@WaelKarkoub you maybe interested in this issue as well. Can #1923 address this?

**Comment by WaelKarkoub** [comment]
@gagb I'm not fully familiar with how tool calls and responses are treated, but the PR should handle that case as well (I hope I'm not overconfident :) ). You have to implement the logic as a `MessageTransform` to handle the logic (which I don't have an example implemented). Something that comes to mind is maybe you want to drop all tool responses:

```python
class DropToolResponses:
    def apply(self, messages: List[Dict]) -> List[Dict]:
        return [message for message in messages if "tool_responses" not in message]
```

**Comment by clemlesne** [comment]
Strongly approve that :) It would be way easier to use AutoGen with that feature.

**Comment by gagb** [comment]
@clemlesne you maybe interested in PR #1923

**Comment by WaelKarkoub** [comment]
Just so I have a better understanding, the idea is to include tool calls and responses in the token count when we are truncating?

**Comment by rysweet** [comment]
looks like this was resolved.
