### ISSUE TITLE
Unable to build docker image on Arm 64 

### ISSUE THREAD

**Issue by Dave-56** [microsoft/autogen#1778]
### Describe the issue

Hi, I'm getting this error when trying to build a docker image. `33.78 2024-02-24 06:11:35 (11.5 MB/s) - ‘quarto-1.4.549-linux-amd64.deb’ saved [117253690/117253690]
33.78 
33.82 dpkg: error processing archive quarto-1.4.549-linux-amd64.deb (--install):
33.82  package architecture (amd64) does not match system (arm64)
33.82 Errors were encountered while processing:
33.82  quarto-1.4.549-linux-amd64.deb`

I do have a Mac with ARM 64. Do you have a way for me to bypass this issue. Thanks

### Screenshots and logs

<img width="1440" alt="Screenshot 2024-02-23 at 10 16 24 PM" src="https://github.com/microsoft/autogen/assets/28014546/ee28a09d-c1da-4cbe-81c7-6de23f35eda0">

**Comment by Dave-56** [comment]
Nevermind, I had to change the package to Arm64 and I was able to build the image

**Comment by yrichard** [comment]
hey @Dave-56 , would you mind sharing how you changed the package to arm64? Was it just by installing quarto for arm first or is there some trick? Thanks

**Comment by jackgerrits** [comment]
I am assuming they are referring to this: https://github.com/microsoft/autogen/blob/68337b955393e2e4995fb56b23ad362ce687b400/.devcontainer/Dockerfile#L17

We can parameterize this install based on arch though to avoid this issue in future
