### ISSUE TITLE
[Bug]: User interface views need sender returned in new "process_message_before_send" hook

### ISSUE THREAD

**Issue by radman-x** [microsoft/autogen#1788]
### Describe the bug

User interfaces for chat-like experience need to know what the sender is in the new "process_message_before_send" hook (PR #1783). Having the recipient is good but not enough. This is a very simple fix -- just pass "self" as the sender in ConversableAgent._process_message_before_send().

**Comment by sonichi** [comment]
Thanks. Adding sender in the hook is good. Would you like to make a PR?

**Comment by RohitRathore1** [comment]
> Thanks. Adding sender in the hook is good. Would you like to make a PR?

@sonichi I would like to open the PR against this issue. Thanks!
