### ISSUE TITLE
[Feature Request]: Lazy import of chromadb in teachability.py

### ISSUE THREAD

**Issue by rickyloynd-microsoft** [microsoft/autogen#1795]
### Is your feature request related to a problem? Please describe.

`teachability.py` uses chromadb as its default vector DB. Users can override this with another DB in their own subclasses of `Teachability` and `MemoStore`. Unfortunately, the import of chromadb at the top of `teachability.py` throws an error unless the chromadb package has been installed. Another solution would be to copy and modify the entire `teachability.py` file, and remove the import, but this would involve owning a lot more code than just the subclass modifications. 

### Describe the solution you'd like

AutoGen can make it easier for users to plug in their favorite vector DB by importing chromadb within the `MemoStore` class instead of at the top of `teachability.py`.

**Comment by rickyloynd-microsoft** [comment]
@shaileshj2803 Does this issue accurately describe the difficulty that the LinkedIn team is experiencing?

**Comment by hardchor** [comment]
Not sure about LinkedIn, but it accurately describes a problem I'm facing :sweat_smile:  We're trying to deploy autogen in a serverless environment, and having an in-memory database won't work, so we had to remove teachability for now.

**Comment by rickyloynd-microsoft** [comment]
> Not sure about LinkedIn, but it accurately describes a problem I'm facing 😅 We're trying to deploy autogen in a serverless environment, and having an in-memory database won't work, so we had to remove teachability for now.

Makes sense, but teachability is not installed by default. So when you say "remove teachability", do you mean "not install teachability"? For instance, the command to install teachability (specifically the chromadb package) would be this:

`pip install -e .[teachable]`

**Comment by hardchor** [comment]
Sorry, confusing wording! I meant we had it previously installed as one of our workflows and had to remove it when we discovered that it blew the size of the bundled package beyond what serverless (the framework) via AWS Lambdas was supporting. 

Currently, the only solution in that scenario seems to be to write a custom implementation of the teachability capability that integrates with a hosted vector DB, right?

**Comment by rickyloynd-microsoft** [comment]
> Sorry, confusing wording! I meant we had it previously installed as one of our workflows and had to remove it when we discovered that it blew the size of the bundled package beyond what serverless (the framework) via AWS Lambdas was supporting.
> 
> Currently, the only solution in that scenario seems to be to write a custom implementation of the teachability capability that integrates with a hosted vector DB, right?
> 
> EDIT: Basically exactly what you said above
> 
> > Another solution would be to copy and modify the entire teachability.py file, and remove the import, but this would involve owning a lot more code than just the subclass modifications.

Your new subclasses (of Teachability and MemoStore) could be quite small.

**Comment by hardchor** [comment]
Yeah but the hard requirement on `chromadb` at the top of  https://github.com/microsoft/autogen/blob/main/autogen/agentchat/contrib/capabilities/teachability.py#L5 pretty much means that we can't import and extend any of the existing code unless I misunderstood you?

> Unfortunately, the import of chromadb at the top of teachability.py throws an error unless the chromadb package has been installed.

**Comment by rickyloynd-microsoft** [comment]
> Yeah but the hard requirement on `chromadb` at the top of https://github.com/microsoft/autogen/blob/main/autogen/agentchat/contrib/capabilities/teachability.py#L5 pretty much means that we can't import and extend any of the existing code unless I misunderstood you?
> 
> > Unfortunately, the import of chromadb at the top of teachability.py throws an error unless the chromadb package has been installed.

Yes, that's why this issue was created. The fix is quite simple.

**Comment by rickyloynd-microsoft** [comment]
Stale. No longer planned.
