### ISSUE TITLE
[Issue]: assistant not giving complete response/stop streaming with incomplete sentence and user_proxy keeps replying empty

### ISSUE THREAD

**Issue by xuanyuxin** [microsoft/autogen#1806]
### Describe the issue

```
# create an AssistantAgent named "assistant"
assistant = autogen.AssistantAgent(
    name="assistant",
    llm_config={
        "cache_seed": 41,  # seed for caching and reproducibility
        "config_list": config_list,  # a list of OpenAI API configurations
        "temperature": 0,  # temperature for sampling
    },  # configuration for autogen's enhanced inference API which is compatible with OpenAI API
)
# create a UserProxyAgent instance named "user_proxy"
user_proxy = autogen.UserProxyAgent(
    name="user_proxy",
    human_input_mode="NEVER",
    max_consecutive_auto_reply=10,
    is_termination_msg=lambda x: x.get("content", "").rstrip().endswith("TERMINATE"),
    code_execution_config={
        "work_dir": "coding",
        "use_docker": False,  # Please set use_docker=True if docker is available to run the generated code. Using docker is safer than running the generated code directly.
    },
)
# the assistant receives a message from the user_proxy, which contains the task description
chat_res = user_proxy.initiate_chat(
    assistant,
    message="""How to define a junction using scenariogeneration, a Python library. After that, save the Python code in a file.""",
    summary_method="reflection_with_llm",
)
```

user_proxy (to assistant):

Write code to define a junction using scenariogeneration, a Python library. After that, save the Python code in a file.

--------------------------------------------------------------------------------
assistant (to user_proxy):

To define a junction using the `scenariogeneration` Python library,

--------------------------------------------------------------------------------
user_proxy (to assistant):

--------------------------------------------------------------------------------
assistant (to user_proxy):

First, we need to install the `scenariogeneration` library if

--------------------------------------------------------------------------------
user_proxy (to assistant):

--------------------------------------------------------------------------------
assistant (to user_proxy):

It seems there was a misunderstanding. Let me provide you with the Python code to

--------------------------------------------------------------------------------
user_proxy (to assistant):

--------------------------------------------------------------------------------
assistant (to user_proxy):

To define a junction using the `scenariogeneration` Python library,

--------------------------------------------------------------------------------
user_proxy (to assistant):

--------------------------------------------------------------------------------
assistant (to user_proxy):

To define a junction using the `scenariogeneration` Python library,

--------------------------------------------------------------------------------
user_proxy (to assistant):

--------------------------------------------------------------------------------
assistant (to user_proxy):

To define a junction using the `scenariogeneration` Python library,

--------------------------------------------------------------------------------
user_proxy (to assistant):

--------------------------------------------------------------------------------
assistant (to user_proxy):

To define a junction using the `scenariogeneration` Python library,

--------------------------------------------------------------------------------
user_proxy (to assistant):

--------------------------------------------------------------------------------
assistant (to user_proxy):

To define a junction using the `scenariogeneration` Python library,

--------------------------------------------------------------------------------
user_proxy (to assistant):

--------------------------------------------------------------------------------
assistant (to user_proxy):

To define a junction using the `scenariogeneration` Python library,

--------------------------------------------------------------------------------
user_proxy (to assistant):

--------------------------------------------------------------------------------
assistant (to user_proxy):

To define a junction using the `scenariogeneration` Python library,

--------------------------------------------------------------------------------
user_proxy (to assistant):

--------------------------------------------------------------------------------
assistant (to user_proxy):

To define a junction using the `scenariogeneration` Python library,

--------------------------------------------------------------------------------

### Steps to reproduce

I am using the example agentchat_auto_feedback_from_code_execution with my own azure GPT4-V endpoint. However, none of the example notebooks seem to reproduce any valid answer as suggested.

**Comment by gagb** [comment]
user_proxy returns empty because there are no code blocks to execute.
Per your current config of is_termination_msg it will only terminate if the assistant message ends with the string "TERMINATE" or if you reach max consecutive auto reply.

@afourney you have used the azure gpt4-v endpoints. Do you see this issue?

**Comment by xuanyuxin** [comment]
Solved by setting max_tokens to a larger non-default value. Thx
