### ISSUE TITLE
[Feature Request]: Async Code Execution

### ISSUE THREAD

**Issue by gagb** [microsoft/autogen#1815]
### Is your feature request related to a problem? Please describe.

Update conversable agent to enable async code execution.

**Comment by julianakiseleva** [comment]
@sonichi

**Comment by RohitRathore1** [comment]
I would like to participate in this.

**Comment by ekzhu** [comment]
@RohitRathore1 thanks! First we need to figure out why there is no async version for code execution reply function. @qingyun-wu @sonichi

**Comment by RohitRathore1** [comment]
@ekzhu is there any communication channel to have these conversations(core chats)?

**Comment by ekzhu** [comment]
@RohitRathore1. I got the context: there isn't any particular reason for not having async code execution reply function. I believe you are good to go to add it :D. There are two of them, one is `generate_code_execution_reply` and the other one is `_generate_code_execution_reply_using_executor` -- both of them would need an async version. Ping me and @jackgerrits  for review. 

For asking questions like this, just post it on Github Discussion or Discord (#agent-coding channel for code execution related questions).

**Comment by RohitRathore1** [comment]
@ekzhu & @jackgerrits I have opened the PR. Please have a look at it and let me know your views, thanks!

**Comment by RohitRathore1** [comment]
@jackgerrits @ekzhu @gagb is there any further plans/discussions?

https://github.com/microsoft/autogen/pull/1875#issuecomment-1981731175
