### ISSUE TITLE
[Feature Request]: Add threshold to retrieval config

### ISSUE THREAD

**Issue by szwang-seedtech** [microsoft/autogen#1830]
### Is your feature request related to a problem? Please describe.

Hello,

The current rag seems to list the top few numbers of chunks into the retrieval content, and then filter them by determing whether they are related to the question, and this will still waste a certain number of tokens at the first place. 

Is it possible to add a threshold setting to the retrieval config, so that only the similarity over the threshold value will be listed in the retrieval content?

**Comment by thinkall** [comment]
Hi @szwang-seedtech , we don't support a threshold, but you can set `context_max_tokens` to control the maximum number of tokens in the context, the default is `max_tokens * 0.8` which `max_token` means  the token limit of the model.

**Comment by szwang-seedtech** [comment]
@thinkall Hello, I am just wondering, will the threshold feature be added in the future. According to my test, the unrelated information in the retrieval_content will actually make an impact on the replies from agents.

**Comment by szwang-seedtech** [comment]
I see. Thank you. I will close this request then : )
