### ISSUE TITLE
[Bug]: `overlap`  parameter in the  `split_text_to_chunks`  not used.

### ISSUE THREAD

**Issue by mohamedaliELfeky** [microsoft/autogen#1844]
### Describe the bug

`overlap`  in the `split_text_to_chunks` function in the `autogen.retrieve_utils.split_text_to_chunks`, I think it's easy to fix it by adding it in the right place [](url)

### Steps to reproduce

1. go to autogen.retrieve_utils file
2. search for the function `split_text_to_chunks`
3. it will be in the parameters but not used with `cnt` indexing

**Comment by szwang-seedtech** [comment]
I have the same issue. Besides, I think the "must_break_at_empty_line" also not working.

**Comment by mohamedaliELfeky** [comment]
@szwang-seedtech I have read the code and I'm sure they are breaking on `\n`  but the problem will be in the pdf reader it doesn't make any cleaning for the text, so you will feel that you have a lot of tokens in one line but actually it's a noise.

**Comment by szwang-seedtech** [comment]
oh I see. That explains. Thank you!

**Comment by thinkall** [comment]
Will be added in a future version. Thanks.

**Comment by thinkall** [comment]
Supported in #2271
