### ISSUE TITLE
[Issue]: Can Autogen configure a network proxy

### ISSUE THREAD

**Issue by guanfeiyun** [microsoft/autogen#1849]
### Describe the issue

Can Autogen configure a network proxy to make calls to the official interfaces of AOAI or OpenAI through the network proxy.
Due to poor local network quality, I would like to set up a network proxy. Can it be done in Autogen? Where can I set it up?

### Steps to reproduce

The system proxy's https proxy and https proxy have been set, but they are not effective in the Autogen program. Do I need to directly add a proxy network proxy in the program

### Additional Information

autogenstudio  version:  0.0.47  
pyautogen version:  0.2.16

**Comment by ekzhu** [comment]
Have you checked out LLM proxies like Ollama and LiteLLM?
