### ISSUE TITLE
is it possible to run autogen locally with LLMs models without API ?! 

### ISSUE THREAD

**Issue by Mana-84** [microsoft/autogen#185]
could you assist, thank you

**Comment by TomExMachina** [comment]
The short answer is 'yes' but this sort of inquiry would best be served as a [Discussion](https://github.com/microsoft/autogen/discussions) thread or on the Discord server. If you search [the Discord](https://discord.gg/aqDEbM4Y) you will find several discussions regarding that topic.

**Comment by Mana-84** [comment]
@TomExMachina  appreciated a lot 👍
