### ISSUE TITLE
token size max

### ISSUE THREAD

**Issue by jkf87** [microsoft/autogen#186]
I'm running the example code (notebook/agentchat_teaching.ipynb) and it keeps getting stuck at token size max.

**Comment by sonichi** [comment]
At which step does it get stuck? Is GPT-4-32K used?

**Comment by erthman18** [comment]
I have the same problem. Is there any other method besides 32k? For example, does it support sliding windows?

**Comment by erthman18** [comment]
> At which step does it get stuck? Is GPT-4-32K used?



> At which step does it get stuck? Is GPT-4-32K used?


I have the same problem. Is there any other method besides 32k? For example, does it support sliding windows?

**Comment by sonichi** [comment]
#195 #131 are two methods
And there is a roadmap #156
