### ISSUE TITLE
Is it possible to call one function multiple times, with different arguments, from one agent message?

### ISSUE THREAD

**Issue by tyler-suard-parker** [microsoft/autogen#1860]
### Is your feature request related to a problem? Please describe.

For example, let's say I have a function called search().
Would it be possible to instruct my agent that it can call that function twice in a single turn, as in it can use that function to search for cats, and it can use that function to search for dogs, and both results sets would be returned?

For example: You are a helpful agent.  Function: search()  argument: query

Me: which is better, a cat or a dog?
Agent:
*Runs search() on "cat"
*Runs search() on "dog"
Agent: Cats and dogs are both good pets.

**Comment by gagb** [comment]
AFAIK open supports parallel function calling so yes this should be possible.

**Comment by leonDuWoo** [comment]
how to enable this feature?
