### ISSUE TITLE
[Issue]: How to redirect to one specific agent 

### ISSUE THREAD

**Issue by YogeshNat** [microsoft/autogen#1883]
### Describe the issue

How to redirect the input based on expertise in groupchat?
For example, In a groupchat there are two agent (say math and science), the input is "what is 2+2", Based on the input the manager should redirect it to math Agent. The other agent should not reply. How to do this?

Thanks
Yogesh

**Comment by qingyun-wu** [comment]
Do you have an explicit rule/criteria for deciding what message to predict to which agent? If so, you could achieve it using a custom `speaker_selection_method`.  Find an example in this notebook: https://github.com/microsoft/autogen/blob/main/notebook/agentchat_groupchat_customized.ipynb

**Comment by rysweet** [comment]
example above and lots of examples in 0.4
