### ISSUE TITLE
[bug]the sanitize_agent_spec is called multiple times, the system_prompts has duplicate content.

### ISSUE THREAD

**Issue by cillyfly** [microsoft/autogen#1898]
https://github.com/microsoft/autogen/blob/2e51cb3f6a23e75b50736762f4ac386e62a24f16/samples/apps/autogen-studio/autogenstudio/workflowmanager.py#L194

when it is groupchat will be call twice sanitize_agent_spec
```python
        agent_spec = self.sanitize_agent_spec(agent_spec)
        if agent_spec.type == "groupchat":
            agents = [
                self.load(self.sanitize_agent_spec(agent_config)) for agent_config in agent_spec.groupchat_config.agents
            ]
```

agent_spec.config.system_message is a global parameter if this Function called twice system_message will has  duplicate content.

https://github.com/microsoft/autogen/blob/2e51cb3f6a23e75b50736762f4ac386e62a24f16/samples/apps/autogen-studio/autogenstudio/workflowmanager.py#L175

```python
        if agent_spec.skills:
            # get skill prompt, also write skills to a file named skills.py
            skills_prompt = ""
            skills_prompt = get_skills_from_prompt(agent_spec.skills, self.work_dir)
            if agent_spec.config.system_message:
                agent_spec.config.system_message = agent_spec.config.system_message + "\n\n" + skills_prompt
            else:
                agent_spec.config.system_message = get_default_system_message(agent_spec.type) + "\n\n" + skills_prompt


```

**Comment by cillyfly** [comment]
change the logic by adding skill_prompts to updating 

![example](https://personal-1309068468.cos.ap-shanghai.myqcloud.com/img/20240307125125.png)

**Comment by victordibia** [comment]
Hi @cillyfly ,

Thanks for noting this.  
I believe some of this might have been fixed in the dev [branch](https://github.com/microsoft/autogen/blob/autogenstudio/samples/apps/autogen-studio/autogenstudio/workflowmanager.py) ..

Please see the autogenstudio [contribution guide](https://github.com/microsoft/autogen/tree/autogenstudio/samples/apps/autogen-studio#contribution-guide). 
Ideally, PRs should be based on the dev branch which is typically ahead of main.

**Comment by victordibia** [comment]
Also ..
> when it is groupchat will be call twice sanitize_agent_spec 

Can you clarify what you mean here? 
- agent_spec = self.sanitize_agent_spec(agent_spec) .. this is for GroupChatManager spec
- agents = [ self.load(self.sanitize_agent_spec(agent_config)) ... this is for agents in the group chat. 

Do you you mean the groupchat manager ends up with duplicate content?

**Comment by cillyfly** [comment]
> Also ..
> 
> > when it is groupchat will be call twice sanitize_agent_spec
> 
> Can you clarify what you mean here?
> 
> * agent_spec = self.sanitize_agent_spec(agent_spec) .. this is for GroupChatManager spec
> * agents = [ self.load(self.sanitize_agent_spec(agent_config)) ... this is for agents in the group chat.
> 
> Do you you mean the groupchat manager ends up with duplicate content?

Mainly because `agent_spec.config.system_message = agent_spec.config.system_message + "\n\n" + skills_prompt`. When sanitize_agent_spec is called externally many times, skills will be added to system Prompts many times. if skills exist.

**Comment by victordibia** [comment]
Closing, given this has been fixed.
