### ISSUE TITLE
[Bug]: build and test documentation require a new version of Quarto

### ISSUE THREAD

**Issue by kevin666aa** [microsoft/autogen#1925]
### Describe the bug

When building locally, I encounter this error when running `python process_notebooks.py render`:

```
...
Quarto version is too old. Please upgrade to 1.5.23 or later.
```

And when run `yarn start` it fails.
```
[ERROR] Sidebars file at "/Users/kevin/Desktop/Desktop files/playground/autogen/website/sidebars.js" failed to be loaded.
[ERROR] Loading of version failed for version current

Error: Sidebar category Topics has neither any subitem nor a link. This makes this item not able to link to anything.
```

I am using MacOS 13.4 (22F66) (Apple Chip), and I installed Quarto=1.4.551 from the link in contributing document.
The problem is solved when installing a prelease version quarto=1.5.24 from https://quarto.org/docs/download. 

@sonichi @skzhang1 @qingyun-wu Should I make a PR to update the version? I am not sure this happens to other OSs.

**Comment by ekzhu** [comment]
I think would be good to update the Contribute.md in the website about the quarto version requirement

**Comment by sonichi** [comment]
@jackgerrits for awareness.

**Comment by jackgerrits** [comment]
Yes, we require a recent pre-release version of Quarto. They fixed some bugs for us that were blocking the docs build. All of their releases have installable artifacts on the release page.

I'll update the contributing page to highlight this fact.

**Comment by jackgerrits** [comment]
You should go ahead and make a PR if you'd like to. I would love your suggestion on how to make this clear to users. I am biased on presentation since I changed the version requirement.

Thanks for helping improve the dev experience!

**Comment by kevin666aa** [comment]
Thanks @jackgerrits! I have created a PR to update the Quarto version, and some other improvements to the doc.
