### ISSUE TITLE
is there anyway to set proxy in LLM Config? 

### ISSUE THREAD

**Issue by stnbSim** [microsoft/autogen#197]
i cant access the internet without reverse proxy, just wonder if there is a way to config it? 
thanks

**Comment by sonichi** [comment]
I don't understand this question. Would you like to ask on Discord?

**Comment by stnbSim** [comment]
hi @sonichi, 

i will need to use my firm's proxy to connect to the internet, I wonder where I can include that in the config, can I do something like below ?

config_list = [
    {
        'model': 'gpt-3.5-turbo-16k',
        'api_key': os.environ.get("OPENAI_API_KEY"),
        **"proxy": 'http://myfirmproxyaddress:8000'**
    },
]

**Comment by sonichi** [comment]
I understand the question now but I don't know the answer. Could you ask on OpenAI's forum? autogen uses the openai package underneath.

**Comment by stnbSim** [comment]
@sonichi , the python library of openai support using it with proxy by 

```
import openai
openai.proxy = "insert proxy here.."
```

**Comment by sonichi** [comment]
In that case, simply add the same line in your code before you initiate the chat.
