### ISSUE TITLE
[Bug]: Error occurred while creating agent: table agents has no column named description

### ISSUE THREAD

**Issue by juandrei** [microsoft/autogen#1986]
### Describe the bug

Autogen Studio:  impossible to create a new agent.  Always get this error, and no agent created.

### Steps to reproduce

I tried to create a team of agents, so tried to instantiate several agents. That didn't work per the error above. Then, duplicating the existing agent still led to the same error.  I am on v0.0.52

### Model Used

gpt4-turbo

### Expected Behavior

An agent should have been instantiated. Any other reasons why this instantiation should fail?

**Comment by juandrei** [comment]
Detailed log: 
INFO:     127.0.0.1:52815 - "POST /api/agents HTTP/1.1" 200 OK
INFO:     127.0.0.1:54428 - "GET /api/models?user_id=guestuser@gmail.com HTTP/1.1" 200 OK
Error running query with query INSERT INTO agents (id, user_id, timestamp, config, type, description, skills) VALUES (?, ?, ?, ?, ?,?) and args ('8486c32d-267c-46af-9e3e-dfa68f089894', 'guestuser@gmail.com', '2024-03-13T00:35:30.821706', '{"name": "sample_assistant", "llm_config": {"config_list": [{"model": "gpt-4-1106-preview"}], "temperature": 0.1, "cache_seed": null, "timeout": 600}, "human_input_mode": "NEVER", "max_consecutive_auto_reply": 8, "system_message": "You are a helpful AI assistant. Solve tasks using your coding and language skills. In the following cases, suggest python code (in a python coding block) or shell script (in a sh coding block) for the user to execute. 1. When you need to collect info, use the code to output the info you need, for example, browse or search the web, download/read a file, print the content of a webpage or a file, get the current date/time, check the operating system. After sufficient info is printed and the task is ready to be solved based on your language skill, you can solve the task by yourself. 2. When you need to perform some task with code, use the code to perform the task and output the result. Finish the task smartly. Solve the task step by step if you need to. If a plan is not provided, explain your plan first. Be clear which step uses code, and which step uses your language skill. When using code, you must indicate the script type in the code block. The user cannot provide any other feedback or perform any other action beyond executing the code you suggest. The user can\'t modify your code. So do not suggest incomplete code which requires users to modify. Don\'t use a code block if it\'s not intended to be executed by the user. If you want the user to save the code in a file before executing it, put # filename: <filename> inside the code block as the first line. Don\'t include multiple code blocks in one response. Do not ask users to copy and paste the result. Instead, use \'print\' function for the output when relevant. Check the execution result returned by the user. If the result indicates there is an error, fix the error and output the code again. Suggest the full code instead of partial code or code changes. If the error can\'t be fixed or if the task is not solved even after the code is executed successfully, analyze the problem, revisit your assumption, collect additional info you need, and think of a different approach to try. When you find an answer, verify the answer carefully. Include verifiable evidence in your response if possible. Reply \'TERMINATE\' in the end when everything is done.", "is_termination_msg": null, "code_execution_config": false, "default_auto_reply": "", "description": ""}', 'assistant', '[]'): table agents has no column named description
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ag/lib/python3.11/site-packages/autogenstudio/web/app.py", line 387, in create_user_agents
    agents = dbutils.upsert_agent(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/ag/lib/python3.11/site-packages/autogenstudio/utils/dbutils.py", line 735, in upsert_agent
    dbmanager.query(query=query, args=args)
  File "/opt/anaconda3/envs/ag/lib/python3.11/site-packages/autogenstudio/utils/dbutils.py", line 307, in query
    raise e
  File "/opt/anaconda3/envs/ag/lib/python3.11/site-packages/autogenstudio/utils/dbutils.py", line 299, in query
    self.cursor.execute(query, args)
sqlite3.OperationalError: table agents has no column named description

**Comment by taowang1993** [comment]
i just got the same error

**Comment by cillyfly** [comment]
maybe remove the old database.sqlite and restart service will work

taowang1993 ***@***.***>于2024年3月13日 周三08:36写道：

**Comment by cillyfly** [comment]
Issue #1976 update to 0.0.53

**Comment by victordibia** [comment]
@juandrei ,  as @cillyfly mentioned, the latest version addresses the issue.

```bash
pip install -U autogenstudio
```

Related to #1976
