### ISSUE TITLE
How to dynamically select a function based on user input

### ISSUE THREAD

**Issue by erthman18** [microsoft/autogen#201]
For example, there are 100 interfaces in my database. I can't put them all into functions at once. Instead, I need to match the most likely 3 interfaces each time based on the user's question.

**Comment by sonichi** [comment]
I have some ideas but I'll give other researchers a chance to take a look.

**Comment by joshkyh** [comment]
For some inspiration... https://gorilla.cs.berkeley.edu/ :D

**Comment by sonichi** [comment]
This is a common problem in production. Solvable. Low-hanging fruits for researchers.
