### ISSUE TITLE
 AttributeError: 'str' object has no attribute 'copy'[Bug]: 

### ISSUE THREAD

**Issue by sjosephrw** [microsoft/autogen#2016]
### Describe the bug

After installing autogen with ```python3 pip install pyautogen```, I get this error,   File "/home/UserName/apps/ai_projects/IAC2/venv/lib/python3.11/site-packages/autogen/oai/client.py", line 372, in <listcomp>
    config_list = [config.copy() for config in config_list]  # make a copy before modifying
                   ^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'copy'

### Steps to reproduce

pip install pyautogen

python3 app.py

### Model Used

gpt - 4

### Expected Behavior

autogen agents should have started running

### Screenshots and logs

![image](https://github.com/microsoft/autogen/assets/36753901/cc675986-9001-48c0-b7d3-6514edf0791b)

**Comment by sjosephrw** [comment]
Here is a code sample of my autogen project, the config object seems fine, but I could be wrong
```python3

config = {
    "config_list": [{"model": "gpt-4", "api_key": os.environ["OPENAI_API_KEY"]}],
}


#config_list_gpt4 = ["gpt-4"]

gpt4_config = {
    "use_cache": False,
    "seed": 42,  # change the seed for different trials
    "temperature": 0,
    "config_list": config,
    "request_timeout": 120,
}


'''
Can you confirm the call to the assistant agent looks good?
assistant = autogen.AssistantAgent(
name='assistant',
llm_config={
"cache_seed": 42, # seed for caching and reproducibility
"config_list": config_list, # a list of OpenAI API configurations
"temperature": 0, # temperature for sampling
}, # configuration for autogen's enhanced inference API which is compatible with OpenAI API
)
'''


user_proxy = autogen.UserProxyAgent(
    name="Admin",
    llm_config=gpt4_config,
    system_message="A human admin. Interact with the planner to discuss the plan. Plan execution needs to be approved by this admin.",
    code_execution_config=False,
)
```

**Comment by qingyun-wu** [comment]
I think you should use `config["config_list"]` in the `config_list` field of `gpt4_config`, i.e.,

```python
gpt4_config = {
    "use_cache": False,
    "seed": 42,  # change the seed for different trials
    "temperature": 0,
    "config_list": config["config_list"],
    "request_timeout": 120,
}
```
