### ISSUE TITLE
[Blog bug]: AutoGen Studio repo link is not accessible.

### ISSUE THREAD

**Issue by hobbytp** [microsoft/autogen#2018]
### Describe the bug

In https://github.com/microsoft/autogen/blob/main/website/blog/2023-12-01-AutoGenStudio/index.mdx
Under "## The AutoGen Studio API" section, the link is not accessible.
```
Please consult the [AutoGen Studio repo](https://microsoft.github.io/autogen/docs/autogenstudio) for more details.
```

or blog issue will not be fixed because some of them will be outdate soon?

**Comment by qingyun-wu** [comment]
Thanks for the catch! We would like to fix it :)  cc-ing @victordibia, @gagb
