### ISSUE TITLE
[Issue]: Enhance notebook contributing guide

### ISSUE THREAD

**Issue by qingyun-wu** [microsoft/autogen#2032]
### Describe the issue

Some suggestions based on my experience of contributing notebooks following the notebook contributing guide:
- Shall we rename this [contributing.md](https://github.com/microsoft/autogen/blob/main/notebook/contributing.md) file in the notebook folder to "README.md" such as it displays in the folder automatically. 
- Add more detail on where to add the [metadata](https://github.com/microsoft/autogen/blob/main/notebook/contributing.md#metadata-fields) in the notebook. There are multiple metadata fields in one notebook (each cell has a "metadata" field). It seems we need to add it to the one above the "kernelspec" field. 
- Changes made in this [PR](https://github.com/microsoft/autogen/pull/1969) could be used as references/examples. (I find them helpful) 
cc-ing @jackgerrits

**Comment by rysweet** [comment]
have been adopted in new docs
