### ISSUE TITLE
[Bug]: Icons are off center on homepage

### ISSUE THREAD

**Issue by jackgerrits** [microsoft/autogen#2053]
### Describe the bug

On the website home page the icons are off center

### Expected Behavior

These should be centered above the text.

### Screenshots and logs

<img width="1321" alt="image" src="https://github.com/microsoft/autogen/assets/7558482/397d093f-4675-45bf-b9e9-618f4a5f561a">

**Comment by veh3546** [comment]
I'd like to work on this!
