### ISSUE TITLE
[Roadmap] Context Handling

### ISSUE THREAD

**Issue by gagb** [microsoft/autogen#2069]
> [!TIP]
> ## Want to get involved?
> We'd love it if you did! Please get in contact with the people assigned to this issue, or leave a comment. See general contributing advice [here](https://microsoft.github.io/autogen/docs/Contribute) too.

## Description

Roadmap for adding context handling to AutoGen agents.

```[tasklist]
- [ ] https://github.com/microsoft/autogen/pull/1591
- [ ] #1775
- [ ] #1923
- [ ] https://github.com/microsoft/autogen/pull/2247
```

**Comment by jackgerrits** [comment]
Brought up in office hours - Have we considered adding support for LLMLingua? https://github.com/microsoft/LLMLingua

**Comment by gagb** [comment]
> Brought up in office hours - Have we considered adding support for LLMLingua? https://github.com/microsoft/LLMLingua

@WaelKarkoub raised that in #1923
