### ISSUE TITLE
[Issue]: RetrieverUserAgent taking relly long to provide output >5 min

### ISSUE THREAD

**Issue by shaleenrajkaur** [microsoft/autogen#2104]
### Describe the issue

Is this normal? I'm following this (`https://microsoft.github.io/autogen/blog/2023/10/18/RetrieveChat/`) would appreciate any guidance thank you!

**Comment by gagb** [comment]
@thinkall

**Comment by thinkall** [comment]
Hi @shaleenrajkaur , is it happens at the first time creating the vector db collection or happens at every single chat? It could take a few minutes to chunk and embed the docs depends on the sizes of the docs.

**Comment by thinkall** [comment]
Close as no active response for a long time. Please reopen it or create a new issue if needed.
