### ISSUE TITLE
ModuleNotFoundError: No Module named 'autogen'

### ISSUE THREAD

**Issue by iainvdp** [microsoft/autogen#211]
Hi All, 

I have copied the multi-agent conversation framework example python code, added an openai api key line and pip installed pyautogen.

When running the script i receive the following error:

 File "/Users/XXXX/Desktop/autogen/app.py", line 1, in <module>
    from autogen import AssistantAgent, UserProxyAgent, config_list_from_json
ModuleNotFoundError: No module named 'autogen'

To rectify I have pip uninstalled then pip installed pyautogen to no avail.

Any help would be appreciated.

Thanks.

**Comment by sonichi** [comment]
This may be an environment issue. Could you try installing `pyautogen` in a clean virtual environment like venv?

**Comment by Rakly3** [comment]
I had the exact same issue earlier, uninstalling 'autogen' and installing 'pyautogen' fixed it.

**Comment by WieMaKa** [comment]
> Hi All,
> 
> I have copied the multi-agent conversation framework example python code, added an openai api key line and pip installed pyautogen.
> 
> When running the script i receive the following error:
> 
> File "/Users/XXXX/Desktop/autogen/app.py", line 1, in from autogen import AssistantAgent, UserProxyAgent, config_list_from_json ModuleNotFoundError: No module named 'autogen'
> 
> To rectify I have pip uninstalled then pip installed pyautogen to no avail.
> 
> Any help would be appreciated.
> 
> Thanks.

I am facing the same issue.

I have setup a new environment and installed first autogen via pip.

I have uninstalled autogen and installed pyautogen -> still same error

switched to venv and installed just pyautogen -> success 
thanks @sonichi

**Comment by sonichi** [comment]
Shall we modify https://microsoft.github.io/autogen/docs/Installation to reduce the chance of error?

**Comment by vici30** [comment]
I tried both pip and venv and I still get ModuleNotFoundError: No module named 'autogen'

**Comment by web3wes** [comment]
Same here at the moment. 


> I tried both conda and venv and I still get ModuleNotFoundError: No module named 'autogen'

**Comment by web3wes** [comment]
looks like I was in nested environments. The following worked for me.

- Running `conda deactivate` until I was out off all envs.
- activating a new env
- installing pyautogen

**Comment by gagb** [comment]
> I tried both conda and venv and I still get ModuleNotFoundError: No module named 'autogen'

Did you do `pip install pyautogen`?

**Comment by gagb** [comment]
@iainvdp was your issue fixed?

**Comment by vici30** [comment]
> > I tried both conda and venv and I still get ModuleNotFoundError: No module named 'autogen'
> 
> Did you do `pip install pyautogen`?

Yes. I tried making a complete new venv as well.
Also I am not in nested environments

**Comment by gagb** [comment]
There gotta be an issue with your setup. Post details of your setup and every command you ran and maybe we can help. Also try a different machine.

**Comment by 1337hero** [comment]
Same problem here - tried some of the steps above - autogen and pyautogen.

Traceback (most recent call last):
  File "/Users/mikekey/app.py", line 1, in <module>
    import pyautogen
ModuleNotFoundError: No module named 'pyautogen'
(pyautogen)

can't find the module currently running, absolute hilarity

**Comment by 1337hero** [comment]
> Same problem here - tried some of the steps above - autogen and pyautogen.
> 
> Traceback (most recent call last): File "/Users/mikekey/app.py", line 1, in import pyautogen ModuleNotFoundError: No module named 'pyautogen' (pyautogen)
> 
> can't find the module currently running, absolute hilarity

Nuking conda and doing `pip install pyautogen` worked for me finally after a reboot

**Comment by eleshinlomo** [comment]
Don't use " import autogen"  pip install pyautogen in your venv and use,

from autogen import AssistantAgent, UserProxyAgent, config_list_from_json

# Load LLM inference endpoints from an env variable or a file
# See https://microsoft.github.io/autogen/docs/FAQ#set-your-api-endpoints
# and OAI_CONFIG_LIST_sample.json
config_list = config_list_from_json(env_or_file="OAI_CONFIG_LIST")
assistant = AssistantAgent("assistant", llm_config={"config_list": config_list})
user_proxy = UserProxyAgent("user_proxy", code_execution_config={"work_dir": "coding"})
user_proxy.initiate_chat(assistant, message="Plot a chart of NVDA and TESLA stock price change YTD.")
# This initiates an automated chat between the two agents to solve the task

**Comment by aganiezgoda** [comment]
I'm also facing the issue. None of the above solutions have worked.

**Comment by pedrodbs** [comment]
I was having the same issue. In my case, the problem was that my python file was named "autogen.py", hence the import error. 
Could it also be the case with OP, since "autogen" is part of the python script's path, thus being considered a local module?

**Comment by ekzhu** [comment]
https://microsoft.github.io/autogen/docs/FAQ#install-the-correct-package---pyautogen

**Comment by faridguellai** [comment]
solve by : 
which python3. # to get the root directory of your python environement.
install comande
/directory/python3 -m pip install pyautogen

**Comment by sleing** [comment]
I met the same problem

**Comment by CellCS** [comment]
Issue: 

![Image](https://github.com/user-attachments/assets/04506027-0779-41fe-8389-95a3e418f85a)

Solution Steps:
1. Install 'uv' by referencing [uv installation](https://docs.astral.sh/uv/getting-started/installation/)

```bash
# install uv
curl -LsSf https://astral.sh/uv/install.sh | sh
# add $HOME/.local/bin to your PATH 
source $HOME/.local/bin/env
```

![Image](https://github.com/user-attachments/assets/445af91c-478b-4a4a-b6c5-3eac52ac4ffc)

3. Locate at "autogen/python/" and install all dependencies, 

```bash
uv sync  --all-extras
```

4 issue is solved: .venv is created unser "/autogen/python"

![Image](https://github.com/user-attachments/assets/75393fa1-d2a1-4e25-bf01-bf8bb918d821)

5:  execute example.

```bash
source .venv/bin/activate
cd packages/autogen-magentic-one 
python3 examples/example.py --logs_dir ./my_logs
```
