### ISSUE TITLE
Something went wrong when i run the agentchat_websockets, how can i solve this problem?

### ISSUE THREAD

**Issue by SsspongeBob** [microsoft/autogen#2111]
Something went wrong when i run the agentchat_websockets, how can i solve this problem?
![image](https://github.com/microsoft/autogen/assets/136151131/5b03a990-b31f-47ef-b609-c6ee320ed955)

_Originally posted by @SsspongeBob in https://github.com/microsoft/autogen/issues/1551#issuecomment-2009903947_

**Comment by Abdul-Maajith** [comment]
What went wrong, and how did you resolve it? @SsspongeBob ?

**Comment by SsspongeBob** [comment]
> What went wrong, and how did you resolve it? @SsspongeBob ?

I haven't solve it yet, the code I pulled is not from the main branch, it's the branch named "autogen-add-output-protocol", it add the WebSocket protocol to autogen, but i couldn't run the notebook it provided, the error is on the image.
