### ISSUE TITLE
[Bug]: AutogenStudio GroupChat Skills Importing Issue

### ISSUE THREAD

**Issue by ShaneYuTH** [microsoft/autogen#2115]
### Describe the bug

If there are multiple assistant agents with skills, only one agent’s skill will be wrote to skills.py file. If other agents skill is called, an unable to import error will occur, in this case, the assistant agent will either try to write its own version of skills to fulfill the task or repeat its previous instruction till max output limit reached.

### Steps to reproduce

1. Create a groupchat workflow with multiple agents who each has multiple skills
2. Run the workflow
3. Check skills.py and see only one agent's skill is wrote to the file.

### Model Used

gpt-4-1106-preview

### Expected Behavior

When a skill is called but not present in skills.py, the assistant agent will either try to write its own version of skills to fulfill the task or repeat its previous instruction till max output limit reached.

**Comment by victordibia** [comment]
Thanks for reporting this.
I have added fix in workflow manager as follows:
- create a `workflow_skills=[]` class variable
- when agents are loaded, update `workflow_skills` with agent skills 
- after all agents load (sender and receiver), write all skills to `skills.py`. 

This is released in  v`0.0.56` 

```python
pip install -U autogenstudio
```

**Comment by odeduxi** [comment]
Thank you so much for fixing so fast, I tested and it works well!!!

**Comment by victordibia** [comment]
Great! I will go ahead and close this out now. 
Thank you both for reporting and testing.

**Comment by ShaneYuTH** [comment]
Works as expected! Thanks for the great work!
