### ISSUE TITLE
Keep cache off by default avoid confusion and file system access error

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#2133]
### Is your feature request related to a problem? Please describe.

We should keep the cache off by default. Only turn it on either using the legacy `cache_seed` setting in llm_config or use the new `autogen.cache.Cache`. 

Many issues from people having difficulty using the default cache in cloud environment where the application has no file system write permission. 

### Describe the solution you'd like

Remove the default cache seed in `autogen.oai.client`.

**Comment by afourney** [comment]
FWIW, I disable it in AutoGenBench due to permission issues. Basically, when run in Docker, the cache folder is owned by root and it causes trouble when trying to reset and re-run benchmarks,

**Comment by ekzhu** [comment]
@afourney, you can use redis cache or change the cache root directory: 

https://microsoft.github.io/autogen/docs/topics/llm-caching

**Comment by afourney** [comment]
It's ok. I just turn it off. Each task only runs once

**Comment by jackgerrits** [comment]
While we at it, we should add a deprecation warning for the "old" way of doing this so we can eventually consolidate and clean up

**Comment by tyler-suard-parker** [comment]
@afourney how did you turn it off?  I am having the same issues with cloud containers and write permissions.
