### ISSUE TITLE
[Feature Request]: different termination message function for different sender agent

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#2134]
### Is your feature request related to a problem? Please describe.

A single agent needs to have different termination check for different sender agent. For example, when you register nested chats, the parent agent needs to check termination for the inner chats, and for different inner agents' different termination message might be needed. E.g., if you want an inner chat to keep working until no "Error" in the reply, but only do it for a specific inner recipient. 

Right now, the termination message check is performed on the message only, need to expand that to include sender agent as well. 

### Describe the solution you'd like

Possible solutions:
- Change `is_termination_msg` parameter to allow `Agent` as a parameter. 
- Supply a dictionary that maps Agent --> termination message check function. 
- Add `is_termination_msg` parameter to `register_reply` and expose this through `register_nested_chats`.

### Additional context

We also need sender specific system message so we can have different instructions for replying to different senders.

_No response_

**Comment by afourney** [comment]
At least in the group chat setting, I believe you can get the sender via the name field — but I haven’t tried it in this specific application context
