### ISSUE TITLE
[Issue]: Code executor Documentation Bug: should use temp_dir.name

### ISSUE THREAD

**Issue by peteryxu** [microsoft/autogen#2136]
### Describe the issue

In this doc:  https://microsoft.github.io/autogen/docs/tutorial/code-executors

This code below failed with error attached: 

import os
print(os.listdir(temp_dir))
# We can see the output scatter.png and the code file generated by the agent.
 
<img width="768" alt="image" src="https://github.com/microsoft/autogen/assets/5605055/e9c15cdf-66ec-48ec-bbe9-f0e0e29b5f21">

Simple fix:
print(os.listdir(temp_dir.name))

**Comment by ekzhu** [comment]
Thanks! Would you like to submit a PR to fix it?

**Comment by ekzhu** [comment]
> I experienced same issue. Replace _temp_dir_ with _temp_dir.name_

Interested in submitting a PR?

**Comment by ekzhu** [comment]
You have my support.

**Comment by jtoy** [comment]
This is fixed already, I cant link to the line because its a ipynb file, but I just checked the source:
https://github.com/microsoft/autogen/blob/main/website/docs/tutorial/code-executors.ipynb
Can we close this ticket now please. cc @ekzhu @peteryxu

**Comment by DLWCMD** [comment]
Thanks and will do.
