### ISSUE TITLE
Simply config_list creation in notebooks and fix examples where llm configs are shared

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#2139]
This is a notebook janitorial work. But easy to do. 

1. Overwhelming feedback is that using the config list creation utils creates steep learning curve for users. We can keep that as advanced utils like caching, but we can use raw config list -- a simple list of dictionaries in our notebooks. See our tutorial for example.

2. Sharing llm_config is bad! Because registering functions modifies agent's llm_config. Go through the notebooks to fix examples where llm_config is shared. Replace them with separate llm_config for each agent.

**Comment by prithvi2226** [comment]
HI @ekzhu ! Is this issue still open? Thanks!!
