### ISSUE TITLE
[Feature Request] allow list of messages as system_messages

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#2140]
Right now `ConversableAgent` only allows `str` type for `system_message` argument in constructor. We should support a list of messages as system messages that can contain multiple in context learning examples. This is useful especially for smaller open weight models. 

system_messages do not need to be system roles, they can have user or assistant role.

**Comment by wlhgtc** [comment]
This is also what I need. Do you have a development plan for this task recently?

**Comment by ekzhu** [comment]
We are organizing this into our roadmaps. https://github.com/microsoft/autogen/issues?q=is%3Aopen+is%3Aissue+label%3Aroadmap

Would you like to help with this one?

**Comment by jtoy** [comment]
I'm working on it now. Which models can I test this against that supports arrays of system messages?

**Comment by ekzhu** [comment]
@jtoy We can test it on GPT-4 first. But I believe most models with OpenAI compatible API can support list of system messages.

**Comment by marklysze** [comment]
Just note that some open source models/inference engines require alternating roles for messages, so some wouldn't support two or more system messages in a row.

**Comment by ekzhu** [comment]
> Just note that some open source models/inference engines require alternating roles for messages, so some wouldn't support two or more system messages in a row.

Right. We need to highlight that the system messages can have any roles.

**Comment by prithvi2226** [comment]
Hi! Is this issue still open?
