### ISSUE TITLE
[Documentation] create topic to cover multimodal features

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#2142]
Currently we don't have documentation for our multimodal features. We should address this by creating a multi-modal topic under https://microsoft.github.io/autogen/docs/topics

It should cover:
- image generation capability
- vision capability 
- multi-modal agent 
- web browsing agent (could be in its own topic on web surfing)

**Comment by BabakBar** [comment]
Looking forward to the web browsing agent documentation!
