### ISSUE TITLE
[Issue]: Silence GitHub Post Commit Messages

### ISSUE THREAD

**Issue by WaelKarkoub** [microsoft/autogen#2148]
### Describe the issue

Silence GitHub's `requested a deployment` messages every time a commit is pushed. It clutters the comments section, not sure if it adds value.

### Steps to reproduce

1. Create a PR
2. Push a commit

### Screenshots and logs

![image](https://github.com/microsoft/autogen/assets/26918142/0a6f0a39-0194-4768-b194-2c672d4fc26a)

**Comment by rickyloynd-microsoft** [comment]
Fixing this would save us all a lot of wasted time.

**Comment by afourney** [comment]
Anyone know how to fix this? We looked into this a while ago, and we could only find browser plugins that remove them from local view -- nothing that would work for everyone.

**Comment by randombet** [comment]
@afourney Do you know where is the "requested a deployment" messages generated? Is it in our repo settings or somewhere https://github.com/actions? 

I checked this PR https://github.com/microsoft/autogen/pull/2973 as an example
Looks like the message is generated for each job run with openai1 environment.
1. test with each python version in https://github.com/microsoft/autogen/blob/main/.github/workflows/openai.yml 
2. each job in https://github.com/microsoft/autogen/blob/main/.github/workflows/contrib-openai.yml

e.g.  
1. action for AgentBuilder step, https://github.com/microsoft/autogen/actions/runs/9585740506/job/26432302886
2. action for test (ubuntu-latest, 3.11) https://github.com/microsoft/autogen/actions/runs/9585740496/job/26432304196

cc @qingyun-wu

**Comment by jackgerrits** [comment]
Given that we no longer use deployments as the way to structure CI, this issue is no longer a concern.
