### ISSUE TITLE
Add a figure to notebook

### ISSUE THREAD

**Issue by sonichi** [microsoft/autogen#215]
The figure and the notebook can be found in
https://github.com/microsoft/FLAML/pull/1216/files

**Comment by Pratikdate** [comment]
Assigned me I will add

**Comment by Pratikdate** [comment]
Can explain more what actually does

**Comment by HarshitVashisht11** [comment]
Hi i will like to fix the issue , can you assign this to me

**Comment by sonichi** [comment]
The figure is not in the notebook in the autogen repo.

**Comment by HarshitVashisht11** [comment]
Pls assign this issue to me i can fix this issue

**Comment by HarshitVashisht11** [comment]
Also can you send the image because its not loading properly
