### ISSUE TITLE
[Issue]: cannot import name 'transform_messages' from 'autogen.agentchat.contrib.capabilities' in autogen 0.2.21

### ISSUE THREAD

**Issue by abhinandanshahdev** [microsoft/autogen#2194]
### Describe the issue

Cant find the package in latest version of autogen, and it says chatmessagehistory is deprecated. 

```
(venv) incubatorone@xxx-MacBook-Pro AutoGen % pip show pyautogen
Name: pyautogen
Version: 0.2.21
Summary: Enabling Next-Gen LLM Applications via Multi-Agent Conversation Framework
Home-page: https://github.com/microsoft/autogen
Author: AutoGen
Author-email: auto-gen@outlook.com
License: UNKNOWN
Location: /Users/incubatorone/Documents/AutoGen/venv/lib/python3.11/site-packages
Requires: diskcache, docker, flaml, numpy, openai, pydantic, python-dotenv, termcolor, tiktoken
```

<img width="286" alt="Screenshot 2024-03-28 at 9 31 37 PM" src="https://github.com/microsoft/autogen/assets/46406497/7dd1fe42-32eb-4631-9ab4-77cd06ed77e7">

### Steps to reproduce

```

python -m venv venv
source venv/bin/activate
pip install pyautogen

```

create a main.py:

import autogen
from autogen.agentchat.contrib.capabilities import transform_messages, transforms

```
python main.py
```

**Comment by jackgerrits** [comment]
`transform_messages` was just [merged](https://github.com/microsoft/autogen/pull/1923) and has not been released yet.

**Comment by abhinandanshahdev** [comment]
Thanks I'm getting token counting errors using the older functionality

**Comment by DLWCMD** [comment]
Thanks. Do you have a release date?
