### ISSUE TITLE
[Issue]: LMstudio setting not working

### ISSUE THREAD

**Issue by nothingness6** [microsoft/autogen#2202]
### Describe the issue

I've been trying to connect LMstudio for Autogen Studio, but it doesn't work at all. 
![autogen](https://github.com/microsoft/autogen/assets/105210258/96bc5fc0-51a9-4bb3-afdd-f6c6c596e426)
It shows me the following error message and I have no clue what it is and why it happens:
Error occurred while testing model: 'NoneType' object is not subscriptable

### Steps to reproduce

1. Changed the local host address to http://localhost:1234/v1, but no luck.
2. Changed the local host address to http://localhost:1234, but no luck.

### Screenshots and logs

![autogen](https://github.com/microsoft/autogen/assets/105210258/b3bff671-ea17-4866-ae6c-9a06491ea23f)
```
Traceback (most recent call last):
  File "C:\Users\MonoD\miniconda3\envs\ag\Lib\site-packages\autogenstudio\web\app.py", line 479, in test_user_models
    response = test_model(model=req.model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MonoD\miniconda3\envs\ag\Lib\site-packages\autogenstudio\utils\utils.py", line 461, in test_model
    return response.choices[0].message.content
           ~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable

[32mINFO[0m:     127.0.0.1:53055 - "[1mPOST /api/models/test HTTP/1.1[0m" [32m200 OK[0m
Traceback (most recent call last):
  File "C:\Users\MonoD\miniconda3\envs\ag\Lib\site-packages\autogenstudio\web\app.py", line 479, in test_user_models
    response = test_model(model=req.model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MonoD\miniconda3\envs\ag\Lib\site-packages\autogenstudio\utils\utils.py", line 461, in test_model
    return response.choices[0].message.content
           ~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable

[32mINFO[0m:     127.0.0.1:53062 - "[1mPOST /api/models/test HTTP/1.1[0m" [32m200 OK[0m
```

### Additional Information

AutoGen Version: Latest
Operating System: Windows 10 64 bit
Python Version: 3.11

**Comment by jackgerrits** [comment]
The endpoint should just be `http://localhost:1234/v1`

**Comment by nothingness6** [comment]
> The endpoint should just be `http://localhost:1234/v1`

If you read my post carefully, you can find that I already tried it.

**Comment by ekzhu** [comment]
There is probably an error somewhere cause the response object to have a None choices. Have you checked lm studio log

**Comment by nothingness6** [comment]
> There is probably an error somewhere cause the response object to have a None choices. Have you checked lm studio log

I don't know why, but it works today somehow.
