### ISSUE TITLE
'ExtendedConversableAgent' object is not iterable

### ISSUE THREAD

**Issue by Louis2602** [microsoft/autogen#2217]
### Describe the issue

I was testing the backend of autogenstudio, running using a websocket server. I make a request from my frontend and got this kind of error. The 'ExtendedConversableAgent' is exactly the same as the one defined in autogenstudio. Like this:
```python
class ExtendedConversableAgent(autogen.ConversableAgent):
    def __init__(self, message_processor=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.message_processor = message_processor

    def receive(
        self,
        message: Union[Dict, str],
        sender: autogen.Agent,
        request_reply: Optional[bool] = None,
        silent: Optional[bool] = False,
    ):
        if self.message_processor:
            self.message_processor(
                sender, self, message, request_reply, silent, sender_type="agent"
            )
        super().receive(message, sender, request_reply, silent)
```
The websocket server running with FastAPI works fine.
Anyone has any idea to fix this issue. Thanks a lot, I really appreciate for your helps.

### Screenshots and logs

![image](https://github.com/microsoft/autogen/assets/62226612/b8a1d7c4-68e4-4707-8ea2-7069c1b398cb)

### Additional Information

AutoGen Version: latest: 0.2.21
Python Version: 3.11.4

**Comment by jackgerrits** [comment]
What was the issue in the end? Just in case someone else comes across this it would be great to know how you fixed it

**Comment by Louis2602** [comment]
It turned out that it was just a mistyping here. I initiate the chat with a group chat manger, but the extended group chat manager class is inherited from a conversable agent, not from the group chat manager agent. I changed it and it works just fine.
