### ISSUE TITLE
Remove "Optional" in GroupChat type hints

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#2221]
If None case is not handled then the type hint should not have Optional. 

Same with several other parameters in the class. We can have a separate PR to fix those parameters cc @joshkyh @marklysze 

_Originally posted by @ekzhu in https://github.com/microsoft/autogen/pull/2199#discussion_r1545582314_

**Comment by ruiwang** [comment]
I am happy to work on it if you could assign to me. @ekzhu :)
