### ISSUE TITLE
[Bug]: autogen.agentchat.register_function adds to all Agents instead of single

### ISSUE THREAD

**Issue by WebsheetPlugin** [microsoft/autogen#2239]
### Describe the bug

autogen.agentchat.register_function( X

There is an critical issue as above functions seems to add tools to all Agents, where I would expect it to add only to specified agent. See in logs: "WRONG WRITER tools:..."

### Steps to reproduce

```python
from autogen import AssistantAgent, UserProxyAgent, ConversableAgent, config_list_from_json
import autogen
from pprint import pprint

config_list = config_list_from_json(env_or_file="OAI_CONFIG_LIST")
gpt4_config = {
    "cache_seed": 42,  # change the cache_seed for different trials
    "temperature": 0,
    "config_list": config_list,
    "timeout": 120,
}

picker = autogen.AssistantAgent(
    name="PICKER",
    system_message="""PICKER. Suggest the most fitting workflow to fullfil the user task.""",
    llm_config=gpt4_config,
)

writer = autogen.AssistantAgent(
    name="WRITER",
    system_message="""You are a an text writer
""",
    llm_config=gpt4_config,
)

def hello_world():
    return "Hello, World!"

autogen.agentchat.register_function(
    hello_world,
    caller=picker,
    executor=picker,
    name="hello_world",
    description="run a shell script and return the execution result.",
)

print("PICKER tools:")
pprint(picker.llm_config["tools"]) # Correct

print("")
print("WRONG WRITER tools:") 
pprint(writer.llm_config["tools"]) # Wrongly Added the hello_world function to the writer tools

```

### Expected Behavior

Add only to picker agent

### Screenshots and logs

The return type of the function 'hello_world' is not annotated. Although annotating it is optional, the function should return either a string, a subclass of 'pydantic.BaseModel'.
PICKER tools:
[{'function': {'description': 'run a shell script and return the execution '
                              'result.',
               'name': 'hello_world',
               'parameters': {'properties': {},
                              'required': [],
                              'type': 'object'}},
  'type': 'function'}]

WRONG WRITER tools:
[{'function': {'description': 'run a shell script and return the execution '
                              'result.',
               'name': 'hello_world',
               'parameters': {'properties': {},
                              'required': [],
                              'type': 'object'}},
  'type': 'function'}]

**Comment by WebsheetPlugin** [comment]
Ok, it seems I found the reason for this behavior, but I don't think this is intended. The issue is that **gpt4_config** dictionary is used and updated across all agents, meaning that whatever I change inside in one agent, like adding a function. Will be also added to the other agent with the same config dictionary.

 I think for most users this behavior will be not clear.. To fix or as proof, I created a **gpt4_config_2**, and all started to work as expected..

**Here fixed code** 

from autogen import AssistantAgent, UserProxyAgent, ConversableAgent, config_list_from_json, function_utils
import autogen
from pprint import pprint

config_list = config_list_from_json(env_or_file="OAI_CONFIG_LIST")
gpt4_config = {
    "cache_seed": 42,  # change the cache_seed for different trials
    "temperature": 0,
    "config_list": config_list,
    "timeout": 120,
}
gpt4_config_2 = {
    "cache_seed": 42,  # change the cache_seed for different trials
    "temperature": 0,
    "config_list": config_list,
    "timeout": 120,
}
picker = autogen.AssistantAgent(
    name="PICKER",
    system_message="""PICKER. Suggest the most fitting workflow to fullfil the user task.""",
    llm_config=gpt4_config,
)

writer = autogen.AssistantAgent(
    name="WRITER",
    system_message="""You are a an text writer
""",
    llm_config=gpt4_config_2,
)

def hello_world():
    return "Hello, World!"

test = function_utils.get_function_schema(hello_world, name= "my text", description= "my description")
print(test)

autogen.agentchat.conversable_agent.register_function(
    hello_world,
    caller=picker,
    executor=picker,
    name="hello_world",
    description="run a shell script and return the execution result.",
)

# writer.register_for_llm(hello_world, name="hello_world", description="run a shell script and return the execution result.")

print("PICKER tools:")
pprint(picker.llm_config["tools"]) # Correct

print("")
print("WRONG WRITER tools:") 
pprint(writer.llm_config["tools"]) # Wrongly Added the hello_world function to the writer tools

**Comment by ekzhu** [comment]
You might have seen some incorrect examples that use a shared llm_config across multiple agents. llm_config should not be shared -- it has caused a lot of issues.

I have created an issue: https://github.com/microsoft/autogen/issues/2251. Would you like to take a stab at this?

**Comment by WebsheetPlugin** [comment]
Yes, but overall it's not clear. I mean this is very confusing.

If this is by design, maybe there is a way to warn users during usage of groupchat that llm_config is shared between agents.  Like storing some Agent Id in config.

**Comment by ekzhu** [comment]
> If this is by design, maybe there is a way to warn users during usage of groupchat that llm_config is shared between agents. Like storing some Agent Id in config.

It is not by design. Agents should have their own llm_config even in a group chat. 

We are cleaning up the notebooks for incorrect usages to avoid misleading users.

Also perhaps doing a deep-copy of the llm_config in constructor may be a good idea.

**Comment by jackgerrits** [comment]
> Also perhaps doing a deep-copy of the llm_config in constructor may be a good idea.

Agree completely. Opened a PR with this fix

**Comment by CalvinHMX** [comment]
> > If this is by design, maybe there is a way to warn users during usage of groupchat that llm_config is shared between agents. Like storing some Agent Id in config.
> 
> Agents should have their own llm_config even in a group chat.
> 
> We are cleaning up the notebooks for incorrect usages to avoid misleading users.
> 
> Also perhaps doing a deep-copy of the llm_config in constructor may be a good idea.


Hello, I want to ask why the following autogen will consider letting all agent sharing tool configuration？
