### ISSUE TITLE
[Documentation] Creating a new category for "GroupChat"

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#2243]
GroupChat has become quite popular but also very complex. It would be good to have a new category under `/website/docs/topics/`. 

What can go in there:

1. Setting custom speaker selection message and prompts @marklysze 
2. Setting custom role for select speaker messages @marklysze 
3. Setting custom select speaker method @kevin666aa 
4. Stateflow @kevin666aa

**Comment by marklysze** [comment]
I'll start thinking about this...

**Comment by Codeshark-NET** [comment]
This is something I'm struggling with at the moment, for sure. In terms of what to cover, writing out my current total confusion as inspiration for the docs (no need to answer them here):

1. Tips for letting the GroupChatManager control my agents in the way that I'd like (speaker selection? multiple types)
2. Methods of controlling who's allowed to speak (and when they're done)
3. How do I control the final output of the conversation between the agents? Do I need a summarizer agent, or will the GroupChatManager take care of it, somehow? (i.e. summarizing final conversation, or specific output, in specific format)

Braindump from an autogen newbie here, hope it helps. 😊 (& thanks for all your work!)

**Comment by marklysze** [comment]
@Codeshark-NET, thanks for your list - it's actually really useful - understanding what everyone is needing is going to help us all. It is a biggish topic and there is a lot of flexibility around it, so thoughtful documentation makes sense.

I'm working to finish up another PR on speaker selection in Group Chat and then I'll put my focus on this.

If there's anything else or any more suggested topics feel free to list them (anyone).

**Comment by Codeshark-NET** [comment]
Hey again @marklysze!

I've ended up going a different route (with a prompt chain approach); but I wanted to share a few additional notes with you regardless, on the chance it might be helpful. Again, no need to answer them.

**Questions I had on my mind, unable to clarify:**

- When should one use a sequential chat vs a group chat (more examples)
- What are easier ways to make a group chat act sequentially? (speaker selection)
- What are some use cases that make the best use of a group chat?
- When **should you not** use Autogen, perhaps vs promt chaining techniques. When is it overkill?
- How does the group chat manager work in terms of the output, and how does its job (so prompts can be uptimized for it)
- Deployment strategies for taking it to production
- Techniques/tips on managing prompts & token usage across all agents in Autogen

Happy to clarify on a call sometime as well if that's more helpful. Product management wise. Thanks again! 🚀

**Comment by marklysze** [comment]
Hi @Codeshark-NET, thanks for putting those through and appreciate you doing that having gone down a different route. I think they're great questions that people (including myself) ask.

I'm hoping to get time to get onto this PR, my work on speaker selection is taking longer than I thought.

Appreciated and good luck with the prompt chain approach!
