### ISSUE TITLE
[Feature Request]: MessageTransform when token limit is exceeded.

### ISSUE THREAD

**Issue by giorgossideris** [microsoft/autogen#2306]
### Is your feature request related to a problem? Please describe.

You can either execute a transformation from the beginning of a conversation or not at all. I think it would be useful to execute a transformation (transformations at this moment refer to content reduction), when the token limit is (or is close to be) exceeded.

### Describe the solution you'd like

Give the option to call transformations when the token limit is (or is close to) exceeded.

### Additional context

Let me know if you want me to open a PR.

**Comment by WaelKarkoub** [comment]
You should be able to create a custom transformation to get the specific behavior.

```python
from autogen.agentchat.contrib.capabilities import transform_messages, transforms
from typing import Dict, List

class CustromTruncation:
    def __init__(self, ...):
        self._token_limiter = transform.MessageTokenLimiter(...)
    ...

    def apply_transform(self, messages: List[Dict]) -> List[Dict]:
        if close_to_limit():
            self._token_limiter.apply_transform(messages)
        else:
            return messages
```

**Comment by giorgossideris** [comment]
> You should be able to create a custom transformation to get the specific behavior.
> 
> ```python
> from autogen.agentchat.contrib.capabilities import transform_messages, transforms
> from typing import Dict, List
> 
> class CustomTruncation:
>     def __init__(self, ...):
>         self._token_limiter = transform.MessageTokenLimiter(...)
>     ...
> 
>     def apply_transform(self, messages: List[Dict]) -> List[Dict]:
>         if close_to_limit():
>             self._token_limiter.apply_transform(messages)
>         else:
>             return messages
> ```

Sure, I just think it should be easier than that.

**Comment by WaelKarkoub** [comment]
I have two solutions in mind:
1. Add "min_token_threshold: Optional[int] = None" to the constructor: Would apply the transform if the threshold is exceeded. Simple to implement.
2. Add "min_token_threshold: Optional[Callable] = None" to the constructor: The callable returns a boolean to decide if transform should be applied. A lot more flexible, the user can dictate the behavior. Not sure if needed

**Comment by giorgossideris** [comment]
> I have two solutions in mind:
> 
> 1. Add "min_token_threshold: Optional[int] = None" to the constructor: Would apply the transform if the threshold is exceeded. Simple to implement.

I don't like it very much, because the user would have to find the token limit, or call the corresponding function, which could be abstracted.

> 2. Add "min_token_threshold: Optional[Callable] = None" to the constructor: The callable returns a boolean to decide if transform should be applied. A lot more flexible, the user can dictate the behavior. Not sure if needed

I like this option very much, and this is an approach that could be extended further than the minimum token case. My additional thought is that probably it could by a `when_to_execute: Optional[Union[Callable, str]] = None` argument, that could also offer some pre-implemented cases (like the token threshold). This way the users don't have to reimplement some standard functions.

**Comment by giorgossideris** [comment]
> Sounds good, I have a couple of PRs open, and once I merge those in I'll add it to the list (more than happy if you want to take over this PR)

I would love to open this PR!
