### ISSUE TITLE
[Feature Request]: Make the cost info easier to read

### ISSUE THREAD

**Issue by sonichi** [microsoft/autogen#2336]
### Is your feature request related to a problem? Please describe.

The `chat_result.cost` is a tuple which users can't tell immediately what the two elements mean. For example,
```python
({'gpt-3.5-turbo-0125': {'completion_tokens': 328,
                         'cost': 0.0015555,
                         'prompt_tokens': 2127,
                         'total_tokens': 2455},
  'total_cost': 0.0015555},
 {'gpt-3.5-turbo-0125': {'completion_tokens': 328,
                         'cost': 0.0015555,
                         'prompt_tokens': 2127,
                         'total_tokens': 2455},
  'total_cost': 0.0015555})
```

### Describe the solution you'd like

It's better to make it easier to read. For example, using a dict.

### Additional context

`gather_usage_summary` in `autogen.agentchat.utils`

**Comment by kevin666aa** [comment]
Noted. I will address this.

**Comment by kevin666aa** [comment]
I think it is a bit confusing to name it "cost" here. Shall we change it to `usage`? 


Or maybe we can add more fields here:
`chat_result.cost` -> total cost
`chat_result.actual_cost` -> total actual cost with cache.
`chat_result.usage` -> all information about the usage, in the format of:
```python
{
"total_usage_summary": {'gpt-3.5-turbo-0125': {'completion_tokens': 328,
                         'cost': 0.0015555,
                         'prompt_tokens': 2127,
                         'total_tokens': 2455},
  'total_cost': 0.0015555},

"actual_usage_summary":  {'gpt-3.5-turbo-0125': {'completion_tokens': 328,
                         'cost': 0.0015555,
                         'prompt_tokens': 2127,
                         'total_tokens': 2455},
  'total_cost': 0.0015555}
}
```

What do you think? @sonichi @qingyun-wu @ekzhu @afourney

**Comment by Hk669** [comment]
can i work on this issue? @sonichi @kevin666aa
