### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by aullrich2013** [microsoft/autogen#2341]
### Describe the bug

When attempting to use the `transforms.MessageTokenLimiter(max_tokens=1000)` on a chatbot, 
I receive error `IndexError: list index out of range`

Because
` /home/ish/.venv/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py` line `1659` fails because `messages` is an empty list and not `None` as expected

### Steps to reproduce

create a chatbot agent with registered functions and attempt to add the MessageTokenLimiter `context_handling.add_to_agent(chatbot)`

**Comment by BeibinLi** [comment]
Thanks for this great feedback!

**Comment by BeibinLi** [comment]
@sonichi   I believe the error occurs at [here](https://github.com/microsoft/autogen/blob/adb8fd849cbc9987e6cf0fdeb611095c7b0ae2cf/autogen/agentchat/conversable_agent.py#L1659C9-L1659C17)

It is possible that the `messages` is an empty list, either from the line above when `sender is None` or the input messages is already an empty list. 

Would the following update resolve the issue?
```python
if len(messages):
    message = messages[-1]
else:
    message = "empty message"
```


Of courese, @WaelKarkoub , we need to update [this function](https://github.com/microsoft/autogen/blob/5a96dc2c2969a98f08d7fc4853b3419f61065609/autogen/agentchat/contrib/capabilities/transforms.py#L124) such that we should avoid returning an empty list. Maybe we can cut the message and get the first few tokens.

**Comment by WaelKarkoub** [comment]
@BeibinLi I opened a PR to fix this behavior. @aullrich2013 would you be able to test your setup with this PR https://github.com/microsoft/autogen/pull/2350?

**Comment by BeibinLi** [comment]
Note that [this line](https://github.com/microsoft/autogen/blob/adb8fd849cbc9987e6cf0fdeb611095c7b0ae2cf/autogen/agentchat/conversable_agent.py#L1657) and [this line](https://github.com/microsoft/autogen/blob/adb8fd849cbc9987e6cf0fdeb611095c7b0ae2cf/autogen/agentchat/conversable_agent.py#L1770) in the conversable agent still needs to be fixed.

@sonichi  Do you think my suggestion from yesterday makes sense?
