### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by asmagen** [microsoft/autogen#2344]
### Describe the issue

The Automated Task Solving with transition paths specified in a graph notebook (agentchat_graph_modelling_language_using_select_speaker.ipynb) is missing.
Here's the original [link](https://github.com/microsoft/autogen/blob/main/notebook/agentchat_graph_modelling_language_using_select_speaker.ipynb) from the [Examples](https://microsoft.github.io/autogen/docs/Examples/) page.

**Comment by ekzhu** [comment]
Yeah some notebooks have not been rendered as web pages. Do you want to submit a PR to add it? 

See: http://localhost:3000/autogen/docs/contributor-guide/documentation#how-to-get-a-notebook-rendered-on-the-website

**Comment by asmagen** [comment]
Can I get the code in any other way then?

**Comment by jackgerrits** [comment]
It seems like either the example was remove at some point or not added when the link was added to examples?
