### ISSUE TITLE
[Bug]: SyntaxError: expected ':'

### ISSUE THREAD

**Issue by sschet** [microsoft/autogen#2348]
### Describe the bug

When I run the below code:

```
@staticmethod
def set_global_default(stream: "IOStream") -> None
```

I get the following error:

```
Cell In[23], line 12
    def set_global_default(stream: "IOStream") -> None
                                                                                      ^
SyntaxError: expected ':'
```

The code was working fine on 4/4 but stopped working on 4/8

### Steps to reproduce

Run the code

### Expected Behavior

Should resolve the "No default IOStream" error.

### Additional Information

pyautogen==0.2.22

**Comment by ekzhu** [comment]
Can you check the code? The main branch's code currently looks like:

https://github.com/microsoft/autogen/blob/adb8fd849cbc9987e6cf0fdeb611095c7b0ae2cf/autogen/io/base.py#L51

And the last time this line was modified was 2 weeks ago.
