### ISSUE TITLE
[Feature Request]: JSON mode

### ISSUE THREAD

**Issue by tytung2020** [microsoft/autogen#2352]
### Is your feature request related to a problem? Please describe.

Agent currently does not output JSON object as instructed. Given now gpt-4-turbo supports JSON mode, it would be great to incorporate this into Autogen.

### Describe the solution you'd like

Add parameter response_format={ "type": "json_object" } in llm_config of an agent.

**Comment by jackgerrits** [comment]
I have been able to get json output to work using `"response_format":{ "type": "json_object" }` in the llm config as you described. Was it not working? Can you provide an example?

**Comment by tytung2020** [comment]
@jackgerrits In my case, the output is always the JSON structure being encapsulated within double quotes and escaped with backslashes (\) like this:
"{\n  \"name\": \"Alice\",\n  ....\n}"
so it will be interpreted as a single string value rather than a JSON object.

I have JSON mentioned in the prompt of the agent, and added "response_format":{ "type": "json_object" } in llm config.

**Comment by ekzhu** [comment]
You can use `json.loads`: https://docs.python.org/3/library/json.html

**Comment by Josephrp** [comment]
this is expected behavior , you'll have to escape and unescape json regularly when using text models
