### ISSUE TITLE
Typescript port of AutoGen

### ISSUE THREAD

**Issue by qingyun-wu** [microsoft/autogen#236]

**Comment by Axultan** [comment]
Looking forward to this!

**Comment by sonichi** [comment]
No one is working on this right now AFAIK.

**Comment by sonichi** [comment]
Found this effort: https://youtu.be/9Hrfx6kw1IE

**Comment by sonichi** [comment]
Also: https://github.com/xXAdonesXx/NodeGPT

**Comment by wladiston** [comment]
Thanks for sharing the video @sonichi!

Made few design choices different from autogen but the overall idea remains the same 
https://github.com/wladiston/aibitat

Great work btw

**Comment by sudhir-b** [comment]
Have done a similar thing to @wladiston, but hopefully more API friendly than the CLI approach: 

https://github.com/Engine-Labs/engine-agents

(there's a way to go to feature parity though! things seem to be moving with impressive speed)

**Comment by vzakharov** [comment]
Started working on the port today, currently not in a separate repo but under a ["playground"-like project](https://github.com/vzakharov/playground/tree/autogen/lib/autogen). Will separate out into a package once I have something working. Will keep you all posted.

**Comment by sonichi** [comment]
@vzakharov @sudhir-b @wladiston @Axultan could you review https://github.com/microsoft/autogen/pull/664 ? I'm not familiar w/ TS/JS.

**Comment by JUNIORCO** [comment]
good news - we've built a project inspired by AutoGen for TypeScript! our goal is to end up having parity with AutoGen while also focusing on developer experience and production-level agents. would love everybody's feedback from this thread 🙏

[Montelo Crews Source Code](https://github.com/montelo-org/montelo/tree/main/apps/crews)
[Montelo Crews Docs](https://docs.montelo.ai/crews/introduction)

**Comment by arielweinberger** [comment]
@JUNIORCO I find it not-so-cool to plug in your 30 days old repo here that immediately links to a cloud platform with paid pricing plans. This isn't the Autogen alternative we need in the JavaScript/TypeScript ecosystem.

**Comment by CallMeLaNN** [comment]
I thought if AutoGen can run in command in shell or docker, it can run NodeJS or any code if the environment configured properly.

So can I just make a skill/tool or executor that can run any command like `node code.js` and the agent will be able to run it?

**Comment by rysweet** [comment]
It is unlikely we will create a typescript port of 0.2, however we have roadmap item to bring autogen to typescript for the 0.4 arch

**Comment by oreshytko** [comment]
@rysweet can you tell the status of this? Are there any plans of having a typescript version of autogen in the observable future?

**Comment by itpropro** [comment]
@rysweet any updates on this? Neither auto-gen nor semantic kernel are available as TypeScript SDKs (which is a Microsoft first party language), which is really odd, considering JS/TS is not on a MS product, but also the most used programming language in the world.

**Comment by rysweet** [comment]
Please see the open PR. We will welcome any comments or feedback or attempts to use it. Since I am not a typescript expert, there may be things that folks who use type group every day would want to see or think should be different and we would like to find those things
