### ISSUE TITLE
[Feature Request]:  Support More core language and make extension

### ISSUE THREAD

**Issue by zjjott** [microsoft/autogen#2379]
### Is your feature request related to a problem? Please describe.

I found there is hard code to support core language executor 
https://github.com/microsoft/autogen/blob/main/autogen/coding/local_commandline_code_executor.py#L31

```
SUPPORTED_LANGUAGES: ClassVar[List[str]] = ["bash", "shell", "sh", "pwsh", "powershell", "ps1", "python"]
```

and here about select code executor:
 https://github.com/microsoft/autogen/blob/main/autogen/code_utils.py#L247-L258
```python
def _cmd(lang: str) -> str:
    if lang in PYTHON_VARIANTS:
        return "python"
    if lang.startswith("python") or lang in ["bash", "sh"]:
        return lang
    if lang in ["shell"]:
        return "sh"
    if lang in ["ps1", "pwsh", "powershell"]:
        powershell_command = get_powershell_command()
        return powershell_command

    raise NotImplementedError(f"{lang} not recognized in code execution")
```
there is hard to inheritance and overloading it,which user hard to make extenstion

### Describe the solution you'd like

can I make a PR, support that:
1. decoupling code write and execute,so that we can let autogen only write code but not execute it, such as write html/css/js file
2. reconstitution _cmd function, let user inheritance and overloading it,so we can support more code lang

**Comment by sonichi** [comment]
Thanks. 1 is already the case: The code writing and execution are decoupled. 2 is a good idea I think. 2 is probably unnecessary given that we already support custom code executor. cc @ekzhu @jackgerrits

**Comment by asandez1** [comment]
For example in my case I try this prompt for docker executor:

chat_result = code_executor_agent_using_docker.initiate_chat(
    code_writer_agent,
     message="Write a game with html and javascript, save the file and launch a website in the port 8080 to play the html game ",
)

The code writer answer correctly but the executor fail:

code_writer_agent (to code_executor_agent_docker):

```html
# filename: index.html
<!DOCTYPE html>
<html>
<head>
    <title>Simple Game</title>
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }
        #game-container {
            width: 300px;
            height: 300px;
            border: 1px solid black;
            display: flex;
            justify-content: center;
            align-items: center;
            font-size: 24px;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <div id="game-container" onclick="handleClick()">Click Me!</div>

    <script>
        let score = 0;

        function handleClick() {
            score++;
            document.getElementById('game-container').innerText = `Score: ${score}`;
        }
    </script>
</body>
</html>
```

```python
# filename: server.py
import http.server
import socketserver

PORT = 8080

Handler = http.server.SimpleHTTPRequestHandler

with socketserver.TCPServer(("", PORT), Handler) as httpd:
    print("Server started at localhost:" + str(PORT))
    httpd.serve_forever()
```

```sh
python server.py
```
After running the above code, open a web browser and go to http://localhost:8080 to play the simple game. Once done, please let me know.


Error:

 raise NotImplementedError(f"{lang} not recognized in code execution")
NotImplementedError: html not recognized in code execution

**Comment by sonichi** [comment]
@asandez1 could you review https://github.com/microsoft/autogen/pull/2303 ?
