### ISSUE TITLE
[Bug]: Reflection_with_llm producing odd/wrong results

### ISSUE THREAD

**Issue by ptkasper** [microsoft/autogen#2407]
### Describe the bug

In the  [agentchat_function_call_currency_calculator.ipynb](https://github.com/microsoft/autogen/blob/main/notebook/agentchat_function_call_currency_calculator.ipynb) notebook, executing the cell with the following code, print("Chat summary:", res.summary), produces a result that is not correct. 

Issue with method or with the use of 'cached' results..? (see cells above). Ps. the notebook contains several printouts of res.summary - this is the one after the message="How much is 112.23 Euros in US Dollars?" and related chat.

### Steps to reproduce

1. Open the notebook in Colab
2. Configure LLM to use GPT-4
3. Run all cells above the cell containing "print("Chat summary:", res.summary)"
4. ERROR: The printed text is "Chat summary: 120.23 Euros is approximately 123.45 US Dollars." even though the chat with currency calculator function call actually produces a result that the 'chatbot' gives to user_proxy: "chatbot (to user_proxy):

112.23 Euros is approximately 123.45 US Dollars."

### Model Used

gpt-4

### Expected Behavior

The print of res.summary should have been "112.23 Euros is approximately 123.45 US Dollars" or something along those lines having the correct value of 112.23 Euros rather than incorrect value of 120.23 Euros.

### Screenshots and logs

![Screenshot 2024-04-17 101004](https://github.com/microsoft/autogen/assets/49829190/ef524925-fabf-4190-892f-c1787172b054)

### Additional Information

Python 3 Google Compute Engine backend

**Comment by sonichi** [comment]
Could you try adding `"cache_seed" : None` into the `llm_config` and run it one more time? I suspect it's a one-time error.

**Comment by ptkasper** [comment]
You were correct. Setting cache_seed: None seems to have fixed it. Thanks! Case closed.
![Screenshot 2024-04-19 092225](https://github.com/microsoft/autogen/assets/49829190/e234d619-ea1c-4f7f-8696-0c5dbb2163b0)

**Comment by ekzhu** [comment]
@sonichi @ptkasper let's make cache_seed None by default: https://github.com/microsoft/autogen/issues/2133
