### ISSUE TITLE
Send/Receive messages for use cases with human_input_mode = ALWAYS

### ISSUE THREAD

**Issue by bamboriz** [microsoft/autogen#241]
Am not able to find anything around use cases where you want a user to always respond. Picture a case where the assistant is asking questions and the user_proxy answers. How do you make this work with a Frontend? 

The pop-up in console mode doesn't work in such a case

**Comment by sonichi** [comment]
you can override [`get_human_input`](https://microsoft.github.io/autogen/docs/reference/agentchat/conversable_agent#get_human_input) to make it work with your frontend.
