### ISSUE TITLE
[Feature Request]: Add support for Ollama

### ISSUE THREAD

**Issue by samimejri** [microsoft/autogen#2419]
### Is your feature request related to a problem? Please describe.

I used Autogen dotnet with LMStudio local llm and it is very very slow, Ollama is faster, is it possible to add support to Ollama please?

### Describe the solution you'd like

Have OllamaAgent and OllamaAgentConfig to use (similar to LMStudioAgent and LMStudioConfig)

**Comment by LittleLittleCloud** [comment]
@samimejri This issue has already been tracked by https://github.com/microsoft/autogen/issues/2319

**Comment by samimejri** [comment]
yes, go ahead!
