### ISSUE TITLE
[Feature Request]: add gemini safety settings and generation config

### ISSUE THREAD

**Issue by NikolayTV** [microsoft/autogen#2428]
### Is your feature request related to a problem? Please describe.

1 - Cannot control behavior of Gemini with generation params like top_p, top_k etc. 
2 - Default safety setting blocks too often, I want to rise threshold to BLOCK_ONLY_HIGH

### Describe the solution you'd like

I want to specify those params in llm_config when creating an agent

**Comment by pratham-darooka** [comment]
@NikolayTV @sonichi how can we add this issue to the roadmap [here](https://github.com/orgs/microsoft/projects/989/views/3)?
