### ISSUE TITLE
[Feature Request]: Optimise user proxy agent prompts when using allowed_or_disallowed_speaker_transitions

### ISSUE THREAD

**Issue by Nathan-Intergral** [microsoft/autogen#2456]
### Is your feature request related to a problem? Please describe.

I am working with a group chat with 11 agents that has to do very long form processes taking up to an even over 10 minutes to complete with gpt 4 turbo. A problem I am facing is the cost of the whole conversation reaches $10+ and i have been trying to optimise this. 

I have taken a look at the logs and i can see that the prompt for the user proxy agent to decide which assistant agent to use next is extremely long with my agent setup and their descriptions. I decided to implement the user of allowed_or_disallowed_speaker_transitions thinking it would reduce the size of these prompts as it would only include the agents that are allowed in the next step of the process. However, ive checked the logs after the change and the prompts are still including all the agents. 

### Describe the solution you'd like

Change the user proxy prompt to append only the agents listed as an allowed transition from the current agent to the next one.

For example:

say that the allowed transitions where set up as:

`allowed_transitions = {
        agent1: [agent2, agent3],
        agent2: [agent3],
        agent3: [agent4],
        agent4: [agent5],
        agent5: [agent1]
    }`

We init the chat and  agent 1 has just responded so the overseer prompts to determine the next agent.

instead of the prompt being this:

`You are in a role play game. The following roles are available:\nagent1:agent1 description, agent2: agent 2 description, agent3: agent 3 description, agent4: agent 4 description, agent5: agent 5 description\n\nRead the following conversation.\nThen select the next role from ['agent1','agent2','agent3','agent4','agent5',] to play. Only return the role.',`

it should instead be the following as only agent 2 and 3 are allowed transitions:

`You are in a role play game. The following roles are available:\nagent2: agent 2 description, agent3: agent 3 description,\n\nRead the following conversation.\nThen select the next role from ['agent2','agent3',] to play. Only return the role.',`

### Additional context

please let me know if you need more info or if there are solutions to this im not aware of.

**Comment by ekzhu** [comment]
Thanks @Nathan-Intergral. Instead of user proxy prompt I assume you meant GroupChat's speaker selection message and speaker selection prompts? 

To reduce cost, you can try to truncate the messages processed by each agent using message history transformation: https://microsoft.github.io/autogen/docs/topics/long_contexts.

**Comment by sonichi** [comment]
Thanks for the suggestion. If you would like to make a PR, please add @joshkyh @freedeaths as reviewers.

**Comment by Nathan-Intergral** [comment]
> Thanks @Nathan-Intergral. Instead of user proxy prompt I assume you meant GroupChat's speaker selection message and speaker selection prompts?
> 
> To reduce cost, you can try to truncate the messages processed by each agent using message history transformation: https://microsoft.github.io/autogen/docs/topics/long_contexts.
> 
> @marklysze has worked extensively on the group chat's prompts. @afourney and @jtrugman has lots of experience with long-context group chat.

Thanks for the suggestion, ill definitely give that a try and see what i find.

**Comment by Nathan-Intergral** [comment]
> Thanks for the suggestion. If you would like to make a PR, please add @joshkyh @freedeaths as reviewers.

@sonichi Thanks, ill look at making that PR today.

**Comment by ekzhu** [comment]
> @sonichi I have taken a look at the documentation for transforming, however TransformMessages and transforms dont seem to be present in the current released version? I see some notes in the version history that this was migrated from compressible agent, however all i can currently access is that compressible agent code.

TransformMessages is replaced by more general `transform` module: https://microsoft.github.io/autogen/docs/topics/long_contexts/ cc @WaelKarkoub

**Comment by WaelKarkoub** [comment]
> @sonichi I have taken a look at the documentation for transforming, however TransformMessages and transforms dont seem to be present in the current released version? I see some notes in the version history that this was migrated from compressible agent, however all i can currently access is that compressible agent code.

Which version of AutoGen do you have installed?

**Comment by WaelKarkoub** [comment]
@Nathan-Intergral you should be able to use the transforms, you can follow this notebook https://microsoft.github.io/autogen/docs/notebooks/agentchat_transform_messages/ for guidance as well. Just make sure you're using the correct Python environment that you have AutoGen installed in

**Comment by Nathan-Intergral** [comment]
> @Nathan-Intergral you should be able to use the transforms, you can follow this notebook https://microsoft.github.io/autogen/docs/notebooks/agentchat_transform_messages/ for guidance as well. Just make sure you're using the correct Python environment that you have AutoGen installed in

@WaelKarkoub You are correct, my version had not updated in my venv correctly.. Thank you!
