### ISSUE TITLE
How to update ChromaDB after documents in the 'docs' folder have been updated? 

### ISSUE THREAD

**Issue by xianzhisheng** [microsoft/autogen#248]
How to update ChromaDB after documents in the 'docs' folder have been updated? Currently, I clear the 'ChromaDB' folder and wait for it to re-index. Is there any other function or method for a direct update?

When I modify the document and rerun the code, it shows a message: 'Number of requested results 20 is greater than the number of elements in index 2, updating n_results = 2,' but, in reality, it doesn't use my latest version of 'docs

**Comment by qingyun-wu** [comment]
I believe @thinkall can help here.

**Comment by thinkall** [comment]
Hi @xianzhisheng , could you upgrade pyautogen to the latest version and set get_or_create to be True?
```
    retrieve_config={
        "task": "qa",
        "docs_path": corpus_file,
        "get_or_create ": True,
    },
```
