### ISSUE TITLE
[Bug]: Runtime logging not supported with GPTAssistantAgent

### ISSUE THREAD

**Issue by krishnashed** [microsoft/autogen#2498]
### Describe the bug

I followed the example mentioned in https://microsoft.github.io/autogen/docs/notebooks/agentchat_logging/
But when i replaced the AssistantAgent, with GPTAssistantAgent. The logs werent captured in the DB. No new entry added.

### Steps to reproduce

In the example https://microsoft.github.io/autogen/docs/notebooks/agentchat_logging/

just replace assistant with 

assistant = GPTAssistantAgent(
    name="assistant",
    llm_config=llm_config
)

and then try to get logs from sqlite, using steps given in same doc.

**Comment by krishnashed** [comment]
I can contribute to fix this issue, please let me know

**Comment by ekzhu** [comment]
Would loved to see your PR! Please add @IANTHEREAL @cheng-tan @jtrugman and me as reviewers

**Comment by IANTHEREAL** [comment]
@krishnashed Just checking in to see if your PR is still in progress. Thanks

**Comment by krishnashed** [comment]
Yes @IANTHEREAL raising it today
