### ISSUE TITLE
chromadb fails in codespaces because of old version of sqlite3

### ISSUE THREAD

**Issue by rickyloynd-microsoft** [microsoft/autogen#251]
Code examples that use chromadb (like retrieval) fail in codespaces. 

To reproduce:
- Create or start a codespace.
- Launch python in VS Code's terminal window
```
$ python
Python 3.10.12 (main, Jun  7 2023, 19:32:10) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

- Attempt to import chromadb
```
>>> import chromadb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vscode/.local/lib/python3.10/site-packages/chromadb/__init__.py", line 69, in <module>
    raise RuntimeError(
RuntimeError: Your system has an unsupported version of sqlite3. Chroma requires sqlite3 >= 3.35.0.
Please visit https://docs.trychroma.com/troubleshooting#sqlite to learn how to upgrade.
```

- Check the sqlite3 version
```
>>> import sqlite3
>>> sqlite3.sqlite_version
'3.34.1'
```

Note that sqlite3 is not a pip-installable package, so upgrading it to a more recent version is non-trivial.

@sonichi found that the same error occurs with python 3.11.

No error occurs after I use Conda to create a virtual environment on Windows or Linux, because the sqlite3 version is then 3.41.2 for all the python versions I've tried.

Since **test_retrieve_utils.py** doesn't hit this error in our automatic continuous integration tests, GitHub must somehow run pytest using a version of sqlite3 that satisfies chromadb.

**Comment by thinkall** [comment]
Does it mean we should guide users to create env with conda?

**Comment by sonichi** [comment]
It's not clear to me whether conda in codespace works. We know that codespace without conda doesn't work. Conda without codespace works.

**Comment by marcgreen-simspace** [comment]
fyi, following instructions from https://gist.github.com/defulmere/8b9695e415a44271061cc8e272f3c300 (which is linked to from official chroma docs for this SQLite issue: https://docs.trychroma.com/troubleshooting#sqlite), I ran these commands in the codespace and was able to get past this sqlite error in the agentchat_RetrieveChat notebook:

`pip install pysqlite3-binary` and
`mkdir ../../home/vscode/.local/lib/python3.10/site-packages/google/colab`

I believe adding that folder triggers chromadb to use pysqlite3 instead of the default.

**Comment by thinkall** [comment]
> fyi, following instructions from https://gist.github.com/defulmere/8b9695e415a44271061cc8e272f3c300 (which is linked to from official chroma docs for this SQLite issue: https://docs.trychroma.com/troubleshooting#sqlite), I ran these commands in the codespace and was able to get past this sqlite error in the agentchat_RetrieveChat notebook:
> 
> `pip install pysqlite3-binary` and `mkdir ../../home/vscode/.local/lib/python3.10/site-packages/google/colab`
> 
> I believe adding that folder triggers chromadb to use pysqlite3 instead of the default.

Worth adding to FAQ

**Comment by thinkall** [comment]
> fyi, following instructions from https://gist.github.com/defulmere/8b9695e415a44271061cc8e272f3c300 (which is linked to from official chroma docs for this SQLite issue: https://docs.trychroma.com/troubleshooting#sqlite), I ran these commands in the codespace and was able to get past this sqlite error in the agentchat_RetrieveChat notebook:
> 
> `pip install pysqlite3-binary` and `mkdir ../../home/vscode/.local/lib/python3.10/site-packages/google/colab`
> 
> I believe adding that folder triggers chromadb to use pysqlite3 instead of the default.

@marcgreen-simspace would you like to make a PR to add your findings to the FAQ doc https://github.com/microsoft/autogen/blob/main/website/docs/FAQ.md ?

**Comment by marcgreen** [comment]
Wonder how much trouble it would be to update the codespace build process to include this fix, so that users don't need to hit the error and find the FAQ workaround themselves.

**Comment by rickyloynd-microsoft** [comment]
> Wonder how much trouble it would be to update the codespace build process to include this fix, so that users don't need to hit the error and find the FAQ workaround themselves.

Yes, let's look into updating the codespace build process after merging your PR #405. Thanks for the fix @marcgreen!

**Comment by rickyloynd-microsoft** [comment]
I've studied the codespaces [setup process](https://docs.github.com/en/codespaces/getting-started/deep-dive), and found no easy way to modify it to perform the manual steps covered in PR #405. So for now the FAQ is a good place for the steps to be listed.

**Comment by tyler-suard-parker** [comment]
I followed the steps, created the folder in code spaces, I am still getting the error.
