### ISSUE TITLE
[Bug]: base_url seems not work on "http://localhost:1234/v1"

### ISSUE THREAD

**Issue by holisHsu** [microsoft/autogen#2514]
Thanks for any potential help in advance, and apologize if what I report is not a bug.

# Description
When I run example code as following with base_url point to my local LM Studio server,
ChatCompletion fail and it seems the request path is wrong

```
from autogen import AssistantAgent, UserProxyAgent


llm_config = {
    "model": "llama3-7B",
    "base_url": "http://localhost:1234/v1",
    "api_key": "lm_studio",
}
assistant = AssistantAgent("assistant", llm_config=llm_config)
user_proxy = UserProxyAgent("user_proxy", code_execution_config=False)

# Start the chat
user_proxy.initiate_chat(
    assistant,
    message="Tell me a joke about NVDA and TESLA stock prices.",
)
```

### Error
![CleanShot 2024-04-26 at 02 00 46@2x](https://github.com/microsoft/autogen/assets/52438637/d5697676-71ee-4827-a467-e0ceb91cb697)

### Screenshot for ChatCompletion
It should call `/v1/chat/completions` instead ?
![CleanShot 2024-04-26 at 01 56 33@2x](https://github.com/microsoft/autogen/assets/52438637/4feaccda-94a2-468d-9652-b2f086610b29)

### Steps to reproduce

1. Use LM Studio to run llama3-7B in local
2. Check following curl script work
```
curl http://localhost:1234/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{ 
    "model": "cognitivecomputations/dolphin-2.9-llama3-8b-gguf",
    "messages": [ 
      { "role": "system", "content": "Always answer in rhymes." },
      { "role": "user", "content": "Introduce yourself." }
    ], 
    "temperature": 0.7, 
    "max_tokens": -1,
    "stream": true
}'
```
3. Run the simple user proxy script and check the error
```
from autogen import AssistantAgent, UserProxyAgent


llm_config = {
    "model": "llama3-7B",
    "base_url": "http://localhost:1234/v1",
    "api_key": "lm_studio",
}
assistant = AssistantAgent("assistant", llm_config=llm_config)
user_proxy = UserProxyAgent("user_proxy", code_execution_config=False)

# Start the chat
user_proxy.initiate_chat(
    assistant,
    message="Tell me a joke about NVDA and TESLA stock prices.",
)
```

### Model Used

Llama3-7B

### Expected Behavior

ChatCompletion should get the result

### Screenshots and logs

Traceback log is provided as following, if any more information should be reveal please let me know, thanks you so much.

![CleanShot 2024-04-26 at 02 05 13@2x](https://github.com/microsoft/autogen/assets/52438637/7f289d2e-4064-4754-b361-dc35cf0606c8)

**Comment by ekzhu** [comment]
Can you check our base_url? I am not sure if you need `v1`

**Comment by riaanpieterse81** [comment]
Make sure your model is right, use the ID from `curl http://localhost:1234/v1/models`
Sample output
```
{
  "data": [
    {
      "id": "microsoft/Phi-3-mini-4k-instruct-gguf/Phi-3-mini-4k-instruct-q4.gguf",
      "object": "model",
      "owned_by": "organization-owner",
      "permission": [
        {}
      ]
    }
  ],
  "object": "list"
```

**Comment by riaanpieterse81** [comment]
Hi @holisHsu 
double check your model name, I'm not sure if the short name is OK, I normally use the full name in your case this would be `ognitivecomputations/dolphin-2.9-llama3-8b-gguf` 

Another way to get your models for llm studio is to ud the id value in 'curl http://localhost:1234/v1/models' output

 Last thing is the `ConversableAgent` will be better suited than the AssistantAgent in your use-case

**Comment by asandez1** [comment]
If you use LLM Studio, try your curl command:

# Load a model, start the server, and run this example in your terminal
# Choose between streaming and non-streaming mode by setting the "stream" field

curl http://localhost:1234/v1/chat/completions \
-H "Content-Type: application/json" \
-d '{ 
  "model": "model-identifier",
  "messages": [ 
    { "role": "system", "content": "Always answer in rhymes." },
    { "role": "user", "content": "Introduce yourself." }
  ], 
  "temperature": 0.7, 
  "max_tokens": -1,
  "stream": true
}'

**Comment by holisHsu** [comment]
> Hi @holisHsu double check your model name, I'm not sure if the short name is OK, I normally use the full name, I think your short model name would be `dolphin-2.9-llama3-8b`
> 
> Another way to get your models for llm studio is to use the id value in `curl http://localhost:1234/v1/models` output
> 
> Last thing is the `ConversableAgent` will be better suited than the AssistantAgent in your use-case
> 
> ** Sample **
> 
> ```
> from autogen import AssistantAgent, UserProxyAgent, ConversableAgent
> 
> 
> llm_config = {
>     "model": "microsoft/Phi-3-mini-4k-instruct-gguf/Phi-3-mini-4k-instruct-q4.gguf",
>     "base_url": "http://localhost:1234/v1",
>     "api_key": "lm_studio",
> }
> assistant = ConversableAgent("assistant", llm_config=llm_config)
> user_proxy = UserProxyAgent("user_proxy", code_execution_config=False)
> 
> # Start the chat
> user_proxy.initiate_chat(
>     assistant, 
>     message="Tell me a joke about NVDA and TESLA stock prices.",
> )
> ```

Thank you so much and the problem seems to be I using the wrong short name.
After I made your advice it work.

`I am considering if it's possible to provide more error detail information to indicate what the problem is.`

And I will close this issue because it's not a bug.

**Comment by holisHsu** [comment]
> If you use LLM Studio, try your curl command:
> 
> curl http://localhost:1234/v1/chat/completions -H "Content-Type: application/json" -d '{ "model": "model-identifier", "messages": [ { "role": "system", "content": "Always answer in rhymes." }, { "role": "user", "content": "Introduce yourself." } ], "temperature": 0.7, "max_tokens": -1, "stream": true }'

Thanks for your advice, I have tried this and check it's work as I have mentioned in "Steps to reproduce" 🙏 

It turns out I provide the wrong short model name and I am now considering is it possible to provide a detail error information to indicate the problem.
