### ISSUE TITLE
Qdrant Vectorstore Support

### ISSUE THREAD

**Issue by kdcokenny** [microsoft/autogen#253]
I created a working qdrant vector store example if anyone wants to clean the code up & submit a PR (if at all necessary). If not, this could just be a good starting point for those who are wanting to use Qdrant with autogen.

```python
# Creating qdrant client
from qdrant_client import QdrantClient

client = QdrantClient(url="***", api_key="***")

# Wrapping RetrieveUserProxyAgent
from litellm import embedding as test_embedding
from autogen.agentchat.contrib.retrieve_user_proxy_agent import RetrieveUserProxyAgent
from qdrant_client.models import SearchRequest, Filter, FieldCondition, MatchText

class QdrantRetrieveUserProxyAgent(RetrieveUserProxyAgent):
    def query_vector_db(
        self,
        query_texts: List[str],
        n_results: int = 10,
        search_string: str = "",
        **kwargs,
    ) -> Dict[str, Union[List[str], List[List[str]]]]:
        print(f"Inputs:\nquery_texts: {query_texts}\nn_results: {n_results}\nsearch_string: {search_string}\nkwargs: {kwargs}")
        # define your own query function here
        embed_response = test_embedding('text-embedding-ada-002', input=query_texts)

        all_embeddings: List[List[float]] = []

        for item in embed_response['data']:
            all_embeddings.append(item['embedding'])

        search_queries: List[SearchRequest] = []

        for embedding in all_embeddings:
            search_queries.append(
                SearchRequest(
                    vector=embedding,
                    filter=Filter(
                        must=[
                            FieldCondition(
                                key="page_content",
                                match=MatchText(
                                    text=search_string,
                                )
                            )
                        ]
                    ),
                    limit=n_results,
                    with_payload=True,
                )
            )

        search_response = client.search_batch(
            collection_name="{your collection name}",
            requests=search_queries,
        )

        return {
            "ids": [[scored_point.id for scored_point in batch] for batch in search_response],
            "documents": [[scored_point.payload.get('page_content', '') for scored_point in batch] for batch in search_response],
            "metadatas": [[scored_point.payload.get('metadata', {}) for scored_point in batch] for batch in search_response]
        }

    def retrieve_docs(self, problem: str, n_results: int = 20, search_string: str = "", **kwargs):
        results = self.query_vector_db(
            query_texts=[problem],
            n_results=n_results,
            search_string=search_string,
            **kwargs,
        )

        self._results = results


# Test QdrantRetrieveUserProxyAgent
testproxyagent = QdrantRetrieveUserProxyAgent(
    name="ragproxyagent",
    human_input_mode="NEVER",
    max_consecutive_auto_reply=2,
    retrieve_config={
        "task": "qa",
        "chunk_token_size": 2000,
        "client": "___",
        "embedding_model": "___",
    },
)

testproxyagent.retrieve_docs("What is Autogen?", n_results=10, search_string="autogen")
```

**Comment by thinkall** [comment]
Hi @kdcokenny , thank you very much. Very nice!

Any volunteers?

**Comment by olaoluwasalami** [comment]
Yes, I can take it @thinkall

**Comment by thinkall** [comment]
> Yes, you can assign it to me @thinkall

Thank you @olaoluwasalami . Assigned.

**Comment by Anush008** [comment]
Hey @olaoluwasalami, thanks for taking this up.
I'll be on standby if would need any help with this.

**Comment by olaoluwasalami** [comment]
Hello @Anush008, you can take the ticket if that's fine.

**Comment by Anush008** [comment]
Thanks. I am fine with you doing it as you asked for it first.

**Comment by olaoluwasalami** [comment]
Its fine, Ill assign this to you. @Anush008, If that's fine with @thinkall

**Comment by thinkall** [comment]
@Anush008 @olaoluwasalami Thank you both. @Anush008 I've assigned it to you. Let me know if you have any questions.

**Comment by Anush008** [comment]
👍👍

**Comment by Anush008** [comment]
Hey @thinkall, how would you like to see Qdrant integrated? Adding it as another retrieve mechanism in [retrieve_utils.py](https://github.com/microsoft/autogen/blob/main/autogen/retrieve_utils.py) or as done in https://github.com/microsoft/autogen/pull/161, extend `RetrieveUserProxyAgent` with Qdrant and add it to the tests?

**Comment by thinkall** [comment]
> Hey @thinkall, how would you like to see Qdrant integrated? Adding it as another retrieve mechanism in [retrieve_utils.py](https://github.com/microsoft/autogen/blob/main/autogen/retrieve_utils.py) or as done in #161, extend `RetrieveUserProxyAgent` with Qdrant and add it to the tests?
> 
> We can have `create_vector_db_from_dir()` and `create_vector_db_from_dir()` in [retrieve_utils.py](https://github.com/microsoft/autogen/blob/main/autogen/retrieve_utils.py) accept Qdrant-client instances too, with tests. It has built in support for generating embeddings using [qdrant/fastembed](https://github.com/qdrant/fastembed) and highly efficient search with filter.

Hi @Anush008 , I'd prefer add a new class `QdrantRetrieveUserProxyAgent`  to `autogen/agentchat/contrib/retrieve_user_proxy_agent.py`, so people can import and use it directly. Test code should go to tests. The import of `qdrant_client` should be in `try...except...`, I don't want to add `qdrant_client` to the dependencies, so we need to raise an error to ask users to install it manually.

**Comment by Anush008** [comment]
Thanks for clarifying. I'll start working on it.
