### ISSUE TITLE
[Issue]: AutoGen Studio devcontainer - frontend build requires rsync

### ISSUE THREAD

**Issue by kasiprasad** [microsoft/autogen#2534]
### Describe the issue

Can't build `samples/apps/autogenstudio/frontend` - missing `rsync`.

Followed the instructions in `samples/apps/autogenstudio` but frontend build seems to require `rsync` to complete successfully now.

From `package.json`
```
"build": "gatsby clean && rm -rf ../autogenstudio/web/ui && PREFIX_PATH_VALUE='' gatsby build --prefix-paths && rsync -a --delete public/ ../autogenstudio/web/ui/",
```

### Steps to reproduce

- Open the codebase in an IDE (i.e. VSCode) using any of the provided devcontainers
- Navigate to the `samples/apps/autogen-studio/frontend` directory, install dependencies, and build the UI:

      ```bash
      npm install -g gatsby-cli
      npm install --global yarn
      cd frontend
      yarn install
      yarn build
      ```

Build fails, rsync is not installed in the devcontainer.

```
/bin/sh: 1: rsync: not found
error Command failed with exit code 127.
```

### Screenshots and logs

<img width="751" alt="image" src="https://github.com/microsoft/autogen/assets/199063/82c67871-0877-4e32-8e54-3e9ead357318">

**Comment by kasiprasad** [comment]
not sure whether all of the `Dockerfile`'s or just `dev` and `full` should be updated to include `rsync` in the list of packages installed using `apt-get` but simply adding `rsync` to the list and rebuilding the devcontainer fixes the issue.

**Comment by victordibia** [comment]
Thanks for pointing this out @kasiprasad .
Adding rsync to the package requirements is a good starting point. 
It might be even better to figure out build commands that work ootb with most environments (rsync is only used to copy the built UI into the python package.)

**Comment by victordibia** [comment]
Closing for now. 
Devs building the source can run `yarn build` and then copy over the built files manually.  
Feel free to reopen with any ideas (or PRs) for improvement here.
