### ISSUE TITLE
[Feature Request][.Net]: Count token usage for `OpenAIClientAgent` 

### ISSUE THREAD

**Issue by LittleLittleCloud** [microsoft/autogen#2535]
### Is your feature request related to a problem? Please describe.

The token usage information is included in `ChatCompletions`, but `OpenAIClentAgent` returns `ChatCompletions.Choice[0]`, which prevents developers get token count information.

### Describe the solution you'd like

Return `ChatCompletions` in `OpenAIClientAgent` so the token count information can be retrieved in the similar way of the following example

https://microsoft.github.io/autogen-for-net/articles/MistralChatAgent-count-token-usage.html

**Comment by DavidLuong98** [comment]
I'll work on this
