### ISSUE TITLE
[Issue]: Warning from the def _num_token_from_messages is verbose and hard to silence

### ISSUE THREAD

**Issue by colaso96** [microsoft/autogen#2538]
### Describe the issue

Here is an example output: 
[I 2024-04-27 00:02:01,357.357 autogen.token_count_utils] gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.

However, this is very verbose and frustrating to see printed.  Can we either dynamically retrieve the number of tokens from the model count or toggle this output?  I can work around it but it seems like a fixable bit of code.

### Steps to reproduce
Initialize a compressible agent or series of compressible agents

### Screenshots and logs

Screenshots in comment

**Comment by colaso96** [comment]
<img width="1089" alt="Screenshot 2024-04-28 at 7 56 20 PM" src="https://github.com/microsoft/autogen/assets/50208048/d2545c26-cebf-4378-9248-013688528a1f">

**Comment by WaelKarkoub** [comment]
Hi @colaso96! We are deprecating compressible agents in favor of `TransformMessages` https://microsoft.github.io/autogen/docs/topics/long_contexts/. I'm implementing `llmlingua` as a new transform in https://github.com/microsoft/autogen/pull/2225 to compress text.
