### ISSUE TITLE
"USING AUTO REPLY... keep showing until it match max_consecutive_auto_reply settings

### ISSUE THREAD

**Issue by stonez56** [microsoft/autogen#254]
My Question:  I've successfully get the code generated by Autogen, but the ">>>Using AUTO REPLY..." just keep showing on the terminal 10 times. The last 8 times, just saying "thank you" stuff, not doing anything. Until the end, I have to type "exit" to stop the code exectution.  

My code:

```python
# use 'pip install pyautogen' instad of 'pip install autogen'!!
import autogen
import OPENAI_KEY

config_list = [
    {
        'model': 'gpt-3.5-turbo-16k-0613',
        'api_key': OPENAI_KEY.myKey
    }
]

llm_config={
    "request_timeout": 600,
    "seed": 42, #for catching to saving money
    "config_list": config_list,
    "temperature": 0
}

assistant = autogen.AssistantAgent(
    name="assistant",
    llm_config = llm_config,
    system_message = "Your loyal assistant!"
)

user_proxy = autogen.UserProxyAgent(
    name = "user_proxy",
    human_input_mode = "TERMINATE",
    max_consecutive_auto_reply = 10,
    is_termination_msg=lambda x: x.get("content", "").rstrip().endswith("TERMINATE"),
    code_execution_config={"work_dir": "D:\stone\Documents\python\ms-autogen\web"},
    llm_config=llm_config,
    system_message = """
    Reply TERMINATE if the task has been solved at full satisfaction. 
    Otherwise, reply CONTINUE, or the reason why the task is not solved yet."""
)

task = """
Write me a python code that add odd numbers from 1 to 1000 and print out the result. After that, save the Python code in a file.
"""

user_proxy.initiate_chat(
    assistant,
    message=task,
)
```

TERMINAL Output:

`Write me a python code that add odd numbers from 1 to 1000 and print out the result. After that, save the Python code in a file.

--------------------------------------------------------------------------------
assistant (to user_proxy):

Certainly! Here's the Python code that adds odd numbers from 1 to 1000 and prints out the result:

```python
# Initialize the sum variable
sum_of_odd_numbers = 0

# Iterate through numbers from 1 to 1000
for num in range(1, 1001):
    # Check if the number is odd
    if num % 2 != 0:
        # Add the odd number to the sum
        sum_of_odd_numbers += num

# Print the result
print("The sum of odd numbers from 1 to 1000 is:", sum_of_odd_numbers)

# Save the Python code in a file
with open("sum_of_odd_numbers.py", "w") as file:
    file.write('''\
# Initialize the sum variable
sum_of_odd_numbers = 0

# Iterate through numbers from 1 to 1000
for num in range(1, 1001):
    # Check if the number is odd
    if num % 2 != 0:
        # Add the odd number to the sum
        sum_of_odd_numbers += num

# Print the result
print("The sum of odd numbers from 1 to 1000 is:", sum_of_odd_numbers)
''')

print("Python code saved in 'sum_of_odd_numbers.py' file.")
```

This code will calculate the sum of odd numbers from 1 to 1000 and print the result. It will also save the Python code in a file named "sum_of_odd_numbers.py".

--------------------------------------------------------------------------------

>>>>>>>> USING AUTO REPLY...

>>>>>>>> EXECUTING CODE BLOCK 0 (inferred language is python)...
execute_code was called with use_docker evaluating to True, but the python docker package is not available. Falling back to native code execution. Note: this fallback behavior is subject to change
SIGALRM is not supported on Windows. No timeout will be enforced.
user_proxy (to assistant):

exitcode: 0 (execution succeeded)
Code output:
The sum of odd numbers from 1 to 1000 is: 250000
Python code saved in 'sum_of_odd_numbers.py' file.

--------------------------------------------------------------------------------
assistant (to user_proxy):

Great! The code executed successfully and the output shows that the sum of odd numbers from 1 to 1000 is 250000. The Python code has also been saved in the "sum_of_odd_numbers.py" file. If you have any more questions or need further assistance, feel free to ask!

--------------------------------------------------------------------------------

>>>>>>>> USING AUTO REPLY...
user_proxy (to assistant):

Great! I'm glad the code executed successfully and the output is as expected. If you have any more questions or need further assistance, feel free to ask. Otherwise, the task has been solved at full satisfaction.

--------------------------------------------------------------------------------
assistant (to user_proxy):

I'm glad to hear that the task has been solved to your satisfaction! If you have any more questions or need assistance in the future, don't hesitate to ask. Have a great day!

--------------------------------------------------------------------------------

>>>>>>>> USING AUTO REPLY...
user_proxy (to assistant):

Thank you! I'm glad I could help. If you have any more questions or need assistance in the future, feel free to reach out. Have a great day too!

--------------------------------------------------------------------------------
assistant (to user_proxy):

Thank you! I appreciate your help and support. I'll definitely reach out if I have any more questions or need assistance. Have a wonderful day ahead!

--------------------------------------------------------------------------------

>>>>>>>> USING AUTO REPLY...
user_proxy (to assistant):

You're welcome! I'm always here to help. Feel free to reach out anytime you need assistance. Have a wonderful day ahead as well!

--------------------------------------------------------------------------------
assistant (to user_proxy):

Thank you for your kind words! I appreciate your availability to assist. I'll definitely reach out whenever I need help. Have a fantastic day too!

--------------------------------------------------------------------------------

>>>>>>>> USING AUTO REPLY...
user_proxy (to assistant):

Thank you for your kind words! I'm always here to assist you whenever you need help. Have a fantastic day as well!

--------------------------------------------------------------------------------
assistant (to user_proxy):

Thank you once again! Your willingness to assist is greatly appreciated. I'll keep that in mind and reach out whenever I need help. Have a fantastic day too! 

--------------------------------------------------------------------------------

>>>>>>>> USING AUTO REPLY...
user_proxy (to assistant):

You're very welcome! I'm always here to assist you, so don't hesitate to reach out whenever you need help. Thank you for your kind words. Have a fantastic day too!

--------------------------------------------------------------------------------
assistant (to user_proxy):

Thank you for your continuous support! I truly appreciate your availability to assist. I'll definitely reach out whenever I need help. Have a fantastic day as well!

--------------------------------------------------------------------------------

>>>>>>>> USING AUTO REPLY...
user_proxy (to assistant):

Thank you for your kind words! I'm always here to support you, so please feel free to reach out whenever you need assistance. Have a fantastic day too!       

--------------------------------------------------------------------------------
assistant (to user_proxy):

Thank you for your kind words and support! I really appreciate it. I'll definitely reach out whenever I need assistance. Have a fantastic day as well!        

You're very welcome! I'm glad I could assist you. Thank you for your kind words. Remember, I'm always here to help, so feel free to reach out whenever you need assistance. Have a fantastic day too!

--------------------------------------------------------------------------------
assistant (to user_proxy):
Thank you for your kind words and support! I'm grateful for your assistance. I'll definitely reach out whenever I need help. Have a fantastic day as well!    

--------------------------------------------------------------------------------
Please give feedback to assistant. Press enter to skip and use auto-reply, or type 'exit' to stop the conversation: exit`

**Comment by thinkall** [comment]
Hi @stonez56 , try this:
```
assistant = autogen.AssistantAgent(
    name="assistant",
    llm_config = llm_config,
    # system_message = "Your loyal assistant!"  # remove this line
)
```

**Comment by stonez56** [comment]
@thinkall I just tried to remove the line and it worked. Thanks a lot!

**Comment by thinkall** [comment]
> @thinkall I just tried to remove the line and it worked. Thanks a lot!
> 
> However, If I input some text at "Please give feedback to assistant. Press enter or type 'exit' to stop the conversation prompt, the same repeating message will happen again.

I'm not sure what do you mean. If you mean you replaced system_message of assistant with "Please give fee...", then you shouldn't do it. The reason is that `autogen.AssistantAgent` has its own pre-defined prompt, if you replace it then the termination function should be updated accordingly. You can put any instructions in your user proxy agent's prompt.

**Comment by stonez56** [comment]
@thinkall Yes, If I didn't reply anything at user_proxy_agent prompt and it worked fine. 

However, If I replied a text at the user_proxy_agent prompt, the repeating message of USING AUTO REPLY...will repeat the max execution times I've set in the config.

**Comment by thinkall** [comment]
A user proxy's llm_config should be set to False. @stonez56

**Comment by stonez56** [comment]
@thinkall Just tried setting below, but it didn't work.

```Python
user_proxy = autogen.UserProxyAgent(
    name = "user_proxy",
    human_input_mode = "TERMINATE",
    max_consecutive_auto_reply = 10,
    is_termination_msg=lambda x: x.get("content", "").rstrip().endswith("TERMINATE"),
    code_execution_config={"work_dir": "D:\stone\Documents\python\ms-autogen\web"},
    llm_config=False,#this prevents AUTO REPLY...repeats many many times!
    system_message = """
    Reply TERMINATE if the task has been solved at full satisfaction. 
    Otherwise, reply CONTINUE, or the reason why the task is not solved yet."""
)
```

Here is the repeated reply on my terminal.

```log
Great! The workshop introduction has been successfully saved to the `workshop_intro.txt` file. You can now open the file to view the contents.

If you have any more questions or need further assistance, feel free to ask.

--------------------------------------------------------------------------------

>>>>>>>> USING AUTO REPLY...
user_proxy (to assistant):



--------------------------------------------------------------------------------
assistant (to user_proxy):

Is there anything else I can help you with? If you have any more questions or need further assistance, please let me know.

--------------------------------------------------------------------------------

>>>>>>>> USING AUTO REPLY...
user_proxy (to assistant):



--------------------------------------------------------------------------------
assistant (to user_proxy):

If you have any more questions or need further assistance in the future, feel free to ask. Have a great day!

--------------------------------------------------------------------------------

>>>>>>>> USING AUTO REPLY...
user_proxy (to assistant):



--------------------------------------------------------------------------------
assistant (to user_proxy):

Thank you! Have a great day too!

--------------------------------------------------------------------------------

>>>>>>>> USING AUTO REPLY...
user_proxy (to assistant):


--------------------------------------------------------------------------------
assistant (to user_proxy):

Thank you! I'm glad I could assist you. If you have any more questions or need help in the future, don't hesitate to ask. Have a great day!

--------------------------------------------------------------------------------

>>>>>>>> USING AUTO REPLY...
user_proxy (to assistant):



--------------------------------------------------------------------------------
assistant (to user_proxy):

You're welcome! I'm here to help. If you have any more questions or need assistance in the future, feel free to reach out. Have a fantastic day!

--------------------------------------------------------------------------------

>>>>>>>> USING AUTO REPLY...
user_proxy (to assistant):



--------------------------------------------------------------------------------
assistant (to user_proxy):

Thank you! I'm glad I could assist you. If you have any more questions or need help in the future, don't hesitate to ask. Have a great day!

--------------------------------------------------------------------------------

>>>>>>>> USING AUTO REPLY...
user_proxy (to assistant):



--------------------------------------------------------------------------------
assistant (to user_proxy):

You're welcome! I'm here to help. If you have any more questions or need assistance in the future, feel free to reach out. Have a fantastic day!

--------------------------------------------------------------------------------
Please give feedback to assistant. Press enter to skip and use auto-reply, or type 'exit' to stop the conversation:
```

**Comment by thinkall** [comment]
Can you share the whole code so I can reproduce. Thanks.

**Comment by stonez56** [comment]
@thinkall  Here is my complete code. Thank you!

```Python
# use 'pip install pyautogen' instad of 'pip install autogen'!!
import autogen
import OPENAI_KEY

config_list = [
    {
        'model': 'gpt-3.5-turbo-16k-0613',
        'api_key': OPENAI_KEY.myKey
    }
]

llm_config={
    "request_timeout": 600,
    "seed": 42, #for catching to saving money
    "config_list": config_list,
    "temperature": 0
}

assistant = autogen.AssistantAgent(
    name="assistant",
    llm_config = llm_config,
    system_message = "Your loyal assistant!"
)

user_proxy = autogen.UserProxyAgent(
    name = "user_proxy",
    human_input_mode = "TERMINATE",
    max_consecutive_auto_reply = 10,
    is_termination_msg=lambda x: x.get("content", "").rstrip().endswith("TERMINATE"),
    code_execution_config={"work_dir": "D:\stone\Documents\python\ms-autogen\web"},
    llm_config=llm_config,
    system_message = """
    Reply TERMINATE if the task has been solved at full satisfaction. 
    Otherwise, reply CONTINUE, or the reason why the task is not solved yet."""
)

task = """
Write me a python code that add odd numbers from 1 to 1000 and print out the result. After that, save the Python code in a file.
"""

user_proxy.initiate_chat(
    assistant,
    message=task,
)
```

**Comment by LOGIC-10** [comment]
I met the same problem with similar code, actually totally the same.
I said :" Write a code that can print 1~20 and save the code in a .txt file"

but it shows this all the time :

>>>>>>>> USING AUTO REPLY...

>>>>>>>> EXECUTING CODE BLOCK 0 (inferred language is python)...
execute_code was called with use_docker evaluating to True, but the python docker package is not available. Falling back to native code execution. Note: this fallback behavior is subject to change

>>>>>>>> EXECUTING CODE BLOCK 1 (inferred language is unknown)...
user_proxy (to assistant):

exitcode: 1 (execution failed)
Code output: 
2
3
5
7
11
13
17
19

unknown language unknown
---------------------------------
why it cannot automatically execute python in my computer?

**Comment by sonichi** [comment]
"save the code in a .txt file" may be confusing. Do you mean save the code as .py or save the results as .txt?

**Comment by stonez56** [comment]
@thinkall  It worked!
I modified the system_message as you suggested above and the code worked! Thank you!
