### ISSUE TITLE
[Issue]: Agentic Loop over a large document

### ISSUE THREAD

**Issue by ismailsimsek** [microsoft/autogen#2542]
### Describe the issue

Is it possible to read large PDF document in chunks using agents. Without programmatic loop. 

Could it be done using [task-decomposition](https://microsoft.github.io/autogen/docs/topics/task_decomposition#approach-1.-two-agent-chat-with-function-call-for-task-decomposition)?  have anyone done something similar?

### Steps to reproduce

something like below:
1. Agents uses tool and reads PDF document 50 pages each time (total 300 pages)
2. Agents summarizes all the chunks to 6 page output
2. Summary written to file

**Comment by WaelKarkoub** [comment]
@ismailsimsek are you asking for an OCR capability or a rag capability? If OCR, I believe it's planned in the multimodality road map https://github.com/microsoft/autogen/issues/1975

**Comment by ismailsimsek** [comment]
Currently trying to get it work with RAG  ( RetrieveUserProxyAgent + GroupChatManager )

Appreciate if anyone could point to similar solutions..

Current code is here: https://github.com/ismailsimsek/aistorybooks/blob/story-book/classic_storiesv2.py
PR https://github.com/ismailsimsek/aistorybooks/pull/3

**Comment by thinkall** [comment]
> Currently trying to get it work with RAG ( RetrieveUserProxyAgent + GroupChatManager )
> 
> Appreciate if anyone could point to similar solutions..
> 
> Current code is here: https://github.com/ismailsimsek/aistorybooks/blob/story-book/classic_storiesv2.py PR [ismailsimsek/aistorybooks#3](https://github.com/ismailsimsek/aistorybooks/pull/3)
> 
> currently just trying to summarize PDF, later on planning to add image generation too



> Currently trying to get it work with RAG ( RetrieveUserProxyAgent + GroupChatManager )
> 
> Appreciate if anyone could point to similar solutions..
> 
> Current code is here: https://github.com/ismailsimsek/aistorybooks/blob/story-book/classic_storiesv2.py PR [ismailsimsek/aistorybooks#3](https://github.com/ismailsimsek/aistorybooks/pull/3)
> 
> currently just trying to summarize PDF, later on planning to add image generation too

The current RetrieveUserProxyAgent should support PDF files. Have you tried it?

**Comment by ismailsimsek** [comment]
@thinkall what i was looking into is summarizing the PDF in small chunks, since its too big. in a loop, is that possible using the  agents to loop and process chunks one by one?

**Comment by thinkall** [comment]
> @thinkall i will check it. what i am looking into is summarizing the PDF in small chunks, since its too big. in a loop, is that possible using the agents to loop and process chunks one by one?



> @thinkall i will check it. what i am looking into is summarizing the PDF in small chunks, since its too big. in a loop, is that possible using the agents to loop and process chunks one by one?

The agent will split the pdf into chunks and save it into vector db.

**Comment by thinkall** [comment]
Close as it's not active for a long time. Please reopen if the issue still persist.
