### ISSUE TITLE
[Issue]: Tools not registered, OpenAI: "Can't execute code or create files"

### ISSUE THREAD

**Issue by geezz07** [microsoft/autogen#2568]
### Describe the issue

I am following this [tutorial](https://microsoft.github.io/autogen/docs/notebooks/agentchat_function_call_code_writing). However I've tried to run it multiple times but I keep getting "As an AI developed by OpenAI, I don't have the capability to directly interact with file systems or execute code". 

What am I doing wrong?

**Comment by GregorD1A1** [comment]
@geezz07 Let me check it out.

**Comment by geezz07** [comment]
@GregorD1A1 

I should've also mentioned that it's not just this tutorial specially. I've tried other tutorials too but more often then not I would get  "As an AI developed by OpenAI, I don't have the capability to directly interact with file systems or execute code".

I'm on a Windows machine.

**Comment by ekzhu** [comment]
@geezz07, just a quick comment: can you print out your agent's llm_config like `agent.llm_config['tools']` to see if they have their tools registered?

**Comment by geezz07** [comment]
@ekzhu, I get the following error:

```
Traceback (most recent call last):
  File "/mnt/d/Projects/python/autogen_examples/app.py", line 35, in <module>
    engineer.llm_config['tools']
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'tools'
```

**Comment by GregorD1A1** [comment]
@geezz07 It looks like your llm has no idea about the existance of functions. You mean your tool definitions are placed in separate file then agents? Can you show code?

**Comment by geezz07** [comment]
Certainly

app.py

import os
import autogen

config_list = [{"model": "gpt-4-turbo-preview", "api_key": os.getenv("OPENAI_API_KEY")}]

llm_config = {
    "cache_seed": 2,
    "temperature": 0,
    "config_list": config_list,
}

engineer = autogen.AssistantAgent(
    name="Engineer",
    llm_config=llm_config,
    system_message="""
    I'm Engineer. I'm expert in python programming. I'm executing code tasks required by Admin.
    """,
)

user_proxy = autogen.UserProxyAgent(
    name="Admin",
    human_input_mode="ALWAYS",
    code_execution_config=False,
)

groupchat = autogen.GroupChat(
    agents=[engineer, user_proxy],
    messages=[],
    max_round=500,
    speaker_selection_method="round_robin",
    enable_clear_history=True,
)
manager = autogen.GroupChatManager(groupchat=groupchat, llm_config=llm_config)

engineer.llm_config['tools']

chat_result = user_proxy.initiate_chat(
    manager,
    message="""
You will need to improve app in FastApi. For now, check out all the application files, try to understand it and wait for next instructions.
""",
)

functions.py

from typing_extensions import Annotated

default_path = "backend_dir/"

@user_proxy.register_for_execution()

@engineer.register_for_llm(description="List files in choosen directory.")
def list_dir(directory: Annotated[str, "Directory to check."]):
    files = os.listdir(default_path + directory)
    return 0, files


@user_proxy.register_for_execution()
@engineer.register_for_llm(description="Check the contents of a chosen file.")
def see_file(filename: Annotated[str, "Name and path of file to check."]):
    with open(default_path + filename, "r") as file:
        lines = file.readlines()
    formatted_lines = [f"{i+1}:{line}" for i, line in enumerate(lines)]
    file_contents = "".join(formatted_lines)

    return 0, file_contents


@user_proxy.register_for_execution()
@engineer.register_for_llm(description="Replace old piece of code with new one. Proper indentation is important.")
def modify_code(
    filename: Annotated[str, "Name and path of file to change."],
    start_line: Annotated[int, "Start line number to replace with new code."],
    end_line: Annotated[int, "End line number to replace with new code."],
    new_code: Annotated[str, "New piece of code to replace old code with. Remember about providing indents."],
):
    with open(default_path + filename, "r+") as file:
        file_contents = file.readlines()
        file_contents[start_line - 1 : end_line] = [new_code + "\n"]
        file.seek(0)
        file.truncate()
        file.write("".join(file_contents))
    return 0, "Code modified"


@user_proxy.register_for_execution()
@engineer.register_for_llm(description="Create a new file with code.")
def create_file_with_code(
    filename: Annotated[str, "Name and path of file to create."], code: Annotated[str, "Code to write in the file."]
):
    with open(default_path + filename, "w") as file:
        file.write(code)
    return 0, "File created successfully"


@user_proxy.register_for_execution()
@engineer.register_for_llm(description="Create a new file with code.")
def create_file_with_code(
    filename: Annotated[str, "Name and path of file to create."], code: Annotated[str, "Code to write in the file."]
):
    with open(default_path + filename, "w") as file:
        file.write(code)
    return 0, "File created successfully"

**Comment by GregorD1A1** [comment]
The problem caused by the fact your functions are in the different file. The simpliest, but less elegant solution will be just to move all your code to the single file. More elegant solution will be to define your functions in separate file without `@user_proxy.register_for_execution()
@engineer.register_for_llm(description=` decorators, next import them to the main file and apply decorators in it.

**Comment by geezz07** [comment]
That was it. Thank you!

**Comment by YinSonglin1997** [comment]
> The problem caused by the fact your functions are in the different file. The simpliest, but less elegant solution will be just to move all your code to the single file. More elegant solution will be to define your functions in separate file without `@user_proxy.register_for_execution() @engineer.register_for_llm(description=` decorators, next import them to the main file and apply decorators in it.

But when I run it in the example notebook/agentchat_function_call_currency_calculator.ipynb, I also report this error：KeyError: 'tools'

**Comment by GregorD1A1** [comment]
@YinSonglin1997 not sure is it the same issue. Can you tell more about how does error happened? You moved you tools in separate file also? or you just executed notebook?

**Comment by YinSonglin1997** [comment]
> @YinSonglin1997 not sure is it the same issue. Can you tell more about how does error happened? You moved you tools in separate file also? or you just executed notebook?

I just executed notebook，but it does not work. The version of the package is also correct.
