### ISSUE TITLE
[Issue]: Multi-user session states?

### ISSUE THREAD

**Issue by afogarty85** [microsoft/autogen#2571]
### Describe the issue

How can I use autogen, ideally GroupChat and GroupChatManager such that multiple users can engage with the same workflow but have their own contained chat history? I have been playing with the clear_history parameter on the initiate_chat method, but it will clear the history on all sessions that are open while using Gradio.

**Comment by r4881t** [comment]
Something like this? https://x.com/xpranavprakash/status/1788534328147751065
