### ISSUE TITLE
ADD RetrieveAssistantAgent in group chat?

### ISSUE THREAD

**Issue by xianzhisheng** [microsoft/autogen#259]
how can I add a RetrieveAssistantAgent or a RetrieveUserProxyAgent into a group chat?
i need an expert agent who can search external docs in the group so others agent can ask him sth

**Comment by sonichi** [comment]
@thinkall in case you have a solution.

**Comment by thinkall** [comment]
Hi @xianzhisheng , #227 has an example for it.

**Comment by xianzhisheng** [comment]
@thinkall is this feature still working in progress?

**Comment by thinkall** [comment]
> @thinkall is this feature still working in progress?

Yes, if not urgent, you can wait till it's merged.

**Comment by sonichi** [comment]
@xianzhisheng the PR is ready for reviewing. No code change is needed from the library. Would you like to review the example notebook and give it a try?

**Comment by thinkall** [comment]
Hi @xianzhisheng , PR merged, please check this https://github.com/microsoft/autogen/blob/main/notebook/agentchat_groupchat_RAG.ipynb
