### ISSUE TITLE
[Issue]: For configuring AzureOpenAI how to send the value user appkey ?

### ISSUE THREAD

**Issue by srinjoychak** [microsoft/autogen#2590]
### Describe the issue

Hi Team,

I am using an Enterprise Azure OpenAI endpoint. I am using Deployment = 'gpt-35-turbo-16k'
For my enterprise we have a parameter 'appkey', which identifies our unique application in Azure OpenAI. 

To load the LLM model i generally use the following method 

```
from langchain_openai import AzureChatOpenAI

llm = AzureChatOpenAI(deployment_name="gpt-35-turbo-16k",                       
                       api_key=token_response.json()["access_token"],  
                       api_version="2023-12-01-preview",
                       model_kwargs=dict(
                       user=f'{{"appkey": "{APP_KEY}"}}'
                     )
        )          
```

This is my config_list for the same Azure OpenAI configuration for Autogen

```
config_list = [
  {
    "model": "gpt-35-turbo-16k",
    "api_type": OPENAI_API_TYPE,
    "api_key": token,
    "base_url": OPENAI_API_BASE,
    "api_version": OPENAI_API_VERSION 
  }
]
```

However i am unable to understand how to provide the 'appkey' value, or if it will be supported. Couldn't find an additional user parameter or equivalent. 

Any guidance will be highly appreciated. 

Thanks in advance.

**Comment by ekzhu** [comment]
Could you try adding the `model_kwargs` in the config?

**Comment by srinjoychak** [comment]
It worked Thank you so much.

Putting the final config_list that worked for me, for anyone requiring a reference: 

```
config_list = [
  {
    "model": "gpt-35-turbo-16k",
    "api_type": OPENAI_API_TYPE,
    "api_key": token,
    "base_url": OPENAI_API_BASE,
    "api_version": OPENAI_API_VERSION,
    "user" : f'{{"appkey": "{OPENAI_APP_KEY}", "user": "{USER_ID}"}}'
  }
]
```

**Comment by srinjoychak** [comment]
> Could you try adding the `model_kwargs` in the config?

Just want to add, if you directly put "model_kwargs" in config_list it throws exception ```TypeError: Completions.create() got an unexpected keyword argument 'model_kwargs'```

I the final config_list i have shared works correctly.
