### ISSUE TITLE
[.Net][Feature Request]: Add AutoGen.Anthropic package

### ISSUE THREAD

**Issue by LittleLittleCloud** [microsoft/autogen#2608]
### Is your feature request related to a problem? Please describe.

I want to connect to Claude models

### Describe the solution you'd like

The `AutoGen.Anthropic` should contain the following classes
- AnthropicClientAgent: An implementation of `IStreamingAgent` class that can connect to Anthropic claude model
- AnthropicMessageConntector: a connector that convert claude message type to autogen message types

We can use the [Anthropic.SDK](https://www.nuget.org/packages/Anthropic.SDK) to consume claude backend api. The SDK provides support for non-streaming/streaming and tool call.

**Comment by DavidLuong98** [comment]
Just wondering, the linked SDK is not an official MSFT package. Does this have any concern?

**Comment by LittleLittleCloud** [comment]
> Just wondering, the linked SDK is not an official MSFT package. Does this have any concern?

For now it should be ok. The linked SDK is under mit license so we can freely use it. For other concerns like security/compliance check/etc, we can run those checks when someone put these items on our radar.
