### ISSUE TITLE
[.Net][Bug]: Constructor of conversableAgentConfig does not accept LMStudioConfig as ConfigList

### ISSUE THREAD

**Issue by PrinzMegahertz** [microsoft/autogen#2609]
### Describe the bug

Coming from autogen for Python, I'm used to the framework actually being able to run with LM-Studio. In case of the DotNet implementation, I can't use (as the title says) an IEnumerable of LMStudioConfig as ConfigList, even though the ConfigList is an IEnumerable of ILLMConfig, which LMStudioConfig implements as well. 

### Steps to reproduce

Create a valid LMStudioConfig:
```csharp
internal class LLMRepository
{
    public ILLMConfig mylocalconfig()
    {
        return new LMStudioConfig("localhost", 1234);
    } 
}
```
Try to build an Agent that's not an LMStudioAgent 
```csharp
internal class AgentRepository
{
    public AssistantAgent Create_AsisstantAgent(ILLMConfig config)
    {
        IEnumerable<ILLMConfig> value = [config];
        var myAgent = new AssistantAgent(
            name: "Assistant",
            systemMessage: "You are an assistant that help user to do some tasks.",
            llmConfig: new ConversableAgentConfig
            {
                Temperature = 0,
                ConfigList = value
            });
        myAgent.RegisterPrintMessage(); // register a hook to print message nicely to console            
        return myAgent;
    }       
}
```
### Model Used

Llama3

### Expected Behavior

The Agent should have been built

**Comment by PrinzMegahertz** [comment]
First time reporting an issue on Github. I should apply the label DoNet, but haven't found out how yet.

**Comment by LittleLittleCloud** [comment]
Mark as completed
