### ISSUE TITLE
[Issue]: Want to run LocalCommandLineCodeExecutor within an venv

### ISSUE THREAD

**Issue by akashDawariLTIM** [microsoft/autogen#2613]
### Describe the issue

I want the agent to run their generated code within an venv so that i donot have to install all the unwant packages into my Base python env. Is there any way in LocalCommandLineCodeExecutor to run the code in a venv?

**Comment by Gr3atWh173** [comment]
Custom python environments aren't supported yet. IIRC the local executor re-uses whatever environment autogen is being ran on.

**Comment by auphof** [comment]
@rysweet can please labeled this as 0.4 as well

v0.2 aquired venv capability with #2615 https://github.com/microsoft/autogen/blob/610388945b6da3a1cc0b70300a2225ad53d6b8f2/autogen/coding/local_commandline_code_executor.py#L88
The current implementation of LocalCommandLineCodeExecutor in v0.4 does not support virtual environments https://github.com/auphof/autogen/blob/e7729511466619edb6a3e32c131d9b73333a6cf3/python/packages/autogen-core/src/autogen_core/components/code_executor/_impl/local_commandline_code_executor.py#L51

It would be really  useful  to have venv's support back to not have Base Python polluted with installed modules

**Comment by rysweet** [comment]
Thanks @auphof - moved to 0.4 and assigned.

**Comment by ekzhu** [comment]
@gziz
