### ISSUE TITLE
[.Net][Feature Request]: Support custom HttpClient

### ISSUE THREAD

**Issue by xuzeyu91** [microsoft/autogen#2614]
### Is your feature request related to a problem? Please describe.

I hope to customize HttpClient similar to Semantic Kernel

### Describe the solution you'd like

Similar to this
```
     var assistantAgent = new GPTAgent(
         name: "assistant",
         systemMessage: "You are an assistant that help user to do some tasks.",
         config: gpt35,
         httpclient:httpclient)
         .RegisterPrintMessage();

```

**Comment by LittleLittleCloud** [comment]
@xuzeyu91 Could you tell us why you want to pass a httpclient? Is that for retry policy/connect to third party openai, etc...

**Comment by xuzeyu91** [comment]
> Could you tell us why you want to pass a httpclient? Is that for retry policy/connect to third party openai, etc...

This will be of great help to us, such as viewing the Prompt for analyzing requests, printing input-output response logs, and connecting to third party openai

**Comment by LittleLittleCloud** [comment]
@xuzeyu91 

Thanks, maybe consider using `OpenAIChatAgent`, which accepts an `OpenAIClient` in it's constructor and you can pass your http client when creating `OpenAIClient`

You can check the example [here](https://github.com/microsoft/autogen/blob/fd12558d262a4442452c785d271634faa0c3b59d/dotnet/sample/AutoGen.BasicSamples/Example16_OpenAIChatAgent_ConnectToThirdPartyBackend.cs)

`GPTAgent` also uses `OpenAIChatAgent`, in fact `GPTAgent` is equivalent to `OpenAIChatAgent` + `OpenAI Message Connector` + `FunctionCall Middleware`, so you can achieve the same behavior of using `OpenAIChatAgent` in your code

**Comment by xuzeyu91** [comment]
Thank you.

**Comment by LittleLittleCloud** [comment]
@xuzeyu91 Does my answer works for you, could I close this issue as completed?

**Comment by xuzeyu91** [comment]
> Does my answer works for you, could I close this issue as completed?

Thank you, no problem
