### ISSUE TITLE
AutoGen.DotnetInteractive Package Compatibility Issue

### ISSUE THREAD

**Issue by feynmanloo** [microsoft/autogen#2646]
### Describe the issue

An issue was encountered when attempting to add the AutoGen.DotnetInteractive package to the project. Despite specifying version 0.0.13, the process resulted in a compatibility issue. The system indicated that the package Microsoft.DotNet.Interactive.VisualStudio could not be found during the restore process and ultimately reported that the AutoGen.DotnetInteractive package is incompatible with the "all" framework in the project.

### Steps to reproduce

1. Execute the command dotnet add package AutoGen.DotnetInteractive --version 0.0.13 in the command line.
2. The system begins to restore the package and attempts to fetch the necessary dependencies.
3. A 404 Not Found error is returned when trying to retrieve the Microsoft.DotNet.Interactive.VisualStudio package from the NuGet source.
4. The system continues to attempt the restore but ultimately reports an error: error: NU1101: Could not find package Microsoft.DotNet.Interactive.VisualStudio.
5. The error message further indicates that the AutoGen.DotnetInteractive package is incompatible with the "all" framework in the project.

### Screenshots and logs

info : Adding PackageReference for package 'AutoGen.DotnetInteractive' version '0.0.13' to project 'C:\Users\Feynman Loo\Workspaces\Autogen-Demo\Autogen-Demo.csproj'.
info : Restoring packages for C:\Users\Feynman Loo\Workspaces\Autogen-Demo\Autogen-Demo.csproj...
info : NotFound https://api.nuget.org/v3-flatcontainer/microsoft.dotnet.interactive.visualstudio/index.json  1951 ms
error: NU1101: Could not find package 'Microsoft.DotNet.Interactive.VisualStudio' in the sources Microsoft Visual Studio Offline Packages, nuget.cnblogs.com, nuget.org.
error: Package 'AutoGen.DotnetInteractive' is not compatible with 'all' targeted frameworks in project 'C:\Users\Feynman Loo\Workspaces\Autogen-Demo\Autogen-Demo.csproj'.

**Comment by LittleLittleCloud** [comment]
The dotnet interactive visual studio package can be found in the following feed https://github.com/microsoft/autogen/blob/b2d3474324f30e64071ab1e68c6d848dd2707898/dotnet/NuGet.config#L5

**Comment by feynmanloo** [comment]
> The dotnet interactive visual studio package can be found in the following feed (either dotnet public or dotnet tool)
> 
> https://github.com/microsoft/autogen/blob/b2d3474324f30e64071ab1e68c6d848dd2707898/dotnet/NuGet.config#L5

![image](https://github.com/microsoft/autogen/assets/20107191/6cd5b425-4812-4e50-ad86-fdc5a66c6b65)
@LittleLittleCloud  the same

**Comment by LittleLittleCloud** [comment]
@feynmanloo try dotnet tools feed?

**Comment by feynmanloo** [comment]
> @feynmanloo try dotnet tool feed?

![image](https://github.com/microsoft/autogen/assets/20107191/97a74cc6-1310-48e3-8eaf-5bf1f9bc0b9c)

@LittleLittleCloud

**Comment by feynmanloo** [comment]
NotFound https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/45bacae2-5efb-47c8-91e5-8ec20c22b4f8/nuget/v3/flat2/microsoft.dotnet.interactive.visualstudio/index.json 1878 毫秒

![image](https://github.com/microsoft/autogen/assets/20107191/cfb1c0d2-c8a5-4912-9a36-04c50c4f0d2c)

@LittleLittleCloud

**Comment by feynmanloo** [comment]
@LittleLittleCloud fixit，change to use 
<add key="dotnet-tools" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json" />

it works ! thx a lot !

**Comment by LittleLittleCloud** [comment]
Thanks, I will update the website to add the instructions on installing interactive package
