### ISSUE TITLE
Fix outdated use of `summary_prompt` in tutorial. 

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#2657]
In the tutorial page: https://microsoft.github.io/autogen/docs/tutorial/conversation-patterns

There are several examples of using `summary_prompt` however the code is outdated as `summary_prompt` is not the top-level argument anymore, it should be:

```python
{
    "recipient": group_chat_manager_with_intros,
    "summary_method": "reflection_with_llm",
    "summary_args":  {"summary_prompt": "Summarize the sequence of operations used to turn " "the source number into target number."},
},
```

Would you like to help fixing this?

_Originally posted by @ekzhu in https://github.com/microsoft/autogen/issues/2621#issuecomment-2105378672_

**Comment by pk673** [comment]
@ekzhu I would love to work on this, could you please assign this to me. thanks!

**Comment by ekzhu** [comment]
@pk673 just assigned. Thanks!

**Comment by prithvi2226** [comment]
Hey @ekzhu! Has this issue been solved? Thanks!

**Comment by ekzhu** [comment]
> Hey @ekzhu! Has this issue been solved? Thanks!

Yes
