### ISSUE TITLE
[Feature Request] Inject message history through `initiate_chat`. 

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#2671]
1. In a typical scenario, the "end user" (human) would want the interface (single Agent, SoM, Group Chat etc) to retain their own context. Any system implementing this would most likely store the end user's query and the interface's response in some DB.
2. To recreate this, the only details available would be user's query and the response. This should be passed to the agent (user proxy or similar).

I would expect something like below

1. ConversableAgent's `initiate_chat` to take a previous history of context and then be able to use it.

While something like this can be achieved using `initiate_chat`'s `message` param which can be a callable, having a native implementation would be helpful. Because in this scenario, it sometimes end up loosing the context, because it also depends on the system prompt of the agent to be able to realise this.

```python

assistant = ConversableAgent(
      name="Assistant",
      system_message="Your are a friendly Q&A Bot"
      "You may use the previous messages to understand the context of current Query"
      "Return 'TERMINATE' when the task is done.",
      llm_config=self.llm_config,
      human_input_mode="NEVER",
      default_auto_reply="Reply with 'TERMINATE' if the task is done.",
      is_termination_msg=is_termination_msg
    )

def my_message(sender: ConversableAgent,
                   recipient: ConversableAgent,
                   context: dict) -> Union[str, Dict]:
      message = context.get("user_query", "")
      last_chats = context.get("last_chats", [])
      prelude = [f"Query: {x.get('query')}. Answer: {x.get('answer')}" for x in last_chats]
      curr_msg = f"CURRENT QUERY: {message}"
      final_msg = f"Previous Messages: {' '.join(prelude)}. {curr_msg}"
      return final_msg


user_proxy.initiate_chat(
      assistant,
      message=my_message,
      user_query=query,
      last_chats=last_chats,
      verbose=True
    )
```

In another example from the [blog mentioned here](https://github.com/microsoft/autogen/issues/229#issuecomment-2014348452), people are replaying the chat in GroupChat and broadcasting it to all other agents. I believe this need can also be eliminated if only the user's query & response are passed onto while initiating group chat

_Originally posted by @r4881t in https://github.com/microsoft/autogen/issues/2437#issuecomment-2106306254_

**Comment by jtoy** [comment]
In [replicantlife](https://github.com/jtoy/replicantlife), we implemented a log file as the database, but also allowed for in memory store, redis or postgres.

1) Is there an official default DB we support such as sqlite?
2) Do we want the history to be in a special format like JSON or newline separated records?

I think this needs more fleshing out before implementing, love the idea!

**Comment by r4881t** [comment]
I tried some versions of it locally. Based on my exp it seemed that the LLM is sometimes unnecessarily pulling up past context in current q&a even when it's not really needed. 

What really worked for us (more deterministically) was to add a tool that would fetch last conversations. So the LLM can decide if it needs the last context.

**Comment by ekzhu** [comment]
Focus development of new features in the new 0.4 version
