### ISSUE TITLE
[Bug]:  在根据示例去写程序的时候，遇到了实例不能调用的问题

### ISSUE THREAD

**Issue by lidisi8520** [microsoft/autogen#2683]
### Describe the bug

在我根据这个示例去创建自己的应用的时候。我遇到了一个问题。https://github.com/microsoft/autogen/blob/dotnet/dotnet/sample/AutoGen.BasicSamples/Example03_Agent_FunctionCall.cs
示例中有定义一个方法UpperCase。这个方法有一个注解，是Function。在run程序中，实例化这个类之后，var instance = new()，能直接instance.UpperCaseFunctionContract()，但是在我自己的代码中，不能instance.UpperCaseFunctionContract()。我想知道是哪一步有问题。我自己的代码中，我也有加注解。

**Comment by LittleLittleCloud** [comment]
Did you add the ‘AutoGen.SourceGenerator’ to your project?

**Comment by lidisi8520** [comment]
> Did you add the ‘AutoGen.SourceGenerator’ package to your project?

Thanks. After adding this package, this issue has been resolved

**Comment by lidisi8520** [comment]
![image](https://github.com/microsoft/autogen/assets/39178394/c260c288-d980-4d55-ac68-f1d71ac1525b)
在安装了之后，新生成的类中，没有找到这个依赖，我并不清楚是缺少什么包导致的，有遇到过这个问题的，可以帮帮我一下吗。

**Comment by lidisi8520** [comment]
> Did you add the ‘AutoGen.SourceGenerator’ package to your project?

![image](https://github.com/microsoft/autogen/assets/39178394/baf8327c-92e0-44cd-a925-75a33a62246b)
在安装了之后，新生成的类中，没有找到这个依赖，我并不清楚是缺少什么包导致的，
可以帮帮我一下吗。

**Comment by LittleLittleCloud** [comment]
看起来是namespace confliction因为你的namespace是‘Edonsoft.AIManagement.Azure’. 然后FunctionDefinition的命名空间是Azure.AI. 所以它就去Edonsoft.AIManagement.Azure.AI 去找FunctionDefinition了

**Comment by lidisi8520** [comment]
> 看起来是namespace confliction因为你的namespace是‘Edonsoft.AIManagement.Azure’. 然后FunctionDefinition的命名空间是Azure.AI. 所以它就去Edonsoft.AIManagement.Azure.AI 去找FunctionDefinition了
> 
> 我可以在下一版的source generator里加上global关键词，目前最快的fix应该是改namespace (比如把 Edonsoft.AIManagement.Azure改成Edonsoft.AIManagement.AzureAI)

好的，谢谢答复。我们这边修改项目内部的命名空间
