### ISSUE TITLE
[Issue]: How to break the inference in autogen studio ?

### ISSUE THREAD

**Issue by taozhiyuai** [microsoft/autogen#2686]
### Describe the issue

How to break the inference in autogen studio ? ctrl + c doesn't work.

**Comment by victordibia** [comment]
The new version of AutoGen Studio addresses this - specifically, there is a cancel button that can interrupt workflows.

https://github.com/user-attachments/assets/dc2b84b0-6302-4f07-b790-e264576bfb1a



The new [AutoGen v0.4 API](https://microsoft.github.io/autogen/dev/) introduces asynchronous operation, which enables seamless message passing between agents. This enhancement particularly benefits end-user applications by adding several crucial features that were difficult to implement in the previous version:

### New Features Already Available:
- Real-time agent updates streaming to the frontend
- Run control: You can now stop agents mid-execution if they're heading in the wrong direction, adjust the team, and continue
- Interactive feedback: Add a UserProxyAgent to get human input through the UI during team runs
- Message flow visualization: See how agents communicate with each other
