### ISSUE TITLE
[Bug]:  在使用[Function]注解时，自动生成的类中，会和自有项目中的命名空间冲突。

### ISSUE THREAD

**Issue by lidisi8520** [microsoft/autogen#2687]
### Describe the bug

![image](https://github.com/microsoft/autogen/assets/39178394/e37281f4-e603-4965-a1ba-009ccb345f37)

如图，这个类是我使用[Function]注解自动生成的类。这个类中，会在定义的函数中使用Azure.AI.OpenAI，这样看似没有问题，但是如果在我本地项目中有一个Azure的命名空间，那么，在这个函数这里使用Azure.AI.OpenAI会优先使用我本身项目的命名空间，导致程序本身找不到这个依赖报错，如果我将Azure.AI.OpenAI放在顶部，使用Using Azure.AI.OpenAI的话，是不会出现这个报错。（这个是我在另外一个类中简单的测试过一次，没有深入测试）。在我看来这可能像是一个bug。不知道现阶段是不是有解决这个bug的方案。

**Comment by lidisi8520** [comment]
> ### Describe the bug
> ![image](https://private-user-images.githubusercontent.com/39178394/330643256-e37281f4-e603-4965-a1ba-009ccb345f37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NDEyMjgsIm5iZiI6MTcxNTc0MDkyOCwicGF0aCI6Ii8zOTE3ODM5NC8zMzA2NDMyNTYtZTM3MjgxZjQtZTYwMy00OTY1LWExYmEtMDA5Y2NiMzQ1ZjM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDAyNDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0ZTQ4Y2EwNTk1OWM5NzIzNDhhM2MwNDQ4ZmRmZWY5ZWYxZTU1YmY5MjdmODVjMjRiN2JmZTIzOWMzMmFlMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6bEryhqo7sI9JwBr9o9ep7pNU-Rij5Hxrn9VZWCCJv0)
> 
> 如图，这个类是我使用[Function]注解自动生成的类。这个类中，会在定义的函数中使用Azure.AI.OpenAI，这样看似没有问题，但是如果在我本地项目中有一个Azure的命名空间，那么，在这个函数这里使用Azure.AI.OpenAI会优先使用我本身项目的命名空间，导致程序本身找不到这个依赖报错，如果我将Azure.AI.OpenAI放在顶部，使用Using Azure.AI.OpenAI的话，是不会出现这个报错。（这个是我在另外一个类中简单的测试过一次，没有深入测试）。在我看来这可能像是一个bug。不知道现阶段是不是有解决这个bug的方案。
> 
> ### Steps to reproduce
> _No response_
> 
> ### Model Used
> _No response_
> 
> ### Expected Behavior
> _No response_
> 
> ### Screenshots and logs
> _No response_
> 
> ### Additional Information
> _No response_

![image](https://github.com/microsoft/autogen/assets/39178394/fd8f14d4-0523-4afc-b960-66c32c4f883e)
我在另外一个类中同样定义了这么一个函数，但是我将依赖引入放在顶部，就不会出现上面图中那个报错。但是那个类是[Function]注解自动生成的，没有办法去修改。想知道还有其他办法解决它吗。

**Comment by LittleLittleCloud** [comment]
@lidisi8520 Thanks, will add `global` keyword in generated code

**Comment by LittleLittleCloud** [comment]
@lidisi8520 The fix is checked in, you can refer to latest nightly build to consume the package
