### ISSUE TITLE
[Bug]: 在使用[Function]注解的方法上无法添加注释

### ISSUE THREAD

**Issue by lidisi8520** [microsoft/autogen#2706]
### Describe the bug

在使用[Function]注解的方法上，无法添加文档注释。如果添加注释，在启动的时候，会出现自动生成的类产生报错。
我不确定这是否会成为一个bug，但是对于团队开发来说，无法添加注释是一个很糟糕的行为。

### Expected Behavior

可以添加文档注释，否则会导致团队其他人不明白这个方法的目的

### Screenshots and logs

![image](https://github.com/microsoft/autogen/assets/39178394/aa17abc2-fa33-458f-aec3-93e23586ad28)
这是我添加注释之后启动代码，自动生成的类直接报错

**Comment by LittleLittleCloud** [comment]
方便贴一下生成类的代码吗

**Comment by lidisi8520** [comment]
> 方便贴一下生成类的代码吗

﻿//----------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//----------------------
using Azure.AI.OpenAI;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using System;
using AutoGen.Core;
using AutoGen.OpenAI.Extension;

namespace Edensoft.AIManage.SemanticKernel.ToolAgent
{
    public partial class AgentTools
    {

        private class ClientToolSchema
        {
            [JsonPropertyName(@"url")]
			public List<string> url {get; set;}
            [JsonPropertyName(@"bodyParam")]
			public List<Dictionary<string, object>> bodyParam {get; set;}
            [JsonPropertyName(@"urlParam")]
			public List<string> urlParam {get; set;}
            [JsonPropertyName(@"methodParam")]
			public List<string> methodParam {get; set;}
        }

        public Task<string> ClientToolWrapper(string arguments)
        {
            var schema = JsonSerializer.Deserialize<ClientToolSchema>(
                arguments, 
                new JsonSerializerOptions
                {
                    PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
                });

            return ClientTool(schema.url, schema.bodyParam, schema.urlParam, schema.methodParam);
        }

        public FunctionContract ClientToolFunctionContract
        {
            get => new FunctionContract
            {
                Namespace = @"Edensoft.AIManage.SemanticKernel.ToolAgent",
                ClassName = @"AgentTools",
                Name = @"ClientTool",
                Description = @"创建http调用外部工具方法",
                ReturnType = typeof(Task<string>),
                Parameters = new []
                {
                    new FunctionParameterContract
                    {
                        Name = @"url",
                        Description = @"要调用的url",
                        ParameterType = typeof(List<string>),
                        IsRequired = true,
                    },
                    new FunctionParameterContract
                    {
                        Name = @"bodyParam",
                        Description = @"body请求参数",
                        ParameterType = typeof(List<Dictionary<string, object>>),
                        IsRequired = true,
                    },
                    new FunctionParameterContract
                    {
                        Name = @"urlParam",
                        Description = @"get请求参数",
                        ParameterType = typeof(List<string>),
                        IsRequired = true,
                    },
                    new FunctionParameterContract
                    {
                        Name = @"methodParam",
                        Description = @"请求方法 get post put delete",
                        ParameterType = typeof(List<string>),
                        IsRequired = true,
                    },
                },
            };
        }

        public Azure.AI.OpenAI.FunctionDefinition ClientToolFunction
        {
            get => this.ClientToolFunctionContract.ToOpenAIFunctionDefinition();
        }
    }
}

这个是我添加注释之后生成的类，看起来和没有添加注释的没有什么区别

**Comment by LittleLittleCloud** [comment]
注释会被用于生成function contract和function definition

**Comment by LittleLittleCloud** [comment]
能不能放一下ide截图，看一下是哪里报错了

**Comment by lidisi8520** [comment]
> 能不能放一下ide截图，看一下是哪里报错了

![image](https://github.com/microsoft/autogen/assets/39178394/ad7cbdec-f645-4fd3-8545-6f003b5e9f03)
这个是启动的时候的报错，基本上都在这里了。但是，在类里面去看， 又看不出什么问题。

**Comment by LittleLittleCloud** [comment]
可能是没在csproj里加这个？

<PropertyGroup>
    
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
</PropertyGroup>

来源：https://microsoft.github.io/autogen-for-net/articles/Create-type-safe-function-call.html

**Comment by lidisi8520** [comment]
> 可能是没在csproj里加这个？ ‘’’ true ‘’’ 来源：https://microsoft.github.io/autogen-for-net/articles/Create-type-safe-function-call.html

我试一下。

**Comment by lidisi8520** [comment]
> 可能是没在csproj里加这个？ `<GenerateDocumentationFile>true</GenerateDocumentationFile>`
> 
> 来源：https://microsoft.github.io/autogen-for-net/articles/Create-type-safe-function-call.html


好的，谢谢，已经解决
