### ISSUE TITLE
Azure openai key dont work

### ISSUE THREAD

**Issue by sixlycos** [microsoft/autogen#272]
After I referred to all the issues and tried all the modifications, I still got the prompt
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account /api-keys for details.

The code is the same as the demo and has not been changed.
my OAI_CONFIG_LIST like :
`
[
    {
        "model": "mymodelname",
        "api_key": "key",
        "api_base": "endpoint",
        "api_type": "azure",
        "api_version": "2023-06-01-preview"
    },
    {
        "model": "mymodelname",
        "api_key": "key",
        "api_base": "endpoint",
        "api_type": "azure",
        "api_version": "2023-06-01-preview"
    }
]

`

This configuration works on openai.ChatCompletion.create，Indicates that my model is fully usable。

But I still don’t understand why it doesn’t work properly in autogen

**Comment by olivMertens** [comment]
Mine is fonctionning 
<img width="424" alt="Capture d'écran 2023-10-17 165045" src="https://github.com/microsoft/autogen/assets/1814314/23c44e30-547b-4f7e-b919-5597adfd0ace">

`[
        {
            "model": "gpt-4",
            "api_key": "xxxxxxxx",
            "api_base": "xxxxxx",
            "api_type": "azure",
            "api_version": "2023-07-01-preview"
        }, 
        {
            "model": "gpt-3.5-turbo",
            "api_key": "xxxxxxxxxxxxxxxxxxxxxxx",
            "api_base": "xxxxx",
            "api_type": "azure",
            "api_version": "2023-07-01-preview"
        }
]`

**Comment by afourney** [comment]
If it's complaining that there's no key, it might not even be reading the file. When you run the example, are any warnings printed to the console? For example you might see something like this:

"The specified config_list file '{config_list_path}' does not exist."

**Comment by mlsymend** [comment]
For Azure the model name refers to the OpenAI Studio deployment name.

![image](https://github.com/microsoft/autogen/assets/83292057/1d9e447c-9462-41d4-983d-f9db33a96355)

**Comment by sonichi** [comment]
> For Azure the model name refers to the OpenAI Studio deployment name.
> 
> ![image](https://user-images.githubusercontent.com/83292057/276012285-1d9e447c-9462-41d4-983d-f9db33a96355.png)

This is worth being added to FAQ: https://microsoft.github.io/autogen/docs/FAQ#option-1-load-a-list-of-endpoints-from-json

**Comment by sixlycos** [comment]
> For Azure the model name refers to the OpenAI Studio deployment name.
> 
> ![image](https://user-images.githubusercontent.com/83292057/276012285-1d9e447c-9462-41d4-983d-f9db33a96355.png)

Yes, I mentioned that I read all the issues and I made sure that I used the deployment model name instead of you know directly copying gpt-4 in the example

This configuration works on openai.ChatCompletion.create

**Comment by sixlycos** [comment]
> @sixlycos, What are your model names? And are you using the same code as [olivMertens](https://github.com/olivMertens)? Thank you!

just use this case
`from autogen import AssistantAgent, UserProxyAgent, config_list_from_json
# Load LLM inference endpoints from an env variable or a file
# See https://microsoft.github.io/autogen/docs/FAQ#set-your-api-endpoints
# and OAI_CONFIG_LIST_sample
config_list = config_list_from_json(env_or_file="OAI_CONFIG_LIST")
# You can also set config_list directly as a list, for example, config_list = [{'model': 'gpt-4', 'api_key': '<your OpenAI API key here>'},]
assistant = AssistantAgent("assistant", llm_config={"config_list": config_list})
user_proxy = UserProxyAgent("user_proxy", code_execution_config={"work_dir": "coding"})
user_proxy.initiate_chat(assistant, message="Plot a chart of NVDA and TESLA stock price change YTD.")
# This initiates an automated chat between the two agents to solve the task`

**Comment by sixlycos** [comment]
> If it's complaining that there's no key, it might not even be reading the file. When you run the example, are any warnings printed to the console? For example you might see something like this:
> 
> "The specified config_list file '{config_list_path}' does not exist."

I tried it, the configuration file exists and can be read

**Comment by sixlycos** [comment]
Could this be related to the autogen version? Do I need to roll back？

**Comment by sixlycos** [comment]
Something strange occurred: I attempted to **redeploy a new model** in a different location, **and it works**. However, the old model can no longer be invoked using auto-generation.

I'm not sure what the issue is, but I appreciate your enthusiasm. Your response was really prompt  :D

**Comment by yhchang520** [comment]
The ”filter_dict“ configuration should contain the model in OAI_CONFIG_LIST, like this:
config_list = autogen.config_list_from_json(
        OAI_CONFIG_LIST,
        file_location=KEY_LOC,
        filter_dict={
            "model": {
                "gpt-3.5"
                "gpt-3.5-turbo",
                "gpt-4"
                "gpt-4-32k",
            },
        },
    )

**Comment by yhchang520** [comment]
Maybe the **filter_dict** configuration should contain the model in OAI_CONFIG_LIST, like this:
   ```
config_list = autogen.config_list_from_json(
        OAI_CONFIG_LIST,
        file_location=KEY_LOC,
        filter_dict={
            "model": {
                "gpt-3.5",
                "gpt-3.5-turbo",
                "gpt-4",
                "gpt-4-32k",
            },
        },
    )
```
