### ISSUE TITLE
[Bug]: 'name' field on messages not working when using Mistral.AI's API

### ISSUE THREAD

**Issue by marklysze** [microsoft/autogen#2748]
### Describe the bug

Mistral.AI's API is strict on what keys are allowed on the messages.

When running a GroupChat, the `name` key on each message is causing an exception when using the Mistral.AI API through the standard client:
```
openai.UnprocessableEntityError: Error code: 422 - {'object': 'error', 'message': {'detail': [{'type': 'extra_forbidden', 'loc': ['body', 'messages', 1, 'user', 'name'], 'msg': 'Extra inputs are not permitted', 'input': 'User_proxy'}]}, 'type': 'invalid_request_error', 'param': None, 'code': None}
```

If the `name` key is removed from each message no exception is thrown.

Mistral.AI API's documentation on message:
![image](https://github.com/microsoft/autogen/assets/66362098/323380f8-ff48-4aa3-9b12-a18e70b684a0)

Creating this issue in relation to testing from PR #2635, specific messages [1](https://github.com/microsoft/autogen/pull/2635#issuecomment-2119694056) and [2](https://github.com/microsoft/autogen/pull/2635#issuecomment-2123119436)

---

Would be good to have an endpoint that developers could use for Mistral.AI, and other non-OpenAI inference, where the `name` isn't accepted/used.

On a side-note, my testing shows that the `name` field isn't being used for Ollama, LiteLLM+Ollama, or together.ai.

**Comment by ekzhu** [comment]
A possible solution is to have a built-in model client for Mistral AI's API. It's a thin client that does a simple pop of the `name` key.

**Comment by marklysze** [comment]
> A possible solution is to have a built-in model client for Mistral AI's API. It's a thin client that does a simple pop of the `name` key. See example of model client: https://microsoft.github.io/autogen/docs/topics/non-openai-models/cloud-anthropic

Thanks @ekzhu, for Mistral, they have their own library, like the Anthropic one, so would you see this using that library or the openai library?

```
from mistralai.client import MistralClient
from mistralai.models.chat_completion import ChatMessage
```

**Comment by ekzhu** [comment]
I think using their library as an optional dependency makes sense. So when `api_type=mistral_ai`, it is going to check if the mistral client library has been installed if not then raise runtime error.

**Comment by marklysze** [comment]
> I think using their library as an optional dependency makes sense. So when `api_type=mistral_ai`, it is going to check if the mistral client library has been installed if not then raise runtime error. 

Okay, I've started creating a Mistral client model class.

**Comment by marklysze** [comment]
Hey @ekzhu, I've created a Mistral Client class. This class does cater for the removal of the `name` field. PR #2892.

**Comment by marklysze** [comment]
Yay, Mistral client class merged - please use `api_type='mistral'` in your configs to use it :).
