### ISSUE TITLE
[Bug]: wrong argument passing?

### ISSUE THREAD

**Issue by adam-osusky** [microsoft/autogen#2763]
### Describe the bug

https://github.com/microsoft/autogen/blob/fb74624376fa0f5b5a0b8da6677624bf3692eb6c/autogen/agentchat/contrib/retrieve_user_proxy_agent.py#L346-L352

Should not be on line 349 `self._chunk_token_size`?

Because we want to split by chunk size and not by maximal context size of the LLM.

**Comment by thinkall** [comment]
This has been fixed.
