### ISSUE TITLE
Is it possible to retry using a different model/deployment?

### ISSUE THREAD

**Issue by tyler-suard-parker** [microsoft/autogen#2765]
### Is your feature request related to a problem? Please describe.

Sometimes when I use too many tokens I get a rate limit.  I know there is a wait-and-retry feature, but it would be nice to be able to call from a backup deployment instead of just waiting.

### Describe the solution you'd like

Add to the config a backup or multiple backup deployments

**Comment by gagb** [comment]
@tyler-suard-parker -- you should be able to list multiple LLMs in the config list to fall back to?

**Comment by jackgerrits** [comment]
Closing as this looks answered, please feel free to reopen if you have any questions
