### ISSUE TITLE
Add to FAQ: For Azure the model name refers to the OpenAI Studio deployment name.

### ISSUE THREAD

**Issue by qingyun-wu** [microsoft/autogen#277]
> For Azure the model name refers to the OpenAI Studio deployment name.
> 
> ![image](https://user-images.githubusercontent.com/83292057/276012285-1d9e447c-9462-41d4-983d-f9db33a96355.png)

This is worth being added to FAQ: https://microsoft.github.io/autogen/docs/FAQ#option-1-load-a-list-of-endpoints-from-json

_Originally posted by @sonichi in https://github.com/microsoft/autogen/issues/272#issuecomment-1767276888_

**Comment by haseeb-xd** [comment]
Can I work on this?
