### ISSUE TITLE
[.Net][Feature Request]: Support image input for Anthropic Models

### ISSUE THREAD

**Issue by DavidLuong98** [microsoft/autogen#2770]
### Is your feature request related to a problem? Please describe.

Anthropic / Claude models do not support images in PR #2769

### Describe the solution you'd like

Support image input for the `AnthropicClient`, `AnthropicClientAgent`, and `AnthropicMessageConnector.cs`

**Comment by Deykeepcomn4me** [comment]
Keep calling from Google accounts these people have stolen money's from me
and are acting as me these are hackers hacking me please contact fbi
