### ISSUE TITLE
[Issue]: Error while executing "yarn build"

### ISSUE THREAD

**Issue by athmey** [microsoft/autogen#2806]
### Describe the issue

branch: master
tag: v0.2.27

Building the autogen-studio frondend from src code. Follow the instructions step by step in this page:
 https://microsoft.github.io/autogen/blog/2023/12/01/AutoGenStudio

npm install -g gatsby-cli 
npm install --global yarn
cd frontend
yarn install
yarn build

after excuting the "yarn build", the error occurs:

"gatsby-plugin-manifest" threw an error while running the onPostBootstrap lifecycle:
Input file contains unsupported image format

### Steps to reproduce

npm install -g gatsby-cli 
npm install --global yarn
cd frontend
yarn install
yarn build

### Screenshots and logs

![企业微信截图_20240528112910](https://github.com/microsoft/autogen/assets/29476966/36a2f386-dd69-4f02-8ecb-d237f4786248)

### Additional Information

OS: Ubuntu 20.04

**Comment by lfnovo** [comment]
Same error her.. on a Mac M2 running Sonoma. Anybody got a way to fix?

**Comment by Deykeepcomn4me** [comment]
These are hackers hacking me please contact fbi

**Comment by icoco** [comment]
the icon.png can not be preview, what is that

**Comment by athmey** [comment]
> I found a way to work around it. Just replaced the icon.png with another png file.. it was corrupted somehow.

Great!it works. Thank you so much. For whom encoutering the same issue, just replace the icon.png in "frontend" dir using the attached image.
![icon](https://github.com/user-attachments/assets/3c1db0e8-7f7a-4eb1-8908-c531ef6905b5)

**Comment by jems-lee** [comment]
I ran into this exact same issue on the main and autogenstudio branches. Replacing `icon.png` with random png allowed the build to succeed. Would this merit a PR for a permanent fix?
