### ISSUE TITLE
[Issue]: About code execution thread getting stuck

### ISSUE THREAD

**Issue by q351941406** [microsoft/autogen#2844]
### Describe the issue

When I use UserProxyAgent to execute code from a fastAPI server, it interrupts all the time and finally timeout. Is there any way to make it debug api automatically? 
I want the agent to automatically start the server and then use curl to debug the api

`from fastapi import FastAPI

app = FastAPI()

@app.get("/")
def read_root():
    return {"message": "Hello, World!"}

@app.get("/items/{item_id}")
def read_item(item_id: int, q: str = None):
    return {"item_id": item_id, "q": q}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)`

**Comment by gagb** [comment]
@q351941406 please provide more complete code to help us help you. Please reopen if you still have this issue.
