### ISSUE TITLE
How to remove some information output in the console???

### ISSUE THREAD

**Issue by SevenMpp** [microsoft/autogen#2876]
### Describe the bug

Is there a parameter to control whether to display it?
![image](https://github.com/microsoft/autogen/assets/34155680/635702b3-ddfe-428a-9482-a6f8634ff522)
code:
 llm_agent1 = AssistantAgent(name="LLM_Agent_1", llm_config=llm_configs, max_consecutive_auto_reply=1, is_termination_msg=lambda msg: "TERMINATE" in msg["content"])
response1 = user_proxy.initiate_chat(llm_agent1, message=original_query, max_turns=1)

**Comment by Hk669** [comment]
@SevenMpp thanks for reaching out. can you please tell us more about the issue/ context of the above code. so far i understood that you dont want the chat to be displayed in the cli.

**Comment by Hk669** [comment]
closing this issue, due to inactivity. feel free to reopen if required. thanks

**Comment by amanG251314** [comment]
thanks for reaching out. can you please tell us more about the issue/ context of the above code. so far i understood that you dont want the chat to be displayed in the cli.

yes, I dont want agentic conversation in the cli.
