### ISSUE TITLE
Document the usage of the AAD auth.

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#2880]
Add documentation of how to use AAD auth to `/docs/topics/llm_configuration.ipynb` 

_Originally posted by @ekzhu in https://github.com/microsoft/autogen/issues/2879#issuecomment-2153121660_

**Comment by prithvi2226** [comment]
Hi! @ekzhu ! Can I work on this task?

**Comment by ekzhu** [comment]
Thanks! I will assign it to you.
