### ISSUE TITLE
[Bug]:  Group chat does not work with Anthropic model

### ISSUE THREAD

**Issue by nguoithichkhampha** [microsoft/autogen#2884]
### Describe the bug

I have a group chat with multiple agent. one agent uses Anthropic model, other agents use openai model.
I have followed this instruction to implement Anthropic model
https://microsoft.github.io/autogen/docs/topics/non-openai-models/cloud-anthropic

### Model Used

claude-3-sonnet-20240229

### Expected Behavior

no error when run group chat

### Screenshots and logs

`anthropic.BadRequestError: Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row'}}`

### Additional Information

End point: anthropic

```[tasklist]
### Tasks
```

**Comment by LittleLittleCloud** [comment]
@DavidLuong98 Maybe AutoGen.Net also have this bug if Anthropic model requires role to show alternatively?

**Comment by nguoithichkhampha** [comment]
@brycecf , yes I did. Actually my workaround solution is add this line
`params['messages'] = [params['messages'][-1]]`
into function `create` of AnthropicClient class

**Comment by DavidLuong98** [comment]
Yes, AutoGen.Net has this bug. Just confirmed. @LittleLittleCloud

**Comment by Deykeepcomn4me** [comment]
You are helping hackers hack me please contact fbi

**Comment by Hk669** [comment]
we are working on enhancing AutoGen support for non openai models. feel free to checkout the roadmap #2946 . thanks

**Comment by Hk669** [comment]
closing the issue, considering it is addressed in the new release of the AutoGen. feel free to raise an issue or contact us at discord. thanks @nguoithichkhampha
