### ISSUE TITLE
[Bug]: CryptographyDeprecationWarning: Blowfish has been deprecated

### ISSUE THREAD

**Issue by Hk669** [microsoft/autogen#2891]
### Describe the bug

i understand the warning can be ignored but what could be the root cause of this warning?  is there any package that is generating the warning?

### Model Used

azure gpt-35-turbo

### Screenshots and logs

<img width="781" alt="image" src="https://github.com/microsoft/autogen/assets/96101829/64f554e5-65ff-4549-b445-d596484861e7">

**Comment by gagb** [comment]
@Hk669 -- can you please share more information about this bug? I am closing it for now.

**Comment by Hk669** [comment]
this is fixed already. Thanks @gagb for closing.
