### ISSUE TITLE
[Feature Request]: gpt-4o as supported model

### ISSUE THREAD

**Issue by tytung2020** [microsoft/autogen#2895]
### Is your feature request related to a problem? Please describe.

It seems gpt-4o is not yet supported in the Autogen code, as I check in the codes. No where is it found except in the token count and pricing. What happens when user calls gpt-4o as the model? From my experience it does not use the right way to insert the uploaded images. 

### Describe the solution you'd like

Add gpt-4o multimodal capability to Autogen

**Comment by Josephrp** [comment]
it's already available.

source ? i'm using it currently in all my autogen apps. just set 
```python 
'model' : 'gpt-4o'
``` 
in your openai api config or use your azure deployment with gpt-4o without any further changes.

**Comment by Deykeepcomn4me** [comment]
Please help I'm so confused and I know for a fact there are extra entities using my device. I don't understand how to use the work flows. Is there a way that I can contact a legitimate mentor or support?

**Comment by tytung2020** [comment]
> it's already available.
> 
> source ? i'm using it currently in all my autogen apps. just set
> 
> ```python
> 'model' : 'gpt-4o'
> ```
> 
> in your openai api config or use your azure deployment with gpt-4o without any further changes.

does it use  gpt4v_formatter to insert the image uri into prompt ?

**Comment by Deykeepcomn4me** [comment]
I don't believe I downloaded this please help as there has been hackers controlling my devices

**Comment by qingyun-wu** [comment]
Hi @Deykeepcomn4me, gpt-4o is already supported. If you are directly using openai's API, you can just set the value of the "model" field to be "gpt-4o" as @Josephrp suggested. I am closing this issue for now. Please feel free to ask for help on discord if any further help is needed! Thank you!

**Comment by Deykeepcomn4me** [comment]
These are hackers hacking me please contact fbi
