### ISSUE TITLE
[Bug]: Gemini missing message in history

### ISSUE THREAD

**Issue by yiranwu0** [microsoft/autogen#2900]
### Describe the bug

When calling Gemini, The last message is missing when the message history is 
```python
[{
"role": "system",
"content": "You are in a debate with others, please first claim whether you are for or against the topic, and explain why."
},
{
"role": "user",
"content": "Debate Topic: Should vaccination be mandatory?"
}]
```

Reason: The messages are not merged correctly in function `_oai_messages_to_gemini_messages` 

### Steps to reproduce

1. Add those print lines in `gemini.py`
<img width="892" alt="Screenshot 2024-06-09 at 5 48 00 PM" src="https://github.com/microsoft/autogen/assets/32823396/af307a21-a953-40a4-b581-f56b86236ea4">

2. run this code:
```python
import autogen
from autogen import OpenAIWrapper

def model_call_example_function(
        model: str,
        message: str,
        cache_seed: int = None,
):
    config_list = autogen.config_list_from_json(
        "OAI_CONFIG_LIST",
        filter_dict={
            "model": [model],
        }
    )
    client = OpenAIWrapper(config_list=config_list)
    response = client.create(
        messages=[{"role": "system", "content": "You are in a debate with others, please first claim whether you are for or against the topic, and explain why."},
            {"role": "user", "content": message}],
        cache_seed=cache_seed
    )

    print(f"\n\nResponse from model {model}: {response.choices[0].message.content}")

    client.print_usage_summary()

model_call_example_function(
    model="gemini-1.5-pro-latest",
    message="Debate Topic: Should vaccination be mandatory?"
)
```

Output:
```
Chat History []
Input Message:  You are in a debate with others, please first claim whether you are for or against the topic, and explain why.


Response from model gemini-1.5-pro-latest: Please provide me with the debate topic! I need to know what we're debating before I can tell you my stance. 😄 

Give me the topic, and I'll be happy to craft a compelling argument for or against it!  

----------------------------------------------------------------------------------------------------
Usage summary excluding cached usage: 
Total cost: 0.00125
* Model 'gemini-1.5-pro-latest': cost: 0.00125, prompt_tokens: 25, completion_tokens: 51, total_tokens: 76

All completions are non-cached: the total cost with cached completions is the same as actual cost.
----------------------------------------------------------------------------------------------------
```

We can see the debate topic is not in chat history, and not in "Input Message:"

**Comment by yiranwu0** [comment]
@BeibinLi @davorrunje Can you maybe take a look?

**Comment by luxzoli** [comment]
@yiranwu0 this has been accidentally introduced by the last changes to the Gemini client, which were not yet released.
I have created a PR for this issue: [#2906](https://github.com/microsoft/autogen/pull/2906)

The example from the comment above will have everything included in the input message, because the system role is mapped later to the user role, and consecutive messages with identical roles are concatenated. This way the behavior is identical to that of the latest release.

Bonus question: currently, messages are concatenated without any separator between them. Would perhaps the addition of a newline character be desired between concatenated messages to act as a separator?

**Comment by yiranwu0** [comment]
Thanks @luxzoli! Yeah I think a newline character would be good for now. Is there a specific gemini document saying that there cannot be same consecutive roles?

**Comment by luxzoli** [comment]
Good point @yiranwu0! I will look into it then if the concatenation can be avoided, and update my PR accordingly

**Comment by luxzoli** [comment]
I am getting the following exception from the Google API using the Vertex AI client, when consecutive messages of the same type are not merged (I have removed some lines from the trace):
```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "Please ensure that multiturn requests alternate between user and model."
        debug_error_string = "UNKNOWN:Error received from peer ipv4:172.217.218.95:443 {grpc_message:"Please ensure that multiturn requests alternate between user and model.", grpc_status:3, created_time:"2024-06-10T21:03:18.368206063+00:00"}"
>

The above exception was the direct cause of the following exception:
...
google.api_core.exceptions.InvalidArgument: 400 Please ensure that multiturn requests alternate between user and model.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
...
File "/home/lux_zoltan_andras/.local/lib/python3.10/site-packages/autogen/oai/gemini.py", line 208, in create
    raise RuntimeError(f"Google GenAI exception occurred while calling Gemini API: {e}")
RuntimeError: Google GenAI exception occurred while calling Gemini API: 400 Please ensure that multiturn requests alternate between user and model.
```
Interestingly, I was not getting this error with the google.generativeai.
For the VertexAI client this [official notebook](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/getting-started/intro_gemini_chat.ipynb) also writes that messages can be added with roles user and model alternately. I have modified the notebook to break this rule in the chat history, and got the following exception.
So maybe it is safer to keep merging consecutive messages with the same role? What do you think @yiranwu0 ?

**Comment by luxzoli** [comment]
I am getting the following exception from the Google API using the Vertex AI client, when consecutive messages of the same type are not merged (I have removed some lines from the trace):
```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "Please ensure that multiturn requests alternate between user and model."
        debug_error_string = "UNKNOWN:Error received from peer ipv4:172.217.218.95:443 {grpc_message:"Please ensure that multiturn requests alternate between user and model.", grpc_status:3, created_time:"2024-06-10T21:03:18.368206063+00:00"}"
>

The above exception was the direct cause of the following exception:
...
google.api_core.exceptions.InvalidArgument: 400 Please ensure that multiturn requests alternate between user and model.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
...
File "/home/lux_zoltan_andras/.local/lib/python3.10/site-packages/autogen/oai/gemini.py", line 208, in create
    raise RuntimeError(f"Google GenAI exception occurred while calling Gemini API: {e}")
RuntimeError: Google GenAI exception occurred while calling Gemini API: 400 Please ensure that multiturn requests alternate between user and model.
```
Interestingly, I was not getting this error with the google.generativeai.
For the VertexAI client this [official notebook](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/getting-started/intro_gemini_chat.ipynb) also writes that messages can be added with roles user and model alternately. I have modified the notebook to break this rule in the chat history, and got the following exception.
So maybe it is safer to keep merging consecutive messages with the same role? 
However, it seems like we can avoid concatenating the actual text by adding a list of parts to the `Content` object

What do you think @yiranwu0 ?
