### ISSUE TITLE
[Bug]: Autogen Studio App does not use the given baseurl

### ISSUE THREAD

**Issue by JaloWalt** [microsoft/autogen#2903]
### Describe the bug

For example with fireworks.ai model: FireFunction V1

Ref: https://fireworks.ai/models/fireworks/firefunction-v1

The base url is informed as: https://api.fireworks.ai/inference/v1/chat/completions

That would then result to the folllowing settings in autogen studio model specification:

Model name: accounts/fireworks/models/firefunction-v1

Api Key: your-fireworks-ai-secret-api-key

Base url: https://api.fireworks.ai/inference/v1/chat/completions

Api Type: empty

Api version: empty

Description: fireworks firefunction-v1

When testing this setup with "test-model" button the result is: 
=> Error occurred while testing model: Error code: 404 - {'detail': 'Not Found'}

The log shows:
  File "<my-computer-path>\site-packages\openai\_base_client.py", line 1020, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'detail': 'Not Found'}

However when the [Base url] is changed to: https://api.fireworks.ai/inference/v1

Then the result (with the same test) is: Model tested successfully

Therefore the conclusion is: Autogen Studio App does not respect the base url setting given by api-inference providers.

This is a serious BUG.

### Steps to reproduce

For example with fireworks.ai model: FireFunction V1

Ref: https://fireworks.ai/models/fireworks/firefunction-v1

The base url is informed as: https://api.fireworks.ai/inference/v1/chat/completions

That would then result to the folllowing settings in autogen studio model specification:

Model name: accounts/fireworks/models/firefunction-v1

Api Key: your-fireworks-ai-secret-api-key

Base url: https://api.fireworks.ai/inference/v1/chat/completions

Api Type: empty

Api version: empty

Description: fireworks firefunction-v1

When testing this setup with "test-model" button the result is: 
=> Error occurred while testing model: Error code: 404 - {'detail': 'Not Found'}

The log shows:
  File "<my-computer-path>\site-packages\openai\_base_client.py", line 1020, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'detail': 'Not Found'}

However when the [Base url] is changed to: https://api.fireworks.ai/inference/v1

Then the result (with the same test) is: Model tested successfully

Therefore the conclusion is: Autogen Studio App does not respect the base url setting given by api-inference providers.

This is a serious BUG.

### Model Used

accounts/fireworks/models/firefunction-v1

### Expected Behavior

The folllowing settings in autogen studio model specification should have worked:

Model name: accounts/fireworks/models/firefunction-v1

Api Key: your-fireworks-ai-secret-api-key

Base url: https://api.fireworks.ai/inference/v1/chat/completions

Api Type: empty

Api version: empty

Description: fireworks firefunction-v1

When testing this setup with "test-model" button the result should have been:
=> Model tested successfully

### Screenshots and logs

  File "<my-computer-path>\site-packages\openai\_base_client.py", line 1020, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'detail': 'Not Found'}

### Additional Information

Autogen Studio version: v0.0.56
puautogen version: pyautogen-0.2.27-py3-none-any.whl (as informed in build log)
Python version: Python 3.12.3

**Comment by JaloWalt** [comment]
When testing this issue with the newest autogen version: 0.0.56rc12

the behavior was as follows:

Creating a new model: it saved three times each new created model, but nothing new became visible in Models view.

After that any new models created did come visible in Models view.

In creating new models (after the first three [see above]) a new selection was presented: see attached picture; pre-choosing-model-type-2024-06-11_120029.jpg
![pre-choosing-model-type-2024-06-11_120029](https://github.com/microsoft/autogen/assets/170605213/bc07545a-ddc4-4f61-8c8d-d16f36310277)


Having a pre-choosing of model type between: OpenAI, Azure OpenAI and Gemini

However none of those worked (tested with the test-button) with the actual fireworks.ai base-url: https://api.fireworks.ai/inference/v1/chat/completions

Therefore, the informed bug still remains.

**Comment by charltonh** [comment]
I had a similar bug open:   https://github.com/microsoft/autogen/issues/2889

Could be more of a documentation/usability issue as both these env variables need to be set:

```
export OPENAI_API_BASE="http://192.168.1.64:5000/v1"
export OPENAI_BASE_URL="http://192.168.1.64:5000/v1"
```

**Comment by victordibia** [comment]
Hi @JaloWalt,

Can you confirm if the fireworks api endpoint you are referencing above is an openai compatible endpoint?
Please notE that only OAI compatible endpoints will work (see docs [here](https://microsoft.github.io/autogen/docs/autogen-studio/faqs#q-can-i-use-other-models-with-autogen-studio)). 

For example, I have a local endpoint (LMstudio)  which I can test successfully via the UI.
<img width="1057" alt="image" src="https://github.com/microsoft/autogen/assets/1547007/18bc64d4-3a9d-4423-a838-d7e37463af53"> 

This can be added to models by clicking the save model button. If you do not see your model in the catalog, there is change that you have have some issues with your installation. In that case, I'd recommend creating a new environment and installing autogenstudio (to address any database inconsistency issues).

<img width="1174" alt="image" src="https://github.com/microsoft/autogen/assets/1547007/ecd509fc-2d1c-484f-8583-d52f2fbdebaf">

You can then attach this model to an agent. I.e create a new agent or go to the models tab of an existing agent and set the model to the model you just created.

It should **not** be necessary to set environment variables once you have defined your models and agents in the UI. AGS only defaults to the openai base url if no base url is provided.

Also, see a video walkthrough of this process (creating a model and associating with an agent) here https://youtu.be/v5U4o-ODrng?si=J856_EDzf5K2_BRC&t=284

**Comment by JaloWalt** [comment]
Hi,

Thanks about the example using the local endpoint. It clarifies somewhat the usage with LMStudio and similar approaches.

Here is what I currently have and what I am able to confirm:

The following fireworks models did get OK, with the autogen "Test Model" button:

        accounts/fireworks/models/firefunction-v1		32768
        accounts/fireworks/models/firefunction-v2		8192
        accounts/fireworks/models/mixtral-8x7b-instruct		32768
        accounts/fireworks/models/mixtral-8x7b-instruct-hf	32768	
        accounts/fireworks/models/mixtral-8x22b-instruct	65536
        accounts/fireworks/models/mixtral-8x22b-instruct-hf	65536
        accounts/fireworks/models/yi-large			32768
        accounts/fireworks/models/qwen2-72b-instruct		32768
        accounts/fireworks/models/yi-34b-200k-capybara		200000

The following models did not get OK:

        accounts/fireworks/models/starcoder-16b			8192  

Error occurred while testing model: Error code: 404 - {'error': {'object': 'error', 'type': 'invalid_request_error', 'message': 'model is missing conversation_config, please use /completions API instead'}}

        accounts/fireworks/models/openorca-7b			32768 

Model not found.


Mentioning this just to show that (using always the same) baseurl alone is not enough to guarantee the model to work.

The above models I did put/set into autogen studio with the following baseurl https://api.fireworks.ai/inference/v1

The autogen studio version I used: v0.0.56rc12


Note also that I do have the following environment variables:


OPENAI_API_BASE="https://api.fireworks.ai/inference/v1"

OPENAI_BASE_URL="https://api.fireworks.ai/inference/v1"


I am inclined to agree with @charltonh that this is maybe a somewhat undocumented behaviour whereby the default api-provider is changed from openai to something else.

Yes, it does have consequences; by doing this (the above base and url environment variables) you (the configurating person) take the responsibility of handling for example the skills (when called by any agent/model) that should be done by default by actual openapi.

So, I think the situation where the default/fallback behaviour is (by you; the configurator) desired to be something else than actual openapi, is not something built-in by the current autogen studio developers.

I do not see any point holding this item open anymore, so I will close this. Feel free to re-open if necessary.
