### ISSUE TITLE
[Bug]: RAG - Collection already exists. 

### ISSUE THREAD

**Issue by marcopepunkt** [microsoft/autogen#2905]
### Describe the bug

Im just following the first steps of https://microsoft.github.io/autogen/blog/2023/10/18/RetrieveChat
And I'm running into following bug:

Exception has occurred: 
**ValueError**
Collection autogen-docs already exists.
  File "/USERPATH/main.py", line 52, in <module>
    ragproxyagent.initiate_chat(assistant, message=ragproxyagent.message_generator, problem="What is autogen?")
ValueError: Collection autogen-docs already exists.

### Steps to reproduce

Created a virtual environment and installed the dependencies with pip. 

### Model Used

gpt-4

### Additional Information

chromadb 0.5.0
pyautogen 0.2.28
Python 3.9.11
macOS Sonoma - 14.5

**Comment by Hk669** [comment]
can you please give us more information in the form of screenshots of your code/logs. thanks

**Comment by jprosevear** [comment]
This will happen on repeated tries unless `"get_or_create": True` is set for the retrieve_config

**Comment by thinkall** [comment]
Hi @marcopepunkt , 

```
ragproxyagent = RetrieveUserProxyAgent(
    name="ragproxyagent",
...
    retrieve_config={
...
        "vector_db": "chroma",  # to use the deprecated `client` parameter, set to None and uncomment the line above
        "get_or_create": True,  # set to False if you don't want to reuse an existing collection
        "overwrite": False,  # set to True if you want to overwrite an existing collection
    },
```

It will raise the error you saw when both `get_or_create` and `overwrite` are set to `False`.

**Comment by marcopepunkt** [comment]
Thank you, fixed it.
