### ISSUE TITLE
[Issue]: Code executor in user proxy

### ISSUE THREAD

**Issue by shaleenrajkaur** [microsoft/autogen#2910]
### Describe the issue

user proxy agent gives off this error. I thought the code_execution config should be set automatically. 
Error routing message: code_execution_config must be a dict or False. Could someone help me out with this please 

### Steps to reproduce

    user_proxy = autogen.UserProxyAgent(
        name="User",
        human_input_mode="NEVER",
        max_consecutive_auto_reply=5,
        is_termination_msg=lambda x: x.get("content", "")
        and x.get("content", "").rstrip().endswith("TERMINATE"),
        llm_config=llm_config,
        system_message="""Reply TERMINATE if the task has been solved at full satisfaction. Otherwise, reply CONTINUE, or the reason why the task is not solved yet.""",
    )

**Comment by Deykeepcomn4me** [comment]
These are hackers hacking me please contact fbi
