### ISSUE TITLE
[Bug]: Modified files after cloning main?!

### ISSUE THREAD

**Issue by gagb** [microsoft/autogen#2920]
### Describe the bug

Cloning current autogen's main results in weird behavior...
E.g., create a new code space on autogen main and run `git status` without making any modifications:
The screenshot below is for code space, but it can happens on wsl and Mac as well.

<img width="1117" alt="image" src="https://github.com/microsoft/autogen/assets/13227607/5899ab1e-c3f2-4942-b8ff-84016bcea2ac">

**Comment by qingyun-wu** [comment]
I also see this weird behavior. The two files I see are "test/test_notebook.py" and "website/blog/authors.yml".

**Comment by willeppy** [comment]
Also having this issue.

I think it might have to do with the line endings on these files not being correct / matching the prescribed ones in `.gitattributes`? Maybe VS Code updates the files automatically which is why it shows changes (but none visible in the diff view)

**Comment by davorrunje** [comment]
The problem is CRLF instead of LF file format, I created PR to fix it https://github.com/microsoft/autogen/pull/2915

**Comment by gagb** [comment]
This is what I saw this morning in a new codespace -- so the issue wasn't fully addressed:

![image](https://github.com/microsoft/autogen/assets/13227607/c15d4109-77f7-4b76-ab4c-9b666a3ddc44)

**Comment by davorrunje** [comment]
@gagb I somehow missed those two files at the first attempt (still not sure how because I used a script for it). Anyhow, here is a new PR #2935

**Comment by davorrunje** [comment]
Btw, I found the change that caused this in PR #2566: https://github.com/microsoft/autogen/pull/2566/files#diff-618cd5b83d62060ba3d027e314a21ceaf75d36067ff820db126642944145393e

**Comment by davorrunje** [comment]
<img width="1291" alt="Screenshot 2024-06-14 at 09 04 07" src="https://github.com/microsoft/autogen/assets/24715380/22f432cf-5073-4fd0-99ea-00ffd7c596c8">

@gagb just checked, everything seems fine now
