### ISSUE TITLE
[Bug]: AnthropicClient Example Does Not Work w/ Other Conversation Patterns

### ISSUE THREAD

**Issue by brycecf** [microsoft/autogen#2932]
### Describe the bug

Due to Anthropic not following the OpenAI messaging flow (_i.e._ it requires "user"->"assistant" strictly), and Autogen's underlying implementation of said OpenAI flow within `ConversableAgent`, the [`AnthropicClient` example notebook](https://microsoft.github.io/autogen/docs/topics/non-openai-models/cloud-anthropic) does not work beyond the demonstrated conversation flow.

### Steps to reproduce

1. Use [AnthropicClient](https://microsoft.github.io/autogen/docs/topics/non-openai-models/cloud-anthropic#implementation-of-anthropicclient) defined here. Any other custom model client would also work.
2. Run the [teacher+student example](https://microsoft.github.io/autogen/docs/tutorial/conversation-patterns/#two-agent-chat-and-chat-result) from the documentation site.

### Model Used

claude-3-sonnet-20240229

### Expected Behavior

No runtime error and comparable results to what is illustrated in the example.

**Comment by Hk669** [comment]
the new release #2946 should fix this issue. thanks
