### ISSUE TITLE
[Issue]: Timeout issues 

### ISSUE THREAD

**Issue by shaleenrajkaur** [microsoft/autogen#2945]
### Describe the issue

With some queries that I pass in, there is often timeout issues with autogen. I'm running my code inside docker - has anyone been experiencing this, if so what did you do to solve it? Thank you

### Screenshots and logs

<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>

**Comment by Deykeepcomn4me** [comment]
Hackers these are please call fbi

**Comment by Deykeepcomn4me** [comment]
L

**Comment by qingyun-wu** [comment]
Hi @shaleenrajkaur, there are many possible reasons for timeout. Could you provide some more information? For this type of question, I encourage you to ask on the discord server: https://discord.com/invite/pAbnFJrkgZ to get a timely response. Thank you!
