### ISSUE TITLE
[Issue]: Specified Azure OpenAI API versions do not support GPT-4o

### ISSUE THREAD

**Issue by Xtrah** [microsoft/autogen#2948]
gpt-4o has newer Azure OpenAI API version. I suggest simply changing API version in the sample config to:

```
"api_version": "<your Azure OpenAI API version here>"
```

Leaving the rest unchanged. We could perhaps add references to where you find the correct Azure OpenAI API version for your model.

_Originally posted by @Xtrah in https://github.com/microsoft/autogen/pull/2923#pullrequestreview-2115030490_

**Comment by Deykeepcomn4me** [comment]
Bitch I am not spam. Spam doesn't respond this way.  These are hackers
hacking me please contact fbi asap they just keep creating name in my
account and my account needs to be closed

**Comment by qingyun-wu** [comment]
Hi @Xtrah, the suggested change makes sense. Would you like to make a PR? Thank you!
