### ISSUE TITLE
[Bug]: Typing mistake for ChatResult , resulting in a Pydantic UserWarning

### ISSUE THREAD

**Issue by alexandre-ist** [microsoft/autogen#2962]
### Describe the bug

Getting this Pydantic warning when using ChatResult as type:

> UserWarning: <built-in function any> is not a Python type (it may be an instance of an object), Pydantic will allow any object with no validation since we cannot even enforce that the input is an instance of the given type. To get rid of this error wrap the type with `pydantic.SkipValidation`.

### Steps to reproduce

Using ChatResult as a type for a variable in a Pydantic class 

```python
class MyClass(BaseModel):

    result: ChatResult
```

### Expected Behavior

The issue is a typing mistake in the ChatResult class in the chat.py file, chat_history variable, line 24:

```python
chat_history: List[Dict[str, any]] = None
```

proper typing should be instead:
```python
chat_history: List[Dict[str, Any]] = None
```

### Additional Information

autogen Version: 0.2.27
python 3.12.3

**Comment by Hk669** [comment]
good catch @alexandre-ist , thanks for raising the issue. the PR mentioned above should fix this warning from the pydantic.
