### ISSUE TITLE
[Bug]: Example04_Dynamic_GroupChat_Coding_Task throwing exception

### ISSUE THREAD

**Issue by teeshajain17** [microsoft/autogen#2970]
### Describe the bug

I was running this example in my system and it is throwing error.
https://github.com/microsoft/autogen/blob/ca4f7176169d5f40b5e7570aab7dce4a37bd088f/dotnet/sample/AutoGen.BasicSamples/Example04_Dynamic_GroupChat_Coding_Task.cs

### Model Used

gpt-3.5

### Expected Behavior

It shouldn't throw exception

### Screenshots and logs

![image](https://github.com/microsoft/autogen/assets/16876986/935f09ae-e381-43f2-830b-e7d6effacbb3)

Details:

System.InvalidOperationException
  HResult=0x80131509
  Message=Sequence contains no matching element
  Source=System.Linq
  StackTrace:
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at AutoGen.Core.GroupChat.<SelectNextSpeakerAsync>d__10.MoveNext()
   at AutoGen.Core.GroupChat.<CallAsync>d__12.MoveNext()
   at AutoGen.Core.AgentExtension.<SendMessageToGroupAsync>d__6.MoveNext()
   at AutoGen.Core.AgentExtension.<SendAsync>d__2.MoveNext()
   at AutoGen.Core.AgentExtension.<SendAsync>d__3.MoveNext()
   at Example04_Dynamic_GroupChat_Coding_Task.<RunAsync>d__0.MoveNext() in C:\Users\91701\source\repos\TestAutoGen\TestAutoGen\Example04_Dynamic_GroupChat_Coding_Task.cs:line 250
   at Program.<Main>d__0.MoveNext() in C:\Users\91701\source\repos\TestAutoGen\TestAutoGen\Program.cs:line 7

**Comment by LittleLittleCloud** [comment]
@teeshajain17 Your api-key is exposed in your previous screenshot, I just update the image to remove the api-key part. In the meantime, please deprecate your current api-key ASAP

**Comment by LittleLittleCloud** [comment]
@teeshajain17 Maybe try a better llm (gpt-4) and see if the error persist? Example-04 is one of the "challenging" tasks that may require a more powerful LLM to complete.

**Comment by teeshajain17** [comment]
Okay. let me try that.

**Comment by teeshajain17** [comment]
It worked. Thanks! Could you suggest a simple example that demonstrates the functionality of the group chat feature and can be accomplished by GPT-3.5?

**Comment by LittleLittleCloud** [comment]
@teeshajain17 Am working on it, you can track progress in #2859

**Comment by teeshajain17** [comment]
@LittleLittleCloud Can I help in any way? I would love to contribute.

**Comment by LittleLittleCloud** [comment]
@teeshajain17 Of course, I can add you as reviewer once the PR is ready. In the meantime the remaining imcomplete samples are the below two, let me know which one you want to take.
![image](https://github.com/microsoft/autogen/assets/16876986/e2ad504e-7f42-4960-b032-3c0d739c8db8)

Also feel free to edit the task list by adding the sample you want to create and assign that sample to yourself.

**Comment by teeshajain17** [comment]
I'm unsure about what to do exactly and how to create these sample examples because I've just started learning Autogen. However, please include me as a reviewer in the pull request.
