### ISSUE TITLE
[.Net] [Feature Request]:  Add ReAct sample

### ISSUE THREAD

**Issue by LittleLittleCloud** [microsoft/autogen#2978]

**Comment by qingyun-wu** [comment]
For your reference: this is an ReAct example with pyautogen: https://microsoft.github.io/autogen/docs/topics/prompting-and-reasoning/react

**Comment by LittleLittleCloud** [comment]
@qingyun-wu Thanks, there are slight difference on the purpose of the two examples thought. This example is to show how to implement ReAct as a single agent and the ReAct example in pyautogen uses two-agent chat conversation pattern.
