### ISSUE TITLE
openai.error.InvalidRequestError: This model maximum context length is 2048 tokens. However, your messages resulted in over 2133 tokens.

### ISSUE THREAD

**Issue by BenjiKCF** [microsoft/autogen#300]
I am using the text generation webui to run it locally, but the following error pops out. Do you guys have it? Thanks.

`openai.error.InvalidRequestError: This model maximum context length is 2048 tokens. However, your messages resulted in over 2133 tokens.`

**Comment by qingyun-wu** [comment]
Yes, there indeed could be a context overflow issue when the conversation context becomes long. Multiple community members are trying to figure out possible solutions. Could you first read discussions in this roadmap item (see if any of the workaround there could be helpful in your case) and keep an eye on further updates from there: https://github.com/orgs/microsoft/projects/989?pane=issue&itemId=41137238

Thank you!

**Comment by sonichi** [comment]
@qingyun-wu This could be a different issue about misconfiguration (the model's context length is > 2048) as I've seen discussions on discord.

**Comment by Ionaut** [comment]
I am having the same issue with a 13B local model with a 4096 context length. I've tried setting max_tokens to 1792 and then in oogabooga setting the 'Truncate the prompt up to this length' to 1792 to split the difference and leave a little for system tokens and it still eventually hits a wall when the message exceeds context length.

**Comment by bendreality** [comment]
For those who use text-generation-web-ui: It's not a context overflow issue of autogen. It's an issue with text-generation-web-ui. 

When you start oogabooga with the OpenAi Extention activated it pulls it's default settings from the file 'modules/shared.py'. The standard value of 'truncation_length' is set to 2048. Even if I change the value in the UI the variable for the OpenAi API calls is not updated. 

My quick fix ist to change it inside the file by setting 'truncation_length': 8192, (line 43)

I'm short on time.  Would be great if someone could verify and open an issue in the "text-generation-web-ui" git-Repo. 

happy generating. :)

**Comment by adrianfiedler** [comment]
> For those who use text-generation-web-ui: It's not a context overflow issue of autogen. It's an issue with text-generation-web-ui.
> 
> When you start oogabooga with the OpenAi Extention activated it pulls it's default settings from the file 'modules/shared.py'. The standard value of 'truncation_length' is set to 2048. Even if I change the value in the UI the variable for the OpenAi API calls is not updated.
> 
> My quick fix ist to change it inside the file by setting 'truncation_length': 8192, (line 43)
> 
> I'm short on time. Would be great if someone could verify and open an issue in the "text-generation-web-ui" git-Repo.
> 
> happy generating. :)

You saved my day Mr. genious!

**Comment by thinkall** [comment]
Resolved.
