### ISSUE TITLE
[Issue]: How to make AutoGen stop outputting ">>>>>>>> EXECUTING ASYNC FUNCTION function_name..."

### ISSUE THREAD

**Issue by tyler-suard-parker** [microsoft/autogen#3039]
### Describe the issue

I don't want this to be in my output, but I can't figure out where to shut it off.  I can't find ">>>> EXECUTING ASYNC FUNCTION" anywhere in the code except for in the notebooks.  How do I turn it off?

### Steps to reproduce

Run any autogen agent with functions

**Comment by yonitjio** [comment]
Here: https://github.com/microsoft/autogen/blob/main/autogen%2Fagentchat%2Fconversable_agent.py#L2298

**Comment by tyler-suard-parker** [comment]
@yonitjio Thank you!
