### ISSUE TITLE
Add the roadmap to the documentation website

### ISSUE THREAD

**Issue by qingyun-wu** [microsoft/autogen#305]
Thanks @gagb! The revision in readme looks good to me. Shall we also add the roadmap to the documentation website as well? (This could be done in another PR). It could be added to the "[Where to Go Next](https://microsoft.github.io/autogen/docs/Getting-Started#where-to-go-next)" tab in the Getting Started page.

_Originally posted by @qingyun-wu in https://github.com/microsoft/autogen/pull/304#pullrequestreview-1688373136_

**Comment by Gourav2609** [comment]
@qingyun-wu can i work in this issue

**Comment by Gourav2609** [comment]
![image](https://github.com/microsoft/autogen/assets/115522947/c188f536-40a6-4183-b707-705092919242)

do i just have to add one more points as ROADMAP( with the link ) beneath Where to go next

**Comment by qingyun-wu** [comment]
Thanks. I will assign this to you! Maybe add the point between "learn about research around AutoGen" and "Chat on Discord".

**Comment by Gourav2609** [comment]
@qingyun-wu Please review the PR #324
