### ISSUE TITLE
[Question] Generative Agents

### ISSUE THREAD

**Issue by austinmw** [microsoft/autogen#3096]
Hi, I'm curious if there are any examples or planned work in the direction of using AutoGen to create believable generative agents for simulation purposes, similar to [AI Town](https://github.com/a16z-infra/ai-town) and the [Concordia](https://github.com/google-deepmind/concordia) library, rather than focusing on assistants and task completion.

**Comment by Hk669** [comment]
here is the discord link: https://discord.gg/95YFGuJ4
feel free to join our discord to find good amount of examples, that are created with AutoGen. thanks @austinmw
