### ISSUE TITLE
Update documentation how to install autogenstudio from the source code for windows users. 

### ISSUE THREAD

**Issue by andrei-galkin-thales** [microsoft/autogen#3110]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/microsoft/autogen/assets/141173037/0a4d6ed6-2731-4d48-b6cd-ee34f9f3ceed)

Please update this part of the doc for windows users. I could not succeed with the installation from source code.

### Describe the solution you'd like

I would be glad to have more details how to do the installation from the source code.

**Comment by jackgerrits** [comment]
Without knowing what failed for you when you followed the existing instructions for installing from source on Windows we aren't able to assist. 

If you are still having issues, please reopen this with the error that you faced.
