### ISSUE TITLE
[Issue]: .NET nightly NuGet feeds do not appear to provide daily builds

### ISSUE THREAD

**Issue by MarkWard0110** [microsoft/autogen#3116]
### Describe the issue

I have set up my NuGet.config source for "https://www.myget.org/F/agentchat/api/v3/index.json" and the latest version is 0.0.15-nightly-9735721869 Published June 30, 2024.
Today is July 11, 2024.
The release before that was published on June 10, 2024.

What other approaches could I use to work with the latest builds of .NET AutoGen?

In addition, when I tried to use the GitHub feed https://nuget.pkg.github.com/microsoft/index.json when installing the AutoGen package, I would get an error for some of the AutoGen dependency packages "not found".

### Steps to reproduce

Configure a NuGet.config or source with one of the feeds.
Review the metadata for the AutoGen package.

### Screenshots and logs

![image](https://github.com/microsoft/autogen/assets/90335263/636fccdc-25d5-41a3-aef9-f9ec51ad12e9)

**Comment by LittleLittleCloud** [comment]
pushed
