### ISSUE TITLE
[Issue]:  AutoGen is the copy of CAMEL?

### ISSUE THREAD

**Issue by hijkzzz** [microsoft/autogen#3159]
### Describe the issue

From "机器之心" blog: https://36kr.com/p/2865862419762049

**Comment by qingyun-wu** [comment]
Hi @hijkzzz, ABSOLUTELY NOT! They are all open-source projects. Any reasonable person who spends some time reading the two papers, using the two libraries, or diving a little into the code knows the differences! Some people are just trying to get cheap traffic by distributing misinformation! Shame on 机器之心 for reporting such self-made drama, by the way!

If you are interested in using or contributing to our project, we welcome you wholeheartedly! If you have specific questions on any technical matters, we'd love to address them! We are not interested in getting dragged into such meaningless, unproductive, and self-made drama!

**Comment by LittleLittleCloud** [comment]
你好，作为AutoGen团队的一员，简单的回答以下你的疑问

利益相关：AutoGen contributor

## 首先，AutoGen的立项时间比你想象的要早些

AutoGen最早的代码是在Flaml里面，第一个PR如下

- [autogen subpackage by sonichi · Pull Request #968 · microsoft/FLAML · GitHub](https://github.com/microsoft/FLAML/pull/968)

其中第一个commit的日期是2023 3月30日

而CAMEL的第一个commit是在2023年3月17日，这个也可以在CAMEL的repo上查到。

所以我觉得AutoGen和CAMEL是同时期的工作，并不存在谁比谁先的问题


## 其次，AutoGen不存在借鉴CAMEL的情况。

以group chat为例子：AutoGen的Group Chat是来自多个作者的，包括我在内其实都做过相关的探索。我在Multi-Agent-UI里面就探索过类似于AutoGen的group chat，以下是相关commit。日期是 2023 4/23
- [add chat · LittleLittleCloud/chatbot-ui@3cc446f (github.com)](https://github.com/LittleLittleCloud/chatbot-ui/commit/3cc446fd101bd139c8b0d98baa0ed68701840118#diff-b0e0d86a87d9e95dd84dd2aa97944b789f5c9de69c135e878a2669a32ac7d1d5R55)

基于以上两点，我觉得称AutoGen和CAMEL都为同时期的工作，是恰当的说法。但是AutoGen借鉴CAMEL的说法，是不恰当的。

## 为什么没有正式引用
再次澄清一下，从论文第一版 （https://arxiv.org/pdf/2308.08155/v1） 到最新版本(https://openreview.net/pdf?id=uAjxFFing2) ，我们一直有引用以及讨论CAMEl。唯一的争议就是在ICLR投稿的版本，由于考虑到投稿页数限制，我们将相关文献的详细讨论放到了论文附录（注意：即使这样被引用的论文也是一样会出现在参考文献的目录中）。收到ICLR评审员的意见后，已经将附录中的部分讨论移到了正文中。”

## 最后再说两句

做开源不容易，在AI这个飞速变化的领域里做开源更不容易。作为AutoGen团队的一员，我还是更希望把注意力多放在项目和代码，解决更多的issue上。

Happy coding

**Comment by hijkzzz** [comment]
你们第一个 commit 啥都没有啊： https://github.com/microsoft/FLAML/pull/968/commits/bc3c2fba5b45b882cbb619f4275f0c92c6ff6e68

**Comment by LittleLittleCloud** [comment]
这并不能说明什么，Agent并不是一个新的概念。我又翻了一下CAMEL的仓库，发现了几个有趣的地方

举个例子，autogen的code-executor功能是2023 april 7加入的，我检查了一下CAMEL 2023年四月七号的代码库，并没包含代码执行的功能
- 相关PR： https://github.com/microsoft/FLAML/pull/968/files#diff-8e5940046b36b13b608bd2ae7b8b6cd85be13ea441441da74c107ffd74cbf58a

再举一个例子，AutoGen的multi-agent chat在8月release的时候就支持了。我搜索了一下CAMEL的仓库，“恰好”有类似的PR，只是现在还没有merge
- https://github.com/camel-ai/camel/pull/390

如此重复的功能，AutoGen也没有说CAMEL抄袭，对吧。那为什么CAMEL一直在说AutoGen抄他们的呢，为什么不想想CAMEL这么做背后的原因。

**而且，AutoGen并非没有引用CAMEL，相关内容我之前发过了，在此不做赘述。**

抄袭是个非常严重的指控，要慎重。

## English version

This doesn't prove anything; the concept of an Agent is not new.

For example, the code-executor feature in AutoGen was added on April 7, 2023. I checked the CAMEL codebase from April 7, 2023, and it didn't include the code execution feature.
- Relevant PR: [Link to PR](https://github.com/microsoft/FLAML/pull/968/files#diff-8e5940046b36b13b608bd2ae7b8b6cd85be13ea441441da74c107ffd74cbf58a)

Another example is the multi-agent group chat feature in AutoGen, which was supported when it was released in August. I searched the CAMEL repository and found a similar PR that just hasn't been merged yet.
- [Link to PR](https://github.com/camel-ai/camel/pull/390)

AutoGen didn't accuse CAMEL of plagiarism despite the overlapping features. So why does CAMEL keep accusing AutoGen of copying them? Why not consider the reasons behind this?

Moreover, AutoGen has cited CAMEL, as I mentioned before, and I won't elaborate on that here.

Plagiarism is a very serious accusation and should be made cautiously.
