### ISSUE TITLE
[.Net][Issue]: Invoking functions and streaming result not working

### ISSUE THREAD

**Issue by ThirstyJarek** [microsoft/autogen#3160]
### Describe the issue

Using the autogen .NET SDK and trying to get an OpenAIChatAgent to invoke a function and stream the results back, but we cannot get it to work. 

Following this [documentation](https://microsoft.github.io/autogen-for-net/articles/OpenAIChatAgent-use-function-call.html) we can get the agent to invoke functions successfully.

Following this [documentation](https://microsoft.github.io/autogen-for-net/articles/OpenAIChatAgent-simple-chat.html), we can get the results to stream back when sending normal messages to the agent successfully.

However, combining these two examples leads to issues. I also note the function call documentation does not mention or have examples of streaming the results of a function call, whereas a lot of the other .NET documentation does show an example of how to stream, which makes me think its possibly not yet supported.

Does anyone have any examples of this working? Or does anyone know if invoking functions and streaming the results are perhaps not supported yet by autogen for .NET?

### Steps to reproduce

Create the agent - FunctionCallMiddleware contains a single function that returns an async IAsyncEnumerable<string>
```
var openAIAgent = new OpenAIChatAgent(...)
.RegisterMessageConnector(new OpenAIChatRequestMessageConnector())
.RegisterStreamingMiddleware(functionCallMiddleware);
```

Use the streaming call instead of SendAsync()
```
var chatMessageContent = MessageEnvelope.Create(new ChatRequestUserMessage(userMessage));
var responseStream2 = openAIAgent.StreamingAgent.GenerateStreamingReplyAsync([chatMessageContent], cancellationToken: cancellationToken);
```

Iterate over the result stream
```
await foreach (var streamingReply in responseStream2)
{

}
```
This result stream doesn't invoke the function anymore. Instead, it returns a ToolCallAggregateMessage, but the function result is just the full class name like '`Project.Code.Plugin.<FunctionName> d__7`'

**Comment by LittleLittleCloud** [comment]
@ThirstyJarek

Even though the response from function call won't be streaming, it should still return the final `ToolCallAggregateMessage` as the only chunk.

May i know which model are you using?

BTW here is an example of streaming function call
```csharp
// Copyright (c) Microsoft Corporation. All rights reserved.
// Streaming_Tool_Call.cs

using AutoGen.Core;
using AutoGen.OpenAI;
using AutoGen.OpenAI.Extension;
using Azure.AI.OpenAI;
using FluentAssertions;

namespace AutoGen.BasicSample.GettingStart;

public partial class Tools
{
    /// <summary>
    /// Get the weather of the city.
    /// </summary>
    /// <param name="city"></param>
    [Function]
    public async Task<string> GetWeather(string city)
    {
        return $"The weather in {city} is sunny.";
    }
}

internal class Streaming_Tool_Call
{
    public static async Task RunAsync()
    {
        var tools = new Tools();

        var autoInvokeMiddleware = new FunctionCallMiddleware(
            functions: [tools.GetWeatherFunctionContract],
            functionMap: new Dictionary<string, Func<string, Task<string>>>()
            {
                { tools.GetWeatherFunctionContract.Name!, tools.GetWeatherWrapper },
            });

        var apiKey = Environment.GetEnvironmentVariable("OPENAI_API_KEY") ?? throw new Exception("Please set OPENAI_API_KEY environment variable.");
        var model = "gpt-3.5-turbo";
        var openaiClient = new OpenAIClient(apiKey);
        var agent = new OpenAIChatAgent(
            openAIClient: openaiClient,
            name: "agent",
            modelName: model,
            systemMessage: "You are a helpful AI assistant")
            .RegisterMessageConnector()
            .RegisterStreamingMiddleware(autoInvokeMiddleware);

        IMessage finalReply = null;
        var chatMessageContent = MessageEnvelope.Create(new ChatRequestUserMessage("what's the weather in Seattle?"));
        await foreach (var message in agent.GenerateStreamingReplyAsync([chatMessageContent]))
        {
            finalReply = message;
        }

        finalReply?.GetContent().Should().Be("The weather in Seattle is sunny.");
    }
}

```
