### ISSUE TITLE
[Bug]: Faulty calculation of custom pricing

### ISSUE THREAD

**Issue by r4881t** [microsoft/autogen#3165]
### Describe the bug

With the openai gpt-4o-mini, I went ahead and tried setting the price param as 

```
model_4o = "gpt-4o-mini"
llm_config_4o = {
  "config_list": [{"model": model_4o, "api_key": os.environ["OPENAI_API_KEY"]}],
  "stream": False,
  "temperature": 0,
  "cache_seed": 20,
  "timeout": 300,
  "max_tokens": 3 * 1024,
  "price": [0.00015, 0.0006],
}
```

Since it's mentioned that the price should be price per 1k tokens. However soon I noticed that the price it shows is quite high. So i went deeper and found that the code commited via https://github.com/microsoft/autogen/pull/2902 contains a bug. Specifically at https://github.com/microsoft/autogen/blob/0cdbc345c56aa0708eb4a15ee70d87b17b5dc0d4/autogen/oai/client.py#L798 where it multiplies price per 1k with the actual number of tokens. Thus gicing wrong value. To fix this I have changed the price to be price per token in my llm config, but the code needs to be updated so that people dont face this issue.

### Expected Behavior

The price should be computed as price per 1k token

**Comment by yiranwu0** [comment]
Yes, thanks! I will submit a PR for this.
