### ISSUE TITLE
[Bug]: register_function is not worked.

### ISSUE THREAD

**Issue by RyanOvO** [microsoft/autogen#3189]
### Describe the bug

I tried it locally with the [react ](https://microsoft.github.io/autogen/docs/topics/prompting-and-reasoning/react) documentation and register_function didn't work at all. Here is my code, which is actually the documentation:
![image](https://github.com/user-attachments/assets/5e8ac563-ecbc-4a68-87d5-fe62df6d1187)
![image](https://github.com/user-attachments/assets/c9eff92d-a1fa-4ef1-aa1e-810c963c0fe5)
But in my output, there's no call to the function I registered, there is log:
![image](https://github.com/user-attachments/assets/3f0b1404-8217-4615-9b71-09e5e7636e60)

**My Guess:  Does autogen not support tools call for VLLM-deployed services?**

### Steps to reproduce

Just refer to the code in the [react](https://microsoft.github.io/autogen/docs/topics/prompting-and-reasoning/react) documentation

### Model Used

model: glm4-9b
inference: vllm-0.5.1

### Expected Behavior

None

### Screenshots and logs

None

### Additional Information

python 3.10

**Comment by marklysze** [comment]
Hey @RyanOvO, I'd say it's likely that the model is not doing tool calling with vllm. I noticed [this comment regarding vLLM tool calling](https://github.com/runpod-workers/worker-vllm/issues/85#issuecomment-2253540467).

Can you try the currency calculator documentation example here to double-check:
https://microsoft.github.io/autogen/docs/notebooks/agentchat_function_call_currency_calculator

The way to register functions has changed a bit as well, the currency calculator shows the current way.

If you are able to use Ollama and a model like Llama 3.1, an active PR for an Ollama client is underway and tool calling does work in that. See #3056.

**Comment by RyanOvO** [comment]
> Hey @RyanOvO, I'd say it's likely that the model is not doing tool calling with vllm. I noticed [this comment regarding vLLM tool calling](https://github.com/runpod-workers/worker-vllm/issues/85#issuecomment-2253540467).
> 
> Can you try the currency calculator documentation example here to double-check: https://microsoft.github.io/autogen/docs/notebooks/agentchat_function_call_currency_calculator
> 
> The way to register functions has changed a bit as well, the currency calculator shows the current way.
> 
> If you are able to use Ollama and a model like Llama 3.1, an active PR for an Ollama client is underway and tool calling does work in that. See #3056.

ok, thks.

**Comment by TimPietrusky** [comment]
@marklysze vLLM will receive `tool_choice="auto"` with https://github.com/vllm-project/vllm/pull/5649. I guess this is what is missing here, as `tools` in general are supported by vLLM.

**Comment by marklysze** [comment]
> @marklysze vLLM will receive `tool_choice="auto"` with [vllm-project/vllm#5649](https://github.com/vllm-project/vllm/pull/5649). I guess this is what is missing here, as `tools` in general are supported by vLLM.

Hi @TimPietrusky, thanks for the note - do you think adding that parameter to the config will fix it?

**Comment by TimPietrusky** [comment]
@marklysze I haven't used autogen yet, but I made some assumptions based on the things I know:

* vLLM does provide an OpenAI-compatible API (fact)
* autogen is using the OpenAI-compatible API (assumption)
* `tool_choice="auto"` is the [default value for function-calling for OpenAI when `tools` are present](https://platform.openai.com/docs/api-reference/chat/create#chat-create-tool_choice) (fact)
* autogen does expect the default value `auto` in vLLM (assumption), but this is not implemented yet in vLLM (fact)
* Right now you can only use `tool_choice` by specifing `none` (no tool call) or the name of the tool you want to use

So if these assumptions are correct, then I totally think that the mentioned PR will actually resolve this problem.

**Comment by K-Mistele** [comment]
Not familiar with autogen either,  but this seems correct once the PR ships (sorry I know it's taking a while ☠️) as long as you have the correct chat template and tool parser configured. Happy to clarify/help as best as I can :)
