### ISSUE TITLE
[Bug]: Bug when using anthropic bedrock 

### ISSUE THREAD

**Issue by Au233** [microsoft/autogen#3198]
### Describe the bug

Hi, I cloned the latest version of your autogen repository and packaged it for use, to utilize the newly added Anthropics Bedrock interface. I discovered several bugs during the process, which I would like to provide for your reference:
(1) Regarding the configuration file of Anthropics Bedrock , aws_session_token is not mandatory. Therefore, in line 111 of the code located at [./autogen/autogen/oai/anthropic.py](https://github.com/microsoft/autogen/blob/b7bdbe1ecc1c00abd5172f472c6051d0230249bd/autogen/oai/anthropic.py#L111), it is unnecessary to check its value.
(2) In line 490 of [/maindata/data/user/qiaoqiao.jin/3DGPT/autogen/autogen/oai/client.py](https://github.com/microsoft/autogen/blob/b7bdbe1ecc1c00abd5172f472c6051d0230249bd/autogen/oai/client.py#L490), the input should be config instead of openai_config, as openai_config is None at that point.

**Comment by Hk669** [comment]
@Au233 thanks for spotting the bug. making a PR on this. feel free to review it and let us know your thoughts. thanks

**Comment by wenngong** [comment]
I have submit a PR: #3200 for this issue. Please review.

**Comment by marklysze** [comment]
Hi all, @Hk669, @Au233, @wenngong - I'll close this as #3210 has been merged. Please re-open if it is still an issue.
