### ISSUE TITLE
[Issue]:   TypeError: 'ChatResult' object is not subscriptable

### ISSUE THREAD

**Issue by Adibahaq** [microsoft/autogen#3225]
### Describe the issue

This is an Autogen issues. 
I am trying to iterate the last response from an agent and find certain words in the response. But the ChatResult cannot be iterated or accessed just to check
if "Medicine A" in response['content']:
   #do something here
else .............

Can anyone please tell me what the right way is to do this?

**Comment by marklysze** [comment]
Hey @Adibahaq, would you be able to provide a short AutoGen code example?

**Comment by Adibahaq** [comment]
Hi Mark,
I solved this issue. Thank you!
