### ISSUE TITLE
[Issue]: Qdrant Retrieval Not working

### ISSUE THREAD

**Issue by teyang-lau** [microsoft/autogen#3230]
### Describe the issue

Qdrant client does not have config for embedding model vector size.

### Screenshots and logs

Code: 
```

rag_agent = QdrantRetrieveUserProxyAgent(
    name="assistant",
    description="Assistant who has extra content retrieval power for finding the right topics.",
    human_input_mode="NEVER",
    retrieve_config = {
        "task": "qa",
        "client": qdrant_client,
        "collection_name": COLLECTION_NAME,
        "embedding_model": "BAAI/bge-base-en-v1.5"
    }, 
    code_execution_config=False,
)
```

```
rag_agent.retrieve_docs(problem="deep learning", n_results=3)
```

Error:

```
UnexpectedResponse: Unexpected Response: 400 (Bad Request)
Raw response content:
b'{"status":{"error":"Wrong input: Vector params for fast-bge-base-en-v1.5 are not specified in config"},"time":0.000074985}'
```

### Additional Information

In autogen/agentchat/contrib/qdrant_retrieve_user_proxy_agent.py

```
if client is None:
        client = QdrantClient(**qdrant_client_options)
        client.set_model(embedding_model)

```

client.set_model(embedding_model) is only set when the client is set to None, which causes the qdrant_client to not have the config vector size params for the embedding model

```
if client is None:
        client = QdrantClient(**qdrant_client_options)
client.set_model(embedding_model)
```

should fix it

**Comment by thinkall** [comment]
Hi @teyang-lau , `QdrantRetrieveUserProxyAgent` has limited customization support, could you set up the client and pass it in? 

In the next release `v0.2.33` (currently in main) , we'll add support to use qdrant db in `RetrieveUserProxyAgent` and you can pass in more kwargs into embedding model as it's implemented with `self._model = TextEmbedding(model_name=model_name, cache_dir=cache_dir, threads=threads, **kwargs)`

Please let me know if this addresses your ask? Thanks.

**Comment by teyang-lau** [comment]
@thinkall, thanks for the reply. Yup this addresses it. Thank you!
