### ISSUE TITLE
[Issue]: Observability Blog Post Image Sizing Issues

### ISSUE THREAD

**Issue by areibman** [microsoft/autogen#3233]
### Describe the issue

Due to the way Docusaurus renders images, I undersized several of the photos in the blog post.

Before (40% width)
<img width="798" alt="image" src="https://github.com/user-attachments/assets/54654606-9234-4bab-b9fc-9a52c37b16ea">

Proposed (100% width)
<img width="666" alt="image" src="https://github.com/user-attachments/assets/dc88a42b-9c68-4b0d-8046-4fd04edfd9a0">

By updating the MDX to change back to 100% width, this will make the images much easier to read.

### Steps to reproduce

See: https://microsoft.github.io/autogen/blog/2024/07/25/AgentOps

**Comment by marklysze** [comment]
@qingyun-wu, @areibman has updated the blog post in regards to the image sizes and it's now rending images full-width. If you could merge that would be great! #3234

I'll close this issue.
