### ISSUE TITLE
Add an example of Vowpal Wabbit + AutoGen

### ISSUE THREAD

**Issue by gagb** [microsoft/autogen#326]
Add an example of using VW with AutoGen to showcase agents that adapt using reinforcement learning.

**Comment by gagb** [comment]
@marco-rossi29 @olgavrou @qingyun-wu you all maybe working on similar features and may want to sync up: https://github.com/microsoft/autogen/issues/522

**Comment by olgavrou** [comment]
Still in draft mode but some initial work of what this might look like can be found [here](https://github.com/VowpalWabbit/autogen/pull/1):
