### ISSUE TITLE
[Issue]: How can I access follow-up questions from the assistant when human input is set to ALWAYS? Currently, it only interacts via the terminal.

### ISSUE THREAD

**Issue by Venkysanju246** [microsoft/autogen#3326]
### Describe the issue

When I set human input to ALWAYS, I was able to interact via the terminal. How do I make this available to the web UI or frontend?

**Comment by Gr3atWh173** [comment]
One way is to TERMINATE on human input, then resume the chat with the additional human input included

**Comment by xin-ran-w** [comment]
The same issue, I now want to predefine multi-turn inputs for humans to make the conversation between humans and machines automatic. Is there a way to predefine the response for an agent?

**Comment by ekzhu** [comment]
@Venkysanju246 for UI integration, we will be adding documentation in the v0.4 (preview). 

@xin-ran-w. In the v0.2 version, you can register reply functions to customize agent responses. https://microsoft.github.io/autogen/0.2/docs/reference/agentchat/conversable_agent#register_reply. In the v0.4 preview, you are just write Python code to define your agent's message handler and take pre-defined responses.
