### ISSUE TITLE
[.Net][Feature Request]: Support prompt cache in claude

### ISSUE THREAD

**Issue by LittleLittleCloud** [microsoft/autogen#3359]
### Is your feature request related to a problem? Please describe.

Claude now support prompt cache, which dramastically lower the bill if cache is hit.

https://www.anthropic.com/news/prompt-caching

### Describe the solution you'd like

Add the corresponding option in claude client

**Comment by marklysze** [comment]
Very cool feature. Would be good to update the Anthropic client class in Python as well. I'll try and get that done.
