### ISSUE TITLE
Used by

### ISSUE THREAD

**Issue by sonichi** [microsoft/autogen#337]
The "Used by" displayed in the GitHub home page is not accurate. It refers to the dependency of the repo and not the pyautogen package. The dependents of the pyautogen package are displayed in https://github.com/microsoft/autogen/network/dependents?package_id=UGFja2FnZS0zOTA3NzUyNDI4.

Is there a way to change the "Used by" section in the GitHub home page? If not, shall we add a link in the README to the actual dependents?

**Comment by Gourav2609** [comment]
@sonichi https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/exploring-the-dependencies-of-a-repository

does this help

**Comment by rabbabansh** [comment]
![image](https://github.com/microsoft/autogen/assets/31804810/f6840595-33f3-49ac-abaf-025968454877)

Link: https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/exploring-the-dependencies-of-a-repository#changing-the-used-by-package

I think this will help!

**Comment by sonichi** [comment]
@rabbabansh @Gourav2609 Thank you both for the help. Problem is solved 😄

**Comment by rabbabansh** [comment]
Kudos!
