### ISSUE TITLE
[Feature Request] Amazon Bedrock support?

### ISSUE THREAD

**Issue by austinmw** [microsoft/autogen#339]
Hi, would it be possible to add support for Amazon Bedrock LLMs?

**Comment by gagb** [comment]
@austinmw this PR is still unresolved but might be worth checking out https://github.com/microsoft/autogen/pull/95

**Comment by sebandres** [comment]
Does anyone know if there is interest in a native implementation of Bedrock? (Instead of using LiteLLM as proposed on the PR mentioned above)
I was planning on tackling one as I haven't found anything along those lines.
Not sure I like the idea of introducing yet another layer of abstraction to my stack.

**Comment by ekzhu** [comment]
Implementing a custom client is a good start. See https://microsoft.github.io/autogen/docs/topics/non-openai-models/cloud-anthropic

**Comment by jtlz2** [comment]
@sebandres How are you getting on ? :)

**Comment by sebandres** [comment]
Hey @jtlz2 ! I ended up implementing a version the TextMessage that leverages Bedrock but after doing it didn't really agree with some of the patterns used to implement the sdk so opted for a clean architecture version that does Agent choreography instead of orchestration so ended up not pursuing this any further.

**Comment by Aspen68** [comment]
I've made a quick fix in case anyone still needs this, contact me on discord (aspen68). It's not clean what so ever but it works. All I've done is modify the anthropic.py file to utilize a bedrock client so it can easily be used in lambda. Nevertheless if someone is interested in it send me a message

**Comment by makkzone** [comment]
I [added](https://github.com/microsoft/autogen/pull/3103) for the anthropic models available through bedrock.

You can pull from [here](https://github.com/makkzone/autogen) until the merge is done to main branch.

Below is the example usage

import autogen
config_list = [
{
"model": "anthropic.claude-3-5-sonnet-20240620-v1:0",
"aws_access_key":accessKey,
"aws_secret_key":secretKey,
"aws_session_token":sessionTok,
"aws_region":"us-east-1",
"api_type": "anthropic",
}
]
assistant = autogen.AssistantAgent("assistant", llm_config={"config_list": config_list})

**Comment by joris-swapfiets** [comment]
@makkzone I only got your solution to work after changing line 490 in file: `autogen/oai/client.py` from:
```                client = AnthropicClient(**openai_config)```
to
```                client = AnthropicClient(**config)```

**Comment by Sanjay3739** [comment]
> Hi, would it be possible to add support for Amazon Bedrock LLMs?

app = FastAPI()

bedrock = boto3.client(
    service_name='bedrock-runtime',
    region_name=os.getenv('REGION'),
    aws_access_key_id=os.getenv('AWS_ACCESS_KEY_ID'),
    aws_secret_access_key=os.getenv('AWS_SECRET_ACCESS_KEY')
)

@app.post("/v1/chat/completions")
async def create_chat_completion(request: Request):
    try:
        data = await request.json()
        messages = data.get('messages', [])
        max_tokens = data.get('max_tokens', 100)
        temperature = data.get('temperature', 0.7)

        prompt = "\n".join([f"{m['role']}: {m['content']}" for m in messages])
        
        body = {
            "prompt": prompt,
            "temperature": temperature,
            "max_gen_len": max_tokens,  # Use max_gen_len instead of max_tokens
        }

        response = bedrock.invoke_model(
            modelId=model_id,
            body=json.dumps(body)
        )

        response_body = json.loads(response['body'].read())
        
        return {
            "id": "chatcmpl-" + str(uuid.uuid4()),
            "object": "chat.completion",
            "created": int(time.time()),
            "model": data.get('model'),
            "choices": [
                {
                    "index": 0,
                    "message": {
                        "role": "assistant",
                        "content": response_body['generation'],
                    },
                    "finish_reason": "stop"
                }
            ],
            "usage": {
                "prompt_tokens": len(prompt.split()),
                "completion_tokens": len(response_body['generation'].split()),
                "total_tokens": len(prompt.split()) + len(response_body['generation'].split())
            }
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
 this work using bedrock api.
