### ISSUE TITLE
"Max token was set to xxxxx , but gpt-3.5-turbo-0613 can only accept 4096 tokens. Capping it to 4096" while using a local model

### ISSUE THREAD

**Issue by Zakk-Yang** [microsoft/autogen#3390]
### Describe the bug

i am using llama3.1 70b with ollama which has a extreamly large context window. When I set the MessageTokenLimiter, it assumes that i am using gpt-3.5-turbo-0613 which i am not. I got the error like the title. Following is the config:
```
    {
        "model": "local-model",
        "api_key": "NULL",
        "price": [0, 0], 
        "base_url": "http://0.0.0.0:4000",
        "max_tokens": 128000
    }
]
```
The base_url here is to use litellm. 

So how can i overide it to get full benefit of large local models.

Thanks.

### Steps to reproduce

```
context_handling = transform_messages.TransformMessages(
    transforms=[
        transforms.MessageHistoryLimiter(max_messages=20),
        transforms.MessageTokenLimiter(max_tokens=10000, max_tokens_per_message=5000, min_tokens=20),
    ]
)
```
This will result error of:
```
Max token was set to 10000, but gpt-3.5-turbo-0613 can only accept 4096 tokens. Capping it to 4096.
```

### Model Used

llama3.1:70b in ollama

### Expected Behavior

This info should not be shown as i have defined the max tokens that is not from gpt models.

### Screenshots and logs

![image](https://github.com/user-attachments/assets/35364c09-e9f4-4fd8-91cd-4911227db651)

**Comment by ruhanaazam** [comment]
Also getting this issue!

**Comment by peterychang** [comment]
Looks like the default model for token calculation function calls (the calls in `token_count_utils.py`) default to `gpt-3.5-turbo-0613`.

For GPT models, please make sure the correct model version is being passed into the function calls. We'll need to do something for local models though

**Comment by peterychang** [comment]
> Also getting this issue! Except my models are set to gpt-4-turbo-preview.

The call when using gpt-4-turbo-preview should look like

```
context_handling = transform_messages.TransformMessages(
    transforms=[
        transforms.MessageHistoryLimiter(max_messages=20),
        transforms.MessageTokenLimiter(max_tokens=10000, max_tokens_per_message=5000, min_tokens=20, model="gpt-4-turbo-preview"),
    ]
)
```

**Comment by peterychang** [comment]
@Zakk-Yang 

If you pass your model name (in this case, "local-model") into the MessageTokenLimiter per my previous comment, it will effectively disable the max token limit checking logic
