### ISSUE TITLE
[Issue]: Please provide latest pypi release of `autogen-studio` 

### ISSUE THREAD

**Issue by hemangjoshi37a** [microsoft/autogen#3449]
### Describe the issue

`autogen-studio`  is outdated in the pypi or pip version. there are so many latest developments in the current state. please bump the version to latest developments .

**Comment by Hk669** [comment]
@victordibia

**Comment by victordibia** [comment]
@hemangjoshi37a , @Hk669 

Thanks for the issue and tag!
I have just created a [release on pypi](https://pypi.org/project/autogenstudio/) `v0.1.15` .

Let me know if there any issues you see.
-V

**Comment by Hk669** [comment]
> @hemangjoshi37a , @Hk669
> 
> Thanks for the issue and tag! I have just created a [release on pypi](https://pypi.org/project/autogenstudio/) `v0.1.15` .
> 
> Let me know if there any issues you see. -V

@victordibia thanks for quick reply.

**Comment by hemangjoshi37a** [comment]
@victordibia thanks for the quick response. i would like the studio to get developed more .
