### ISSUE TITLE
[Question]: Using vLLM to build GroupChat

### ISSUE THREAD

**Issue by wxl-lxw** [microsoft/autogen#3458]
### Describe the issue

Hi there! Your work is inspiring, but may I ask if there any examples about how to use vLLM to build GroupChat?

I can only find a simple [example](https://github.com/microsoft/autogen/blob/main/website/docs/topics/non-openai-models/local-vllm.md) about leveraging vLLM-powered application, which only supports simple chat form: 'user/assistant/user/assistant/...'

**Comment by Hk669** [comment]
you can try the existing groupchat notebooks/tutorials with the `config_list` mentioned in the above mentioned example.
https://microsoft.github.io/autogen/docs/notebooks

**Comment by marklysze** [comment]
Thanks @Hk669, @wxl-lxw you can also look at specific group chat examples in [this section](https://microsoft.github.io/autogen/docs/Examples#multi-agent-collaboration-3-agents).

**Comment by wxl-lxw** [comment]
Thanks!
