### ISSUE TITLE
[Bug]: Cannot create Agent in Autogen Studio

### ISSUE THREAD

**Issue by goyaweb** [microsoft/autogen#3489]
### Describe the bug

Getting error when trying to create my first agent.

### Steps to reproduce

I'm a newbie, just installed autogenstudio but running into errors when trying to create an agent.
Step 1: hit + Create Agent button
Step 2: choose any of the 3 options
Step 3: accept all default configurations
Step 4: Hit "Create Agent"
Result:  A red cross will appear in notification style with message "Agent Created Succesfully"
VS Code console will show:

> Error while updating Agent: (builtins.TypeError) Object of type AgentConfig is not JSON serializable
> [SQL: INSERT INTO agent (created_at, updated_at, user_id, version, type, config, task_instruction) VALUES (?, ?, ?, ?, ?, ?, ?)]
> [parameters: [{'type': <AgentType.groupchat: 'groupchat'>, 'user_id': 'guestuser@gmail.com', 'version': '0.0.1', 'created_at': datetime.datetime(2024, 9, 6, 16, 31, ... (563 characters truncated) ... peaker_selection_method='auto', allow_repeat_speaker=False), 'updated_at': datetime.datetime(2024, 9, 6, 16, 31, 2, 164427), 'task_instruction': None}]]

### Model Used

gpt-4-1106-preview

### Additional Information

AutoGen version: installed today from pip
MacOSX latest
Python 3.11

**Comment by goyaweb** [comment]
re-installed using Conda and now it does work out of the box.

**Comment by windowshopr** [comment]
I'm getting the same error. I try to create any agent, using the default settings in the popup window, get this traceback:

```
2024-09-09 10:27:30.755 | ERROR    | autogenstudio.database.dbmanager:upsert:75 - Error while updating Agent: (builtins.TypeError) Object of type 
AgentConfig is not JSON serializable
[SQL: INSERT INTO agent (created_at, updated_at, user_id, version, type, config, task_instruction) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: [{'version': '0.0.1', 'created_at': datetime.datetime(2024, 9, 9, 10, 27, 30, 753154), 'type': <AgentType.userproxy: 'userproxy'>, 'updated_at': dateti ... (473 characters truncated) ... , messages=[], max_round=100, speaker_selection_method='auto', allow_repeat_speaker=True), 'user_id': 'guestuser@gmail.com', 'task_instruction': None}]]
INFO:     127.0.0.1:20933 - "POST /api/agents HTTP/1.1" 200 OK
INFO:     127.0.0.1:20935 - "GET /api/agents?user_id=guestuser@gmail.com HTTP/1.1" 200 OK
```

This is for UserProxy, Assistant and GroupChat agents.

Windows 10
Python 3.11
autogen==0.3.0
`autogenstudio ui --database-uri sqlite:///database.sqlite`
