### ISSUE TITLE
[Bug]: Bedrock client uses incorrect environment variables for authentication

### ISSUE THREAD

**Issue by seam-ctooley** [microsoft/autogen#3500]
### Describe the bug

The AWS Bedrock client uses `AWS_ACCESS_KEY` and `AWS_SECRET_KEY` as environment variables.
https://github.com/microsoft/autogen/blob/63d3297ffc66120a16e60391af538354a11e5d35/autogen/oai/bedrock.py#L61

### Steps to reproduce

N/A

### Model Used

N/A

### Expected Behavior

The client should use `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` as detailed [here](https://docs.aws.amazon.com/cli/v1/userguide/cli-configure-envvars.html).

**Comment by vaisakh-prod** [comment]
@seam-ctooley can i have a run at it ??

**Comment by seam-ctooley** [comment]
> [@seam-ctooley](https://github.com/seam-ctooley) can i have a run at it ??

Go for it

**Comment by ekzhu** [comment]
Fix Merged, will be available in the next release.
