### ISSUE TITLE
RAG [Issue]:  Reuse an existing vector database for RetrieveUserProxyAgent 

### ISSUE THREAD

**Issue by whydatk** [microsoft/autogen#3520]
### Describe the issue

I'm trying to create a RAG application using Autogen. This is my RetrieveUserProxyAgent setup.
<img width="362" alt="image" src="https://github.com/user-attachments/assets/8012290c-aded-4f8a-bec8-c09a3f32f35f">

when i run this code i got "ValueError: Collection my_datasource does not exist."

<img width="608" alt="image" src="https://github.com/user-attachments/assets/9d31e12d-5ad0-4830-b983-34cbbf5ad355">

I checked the chroma db collection list and the collection is there "Collection(name=my_datasource)".
don't know what is causing this. how to fix this issue.

```[tasklist]
### Tasks
```

**Comment by ekzhu** [comment]
@thinkall is this something you can comment on?

**Comment by thinkall** [comment]
Hi @whydatk , have you made it work before? Which versions of autogen and chromadb are you using?

**Comment by whydatk** [comment]
Hi @thinkall , not in this way. Autogen = 0.2.33, chromaDB =0.4.24.

**Comment by thinkall** [comment]
> Hi [@thinkall](https://github.com/thinkall) , not in this way. Autogen = 0.2.33, chromaDB =0.4.24.

Hi @whydatk , I see you've passed in a customized client. `client` is a deprecated parameter, you need to also set `vector_db` to `None` to use it.

https://github.com/microsoft/autogen/blob/v0.2.33/autogen/agentchat/contrib/retrieve_user_proxy_agent.py#L129-L139

**Comment by whydatk** [comment]
Hi @thinkall setting vector_db to None will fix it ?  and what would be the best practice if i want to use the existing vector db in autogen

**Comment by thinkall** [comment]
> [@thinkall](https://github.com/thinkall) when i set the vector_db to None it creates a new issue. I have tested the code with the same setup. This is my client code "persistent_client = chromadb.PersistentClient(path)" ![Image](https://github.com/user-attachments/assets/36025234-9070-4b27-a296-9b3cbb3fab20)
> 
> NOTE: The embedding model was working fine i have tested it using a autogen code to create embedding and then perform RAG on it.

Hi @whydatk , only models listed [here](https://www.sbert.net/docs/sentence_transformer/pretrained_models.html) is supported by passing in a model name to "embedding_model". If you need other models, you can create a `embedding_function`. Check out the docs [here](https://microsoft.github.io/autogen/0.2/docs/reference/agentchat/contrib/retrieve_user_proxy_agent) and [here](https://microsoft.github.io/autogen/0.2/blog/2023/10/18/RetrieveChat#customizing-embedding-function)

**Comment by whydatk** [comment]
Hi @thinkall code is working now, Thanks for the help :)
