### ISSUE TITLE
[Bug]: WARNING:autogen.token_count_utils:Model gpt-4o-2024-08-06 not found. Using cl100k_base encoding. INFO:autogen.token_count_utils:gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.

### ISSUE THREAD

**Issue by tyler-suard-parker** [microsoft/autogen#3521]
### Describe the bug

It looks like gpt-4o-2024-08-06 is too new and has not been added to the token count utils module.

### Steps to reproduce

Try to run autogen using gpt-4o-2024-08-06

### Model Used

gpt-4o-2024-08-06

**Comment by hackertron** [comment]
Do you think my issue is related to yours? : https://github.com/microsoft/autogen/issues/3672

**Comment by jackgerrits** [comment]
Duplicate of #3672
