### ISSUE TITLE
[.Net][Feature Request]: Add support for OpenAI o1-preivew model

### ISSUE THREAD

**Issue by LittleLittleCloud** [microsoft/autogen#3522]
### Is your feature request related to a problem? Please describe.

The existing `OpenAIChatClientAgent` needs a little twist in order to work with o1-preview model
- make system message optional, because o1 doesn't support system message
- don't set temperature/max token when it's null, because o1 doesn't allow setting these fields

**Comment by tyejcoleman** [comment]
Hello @LittleLittleCloud, wondering if o1-preview model is supported for the python package as well. In particular, I am looking to use it in AssistantAgent.
