### ISSUE TITLE
[Issue]: LocalCommandlineCodeExecutor doesn't include the stdout when timeout is hit

### ISSUE THREAD

**Issue by Ilaiwi** [microsoft/autogen#3534]
### Describe the issue

when timeout is hit while using `LocalCommandlineCodeExecutor`. The stdout from all of our prints are never returned to the llm.

### Steps to reproduce

run this code

```python
from pathlib import Path

from autogen.coding import CodeBlock, LocalCommandLineCodeExecutor

work_dir = Path("coding")
work_dir.mkdir(exist_ok=True)

executor = LocalCommandLineCodeExecutor(work_dir=work_dir, timeout=5)
print(
    executor.execute_code_blocks(
        code_blocks=[
            CodeBlock(language="python", code="""print('Hello, World!')
import time
time.sleep(10)"""),
        ]
    )
)
```

Notice that the output only has `Timeout` but not "Hello, World!"

### Additional Information

Not sure if this is done intentionally or not. If it's not then I would be happy to submit a fix.

**Comment by ekzhu** [comment]
It is intended. 

Note that the team is currently focusing on releasing v0.4. You can take a look at the new API: https://microsoft.github.io/autogen/dev/index.html. It also has a code executor though the behavior is the same.
