### ISSUE TITLE
[Issue]: Application creates multiple docker containers while running.

### ISSUE THREAD

**Issue by b4codify** [microsoft/autogen#3542]
### Describe the issue

I have setup 3 autogen agents as part of group chat along with tools function call:
- user proxy
- planner
- coder

Agent Config: 
- Using Docker command executor for user proxy agent 
- llm config is set for both planner and coder

However, as soon as user proxy agent starts the group chat with planner, Autogen launches 2 container right away and the moment planner and coder start conversation, docker container count reaches 6 containers. 

Issues:
1. How to limit application to have only one docker container running?
   - I could see the same code gets copied inside all 6 container which is generated by Coder agent and executed by user proxy agent.
  
2. Multiple LLM Api calls for a very basic conversation
   - When I stop the program execution after one round of communication in this order: User Proxy starts chat -> Planner -> coder -> user proxy execution -> Planner. I observed more than 12 LLM API calls for just 4-5 group chat interactions.

Need to know how to limit multiple containers and multiple LLM api calls for a very simple workflow?

### Screenshots and logs

<img width="1356" alt="Screenshot 2024-09-17 at 2 56 11 PM" src="https://github.com/user-attachments/assets/999bcae8-042f-4a40-9901-497b3c1211d8">

**Comment by jackgerrits** [comment]
can you provide the code used?
