### ISSUE TITLE
[Feature Request]: support parallel processing and multi-user usage

### ISSUE THREAD

**Issue by douyacai1010** [microsoft/autogen#3549]
### Is your feature request related to a problem? Please describe.

 Now only one user can use it at a time, and each user can only have one conversation in progress. It is not possible to open another conversation

### Describe the solution you'd like

I hope to support parallel processing and multi-user usage.

**Comment by ekzhu** [comment]
For multi-tenant, see the documentation for v0.4 (preview): https://microsoft.github.io/autogen/dev/user-guide/core-user-guide/index.html. In short, we support this scenario using native async API and topic and subscription (see [example](https://microsoft.github.io/autogen/dev/user-guide/core-user-guide/cookbook/topic-subscription-scenarios.html))
