### ISSUE TITLE
[Issue]: Can we have multiple user proxies?

### ISSUE THREAD

**Issue by MAhmadUzair** [microsoft/autogen#3550]
### Describe the issue

I am trying to integrate the multiple agents where I need to have multiple user proxies. Is it possible? If yes then How?
![userproxy](https://github.com/user-attachments/assets/f8f2bd62-cb14-46c6-b260-a7a61a166e83)

**Comment by SuMiaoALi** [comment]
A user can use multiple user agents to talk to different ConversableAgents. You can and should do this. Only in this way can the chat records and status cache of different businesses be isolated.

**Comment by ekzhu** [comment]
Thanks @SuMiaoALi .

@MAhmadUzair  you can also take a look at v0.4 (preview) the core library, which makes implementing your use case much easier with even-driven agents. https://microsoft.github.io/autogen/dev/user-guide/core-user-guide/index.html
