### ISSUE TITLE
[Issue]: BadRequestError: Error code: 400, exceeding max content length even with context_window_handler.

### ISSUE THREAD

**Issue by its-arsalann** [microsoft/autogen#3564]
## Facing below error even after implementing the context window handler
**Library: pyautogen 0.2.31**

I am using groupchat and have two agents along with some tools. I have added context window handler to both agents.

context_handling.add_to_agent(engineer)
context_handling.add_to_agent(user_proxy)
  
GroupChat( agents=[engineer, user_proxy],.....)

**below is the context window handler's setting**

context_configs = {
    "max_msgs": 20,
    "model": gpt-4o,
    "max_tokens": 128000,
    "max_token_per_msg": 15000,
    "min_tokens": 0
}

It usually appears when the "number of tokens reduced from" count increases above 128k. below is the example
"Number of tokens reduced from **139924** to 47584"  

### Screenshots and logs

**Error log:**
Truncated 92340 tokens. Number of tokens reduced from 139924 to 47584
.
.
.
......\lib\site-packages\openai\_base_client.py", line 1020, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "This model's maximum context length is 128000 tokens. However, your messages resulted in 144122 tokens (143706 in the messages, 416 in the functions). Please reduce the length of the messages or functions.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}

### Additional Information

pyautoGen Version: 0.2.31
Operating System: Window 11
Python Version: 3.10

**Comment by ekzhu** [comment]
@WaelKarkoub is this something you can take a look at? 

Also, we are using `autogen-agentchat` package now and the current version is 0.2.36.

**Comment by its-arsalann** [comment]
> [@WaelKarkoub](https://github.com/WaelKarkoub) is this something you can take a look at?
> 
> Also, we are using `autogen-agentchat` package now and the current version is 0.2.36.

Can you please briefly explain the difference between "pyautogen" (now autogen) and "autogen-agentchat" pypi projects ?

**Comment by WaelKarkoub** [comment]
If I'm not mistaken, this is fixed in the latest version

**Comment by ekzhu** [comment]
> > [@WaelKarkoub](https://github.com/WaelKarkoub) is this something you can take a look at?
> > 
> > Also, we are using `autogen-agentchat` package now and the current version is 0.2.36.
> 
> @ekzhu, Can you please briefly explain the difference between "pyautogen" (now autogen) and "autogen-agentchat" pypi projects ?

See our FAQ in the README: https://github.com/microsoft/autogen

**Comment by ekzhu** [comment]
We will make a release soon. Thanks @WaelKarkoub
