### ISSUE TITLE
[Issue]: model not found

### ISSUE THREAD

**Issue by xulegithub** [microsoft/autogen#3576]
### Describe the issue

 WARNING - Model qwen2.5:latest is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
groupchat found, processing 2

Testing model id=80 created_at='2024-09-27T16:21:53.817416' updated_at='2024-09-27T16:21:53.817416' user_id='guestuser@gmail.com' version='0.0.1' model='qwen2.5:latest' api_key='your_api_key' base_url='http://localhost:11434/v1' api_type='open_ai' api_version=None description='qwen2.5:latest_02'

![image](https://github.com/user-attachments/assets/ffb7c477-33ce-4bd3-bfff-91c91f6efa05)

**Comment by ekzhu** [comment]
The warning is caused by the cost information not available for the model you selected. Since it is a local model, you can ignore this warning.
