### ISSUE TITLE
Erros when use reflection_with_llm

### ISSUE THREAD

**Issue by dmitry-sablin-db** [microsoft/autogen#3582]
### Describe the bug

Error code: 400 - {'error': {'message': "Invalid 'messages[2].name': string does not match pattern. Expected a string that matches the pattern '^[a-zA-Z0-9_-]+$'.", 'type': 'invalid_request_error', 'param': 'messages[2].name', 'code': 'invalid_value'}}

### Steps to reproduce

If one agent has json format of markdown format, i got such parsing error when try to get summary

### Model Used

gpt-4o-mini

### Expected Behavior

Expect to get summary of conversation with and format inside chat

**Comment by ekzhu** [comment]
Looks like you might be passing an agent name with a space.

**Comment by ekzhu** [comment]
@dmitry-sablin-db  have you tried removing spaces from agent names?

**Comment by ekzhu** [comment]
Closing this for now. Let me know if the proposed solution did not work.
