### ISSUE TITLE
0.1.2 PyPI version missing

### ISSUE THREAD

**Issue by jklaise** [microsoft/autogen#36]
Looks like the `0.1.2` version is yet to be uploaded to PyPI, hence some notebooks that specify `~=0.1.2` cannot be executed as is, e.g. https://github.com/microsoft/autogen/blob/main/notebook/agentchat_RetrieveChat.ipynb

**Comment by sonichi** [comment]
Thanks for reporting this. It's available now: 
![image](https://github.com/microsoft/autogen/assets/4250911/62c9da8a-d2dc-4f12-a37d-98bd2b8b28c2)
