### ISSUE TITLE
Add warning for returning None from intervention handler

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#3621]
Add warning for returning None from intervention handler

**Comment by decodingafterlife** [comment]
Hey, is this issue still open? If it's possible I'll love to contribute to it; if you could guide me on the same as this will be my first issue.

**Comment by jackgerrits** [comment]
Feel free to contribute! You should look at where the intervention handled is called in the single threaded runtime

**Comment by SANTHOSH-MAMIDISETTI** [comment]
> Add warning for returning None from intervention handler

Could you please elaborate more @?
