### ISSUE TITLE
A replay mock model client for testing

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#3622]
### What feature would you like to be added?

Add a test utility class for mocking a ChatCompletionClient for testing. E.g.

```python
mock_client = ReplayChatCompletionClient(chat_completions=<a list of model client messages>)
# Use it as a regular model client, pop a message from the input list on each `create` or `create_stream` call. 
```

The model client should raise exception once the list of messages is exhausted. 

### Why is this needed?

We should avoid calling a real LLM as much as possible in unit tests for development velocity.

**Comment by MohMaz** [comment]
@ekzhu 
This implementation could be as simple as wrapping existing [_mock_create](https://github.com/microsoft/autogen/blob/930e61306a2c4fe03b923e361fcfa21f32d9efb6/python/packages/autogen-ext/tests/models/test_openai_model_client.py#L108) and [_mock_create_stream](_mock_create_stream) into the `ReplayChatCompletionClient` all the way to (try to) calculate and return usages and support Tools.  What scope do you think we should take for this ticket so I can create subtasks accordingly.

**Comment by ekzhu** [comment]
It is sufficient to have a mock client we can reuse for each instance of model client. Currently the mock approach is for all clients rather than an instance.
