### ISSUE TITLE
Feature: aider coding assistant agent (2nd try)

### ISSUE THREAD

**Issue by usmanovbf** [microsoft/autogen#3623]
### What feature would you like to be added?

It would be great to see a coding agent that could leverage the [Aider](https://github.com/paul-gauthier/aider) coding assistant tool to implement changes. 
Discussed [previously](https://github.com/microsoft/autogen/issues/528), but may be someone has an interest now for that?

### Why is this needed?

The aider tool's features such as git integration could be an interesting and powerful addition to this framework.

**Comment by ekzhu** [comment]
@usmanovbf can you take a look at the autogen-agentchat 0.4 API and see if it is possible to connect a `BaseChatAgent` subclass to an Aider agent?

**Comment by usmanovbf** [comment]
@ekzhu sure, but can you please elaborate more, how do I need to check that?

**Comment by Fasti-au** [comment]
--message-file MESSAGE_FILE
--message

you can function call it with an instruction....seems like this is just a wrapper to handle the command options for CLI. Aider already has the CLI options

**Comment by ekzhu** [comment]
@usmanovbf please take a look at the AgentChat tutorial for how to implement a custom agent: https://microsoft.github.io/autogen/dev/user-guide/agentchat-user-guide/tutorial/custom-agents.html. 

And you can create a community package for your agent following the guideline here: https://microsoft.github.io/autogen/dev/user-guide/extensions-user-guide/index.html

**Comment by ekzhu** [comment]
We can't accept changes that we cannot test here. Please consider creating a community package and apply tags for discoverability.
