### ISSUE TITLE
Proto message serializer for message types defined using proto

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#3643]
### What feature would you like to be added?

Support proto message types in Python API: built in serializer in core.

### Why is this needed?

.NET API is using proto message types. So this is required for cross-language.

**Comment by peterychang** [comment]
Python code changes are in place, but need to be tested. Testing is currently hampered by a bug somewhere thats preventing the python and dotnet components from connecting via grpc.

**Comment by peterychang** [comment]
Latest proposal is to separate the control messages from agent messages.
This would result in the following top-level message structures
`RegisterAgentType*`, `AddSubscription*`, `CloudEvent[Message[RpcRequest|RpcResponse|Event]]`
2 new rpc calls would be implemented to handle `RegisterAgentType` and `AddSubscription`

The problem I've run into with this proposal is that the current python design is that all these messages are sent on a single persistent channel. That means that the RegisterAgentTypeRequest, AddSubscriptionRequest, and all the CloudEvent requests can directly be correlated to the same caller. Under the new proposal all these calls would be separated into separate channels (with the CloudEvent calls on a single persistent channel). In short, there is no way to determine which RegisterAgentTypeRequest is associated with which AddSubscriptionRequest.

**Comment by peterychang** [comment]
The hopefully final design of this feature:

`RpcRequest` and `RpcResponse` will be removed, their workflows will effectively use what is currently the `Event` message type.
`Events` will be put into a Cloud Event. The final message types will be
`Message[RegisterAgentType*]`, `Message[AddSubscription*]`, `Message[CloudEvent]`.

RPC messages will be recreated by having the sender subscribe to a temporary, request-specific TopicID that will be unsubscribed from once the response is received. The caller-side behavior will remain the same, where the `send_rpc()` function will only return once the response has been received.

Pseudocode is (on BaseAgent)
![Image](https://github.com/user-attachments/assets/ee70f614-d40e-427d-838e-7e6cef11a31d)
