### ISSUE TITLE
Create OpenAI assisant agent

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#3646]
### What feature would you like to be added?

A `BaseChatAgent` implementation backed by an OpenAI Assistant. 

See the OpenAI AI assistant cookbook in the core library for reference. 

### Why is this needed?

Assistant is useful single agent abstraction used by many applications.

**Comment by lspinheiro** [comment]
@ekzhu , I can take a look into this. On top of adding the agent, would have any suggestions for how to integrate it into existing cookbooks?

**Comment by ekzhu** [comment]
Sounds good! We can include this in the extension module. 

@victordibia and I are working on the agent chat tutorial and documentation. We can have an example section for the open ai assistant agent.
