### ISSUE TITLE
WARNING - Model gpt-4o-2024-08-06 is not found. 

### ISSUE THREAD

**Issue by hackertron** [microsoft/autogen#3672]
### What happened?
[autogen.oai.client: 10-07 13:00:36] {315} WARNING - Model gpt-4o-2024-08-06 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, 
completion_token_price_per_1k]} for customized pricing.
←[33mfront_desk_assistant←[0m (to user_proxy):
 WARNING - Model gpt-4o-2024-08-06 is not found. The cost will 
be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

### What did you expect to happen?

the project was working fine and the model that is being used is "gpt-4o", not sure what the issue can be

### How can we reproduce it (as minimally and precisely as possible)?

try : https://github.com/bonadio/autogenwebdemo with gpt-4o, you will get the issue.

### AutoGen version

pyautogen==0.2.32

### Which package was this bug in

Core

### Model used

gpt-4o

### Python version

3.11.3

### Operating system

windows

**Comment by talyabs** [comment]
Having the same error with `Model gpt-4o-2024-08-06 is not found` 
my config is not specifing this specific version, but like that:
```
llm_config_openai = {
    "config_list": [{"model": "gpt-4o", "api_key": OPENAI_API_KEY}],
    "temperature": 0,
    "seed": 42,
}
```

**Comment by hackertron** [comment]
> The resolved model from `gpt-4o` must have changed on OpenAI's end. `gpt-4o-2024-08-06` was added in `0.2.33`, please update your installed package to resolve the issue without needing to use an older 4o.
> 
> Please note the package name has changed to `autogen-agentchat`, so you can use:
> 
> ```
> autogen-agentchat==0.2.36
> ```

Thanks !! :) I confirm it works !! We can close this issue
