### ISSUE TITLE
Autogen throws an error on Windows 10

### ISSUE THREAD

**Issue by ramzeez88** [microsoft/autogen#369]
Traceback (most recent call last):
  File "e:\Python\AutoGen\a1.py", line 44, in <module>
    user_proxy.initiate_chat(
  File "C:\ProgramData\anaconda3\lib\site-packages\autogen\agentchat\conversable_agent.py", line 531, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "C:\ProgramData\anaconda3\lib\site-packages\autogen\agentchat\conversable_agent.py", line 334, in send
    recipient.receive(message, self, request_reply, silent)
  File "C:\ProgramData\anaconda3\lib\site-packages\autogen\agentchat\conversable_agent.py", line 462, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
  File "C:\ProgramData\anaconda3\lib\site-packages\autogen\agentchat\conversable_agent.py", line 781, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
  File "C:\ProgramData\anaconda3\lib\site-packages\autogen\agentchat\groupchat.py", line 162, in run_chat
    speaker = groupchat.select_speaker(speaker, self)
  File "C:\ProgramData\anaconda3\lib\site-packages\autogen\agentchat\groupchat.py", line 91, in select_speaker
    final, name = selector.generate_oai_reply(
  File "C:\ProgramData\anaconda3\lib\site-packages\autogen\agentchat\conversable_agent.py", line 609, in generate_oai_reply
    return True, oai.ChatCompletion.extract_text_or_function_call(response)[0]
  File "C:\ProgramData\anaconda3\lib\site-packages\autogen\oai\completion.py", line 1066, in extract_text_or_function_call
    choices = response["choices"]
KeyError: 'choices'
I run it without docker and with code_execution_config=False. What is this error related to please?

**Comment by sonichi** [comment]
Could you show the code snippet? This error has nothing to do with win 10.

**Comment by ramzeez88** [comment]
I forgot to mention that I use Ooba's text gen as a openai server with Zephyr7B llm. Here is the code snipped i use:

import autogen

config_list = [{
    "api_type":"open_ai",
    "api_base":"http://127.0.0.1:5001/v1",
    "api_key": "sk-111111111111111111111111111111111111111111111111"
}]

llm_config = {
    "request_timeout": 600,
    "seed": 42,
    "config_list": config_list,
    "temperature": 0.1
}

user_proxy = autogen.UserProxyAgent(
   name="User_proxy",
   system_message="A human admin.",
   code_execution_config={"work_dir":"_output", "use_docker":False},
   human_input_mode="TERMINATE"
)
coder = autogen.AssistantAgent(
    name="Coder",
    system_message= " You are a proficient python coder that writes the code for a given task.",
    llm_config=llm_config,
)
pm = autogen.AssistantAgent(
    name="Product_manager",
    system_message="You are responsible for the task overview. You come up with easiest and most effective ways to outline the task.",
    llm_config=llm_config,
)
groupchat = autogen.GroupChat(agents=[user_proxy, pm, coder], messages=[], max_round=12)
manager = autogen.GroupChatManager(groupchat=groupchat, llm_config=llm_config)

task = input("What is the task you want to accomplish: ")
    
# the assistant receives a message from the user_proxy, which contains the task description
user_proxy.initiate_chat(
    manager,
    message='"""' + task + '"""',
)

**Comment by ramzeez88** [comment]
> Could you show the code snippet? This error has nothing to do with win 10.

I forgot to mention that i use ooba's text gen as the openai server with zephyr7b llm.
Here is the code snipped i used:

import autogen

config_list = [{
    "api_type":"open_ai",
    "api_base":"http://127.0.0.1:5001/v1",
    "api_key": "sk-111111111111111111111111111111111111111111111111"
}]

llm_config = {
    "request_timeout": 600,
    "seed": 42,
    "config_list": config_list,
    "temperature": 0.1
}

user_proxy = autogen.UserProxyAgent(
   name="User_proxy",
   system_message="A human admin.",
   code_execution_config={"work_dir":"_output", "use_docker":False},
   human_input_mode="TERMINATE"
)
coder = autogen.AssistantAgent(
    name="Coder",
    system_message= " You are a proficient python coder that writes the code for a given task.",
    llm_config=llm_config,
)
pm = autogen.AssistantAgent(
    name="Product_manager",
    system_message="You are responsible for the task overview. You come up with easiest and most effective ways to outline the task.",
    llm_config=llm_config,
)
groupchat = autogen.GroupChat(agents=[user_proxy, pm, coder], messages=[], max_round=12)
manager = autogen.GroupChatManager(groupchat=groupchat, llm_config=llm_config)

task = input("What is the task you want to accomplish: ")
    

user_proxy.initiate_chat(
    manager,
    message='"""' + task + '"""',
)

**Comment by sonichi** [comment]
For some reason the response doesn't contain the field "choices" with the model you are using.

**Comment by the-don-wan** [comment]
I'm also getting the same error. I'm using the mistral 7b model with Ollama.ai locally installed on my mac.
