### ISSUE TITLE
Python version for uv checks, tomllib [staging]

### ISSUE THREAD

**Issue by husseinmozannar** [microsoft/autogen#3710]
### What happened?

When running development checks for python in the staging error,

Get the error:
ModuleNotFoundError: No module named 'tomllib'

This is because tomllib is only available in Python 3.11, which [run_task_in_pkgs_if_exist](https://github.com/microsoft/autogen/blob/staging/python/run_task_in_pkgs_if_exist.py) uses

Instead, maybe let's use the [tomli ](https://github.com/hukkin/tomli) package (?), or something else?

### What did you expect to happen?

not having errors

### How can we reproduce it (as minimally and precisely as possible)?

Run checks with "poe check" in Python <3.11

### AutoGen version

staging

### Which package was this bug in

Core

**Comment by jackgerrits** [comment]
Yeah, when running the poe tasks 3.11 is required due to the dep. I did it since it means we don't need to install any extra packages, but yeah we can just add one to the dev dependencies and it'll be there anyway and get rid of the requirement
