### ISSUE TITLE
Add a javascript SDK 

### ISSUE THREAD

**Issue by markokraemer** [microsoft/autogen#372]

**Comment by victordibia** [comment]
Related to issue #236 

Some information and status on this 

- It is on the [AutoGen roadmap](https://github.com/orgs/microsoft/projects/989/views/1?pane=issue&itemId=41526077), but not actively worked on right now.
- There are some related open source efforts towards this - [here](https://youtu.be/9Hrfx6kw1IE) and [here](https://github.com/xXAdonesXx/NodeGPT)

**Comment by simon12** [comment]
An API-friendly typescript port here

https://github.com/Engine-Labs/engine-agents
