### ISSUE TITLE
Moving OpenAIChatCompletionClient and AzureOpenAIChatCompletionClient to `autogen_ext`

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#3740]
- [ ] Move the model clients to `autogen_ext`
- [ ] Make install clients using `pip install autgen-ext[openai]`, and `pip install autogen-ext[azure]` to include `azure.identity` for AAD auth. 
- [ ] Update quick start documentations

**Comment by lspinheiro** [comment]
FYI, waiting for new `autogen-ext` package structure.
