### ISSUE TITLE
Unable to access chat history in group chat setting.

### ISSUE THREAD

**Issue by athmanar** [microsoft/autogen#3765]
I cannot understand how to make an agent summarize the entire conversation in a group chat.
I have a group chat which looks like this:

`initializer -> code_creator <--> code_executor --->summarizer
`
The code_creator and code_executor go into a loop until code_execuor send an `''` (empty sting)

Now the summarizer which is an llm agent needs to get the entire history of the conversations that the group had and not just empty message from the code_executor. How can I define the summarizer to do so?

```
def custom_speaker_selection_func(last_speaker: Agent, groupchat: autogen.GroupChat):
    messages = groupchat.messages
    if len(messages) <= 1:
        return code_creator
    if last_speaker is initializer:
            return code_creator
    elif last_speaker is code_creator:
            return code_executor
    elif last_speaker is code_executor:
        if "TERMINATE" in messages[-1]["content"] or messages[-1]['content']=='':
            return summarizer
        else:
            return code_creator  
    elif last_speaker == summarizer:
        return None
    else:
        return "random"
```

```
summarizer = autogen.AssistantAgent( name="summarizer", 
                                    system_message="Write detailed logs and summarize the chat history", 
                                     llm_config={ "cache_seed": 41, "config_list": config_list, "temperature": 0,}, )
```

**Comment by ekzhu** [comment]
Looks fine to me. What's your output?

**Comment by athmanar** [comment]
@ekzhu so problem is the `''`  string is sent to the summarizer. So summarizer responds 
```
summarizer (to chat_manager):

It seems like there was no specific query in your last message. If you have any further questions or need additional assistance, please let me know!
```

However what i want to send is the entire chat history..ie what the code_execuotor and code_creator is sending and summarize it.

**Comment by ekzhu** [comment]
The summarizer should already have the entire chat history because the group chat updates all agents with all messages in the group chat. You can put a breakpoint in your summarizer to look at its chat history. 

https://github.com/microsoft/autogen/blob/c179efbb13b1040df92f9b4a8c997963dc1596df/autogen/agentchat/conversable_agent.py#L2045

**Comment by athmanar** [comment]
@ekzhu actually I am able to simulate the expected responses by copying the     `DEFAULT_SUMMARY_PROMPT = "Summarize the takeaway from the conversation. Do not add any introductory phrases."` as my system message for the summarizer and acts as expected!..
