### ISSUE TITLE
Stitching Multiple Sections of the Prompt

### ISSUE THREAD

**Issue by anshukpal** [microsoft/autogen#3794]
### What feature would you like to be added?

I would like to understand if there is a feature today when autogen can be used to formulate the sections of the prompt. e.g. contents of the prompt can be formed from different places like DB, vector-search, static, LLM, etc. and finally can be chained together and formed a final prompt.

This is something which can be implemented using chain concepts of lang-chain, and these multiple calls to get the content, can be also run in parallel.

### Why is this needed?

In order to provide a flexibility to the user, based on their domain need and understanding, different sections like context, domain details need to be fetched from specific RAG sources, so that can fetched and customised and stitched together to make the final prompt.

**Comment by rysweet** [comment]
Hi @anshukpal - you can certainly do this in the code for you agent, using langchain or semantic kernel etc, there are examples in the docs for python. Adding @afourney inncase he has comments on other conventions in the pyautogen that might help.

**Comment by anshukpal** [comment]
hi @rysweet Thanks for your comment, I was wondering, this feature can be done directly using only autogen apis? not using langchain in autogen. I mentioned langchain - because using only langchain I have experimented that and it works; and whether that similar functionality can be achieved using only autogen or not. 
FYI - @afourney

**Comment by ekzhu** [comment]
Can you post some example or pseudo code for what you are looking for? 

For context, the core API is agnostic to what agent framework you are using. You can use langchain, crew AI, llamaindex, or AutoGen v0.2 agents or tools. 

See example of using langraph agent: https://microsoft.github.io/autogen/dev/user-guide/core-user-guide/cookbook/langgraph-agent.html

**Comment by anshukpal** [comment]
What I have done and experimented - using langchain is something like this:

- Defined 4 chains, every chain is invoking DB or some rest api  (consider them as intermediate RAG sources) and getting some results.
- The results of the 4 chains are stitched together, and then formed a final prompt.
- The final prompt is used to do a final llm invocation and get final result back.

```
chain_1 = (
    prompt1
  | <custom_rest_api_call>
  | RunnableParallel(result1=RunnablePassthrough()
  )
).with_types(input_type=Dict[str, str], output_type=str)


chain_2 = (
    prompt2
  | <custom_rest_api_call>
  | RunnableParallel(result2=RunnablePassthrough()
  )
).with_types(input_type=Dict[str, str], output_type=str)


chain_3 = (
    prompt3
  | <custom_rest_api_call>
  | RunnableParallel(result3=RunnablePassthrough()
  )
).with_types(input_type=Dict[str, str], output_type=str)


chain_4 = (
    prompt4
  | <custom_rest_api_call>
  | RunnableParallel(result4=RunnablePassthrough()
  )
).with_types(input_type=Dict[str, str], output_type=str)



parallel = RunnableParallel({
  'result1': chain_1,
  'result2': chain_2,
  'result3': chain_3,
  'result4': chain_4,
})
result = parallel.invoke({'result1':query,'result2': result2,'result3': result3,'result4': query})

formatted_prompt = full_prompt.format(....)//from the result

final_chain = (
          # PromptTemplate.from_template(prompt + "\nQuestion: {nl_query}\nOracle SQL:")
          PromptTemplate.from_template(formatted_prompt)
          | <lllm_call_via_rest_api>
          | RunnableParallel(final_result=RunnablePassthrough()
          )
          ).with_types(input_type=Dict[str, str], output_type=str)
final_result = final_chain.invoke({})
```

Can the above functionality achieved using only autogen, and not using langchain?

**Comment by ekzhu** [comment]
I would use Python asyncio and use asyncio.gather for this. 

I don't think it's an abstraction we are considering at the moment. You can use langchain. You can also write your autogen agent using langgraph.

**Comment by ekzhu** [comment]
Closing this for not planned for the core libaries. @anshukpal if you are interested you can create a community AutoGen package that extends the core libraries. See https://microsoft.github.io/autogen/dev/user-guide/extensions-user-guide/index.html#creating-your-own-community-extension
