### ISSUE TITLE
Not able to install retrievechat

### ISSUE THREAD

**Issue by lokesh-couchbase** [microsoft/autogen#3796]
### What happened?

As agenthchat has been moved to autogen-agenthchat. I am not able to do `pip install autogen-agentchat[retrievechat]` or `pip install autogen-agentchat[retrievechat]~=0.2` or `pip install autogen-agentchat[retrievechat-couchbase]`.

### What did you expect to happen?

I expected these packages to be installed so that retrievechat functionality can be used from autogen

### How can we reproduce it (as minimally and precisely as possible)?

Try `pip install autogen-agentchat[retrievechat]`

### AutoGen version

0.2.36

### Which package was this bug in

AgentChat

### Python version

3.11.7

### Operating system

Mac OS, Sonoma, Apple Silicon

**Comment by ekzhu** [comment]
I couldn't reproduce this issue using a fresh conda environment Python 3.11

> pip install 'autogen-agentchat[retrievechat]~=0.2'

Can you please include your full error message?

**Comment by rysweet** [comment]
Hi @lokesh-couchbase - looks like we can't repro this issue, could you please try again and provide more information that might help us help you?

**Comment by lokesh-couchbase** [comment]
I found the issue, I was not including single quotes like here `pip install 'autogen-agentchat[retrievechat]~=0.2'`

It works now and I am closing the issue. Thanks a lot for your responses @ekzhu @rysweet
