### ISSUE TITLE
Handoff figure renders poorly in dark mode

### ISSUE THREAD

**Issue by jackgerrits** [microsoft/autogen#3797]
### What happened?

![Image](https://github.com/user-attachments/assets/185cdb4c-88ba-4879-946f-50e7c66435a7)

For reference light mode is: 

![Image](https://github.com/user-attachments/assets/06fb6a7d-c4f2-4412-bef7-b57b267f3999)

### What did you expect to happen?

Something more readable than this

### How can we reproduce it (as minimally and precisely as possible)?

View this page in dark mode: https://microsoft.github.io/autogen/dev/user-guide/core-user-guide/design-patterns/handoffs.html

### AutoGen version

dev

### Which package was this bug in

Core

**Comment by ekzhu** [comment]
For reference, the drawio source is in https://github.com/microsoft/autogen/tree/main/python/packages/autogen-core/docs/drawio
