### ISSUE TITLE
RAG agents gives error: No such file or directory: '/tmp/chromadb/README.md'

### ISSUE THREAD

**Issue by daniel-counto** [microsoft/autogen#380]
I followed the codes in "Basic Usage of RAG Agents" section of the page https://microsoft.github.io/autogen/blog/2023/10/18/RetrieveChat , but it gives the above mentioned error.

![Screenshot (598)](https://github.com/microsoft/autogen/assets/140989990/5b0b9a8c-00ef-4538-8bdd-d6871696b99e)

**Comment by gagb** [comment]
@thinkall

**Comment by daniel-counto** [comment]
FYI, this is my code:
![Screenshot (599)](https://github.com/microsoft/autogen/assets/140989990/6d280500-938f-4c02-9809-1bd698b784cb)

**Comment by krissz22** [comment]
What i found, while running the script under Windows is, that the original "get_file_from_url" function in "retrieve_utils.py" does not work correctly on Windows systems, as it tries to create a file in the "tmp/chromadb" directory. This directory structure is specific to Unix-based systems and is not valid on Windows. As a result, the "FileNotFoundError" occurs when the function attempts to create the folder and save the file.

Here's the code of the **original function**:

```python
def get_file_from_url(url: str, save_path: str = None):
    """Download a file from a URL."""
    if save_path is None:
        save_path = os.path.join("/tmp/chromadb", os.path.basename(url))
    with requests.get(url, stream=True) as r:
        r.raise_for_status()
        with open(save_path, "wb") as f:
            for chunk in r.iter_content(chunk_size=8192):
                f.write(chunk)
    return save_path
```

**My solution:** 
To make the function work on both Unix-based and Windows systems, i modified the function to create the temporary directory in a platform-independent manner. One possible solution is to create the "chromadb" folder in the current working directory.
 
Here's the **updated** get_file_from_url **function**: 

```python
def get_file_from_url(url: str, save_path: str = None):
    """Download a file from a URL."""
    if save_path is None:
        current_dir = os.getcwd()
        temp_dir = os.path.join(current_dir, "chromadb")
        save_path = os.path.join(temp_dir, os.path.basename(url))
        os.makedirs(os.path.dirname(save_path), exist_ok=True)

    with requests.get(url, stream=True) as r:
        r.raise_for_status()
        with open(save_path, "wb") as f:
            for chunk in r.iter_content(chunk_size=8192):
                f.write(chunk)
    return save_path
```

I do not know exactly whether this is the right way to do it, but it worked for me. At least now there is a "chromadb" directory within the working directory which contains the "README.md" file.

**Comment by daniel-counto** [comment]
I specified " "client": chromadb.PersistentClient(path="/tmp/chromadb")," in the RetrieveUserProxyAgent function and it seems the above error no longer appears:

`ragproxyagent = RetrieveUserProxyAgent(
    name="ragproxyagent",
    retrieve_config={
        "task": "question answering",
        "docs_path": "https://raw.githubusercontent.com/microsoft/autogen/main/README.md",
        "client": chromadb.PersistentClient(path="/tmp/chromadb"),
        "chunk_token_size": 500,
        "get_or_create": True,
    },
)`

however a new error occurs:
![Screenshot (601)](https://github.com/microsoft/autogen/assets/140989990/303da5fd-89b6-4073-b5be-17db0640e50e)
@thinkall

**Comment by krissz22** [comment]
I reverted the changes made to the "get_file_from_url" function from my post earlier and applied `chromadb.PersistentClient(path="/tmp/chromadb"),` to my code. 

Now i can also confirm that the initial error is gone.

**Comment by ewagner70** [comment]
why is "db_path" in "retrieve_config" not supported? I suggest to include that as the cleanest, most professional solution, right?
