### ISSUE TITLE
[doc] need to document that if the protos change you have to update poe gen-proto

### ISSUE THREAD

**Issue by rysweet** [microsoft/autogen#3812]
### What feature would you like to be added?

if you change the global .proto files you have to run 
```bash
cd python
python -m pip instal uv
uv sync --all-extras
source .venv/bin/activate
poe gén-proto
```

### Why is this needed?

perhaps we could add this to the build if the protos have changed?

**Comment by jackgerrits** [comment]
This is checked in CI to ensure it remains in sync: https://github.com/microsoft/autogen/blob/0214299de506bd0a5ffd795e18daa3337e032f80/.github/workflows/checks.yml#L144

**Comment by jackgerrits** [comment]
CI checks this, closing
