### ISSUE TITLE
[code-scanning] - Fix security alerts for "exception potentially reveals information" or suppress

### ISSUE THREAD

**Issue by rysweet** [microsoft/autogen#3824]
### What happened?

There are a number of code scan alerts on autogen studio for exposing exceptions to the user, potentially these could reveal info, but Autogen studio is also not an end user tool, but a developer tool, so we are willing to suppress these alerts. 

### What did you expect to happen?

need to either fix the issue or configure code scan to ignore. 

### How can we reproduce it (as minimally and precisely as possible)?

https://github.com/microsoft/autogen/security

### AutoGen version

0.2

### Which package was this bug in

AutoGen Studio

### Python version

3.10

**Comment by victordibia** [comment]
Addressed in #4097
