### ISSUE TITLE
Examples are buried in the repo

### ISSUE THREAD

**Issue by husseinmozannar** [microsoft/autogen#3825]
In the 0.2 branch, Autogen examples are very visible existing in the notebook folder at the top of the repo with references to the examples in the Quickstart section. Moreover, the quickstart created an environmental variable to store your API key if needed rather than declared in the notebook.

On this branch, you have to work really hard to find the example jupyter notebooks and many are not found by navigating the docs alone.

Please correct me if wrong but all examples are here  [https://github.com/microsoft/autogen/tree/main/python/packages/autogen-core/docs/src/user-guide](https://github.com/microsoft/autogen/tree/main/python/packages/autogen-core/docs/src/user-guide).

My recommendation:
- move user-guide to the top level of the repo (or a similarly less obscure place)
- add links to the examples in the Readme: under autogen, under code, under agent-chat. 

In addition, I recommend changing the quickstart example to one not involving Docker as it may scare people from trying it (you need to install something else) which is not in the spirit of a quickstart.

**Comment by jackgerrits** [comment]
Yeah the intention has been to move the website to the top level of the repo to represent the fact that it is meant to span all languages in the project.

**Comment by jackgerrits** [comment]
Will be resolved once sub issues are closed.
