### ISSUE TITLE
Disable Open AI and Gemini

### ISSUE THREAD

**Issue by praveenchaga** [microsoft/autogen#3836]
### What feature would you like to be added?

Is it possible to disable OpenAI & Gemini in model specification. 

### Why is this needed?

Security purposes: Control over Models.

**Comment by ekzhu** [comment]
Can you be more specific?

If you want to use custom models you can take a look the following:

Custom models in v0.2: https://microsoft.github.io/autogen/0.2/docs/topics/non-openai-models/about-using-nonopenai-models

Custom models in v0.4: https://microsoft.github.io/autogen/dev/user-guide/core-user-guide/cookbook/local-llms-ollama-litellm.html

**Comment by praveenchaga** [comment]
Think like this, I am a Admin want to offer Autogen studio for 10 customers with different containers and customers must only see or able to use only Azure openAI. Not the others like Open AI, Gemini. 

Is there a way to disable, control or block to use OpenAI models and Gemini.

**Comment by victordibia** [comment]
@praveenchaga ,

Thanks for explaining more about the application use case you have in mind. 
I certainly can see the important value of having an application that conforms to some set of specific policies. However, I think this will best be supported at the application level as opposed to the core library. 

![Image](https://github.com/user-attachments/assets/28da3536-6c65-4182-9789-f66c699a0c27)


For example, an application/system/api build with autogen may provide configuration parameters to restrict the supported app providers. This is a feature that could go into autogen studio. Currently, we are still working on exploring how to best update studio to autogen v0.4. Once an initial version of that is done, I'll be happy to work with you in accepting contributions to admin configuration settings.
