### ISSUE TITLE
AutoGen Studio needs to support main/AutoGen 0.4

### ISSUE THREAD

**Issue by dsanr** [microsoft/autogen#3837]
### What happened?

Support for human input is merged with the main branch https://github.com/microsoft/autogen/pull/3484
When autogenstudio is installed with 'pip install autogenstudio', it is not accessing the main branch, even if the main branch is installed locally.
Autogenstudio is accessing only a different package, which is getting installed from pip, that doesn't include the mentioned PR.

How can I use Human Input Mode in AutoGen Studio? Do we need a separate release?

### What did you expect to happen?

Human Input Mode in AutoGen Studio should work when installing the main branch or 0.4 dev1 branch

### How can we reproduce it (as minimally and precisely as possible)?

pip install autogen-agentchat==0.4.0dev1
pip install autogenstudio
autogenstudio ui

Then try the options of Human_Input_Mode

### AutoGen version

0.4

### Which package was this bug in

AutoGen Studio

**Comment by rysweet** [comment]
@dsanr - Autogen studio does not yet support AutoGen 0.4. We do plan to revise it to support 0.4 but do not have an ETA. Contributions welcome.

**Comment by dsanr** [comment]
@rysweet Thank you for editing the issue and reply. 
By the way, how is https://github.com/autogen-ai/autogen different from this repository? Which one is likely to get frequent updates?

**Comment by victordibia** [comment]
@dsanr ,

I have created a broader issue for AutoGen Studio on v0.4 that we can use to track progress - [#4006](https://github.com/microsoft/autogen/issues/4006) (it includes the Human Input mode issue you have above)
I'll close this issue in favor of that one.
Let me know if there are any suggested additions to #4006
