### ISSUE TITLE
Migrate stateflow to 0.4

### ISSUE THREAD

**Issue by jackgerrits** [microsoft/autogen#3864]
Stateflow is a useful pattern that should be ported to 0.4

**Comment by ekzhu** [comment]
The existing v0.2 stateflow does not support stateful select next speaker function as the state is passed in as the `GroupChat` object. It is a limitation as it forces the user to use a pre-defined state. 

The core idea of stateflow is overriding the select speaker function. Thus, there should be a public `GroupChat` base class in v0.4 AgentChat. This requires more design. 
 
Consider moving this to v0.4.1 milestone.
