### ISSUE TITLE
openai.Completion.create() -> client.completions.create()

### ISSUE THREAD

**Issue by sonichi** [microsoft/autogen#387]

**Comment by olaoluwasalami** [comment]
Can yu assign to me?

**Comment by sonichi** [comment]
@olaoluwasalami happy to assign to you if you are confident about what to do. I haven't figured out how to do it myself.
Please note that the base branch for this task is dev/v0.2, not main.

**Comment by olaoluwasalami** [comment]
Okay, Please don't assign yet  @sonichi . Thanks
