### ISSUE TITLE
[Docs] /docs in repo should have a README.md that links to the docs

### ISSUE THREAD

**Issue by rysweet** [microsoft/autogen#3870]
### What feature would you like to be added?

if browsing the repo there is a top level /docs dir that doesn't have much in it - we need at least a readme there that points to the preferred docs entry point.

### Why is this needed?

should be super easy to find the docs

**Comment by jackgerrits** [comment]
The main entrypoint is here:
![Image](https://github.com/user-attachments/assets/345a44cd-334c-48dd-a311-54867e54eab1)

The plan is to repoint this to 0.4 once it is released
