### ISSUE TITLE
Using top level awaits in tutorial notebooks is confusing

### ISSUE THREAD

**Issue by jackgerrits** [microsoft/autogen#3885]
Jupyter allows top level await which is very convenient - but when we then render these notebooks to a docs page is confusing for users as it is not confusing why there is a top level await when this isn't normally supported in python.

Not sure what the best solution is here but we need to improve/fix this

**Comment by gziz** [comment]
Hi @jackgerrits ,
I agree and kinda feel the struggle when having to copy paste each code block and wrap the awaits inside an async function.

One proposal could be to have the full code of the notebook inside a dropdown at the bottom of the notebook.

```
```{dropdown} Full Code
:icon: code
```python
# Here goes the full code
```


<img width=600 src=https://github.com/user-attachments/assets/33dfb498-837b-4729-9194-7ba1a608dd2b/>

Block of code with a handy copy button!
<img width=600 src=https://github.com/user-attachments/assets/d402a1ad-88b6-40d8-8bf4-232244ec7488/>

**Comment by jackgerrits** [comment]
I like it but unfortunately we lose the ability to easily check those codeblocks so they can become out of sync easily. The approach taken in [this page](https://microsoft.github.io/autogen/dev/user-guide/agentchat-user-guide/quickstart.html) feels like a potentially simple solution where we structure things such that running the main is nice and easy when a user does face the error

**Comment by ekzhu** [comment]
Addressed all usages of top-level awaits in agentchat using comments. 

Let's use #4378 to address notebook usability.
