### ISSUE TITLE
ModuleNotFoundError: No module named 'autogen_ext.models'

### ISSUE THREAD

**Issue by DilayGulhan** [microsoft/autogen#3890]
### What happened?

When I create a new environment and try to import autogen_ext.models, the code doesn't run, even though autogen_ext.code_executor.docker_executor works fine when I execute the example in the README. Instead of autogen_ext.models, I tried autogen_core.components.models, and it worked

### What did you expect to happen?

We were expecting the code to function properly

### How can we reproduce it (as minimally and precisely as possible)?

With adding this code 
''''import asyncio
import logging
from autogen_agentchat import EVENT_LOGGER_NAME
from autogen_agentchat.agents import CodeExecutorAgent, CodingAssistantAgent
from autogen_agentchat.logging import ConsoleLogHandler
from autogen_agentchat.teams import RoundRobinGroupChat, StopMessageTermination
from autogen_ext.code_executor.docker_executor import DockerCommandLineCodeExecutor
from autogen_core.components.models import OpenAIChatCompletionClient

logger = logging.getLogger(EVENT_LOGGER_NAME)
logger.addHandler(ConsoleLogHandler())
logger.setLevel(logging.INFO)

async def main() -> None:
    async with DockerCommandLineCodeExecutor(work_dir="coding") as code_executor:
        code_executor_agent = CodeExecutorAgent("code_executor", code_executor=code_executor)
        coding_assistant_agent = CodingAssistantAgent(
            "coding_assistant", model_client=OpenAIChatCompletionClient(model="gpt-4o", api_key="API KEY")
        )
        group_chat = RoundRobinGroupChat([coding_assistant_agent, code_executor_agent])
        result = await group_chat.run(
            task="Create a plot of NVDIA and TSLA stock returns YTD from 2024-01-01 and save it to 'nvidia_tesla_2024_ytd.png'.",
            termination_condition=StopMessageTermination(),
        )

asyncio.run(main())
'''' in the README  like that

### AutoGen version

0.4

### Which package was this bug in

Core

### Python version

Python 3.10.12

### Operating system

Linux Ubuntu

**Comment by ekzhu** [comment]
The new release has not been made. Will update soon

**Comment by jackgerrits** [comment]
The website now allows you to choose which version to view the docs for - you should use the docs for the most recently released version when using the pypi package. See here: https://microsoft.github.io/autogen/0.4.0dev1/

**Comment by ekzhu** [comment]
Closing this as the website has been updated for the showing the latest dev release

**Comment by ooooona** [comment]
Hi team, I also met the same problem when tried to run your quickstart in my personal pc.

the quickstart:
- https://microsoft.github.io/autogen/dev/packages/index.html#pkg-info-autogen-core
-  https://microsoft.github.io/autogen/dev/user-guide/core-user-guide/quickstart.html

while I met the error:
```
Traceback (most recent call last):
  File "main.py", line 61, in <module>
    from autogen_ext.code_executors import DockerCommandLineCodeExecutor
ModuleNotFoundError: No module named 'autogen_ext.code_executors'
```

Confirmed with the autogen libs I installed, I found that the 'autogen_ext' only have 'code_executor' without 'code_executors' or 'models'!

![Image](https://github.com/user-attachments/assets/408a40f6-0252-4913-83b8-9d1deffa0d90)

**Comment by jackgerrits** [comment]
Please view the docs for the version you have installed - https://microsoft.github.io/autogen/0.4.0dev1/

Things are changing quickly atm so its not uncommon for main to diverge from the most recent dev release, which is why we just added versioned docs

**Comment by gziz** [comment]
Hey @ooooona , make sure you: `pip install autogen-ext==0.4.0.dev2`, as stated in these [docs](https://microsoft.github.io/autogen/0.4.0.dev2/packages/index.html#pkg-info-autogen-core). 
For a moment, I had the same problem where I couldn't import `DockerCommandLineCodeExecutor`.

**Comment by ooooona** [comment]
Thanks @gziz @jackgerrits , the `autogen-ext==0.4.0.dev2` works fine. Suggest you to update the userguide: https://microsoft.github.io/autogen/dev/packages/index.html#pkg-info-autogen-core, `autogen-ext==0.4.0.dev1` cannot work
