### ISSUE TITLE
Kindly help with this.

### ISSUE THREAD

**Issue by Kunjal1999** [microsoft/autogen#3932]
> Hello,
> 
> I want an implementation such that when user inputs "RESET", the agent forgets all history. 
> 
> ```python
> class AgentFactory:
>     @staticmethod
>     def create_assistant_agent(llm_config: Dict) -> autogen.AssistantAgent:
>         return autogen.AssistantAgent(
>             name="assistant",
>             llm_config={
>                 "cache_seed": 42,
>                 "config_list": llm_config["config_list"],
>                 "temperature": 0,
>             },
>         )
> 
>    @staticmethod
>     def create_user_proxy_agent() -> autogen.UserProxyAgent:
>         return autogen.UserProxyAgent(
>             name="user_proxy",
>             human_input_mode="TERMINATE",
>             max_consecutive_auto_reply=1,
>             is_termination_msg=lambda x: x.get("content", "").rstrip().endswith("TERMINATE"),            
>             code_execution_config={
>                 "executor": LocalCommandLineCodeExecutor(work_dir="coding"),
>             },
>         )
> 
> class ChatInitiator:
>     def __init__(self, user_proxy: autogen.UserProxyAgent, assistant: autogen.AssistantAgent):
>         self.user_proxy = user_proxy
>         self.assistant = assistant
> 
>     def initiate_chat(self, message: str) -> Dict:
>         return self.user_proxy.initiate_chat(
>             self.assistant,
>             message=message,
>             summary_method="reflection_with_llm",            
>         )
> ``` 

 _Originally posted by @Kunjal1999 in [#3896](https://github.com/microsoft/autogen/issues/3896#issuecomment-2433468493)_

**Comment by ekzhu** [comment]
@Kunjal1999 I need to close this to avoid cluttering the issue page.
