### ISSUE TITLE
Error occurred while processing message: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}

### ISSUE THREAD

**Issue by jobalbz** [microsoft/autogen#3953]
Im running this on an Ubuntu VM in Azure and using Azure OpenAI API.

**Comment by rysweet** [comment]
Hi @jobalbz - I'm afraid we will need more info to be able to help - what code were you running/what resource is it that was not found?

**Comment by ekzhu** [comment]
@jobalbz https://autogen-studio.com/autogen-studio-ui is not our site -- we have nothing to do with it.

**Comment by jobalbz** [comment]
i fixed the issue. There was mismatch of the endpoint URL. Use the endpoint URL of the deployed model.
