### ISSUE TITLE
docker image doesn't exist

### ISSUE THREAD

**Issue by minki-j** [microsoft/autogen#3966]
### What happened?

```
 => ERROR [internal] load metadata for mcr.microsoft.com/devcontainers/universal:2            0.2s
------
 > [internal] load metadata for mcr.microsoft.com/devcontainers/universal:2:
------
.devcontainer/Dockerfile:2
--------------------
   1 |     # Note: You can use any Debian/Ubuntu based image you want.
   2 | >>> FROM mcr.microsoft.com/devcontainers/universal:2
   3 |     
   4 |     # [Optional] Uncomment this section to install additional OS packages.
--------------------
ERROR: failed to solve: mcr.microsoft.com/devcontainers/universal:2: failed to resolve source metadata for mcr.microsoft.com/devcontainers/universal:2: no match for platform in manifest: not found
```

### What did you expect to happen?

.

### How can we reproduce it (as minimally and precisely as possible)?

run this command

docker build -f .devcontainer/Dockerfile -t autogen_base_img https://github.com/microsoft/autogen.git#main

### AutoGen version

0.3.1

### Which package was this bug in

Core

**Comment by jackgerrits** [comment]
@rysweet or @kostapetan do you know whats up here?

**Comment by kostapetan** [comment]
@minki-j are you trying to use Codespaces or open the repo in a devcontainer?

**Comment by rysweet** [comment]
I can repro locally but no ida what to do next

**Comment by kostapetan** [comment]
The error @minki-j described suggests that docker didn't find a suitable image for the platform, which I will speculate is some flavor of macOS.
I did run `docker pull mcr.microsoft.com/devcontainers/universal:2` on macOS, Windows and Linux, works on Windows (with linux containers) and Linux, but fails on macOS.
I don't think this is an issue however, as the `devcontainer/Dockerfile` is used to build a devcontainer, locally or in Codespaces and not to actually build any part of the autogen framework.

**Comment by MathavanSG** [comment]
ERROR: failed to solve: mcr.microsoft.com/devcontainers/universal:2: failed to resolve source metadata for mcr.microsoft.com/devcontainers/universal:2: no match for platform in manifest: not found
➜  ~ docker build -f .devcontainer/Dockerfile -t autogen_base_img https://github.com/microsoft/autogen.git\#main
[+] Building 0.9s (2/2) FINISHED                           docker:desktop-linux
 => CACHED [internal] load git source https://github.com/microsoft/autoge  0.7s
 => ERROR [internal] load metadata for mcr.microsoft.com/devcontainers/un  0.2s
------
 > [internal] load metadata for mcr.microsoft.com/devcontainers/universal:2:
------
.devcontainer/Dockerfile:2
--------------------
   1 |     # Note: You can use any Debian/Ubuntu based image you want.
   2 | >>> FROM mcr.microsoft.com/devcontainers/universal:2
   3 |     
   4 |     # [Optional] Uncomment this section to install additional OS packages.
--------------------
ERROR: failed to solve: mcr.microsoft.com/devcontainers/universal:2: failed to resolve source metadata for mcr.microsoft.com/devcontainers/universal:2: no match for platform in manifest: not found
➜  ~ clear

➜  ~ docker build -f .devcontainer/Dockerfile -t autogen_base_img https://github.com/microsoft/autogen.git\#main
[+] Building 0.9s (2/2) FINISHED                           docker:desktop-linux
 => CACHED [internal] load git source https://github.com/microsoft/autoge  0.8s
 => ERROR [internal] load metadata for mcr.microsoft.com/devcontainers/un  0.2s
------
 > [internal] load metadata for mcr.microsoft.com/devcontainers/universal:2:
------
.devcontainer/Dockerfile:2
--------------------
   1 |     # Note: You can use any Debian/Ubuntu based image you want.
   2 | >>> FROM mcr.microsoft.com/devcontainers/universal:2
   3 |     
   4 |     # [Optional] Uncomment this section to install additional OS packages.
--------------------
ERROR: failed to solve: mcr.microsoft.com/devcontainers/universal:2: failed to resolve source metadata for mcr.microsoft.com/devcontainers/universal:2: no match for platform in manifest: not found
➜  ~ docker pull mcr.microsoft.com/devcontainers/universal:2 
2: Pulling from devcontainers/universal

What's next:
    View a summary of image vulnerabilities and recommendations → docker scout quickview mcr.microsoft.com/devcontainers/universal:2
no matching manifest for linux/arm64/v8 in the manifest list entries
➜  ~ 

@kostapetan
