### ISSUE TITLE
Custom Function Tools Cannot Return a List

### ISSUE THREAD

**Issue by gziz** [microsoft/autogen#3987]
### What happened?

I wanted to suggest an addition to the documentation that I believe could help users avoid a potential error when using Custom Function Tools.

**The issue arises when defining a Custom Function Tool that returns a list of objects.** Even though LLMs are typically designed to handle data in a "string in, string out" manner, someone might attempt to define a Function Tool that returns a list of strings, assuming this list could later be converted to a single string. However, doing so will lead to an error that can be somewhat tedious to debug.

### How Does This Error Occur?

In *function_tool.py*, the code checks whether the result from the Custom Function Tool matches the return type specified in the tool's definition. If the user specifies the return type of the Custom Function Tool as a list—such as `List[float]` or `List[str]`—the following issue arises:

The `isinstance` function will throw a `TypeError: "Subscripted generics cannot be used with class and instance checks”`. In this context, a subscripted generic refers to a type like `List[float]`.

Since this error is not caught, it causes the agent calling the function (e.g., a ToolAgent) to return an empty string, making the issue harder to debug for the user or LLM.

```python
# _function_tool.py
if not isinstance(result, self.return_type()):
    raise ValueError(f"Expected return type {self.return_type()}, got {type(result)}")

```

I haven’t created a pull request to modify the documentation to explicitly warn against returning a list from a Function Tool. This is because I think there could be a discussion beforehand about whether`ToolFunction` should support lists as a return type.
Whatever's decided, I can handle the changes and create a PR for it.

### What did you expect to happen?

The custom function tool could return lists or handle the error in a different way. 
Alternatively, just specify in the docs that the function cannot return lists.

### How can we reproduce it (as minimally and precisely as possible)?

To reproduce it, one could run the example in the weather [custom tool documentation](https://microsoft.github.io/autogen/0.4.0.dev2/user-guide/core-user-guide/framework/tools.html). However, instead of returning float, imagine a custom tool that returned a List of floats `List[float]`.

### AutoGen version

0.4dev2

### Which package was this bug in

Core

**Comment by ekzhu** [comment]
@gziz thank you this is an important issue. We should support `List[float]` type of annotation in the function tool. I think the first step is to remove the `isinstance` check and just return the object as is. I believe it is the responsibility of the caller to check and serialize the return value into string for the next LLM call.

If there is a way to annotate the return type of `run_json` dynamically with the return type of the input function, it would be great for usability. Perhaps through use of generics.

**Comment by gziz** [comment]
Hi @ekzhu, could you elaborate on a scenario where dynamically assigning the return type of `run_json` would improve usability? This would help me better understand how to implement it.  
Thanks!

**Comment by ekzhu** [comment]
It is not required to fix this issue. But here is an example:

```python

async def func(input: str) -> List[float]:
    return [0.1, 0.2]

tool = FunctionTool(func, description="return a list")

result = await tool.run_json(arguments, cancellation_token)
```

During type checking inside an IDE, we can infer the type of `result` is `List[float]`. This makes it easy for type check to validate the usage of `result` follows the type `List[float]`.

**Comment by gziz** [comment]
Ok.

So it seems like we have two options:

1. Remove the isinstance check.
2. Improve the isinstance logic to handle Subscripted generics, we could do something like this:

```python
def check_list(result, elem_type):
	# ensure all elements are elem_type

def check_tuple(result, elem_types):
	# ensure all elems are elem_types

def check_dict(result, key_type, value_type):
	# ensure all key-value pairs correspond to the expected value

def check_type(result, expected_type):
    origin = get_origin(expected_type)
    args = get_args(expected_type)
    
    if origin is list:
        check_list(result, args[0] if args else Any)
    elif origin is tuple:
        check_tuple(result, args)
    elif origin is dict:
        check_dict(result, args[0], args[1])
    else:
        # For non-generic types, just do a regular isinstance check
        if not isinstance(result, expected_type):
            raise ValueError(f"Expected return type {expected_type}, got {type(result)}")
    return result

# the modify inside _funtion_tool.py to have

check_type(result, self.return_type())
return result
```

The downside being that we would add lots of code to handle every potential `typing` Subscripted generic.

**Comment by ekzhu** [comment]
I agree with you. Option 1 is easier: we need to better document `FunctionTool` in its doc string as well with example code blocks etc.
