### ISSUE TITLE
Autogen.* tests hang in CI about 20% of the time

### ISSUE THREAD

**Issue by rysweet** [microsoft/autogen#3994]
### What happened?

too frequently the AutoGen.* tests hang in CI and spin until GH actions cancels the job and fails the test after 30m. 
re-running the job usually works. 

### What did you expect to happen?

consistent pass/fail

### How can we reproduce it (as minimally and precisely as possible)?

just run CI

### AutoGen version

0.4

### Which package was this bug in

Core

**Comment by LittleLittleCloud** [comment]
It hangs again after #3982 ?

**Comment by LittleLittleCloud** [comment]
Hit again, let's just disable all dotnet interactive stdio tests

**Comment by rysweet** [comment]
is resolved.
