### ISSUE TITLE
Include Metric in AgentChat Messages

### ISSUE THREAD

**Issue by victordibia** [microsoft/autogen#4017]
### What feature would you like to be added?

Currently messages in AgentChat contain source and content fields.
Goal is to extend this to also include metrics that applications can consume.
Some candidate metrics are listed below

- Tokens (prompt, output)
- Cost (if available) 
- Tool call status (pass or fail where available)

 There should be clear ways to associate each message with the agent/team that produces it.

### Why is this needed?

Most applications need to visualize metrics for debugging purposes.

**Comment by ekzhu** [comment]
Once we have this, let's add a termination condition with token/cost budget https://github.com/microsoft/autogen/issues/4022

**Comment by victordibia** [comment]
Yup that makes sense
