### ISSUE TITLE
Timer-based termination condition

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#4038]
### What feature would you like to be added?

A `TerminationCondition` class that starts a timer when created and will terminate once the timer goes off.

### Why is this needed?

To limit the resource usage of a team.

**Comment by victordibia** [comment]
Good idea.
Blends with how I have been thinking of this.

- Implict llm based termination (similar to what we do with teams, orchestrators that emit a termination signal)
- external monitor based termination (having a truly decoupled system) 
- budget based termination ... ends based when some budget is exhaused .. cost, tokens, time, memory, etc ..
-
