### ISSUE TITLE
Error with Quick Start

### ISSUE THREAD

**Issue by CJFEdu** [microsoft/autogen#4063]
### What happened?

It got the following output trying to get the [Quick Start](https://microsoft.github.io/autogen/0.4.0.dev3/user-guide/core-user-guide/quickstart.html) code to work.  I made some minor changes to the prompt because it was generating fake data rather than trying to pull original data.  

The prompt I used was pretty close to.

`Create a plot of NVDA vs TSLA stock returns YTD from 2024-01-01.
Download real world data.
Don't use sudo in the command line.`

I also made a modification to run this in an async function.  I don't think this affected the error, because it ran properly once before.  However, I'll include the full function just for thoroughness.

```python
async def main():
    async with DockerCommandLineCodeExecutor(work_dir=work_dir) as executor:  # type: ignore[syntax]
        # Register the assistant and executor agents by providing
        # their agent types, the factory functions for creating instances and subscriptions.
        await Assistant.register(
            runtime,
            "assistant",
            lambda: Assistant(
                OpenAIChatCompletionClient(
                    model="gpt-4o",
                    api_key=os.getenv("OPENAI_API_KEY")
                )
            ),
        )
        await Executor.register(runtime, "executor", lambda: Executor(executor))

        # Start the runtime and publish a message to the assistant.
        runtime.start()
        await runtime.publish_message(
            Message(instruction), DefaultTopicId()
        )
        await runtime.stop_when_idle()

# Run the async main function
asyncio.run(main())
```

````
--------------------------------------------------------------------------------
Assistant:
The `!pip install` command is specific to Jupyter notebooks and similar interactive environments. Since we are in a standard script environment, let's try a different approach.

You can install the `yfinance` package by running the following command directly in your terminal or command prompt (not in the Python script):

```
pip install yfinance
```

After installing `yfinance`, rerun the Python script. Here's the script again for your convenience:

```python
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt

# Define the start and end dates
start_date = "2024-01-01"
end_date = pd.Timestamp.today().strftime('%Y-%m-%d')  # Today's date

# Define the stock tickers
tickers = ["NVDA", "TSLA"]

# Download the stock data
data = yf.download(tickers, start=start_date, end=end_date)

# Calculate daily returns
returns = data['Adj Close'].pct_change().dropna()

# Plot the returns
plt.figure(figsize=(10, 6))
for ticker in tickers:
    plt.plot(returns.index, returns[ticker], label=ticker)

plt.title('YTD Stock Returns for NVDA and TSLA (2024)')
plt.xlabel('Date')
plt.ylabel('Daily Returns')
plt.legend()
plt.savefig('nvda_vs_tsla_2024_returns.png')
```
Error processing publish message
Traceback (most recent call last):
  File "/path/to/folder/.venv/lib/python3.12/site-packages/autogen_core/application/_single_threaded_agent_runtime.py", line 385, in _process_publish
    await asyncio.gather(*responses)
  File "/path/to/folder/.venv/lib/python3.12/site-packages/autogen_core/application/_single_threaded_agent_runtime.py", line 377, in _on_message
    return await agent.on_message(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/folder/.venv/lib/python3.12/site-packages/autogen_core/components/_routed_agent.py", line 468, in on_message
    return await h(self, message, ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/folder/.venv/lib/python3.12/site-packages/autogen_core/components/_routed_agent.py", line 148, in wrapper
    return_value = await func(self, message, ctx)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/folder/autogen_agents.py", line 52, in handle_message
    result = await self._code_executor.execute_code_blocks(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/folder/.venv/lib/python3.12/site-packages/autogen_ext/code_executors/_docker_code_executor.py", line 284, in execute_code_blocks
    return await self._execute_code_dont_check_setup(code_blocks, cancellation_token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/folder/.venv/lib/python3.12/site-packages/autogen_ext/code_executors/_docker_code_executor.py", line 249, in _execute_code_dont_check_setup
    command = ["timeout", str(self._timeout), lang_to_cmd(lang), filename]
                                              ^^^^^^^^^^^^^^^^^
  File "/path/to/folder/.venv/lib/python3.12/site-packages/autogen_core/components/code_executor/_impl/utils.py", line 78, in lang_to_cmd
    raise ValueError(f"Unsupported language: {lang}")
ValueError: Unsupported language: 


````

### What did you expect to happen?

The message to be processed as usual.

### How can we reproduce it (as minimally and precisely as possible)?

Explained in the beginning.

### AutoGen version

0.4.0.dev3

### Which package was this bug in

Core

### Model used

gpt-4o

### Python version

python3.12

### Operating system

Ubuntu 24.04

**Comment by ekzhu** [comment]
Modified the issue description to use "````" quote for the output block.


You can see this markdown code block in the output:

````
```
pip install yfinance
```
````

It doesn't have a language annotation. So, the language annotation becomes an empty string. The `Executor`'s code executor cannot understand it. 

To fix this we can throw a value error in the `Executor` if the language is not detected.

**Comment by peterychang** [comment]
In the given sample outputs, the code executor gets 2 code blocks, the first of which fails to execute because it has no language tagged on it. Realistically, this should be tagged as `sh`. I wonder if we can just add a section to the code executor's description, basically adding

`f"All code blocks must be tagged with one of the following languages: {_executor.SUPPORTED_LANGUAGES}"`

this would get around cases where we execute only some of the code blocks and potentially break the execution environment

**Comment by ekzhu** [comment]
Yep. Though I was thinking if we can even remove the quick start -- it is not quick but rather complex, and I the Framework Guide already does a job to take the reader through the basic concepts. 

We can move the quick start example to a multi-agent design pattern page.

**Comment by peterychang** [comment]
I'm not actually able to reproduce this issue, every run I've tried has chatgpt correctly label the code block as `bash` (both the dev branch and the dev3 release branch).

@CJFEdu can you try running the example again on the latest release (dev11)? In the meantime I'll add additional prompting to try and ensure an LLM correctly labels their code blocks

**Comment by ekzhu** [comment]
Resolved as the quick start is updated.
