### ISSUE TITLE
Real-time visualization of AGS agent message exchange for improved debugging

### ISSUE THREAD

**Issue by victordibia** [microsoft/autogen#4067]
In AutoGen Studio, add an optional panel to visualize message exchange between agents as the task progresses.

**Comment by victordibia** [comment]
@ekzhu .

Messages from agents in AgentChat have a `source` and `content` field.
To construct graphs on the flow of data between agents (useful in a UI for visualizing transitions and state), we need to infer the `receiver`.
In an event/message driven setting, this can be challenging as message is sent and could be processed by any arbitrary receipient (based on the communication protocol).

One way to visualize transitions on current design:
- Keep track of an active node (node that just sent a message) 
- When there is n>2 messages, visualize the last transition + active node 

Happy to hear your  general thoughts on the above.

**Comment by ekzhu** [comment]
Once #4075 is in we can use intervention handlers to emit events whenever an agent receives a message
