### ISSUE TITLE
Include maximum Python version in the installation guide

### ISSUE THREAD

**Issue by lqdev** [microsoft/autogen#4084]
### What happened?

While installing 'autogen-core==0.4.0.dev4' on Python 3.13, it failed. Installing 3.12 worked. What's the highest version supported?

### What did you expect to happen?

Packages install successfully

### How can we reproduce it (as minimally and precisely as possible)?

Install 'autogen-core==0.4.0.dev4' on Debian Bookworm with Python 3.13.

### AutoGen version

0.4.0.dev4

### Which package was this bug in

Core

**Comment by jackgerrits** [comment]
Can you share the error you are getting? Python 3.13 is meant to be supported.

**Comment by jackgerrits** [comment]
We don't have a max version. There is a dependency issue to do with grpc, but that is now an optional dep (tracked here #4278). Min version is stated on the install page.
