### ISSUE TITLE
Why do we have code_executor and code_executors?

### ISSUE THREAD

**Issue by thinkall** [microsoft/autogen#4087]
Shouldn't we use either `code_executor` or `code_executors` ?

![Image](https://github.com/user-attachments/assets/3b7cb3dc-64ae-44f5-a299-021513d4a1ae)

**Comment by ekzhu** [comment]
@lspinheiro

**Comment by jackgerrits** [comment]
One of them is just a compat shim so we don’t break people using an earlier version. We’ll remove that in time when people have had enough chance to notice the warning and fix their code.

**Comment by lspinheiro** [comment]
What Jack said. I can help with the clean up once we have a clear idea of when we want to introduce breaking changes. Maybe when we are about to go out of 0.4.0.devx?

**Comment by lspinheiro** [comment]
Sounds good. Picking this up today
