### ISSUE TITLE
Consider rename "termination" to "stop" in AgentChat

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#4089]
Rename `TerminationCondition` to `StopCondition` and `TextMentionTermination` to `TextMentionStopCondition`, etc.

Right now termination conditions are used to pause/stop the team's run, rather than completely closing it.

**Comment by victordibia** [comment]
There might be some nuance here. 

There seem to be two behaviors that can be realized with termination conditions after `team.run()` is called.

- 1. **Single call to `team.run()`**:   if `team.reset()` is **never** called, then those conditions are indeed termination conditions. The run does terminate there.
- 2. **Multiple calls to `team.run()`**: if `team.reset()` is called followed by another  `team.run()`, the termination condition behaves _kinda like_ a stop/pause. Or more accurately it marks a stopping point where the agents (and their data) from previous `team.run()` is still held **in memory** and a subsequent  `team.run()` call continues the `run` process.

One way to chose the name is to follow the most used / happy path rule and document both behaviors. What behavior is likely to be used more often? I think scenarios with a single run might be more common, but happy to hear thoughts.

**Comment by ekzhu** [comment]
> One way to chose the name is to follow the most used / happy path rule and document both behaviors. What behavior is likely to be used more often? I think scenarios with a single run might be more common, but happy to hear thoughts.

Good point. This is why I think we shouldn't call it "pause". "Stop" seems like a more natural term that encapsulates both "pause" and "termination".

**Comment by victordibia** [comment]
@afourney , @husseinmozannar , @gagb

**Comment by afourney** [comment]
When it stops (pauses), do we call a method to extract a final answer from the transcript? How does this factor in?

**Comment by jackgerrits** [comment]
Too disruptive and not high enough value
