### ISSUE TITLE
Error while using RAG agent

### ISSUE THREAD

**Issue by tytung2020** [microsoft/autogen#410]
Ran into the following error:
![Screenshot (601)](https://github.com/microsoft/autogen/assets/37324680/8681eeb8-89b4-41b6-b04b-ce08b1780906)

the code that outputs the error is as follows:
![Screenshot (604)](https://github.com/microsoft/autogen/assets/37324680/e343c56c-41d4-47d0-91e1-2be642fc15f5)

as seen from the error message above, it seems the document is embedded, but the chat is somehow not started.

**Comment by thinkall** [comment]
@tytung2020 task can only be "qa", "code" or "default".
