### ISSUE TITLE
The generated code  is not compele

### ISSUE THREAD

**Issue by MrSchnappi** [microsoft/autogen#413]
I used AutoGen to complete a complex task and utilized the gpt-3.5-turbo model. However, whenever the language model generates code and displays it in the console, it always appears incomplete. I would like to know whether it is due to an issue with the language model itself or if there is a maximum length limit imposed on the output logs.

**Comment by afourney** [comment]
If it looks incomplete, it is likely running out of tokens in the generation in the call to OpenAI. The console output should show everything that was generated. Are you using the gpt-3.5-turbo-**16k**? You can turn on logging to see what's being sent and received from OpenAI.

https://microsoft.github.io/autogen/docs/reference/oai/completion#start_logging

**Comment by MrSchnappi** [comment]
OK , ThX
