### ISSUE TITLE
udocker support

### ISSUE THREAD

**Issue by productdeployer** [microsoft/autogen#4151]
### What feature would you like to be added?

Hello,

seems it only works with docker, is there udocker support ?

### Why is this needed?

this allows magnetic one to work on more systems.
udocker is a basic user tool to execute simple docker containers in user space without requiring root privileges. Enables download and execution of docker containers by non-privileged users in Linux systems where docker is not available

**Comment by jackgerrits** [comment]
We don't have plans currently of built in support for udocker, if there is enough interest this could be revisited.

However, if you or anyone else would like to build a code executor to support this and publish it as a community extension then that would be great! The [existing docker executor](https://github.com/microsoft/autogen/blob/main/python/packages/autogen-ext/src/autogen_ext/code_executors/_docker_code_executor.py) might be a good template to start from. You can find more info about community extensions [here](https://microsoft.github.io/autogen/dev/user-guide/extensions-user-guide/index.html).
