### ISSUE TITLE
Not clear error message when agent name is not valid (0.2 branch).

### ISSUE THREAD

**Issue by giorgossideris** [microsoft/autogen#4157]
### What feature would you like to be added?

**This issue refers to the [0.2 branch](https://github.com/microsoft/autogen/tree/0.2).**

The message when an agent name is not valid (based on the OpenAI's expected pattern) should be clearer (this problem is fixed in the `main` branch [here](https://github.com/microsoft/autogen/blob/main/python/packages/autogen-agentchat/src/autogen_agentchat/agents/_base_chat_agent.py#L15C9-L16C41)).

The message right now is: 
`BadRequestError: Error code: 400 - {'error': {'message': "Invalid 'messages[1].name': string does not match pattern. Expected a string that matches the pattern '^[a-zA-Z0-9_-]+$'.", 'type': 'invalid_request_error', 'param': 'messages[1].name', 'code': 'invalid_value'}}`

### Why is this needed?

It will be easier to identify the problem.

**Comment by jackgerrits** [comment]
Closing as not-planned/wontfix for now with rationale in this comment: https://github.com/microsoft/autogen/pull/4158#issuecomment-2479258774
