### ISSUE TITLE
assistant_agent's system prompt contains an invalid escape character

### ISSUE THREAD

**Issue by qcloop** [microsoft/autogen#4169]
Backlash character in the [prompt](https://github.com/microsoft/autogen/blob/16463a8a9851f5adb54c4685d443f5d749f052a2/python/packages/autogen-agentchat/src/autogen_agentchat/agents/_assistant_agent.py#L168) needs to be escaped, otherwise it causes issues when sending it as JSON payload.

i.e. from current

{
            "content": "You are a helpful AI assistant. Solve tasks using your tools. Reply with \'TERMINATE\' when the task has been completed.",
            "role": "system"
        }

to 

{
            "content": "You are a helpful AI assistant. Solve tasks using your tools. Reply with \\'TERMINATE\\' when the task has been completed.",
            "role": "system"
        }

**Comment by victordibia** [comment]
Thanks for the note @qcloop .
Can you show a concrete example of the errors you are seeing?

@ekzhu .. thoughts?

**Comment by qcloop** [comment]
We have a propriatery LLM which we are trying to leverage with Autogen. I was getting an 400 error that could not decipher. So I decided to get the actual request to an LLM and try it out using Postman REST API tool. Attached is the Postman with the JSON payload, and Postman complaining about "Invalid Escape Chara![Image](https://github.com/user-attachments/assets/2deafd73-f3ef-4cc3-b949-cc16c862d31c)
cter"

**Comment by ekzhu** [comment]
This seems very LLM specific. Let's just remove the quotes for now.

**Comment by ekzhu** [comment]
Resolved by #4231

**Comment by ekzhu** [comment]
Resolved by #4231
