### ISSUE TITLE
Error: "message" needs to be provided if the `generate_init_message` method is not overridden.

### ISSUE THREAD

**Issue by hellocaio** [microsoft/autogen#422]
Hello,

Could someone please enligten me about this error? I've been trying to learn AutoGen and create my own application that can answer simple questions, fetch data from API or from local ChromaDB. It is an amazing tool! I had it working but recently I've been getting this error and have no idea how to solve it.

I suspect it is something to do with the API endpoints? Because when I run the notebooks provided in the source code on Github Codespaces I get this same error at times. The following error came from `notebook/agentchat_chess.ipynb`. All I did was changed OAI_CONFIG_LIST with my keys and ran the code.

Thanks!

<img width="600" alt="Screenshot 2023-10-25 at 13 44 00" src="https://github.com/microsoft/autogen/assets/42479948/808fe144-b430-4425-b4b4-9970526c7c88">

**Comment by hellocaio** [comment]
Thanks for pointing me in the right direction. The error appears related to OpenAI endpoint, I ran out of credit, oops. Can I use only Azure OpenAI or OpenAI is required? I ask because I have a lot of credit in Azure but when I try run it with only Azure OpenAI it fails. Thanks!

**Comment by afourney** [comment]
You can just use Azure, yes. Just remove any  OpenAI entries in the confit_list

**Comment by caioatpluto** [comment]
Awesome, thank you! It was lack of credit after all, I ended up running some complex requests on gpt-4 and it drained my credits but it was worth it. :)

**Comment by hellocaio** [comment]
Awesome, thank you! It was lack of credit after all, I ended up running some complex requests on gpt-4 and it drained my credits but it was worth it. :)
