### ISSUE TITLE
Function mapping is not working

### ISSUE THREAD

**Issue by AlbelTec** [microsoft/autogen#427]
Hi,
I'm trying to understand how functions are executed. But the weird thing is seems that rely only openai llms. Because in my case the function is never triggered :

here is my code : to start with function I just created a dummy function. and then I'm calling it

```
import autogen 

config_list = [
    {
        'api_type': 'open_ai',
        'api_base':'http://localhost:7500/v1',
        'api_key': 'NULL'
    }
]

def answer_my_question():
    return "LangChain provides standard, extendable interfaces and external integrations for the following modules, listed from least to most complex."

llm_config={
    "request_timeout": 600,
    "seed": 42,
    "config_list": config_list,
    "temperature": 0,
    "functions": [
        {
            "name": "answer_my_question",
            "description": "Answer any related question"
        }
    ],
}

assistant = autogen.AssistantAgent(
    name="assistant",
    system_message="Only use the functions you have been provided with. Do not ask the user to perform other actions than executing the functions.",
    llm_config=llm_config,
    is_termination_msg=lambda x: x.get("content", "").rstrip().endswith("TERMINATE"),
)

user_proxy = autogen.UserProxyAgent(
    name="user_proxy",
    human_input_mode="NEVER",
    max_consecutive_auto_reply=10,
    is_termination_msg=lambda x: x.get("content", "").rstrip().endswith("TERMINATE"),
    code_execution_config=False,
    llm_config=llm_config,
    system_message="""Reply TERMINATE if the task has been solved at full satisfaction. Otherwise, reply CONTINUE, or the reason why the task is not solved yet.""",
    function_map={"answer_my_question": answer_my_question}
)

user_proxy.initiate_chat(
    assistant,
    message="""
I want you to answer this following question:

what LangChain provides?

Start the work now.
"""
) 
```

and the output is just a kind of random text generation :

```
user_proxy (to assistant):

I want you to answer this following question:

what LangChain provides?

Start the work now.

--------------------------------------------------------------------------------
assistant (to user_proxy):

LangChain is a decentralized platform that enables users to create, share and execute smart contracts on the Ethereum blockchain. It provides a user-friendly interface for creating and deploying smart contracts, as well as tools for managing and executing them. LangChain also offers a range of features such as gas optimization, contract auditing, and contract monitoring, which help users to ensure that their smart contracts are secure and efficient. Additionally, LangChain provides a community of developers who can assist with any questions or issues related to smart contracts on the Ethereum blockchain.

--------------------------------------------------------------------------------
user_proxy (to assistant):

Is there anything else you need to know?

--------------------------------------------------------------------------------
assistant (to user_proxy):

No, that is all I need to know. Thank you for your help.

--------------------------------------------------------------------------------
user_proxy (to assistant):

Reply TERMINATE

--------------------------------------------------------------------------------
```
any insights ?

**Comment by gagb** [comment]
Which model are you using? 


What if you used a different function that is not in the model parametric knowledge:

eg 

```
def print_secret():
    return "This is secret"
```
Then initiate the chat with "please print the secret"

**Comment by AlbelTec** [comment]
Hi 
I'm using Mistral-Instruct-7B

**Comment by AlbelTec** [comment]
@gagb 
here is the output : 

```
user_proxy (to assistant):

 please print the secret 

--------------------------------------------------------------------------------
assistant (to user_proxy):


def print_secret(secret):
    print("The secret is:", secret)

def get_secret():
    return "This is a secret"

print_secret(get_secret())

--------------------------------------------------------------------------------
user_proxy (to assistant):


TERMINATE 
```
it ignores whether a function is called or not. 

Do you have any example that I can run with local llm (.gguf) ?

**Comment by gagb** [comment]
> Hi I'm using Mistral-Instruct-7B

@victordibia my understanding is the Mistral models don't have function call support. Is that correct? Maybe that explains why this is being ignored.

**Comment by rainfd** [comment]
@AlbelTec Currently only GPT and a few online LLMS support function calling api, If you want to use function calling in Mistral-Instruct-7B, You should refer to langchain Agent prompt implementations such as ReAct Agent. And I've used it this way before with the same model, and it doesn't work very well.

**Comment by rainfd** [comment]
@AlbelTec Currently only GPT and a few online LLMS support function calling api, If you want to use function calling in Mistral-Instruct-7B, You should refer to langchain Agent prompt implementations such as ReAct Agent. And I've used it this way before with the same model, and it doesn't work very well.

**Comment by AlbelTec** [comment]
@rainfd Thanks for your feedback. it's clear for me now.

**Comment by victordibia** [comment]
I have seen a few work arounds where the function itself is appended to the prompt. 
litellm seems to do [that](https://github.com/BerriAI/litellm/issues/664#issuecomment-1773870191). 

> @peterz3g here's how you can do function calling for non openai llms: https://docs.litellm.ai/docs/completion/function_call#function-calling-for-non-openai-llms
We add the function call to the prompt when you set litellm.add_function_to_prompt = True 
did this not work for you?

**Comment by jhachirag7** [comment]
model-> meta/llama3-70b-instruct is it supports function mapping?

**Comment by jhachirag7** [comment]
llm_config_content_assistant = {
    "functions": [
        {
            "name": "research",
            "description": "research about a given topic, return the research material including reference links",
            "parameters": {
                    "type": "object",
                    "properties": {
                        "query": {
                            "type": "string",
                            "description": "The topic to be researched about",
                        }
                    },
                "required": ["query"],
            },
        },
        {
            "name": "write_content",
            "description": "Write content based on the given research material & topic",
            "parameters": {
                    "type": "object",
                    "properties": {
                        "research_material": {
                            "type": "string",
                            "description": "research material of a given topic, including reference links when available",
                        },
                        "topic": {
                            "type": "string",
                            "description": "The topic of the content",
                        }
                    },
                "required": ["research_material", "topic"],
            },
        },
    ],
    "config_list": config_list}


writing_assistant = autogen.AssistantAgent(
    name="writing_assistant",
    system_message="You are a writing assistant, you can use research function to collect latest information about a given topic, and then use write_content function to write a very well written content; Reply TERMINATE when your task is done",
    llm_config=llm_config_content_assistant,
)

user_proxy = autogen.UserProxyAgent(
    name="User_proxy",
    human_input_mode="TERMINATE",
    code_execution_config=False,
    function_map={
        "write_content": write_content,
        "research": research,
    }
)
list= ["Machine learning", "health"]
user_proxy.initiate_chat(
    writing_assistant, message=f"write a blog about keywords mentioned in the list {list}")



i also ran to same problem it's not calling the research function
