### ISSUE TITLE
Can AutoGen access publicly available external data and/or locally saved data?

### ISSUE THREAD

**Issue by ViperVille007** [microsoft/autogen#429]
Is it possible to have Autogen agents make use of external data (say, a dataset from Kaggle) and then perform some tasks on it (simple data analysis,etc) ?
Also, can we feed data that we have saved locally (any .csv or .text file) and perform a similar task?

**Comment by gagb** [comment]
Yes put the data in the work_dir. Eg the work_dir is set to coding in the quick start example https://github.com/microsoft/autogen#multi-agent-conversation-framework

**Comment by sonichi** [comment]
Example: https://github.com/microsoft/autogen/blob/main/notebook/agentchat_groupchat_vis.ipynb
