### ISSUE TITLE
What is the current way to export an thread and preload a chat with a team in v0.4

### ISSUE THREAD

**Issue by bih** [microsoft/autogen#4327]
I'm fairly new to the AutoGen project and we're exploring it for our use case, but as I was prototyping it in a notebook I was wondering what is the way for us to be able to export a chat and preload it in a team. For example:

```python
team = SelectorGroupChat(
    participants=[customer_service_agent, manager_agent, finance_agent],
    allow_repeated_speaker=False,
    model_client=OpenAIChatCompletionClient(model="gpt-4o"),
)
```

I can do this to get the conversation history

```python
conversation = await team.run(task="Hello I would like a refund!")
print(conversation.messages)
```

But I would love to be able to export it as JSON

```python
import json

conversation = await team.run(task="Hello I would like a refund!")
print(json.dumps(conversation.messages))
```

And equally I would love to be able to import the conversation history JSON so anything ran against in `team.run()`

```python
conversation_history = json.loads(conversation_history_json)
conversation = await team.run(conversation=conversation_history, task="Hi world!")
```

Also, is it possible to message the agents with nothing (ideally as a specific flag)? We would love to be able to have agents give a meaningful intro message, but this isn't critical - we can build workarounds for this.

Note that this is for the v0.4 release!

**Comment by victordibia** [comment]
Hi @bih ,

We are currently working a memory interface that should help with this.
These capabilities are being tracked in issue #4039  and #4100 . 
Stay tuned.

**Comment by bih** [comment]
Sounds good, thanks for the quick response!

**Comment by victordibia** [comment]
Hi @bih ,

We have the PR for loading/saving state merged into main (should be available in the next dev release).
 
Documentation page is [here](https://microsoft.github.io/autogen/dev/user-guide/agentchat-user-guide/tutorial/state.html) 


Save state ..
```python
# Define a team.
assistant_agent = AssistantAgent(
    name="assistant_agent",
    system_message="You are a helpful assistant",
    model_client=OpenAIChatCompletionClient(
        model="gpt-4o-2024-08-06",
    ),
)
agent_team = RoundRobinGroupChat([assistant_agent], termination_condition=MaxMessageTermination(max_messages=2))

# Run the team and stream messages to the console.
stream = agent_team.run_stream(task="Write a beautiful poem 3-line about lake tangayika")

# Use asyncio.run(...) when running in a script.
await Console(stream)

# Save the state of the agent team.
team_state = await agent_team.save_state()
```

load team state

```python
print(team_state)

# Load team state.
await agent_team.load_state(team_state)
stream = agent_team.run_stream(task="What was the last line of the poem you wrote?")
await Console(stream)
```

Let us know if it works for you.

**Comment by zzzzxcshuijiao** [comment]
If load_state work in anther context, how can i get the agent_team instance? In the same context, i don't need get team instance by load_state method

**Comment by victordibia** [comment]
Does this work for you / answer your question?

## To Save Your Team

```python
# 1. Run your team
# 2. Get the team state
team_state = await agent_team.save_state()

# 3. Save the team state to disk
with open('teamstate.json', 'w') as f:
    json.dump(team_state.model_dump(), f)
```

## To Load Your Team Back

```python

from autogen_agentchat.state import TeamState

# 1. Create the team
agent_team = RoundRobinGroupChat(
    [assistant_agent], 
    termination_condition=MaxMessageTermination(max_messages=2)
)

# 2. Load the saved state from disk
with open('teamstate.json', 'r') as f:
    team_state_data = json.load(f)
team_state = TeamState(**team_state_data)

# 3. Apply the state to the team
team.load_state(team_state)
```
