### ISSUE TITLE
Tutorial Chapter on Termination Conditions

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#4334]
The current chapter on termination conditions is outdated.  Examples of how to use termination conditions already exists in the previous chapters, so in this chapter just focus on the mechanism, and list the built-in termination conditions. 

It is important to note the termination conditions are reset automatically after each `run` and `run_stream`.

**Comment by victordibia** [comment]
Also that they can be combined. 
E.g.
```python

termination = termination = MaxMessageTermination(3) | TextMentionTermination("stop")
termination = termination = MaxMessageTermination(3)  & TextMentionTermination("stop")
```
