### ISSUE TITLE
Fix code scanning alert - Websites must specify the HttpOnly attribute on sensitive cookies

### ISSUE THREAD

**Issue by rysweet** [microsoft/autogen#4367]
Tracking issue for:
- [ ] https://github.com/microsoft/autogen/security/code-scanning/4775

**Comment by rysweet** [comment]
looks like a transient fp to me. @LittleLittleCloud can you please have a look?

**Comment by LittleLittleCloud** [comment]
Let's see if this warning goes away in the future ommits

**Comment by LittleLittleCloud** [comment]
Semantic kernel also hits the same issue. @markwallace-microsoft creates an issue in codeql repo for tracking
- https://github.com/github/codeql/issues/18119
