### ISSUE TITLE
RAG error: cannot import name 'API' from 'chromadb.api' (/usr/local/lib/python3.10/dist-packages/chromadb/api/__init__.py)

### ISSUE THREAD

**Issue by daniel-counto** [microsoft/autogen#437]
![Screenshot (605)](https://github.com/microsoft/autogen/assets/140989990/3eb71894-9567-4177-86e0-632e4760db0b)

`from autogen.agentchat.contrib.retrieve_user_proxy_agent import RetrieveUserProxyAgent` gives the above error, which only happens starting today. It worked fine yesterday and before. Anything changed in the library?

**Comment by gagb** [comment]
@rickyloynd-microsoft

**Comment by rickyloynd-microsoft** [comment]
Chromadb just made a change to their api. @thinkall has a PR #435 to fix this.

**Comment by tytung2020** [comment]
> Chromadb just made a change to their api. @thinkall has a PR #435 to fix this.

not sure how to fix it in colab, could anyone elaborate?

**Comment by thinkall** [comment]
> > Chromadb just made a change to their api. @thinkall has a PR #435 to fix this.
> 
> not sure how to fix it in colab, could anyone elaborate?

`pip install "chromadb<0.4.15"`

**Comment by Owaiskhan9654** [comment]
@sonichi This issue can be marked as closed now.
