### ISSUE TITLE
Questions about tools and agent

### ISSUE THREAD

**Issue by deku0818** [microsoft/autogen#438]
I define a tool in autogen, and then have a group chat and find that all agents can use this tool, I want to specify a certain agent to use this tool, but other agents can not use it. What should I do?

**Comment by gagb** [comment]
By tools do you mean function calls?  If so, consider only making a subset of AssistantAgents aware of the functions. They'll use a different llm_config compared to others.

**Comment by deku0818** [comment]
> By tools do you mean function calls? If so, consider only making a subset of AssistantAgents aware of the functions. They'll use a different llm_config compared to others.你所说的工具是指函数调用吗？如果是这样，请考虑仅让一部分 AssistantAgent 了解这些功能。与其他人相比，他们将使用不同的 llm_config 。

Thank you! But How to control the order of speaking

**Comment by gagb** [comment]
@LittleLittleCloud may have advice for controling order

**Comment by sonichi** [comment]
@deku0818 How would you like the speaking order to be? Static?

**Comment by deku0818** [comment]
> @deku0818 How would you like the speaking order to be? Static? 您希望发言顺序如何？静止的？

can be static,
I have a relatively fixed workflow, but it can't be that my agents run in a certain order.I want to achieve the effect that when I propose a problem, the agent will split the problem, obtain the corresponding information from my knowledge base, and then combine the information to generate code to solve the problem

**Comment by sonichi** [comment]
Have you considered using https://microsoft.github.io/autogen/blog/2023/10/18/RetrieveChat to solve it? @thinkall is the author of it.

**Comment by thinkall** [comment]
Tool/function usage is convenient now, close this very old issue.

**Comment by mynewstart** [comment]
I have bind the coder agent with retrieve_reviews_AND_deals. But I found task_planner agent also can use this tool. I created a groupmanger, both coder agent an task_planner agent are in

register_function(
    retrieve_reviews_AND_deals,
    caller=coder,  
    executor=user_proxy, 
    name="retrieve_ASIN_reviews_AND_deals",  
)
