### ISSUE TITLE
ModuleNotFoundError: No module named 'autogen_agentchat'

### ISSUE THREAD

**Issue by sanjaylalwani** [microsoft/autogen#4396]
I have installed autogen with pip install 'autogen-agentchat==0.4.0.dev7'
But its throwing error now as below,

`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[3], [line 1](vscode-notebook-cell:?execution_count=3&line=1)
----> [1](vscode-notebook-cell:?execution_count=3&line=1) from autogen_agentchat.agents import AssistantAgent
      [2](vscode-notebook-cell:?execution_count=3&line=2) from autogen_agentchat.messages import TextMessage
      [3](vscode-notebook-cell:?execution_count=3&line=3) from autogen_core.base import CancellationToken

ModuleNotFoundError: No module named 'autogen_agentchat'`

**Comment by ekzhu** [comment]
Could you please share your minimum reproduction? There is a known bug in missing dep for grpc but this is not it.

**Comment by ekzhu** [comment]
Closing this. Please check if this has been fixed with latest dev8 release.
