### ISSUE TITLE
Same "OAI_CONFIG_LIST" file in codespaces work but failed in docker

### ISSUE THREAD

**Issue by Hanochhu** [microsoft/autogen#440]
I try autogen in Codespaces in github, and create a "OAI_CONFIG_LIST" file like 
![image](https://github.com/microsoft/autogen/assets/52187558/09274a32-ec78-4a2c-97c8-15f3ea1b7b3a)

it's work but when I paste same file in docker container ,there is an error :
AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'.

**Comment by elecnix** [comment]
I also noticed notebooks containing this no longer work:

    import autogen
    
    config_list = autogen.config_list_from_json(
        "OAI_CONFIG_LIST",
        filter_dict={
            "model": ["gpt-4", "gpt-4-0314", "gpt4", "gpt-4-32k", "gpt-4-32k-0314", "gpt-4-32k-v0314"],
        },
    )

**Comment by elecnix** [comment]
This warning shows up:

    WARNING - Completion was provided with a config_list, but the list was empty. Adopting default OpenAI behavior, which reads from the 'model' parameter instead.

**Comment by gagb** [comment]
@Hanochhu what is the location of your OAI_CONFIG_LIST file? If you are running a notebook its looking for that file in the cwd of the notebook (unless you changed the path).

**Comment by rjohnson318** [comment]
> I try autogen in Codespaces in github, and create a "OAI_CONFIG_LIST" file like ![image](https://user-images.githubusercontent.com/52187558/278352283-09274a32-ec78-4a2c-97c8-15f3ea1b7b3a.png)
> 
> it's work but when I paste same file in docker container ,there is an error : AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = ', or you can set the environment variable OPENAI_API_KEY=). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = '.

I get this same error as well. I have tried multiple notebooks in my codespaces container and they all say this.

**Comment by rjohnson318** [comment]
> I try autogen in Codespaces in github, and create a "OAI_CONFIG_LIST" file like ![image](https://user-images.githubusercontent.com/52187558/278352283-09274a32-ec78-4a2c-97c8-15f3ea1b7b3a.png)
> 
> it's work but when I paste same file in docker container ,there is an error : AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = ', or you can set the environment variable OPENAI_API_KEY=). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = '.

I get this same error as well. I have tried multiple notebooks in my codespaces container and they all say this.

**Comment by Hanochhu** [comment]
> what is the location of your OAI_CONFIG_LIST file? If you are running a notebook its looking for that file in the cwd of the notebook (unless you changed the path).

the location of "OAI_CONFIG_LIST" is in the root of autogen, same with "OAI_CONFIG_LIST_sample" .  And it's all same with Codespaces as I said.

**Comment by gagb** [comment]
See point number 2 here: https://github.com/microsoft/autogen#quickstart

"Copy OAI_CONFIG_LIST_sample to /notebook folder, name to OAI_CONFIG_LIST, and set the correct config."

**Comment by Hanochhu** [comment]
> See point number 2 here: https://github.com/microsoft/autogen#quickstart
> 
> "Copy OAI_CONFIG_LIST_sample to /notebook folder, name to OAI_CONFIG_LIST, and set the correct config."

ah, it work. why it work also in codespaces, when the file in root path.

**Comment by gagb** [comment]
> > See point number 2 here: https://github.com/microsoft/autogen#quickstart
> > "Copy OAI_CONFIG_LIST_sample to /notebook folder, name to OAI_CONFIG_LIST, and set the correct config."
> 
> ah, it work. why it work also in codespaces, when the file in root path.

That's weird I see the error in code spaces as well if don't put the config list in the correct path. See screenshot below. Would you be willing to double check your setup once more. If not please provide a screenshot?

<img width="934" alt="image" src="https://github.com/microsoft/autogen/assets/13227607/0e8b0d8d-9a97-4819-b5d4-c9cfb346199b">
