### ISSUE TITLE
support the old way of logging?

### ISSUE THREAD

**Issue by sonichi** [microsoft/autogen#442]
Supporting the old way of logging in #393 is not hard. If it is desired, I can provide guidance on how to create a PR to implement it.
@afourney

**Comment by afourney** [comment]
Let's link this to #412  It's an opportunity to get the short and long-form logs to be more consistent.
@victordibia @kevin666aa

**Comment by victordibia** [comment]
@sonichi , I can take this on. What are the main things to be aware of. Any pointers apppreciated. I'll share updates as progress is made.

**Comment by sonichi** [comment]
One I had was: Do we want to support both global logging and per-client logging? The global logging every ".create" call. The per-client logging logs the call made by this client. openai v1 switched from global inference to client-based inference call. Hence I have this question. One factor to consider is whether global logging was used by many people and whether they would like to continue using it.

**Comment by victordibia** [comment]
Good question. 
To me, the client approach seems to offer more control and isolate properties of each client call. 
This may inevitably create more work implementation-wise to track all client instances etc. 
I have only mostly seen calls to `start_logging` which global I believe.
Overall, I am fine with this being a breaking change if we explore client (with some support for global that is phases out over time)

**Comment by sonichi** [comment]
If we want to enable both, we can do:
call `self._book_keeping()` in the client, in which we call `Completion._book_keeping()` for the global logging.
