### ISSUE TITLE
Add a Core API example showing how to run multiple agents in concurrently

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#4427]
Create a new notebook example showing how to run multiple agents concurrently. Put it under multi-agent design patterns. 

It should cover the following scenarios. 

1. Single message, multiple processors: concurrently running multiple agents by publishing a message to a topic with multiple subscribers, all of which start processing the same message concurrently. 
2. Multiple messages, multiple processors: in a single scope (e.g., main function, or an agent's handler) publish messages to separate topic IDs, each of which has a single or multiple subscribers.
3. Direct messaging: use `send_message` API to create coroutines for sending direct messages to multiple agents, and then use `asyncio.gather` to collect the results. 

Avoid calling any model API. Use `asyncio.sleep` and `print` to simulate processing.

**Comment by gziz** [comment]
Should we close this one @ekzhu ?
