### ISSUE TITLE
Allow `AgentType` in APIs such as `TypeSubscription` when only string agent type is accepted

### ISSUE THREAD

**Issue by jackgerrits** [microsoft/autogen#4454]
In order to make things simpler it might be better to just deal with strings for AgentType

Update: we keep the AgentType, but need to update APIs to accept this type.

**Comment by jackgerrits** [comment]
@ekzhu we agreed to leave this as is right?

**Comment by ekzhu** [comment]
Let's not remove the type for now. Though we do need to update existing APIs to accept this as argument parameter. E.g., `TypeSubscription`
