### ISSUE TITLE
Automate example selection in LLM few-shot learning

### ISSUE THREAD

**Issue by sonichi** [microsoft/autogen#448]
Planning new features in `autogen`. Suggestions are welcome.

**Comment by qingyun-wu** [comment]
> @sonichi could you, please, tell are there any solutions for few-shot learning in autogen so far?

Thanks @sonichi  and @RageAgainstTheMachine101.  I am indeed considering adding a relevant feature and trying to find a good use cases. @RageAgainstTheMachine101 can you please briefly describe your use cases that need few-shot learning?

**Comment by RageAgainstTheMachine101** [comment]
> @RageAgainstTheMachine101 can you please briefly describe your use cases that need few-shot learning?

Yes, I can.

I am working with the following scenario: a requester asks some ad hoc question about users behavior in a product -> AI agent tries to map ad hoc question to SQL -> another AI agent tries to run this query against the db and fix errors if they occur -> the final result is provided to requester.

The main problem here is documentation knowledge. I resolved this problem with a system prompt with a lot of docs info.
Also, there is a problem with a special SQL dialect and code style. The second problem is resolved via a few shot learning approach very well. But the whole scenario was implemented without autogen.

**Comment by sonichi** [comment]
@RageAgainstTheMachine101 have you checked the [teachable agent](https://microsoft.github.io/autogen/blog/2023/10/26/TeachableAgent) or [retrieve chat](https://microsoft.github.io/autogen/blog/2023/10/18/RetrieveChat) in autogen? It sounds relevant from what you said.

**Comment by RageAgainstTheMachine101** [comment]
> @RageAgainstTheMachine101 have you checked the [teachable agent](https://microsoft.github.io/autogen/blog/2023/10/26/TeachableAgent) or [retrieve chat](https://microsoft.github.io/autogen/blog/2023/10/18/RetrieveChat) in autogen? It sounds relevant from what you said.

Yes, I tried [retrieve chat](https://microsoft.github.io/autogen/blog/2023/10/18/RetrieveChat), but it consumed all available tokens per minute for an organization. I believe I should try [teachable agent](https://microsoft.github.io/autogen/blog/2023/10/26/TeachableAgent) and find out how to limit tokens consuming.

Thank you!
