### ISSUE TITLE
make infer_lang() more robust

### ISSUE THREAD

**Issue by rabbabansh** [microsoft/autogen#452]
I saw a TODO in autogen/code_utils.py for the infer_lang() function to make it more robust.

```python
def infer_lang(code):
    """infer the language for the code.
    TODO: make it robust.
    """
    if code.startswith("python ") or code.startswith("pip") or code.startswith("python3 "):
        return "sh"

    # check if code is a valid python code
    try:
        compile(code, "test", "exec")
        return "python"
    except SyntaxError:
        # not a valid python code
        return UNKNOWN
```
What are we exactly looking for to improve here? I would like to contribute to improving this! 

@sonichi @LittleLittleCloud please help.

**Comment by afourney** [comment]
Language inference isn’t too bad. The only issue I’ve seen is when asking for markdown output, it sometimes uses a code block with the language set to “markdown” and this will throw an unknown language exception.

The areas where most problems are, in my estimation, detecting the code in the first place. Sometimes codeblocks aren’t used, or their format breaks the regex. See here for more details: https://github.com/microsoft/autogen/issues/414

**Comment by rabbabansh** [comment]
Will check it out! thank you

**Comment by pcdeadeasy** [comment]
Closing this for now. @rabbabansh, please feel to create new issues and contribute to the code base.
