### ISSUE TITLE
AgentChat Event types

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#4533]
1. Rename `ToolCallMessage` and `ToolCallResultMessage` to `ToolCallRequestEvent` and `ToolCallExecutionEvent`
2. Create union type `AgentEvent` which includes `ToolCallRequestEvent` and `ToolCallExecutionEvent`.
3. Deprecate old names.
4. Remove `AgentMessage`, always use union type `ChatMessage | AgentEvent`.
5. Update AgentChat API documentation for the message types. 

Use the following definitions:

- Agent perceives a sequence of ChatMessages and produces a ChatMessage as a response. ChatMessage include: TextMessage, MultiModalMessage, StopMessage, and HandoffMessage
- Events are messages emitted from the internal working of Agents or Teams, they are not used for Agent-Agent communication.
- Both ChatMessages and Events can be observed by applications, allowing the applications to observe and control the behavior of Agents and Teams. 

Why: 

- events may or may not coming from agents. e.g., Selector Group Chat manager can emit events such as "agent selected"
- "system-level" or "orchestration-level" events such as reset, start, etc.
- enhance observability!

**Comment by ekzhu** [comment]
@gagb  feel free to close this one depending on how the documentation content goes.

**Comment by ekzhu** [comment]
Will revisit in the future. Seems not necessary.

**Comment by husseinmozannar** [comment]
I like this proposal!
