### ISSUE TITLE
ClosureAgent Got unexpected keyword Closure

### ISSUE THREAD

**Issue by kiranraaj19** [microsoft/autogen#4534]
Hey, Thanks for the help. I realized i was importing Agents from autogen rather than autogen_agentchat and its way simpler to develop Agents with the tools parameter now. But I still have a problem while following this [documentation](https://microsoft.github.io/autogen/dev/user-guide/agentchat-user-guide/tutorial/selector-group-chat.html)

I have setup agents and SelectorGroupChat properly but i get this following error:

```
in _init
    await ClosureAgent.register(
          ^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseAgent.register() got an unexpected keyword argument 'closure'
```

I am not using ClosureAgent anywhere!

Code I am using:
```
# agents are defined according to documentation
team = SelectorGroupChat(
        agents,
        model_client=az_model_client,
        termination_condition=termination
    )

stream = team.run_stream(task = input_message)
async for message in stream:
    print(message)
```

Is there something that I am missing?

_Originally posted by @kiranraaj19 in https://github.com/microsoft/autogen/discussions/4488#discussioncomment-11453283_

**Comment by ekzhu** [comment]
Which version are you using? And your Python version?

Also be aware you need to use the documentation version that matches the dev build version. The code is currently under development.

**Comment by kiranraaj19** [comment]
Autogen and autogen-agentchants version were interferring each other i think. Clean installing the library worked! Thanks
