### ISSUE TITLE
pip3.13 install  autogen-agentchat==0.4.0.dev8 failed on MAC M3

### ISSUE THREAD

**Issue by zyliu1985** [microsoft/autogen#4537]
### What happened?

OS:  mac Sonoma 14.2 (23C64)
python version: 3.13

error lib: grpcio==1.62.3

install grpcio by manual:
```
(autogen_env) banma-3808@U-XFFQ16M0-2331 autogen_env % pip install grpcio
Collecting grpcio
  Downloading grpcio-1.68.1-cp313-cp313-macosx_10_13_universal2.whl.metadata (3.9 kB)
Downloading grpcio-1.68.1-cp313-cp313-macosx_10_13_universal2.whl (11.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.1/11.1 MB 20.0 MB/s eta 0:00:00
Installing collected packages: grpcio
Successfully installed grpcio-1.68.1
``` 
[error.log](https://github.com/user-attachments/files/18004427/error.log)

reinstall again. The error is the same. It's still depended with 1.62.3.

### What did you expect to happen?

pip can install successfully on mac M3

### How can we reproduce it (as minimally and precisely as possible)?

upgrade the grpcio dependency version.

### AutoGen version

0.4.0.dev8

### Which package was this bug in

Core

### Python version

3.13

### Operating system

macos 14.2 (23C64)

**Comment by zyliu1985** [comment]
CPU:  Apple M3 Pro

**Comment by ekzhu** [comment]
@zyliu1985 thanks for the issue. It's known, this will be addressed in the next dev build by making the grpcio dependency optional. 

Meanwhile you need to downgrade to 3.12...

**Comment by zyliu1985** [comment]
> [@zyliu1985](https://github.com/zyliu1985) thanks for the issue. It's known, this will be addressed in the next dev build by making the grpcio dependency optional.
> 
> Meanwhile you need to downgrade to 3.12...

Thank you . I downgraded python to 3.12 and installed successfully.

**Comment by ekzhu** [comment]
This should be resolved now in dev9 build. The grpcio dependency has been moved to autogen_ext as an optional extra.
