### ISSUE TITLE
AutogenStudio support streaming output

### ISSUE THREAD

**Issue by jackq007** [microsoft/autogen#4586]
### What feature would you like to be added?

I'm really looking forward to AutogenStudio's support for streaming output.

### Why is this needed?

1. The experience will be better, and you can see the interactive messages more intuitively.
2. In some cases, for example, when the output doesn't meet expectations, the message output can be terminated earlier, thus saving time.

**Comment by victordibia** [comment]
Hi @jackq007 ,

Thanks for the feedback.
Currently the updated version we are working on for AutoGen Studio streams agent messages as they become available. Any chance you have gotten a chance to take a look at the new version we are working on?

Please take a look at the issue #4006 and [discussion](https://github.com/microsoft/autogen/discussions/4208) . Does the video below meet what you are thinking of?

https://github.com/user-attachments/assets/dc2b84b0-6302-4f07-b790-e264576bfb1a

At some point, once we have token streaming implemented in AgentChat, we can have that available in AutoGen studio. Streaming is being tracked here https://github.com/microsoft/autogen/issues/3862

**Comment by jackq007** [comment]
> Hi [@jackq007](https://github.com/jackq007) , 你好，
> 
> Thanks for the feedback. 感谢您的反馈。 Currently the updated version we are working on for AutoGen Studio streams agent messages as they become available. Any chance you have gotten a chance to take a look at the new version we are working on? 目前，我们正在为AutoGen Studio工作的更新版本在代理消息可用时将其流式传输。你有机会看看我们正在开发的新版本吗？
> 
> Please take a look at the issue [#4006](https://github.com/microsoft/autogen/issues/4006) and [discussion](https://github.com/microsoft/autogen/discussions/4208) . Does the video below meet what you are thinking of?请看问题 [#4006](https://github.com/microsoft/autogen/issues/4006) 和讨论。下面的视频符合你的想法吗？
> 
>  ags_update.mp4 
> At some point, once we have token streaming implemented in AgentChat, we can have that available in AutoGen studio. Streaming is being tracked here [#3862](https://github.com/microsoft/autogen/issues/3862)在某些时候，一旦我们在AgentChat中实现了令牌流，我们就可以在AutoGen Studio中使用它。流媒体正在跟踪这里 [#3862](https://github.com/microsoft/autogen/issues/3862)

I watched your video carefully, and I have to say it's great. It's understandable that a single agent does not output in a streaming fashion, but agents output to each other in a streaming manner. Actually, I would love to see that when a single agent outputs messages, it also supports streaming output. Especially when a single agent outputs a lot of messages, this would definitely be awesome.

**Comment by victordibia** [comment]
Closing this for now, there also seems to be overlap/duplication with #4737
