### ISSUE TITLE
RAG agent doesn't create any context

### ISSUE THREAD

**Issue by zboinek** [microsoft/autogen#461]
Hi, I tried to run RAG agent in my remote jupyter environment.
I'm equiped with NVIDIA A5000 and using Vicuna-13B-16k with fastchat as backend.

I paste whole code but it's just basic RAG example

```
import autogen

config_list = [
        {
            "model": "vicuna-13b-v1.5-16k",
            "api_base": "http://0.0.0.0:9000/v1",
            "api_type": "open_ai",
            "api_key": "NULL", # just a placeholder
        }
    ]
```

```
from autogen.agentchat.contrib.retrieve_assistant_agent import RetrieveAssistantAgent
from autogen.agentchat.contrib.retrieve_user_proxy_agent import RetrieveUserProxyAgent
import chromadb

autogen.ChatCompletion.start_logging()

# 1. create an RetrieveAssistantAgent instance named "assistant"
assistant = RetrieveAssistantAgent(
    name="assistant", 
    system_message="You are a helpful assistant.",
    llm_config={
        "request_timeout": 600,
        "seed": 42,
        "config_list": config_list,
    },
)
```

```
ragproxyagent = RetrieveUserProxyAgent(
    name="ragproxyagent",
    human_input_mode="NEVER",
    max_consecutive_auto_reply=10,
    retrieve_config={
        "task": "qa",
        "docs_path": "/workspace/llm-big/AutoGen/docs/installation.md",  # change this to your own path, such as https://raw.githubusercontent.com/microsoft/autogen/main/README.md
        "chunk_token_size": 2000,
        "model": config_list[0]["model"],
        "client": chromadb.PersistentClient(path="/tmp/chromadb"),
        "embedding_model": "all-mpnet-base-v2",
        "get_or_create": True,  # set to True if you want to recreate the collection

    },
)
```

Then I initialize

```
assistant.reset()
qa_problem = "How to install CGC?"
ragproxyagent.initiate_chat(assistant, problem=qa_problem, search_string="spark") 
```
Output is clean, no errors but also no contex

```
Trying to create collection.
doc_ids:  [[]]
No more context, will terminate.
ragproxyagent (to assistant):

TERMINATE
```

It's the same with local files or external URLs.
Any ideas? I'm using nvidia-pytorch container image as base, but already downgraded pytorch

**Comment by sonichi** [comment]
@thinkall for awareness.

**Comment by vstudio12** [comment]
I'm running into the same issue as @zboinek.

**Comment by thinkall** [comment]
Hi @zboinek , @vstudio12 , please check if  you really want to search only documents with "spark" in the text. Remove the `search_string="spark"` if not.

**Comment by pcdeadeasy** [comment]
@zboinek, could you verify and close the issue?

**Comment by motahari64** [comment]
@thinkall , @zboinek  "Hi, I'm encountering the same issue as @zboinek, and removing the search_string="spark" doesn't help me."

**Comment by thinkall** [comment]
> @thinkall , @zboinek "Hi, I'm encountering the same issue as @zboinek, and removing the search_string="spark" doesn't help me."

Could you share your code? Thanks.

**Comment by gallo2000sv** [comment]
I can confirm it works after removing search_string="spark" 
from the examples I had: `ragproxyagent.initiate_chat(assistant, problem=code_problem, search_string="spark") `
and got no context: 
```
doc_ids:  [[]]
No more context, will terminate.

```
It's working now with:
`ragproxyagent.initiate_chat(assistant, problem=code_problem)`
search_string="spark" seems to search for exact match word "spark" within your documents, so there is no need if you are trying to solve a more general problem.
