### ISSUE TITLE
Mistake in documentation for oai.completion - filter_func

### ISSUE THREAD

**Issue by Abhishek-Balram** [microsoft/autogen#462]
The documentation says that when passing a filter_func to oai.Completion.Create, the parameters of the function should be 'context', 'config', and 'response'. e.g.

```
def valid_json_filter(context, config, response):
    for text in autogen.Completion.extract_text(response):
        try:
            json.loads(text)
            return True
        except ValueError:
            pass
    return False
```
The above example is taken from the documentation page at https://microsoft.github.io/autogen/docs/reference/oai/completion.

This causes the following error: 
```
Traceback (most recent call last):
  File "/Users/bshek/Documents/autogen/enhanced_inference.py", line 35, in <module>
    response = autogen.Completion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bshek/Documents/autogen/.venv/lib/python3.11/site-packages/autogen/oai/completion.py", line 811, in create
    pass_filter = filter_func is None or filter_func(
                                         ^^^^^^^^^^^^
TypeError: valid_json_filter() got an unexpected keyword argument 'base_config'
```
I believe the parameter 'config' should be renamed to 'base_config' in the documentation, because this is the expected keyword argument in line 811 of completion.py

**Comment by sonichi** [comment]
Thanks. It's indeed a mistake. We'll fix it in #393 by removing the config from the input of the function.
