### ISSUE TITLE
Make a new dev release ASAP

### ISSUE THREAD

**Issue by vincent-pli** [microsoft/autogen#4628]
### What happened?

The latest dev release of 0.4 is `autogen-core==0.4.0.dev9` seems, but there is some big change after that release, 
for example `model context and models modules` migrated from `core.component` to `core`, that's make tutorial not work:
https://microsoft.github.io/autogen/dev/user-guide/core-user-guide/quickstart.html
 

### What did you expect to happen?

tutorial works

### How can we reproduce it (as minimally and precisely as possible)?

n/a

### AutoGen version

autogen-core==0.4.0.dev9

### Which package was this bug in

Core

**Comment by ekzhu** [comment]
Will do in a bit!!

**Comment by ekzhu** [comment]
We will need to change the default displayed version of the documentation to be the latest released version.

Otherwise dev10 has just released.
