### ISSUE TITLE
RetrievalChat fails with chromadb error

### ISSUE THREAD

**Issue by tevslin** [microsoft/autogen#464]
trying to run the cell which builds the agents in retrievalchat, fails with this message: (repeated)
Failed to send telemetry event ClientStartEvent: module 'chromadb' has no attribute 'get_settings'
Failed to send telemetry event ClientStartEvent: module 'chromadb' has no attribute 'get_settings'

am running in github codespace with python 3.10. used sqlite workaround to get chromadb properly installed.

**Comment by sonichi** [comment]
@thinkall are you aware of this issue?

**Comment by thinkall** [comment]
Hi @tevslin , have you tried on your local machine? I'm sorry, but I can't reproduce the issue because I can't access the Codespace.
![image](https://github.com/microsoft/autogen/assets/3197038/8c69292c-aef8-4183-bfc8-7af2a7deb386)

**Comment by tevslin** [comment]
No. Have only tried in codespace. Am on windows and trying to avoid having to setup the environment and docker container.

**Comment by tevslin** [comment]
now seems to be working

**Comment by httplups** [comment]
> trying to run the cell which builds the agents in retrievalchat, fails with this message: (repeated) Failed to send telemetry event ClientStartEvent: module 'chromadb' has no attribute 'get_settings' Failed to send telemetry event ClientStartEvent: module 'chromadb' has no attribute 'get_settings'
> 
> am running in github codespace with python 3.10. used sqlite workaround to get chromadb properly installed.

Same error here

**Comment by sorydi3** [comment]
@httplups I'm having the same issue as well, did you managed to fix it?
