### ISSUE TITLE
Core API Doc Quick Start is Slow Start

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#4662]
I think this quick start isn't so quick. We should consider moving this to the multi-agent design pattern section, and update this quick start with something super simple, such as two agents counting from 10 to 1, without using any model or executor, just pure Python.

_Originally posted by @ekzhu in https://github.com/microsoft/autogen/pull/4658#pullrequestreview-2497323440_

**Comment by victordibia** [comment]
+1 here .. The Core quickstart could be better.

**Comment by peterychang** [comment]
What would the two agents be doing? Maybe one decrementing a count while the other checks the ending condition?

**Comment by ekzhu** [comment]
Yep. That's a great idea.
