### ISSUE TITLE
OAI_CONFIG_LIST cannot find environment variable

### ISSUE THREAD

**Issue by nhtkid** [microsoft/autogen#470]
Many of the example notebook had
`config_list = autogen.config_list_from_json(
    "OAI_CONFIG_LIST",
    filter_dict={
        "model": ["gpt4", "gpt-4-32k", "gpt-4-32k-0314", "gpt-4-32k-v0314"],
    },
)`

I think it should be below base on the guide [In-depth Guide to OpenAI Utility Functions](https://github.com/microsoft/autogen/blob/main/notebook/oai_openai_utils.ipynb).
`config_list = autogen.config_list_from_json(
    env_or_file= "OAI_CONFIG_LIST",
    filter_dict={
        "model": ["gpt4", "gpt-4-32k", "gpt-4-32k-0314", "gpt-4-32k-v0314"],
    },
)`

**Comment by sonichi** [comment]
These two ways are equivalent.

**Comment by nhtkid** [comment]
Thanks for the reply. However if I don't use "env_or_file=", it cannot recognise the file and API key.
