### ISSUE TITLE
TypeError: ConversableAgent.__init__() got an unexpected keyword argument 'lm_config'

### ISSUE THREAD

**Issue by tricodex** [microsoft/autogen#475]
Exception has occurred: TypeError
ConversableAgent.__init__() got an unexpected keyword argument 'lm_config'
  File "C:\workforce\app.py", line 27, in <module>
    assistant = autogen.AssistantAgent(
                ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ConversableAgent.__init__() got an unexpected keyword argument 'lm_config'

I keep getting this error, I am using pyautogen, not autogen, when I use autogen I get this error: AttributeError: module 'autogen' has no attribute 'AssistantAgent'

Does anyone know what to do?

Setup:

import autogen

config_list = [
    {
        "api_type": "open_ai",
        "api_base": "https://localhost:1234/v1",
        "api_key": "NULL",
    }

]

lm_config={
    "request_timeout": 600,
    "seed": 42,
    "config_list": config_list,
    "temperature": 0
}

assistant = autogen.AssistantAgent(
    name="coder",
    system_message="You are a coder specializing in Python.",
    lm_config=lm_config
)

user_proxy = autogen.UserProxyAgent(
    name="user_proxy",
    human_input_mode="TERMINATE",
    max_consecutive_auto_reply=10,
    is_termination_msg=lambda x: x.get("content", "").rstrip().endswith("TERMINATE"),
    code_execution_config={"work_dir": "web"},
    lm_config=lm_config,
    system_message="Reply TERMINATE if the task has been completed satisfactorily. Otherwise, reply CONTINUE, or the reason why the task is unsatisfactory."
)

task = """
Write python code to output numbers 1 to a 100, and then store it in a file. """

user_proxy.initiate_chat(
    assistant,
    message=task,
)

**Comment by rickyloynd-microsoft** [comment]
Hi @tricodex , have you tried running the [twoagent.py example code](https://github.com/microsoft/autogen/blob/main/test/twoagent.py) from the main readme? What LLM are you using?

**Comment by sonichi** [comment]
Please use `llm_config` instead of `lm_config`

**Comment by tricodex** [comment]
> Please use `llm_config` instead of `lm_config`

Thank you!

**Comment by tricodex** [comment]
> Hi @tricodex , have you tried running the [twoagent.py example code](https://github.com/microsoft/autogen/blob/main/test/twoagent.py) from the main readme? What LLM are you using?

Thank you, the solution from sonichi works for my issue, but I have aquired new issues now. I am trying to use a 7B mistral model from LLM studio, it doesn't work unfortunately, but the OpenAI model do connect with my autogen setup.
