### ISSUE TITLE
autogen-studio encounters an error when working in GrpcWorkerAgentRuntime mode

### ISSUE THREAD

**Issue by angive** [microsoft/autogen#4766]
### What happened?

Running with SingleThreadedAgentRuntime works fine, but after switching to GrpcWorkerAgentRuntime, an error occurs when executing workflows, Errors:

![Image](https://github.com/user-attachments/assets/837950ad-6b17-4d4a-9a7e-9090ca9d8ee6)

### What did you expect to happen?

It is expected that running with SingleThreadedAgentRuntime and GrpcWorkerAgentRuntime in autogen-studio produces the same result.

### How can we reproduce it (as minimally and precisely as possible)?

1、Replaced self._runtime = SingleThreadedAgentRuntime() at approximately line 70 in the __init__ method of _base_group_chat.py under autogen_agentchat with self._runtime = GrpcWorkerAgentRuntime(host_address="127.0.0.1:50051"), and rebuilt the project.
2、Started a local GrpcWorkerAgentRuntimeHost(address="0.0.0.0:50051").
3、Ran autogen-studio, and the error can be reproduced.

### AutoGen version

0.4.0.dev11

### Which package was this bug in

AutoGen Studio

### Model used

gpt-4o

### Python version

3.11.10

### Operating system

windows 11

**Comment by ekzhu** [comment]
@angive I wouldn't call it a bug because currently the team is assuming SingleThreadedRuntime, the way runtime should be connected is different. 

Please see our issue that tracks swapping runtimes: #4075

**Comment by angive** [comment]
Thank you for your explanation.
