### ISSUE TITLE
Fix busy loop in single threaded agent runtime

### ISSUE THREAD

**Issue by jackgerrits** [microsoft/autogen#4773]
### Discussed in https://github.com/microsoft/autogen/discussions/4772

<div type='discussions-op-text'>

<sup>Originally posted by **un-hongly** December 20, 2024</sup>
```
team.run_stream(task=input.message)
async for message in stream:
   pass
```

`async for message in stream` cause high cpu usages.

<img width="994" alt="Screenshot 2024-12-20 at 5 40 20 in the afternoon" src="https://github.com/user-attachments/assets/d5c310a3-fa0b-429d-be94-8f0d81e64e54" />
</div>

We need to replace this busy loop with proper eventing based on when messages are available to be consumed.

https://github.com/microsoft/autogen/blob/a4c1314432299605e1ef0777f4c5dc3ba9d6482b/python/packages/autogen-core/src/autogen_core/_single_threaded_agent_runtime.py#L446

**Comment by ekzhu** [comment]
Good catch. We can use asyncio.Event to set and fire events or use asyncio.Queue
