### ISSUE TITLE
how do i get each agent message? instead of agent last message?

### ISSUE THREAD

**Issue by xmi1an** [microsoft/autogen#478]
how do i get each agent message? instead of agent last message?

**Comment by sonichi** [comment]
https://microsoft.github.io/autogen/docs/reference/agentchat/conversable_agent#chat_messages

**Comment by sonichi** [comment]
Candidate for FAQ.

**Comment by xmi1an** [comment]
> https://microsoft.github.io/autogen/docs/reference/agentchat/conversable_agent#chat_messages

But how can during conversation ? i mean chat_messages print after all convertion finish. right?

**Comment by afourney** [comment]
No the property provides access to a dictionary of all the messages send or received by the agent. It is organized by conversation partner, and it should be up to date whenever you access it. 

Note that the key to the dictionary is the actual Agent instance (not a string name, etc.)

**Comment by xmi1an** [comment]
> No the property provides access to a dictionary of all the messages sent or received by the agent. It is organized by conversation partner, and it should be up to date whenever you access it.
> 
> Note that the key to the dictionary is the actual Agent instance (not a string name, etc.)

Then How can i get each messages of agent during conversion? Because chat_messages property provides after whole task completes.

**Comment by victordibia** [comment]
@xmi1an you can hook in function that is called whenever an agent receives a message. 

Assuming you have two agents `user_proxy` and `assistant`, you can [register a function](https://microsoft.github.io/autogen/docs/reference/agentchat/conversable_agent#conversableagent-objects) with these agents that gets called with some parameters. 

```python

def print_messages(recipient, messages, sender, config): 
    if "callback" in config and  config["callback"] is not None:
        callback = config["callback"]
        callback(sender, recipient, messages[-1])
    print(f"Messages sent to: {recipient.name} | num messages: {len(messages)}")
    return False, None  # required to ensure the flow continues

user_proxy.register_reply(
    [autogen.Agent, None],
    reply_func=print_messages, 
    config={"callback": None},
)

assistant.register_reply(
    [autogen.Agent, None],
    reply_func=print_messages, 
    config={"callback": None},
) 
``` 

In the above, we register a `print_messages` message that is called each time the agent receive a message.

**Comment by beckortikov** [comment]
> @xmi1an you can hook in function that is called whenever an agent receives a message.
> 
> Assuming you have two agents `user_proxy` and `assistant`, you can [register a function](https://microsoft.github.io/autogen/docs/reference/agentchat/conversable_agent#conversableagent-objects) with these agents that gets called with some parameters.
> 
> ```python
> def print_messages(recipient, messages, sender, config): 
>     if "callback" in config and  config["callback"] is not None:
>         callback = config["callback"]
>         callback(sender, recipient, messages[-1])
>     print(f"Messages sent to: {recipient.name} | num messages: {len(messages)}")
>     return False, None  # required to ensure the agent communication flow continues
> 
> user_proxy.register_reply(
>     [autogen.Agent, None],
>     reply_func=print_messages, 
>     config={"callback": None},
> )
> 
> assistant.register_reply(
>     [autogen.Agent, None],
>     reply_func=print_messages, 
>     config={"callback": None},
> ) 
> ```
> 
> In the above, we register a `print_messages` message that is called each time the agent receive a message.

How to use it then?

**Comment by ekzhu** [comment]
can you elaborate what's your usage case?

**Comment by AndriCause** [comment]
I would like to save the chat messages in the DB of a website, and doing it with an async function while the agents are conversing through a group chat would be very useful, so that the user can also see who says what, while the discussion is being made. 
Could you please let me know an example of how this could be achieved?

**Comment by ekzhu** [comment]
You can take a look at autogen studio in samples/apps. It realizes the functionality you mentioned.
