### ISSUE TITLE
Consistent type hints for Sequence in interfaces

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#4783]
Currently List and Sequences are mixed in `agentchat.base` types. Make them all Sequence as it is more general. 

- `ChatAgent.produced_message_types` 
- `Response.inner_messages`
- `TaskRunner.run`
- `TaskRunner.run_stream`

**Comment by kartikx** [comment]
Hi, if this is a good first issue can I pick this up? I would like to contribute to AutoGen.

**Comment by ekzhu** [comment]
Sure. There is a time urgency though if you are comfortable with. Let us know asap if you are blocked or otherwise unable to continue.

**Comment by kartikx** [comment]
Thanks for the info @ekzhu. I might not be able to get it done within the deadline so please don't be blocked on me.

**Comment by ekzhu** [comment]
> Thanks for the info @ekzhu. I might not be able to get it done within the deadline so please don't be blocked on me.

No problem. There are many issues tagged with 0.4.1 milestones and beyond. You can take a look at those and see if you have any suggestions. 

The best kind of contributions we can get right now is bug reports and you actively trying out the API.
