### ISSUE TITLE
Reminder in error message to add model capabilities when model name does not exist

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#4787]
> I see. Ok if you encountered issues with this in the past then it's probably best not to ignore the model capabilities. I think it could be good to produce an error message for it. 

 _Originally posted by @gabayben in [#4785](https://github.com/microsoft/autogen/issues/4785#issuecomment-2558702505)_

**Comment by ekzhu** [comment]
@srjoglekar246 here you go. Not sure why I can't assign you directly.

**Comment by srjoglekar246** [comment]
@ekzhu  I think its because I may need to be added to the list of collaborators or something? I am already a part of `microsoft`
