### ISSUE TITLE
Quickstart documentation correction

### ISSUE THREAD

**Issue by jaygdesai** [microsoft/autogen#4866]
Installation of packages via command 

`pip install "autogen-agentchat==0.4.0.dev13" "autogen-ext[openai]==0.4.0.dev13`

results in error as under.

While running the code 

`from autogen_ext.models.openai import OpenAIChatCompletionClient`

following error is generated. 

ModuleNotFoundError: No module named 'azure'

**Comment by jaygdesai** [comment]
I got the error while executing example Quickstart code given on the same documentation page.

**Comment by jackgerrits** [comment]
Will address the dependency that probably should not be rquired in #4870
