### ISSUE TITLE
unable to integrate "qwen_turbo" model (use online api server) into AutoGen. 

### ISSUE THREAD

**Issue by ImagineL** [microsoft/autogen#499]
Hello, I am currently using the qwen_turbo large model, which has its own online API service. However, I am unable to integrate this capability into AutoGen. Do you have plans to support qwen_turbo or similar large API model online services?

**Comment by victordibia** [comment]
Hi @ImagineL ,

How are you serving your qwen_turbo model? 
In general, our plan is to support any model, as long as they can be wrapped into an openai- compatible endpoint. 

There are several tools that seem to offer a good wrapper for local models with an open-ai compatible endpoint.

- fastChat 
- vllm
- llmstudio.ai

**Comment by ImagineL** [comment]
Thank you for your response. My qwen_turbo is an online API service that does not require local model deployment. For more details, you can check the official documentation: https://help.aliyun.com/zh/dashscope/developer-reference/api-details?spm=a2c4g.11186623.0.i6#341800c0f8w0r.

**Comment by ImagineL** [comment]
> Hi @ImagineL ,
> 
> How are you serving your `qwen_turbo` model? In general, our plan is to support any model, as long as they can be wrapped into an **openai-compatible** endpoint.
> 
> There are several tools that seem to offer a good wrapper for local models with an open-ai compatible endpoint.
> 
> * fastChat
> * vllm
> * llmstudio.ai

@victordibia 
Hello VictorDibia, I'm not sure if I expressed myself clearly. The 'qwen_turbo' is a large model that provides a RESTful API server for users. At the same time, it also offers a Python SDK to utilize its server. Therefore, users do not need to deploy the model locally on their machines."
For more details, please refer to the official documentation: https://help.aliyun.com/zh/dashscope/developer-reference/api-details?spm=a2c4g.11186623.0.i6#341800c0f8w0r. I look forward to your reply. Thank you, VictorDibia.

**Comment by thinkall** [comment]
@ImagineL you can either wrap qwen as a openai compatible model or follow this https://microsoft.github.io/autogen/blog/2024/01/26/Custom-Models to support it. Let me know if it works for you. Thanks.

**Comment by rysweet** [comment]
closing won't fix

**Comment by zzheng90** [comment]
try this below, it works for me:

`from autogen_agentchat.agents import AssistantAgent, UserProxyAgent
from autogen_agentchat.conditions import TextMentionTermination
from autogen_agentchat.teams import RoundRobinGroupChat
from autogen_agentchat.ui import Console
from autogen_ext.models.openai import OpenAIChatCompletionClient

# Create the agents.
# model_client = OpenAIChatCompletionClient(model="gpt-4o-mini", api_key=api_key_gpt)

**model_client = OpenAIChatCompletionClient(
          
    model="qwen-turbo",
      
    base_url="https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
      
    api_key=api_key_qwen, 
          
    model_info={
          
    "vision":False,
          
    "function_calling":True,
          
    "json_output":False,
          
    "family":"unknown"
          
    })**

assistant = AssistantAgent("assistant", model_client=model_client)
user_proxy = UserProxyAgent("user_proxy", input_func=input)  # Use input() to get user input from console.

# Create the termination condition which will end the conversation when the user says "APPROVE".
termination = TextMentionTermination("APPROVE")

# Create the team.
team = RoundRobinGroupChat([assistant, user_proxy], termination_condition=termination)

# Run the conversation and stream to the console.
stream = team.run_stream(task="Write a 4-line poem about the ocean.")
# Use asyncio.run(...) when running in a script.
await Console(stream)`
