### ISSUE TITLE
InvalidRequestError when giving the autogen.AssistantAgent tools via llm_config.functions

### ISSUE THREAD

**Issue by bruinon** [microsoft/autogen#51]
folks,

i am following the tutorial listed in https://github.com/microsoft/autogen/blob/main/notebook/agentchat_two_users.ipynb

1. I completed the set up for the **ask_planer** function without issues
```
planner_user (to planner):

hello

--------------------------------------------------------------------------------
planner (to planner_user):

Hello! How can I help you today? Do you need assistance with a coding project or reasoning about a certain topic? Please provide me with some details so I can suggest the appropriate steps to accomplish the task.

--------------------------------------------------------------------------------
'Hello! How can I help you today? Do you need assistance with a coding project or reasoning about a certain topic? Please provide me with some details so I can suggest the appropriate steps to accomplish the task.'
```
2. i got the following error when i tried to run 
```
user_proxy.initiate_chat(
    assistant,
    message="""what is 1+1""",
)
```
**InvalidRequestError: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.**
if i remove the llm_config['functions'] then the problem goes away; however, that prevents me to connecting the agents
do you know what could be causing this problem? and how i can resolve this?

**Comment by AaronWard** [comment]
@bruinon Pass your config list to `initiate_chat()`

```python
user_proxy.initiate_chat(assistant, 
                         message="""what is 1+1""",
                         config_list=config_list)
```

**Comment by bruinon** [comment]
> @bruinon Pass your config list to `initiate_chat()`
> 
> ```python
> user_proxy.initiate_chat(assistant, 
>                          message="""what is 1+1""",
>                          config_list=config_list)
> ```
It doesnt seem to be the solution for this issue.

After digging into the error message, it appears that the problem is in the **oai.ChatCompletion.create**

```
596 response = oai.ChatCompletion.create(
597     context=messages[-1].pop("context", None), messages=self._oai_system_message + messages, **llm_config
598 )
InvalidRequestError: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.
```
what i dont quite understand is why the API is not recognized when the llm_config['functions'] is provided

**Comment by bruinon** [comment]
It appears that the first problem has gone away after I properly provide the **config_list**. However, it encountered a new error message as shown below, 
**InvalidRequestError: Unrecognized request argument supplied: functions**

**Comment by sonichi** [comment]
what models and versions are you using? "functions" is only supported by the latest OpenAI models.

**Comment by bruinon** [comment]
> what models and versions are you using? "functions" is only supported by the latest OpenAI models.

thanks for your input.
I am using **openai.version.VERSION:'0.28.1'**, and **model:'gpt-4-32k'**. 
Do you have means to verify which version would be compatible with AutoGen examples?

**Comment by sonichi** [comment]
Can I see the code that causes this error?

**Comment by bruinon** [comment]
> Can I see the code that causes this error?

I traced it back to the **oai.ChatCompletion.create** function, and built the corresponding unit test as shown below. If i comment out LLM_CONFIGS['functions'], it can execute without error.

```
OPENAI_CONFIGS = [{
    'api_key': <API_KEY>,
    'api_base': <API_BASE>,
    'api_type': 'azure',
    'api_version': <API_VERSION>,
    'model': "gpt-4-32k",    
}]

LLM_CONFIGS = {
    "request_timeout": 600,
    "seed": 42,
    "config_list": OPENAI_CONFIGS,
    "temperature": 0,
    "functions":[{
            "name": "python",
            "description": "run cell in ipython and return the execution result.",
            "parameters": {
                "type": "object",
                "properties": {
                    "cell": {
                        "type": "string",
                        "description": "Valid Python cell to execute.",
                    }
                },
                "required": ["cell"],
            },
        }
    ]
}


from flaml.autogen import oai
oai.ChatCompletion.create(
    prompt='what is 1+1?',
    **LLM_CONFIGS
)
```

Error:
```
File ~/venv/GPT_venv/lib/python3.10/site-packages/openai/api_requestor.py:775, in APIRequestor._interpret_response_line(self, rbody, rcode, rheaders, stream)
    773 stream_error = stream and "error" in resp.data
    774 if stream_error or not 200 <= rcode < 300:
--> 775     raise self.handle_error_response(
    776         rbody, rcode, resp.data, rheaders, stream_error=stream_error
    777     )
    778 return resp

InvalidRequestError: Unrecognized request argument supplied: functions
```

**Comment by sonichi** [comment]
Could you use "api_version": "2023-07-01-preview"?
Also, could you check in your azure oai deployments whether the "model_version" column shows "0613"?

**Comment by bruinon** [comment]
> version

@sonichi 
using **"api_version": "2023-07-01-preview"** in the OPENAI_CONFIGS didnt resolve the problem.
I will have to get back to you about the "model_version" column in the azure oai deployments.

**Comment by bruinon** [comment]
> Could you use "api_version": "2023-07-01-preview"? Also, could you check in your azure oai deployments whether the "model_version" column shows "0613"?

i confirmed that it is gpt-4-32k model version 0613

**Comment by AllenJShi** [comment]
Encountered the same issue lately. First, check and make sure your API version and model name are valid per Azure's doc https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/function-calling.

Next, recommend adding "gpt-35-turbo-16k" and other relevant names to the chat_model list. One of the issues I encountered was that the "35" was not replaced with "3.5" and thus the openai completion API was not correctly selected in the following code:
```
        openai_completion = (
            openai.ChatCompletion
            if config["model"] in cls.chat_models or issubclass(cls, ChatCompletion)
            else openai.Completion
        )
```

Hence, as a quick fix, add all "35" to the chat_model list. Or, the more elegant way is to move the following code ahead a bit
```
                if "azure" in config.get("api_type", openai.api_type) and "model" in config:
                    # azure api uses "engine" instead of "model"
                    config["engine"] = config.pop("model").replace("gpt-3.5-turbo", "gpt-35-turbo")
```

```
class Completion(openai_Completion):
    """A class for OpenAI completion API.

    It also supports: ChatCompletion, Azure OpenAI API.
    """

    # set of models that support chat completion
    chat_models = {
        "gpt-3.5-turbo",
        "gpt-3.5-turbo-0301",  # deprecate in Sep
        "gpt-3.5-turbo-0613",
        "gpt-3.5-turbo-16k",
        "gpt-3.5-turbo-16k-0613",
        "gpt-35-turbo",
        "gpt-4",
        "gpt-4-32k",
        "gpt-4-32k-0314",  # deprecate in Sep
        "gpt-4-0314",  # deprecate in Sep
        "gpt-4-0613",
        "gpt-4-32k-0613",
    }
```
