### ISSUE TITLE
Question about notebook/agentchat_function_call.ipynb

### ISSUE THREAD

**Issue by dluc** [microsoft/autogen#510]
I'm going through the first example at https://github.com/microsoft/autogen/blob/main/notebook/agentchat_function_call.ipynb and I was wondering why use a `UserProxyAgent` with `human_input_mode="NEVER"` rather than a `ConversableAgent`?

For instance, I replaced this:
```python
user_proxy = autogen.UserProxyAgent(
    name="user_proxy",
    is_termination_msg=lambda x: x.get("content", "") and x.get("content", "").rstrip().endswith("TERMINATE"),
    human_input_mode="NEVER",
    max_consecutive_auto_reply=10,
    code_execution_config={"work_dir": "coding"},
)
```

with
```python
user_proxy = autogen.ConversableAgent(
    name="another_agent",
    is_termination_msg=lambda x: x.get("content", "") and x.get("content", "").rstrip().endswith("TERMINATE"),
    human_input_mode="NEVER",
    max_consecutive_auto_reply=10,
    code_execution_config={"work_dir": "coding"},
)
```

and everything works the same.

**Comment by victordibia** [comment]
@dluc 

A `ConversableAgent` is the **base class** for both the `UserProxyAgent` agent and `AssistantAgent`.  

The main difference between UserProxyAgent and AssistantAgent (and ConversableAgent) is that they have different default arguments. 

For example, while `UserProxyAgent` has human_input_mode set to `ALWAYS` by [default](https://github.com/microsoft/autogen/blob/503c2430f94a0e53fa574ba589cbf1674ada1d20/autogen/agentchat/user_proxy_agent.py#L23), AssistantAgent has it [default](https://github.com/microsoft/autogen/blob/503c2430f94a0e53fa574ba589cbf1674ada1d20/autogen/agentchat/assistant_agent.py#L36) to NEVER.  

View the links above to review the differences in default arguments.
