### ISSUE TITLE
Question: how to manage multiple Azure OpenAI resources?

### ISSUE THREAD

**Issue by dluc** [microsoft/autogen#511]
Assuming a configuration like this:

```json
[
    {
        "model": "gpt-4",
        "api_key": "sk-..."
    },
    {
        "model": "gpt-4-32k",
        "api_type": "azure",
        "api_key": "...",
        "api_base": "https://my-service-central-us.openai.azure.com/"
    },
    {
        "model": "gpt-4-32k",
        "api_type": "azure",
        "api_key": "...",
        "api_base": "https://my-service-france.openai.azure.com/"
    }
]
```
Note how all Azure settings are the same, except for `api_base`. Using `filter_dict`, is there a way to select "gpt-4-32k" in central-us vs france, **without** filtering on "api_base" (I cannot hard code personal settings in code) ? 

I tried adding a custom `group` key in the JSON config, but that causes request errors, because any extra key is included in the HTTP request:

```json
[
    {
        "group": "openai.com",
       ...
    },
    {
        "group": "azure-us",
       ...
    },
    {
        "group": "azure-france",
       ...
    }
]
```

==> `InvalidRequestError: Unrecognized request argument supplied: group` in `api_requestor.py:775`

**Comment by pcdeadeasy** [comment]
Please look at the example configuration: https://github.com/microsoft/autogen/blob/main/OAI_CONFIG_LIST_sample.

change the url end point in api_base.

**Comment by dluc** [comment]
@pcdeadeasy I have 2 Azure OpenAI deployments, one in US and one in France. How can I filter at runtime to select one or the other?

**Comment by pcdeadeasy** [comment]
Can you refer the documentation here: https://microsoft.github.io/autogen/docs/FAQ/, and see if are able to pass a specific configuration to the agent?

**Comment by victordibia** [comment]
@dluc, 

What do you think about the below

- create several `OAI_CONFIG_LISTS`. E.g. `OAI_CONFIG_LISTS`, `OAI_CONFIG_LISTS_US`, `OAI_CONFIG_LISTS_FRANCE` 
- in your code, define some logic for determining which region to use at any given time. 
- load the associated config file based on your region logic.


Something that looks like the below:

```python

def get_config_list(region: str):
    env_var = f"OAI_CONFIG_LIST_{region}"
    config_list = autogent.config_list_from_json(
        env_or_file=env_var, # could be a json file
        filter_dict={"model": {"gpt-4", "gpt-3.5-turbo"}}
    )
    return config_list

region = "US"  # Set the desired region
config_list = get_config_list(region)
print(f"Config list for {region}: {config_list}")
```

More details on how to set env config variable [here](https://github.com/microsoft/autogen/blob/main/notebook/oai_openai_utils.ipynb).
