### ISSUE TITLE
Improve documentation for validating agent responses

### ISSUE THREAD

**Issue by crypdick** [microsoft/autogen#512]
I need my agents to respond in specific formats, and so I want to validate their messages and respond with an error message if they give malformed responses. I see that the [Chess example makes use of `register_reply`](https://github.com/microsoft/autogen/blob/main/notebook/agentchat_chess.ipynb) to validate the agents make legal Chess moves, but the subclassed AssistantAgent are not well documented and neither are the [API docs](https://microsoft.github.io/autogen/docs/reference/agentchat/conversable_agent#register_reply).

Can someone explain how to validate an agent's outputs?

**Comment by victordibia** [comment]
Hi @crypdick ,

In general, `register_reply` can be seen as a function that get's called once the agent generates a response. We can repurpose this for a task such as printing the agents reponse, sending it over a socket etc. or validation in your case. 


In the sample below, I have an example of printing the response from the agent 

```python

def print_messages(recipient, messages, sender, config): 
    if "callback" in config and  config["callback"] is not None:
        callback = config["callback"]
        callback(sender, recipient, messages[-1])
    print(f"Messages sent to: {recipient.name} | num messages: {len(messages)}")
    return False, None  # required to ensure the agent communication flow continues

user_proxy.register_reply(
    [autogen.Agent, None],
    reply_func=print_messages, 
    config={"callback": None},
)

assistant.register_reply(
    [autogen.Agent, None],
    reply_func=print_messages, 
    config={"callback": None},
) 
``` 


You should be able to modify the `print_messages` function for validation e.g.
- inspect the last message in messages `messages[-1]` 
- perform your validation 
- raise some error  

It might help to share a toy example that we can use for debuggin purposes.

**Comment by crypdick** [comment]
Thanks for the quick response @victordibia ! I've tried to make a minimal example [here](https://gist.github.com/crypdick/a56337279b4f97d7a5e12616ee3d5b6a). The goal is to have a separate validator for different agents, and if a given agent fails a validation, to send a message back to that agent so that it can fix its mistake.

**Comment by crypdick** [comment]
Hey @victordibia , I wanted to follow up and see if you have had the chance to review my toy example. I haven't figured out how to get the callback working so that I can send error messages back to an agent.

**Comment by ekzhu** [comment]
@Nisarg1112  The chess notebook has a complete example: https://microsoft.github.io/autogen/0.2/docs/notebooks/agentchat_nested_chats_chess/
