### ISSUE TITLE
Issue with Autogen Installation? 

### ISSUE THREAD

**Issue by DiegoAMorales** [microsoft/autogen#526]
I've run into the following code: 

Traceback (most recent call last):
  File "x", line 6, in <module>
    config_list = config_list_from_json(env_or_file="OAI_CONFIG_LIST")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: config_list_from_json() got an unexpected keyword argument 'env_or_file'

This is the reason why I currently can't run Autogen. I'd like to point out that I was able to - pip install pyautogen and it appears I was able to complete this task successfully. My next step was: 'pip install openai' which I had to complete in a second local terminal but was also employed correctly ( no error codes were generated). 

Once I try to run the following operation: from autogen import AssistantAgent, UserProxyAgent, config_list_from_json
import openai

openai.api_key = 'x'

config_list = config_list_from_json(env_or_file="OAI_CONFIG_LIST")
assistant = AssistantAgent("assistant", llm_config={"config_list": config_list})
user_proxy = UserProxyAgent("user_proxy", code_execution_config={"work_dir": "coding"})
user_proxy.initiate_chat(assistant, message="Build a simple snake game")

The above error occurs and I'm not sure why. I'm currently following the steps outlined by Wes Roth in this YouTube tutorial (https://www.youtube.com/watch?v=oAsJVZlDOgQ&t=771s) because I'm no developer and he's explained the installation very well thus far. Thanks for anyone's help on this!

**Comment by sonichi** [comment]
I'm surprised to see this error. What happens if you remove `env_or_file=`?

**Comment by DiegoAMorales** [comment]
@sonichi Thank you for reaching out! I'm sorry as I'm a complete noob with this. Is this a command I should run in the terminal or? If you have a moment, I could also send screenshots or screenshare through Zoom.

**Comment by DiegoAMorales** [comment]
In addition @sonichi , I wanted to add that I re-tried going through the process and now the following error code appears:

  File "User file/main.py", line 2
    import.openai
          ^
SyntaxError: invalid syntax

Instead of the above. Not sure if the original error code will reappear if the above is fixed. Thanks for the attention!

**Comment by DiegoAMorales** [comment]
This thread is getting long my apologies. Was able to remove 'env_or_file' from the initial issue and figure the 'import openai' problem. Now the following error message comes out: 

Traceback (most recent call last):
  File "UserFile/main.py", line 6, in <module>
    config_list = config_list_from_json("OAI_CONFIG_LIST")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: config_list_from_json() takes 0 positional arguments but 1 was given

**Comment by DiegoAMorales** [comment]
Please disregard this post. I figured out the environment needed to be aligned. Fixed this through ChatGPT. Thanks!
