### ISSUE TITLE
One existing test needs [mathchat]. It'll be good to change that test in future to get rid of the dependency.

### ISSUE THREAD

**Issue by thinkall** [microsoft/autogen#544]
One existing test needs [mathchat]. It'll be good to change that test in future to get rid of the dependency. @kevin666aa for awareness.

_Originally posted by @sonichi in https://github.com/microsoft/autogen/pull/480#discussion_r1382312801_

**Comment by kevin666aa** [comment]
Got it!

**Comment by rysweet** [comment]
seems like this has long since been resolved.
