### ISSUE TITLE
v0.2.0b1: testing with the simplest code

### ISSUE THREAD

**Issue by jonny7737** [microsoft/autogen#550]
The simplest code:

Define:
  - config_list
  - llm_config

Instantiate:
  - assistant agent => AssistantAgent
  - user agent => UserProxyAgent

Call:
  - initiate_chat

Testing several prompts on several LLMs locally (no openai)
  - autogen caching is a problem
  - How to disable caching?

**Comment by sonichi** [comment]
add `"seed": None` in the `llm_config`
https://microsoft.github.io/autogen/docs/Installation#migration-guide-to-v02

**Comment by jonny7737** [comment]
Thanks.

The doc was unclear to me that it was referring to llm_config.

**Comment by jonny7737** [comment]
Thanks - For the help.

**Comment by jonny7737** [comment]
.cache/41 is still created and cache is still active.

**Comment by sonichi** [comment]
That's weird. When I use `assistant = AssistantAgent("assistant", llm_config={"config_list": config_list, "seed": None})` the cache is disabled. Could you verify the pyautogen version and share the code to reproduce it?

**Comment by jonny7737** [comment]
I'll see if I can craft a minimal piece of code that will reproduce the issue.  
FYI - Not seeing any other issues with v0.2.0b1

Feel free to close this ticket if you like.  I can create a new one with the reproducing code when I have it ready.

**Comment by sonichi** [comment]
Thank for testing and sharing the results! There is one bug in v0.2.0b1 which is fixed in #551 . The caching problem seems unrelated, but maybe worth trying.

**Comment by jonny7737** [comment]
The issue was caused by me not autogen.

Thanks for the help and sorry for the trouble.
