### ISSUE TITLE
can't use azure openai 

### ISSUE THREAD

**Issue by bubbleboth** [microsoft/autogen#558]
**This is my code**
import autogen
config_list= config_list= [
    {
        "model": "gpt-3.5-turbo-16k",
        "api_key": "xxxxxxxxxxxxxxxxxxxxxxxxx",
        "base_url": "https://xxxxxxx.openai.azure.com/",
        "api_type": "azure",
        "api_version": "2023-03-15-preview"
    }
]

assistant = autogen.AssistantAgent(
    name="assistant",
    llm_config={
        "seed": 42,  # seed for caching and reproducibility
        "config_list": config_list,  # a list of OpenAI API configurations
        "temperature": 0,  # temperature for sampling
    },  # configuration for autogen's enhanced inference API which is compatible with OpenAI API
)

user_proxy = autogen.UserProxyAgent(
    name="user_proxy",
    human_input_mode="NEVER",
    max_consecutive_auto_reply=10,
    is_termination_msg=lambda x: x.get("content", "").rstrip().endswith("TERMINATE"),
    code_execution_config={
        "work_dir": "coding",
        "use_docker": False,  # set to True or image name like "python:3" to use docker
    },
)

user_proxy.initiate_chat(
    assistant,
    message="""What date is today? Compare the year-to-date gain for META and TESLA.""",
)

and I got error like this , how can I fix it 
![image](https://github.com/microsoft/autogen/assets/129883941/fb0fd791-5a3f-4858-82e4-d4b4e44d02e9)

**Comment by sonichi** [comment]
#551 fixes a bug which may be related. Could you try that branch?

**Comment by bubbleboth** [comment]
@sonichi Thank you, it already worked when I changed to 'pip install pyautogen~=0.2.0b1

**Comment by mraguth** [comment]
Are you using Openai 1 or above? I am still getting the same error.
