### ISSUE TITLE
Improve manager's agent selection logic

### ISSUE THREAD

**Issue by telesccope** [microsoft/autogen#565]
I wrote a script in order to get the prompts, to indirectly understand how the groupchat works:
```python
from flask import Flask,request
import requests

app = Flask(__name__)

url = 'https://api.openai.com/v1/chat/completions'

@app.route('/', methods=['GET', 'POST'])
def index():
    data = request.get_json()
    print('data:',data)
    return "Hello, World!"

@app.route('/chat/completions', methods=['GET', 'POST'])
def index2():
    data = request.get_json()
    print('receive:',data)
    headers = {
            'X-OpenAI-Client-User-Agent':
                '{"bindings_version": "0.28.1", "httplib": "requests", "lang": "python", "lang_version": "3.10.6", "platform": "Linux-5.15.0-79-generic-x86_64-with-glibc2.35", "publisher": "openai", "uname": "Linux 5.15.0-79-generic #86-Ubuntu SMP Mon Jul 10 16:07:21 UTC 2023 x86_64"}',
                'User-Agent': 'OpenAI/v1 PythonBindings/0.28.1',
                'Authorization': 'Bearer <openai_api_key>',
                'Content-Type': 'application/json'
            }
    response = requests.post(url,json=data,headers=headers)
    result = response.json()
    print('return:',result)

    return result

if __name__ == '__main__':
    app.run(host='0.0.0.0',port=5002)
```
I know that the prompt of GroupChatManager is 'Read the above conversion. Then select the next role from \['user_proxy','Assistant',...\] to play. **Only return the role**.'
In my test case, after many rounds of conversations, enter thousands of tokens to get the name of next agent name.
![de942409f52ed694b904e38f8207ff2a](https://github.com/microsoft/autogen/assets/86958588/81254fd2-db98-4ae7-8ca8-cd8730b43559)
Whether the working order of the agent can be designed in advance in the subsequent update?

**Comment by afourney** [comment]
I believe this is related to: 
#485
#489

And PR:
#500

**Comment by telesccope** [comment]
> I believe this is related to: #485 #489
> 
> And PR: #500

Thanks! It seems that there are a lot of solutions, I'll try to create subclasses to specify the order of GroupChat.
