### ISSUE TITLE
Need to add "/" to the end of base_url.

### ISSUE THREAD

**Issue by thinkall** [microsoft/autogen#567]
In the docs of both autogen and openai python package, there is no "/" in the end of `base_url`, but it won't work for the current main branch of autogen. Would be better to keep the consistency, or even support both w/ and w/o "/".
Current valid example of Azure OpenAI config:
```
[{
    "model": "gpt-35-turbo",
    "base_url": "https://xxx.openai.azure.com/",
    "api_type": "azure",
    "api_version": "2023-05-15",
    "api_key": "xxx"
}]
```

Invalid:
```
[{
    "model": "gpt-35-turbo",
    "base_url": "https://xxx.openai.azure.com",
    "api_type": "azure",
    "api_version": "2023-05-15",
    "api_key": "xxx"
}]
```

@sonichi

**Comment by sonichi** [comment]
support both w/ and w/o "/" is the right solution. It should be an easy fix.
