### ISSUE TITLE
How do we intercept agent messages?

### ISSUE THREAD

**Issue by abhishek-ravikumar-kulkarni** [microsoft/autogen#570]
For instance, consider a workflow agent responsible for generating a series of tasks to execute a workflow. How can we capture or monitor the workflow steps it generates once the group chat is initiated?

**Comment by abhishek-ravikumar-kulkarni** [comment]
This helps @victordibia . Thanks

**Comment by jayralencar** [comment]
Hi, everyone.

How to do this with v0.5?

**Comment by victordibia** [comment]
@jayralencar ,

Yes, its easier than every. You can capture messages from the groupchat either as a full mages or streamed chunks. 

There is extensive documentation here - https://microsoft.github.io/autogen/dev/user-guide/agentchat-user-guide/tutorial/teams.html#observing-a-team 

A short video overview of the updated API is [here](https://youtu.be/zpJuaFgWzmQ?si=HpUK34EWDTKWXqxZ) 

[![Designing With AI](https://img.youtube.com/vi/zpJuaFgWzmQ/maxresdefault.jpg)](https://www.youtube.com/watch?v=zpJuaFgWzmQ&t=800s&ab_channel=DesigningWithAI )  
-  
 -
