### ISSUE TITLE
client.beta.assistants is present in OpenAI 1.1 but not 1.0

### ISSUE THREAD

**Issue by joshkyh** [microsoft/autogen#576]
Hey Team, 

I understand the dev team has very recently worked hard to upgrade OpenAI to v1.0.

The recent v 1.1 release/announcement from OpenAI is exciting for this project because of the OpenAI Assistant class.
The full release notes are [here](https://github.com/openai/openai-python/pull/682)

It'd be pretty exciting for Assistant classes in Autogen, ranging from retrieval to code interpreter. And maybe its worth waiting for the OpenAI Assistant to move out of Beta. :)

**Comment by afourney** [comment]
@sonichi can you take a look at this one? I know you're just finishing up the v1.0 port.
