### ISSUE TITLE
Simplify the agent structure by using only one userProxy

### ISSUE THREAD

**Issue by Jeffwan** [microsoft/autogen#580]
In multi-agent scenarios, I notice the agent orchestration using autogen is kind of complex. using this notebook as an example (https://github.com/microsoft/autogen/blob/main/notebook/agentchat_planning.ipynb). In order to invoke planner agent, It has to  create a `planner_user` which seems unnecessary. In that case, any method which likes to invoke an agent requires a dedicate user proxy, can we just use a single user_proxy for all the invocation?

```
planner_user = autogen.UserProxyAgent(
    name="planner_user",
    max_consecutive_auto_reply=0,  # terminate without auto-reply
    human_input_mode="NEVER",
)

```

**Comment by gagb** [comment]
I think that should work, especially cuz each agent maintains a separate chat history for other agents. Did you try it?

**Comment by Jeffwan** [comment]
@gagb I did some tests and it's working. there're few observations.

1. userProxy will talk directly with routed agent. In the demo case, planner_proxy plays the role
2. If the agent has tools associated, userProxy needs to be aware of the tool. for example, if we want to execute some codes, the single userProxy has to prepare the env. If we follow multi-user-proxy mode, it does provides some abstraction and end userproxy just needs to know the result and xxxuserproxy can play the role of runner.
