### ISSUE TITLE
Groupchat auto-terminate.

### ISSUE THREAD

**Issue by NikhilModi488** [microsoft/autogen#581]
Hi @iemejia @lgersman @qinc @msaelices @craigomatic,

I am facing some issues while working on the group chat of Autogen, i.e, while the chat incoming the chat comes and it terminates the whole chat for me and I am not able to access the same after this issue and it has happened to me multiple times in the group chat.

I have tried this as well but the issue persists.
is_termination_msg=lambda x: x.get("content", "").rstrip().endswith("TERMINATE")

groupchat = autogen.GroupChat(agents=[user_proxy, Interactor, Planner, executor, critic, Engineer, Analyst, Agent_selector], messages=[])
manager = autogen.GroupChatManager(groupchat=groupchat)
user_proxy.initiate_chat(manager, message=usr_input,clear_output=True, clear_history=True)

Please look into this.

Thank You.

**Comment by gagb** [comment]
Where have you set the above `is_termination_msg`?

**Comment by NikhilModi488** [comment]
> Where have you set the above `is_termination_msg`?

Only in user proxy.

user_proxy = autogen.UserProxyAgent(
    name="user_proxy",
    human_input_mode="ALWAYS",
    code_execution_config=False,
    is_termination_msg=lambda x: x.get("content", "").rstrip().endswith("TERMINATE"),
    llm_config={'temperature': 0},
)
