### ISSUE TITLE
How do we propagate custom configs/secrets to docker env when code execution needs to be done?

### ISSUE THREAD

**Issue by abhishek-ravikumar-kulkarni** [microsoft/autogen#585]
I want to know if theres a way to send custom secrets/configs to the docker env when code execution is being done in docker env.

**Comment by afourney** [comment]
Good question. In the Testbed, I write the secrets to an ENV file, which is provided to Docker via mounting a shared folder:

https://github.com/microsoft/autogen/blob/b41b366549c1a1815a9af61d9b27e090e3af6b25/samples/tools/testbed/run_scenarios.py#L192

It's not too onerous in that context, but I could see it becoming an issue in regular Autogen, which uses docker for every separate call or code execution. 

I'd be happy to learn of any alternate methods.

**Comment by abhishek-ravikumar-kulkarni** [comment]
@afourney I have raised a PR for this - https://github.com/microsoft/autogen/pull/620

**Comment by rysweet** [comment]
closing as the related PR was closed
