### ISSUE TITLE
RetrieveChat finds no docs with "spark" as a keyword when defaults doc is referenced in Example 1

### ISSUE THREAD

**Issue by tevslin** [microsoft/autogen#591]
The problem occurs because there actually isn't the word "spark" in the referenced document. If I take the reference to the keyword out, docs 0 and 1 are returned and code is generated and executed.

**Comment by thinkall** [comment]
> The problem occurs because there actually isn't the word "spark" in the referenced document. If I take the reference to the keyword out, docs 0 and 1 are returned and code is generated and executed.

Thanks @tevslin , have you followed the comments to prepare the reference docs of [FLAML](https://github.com/microsoft/FLAML) rather than AutoGen?

**Comment by tevslin** [comment]
No. I did see those instructions but thought the sample code would work in a limited fashion w/out modification. Thanks for checking.

**Comment by thinkall** [comment]
If the docs don't necessarily to contain `spark`, then `spark` should not be in the search string.
