### ISSUE TITLE
Open ai version conflict with new upadates on both ends

### ISSUE THREAD

**Issue by swappybizz** [microsoft/autogen#598]
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyautogen 0.2.0b1 requires openai==1.0.0b3, but you have openai 1.1.1 which is incompatible.`

**Comment by sonichi** [comment]
Could you try the new release [v0.2.0b3](https://github.com/microsoft/autogen/releases/tag/v0.2.0b3)?

**Comment by swappybizz** [comment]
I believe this worked but got sevear warnings
`...for venv
\Lib\site-packages\pyautogen-0.2.0b1.dist-info due to invalid metadata entry 'name'
\Lib\site-packages\openai-1.0.0b3.dist-info due to invalid metadata entry 'name'
\Lib\site-packages\pyautogen-0.2.0b1.dist-info due to invalid metadata entry 'name'
\Lib\site-packages\openai-1.0.0b3.dist-info due to invalid metadata entry 'name'
\Lib\site-packages\pyautogen-0.2.0b1.dist-info due to invalid metadata entry 'name'
\Lib\site-packages\openai-1.0.0b3.dist-info due to invalid metadata entry 'name'
\Lib\site-packages\pyautogen-0.2.0b1.dist-info due to invalid metadata entry 'name'
\Lib\site-packages\openai-1.0.0b3.dist-info due to invalid metadata entry 'name'

`
