### ISSUE TITLE
How does a list of models from config is assigned to different assistants in the backend? How can we customize it?

### ISSUE THREAD

**Issue by ivrschool** [microsoft/autogen#605]
Hi amazing people,

I have a question and I am hoping to get the answer.

When We are passing a list of models from config file to each of the assistant, how does the work assignment done to different agents in groupChat case.

For example, 

Config:

```
config_list_gpt4 = autogen.config_list_from_json(
    "OAI_CONFIG_LIST",
    filter_dict={
        "model": ["gpt-4-32k", "gpt-4-32k-0314", "gpt-4-32k-v0314"],
    },
)
```

Agents:

```
user_proxy = autogen.UserProxyAgent(
   name="Admin",
   system_message="...",
   code_execution_config=False,
)
engineer = autogen.AssistantAgent(
    name="Engineer",
    llm_config=gpt4_config,
    system_message='''...''',
)
scientist = autogen.AssistantAgent(
    name="Scientist",
    llm_config=gpt4_config,
    system_message="""..."""
)
```

How does autogen decides which model `(["gpt-4-32k", "gpt-4-32k-0314", "gpt-4-32k-v0314"])` should be assigned to which agent? Can anyone help me understand this?

One way to customize is by writing different config files for different agents. Is there any way to do the same with one config file?

Thank you a ton for your time.:pray:

**Comment by afourney** [comment]
It tries them in the order listed, and if there's an issue (e.g., rate limit) it moves down the list.

To get it to select a particular model, you can filter it:

E.g.,

https://microsoft.github.io/autogen/docs/reference/oai/openai_utils#config_list_from_json

**Comment by afourney** [comment]
I'm hoping the above answer addresses your question adequately. Please re-open this issue if not.
