### ISSUE TITLE
How To Install Autogen From Editable Source?

### ISSUE THREAD

**Issue by dhifafaz** [microsoft/autogen#606]
It seems i break the code if i install it from source. My python version is 3.11, I'm using `pip install -e .`. But when i try to call some function like this.

``` python
import autogen
autogen.config_list_from_json("jsonpath")
```

It throws an error that says autogen doesn't have the module. So i need to call it by using this.

``` python
autogen.oai.config_list_from_json("jsonpath")
```

**Comment by afourney** [comment]
I have had great success from -e, but always from a folder outside of autogen. Maybe give that a try (in which case it would be `pip install -r path_to_repo`). There is an autogen folder within the root of the repo, and it is perhaps getting confused.

**Comment by afourney** [comment]
Did this work for you? Please re-open this issue if you continue to have trouble with this.
