### ISSUE TITLE
Custom message in the middle of a group chat

### ISSUE THREAD

**Issue by PyroGenesis** [microsoft/autogen#613]
Hi,

Is it possible to add a custom message in the middle of a groupchat? Basically, I want my Coder agent to perform a task on a CSV file but before it does I want to add a message to the chat with the CSV headers and details so that the Coder agent knows about it.

The conversation flow would be something like this:
```
USER:
<Question about data>

CUSTOM MESSAGE
<information about the data file>

CODER:
<Writes code performing the operation specified by USER using the context information from CUSTOM MESSAGE>

USER:
<Executes code written by CODER>
```

**Comment by sonichi** [comment]
what about using a separate agent who inserts this custom message after the USER and before the CODER? Need to clearly specify the timing to trigger it in its system message.

**Comment by PyroGenesis** [comment]
@sonichi Thanks for the pointer. 

From what I understand, I could implement `select_speaker()` ([like this notebook](https://github.com/microsoft/autogen/blob/main/notebook/agentchat_hierarchy_flow_using_select_speaker.ipynb)) to control the flow like so: 
USER -> DATA PARSER -> CODER.

As for the new DATA PARSER agent, I could implement its `register_reply()` method to make it always simply return the CSV file info and nothing else.

Would this be a viable solution? Is there anything I'm overlooking?

**Comment by sonichi** [comment]
That sounds right.

**Comment by PyroGenesis** [comment]
I was able to create a conversation flow with my requirements + add agents for general questions and code execution. I'm sharing my current implementation with the hope it might be useful to others.

### Code: 

```py
from autogen.agentchat.groupchat import GroupChat
from autogen.agentchat.agent import Agent
from autogen.agentchat.assistant_agent import AssistantAgent

class CustomGroupChat(GroupChat):
    def __init__(self, agents, messages, max_round=10):
        super().__init__(agents, messages, max_round)
        self.previous_speaker = None  # Keep track of the previous speaker
    
    def select_speaker(self, last_speaker: Agent, selector: AssistantAgent):
        # Check if last message suggests a next speaker or termination
        last_message = self.messages[-1] if self.messages else None
        if last_message:
            if 'NEXT:' in last_message['content']:
                # if there is a suggested agent to speak next, pick them
                suggested_next = last_message['content'].split('NEXT: ')[-1].strip()
                print(f'Extracted suggested_next = {suggested_next}')
                try:
                    return self.agent_by_name(suggested_next)
                except ValueError:
                    return None  # If agent name is not valid, something went wrong
            
            elif 'TERMINATE' in last_message['content']:
                # termination gives back control to user
                return self.agent_by_name('User')
                    
            elif 'execution failed' in last_message['content']:
                # that means the executor spoke and there was an error
                # return control back to coder
                return self.agent_by_name('Coder')
        
        if last_speaker.name == "User":
            # the user should always prompt the commander
            return self.agent_by_name('Commander')

        elif last_speaker.name == "Data_Parser":
            # data parser relinquishes control to coder
            return self.agent_by_name('Coder')

        elif last_speaker.name == "Coder":
            # coder goes relinquishes control to executor
            return self.agent_by_name('Executor')
            
        elif last_speaker.name in ["General_Assistant", "Executor"]:
            # the leaf workers have spoken now
            # return control to the user
            return self.agent_by_name('User')

        else:
            # this would be an invalid state
            return None
        
        self.previous_speaker = last_speaker

```

### Diagram
This is a diagram of what the control flow looks like:

[![](https://mermaid.ink/img/pako:eNpdUctqwzAQ_JVFJxeSH_ChYGyTU6EhdS9xCRtrE4taUlhJtCXJv1e2laZEJ80-ZmZ3z6KzkkQuDoP96npkD29VayC-Jmsc8dMMiqy0WqORfxEX9kfGUw8jAWzXgZxX1gDubfBQbt4_5roydt67qqxCj7tX5Dt3ndXf1AVvbwEy8kHjSAa2KzLEOMBNKgmsspTYFc4p59H4R54GlstnKNIoExhd_8dRITmcYJnMT6BOPkdwUQcgZssXKMVCaGKNSsYFnseiVvieNLUij1-J_NmK1lxjHcbxNj-mE7nnQAsRThI9VQrjfFrkBxxcjJJUcQsv80Wmw1x_AZ2Qf9w?type=png)](https://mermaid.live/edit#pako:eNpdUctqwzAQ_JVFJxeSH_ChYGyTU6EhdS9xCRtrE4taUlhJtCXJv1e2laZEJ80-ZmZ3z6KzkkQuDoP96npkD29VayC-Jmsc8dMMiqy0WqORfxEX9kfGUw8jAWzXgZxX1gDubfBQbt4_5roydt67qqxCj7tX5Dt3ndXf1AVvbwEy8kHjSAa2KzLEOMBNKgmsspTYFc4p59H4R54GlstnKNIoExhd_8dRITmcYJnMT6BOPkdwUQcgZssXKMVCaGKNSsYFnseiVvieNLUij1-J_NmK1lxjHcbxNj-mE7nnQAsRThI9VQrjfFrkBxxcjJJUcQsv80Wmw1x_AZ2Qf9w)
