### ISSUE TITLE
Add support to different models to num_tokens_from_text

### ISSUE THREAD

**Issue by thinkall** [microsoft/autogen#63]
Currently only gpt-x models are supported, would be nice to add support to more models.

**Comment by vidhula17** [comment]
I would like to work on this. Can you please assign this to me?

**Comment by thinkall** [comment]
> I would like to work on this. Can you please assign this to me?

Hi @vidhula17 , thanks for your interest, I’ve assigned the task to you. Let me know if you need any assistance.

**Comment by vidhula17** [comment]
I have created a PR for this issue. Kindly look into it.
