### ISSUE TITLE
Refractor streaming for oai client

### ISSUE THREAD

**Issue by yiranwu0** [microsoft/autogen#633]
#597 is merged as a temporal solution. The following changes are needed: 
1. support streaming for function call.
2. move print outside oai function

**Comment by sonichi** [comment]
Could you add this issue to the task list of #217 ?
And use a task list for the subtasks.

**Comment by bitnom** [comment]
Some notes from [openai-community/function-calls-and-streaming](https://community.openai.com/t/function-calls-and-streaming/263393)

```python
func_call = {
        "name": None,
        "arguments": "",
    }
    for res in response:
        delta = res.choices[0].delta
        if "function_call" in delta:
            if "name" in delta.function_call:
                func_call["name"] = delta.function_call["name"]
            if "arguments" in delta.function_call:
                func_call["arguments"] += delta.function_call["arguments"]
        if res.choices[0].finish_reason == "function_call":
            # function call here using func_call
            return
        if not delta.get("content", None):
            continue
        sys.stdout.write(delta.content)
        sys.stdout.flush()
```

> I had another post about json.loads, the API doesn’t seem to always return a valid json object but rather a python object (with triple quotes for instance).
In their examples they use eval to parse arguments which, to me, seems incredibly dangerous.
I would suggest to use ast.literal_eval for now, as it is much safer.

**Comment by Deykeepcomn4me** [comment]
Hacker please call fbi
