### ISSUE TITLE
samples/tools/testbed/run_scenarios.py prepare the run script fails in windows environment

### ISSUE THREAD

**Issue by garyfollett** [microsoft/autogen#635]
the run.sh will fail in the docker container in a windows environment if newline='\n' is not included in the call.

 with open(os.path.join(work_dir, "run.sh"), "wt", newline='\n') as f:

**Comment by afourney** [comment]
Thanks for the report. I'll fix this ASAP, and include the fix in all cases where a file is written by the host OS, and read in the Docker image (I suspect that is the incompatibility here)

**Comment by afourney** [comment]
@garyfollett  I believe I have addressed this in PR #678
 
Please have a look and let us know if it works for you.
