### ISSUE TITLE
Format issue in README

### ISSUE THREAD

**Issue by sonichi** [microsoft/autogen#65]
A recent PR introduce a paragraph with some formatting issue:

Multi-agent conversations: AutoGen agents can communicate with each other to solve tasks. This allows for more complex and sophisticated applications than would be possible with a single LLM. Customization: AutoGen agents can be customized to meet the specific needs of an application. This includes the ability to choose the LLMs to use, the types of human input to allow, and the tools to employ. Human participation: AutoGen seamlessly allows human participation. This means that humans can provide input and feedback to the agents as needed.

They are supposed to be sub bullet points. A fix is appreciated.

**Comment by Itsbabin** [comment]
Hi, I want to contribute in this issue..

**Comment by sonichi** [comment]
Please. It's assigned to you.

**Comment by Itsbabin** [comment]
should I append those informations in one section or in separate 3 section ?

**Comment by sonichi** [comment]
@qingyun-wu could you suggest? Also, could you preview the doc before you approve a doc change?

**Comment by alhridoy** [comment]
Hello @sonichi 

I came across issue #65 regarding the formatting problem in the README. I've reviewed the conversation and understand that there's a need to format a paragraph as sub-bullet points. I'm super interested in contributing to this project and would like to offer my assistance if @Itsbabin requires any help or if there are other related tasks.

**Comment by Itsbabin** [comment]
@alhridoy please help me. I can't understand in which section I should write?

**Comment by Itsbabin** [comment]
Please help me in my first open-source contribution ☺️

**Comment by vidhula17** [comment]
I have created a PR, which resolves this issue. Kindly do check this @sonichi.
