### ISSUE TITLE
Code library like AgentCloud?

### ISSUE THREAD

**Issue by rickyloynd-microsoft** [microsoft/autogen#666]
Our discord contains discussion about the need for a code library for users to share their agents etc. One such library (built on AutoGen) already exists:  [AgentCloud](https://www.agentcloud.dev/) 

Should our repo provide links to AgentCloud? Do we have other ideas for supporting such libraries?

**Comment by sonichi** [comment]
We should provide links in our webiste. For example, this page: https://microsoft.github.io/autogen/docs/Examples/AgentChat and  this section: https://microsoft.github.io/autogen/docs/Use-Cases/agent_chat#diverse-applications-implemented-with-autogen
@qingyun-wu @JieyuZ2 any other suggestion?
Eventually I'd like to have an "ecosystem" page similar to what pytorch has.

**Comment by JieyuZ2** [comment]
Yeah providing links in the website is a good idea.

Is the code library similar to **autogen/agentchat/contrib**?

**Comment by sonichi** [comment]
No. The example above is a different repo. We'll have some other examples under samples/.

**Comment by qingyun-wu** [comment]
Add an ecosystem system page on our website displaying the featured integrations and a spreadsheet link or PR template formatted for anyone to make a request to display their agent's creations?
