### ISSUE TITLE
Spaces in agent names

### ISSUE THREAD

**Issue by rickyloynd-microsoft** [microsoft/autogen#668]
Group chat throws an error if an agent name contains a space. 

Should we fix this? If not, would ConversableAgent by the best place to document it?

**Comment by afourney** [comment]
@rickyloynd-microsoft Yes. We should fix it. I've got a PR in #669

**Comment by afourney** [comment]
@rickyloynd-microsoft I am not able to replicate this after #669. Can you check if this resolves the issue?

**Comment by rickyloynd-microsoft** [comment]
@afourney I never had a repro for the original problem. But after this is merged, I'll ask the user on discord to try it.

**Comment by sonichi** [comment]
I think this issue refers to a limitation of openai's requirement in the "name" field in messages.
