### ISSUE TITLE
InvalidRequestError: Unrecognized request argument supplied: cache_seed

### ISSUE THREAD

**Issue by nickjanssen** [microsoft/autogen#676]
Fresh install on anaconda using python 3.8

Probably related to https://github.com/microsoft/autogen/commit/dfcbea9777517a6d8386bf0b7f3c669094489bc9

**Comment by afourney** [comment]
Did you specify a beta version (e.g., 0.2.0b5) or just grab the latest stable?

**Comment by nickjanssen** [comment]
My bad, was using latest stable where the instructions said to use 0.2.0b4

**Comment by OGGEE61** [comment]
Hi, I am also getting that error, but I am using 0.1.8. So I guess using the 0.2.0b5 should solve this? Thanks in advance

**Comment by OGGEE61** [comment]
Hi, I am also getting the "InvalidRequestError: Unrecognized request argument supplied: cache_seed", even though I am using the 0.2.0b5. I have checked with the b6, but I am getting the same error. Any idea what might be the reason?
