### ISSUE TITLE
Add an example of Guidance + AutoGen

### ISSUE THREAD

**Issue by gagb** [microsoft/autogen#677]
IndyDevDan just dropped an incredible video of using Guidance to ensure structured JSON responses from AutoGen agents. It would be a good idea to add an example related to this because so many people have been asking for it.

Video: https://www.youtube.com/watch?v=XGCWyfA3rgQ&t=142s
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/autogen/pull/937
```

**Comment by qingyun-wu** [comment]
I believe @skzhang1 might be interested in help add this.

**Comment by mcchung52g** [comment]
I'm also interested in this. Currently having some hard time putting the two together because guidance now has a new syntax and the only way to integrate is to hook into autogen's generate reply method. Any example/help/lead will be great. Thanks!
