### ISSUE TITLE
Cache directory and database created even when cache_seed = None

### ISSUE THREAD

**Issue by afourney** [microsoft/autogen#679]
Prior to version 0.2.0, setting use_cache = False in the llm_config would prevent the .cache directory from being created.

The new method of disabling cache is to use seed = None (prior to 0.2.0b4) or cache_seed = None (after 0.2.0b4). However, setting the seed to None does not prevent the .cache folder from being created. In fact the following sqlite database gets initialized:

`.cache/None/cache.db`

This causes the fix in #593 to be less effective than with prior versions.

**Comment by joshkyh** [comment]
I had a similar small discussion -- adding here for context if it helps? https://github.com/microsoft/autogen/pull/600#discussion_r1387311379

**Comment by amanuel1782** [comment]
how to fix the issue of cache #when autogen is deployed in AWS lambda
