### ISSUE TITLE
Compare performance on learning of GPTAssistantAgent and TeachableAgent

### ISSUE THREAD

**Issue by gagb** [microsoft/autogen#680]

**Comment by rickyloynd-microsoft** [comment]
@gagb  Does GPTAssistantAgent provide learning beyond its (thread-extended) context?

**Comment by gagb** [comment]
No it doesn't but we don't know how exactly it manages the thread (e.g., it may be compressing). So we can only empirically compare the performance of the two agents.

**Comment by rickyloynd-microsoft** [comment]
I'll frame this in the larger context of #537, where I need to add many more details.

**Comment by gagb** [comment]
This issue is stale and not on the horizon as far as I know. Please re-open if its required.
