### ISSUE TITLE
Add new mode "WINDOW" for compressible agent

### ISSUE THREAD

**Issue by kevin666aa** [microsoft/autogen#685]
Add a mode, with the possible name "WINDOW", that provide a sliding windowing view of the chat history, for example, only the last 5 messages is reserved in the chat.

@bioshazard Are you still interested?

**Comment by bioshazard** [comment]
TY for the tag, definitely. If someone doesn't beat me to it, I'll probably get around to it after Thanksgiving.

**Comment by kevin666aa** [comment]
Compressible agent will be deprecated.
