### ISSUE TITLE
Add file to assistant to use in retrieval

### ISSUE THREAD

**Issue by hahl9000** [microsoft/autogen#686]
There is not documentation of adding file to GPT assistant using retrieval. It could be added at run-time on
assistant create or thread level. It could also be pre-defined in existing assistant id from OpenAI?

**Comment by rickyloynd-microsoft** [comment]
@gagb fyi

**Comment by sonichi** [comment]
@IANTHEREAL is this issue closed by #689 ?

**Comment by hahl9000** [comment]
Great work!
