### ISSUE TITLE
How to custom an agent?

### ISSUE THREAD

**Issue by Reason-Wang** [microsoft/autogen#698]
Is there a way to deeply custom an agent. (e.g. write an agent with a different reply function). Should I git clone the repo and modify the project directly?

**Comment by rickyloynd-microsoft** [comment]
Yes, that's a common approach, usually followed by creating a local branch for your modifications. The repo contains several examples of customized agents, like [TeachableAgent](https://github.com/microsoft/autogen/blob/main/autogen/agentchat/contrib/teachable_agent.py).

I'll close this issue. If you need further help, and depending on the details of what you are trying to do, our [Discord channel](https://discord.gg/pAbnFJrkgZ) is a thriving community for mutual help and discussion.

**Comment by sonichi** [comment]
Not necessarily modifying the project. There are many notebook examples which register custom reply functions without modifying the project. For example, https://github.com/microsoft/autogen/blob/main/notebook/agentchat_chess.ipynb
Of course, you are welcome to contribute back.
