### ISSUE TITLE
Project roadmap

### ISSUE THREAD

**Issue by qingyun-wu** [microsoft/autogen#70]
To ensemble a project roadmap? 

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/autogen/issues/48
```

**Comment by gagb** [comment]
@qingyun-wu is this issue necessary given that we have roadmap board in the readme now?

**Comment by sonichi** [comment]
@qingyun-wu could you respond?

**Comment by qingyun-wu** [comment]
I think we can close this issue now! Thanks @gagb  @sonichi !
