### ISSUE TITLE
GroupChat: Feedback to the user when it finishes early

### ISSUE THREAD

**Issue by m-carter1** [microsoft/autogen#706]
With GroupChat, if max_rounds is reached Autogen will just stop, with no feedback to the User. 

It would be very useful to have some feedback, such as a message to say why it's stopped. 

There may be other instances when it stops with no feedback, such as reply returning None or a function returning None.

**Comment by afourney** [comment]
The same is true for other agent configurations.

It would be great to get some signal that captures the reason for termination.

**Comment by sonichi** [comment]
I agree with @afourney that the feature is worth adding whenever termination happens, not only group chat.

**Comment by jtoy** [comment]
The code looks good. I suggest adding tests to make sure it works as expected.
