### ISSUE TITLE
Better name management of threads and assistants using OpenAI APIs

### ISSUE THREAD

**Issue by dcburger1** [microsoft/autogen#709]
The OpenAI APIs have some surprising friction, where you can create an assistant with a name, the creation returns an ID, and then you need to save the ID to find the assistant in subsequent developments.  You can search the list of created agents to find the ID, of course.  Same issue with threads.  It would be awesome if AutoGen allowed you to refer to the agents by name, and either did a search or mapping behind the scenes to users don't need to curate these IDs.

**Comment by IANTHEREAL** [comment]
Good idea!
