### ISSUE TITLE
filename change in README

### ISSUE THREAD

**Issue by sonichi** [microsoft/autogen#71]
`# and OAI_CONFIG_LIST_sample.json`
should be
`# and OAI_CONFIG_LIST_sample`

**Comment by 0xJaskeerat** [comment]
@sonichi Please review my PR for this issue

**Comment by sonichi** [comment]
I haven't seen it.

**Comment by 0xJaskeerat** [comment]
> I haven't seen it.

The PR or the changes in the PR ?

**Comment by sonichi** [comment]
I haven't seen the PR.

**Comment by 0xJaskeerat** [comment]
@sonichi The PR is right up, just below your issue description 
Already submitted a PR 10 hours ago
