### ISSUE TITLE
[ENH] accessing the run steps with GPTAssistantAgent

### ISSUE THREAD

**Issue by YannDubs** [microsoft/autogen#715]
The current GPTAssistantAgent only returns the output from the last step when you call `_invoke_assistant`. But in many cases I would like to be able to see what were the intermediate calls that were made. You can get that information using `self.openai_client.beta.beta.threads.runs.steps.list(thread_id=..., run_id=..., order="asc")` as shown [here](https://github.com/openai/openai-cookbook/blob/main/examples/Assistants_API_overview_python.ipynb). But I don't think you can currently get the run_id of the last call to get those steps. For more interpretability and when developing, it would be nice to either:
1. save the latest `run_id` to be able to get the steps
and/or
2. have an option in `_invoke_assistant` to return all the steps

E.g. this i useful when using web search or code_interpreter to know what were the arguments and how many calls were there.

Ps: thanks for the great library 💯

**Comment by gagb** [comment]
@YannDubs checkout this PR https://github.com/microsoft/autogen/pull/665

**Comment by YannDubs** [comment]
Thanks @gagb, But I don't quite see how the PR addresses the issue. You still can't access the run.id after invoking the assistant, right?

**Comment by gagb** [comment]
It doesn't yet, but perhaps `_get_run_response`  and `_process_messages` can be modified to log steps (or add them to the message itself). Or did I misunderstand your question?

https://github.com/microsoft/autogen/blob/7ae462df737e9448f85df336dc20d87d652a88ab/autogen/agentchat/contrib/gpt_assistant_agent.py#L151
https://github.com/microsoft/autogen/blob/7ae462df737e9448f85df336dc20d87d652a88ab/autogen/agentchat/contrib/gpt_assistant_agent.py#L158

**Comment by sonichi** [comment]
@IANTHEREAL FYI

**Comment by YannDubs** [comment]
Thanks @IANTHEREAL but #717 seems to be only about the function execution right? It won't show all the steps in the assistant in the case where you use the code interpreter, right?

I haven't looked too deeply into it so I might be wrong, but I was under the impression that those substeps are controlled by OpenAI and you can only access them using `client.beta.threads.runs.steps`
