### ISSUE TITLE
[error]: GPTAssistantAgent doesn't work with gpt model from Microsoft Azure

### ISSUE THREAD

**Issue by YuanZongjian** [microsoft/autogen#722]
I am trying to apply the gpt-4-1106 model from Microsoft Azure to run the GPTAssistantAgent. Then I got error:     

        _Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}
        httpx.HTTPStatusError: Client error '404 Resource Not Found' for url 'https://my azure openai base url/openai/deployments/gpt-4-1106/assistants'
        For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
        
        During handling of the above exception, another exception occurred:
        
          File "/home/yzj/LLM_project/writer_v0.0/writer.py", line 60, in <module>
            planner = GPTAssistantAgent(
        openai.NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}_

my oai_config_list is as below:
`{
        "model":"gpt-4-1106",
        "api_type":"azure",
        "base_url": "****",
        "api_key":"****"
},`

Is this because the GPTAssistantAgent only run with OpenAI api?

**Comment by rickyloynd-microsoft** [comment]
@gagb fyi

**Comment by gagb** [comment]
@YuanZongjian , GPTAssistantAgent uses the OpenAssistant API which is not available on Azure yet.

**Comment by YuanZongjian** [comment]
> @YuanZongjian , GPTAssistantAgent uses the OpenAssistant API which is not available on Azure yet.

Okay, I see. Thank you

**Comment by KAIYI-HSU** [comment]
May I ask if I cannot use the base_url "localhost:8000/v1" when using the FastChat API on the local end? I encountered an openai.notfounderror with the GPTAssistantAgent, too. The error code is 404.

I have another question:
Is there any difference between running a Python program with GPTAssistantAgent and UserProxyAgent?
It seems like the code interpreter function and the "run Python" function in UserProxyAgent are very similar.
Thank you for your answer.
