### ISSUE TITLE
How to add a new vector database?

### ISSUE THREAD

**Issue by hsm207** [microsoft/autogen#725]
I would like to contribute a [weaviate](https://github.com/weaviate/weaviate) integration and would like advise on how to build this integration.

It seems the current way to do it according to PR #161 is to subclass `RetrieveUserProxyAgent` and implement the `retrieve_docs` and `query_vector_db` methods. However, there's also a recent PR (#619 ) that proposes a new retriever API.

Which approach is going to be supported in release >= 0.2?

**Comment by thinkall** [comment]
Thank you @hsm207 , if you'd like to use your integration in a short time, say one or two days, I suggest you follow #161. If you can wait till next week, then maybe it's better to wait or start based on #619.

Let me know if you need more info. Thanks.

**Comment by hsm207** [comment]
@thinkall thanks for the clarification. I'll wait until #619 is merged.

**Comment by garethchengibm** [comment]
@thinkall Could you kindly provide an estimate of when this might be merged? Thank you

**Comment by thinkall** [comment]
> @thinkall Could you kindly provide an estimate of when this might be merged? Thank you

Hi @garethchengibm , I'm oof this week, will try finish reviewing and merge the PR next week. Thanks.

**Comment by thinkall** [comment]
Hi @hsm207, are you still interested in contributing weaviate integration? We've a new abstraction of vectordb.

**Comment by hsm207** [comment]
@thinkall yes, i'm interested in contributing a weaviate integration. Where can I find the docs to understand what I need to implement and are there already implementations that use the new abstraction that I can use as reference?

**Comment by swadharma-me** [comment]
Any update on if this is implemented ? thanks a ton

**Comment by hsm207** [comment]
@swadharma-me I haven't started on this yet. I'll probably have some down time around Q4 to contribute so open to someone else contributing if they have the capacity sooner.

**Comment by rysweet** [comment]
some examples of this in 0.2 and 0.4. closing this issues as stale.

**Comment by aperez900907** [comment]
Do you know if there are any advances in this project? Are you using VectorDBBase to extend the base class?
Thanks.
