### ISSUE TITLE
Builtin method for Azure Cognitive Search?

### ISSUE THREAD

**Issue by tyler-suard-parker** [microsoft/autogen#727]
I noticed there was a module for searching Qdrant, it would be nice to have one too for Azure Cognitive Search.

**Comment by sonichi** [comment]
It might be as easy as adding the right configuration in the llm because I remember seeing a similar question which uses Azure Cognitive Search in an API compatible with openai inference.

**Comment by joao-d-oliveira** [comment]
I would also be very happy for such solution.
I can't find any documentation related with Azure Cognitive Search and AutoGen.

**Comment by blakedwbrownie** [comment]
Agreed - would be great to have an example of how to use AutoGen with Azure Cognitive/AI Search. Not finding any documentation on it. I think we might be able to create a custom implementation of the RetrieveUserProxyAgent like [they did with Qdrant](https://microsoft.github.io/autogen/blog/2023/10/18/RetrieveChat#customizing-vector-database). But given this is a microsoft backed project, I imagine a dedicated Azure AI Search implementation should be on the roadmap

**Comment by bsonnek** [comment]
I'm surprised this isn't built into Autogen already, is anyone actively working on adding Azure AI Search RAG Agents?

Adding the completions extensions API for DataSources to the llm_config could help to implement this. 
https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#azure-ai-search

Sample app example for datasources extensions - https://github.com/microsoft/sample-app-aoai-chatGPT/blob/main/app.py

config_list = [
    {
        "model": "gpt-35-turbo-16k",
        "api_key": os.environ.get("AZURE_OPENAI_API_KEY"),
        "api_base": os.environ.get("AZURE_OPENAI_ENDPOINT"),
        "api_type": "azure",
        "api_version": "2023-05-15",
        "dataSources": [
            {
                "type": "AzureCognitiveSearch",
                "parameters": {
                    "endpoint": f"https://{AZURE_SEARCH_SERVICE}.search.windows.net",
                    "key": AZURE_SEARCH_KEY,
                    "indexName": AZURE_SEARCH_INDEX,
                    "fieldsMapping": {
                        "contentFields": parse_multi_columns(AZURE_SEARCH_CONTENT_COLUMNS) if AZURE_SEARCH_CONTENT_COLUMNS else [],
                        "titleField": AZURE_SEARCH_TITLE_COLUMN if AZURE_SEARCH_TITLE_COLUMN else None,
                        "urlField": AZURE_SEARCH_URL_COLUMN if AZURE_SEARCH_URL_COLUMN else None,
                        "filepathField": AZURE_SEARCH_FILENAME_COLUMN if AZURE_SEARCH_FILENAME_COLUMN else None,
                        "vectorFields": parse_multi_columns(AZURE_SEARCH_VECTOR_COLUMNS) if AZURE_SEARCH_VECTOR_COLUMNS else []
                    },
                    "inScope": True if AZURE_SEARCH_ENABLE_IN_DOMAIN.lower() == "true" else False,
                    "topNDocuments": int(AZURE_SEARCH_TOP_K),
                    "queryType": query_type,
                    "semanticConfiguration": AZURE_SEARCH_SEMANTIC_SEARCH_CONFIG if AZURE_SEARCH_SEMANTIC_SEARCH_CONFIG else "",
                    "roleInformation": AZURE_OPENAI_SYSTEM_MESSAGE,
                    "filter": filter,
                    "strictness": int(AZURE_SEARCH_STRICTNESS)
                }
            }
        ]
    }  
]

**Comment by m-carter1** [comment]
I've got it working, but I needed to do some minor changes (I may submit a PR if i have time)

If anyone is interested the basic steps are:

- add the dataSources section to "extra_body" in llm_config
- add "/extensions" to the model name, this is hacky but it means the correct completions url is used

Those 2 steps should create the correct request but the response.choices causes an error, it expects a Message value to check for any function_call's but this is null and instead the message data is in Messages.
I created a AzureCognitiveSearchAgent agent and override generate_oai_reply with a fix in there but there may be a better way.



Config Examples

config_list = [
    {
        'model': "[MODEL_NAME]/extensions",
        'api_key': apiKey,
        'base_url': base_url,
        'api_type': apiType,
        'api_version': search_api_version,
    }
]

llm_config={
	"timeout": 600,
	"cache_seed": 41,
	"config_list": config_list,
	"extra_body":{
		"dataSources":[
		{
			"type": "AzureCognitiveSearch",
			"parameters": {
				"endpoint": "https://[SEARCH_NAME].search.windows.net",
				"indexName": "[INDEX_NAME]",
				"key": "[SEARCH_KEY]"
			}
		}
		]
	}
},

**Comment by cforce** [comment]
@m-carter1  Please summit MR

**Comment by ekzhu** [comment]
Is it only for retrieval argumented agent? Would you consider adding the support in the retrieval_utils.py, and creating an AgentCapability so RAG can be added to any agent?

**Comment by sonichi** [comment]
> Is it only for retrieval argumented agent? Would you consider adding the support in the retrieval_utils.py, and creating an AgentCapability so RAG can be added to any agent?

This is a functionality from Azure Cognitive Search. It has an API compatible to Azure OpenAI. Any ConversableAgent can use the `llm_config` to access Azure Cognitive Search. So I don't think a AgentCapability is necessary here. But documentation, examples are going to be helpful.
cc @jackgerrits @m-carter1 @thinkall

**Comment by cforce** [comment]
Are there any examples meanwhile?

**Comment by chengyuliu-msft** [comment]
Looking for a solution for Azure AI search, too.

**Comment by 9hsein5** [comment]
No need to modify any code passing the this way it will make it compatible with Azure AI Search, only need probably to modify the response since references aren't returned so we have a need to overide OpenAIWrapper 

config_list = [{
        "model": "gpt-35-turbo",
        "api_key": "***",
        "base_url": "https://<***>.openai.azure.com/",
        "api_type": "azure",
        "api_version": "2024-02-15-preview",
        "extra_body": {
            "data_sources": [
                {
                    "type": "AzureCognitiveSearch",
                    "parameters": {
                        "endpoint": "https://<***>.search.windows.net",
                        "indexName": "<***>",
                        "key": "<***>",
                        "semanticConfiguration":"<***>",
                        "queryType":"semantic",
                        "fieldsMapping": {
                            "contentFieldsSeparator": "\n",
                            "contentFields": ["<***>"],
                            "filepathField": "<***>",
                            "titleField": "<***>",
                            "urlField": "<***>",
                            "vectorFields": []
                        },
                        "filter": null,
                        "inScope": true,
                        "strictness": 3,
                        "topNDocuments": 5
                    }
                }
            ]
        }
    }
]

**Comment by tyler-suard-parker** [comment]
@9hsein5 do you want to work together on a PR for adding your code to Autogen?

**Comment by 9hsein5** [comment]
> @9hsein5 do you want to work together on a PR for adding your code to Autogen?

Yes let's go with it

**Comment by tyler-suard-parker** [comment]
@sonichi Do you have any recommendations for how we can implement this according to @9hsein5 's code?  Do you want us to create a protocol/interface etc?  What file or folder would you recommend we add this to?

**Comment by FarshidShafia** [comment]
looks like the issue is solved here:
https://microsoft.github.io/autogen/docs/notebooks/agentchat_azr_ai_search/
I guess the thread can be closed
