### ISSUE TITLE
Could you please make this more descriptive?

### ISSUE THREAD

**Issue by tyler-suard-parker** [microsoft/autogen#728]
https://github.com/microsoft/autogen/blob/ef1c3d3f7f46fd7323aeecb7000ad99c43564a75/autogen/retrieve_utils.py#L310

Variable name: query_texts
Variable description: the query texts

Yes, I understand that, but what do you mean by query texts?  Is this a list of strings that are going to be used to query documents?  If so then why do we have a search string?

**Comment by rickyloynd-microsoft** [comment]
@thinkall fyi

**Comment by thinkall** [comment]
@tyler-suard-parker thanks for asking, it’s a list of strings, `query_texts (List[str]): the query texts.` says `List[str]`. Does it make sense to you?

**Comment by tyler-suard-parker** [comment]
Sorry, still no.  I understand it is a list of strings, but what is the purpose of the query_texts argument?

**Comment by thinkall** [comment]
It contains the text used for retrieving documents from the database.

**Comment by tyler-suard-parker** [comment]
@thinkall Thank you.  How is that different from the search string?

**Comment by thinkall** [comment]
> @thinkall Thank you. How is that different from the search string?

Thank you @tyler-suard-parker , I get your point. This is not a user-oriented function, if you come to this file from [here](https://github.com/microsoft/autogen/blob/b30ead29459b89d0b381066ca9af709acca37f86/autogen/agentchat/contrib/retrieve_user_proxy_agent.py#L371), `search_string (str): only docs containing this string will be retrieved.` you may not be so confused.

I'll make a PR to improve the doc_string. Thanks.
