### ISSUE TITLE
file not retrieved in assistant_retrieval notebook

### ISSUE THREAD

**Issue by ramsoai** [microsoft/autogen#731]
Using the exact script in the notebook, I get the following results:
https://github.com/microsoft/autogen/blob/main/notebook/agentchat_oai_assistant_retrieval.ipynb

user_proxy (to assistant):

What is the name of the class of agents I gave you?

--------------------------------------------------------------------------------
assistant (to user_proxy):

It appears that there aren't any documents uploaded in this conversation. To provide you with the name of the class of agents, I would need the relevant document or information to be uploaded. Could you please upload the document that contains the information about the class of agents you're referring to?

--------------------------------------------------------------------------------

**Comment by rickyloynd-microsoft** [comment]
@thinkall fyi

**Comment by gagb** [comment]
> Hi @ramsoai , have you replaced the file id to the one you have access to?
> 
> @gagb Whether the comment `# add id of an existing file our openai account` should be `# add id of an existing file of your openai account`?

added a pr. see above

**Comment by ramsoai** [comment]
I have kept the format as is, and replaced the fileid with another one I have uploaded manually to the openai playground.  I still get the same answer.

llm_config = {
    "config_list": config_list,
    "assistant_id": assistant_id,
    "tools": [
            {
                "type": "retrieval"
            }
        ],
    "file_ids": ["file-CmlT0YKLB3ZCdHmslF9FOv69"]  
    # add id of an existing file our openai account
    # in this case I added the implementation of conversable_agent.py
}

I've also tried multiple files in this format as well:

"file_ids": ["file-CmlT0YKLB3ZCdHmslF9FOv69","file-xxxx"]

**Comment by ramsoai** [comment]
This has been solved with the latest beta6 update.  Thank you!!
