### ISSUE TITLE
Integrate the initiate_chat with Streamlit/Gradio.

### ISSUE THREAD

**Issue by NikhilModi488** [microsoft/autogen#740]
Hello,

I have created a chatbot with multiple agents using groupchat, groupchatmanager, and initiate_chat. Human_input_mode is set ALWAYS in the UserProxyAgent.  Now, I want to integrate initiate_chat with a Streamlit UI. How can I accomplish this and display only one agent's output and user input in the UI while they engage in a conversation?

**Comment by rickyloynd-microsoft** [comment]
I'm not familiar with Streamlit, but it's been discussed by many on our [Discord server](https://discord.gg/pAbnFJrkgZ). You may find good suggestions there.

**Comment by janaka** [comment]
@rickyloynd-microsoft This seems like the same point I was getting at in the simple sample issue.
