### ISSUE TITLE
Add request for the class GPTAssistantAgent

### ISSUE THREAD

**Issue by Alblahm** [microsoft/autogen#747]
Is it possible to add the "**retrieve**" method  to the "GPTAssistantAgent" class in a similar way as it supports the "**delete**" method.

The autogen class "GPTAssistantAgent" supports the "delete_assistant" method, in the same way as the openAI "Assistants" class. 
This should be very usefull to **allow the users to reuse or  modify the created assistants online** inside the OpenAI api web, and then just retrieve them from the sample code...  Now you can create the assistants, and also you can modify, but you cant recover one previously used assistant.

Example from the autogen  "agentchat_oai_assistant_retrieval.ipynb"

### If you try to replace the code that creates one GPTAssistantAgent, using the OpenAI retrieve, it does not work ...

```
# ORIGINAL CODE
gpt_assistant = GPTAssistantAgent(name="assistant",
                                instructions="You are adapt at question answering",
                                llm_config=llm_config)

user_proxy.initiate_chat(gpt_assistant, message="What is the name of the class of agents I gave you?")
```

```
# TRY to import from OPENAI web ...
from openai import OpenAI
client = OpenAI(
  organization='org-XXXXXXXX', api_key="sk-XXXXXXXXXXXXXX",
)
gpt_assistant = client.beta.assistants.retrieve("asst_XXXXXXXXX")
user_proxy.initiate_chat(gpt_assistant, message="What is the name of the class of agents I gave you?")
```
The second code does not work, probably because you have to cast the agent from one type to the other.  But it sould be interesting for the autogen assistants to include the option of recovering the assistants previously saved.

**Comment by gagb** [comment]
@Alblahm, This was addressed in https://github.com/microsoft/autogen/pull/718?

**Comment by gagb** [comment]
was addressed.
