### ISSUE TITLE
Why is config list a list?

### ISSUE THREAD

**Issue by austinmw** [microsoft/autogen#749]
Hi, it seems that the basics of the config list structure is missing or not obvious from the documentation.

Why is config list a list of models in the first place? What happens with this list of models when you pass it to an agent? Does it just use the first one or choose one with some criteria? The structure and use of the config list seems like something that should be at the very top of the documentation.

**Comment by rickyloynd-microsoft** [comment]
Yes, this is critical information to surface. It's also complicated. The fullest explanation is in [oai_openai_utils.ipynb](https://github.com/microsoft/autogen/blob/main/notebook/oai_openai_utils.ipynb). The Quickstart on the main readme refers to OAI_CONFIG_LIST_sample and the ./notebook folder. Suppose that we expanded item 2 in the Quickstart to say:

**Copy OAI_CONFIG_LIST_sample to ./notebook folder, name to OAI_CONFIG_LIST, and set the correct configuration. (See [oai_openai_utils.ipynb](https://github.com/microsoft/autogen/blob/main/notebook/oai_openai_utils.ipynb) for details on model configurations.)**

Would that fill in the documentation gap, or would you suggest doing more?

**Comment by austinmw** [comment]
Hi, thanks for your quick reply. A couple comments:

The notebook example goes into a lot of detail about how to generate a config list, but lacks sufficient detail about how the config list is actually used by autogen. It mentions, "config_list aids in dynamically selecting the appropriate model configuration, managing API keys, endpoints, and versions for efficient operation of the intelligent assistant", but this is too vague in my opinion. It doesn't give me any actionable information on how I should best define a config list for a specific use case. Additionally, If I was concerned about cost or latency I'd still be very unsure how to estimate how often each model may be used.

Also the notebook is obscured a bit by its title alone. I'd really recommend a notebook that's titled, `config_list_guide.ipynb` or something like that. Especially considering users will likely want to know how to set configurations across not only OpenAI models, but local models, and other API services.

**Comment by rickyloynd-microsoft** [comment]
Thanks for the recommendations!

**Comment by sonichi** [comment]
@AaronWard FYI about the notebook title suggestion.
@austinmw the missing info you are looking for is at https://microsoft.github.io/autogen/docs/Use-Cases/enhanced_inference#error-handling
It'll be good to fill the gap by making a link to that page in the notebook or a more prominent place if desired.

**Comment by sonichi** [comment]
I've seen more than one people asking this question. We should definitely improve the documentation. Any volunteer?

**Comment by javadrip** [comment]
@sonichi I asked a similar question on Discord yesterday (which you and @rickyloynd-microsoft have very kindly responded to). 

I would love to help, but as a newbie , I'd probably need some guidance. 😬

**Comment by sonichi** [comment]
Thanks. The easiest thing to do is to add the link at the place where you thought you were supposed to find that info. An outsider could actually be good at this task because it is a blind spot of the insiders.

**Comment by AaronWard** [comment]
> @AaronWard FYI about the notebook title suggestion.

Just seeing this issue now. Good call out.

The reason for the name is because of it being in `autogen/oai/openai_utils.py`. Considering config lists are provider agnostic the functions not directly related to openai could be broken out into a separate file, and keep `retrieve_assistants_by_name` in `openai_utils.py`?

**Comment by rickyloynd-microsoft** [comment]
Closely related to #797

**Comment by jonmadison** [comment]
Observation: custom models respect config list as a list, but do not bring the `tools` along in the `config` param for the custom model.  Wondering if anyone else has experience this. I've a workaround, (i.e. sending the config as a `dict`) but would like things to be consistent and will dig in to ensure it's not just me.
