### ISSUE TITLE
Azure OpenAI API requires 'content' field despite documentation stating otherwise

### ISSUE THREAD

**Issue by pachacamac** [microsoft/autogen#75]
**Description:**
When interacting with the Azure OpenAI API, the 'content' field is mandated even though the official API documentation mentions it as optional. This inconsistency leads to an error message: `'content' is a required property - 'messages.2'`.

**Steps to Reproduce:**
1. Set up Azure OpenAI API integration as per the documentation.
2. Make a request without the 'content' field.
3. Observe the error message.

**Expected Behavior:**
The API should accept requests without the 'content' field, as per the documentation.

**Actual Behavior:**
The API returns an error message: `'content' is a required property - 'messages.2'`.

**Reference:**
Error can be traced back to [conversible_agent.py:274](https://github.com/microsoft/FLAML/blob/main/flaml/autogen/agentchat/conversable_agent.py#L274).

**Environment:**
- Azure OpenAI version: 2023-08-01-preview

**Comment by sonichi** [comment]
Thanks. @kevin666aa is this a known issue to you?

**Comment by kevin666aa** [comment]
Thank you! We are fixing this in PR #47. We will set "content" to None if only "function_call" is in the message. This error might occur because the model make a function call directly.

With OpenAI API, it is observed that content is set to None.
```
# returned message
{
"content" : None,
"function_call"L "..."
...
}

It might be different with  AzureAI (That the field is not there?), and we will do the same handling of setting it to None.

**Comment by kevin666aa** [comment]
@pachacamac We updated the code. Can you pull and test it to see if the error persists?
