### ISSUE TITLE
autogen-assistant doesn't work on Azure OpenAI

### ISSUE THREAD

**Issue by ArneJanning** [microsoft/autogen#755]
If you edit the the `get_default_agent_config()`-Method in utils.py to use Azure OpenAI, as described in the [documentation](https://github.com/microsoft/autogen/tree/main/samples/apps/autogen-assistant):

`def get_default_agent_config(work_dir: str, skills_suffix: str = "") -> FlowConfig:
    """
    Get a default agent flow config .
    """

    llm_config = LLMConfig(
        config_list=[{
                "model": "gpt4",
                "api_key": "<myKey>",
                "api_base": "<myBase>",
                "api_type": "azure",
                "api_version": "2023-06-01-preview" 
        }],
        temperature=0,
    )
`
Then you'll receive an error:

`openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
`

**Comment by victordibia** [comment]
Thanks for noting this @ArneJanning .

I am looking at the OAI_CONFIG_LIST documentation here and it looks like the correct formatting for azure openai models is

```json
{
        "model": "<your Azure OpenAI deployment name>",
        "api_key": "<your Azure OpenAI API key here>",
        "base_url": "<your Azure OpenAI API base here>",
        "api_type": "azure",
        "api_version": "2023-07-01-preview"
    }
```

Note that the difference is `api_base ` -> `base_url `. 

What do you get when you try the above?

**Comment by ArneJanning** [comment]
Thank you for your answer @victordibia .

I changed the `api_base` to `base_url` and still get the same error:

`autogenra ui --port 8081

INFO:     Started server process [105794]

INFO:     Waiting for application startup.

INFO:     Application startup complete.

INFO:     Uvicorn running on http://127.0.0.1:8081 (Press CTRL+C to quit)

INFO:     127.0.0.1:56470 - "GET / HTTP/1.1" 200 OK

INFO:     127.0.0.1:56470 - "GET /app-a69e64a20490df34caf8.js HTTP/1.1" 200 OK

INFO:     127.0.0.1:56482 - "GET /framework-34c4775408c4a2a587eb.js HTTP/1.1" 200 OK

INFO:     127.0.0.1:56470 - "GET /webpack-runtime-9a1c1a0dc45832ebafbd.js HTTP/1.1" 200 OK

INFO:     127.0.0.1:56482 - "GET /page-data/index/page-data.json HTTP/1.1" 200 OK

INFO:     127.0.0.1:56470 - "GET /page-data/app-data.json HTTP/1.1" 200 OK

INFO:     127.0.0.1:56470 - "GET /component---src-pages-index-tsx-9c8c5671443f8293283f.js HTTP/1.1" 200 OK

INFO:     127.0.0.1:56470 - "GET /skills?user_id=guestuser@gmail.com HTTP/1.1" 200 OK

INFO:     127.0.0.1:56482 - "GET /messages?user_id=guestuser@gmail.com HTTP/1.1" 200 OK

INFO:     127.0.0.1:56488 - "GET /manifest.webmanifest HTTP/1.1" 200 OK

Traceback (most recent call last):

  File "/home/arne/src/autogen3/autogen/samples/apps/autogen-assistant/autogenra/web/app.py", line 85, in add_message
    response_message: Message = chatmanager.chat(
                                ^^^^^^^^^^^^^^^^^

  File "/home/arne/src/autogen3/autogen/samples/apps/autogen-assistant/autogenra/autogenchat.py", line 24, in chat
    flow = AutoGenFlow(config=flow_config, history=history, work_dir=scratch_dir, asst_prompt=skills_suffix)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/arne/src/autogen3/autogen/samples/apps/autogen-assistant/autogenra/autogenflow.py", line 26, in __init__
    self.sender = self.load(config.sender)
                  ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/arne/src/autogen3/autogen/samples/apps/autogen-assistant/autogenra/autogenflow.py", line 116, in load
    agent = autogen.UserProxyAgent(**asdict(agent_spec.config))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/arne/src/autogen3/.venv/lib/python3.11/site-packages/autogen/agentchat/user_proxy_agent.py", line 72, in __init__
    super().__init__(

  File "/home/arne/src/autogen3/.venv/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 115, in __init__
    self.client = OpenAIWrapper(**self.llm_config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/arne/src/autogen3/.venv/lib/python3.11/site-packages/autogen/oai/client.py", line 77, in __init__
    self._clients = [self._client(config, openai_config) for config in config_list]  # could modify the config
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/arne/src/autogen3/.venv/lib/python3.11/site-packages/autogen/oai/client.py", line 77, in <listcomp>
    self._clients = [self._client(config, openai_config) for config in config_list]  # could modify the config
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/arne/src/autogen3/.venv/lib/python3.11/site-packages/autogen/oai/client.py", line 138, in _client
    client = OpenAI(**openai_config)
             ^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/arne/src/autogen3/.venv/lib/python3.11/site-packages/openai/_client.py", line 93, in __init__
    raise OpenAIError(

openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
`

**Comment by miiiz** [comment]
I get the same error with OpenAI api_key. No matter how I set get_default_agent_config(). 
I tried 
`llm_config = LLMConfig(
    config_list=[{
            "model": "gpt-4",
            "api_key": "<myKey>",
    }],
    temperature=0,
)
`
and also tried the old way I use in autogen
`config_list = [
    {
        'model': 'gpt-4',
        'api_key': "<myKey>",
    },
]
llm_config = {
    "cache_seed": 42,  
    "temperature": 0,
    "config_list": config_list,
}
`

**Comment by olivMertens** [comment]
Yeah i've the same issue, whatever i used, the message stay here the api_key is not passed to the original openai library

**Comment by codernew007** [comment]
I try code like this, and then run python test/twoagent.py success.
```
config_list = [ { 'model': 'gpt-3.5-turbo', 'api_key': "xx","base_url":"xxx","api_type":"azure","api_version": "2023-07-01-preview" }]
```

**Comment by ChunshengLin** [comment]
To fix this, try to change code at autogen-assistant/frontend/src/components/atoms.tsx. Add the following code, then cd autogen-assistant/frontend, use `yarn build` rebuild the frontend.

![image](https://github.com/microsoft/autogen/assets/45332194/ff843f25-b4da-44a7-bff1-4243d997646d)

![image](https://github.com/microsoft/autogen/assets/45332194/96551191-7b63-475b-b6ed-f0e8aaa7101a)

After that, when add mode, you need fill the Api Version, then save it.

![image](https://github.com/microsoft/autogen/assets/45332194/30b1d5bf-7f6d-41b9-a66e-8f9fb2b8f4ed)

Now you can use the Azure OpenAI.

**Comment by Li-Yanzhi** [comment]
When direct pip and run autogenra or autogenstudio from cmd, how to specify azure OpenAI config file?  and I tried to edit the model config (add key/base_url, model type and version etc) from autogenstudio Build page, it did not take effect too.  Maybe need to add a config parameter for this, e.g.  autogenstudio ui --config "config_file"

**Comment by victordibia** [comment]
Looking into it. Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dumbkid-tom** [comment]
my issue was `llm_config` was not passed to autogen.groupchatmanager function.  After the fix, no more api_key missing error.

BEFORE:
`    groupchat = autogen.GroupChat(agents=[user_proxy, assistant], messages=[], max_round=MAX_ITER)
    manager = autogen.GroupChatManager(groupchat=groupchat)`

AFTER:
`    groupchat = autogen.GroupChat(agents=[user_proxy, assistant], messages=[], max_round=MAX_ITER)
    manager = autogen.GroupChatManager(groupchat=groupchat, llm_config=llm_config)`

Here is my llm_config:

`config_list = [
    {
        "model": "gpt-35-turbo",  
        "api_key": os.environ.get("AZURE_OPENAI_API_KEY"),
        "base_url": os.environ.get("AZURE_OPENAI_API_BASE"),
        "api_type": "azure", 
        "api_version": "2023-07-01-preview", 
 }
]

llm_config={
    "timeout": 600,
    "cache_seed": 42,
    "config_list": config_list,
}`

**Comment by huangpan2507** [comment]
> When direct pip and run autogenra or autogenstudio from cmd, how to specify azure OpenAI config file? and I tried to edit the model config (add key/base_url, model type and version etc) from autogenstudio Build page, it did not take effect too. Maybe need to add a config parameter for this, e.g. autogenstudio ui --config "config_file"

I had the same doubt about using run autogenstudio ui from cmd

**Comment by victordibia** [comment]
HI @huangpan2507 ,

AutoGen studio is a UI interface on top of AutoGen. 
Currently, it is built such that the user specifies the agent workflow configuration in the UI (rather than a config file).
