### ISSUE TITLE
Call to openai should be async when in async context

### ISSUE THREAD

**Issue by jonathan-fraser-altium** [microsoft/autogen#760]
The current release adds support for async functions calls. However, the bottom call to openai is still sync. This basically precludes using this in any true async system as calls to the llm are the bottleneck. Openai does have an async client in its newer releases which we should utilize when the conversation or reply is initiated as async.

**Comment by JonathanFraser** [comment]
Couldn't find this when searching issues. However, there appears to be an open PR #543

**Comment by JonathanFraser** [comment]
On reading through the changes in that PR, it seems it doesn't not actually call openai in an async manner.

**Comment by sonichi** [comment]
Makes sense to me. #543 is stuck for 2 weeks. Do you think it's a good idea to merge that PR before making a new PR to address this issue?

**Comment by jonathan-fraser-altium** [comment]
Probably. #543 still puts the nessecary async hooks into the reply stack. Then we can make a second edit to how we handle OpenAIWrapper to expose the underlying async client when appropriate.

**Comment by sonichi** [comment]
Given that #543 is stale for 3 weeks, I don't recommend waiting for it.
@qingyun-wu what do you think?

**Comment by Tylersuard** [comment]
@sonichi I need autogen to be async too.  Is there anything I can do to help?

**Comment by sonichi** [comment]
There is no blocking PR now. @Tylersuard could you work with others interested in this feature together to enable async inference? @tyler-suard-parker @jonathan-fraser-altium could probably help reviewing.
I'll try to review it during my vacation from now to the new year.
