### ISSUE TITLE
How to connect to LLM ,not gpt4

### ISSUE THREAD

**Issue by liucheny** [microsoft/autogen#763]

**Comment by abc-africa** [comment]
Hello @liucheny  I have got it working by using a combination of ollama.ai and litellm.ai here are the steps

### Step 1: install ollama.ai by following the link [ollama install ](https://ollama.ai/download)
	curl https://ollama.ai/install.sh | sh
### Step 2: Run the selected LLM, i have choosen llama2
	ollama run llama2
### Step 3: Install litellm.ai by following the link[ litellm intall](https://docs.litellm.ai/docs/#basic-usage)
	pip install litellm
### Step 4: Run litellm by specifying the model served by ollama in Step 2 
	litellm --model ollama/llama2
### Step 5: Here is a sample code using the url output from Step 4
	import autogen
	config_list = [
		{
			"api_base": "http://127.0.0.1:8000",
			"api_key" : "NULL",
		}
	]
	llm_config = {
		"request_timeout" : 800,
		"config_list" : config_list
	}

	assistant = AssistantAgent(
	    "assistant",
	    llm_config = llm_config
	)

	user_proxy = UserProxyAgent(
	    "user_proxy",
	    code_execution_config = {
	        "work_dir" : "coding"
	    }
	)

	user_proxy.initiate_chat(
	    assistant,
	    message ="What is the name of the model you are based on?"
	)

### Happy AutoGenerating!🚀

**Comment by phalexo** [comment]
If I am running multiple models on different GPUs, should I assume I should have

config_list1 = [
	{
		"api_base": "http://127.0.0.1:8000",
		"api_key" : "NULL",
	}
]

config_list2 = [
	{
		"api_base": "http://127.0.0.1:8888",
		"api_key" : "NULL",
	}
]

assistant = AssistantAgent(
    "assistant",
    llm_config = { "request_timeout" : 800, "config_list" : config_list1 }
)

user_proxy = UserProxyAgent(
    "assistant",
    llm_config = { "request_timeout" : 800, "config_list" : config_list2 }
)

???

**Comment by phalexo** [comment]
Hm. "request_timeout" does not seem to be a valid key word.

**Comment by rickyloynd-microsoft** [comment]
Ah, `request_timeout` went away with `pyautogen==0.2.0` and `openai>=1.0.0`. You'll want to review the migration guide [here](https://microsoft.github.io/autogen/docs/Installation).

**Comment by phalexo** [comment]
> Ah, `request_timeout` went away with `pyautogen==0.2.0` and `openai>=1.0.0`. You'll want to review the migration guide [here](https://microsoft.github.io/autogen/docs/Installation).

Thanks.

It appears to me that AutoGen is set up to work synchronously, right? Only one agent can do something at a time?
I was hoping to get multiple agents to run at the same time, but it seems to swapping models in and out.

**Comment by rickyloynd-microsoft** [comment]
OpenAI added async functionality in their latest version of the api, and we've added corresponding support to autogen. See this [notebook](https://github.com/microsoft/autogen/blob/main/notebook/Async_human_input.ipynb).

**Comment by sonichi** [comment]
OpenAI Async support has not been added. See #760 . I've encouraged a PR. Please help with reviewing the PR if it happens. @phalexo 
cc @Tylersuard
