### ISSUE TITLE
Documentation and code not lining up.

### ISSUE THREAD

**Issue by iplayfast** [microsoft/autogen#764]
from https://microsoft.github.io/autogen/docs/Use-Cases/agent_chat
```
from autogen import AssistantAgent, UserProxyAgent

# create an AssistantAgent instance named "assistant"
assistant = AssistantAgent(name="assistant")

# create a UserProxyAgent instance named "user_proxy"
user_proxy = UserProxyAgent(name="user_proxy")
```

So installed autogen newish release. and rain the above code. This is the result

```

pip install autogen==1.0.14
Collecting autogen==1.0.14
  Using cached autogen-1.0.14-py3-none-any.whl (30 kB)
Requirement already satisfied: setuptools in /home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages (from autogen==1.0.14) (68.2.2)
Requirement already satisfied: docopt in /home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages (from autogen==1.0.14) (0.6.2)
Requirement already satisfied: PyYAML in /home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages (from autogen==1.0.14) (6.0.1)
Requirement already satisfied: autopep8 in /home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages (from autogen==1.0.14) (2.0.4)
Requirement already satisfied: pycodestyle>=2.10.0 in /home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages (from autopep8->autogen==1.0.14) (2.11.1)
Installing collected packages: autogen
  Attempting uninstall: autogen
    Found existing installation: autogen 1.0.1
    Uninstalling autogen-1.0.1:
      Successfully uninstalled autogen-1.0.1
Successfully installed autogen-1.0.14
```
starting python
```
(autogen) chris@FORGE:~/ai/aiprojects/ollama/autogen$ python
Python 3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:57:19) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

first line from docs fails

```
>>> from autogen import AssistantAgent, UserProxyAgent
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'AssistantAgent' from 'autogen' (/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/autogen/__init__.py)
>>> 
>>> # create an AssistantAgent instance named "assistant"
>>> assistant = AssistantAgent(name="assistant")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'AssistantAgent' is not defined
>>> 
>>> # create a UserProxyAgent instance named "user_proxy"
>>> user_proxy = UserProxyAgent(name="user_proxy")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'UserProxyAgent' is not defined
>>> 
```

**Comment by sonichi** [comment]
Please install `pyautogen` instead of `autogen`.

**Comment by iplayfast** [comment]
same result

**Comment by sonichi** [comment]
`pyautogen` and `autogen` are two different packages. Please use `pyautogen` which is the right one for this project.

**Comment by iplayfast** [comment]
Thanks. That got me further. Seems like the whole system is slow, and code generated from llm is showing in litellm but not actually making its way to disk.  Documented in more detail https://github.com/jmorganca/ollama/issues/1277

**Comment by FlutterPaw** [comment]
@sonichi I have autogen uninstalled and pyautogen reinstalled. I tried to construct the agent in the autogen  notebook called: Automated Task Solving with Coding & Planning Agents

using the given code: 

planner = autogen.AssistantAgent(
    name="planner",
    llm_config={"config_list": config_list},
    # the default system message of the AssistantAgent is overwritten here
    system_message="You are a helpful AI assistant. You suggest coding and reasoning steps for another AI assistant to accomplish a task. Do not suggest concrete code. For any action beyond writing code or reasoning, convert it to a step that can be implemented by writing code. For example, browsing the web can be implemented by writing code that reads and prints the content of a web page. Finally, inspect the execution result. If the plan is not good, suggest a better plan. If the execution is wrong, analyze the error and suggest a fix."
)
planner_user = autogen.UserProxyAgent(
    name="planner_user",
    max_consecutive_auto_reply=0,  # terminate without auto-reply
    human_input_mode="NEVER",
)

def ask_planner(message):
    planner_user.initiate_chat(planner, message=message)
    # return the last message received from the planner
    return planner_user.last_message()["content"]
    
    But this error occurs: 
    
    NameError                                 Traceback (most recent call last)
[<ipython-input-6-28ae22134eb6>](https://localhost:8080/#) in <cell line: 1>()
----> 1 planner = autogen.AssistantAgent(
      2     name="planner",
      3     llm_config={"config_list": config_list},
      4     # the default system message of the AssistantAgent is overwritten here
      5     system_message="You are a helpful AI assistant. You suggest coding and reasoning steps for another AI assistant to accomplish a task. Do not suggest concrete code. For any action beyond writing code or reasoning, convert it to a step that can be implemented by writing code. For example, browsing the web can be implemented by writing code that reads and prints the content of a web page. Finally, inspect the execution result. If the plan is not good, suggest a better plan. If the execution is wrong, analyze the error and suggest a fix."

NameError: name 'autogen' is not defined

--

Do you know why this error is taking place?

**Comment by sonichi** [comment]
did you "import autogen"?

**Comment by FlutterPaw** [comment]
@sonichi yes I imported autogen and the error occurs, so I uninstalled it and then installed pyautogen, when I have either or both of these installed the same error occurs. I am using Google Colab
