### ISSUE TITLE
TypeError in groupchat.py - mentioned_agents() function in 0.2.0

### ISSUE THREAD

**Issue by ZionTilley** [microsoft/autogen#765]
After updating updating the pyautogen module last night (I didn't know at the time a release had occurred just 6 hours prior) I ran the same code that had been working and I began encountering this message shortly after calling `user_proxy.initiate_chat(manager,...)`

**Error:**
**TypeError: can only concatenate str (not "ChatCompletionMessage") to str`**

```
File "C:\Users\ziont\anaconda3\envs\zenv\Lib\site-packages\autogen\agentchat\groupchat.py", line 211, in _mentioned_agents
    count = len(re.findall(regex, " " + message_content + " "))  # Pad the message to help with matching
                                  ~~~~^~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "ChatCompletionMessage") to str
```

The error occurs in the newly added "**mentioned_agents**" function beginning on line 200 in groupchat.py:

```
def _mentioned_agents(self, message_content: str, agents: List[Agent]) -> Dict:
        """
        Finds and counts agent mentions in the string message_content, taking word boundaries into account.
        Returns: A dictionary mapping agent names to mention counts (to be included, at least one mention must occur)
        """
        mentions = dict()
        for agent in agents:
            regex = (
                r"(?<=\W)" + re.escape(agent.name) + r"(?=\W)"
            )  # Finds agent mentions, taking word boundaries into account
            count = len(re.findall(regex, " " + message_content + " "))  # Pad the message to help with matching
            if count > 0:
                mentions[agent.name] = count
        return mentions
```
        
I presume the line of text in my 'message' in the initate_chat call is this:
        "...
        1) Have an android_test_engineer generate unit tests for the following file by sending the contents of the file to the 'AndroidTestEngineer' agent:..."
        
I suspect that is causing the issue because it specifically calls out one of my declared agents involved in the group chat.

**Comment by afourney** [comment]
It seems that at some point the message content became ChatCompletionMessage rather than a string. What models are you using, and are you using the GPTAssistants?

**Comment by hardchor** [comment]
Hi! Encountering the same issue. I doubt it's down to the config, but using `gpt-4-1106-preview`

**Comment by afourney** [comment]
Sorry for the bug. The problem, I'm sure, is that "extract_text_or_function_call" in oai/client.py is returning a completion object rather than a str. This shouldn't happen, because the GroupChat LLM call is very specific. It's not using functions. It's not multimodal, etc.

The 1106 preview seems also to be a common element. I'll see if I can replicate it quickly, and if not, then I'll submit a quick fix for mitigation (so at least it won't crash, but would behave as any other speaker selection failure)

**Comment by afourney** [comment]
Yeah, this is the way to go if installing from pip, until we publish a new release. The PR I mentioned should fix things if running from source however. The fact that it broke between 0.2.0b6 and 0.2.0 is a good hint for tracking this down.

**Comment by drosini-ibm** [comment]
I am running into the same issue as well. I am using `gpt-4-32k` 

Do we know if there was a solve yet for this bug ?

**Comment by sonichi** [comment]
It seems to be caused by a breaking change from openai (from 1.2 to 1.3). #791 is trying to fix it.
