### ISSUE TITLE
GroupChat: selecting agents by default with gpt4 and not working for large context windows 

### ISSUE THREAD

**Issue by dfs99** [microsoft/autogen#766]
I'm using large context windows for my agents but when orchestrating these agents inside a GroupChat, the following error rises:

![error1](https://github.com/microsoft/autogen/assets/37598654/bba8bfad-d133-4913-b336-6fb37da6293b)

Even though I'm specifying the model: `gpt-4-1106-preview` for all agents through the func `config_list_from_json()` the following error is raising  because by default, when trying to pick up an agent, the model is: gpt4. 

I think that it's a bug and my thoughts are that the bug is located inside `select_speaker` function  when calling function `generate_oai_reply` since no config is passed as arg.

![image](https://github.com/microsoft/autogen/assets/37598654/0cbeb56a-fc55-47ab-b289-fe759adfa201)

Here is part of my code: 
```
admin = autogen.UserProxyAgent(
    name = "Admin",
    system_message=admin_sys, 
    code_execution_config=False
)

# more agent go here...

# create the group chat.
group_chat = autogen.GroupChat(
    agents=[admin, B,_agent C_agent],
    messages=[],
    max_round=3
)

manager = autogen.GroupChatManager(
    groupchat=group_chat,
    llm_config=conf_list_4turbo 
)

# run chat.
admin.initiate_chat(
    manager,
    message = "some msg"
)

```

**Comment by sonichi** [comment]
Have you tried to print the `conf_list_4turbo` to verify the content of it?

**Comment by dfs99** [comment]
Sure! Here you have the output:

```
[{'model': 'gpt-4-1106-preview', 'api_key': 'my-secret-key', 'api_type': 'open_ai'}]
```

And that's how I call the function.  Note that in the json file I have defined the model and so on:
```python
conf_list_4turbo = autogen.config_list_from_json(
    "OAI_CONFIG_LIST.json",
    filter_dict={
        "model": ["gpt-4-1106-preview"]
    }
)
```

Here is the json data:

```json
[
    {
        "model": "gpt-4-1106-preview",
        "api_key": "my-secret-key",
        "api_type": "open_ai"
    }
]
```

**Comment by miiiz** [comment]
I have the same problem. Using same llm_config gpt-4-1106-preview, Agents in the groupchat are right but groupchat manager uses gpt-4.

**Comment by sonichi** [comment]
The groupchat manager also has a `llm_config` to be configured. If it's omitted, the default model is gpt-4.

**Comment by dfs99** [comment]
To shed light on the problem, in the example I provided the groupchat manager does have the llm_config set up. Here you have the piece of code posted above. 

```python
# agent instances here...

# create the group chat.
group_chat = autogen.GroupChat(
    agents=[admin, B_agent C_agent],
    messages=[],
    max_round=3
)

manager = autogen.GroupChatManager(
    groupchat=group_chat,
    # groupchat manager setup with gpt-4-1106-preview
    llm_config=conf_list_4turbo 
)
```
