### ISSUE TITLE
Extending Graph Group Chat - Prioritise choosing an executor from eligible_speakers when the previous_speaker produced code

### ISSUE THREAD

**Issue by joshkyh** [microsoft/autogen#778]
During the review of #753, @JieyuZ2 suggested prioritising choosing an executor from `eligible_speakers` when the previous_speaker produced code in `GraphGroupChat`.

<img width="765" alt="image" src="https://github.com/microsoft/autogen/assets/14764966/33eae6c3-998f-482d-8a84-559d4d14fd2b">

Couple of considerations:
1. Limit the code language detection to Python for this iteration. Do we have a Python code detector currently?
2. Do not pick a random executor if there are at least two eligible executors, and ask the LLM instead.
3. Allow the `Agent` class, along with its attributes like able to execute code to be passed into the NetworkX `Graph` class instead of strings.

Please feel free to add considerations if anyone can think of any.

**Comment by JieyuZ2** [comment]
re code detector: https://github.com/microsoft/autogen/blob/main/autogen/agentchat/conversable_agent.py#L664

**Comment by JieyuZ2** [comment]
And to do this, we better follow the trigger-match mechanism in conversableagent https://github.com/microsoft/autogen/blob/main/autogen/agentchat/conversable_agent.py#L954

There we trigger a reply func if the condition is satisfied, and reply funcs are checked in order
Here we mark an agent as eligible once the condition is satisfied.

**Comment by joshkyh** [comment]
Maybe we don't want to prioritise executors if the previous message contains code.
<img width="1496" alt="image" src="https://github.com/microsoft/autogen/assets/14764966/ab832867-b70c-4281-80c3-4a8a39d7209e">

**Comment by ragyabraham** [comment]
yeah, the way I see it is that at present, Autogen is very much geared towards performing tasks with code, which is why this bias exists of "if there's code, then execute code". However, if Autogen is to extend its utility beyond that to become a generalised LLM framework, the user should be able to dictate "code behaviour". 

If I want to chat with an agent or group of agents and I do not want any code to be executed but rather purely from an education/knowledge perspective, I should, in theory, have the ability to do that.

**Comment by ragyabraham** [comment]
Perhaps there should be a flag somewhere where a user can set their code preference. 
As in "What should we do when we see code." And that could be:

- Nothing 
- Execute
- write to file
- etc.

**Comment by JieyuZ2** [comment]
> Maybe we don't want to prioritise executors if the previous message contains code. <img alt="image" width="1496" src="https://private-user-images.githubusercontent.com/14764966/287910305-ab832867-b70c-4281-80c3-4a8a39d7209e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NDgyODMsIm5iZiI6MTcwMTc0Nzk4MywicGF0aCI6Ii8xNDc2NDk2Ni8yODc5MTAzMDUtYWI4MzI4NjctYjcwYy00MjgxLTgwYzMtNGE4YTM5ZDcyMDllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDAzNDYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3MWYxNzZhOWNjOWE3NGU4NTBhYTgwMGJjM2YzZTM3NDI0ODAwY2Y0YTQ1YTlmMzI5NzgzMmI0OGNjNjE3NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K6YZ1hd-irqN97YHqSBh6hcWNZrQEs8Fh2AG67tg8-Y">

yes i agree. In that case, we don't have to put an executor in the group chat at the beginning. And the trigger-match mechanism does not mean to always prioritise choosing an executor when there is code, but rather a choice of users: the user can bind a "code trigger" with the executor, then the executor will become eligible when there is code ("code trigger" is matched)

**Comment by JieyuZ2** [comment]
> Perhaps there should be a flag somewhere where a user can set their code preference. As in "What should we do when we see code." And that could be:
> 
> * Nothing
> * Execute
> * write to file
> * etc.

yes, in this case, the user can:

- do nothing
- bind the "code trigger" with an executor so it extracts and execute the code
- bind the "code trigger" with an file writer so it extracts and cp the code to a file

**Comment by ragyabraham** [comment]
For reference, this is what is currently happening.

![Screenshot 2023-12-05 at 2 57 21 pm](https://github.com/microsoft/autogen/assets/52903382/e016ce90-8b29-4ed9-b231-45a1453156ce)

**Comment by joshkyh** [comment]
> For reference, this is what is currently happening.
> 
> ![Screenshot 2023-12-05 at 2 57 21 pm](https://private-user-images.githubusercontent.com/52903382/287912859-e016ce90-8b29-4ed9-b231-45a1453156ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NDkzNzksIm5iZiI6MTcwMTc0OTA3OSwicGF0aCI6Ii81MjkwMzM4Mi8yODc5MTI4NTktZTAxNmNlOTAtOGIyOS00ZWQ5LWIyMzEtNDVhMTQ1MzE1NmNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA0MDQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3YTdjODUxZjI1MTNiZTA1NzE1ZTU5NmE1OTRjNWY1ZThlZjA2Nzg3NGUzYjM3ZTIwMDgzNmZjMDZlMTgzOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4a3zoJbhHXT1_xEgMx9ND5waS_BAd98415yh_5dl4GU)

Yeah, interesting the user is trying to learn Rust without wanting to run code. I guess for now, we have to remove the executor abilities for the User Proxy agent in your use-case @ragyabraham.
