### ISSUE TITLE
Function calls dont work with Azure OpenAI currently due to differences between OpenAI API, and AzureOpenAI

### ISSUE THREAD

**Issue by OwenVanV** [microsoft/autogen#78]
I am one of the AI Global Black Belts and have been working with AutoGPT to build some applications in the last few days. I noticed a pretty impactful bug. I have only noticed this using AzureOpenAI, but custom functions are not working. When the API returns the function call spec {"function_call"}, it triggers issues with the AutoGen create completion, as it cannot find a "Content" for the message. I tested verbatim with your demo, as well as my custom code, and the issue persists. Hopefully this is helpful! Thanks!

**Comment by sonichi** [comment]
Thanks. Probably the same issue with #75

**Comment by kevin666aa** [comment]
@OwenVanV We just fixed this problem. Can you test it to see if the error persists?

**Comment by kevin666aa** [comment]
We believe this issue is solved and are closing it. Thank you for pointing it out!
