### ISSUE TITLE
Error: Function {function name} not found (GPT4-Turbo 1106-Preview)

### ISSUE THREAD

**Issue by tyler-suard-parker** [microsoft/autogen#783]
Hello.  I am having a problem with running AutoGen using GPT-4 Turbo (1106-Preview) for my backend.  It will often, but not always, say that it can't find the functions I defined earlier in my script.  For example, I have 3 functions, it will call the first one successfully, and then say it cannot locate the next 2.  I changed absolutely nothing about my script except for the backend I was using, from GPT-4-32k to GPT-4 1106-Preview

**Comment by tyler-suard-parker** [comment]
Edit: this is now happening on GPT-4-32k as well.  Not sure what is going on here.

**Comment by rickyloynd-microsoft** [comment]
Does GPT-4-32k always fail? Or does it work sometimes?

**Comment by victordibia** [comment]
@tyler-suard-parker ,

Can you kindly share sample code on how you are defining your functions and the exact error messages?
That would be useful in replicating/debugging/providing help.

**Comment by victordibia** [comment]
@tyler-suard-parker  .. any updates on this? Still seeing this issue?

**Comment by tyler-suard-parker** [comment]
@victordibia Hello Dr. Dibia!  I follow you on Linkedin.  For some reason the problem has disappeared.  I think it might have had something to do with context length.

**Comment by victordibia** [comment]
Thanks for following up.
It probably was some random outage with the OAI service. 
I usually check their status page here whenever I see errors. 
https://status.openai.com/ 

Closing this out.
