### ISSUE TITLE
Confused about RetrieveChat Example 1: Generating and running code

### ISSUE THREAD

**Issue by austinmw** [microsoft/autogen#788]
Hi, I'm a bit confused about the notebook demo output from Example 1 here:
https://github.com/microsoft/autogen/blob/main/notebook/agentchat_RetrieveChat.ipynb

Has this actually successfully run the code it generated? I don't see any indication of that in the output, but maybe the output of running the code is not displayed?

**Comment by julianakiseleva** [comment]
@thinkall can please us here

**Comment by thinkall** [comment]
Hi @austinmw , in this notebook, we set `code_execution_config=False` to skip the code execution because code execution may fail and `Run All` would not work. You can config `code_execution_config={}` to enable code execution or just unset `code_execution_config`.

**Comment by julianakiseleva** [comment]
thanks @thinkall! @austinmw did it help? Can we close the issue?
