### ISSUE TITLE
AzureML Compute Instance Error: OperationalError: database is locked

### ISSUE THREAD

**Issue by jakeatmsft** [microsoft/autogen#79]
When running agents on AzureML Compute Instance, sqlite db is throwing error.  Seems this is a known issue with sqllite3 db on vm, work around is to move db to a different location, please provide that capability is necessary.

File /anaconda/envs/autogen/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py:521, in ConversableAgent.initiate_chat(self, recipient, clear_history, silent, **context)
    507 """Initiate a chat with the recipient agent.
    508 
    509 Reset the consecutive auto reply counter.
   (...)
    518         "message" needs to be provided if the `generate_init_message` method is not overridden.
    519 """
    520 self._prepare_chat(recipient, clear_history)
--> 521 self.send(self.generate_init_message(**context), recipient, silent=silent)

File /anaconda/envs/autogen/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py:324, in ConversableAgent.send(self, message, recipient, request_reply, silent)
    322 valid = self._append_oai_message(message, "assistant", recipient)
    323 if valid:
--> 324     recipient.receive(message, self, request_reply, silent)
    325 else:
    326     raise ValueError(
...
-> 2438         sql('PRAGMA %s = %s' % (pragma, value)).fetchall()
   2439     break
   2440 except sqlite3.OperationalError as exc:

OperationalError: database is locked

**Comment by sonichi** [comment]
Is it because of the diskcache? Do you have the full trace?

**Comment by pcdeadeasy** [comment]
Could @jakeatmsft I get some more information about the notebook or code you were running? It will be good to repro the scenario before providing a solution.

**Comment by jakeatmsft** [comment]
I was able to fix the issue by cloning code into the localfiles folder and running there, it looks like it is related to running sqlite in cloudfiles (azure fileshare).  We can close as this is a suitable workaround.

**Comment by jakeatmsft** [comment]
Disabling cache works as well: #801

**Comment by R1j1t** [comment]
@jakeatmsft your comment on using localfiles folder worked like a charm. I wish the error message was more descriptive.
