### ISSUE TITLE
autogen-assistant Chatbox unresponsive 

### ISSUE THREAD

**Issue by abc-africa** [microsoft/autogen#793]
It keep saying "loading messages"
![Screenshot from 2023-11-28 10-42-46](https://github.com/microsoft/autogen/assets/105781261/15a2159b-3db6-4620-93a7-1a6b34e0fe39)

**Comment by victordibia** [comment]
Hi @abc-africa ,

It looks like you are on the latest `autogenra` dev branch.  Pulling the latest version of the branch should address the `loading` issue above.
I'd suggest `pip install autogenra` for a more stable version.

**Comment by victordibia** [comment]
@abc-africa , thanks again for noting these issues. Were you able to make progress?
