### ISSUE TITLE
llm_config  instructions

### ISSUE THREAD

**Issue by waynecanfly** [microsoft/autogen#797]
I was hoping for a clear explanation of llm_config but only found llm_config (dict or False): llm inference configuration.
                 Please refer to [OpenAIWrapper.create](/docs/reference/oai/client#create)
                 for available options., please help me find this instruction

**Comment by rickyloynd-microsoft** [comment]
Closely related to #749

**Comment by victordibia** [comment]
Also see this notebook on multiple ways to setup the llm config.

https://github.com/microsoft/autogen/blob/main/notebook/oai_openai_utils.ipynb

**Comment by waynecanfly** [comment]
> Closely related to #749

it's useful to me.thank you~

**Comment by sonichi** [comment]
> [olivMertens](/olivMertens)

Good suggestion. Would you like to make a PR?
