### ISSUE TITLE
Unable to succesfully run the Autogen Testbed Environment 

### ISSUE THREAD

**Issue by antoan** [microsoft/autogen#800]
Autogen 0.2.0b5
python: 3.8.10

I followed the Autogen Testbed Environment readme and configured my config list as a json string.

Attempted to run some scenarios with:
`python run_scenarios.py --repeat 1`

Unfortunately, every scenario that is run throws the same error: `
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable`
[results.zip](https://github.com/microsoft/autogen/files/13493693/results.zip)

Any thoughts would be much appreciated.

**Comment by rickyloynd-microsoft** [comment]
The problem seems to be with your api_key. Also, it would be best to use the latest stable version of autogen (0.2.0), which you can get with `pip install pyautogen`.

**Comment by afourney** [comment]
Typically, that error would indicate either that the API key is missing from the OAI_CONFIG_LIST, or that an agent's llm_config is not set (though this should be set in any of the provided templates).

**Comment by julianakiseleva** [comment]
Hi @antoan!

please make sure your OAI_CONFIG_LIST is set up properly.

**Comment by antoan** [comment]
Hi @julianakiseleva @rickyloynd-microsoft @afourney 

Thank you for your suggestions. 

I have looked at my OAI_CONFIG_LIST, and I checked that the model and api keys are retrieved correctly, by inspecting the `config_list `argument, of the `run_scenarios` function in run_scenarios.py, as seen in the image below. (api key since deleted)

As the error originates from api calls made inside the docker container, I decided to do a native run (
without docker), in which case I was able get past this issue.

**Comment by afourney** [comment]
@antoan That's a very strong clue. I am not thrilled with how secret sharing is done with Docker, and that's probably what is broken in your case. I'd love to know why.

In any case, the way things work is that the testbed creates the folder, populates it, and appends the key to an ENV file within the created folder. When Docker runs, it sources this ENV file to set the environment variables. Something must be going on there....

In any case, there are two big PRs related to the tested coming (#792 and #810). While I don't believe any of this behavior will have changed, they are pretty big re-writes.. so it is possible.

**Comment by antoan** [comment]
@afourney thank you letting me know, I can manage without docker for now.

I was wondering if there are any plans to make the testbed available in the pyautogen pip package so it can be used with user projects?

**Comment by afourney** [comment]
@antoan I like that idea either as an option (like the RAG support), or as a separate package (like the Autogen Assistant). I think I'd need to do a little refactoring (e.g., to make the script less dependent on the surrounding directory structure), but I like the idea.
