### ISSUE TITLE
TypeError: Completions.create() got an unexpected keyword argument 'cache_seed'

### ISSUE THREAD

**Issue by pranavvr-lumiq** [microsoft/autogen#808]
I am getting the following error.

TypeError: Completions.create() got an unexpected keyword argument 'cache_seed'

I am trying to recreate the notebook from the following link:

https://github.com/microsoft/autogen/blob/main/notebook/agentchat_auto_feedback_from_code_execution.ipynb

**Comment by pranavvr-lumiq** [comment]
I made some changes to the config list that look like this:

api_keys = ["my_api_key"]
base_urls = None  
# api_type = "openai"  
api_version = ["gpt-3.5-turbo", "gpt-3.5-turbo-16k"] 

config_list = autogen.get_config_list(
    api_keys,
    base_urls=base_urls,
    # api_type=api_type,
    api_version=api_version
)

**Comment by victordibia** [comment]
unexpected keyword argument 'cache_seed' ..
Suggests you may be on an older version of pyautogen. Can you do the following

- print your pyautogen version. It should be >=0.2.0 
- show your llm_config for the agent. 


Ref

- MIgration guide : https://microsoft.github.io/autogen/docs/Installation/#migration-guide-to-v02

**Comment by AndrewHogenson** [comment]
Pre 1.+ versions of openai (eg 0.28.0) do not recognize "cache_seed" it seems.  I had the same issue but also have had  other issues with the newest (1.+) openai versions. I reviewed the openai files for 0.28 and found it uses 'seed' instead of 'cache_seed', and just changed references in my code to 'seed'. Problem solved.

**Comment by pranavvr-lumiq** [comment]
> > unexpected keyword argument 'cache_seed' ..
> 
> This error suggests you may be on an older version of pyautogen. Can you do the following
> 
> * print your pyautogen version. It should be >=0.2.0
> * show your llm_config for the agent.
> 
> ## Reference
> * MIgration guide : https://microsoft.github.io/autogen/docs/Installation/#migration-guide-to-v02

here is my llm config for the agent:

assistant = autogen.AssistantAgent(
    name="assistant",
    llm_config={
        "cache_seed": 42,  # seed for caching and reproducibility
        "config_list": config_list,  # a list of OpenAI API configurations
        "temperature": 0,  # temperature for sampling
    },  # configuration for autogen's enhanced inference API which is compatible with OpenAI API
)

pyautogen version: 
print(autogen.__version__)
0.2.0b2

**Comment by pranavvr-lumiq** [comment]
> Pre 1.+ versions of openai (eg 0.28.0) do not recognize "cache_seed" it seems. I had the same issue but also have had other issues with the newest (1.+) openai versions. I reviewed the openai files for 0.28 and found it uses 'seed' instead of 'cache_seed', and just changed references in my code to 'seed'. Problem solved.

That seemed to do the trick. Thanks.
