### ISSUE TITLE
model configuration is not working

### ISSUE THREAD

**Issue by ruifengma** [microsoft/autogen#816]
Here is the way that I do model configuretion
```
def get_default_agent_config(work_dir: str, skills_suffix: str = "") -> FlowConfig:
    """
    Get a default agent flow config .
    """
    config_list=[
        {   "model": "Mistral-7B-Instruct-v0.1", 
        "base_url": "http://10.86.13.180:8090/v1", 
        "api_key": "null"},
        {   "model": "chatglm3-6b", 
        "base_url": "http://10.86.13.180:8090/v1",
        "api_key": "null"}]

    llm_config = LLMConfig(
        config_list=config_list,
        temperature=0,
    )
```
The question is, after I set this on utills.py and I start autogenra, nothing changed and I stil need to type in the model and its url to use it normally.

**Comment by victordibia** [comment]
Hi @ruifengma,

Thanks for noting this.  

If you are working directly with the source code, you'll notice that there is some [conditional logic ](https://github.com/microsoft/autogen/blob/autogenra/samples/apps/autogen-assistant/autogenra/autogenchat.py#L20)where `get_default_agent_config ` is only used if no agent flow configuration is sent from the frontend. That is why the details in the front end always get set.  

To ensure your default config is used,you can change to

```python
if flow_config is None:
            flow_config = get_default_agent_config(scratch_dir, skills_suffix=skills_suffix)
```

to 

```
flow_config = get_default_agent_config(scratch_dir, skills_suffix=skills_suffix)
```

There are some updates to the autogen assistant in this [dev branch](https://github.com/microsoft/autogen/tree/autogenra) that should allow you directly specify your agents in the UI.

**Comment by ruifengma** [comment]
Hi @victordibia,  the update is performed already or I still need to modify the source code my self?

**Comment by victordibia** [comment]
Hi @ruifengma, 

The main app behavior has not changed as it is expected to be used with the frontend.
Please modify your local version. I am happy to help if you still have any issues
