### ISSUE TITLE
NotFoundError: Error code: 404 - {'error': {'code': 'DeploymentNotFound', 'message': 'The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.'}}

### ISSUE THREAD

**Issue by pranavvr-lumiq** [microsoft/autogen#822]
I am getting the following error:

NotFoundError: Error code: 404 - {'error': {'code': 'DeploymentNotFound', 'message': 'The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.'}}

trying to recreate this notebook locally:
https://github.com/microsoft/autogen/blob/main/notebook/agentchat_auto_feedback_from_code_execution.ipynb

**Comment by pranavvr-lumiq** [comment]
> @pranavvr-lumiq it's looks to me as a problem with your endpoint for OpenAI api.
> 
> you can see more here: https://learn.microsoft.com/en-us/answers/questions/1308161/the-api-deployment-for-this-resource-does-not-exis
> 
> Can you please check if you configuration file is setup properly? Have you just started and it's your first try? Or have you used autogen successfully, and it's start happening suddenly?

Thanks for the quick reply @julianakiseleva. This is not my first time using autogen. i was using it succesfully with a conventional openai API key, until my company temporarily shut them down. Right now i am trying to use an azure openai key, and this issue started. I do believe the config json file is set up correctly. I followed the instructions closely.

**Comment by tengda89757** [comment]
I also encountered with the same problem. Sad :-(

**Comment by olivMertens** [comment]
Yeah same thing here

**Comment by sonichi** [comment]
Could you share an example of the config that failed?

**Comment by pranavvr-lumiq** [comment]
> Could you share an example of the config that failed?

Sure. here it is:

{
		"model": "gpt-4",
		"base_url": "https://my_link.openai.azure.com/",
		"api_type": "azure",
		"api_version": "2023-07-01-preview",
		"api_key": "my_apa_key"
}

**Comment by winstxnhdw** [comment]
The Azure API endpoint requires a `deployment_name` parameter which `autogen` does not expose..

**Comment by pranavvr-lumiq** [comment]
Finally figured it out. The deployment name my coworker gave me was incomplete. Filled in the full deployment name in the model section and it worked.

**Comment by gregrobison** [comment]
What is the proper format for Azure OpenAI deployment name that works in autogen?

**Comment by rickyloynd-microsoft** [comment]
Normally the "model" key should have your model deployment name as its value.

**Comment by mrmechazilla** [comment]
In spring AI, the application.properties should look like this:

spring.ai.azure.openai.api-key=<api-key>
spring.ai.azure.openai.endpoint=<endpoint>
spring.ai.azure.openai.model=<model-name>
spring.ai.azure.openai.api-version=<api-version>

this will solve the problem
