### ISSUE TITLE
"Error: You did not pass an authentication token" with notebook/agentchat_lmm_llava.ipynb

### ISSUE THREAD

**Issue by leonpalm** [microsoft/autogen#827]
Hi,
I always get this replicate_token authentication error when running the notebook, tried both setting environment variable and just putting the token on the notebook,  the replicate account with credit card info has been set already, what's wrong?
I appreciate your soon help!
![截屏2023-12-01 13 33 31](https://github.com/microsoft/autogen/assets/55522398/ce1c3ad9-06e6-481a-94ac-b96a8cdf68ba)
![截屏2023-12-01 13 43 11](https://github.com/microsoft/autogen/assets/55522398/f3537486-7f0e-42e7-9a4f-5b67b42776b3)

**Comment by BeibinLi** [comment]
Let's figure out what the "authentication" is for. 

Can you try to create a new file and run the replicate tutorial first? https://replicate.com/docs/get-started/python

If you still get the same error, it should be the Replicate issue.

**Comment by EteimZ** [comment]
@BeibinLi I encountered this issue while going through **agentchat_lmm_llava** example. When I got the error I tried using replicate sdk directly but still got the error. After I restarted my notebook the error wasn't present in both AutoGen and replicate.

**Comment by BeibinLi** [comment]
@EteimZ  I believe in your case, you added the replicate API key into the environment variable? If that is the case, you would need to restart the terminal or "source ~/.bashrc" to update environment variable.

**Comment by EteimZ** [comment]
> @EteimZ I believe in your case, you added the replicate API key into the environment variable? If that is the case, you would need to restart the terminal or "source ~/.bashrc" to update environment variable.

Okay thanks @BeibinLi

**Comment by thinkall** [comment]
Hi @leonpalm ,  is your issue resolved? If yes, could you please close this issue? Thanks.

**Comment by ethanelasky** [comment]
This is still broken  -- I tried restarting the terminal and adding `source ~/.bashrc` and it didn't work.
