### ISSUE TITLE
Attempting RAG with .csv files.

### ISSUE THREAD

**Issue by pranavvr-lumiq** [microsoft/autogen#829]
I am trying to modify the following bit of code to read through a set of .csv files and generate an output.

boss_aid = RetrieveUserProxyAgent(
    name="Boss_Assistant",
    is_termination_msg=termination_msg,
    system_message="Assistant who has extra content retrieval power for solving difficult problems.",
    human_input_mode="NEVER",
    max_consecutive_auto_reply=3,
    retrieve_config={
        "task": "code",
        "docs_path": "https://raw.githubusercontent.com/microsoft/FLAML/main/website/docs/Examples/Integrate%20-%20Spark.md",
        "chunk_token_size": 1000,
        "model": config_list[0]["model"],
        "client": chromadb.PersistentClient(path="/tmp/chromadb"),
        "collection_name": "groupchat",
        "get_or_create": True,
    },
    code_execution_config=False,  # we don't want to execute code in this case.

**Comment by joshkyh** [comment]
```
max_tokens is too small to fit a single line of text. Breaking this line:
_id,workItemID ...
Failed to split docs with must_break_at_empty_line being True, set to False.
max_tokens is too small to fit a single line of text. Breaking this line:
POL_ID,AUREOUS_RISK_SCORE1,AUREOUS_RISK_BAND1,AUREOUS_RISK_SCORE2,AUREOUS_RISK_BAND2,AUREOUS_RISK_SC ...
```

Looks like the program is trying to create an embedding for structured data.

SQL database might be a more natural fit for the structured csv data, relative to RAG's vector DB. I'm not sure if you have seen https://github.com/microsoft/autogen/blob/main/notebook/agentchat_langchain.ipynb, it might be helpful.

**Comment by pranavvr-lumiq** [comment]
Also getting the following error:
TypeError: stat: path should be string, bytes, os.PathLike or integer, not list

**Comment by whoami02** [comment]
> Also getting the following error: TypeError: stat: path should be string, bytes, os.PathLike or integer, not list

your .csv files are given as a list. Either iterate over the list or just provide the file name directly

**Comment by thinkall** [comment]
Close as no further feedbacks from the issues's original author.
