### ISSUE TITLE
Integrating Python REPL Tool

### ISSUE THREAD

**Issue by krishnashed** [microsoft/autogen#840]
How to integrate Python REPL tool with one of the agents in Autogen ?

**Comment by rickyloynd-microsoft** [comment]
@krishnashed  I see that python REPL was discussed in our [discord channel](https://discord.com/channels/1153072414184452236/1179803969095221318). Does that answer your question?

**Comment by krishnashed** [comment]
Thanks it resolves my issue!

**Comment by sonichi** [comment]
@ekzhu fyi

**Comment by ekzhu** [comment]
@krishnashed what's your discord username I can add you to a `code-execution-user` role so you will be notified for updates on this. We are working on new code executor capabilities. For example, a stateful IPython executor is going to be part of the next release. If you want to contribute to this effort please comment under #1421

**Comment by ekzhu** [comment]
Added you to code-execution-user
