### ISSUE TITLE
AttributeError: 'ChatCompletion' object has no attribute 'cost' for OpenAIWrapper when using AzuerOpenaAI

### ISSUE THREAD

**Issue by bhishanpdl** [microsoft/autogen#883]
Reference:
- https://github.com/microsoft/autogen/blob/main/notebook/oai_client_cost.ipynb

I am trying to use autogen to get the cost estimate as described in above notebook.
However, I got the error:

```
AttributeError: 'ChatCompletion' object has no attribute 'cost'
```

# Info
- Windows 10 computer, python 3.11
- autogen : 0.2.0

# MWE
```python
import autogen
import os

config_list = autogen.config_list_from_json(
    env_or_file=os.path.expanduser('~/.config/autogen_config_list.json')
)

from autogen import OpenAIWrapper

client = OpenAIWrapper(config_list=config_list)
messages = [{'role': 'user',
             'content': 'Can you give me 3 useful tips on learning Python? Keep it simple and short.'
            },]
response = client.create(messages=messages, model="gpt-35-turbo", cache_seed=None)
print(response) # this does not give error
```

# This gives error
```
print(response.cost)
```

# config list
```json
[{'model': 'gpt-35-turbo',
  'api_key': 'xxx',
  'base_url': 'xxx',
  'api_type': 'azure',
  'api_version': '2023-06-01-preview'}]
```

# How to make it work?

**Comment by rickyloynd-microsoft** [comment]
@kevin666aa fyi

**Comment by kevin666aa** [comment]
autogen : 0.2.0 doesn't have this feature yet. Will be in v0.2.1.

**Comment by kyang8093** [comment]
@kevin666aa likewise, also on 0.2.1 (and openai 1.2.4)

**Comment by kevin666aa** [comment]
@kyang8093 @gbertb 
```python
from autogen import OpenAIWrapper

client = OpenAIWrapper(config_list=config_list)
messages = [{'role': 'user', 'content': 'Can you give me 3 useful tips on learning Python? Keep it simple and short.'},]
response = client.create(messages=messages, model="gpt-35-turbo-1106", cache_seed=None)
print(response.cost)
```
Are you running this code from `oai_client_cost.ipynb` and get an error? If not, can you share your code ?

If you running a code with `cache_seed` set and using cache, this could cause the issue, because previous cache doesn't have the cost attribute. I am making a PR to address that. Please let me know if this is not the case.

**Comment by kyang8093** [comment]
Yes, I was using my own code with cache_seed set. Thanks for making a PR, hope it's addressed soon!
