### ISSUE TITLE
formats in retrieve_utils.py

### ISSUE THREAD

**Issue by szwang-seedtech** [microsoft/autogen#891]
Hello,

I find "pdf, rtf, rst" are listed in both TEXT_FORMATS and UNSTRUCTED_FORMATS. Is it a typo?

https://github.com/microsoft/autogen/blob/f8b4b4259b2c4bf26c47e6eb0fa3257203d106a0/autogen/retrieve_utils.py

**Comment by rickyloynd-microsoft** [comment]
@thinkall fyi

**Comment by szwang-seedtech** [comment]
I see. Thank you for the explanation!
