### ISSUE TITLE
SSL Error 

### ISSUE THREAD

**Issue by PriyaBrataSen** [microsoft/autogen#898]
Hello, When i run the first example code to get Meta and Tesla ytd gain%, it runs fine in the goggle colab. However, when i run it in my computer using docker, i always get this error. Once this error happens, Autogen stop using yfinance and starts moving to some paid library. Ultimately, it fails. It seems like the SSLError. Any idea why it is happening? Any help will be highly appreciated 

Downloading soupsieve-2.5-py3-none-any.whl (36 kB)
Building wheels for collected packages: peewee
  Building wheel for peewee (pyproject.toml): started
  Building wheel for peewee (pyproject.toml): finished with status 'done'
  Created wheel for peewee: filename=peewee-3.17.0-py3-none-any.whl size=135721 sha256=b884edfe675a286ba1622af63dad5b64eefd93fd434291a32a2b49b3bae75dce
  Stored in directory: /root/.cache/pip/wheels/02/20/23/74a10d0cd31f5d41c19b92ddf4c138ceff01b9f4675f19dbf5
Successfully built peewee
Installing collected packages: webencodings, pytz, peewee, multitasking, appdirs, tzdata, soupsieve, six, lxml, frozendict, python-dateutil, html5lib, beautifulsoup4, pandas, yfinance
Successfully installed appdirs-1.4.4 beautifulsoup4-4.12.2 frozendict-2.3.10 html5lib-1.1 lxml-4.9.3 multitasking-0.0.11 pandas-2.1.3 peewee-3.17.0 python-dateutil-2.8.2 pytz-2023.3.post1 six-1.16.0 soupsieve-2.5 tzdata-2023.3 webencodings-0.5.1 yfinance-0.2.33

Failed to get ticker 'FB' reason: HTTPSConnectionPool(host='fc.yahoo.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1006)')))
FB: No price data found, symbol may be delisted (period=ytd)
Traceback (most recent call last):
  File "", line 11, in <module>
    meta_ytd_gain = get_ytd_gain("FB")
                    ^^^^^^^^^^^^^^^^^^
  File "", line 6, in get_ytd_gain
    start_price = hist.iloc[0]["Close"]
                  ~~~~~~~~~^^^
  File "/usr/local/lib/python3.11/site-packages/pandas/core/indexing.py", line 1153, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pandas/core/indexing.py", line 1714, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.11/site-packages/pandas/core/indexing.py", line 1647, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

**Comment by PriyaBrataSen** [comment]
Thank your Sir for looking into this matter. Sure, below is my terminal. I copied the demo.py file in working directory inside the docker file. It has the first example.  




PS C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen> activate
PS C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen> conda activate C:\Users\PSen\AppData\Local\anaconda3
PS C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen> docker run -it autogen2
autogen-dev@43ce554b3892:~/autogen$ python demo.py
user_proxy (to assistant):


What date is today? Compare the year-to-date gain for META and TESLA.


--------------------------------------------------------------------------------
assistant (to user_proxy):

First, let's get the current date. Then, we will fetch the stock prices for META (Facebook) and TESLA and calculate the year-to-date gain for both.

Step 1: Get the current date
```python
from datetime import datetime
today = datetime.now()
print("Today's date:", today.strftime("%Y-%m-%d"))
```

Step 2: Fetch stock prices and calculate year-to-date gain
To fetch stock prices, we will use the `yfinance` library. Please install it by running the following command:

```sh
pip install yfinance
```

After installing the library, execute the following code to fetch the stock prices and calculate the year-to-date gain:

```python
import yfinance as yf
from datetime import datetime, timedelta

today = datetime.now()
start_of_year = datetime(today.year, 1, 1)

meta = yf.Ticker("FB")
tesla = yf.Ticker("TSLA")

meta_history = meta.history(start=start_of_year, end=today)
tesla_history = tesla.history(start=start_of_year, end=today)

meta_start_price = meta_history.iloc[0]['Close']
meta_end_price = meta_history.iloc[-1]['Close']
meta_ytd_gain = (meta_end_price - meta_start_price) / meta_start_price * 100

tesla_start_price = tesla_history.iloc[0]['Close']
tesla_end_price = tesla_history.iloc[-1]['Close']
tesla_ytd_gain = (tesla_end_price - tesla_start_price) / tesla_start_price * 100

print(f"Year-to-date gain for META (Facebook): {meta_ytd_gain:.2f}%")
print(f"Year-to-date gain for TESLA: {tesla_ytd_gain:.2f}%")
```

This code will print the current date and the year-to-date gain for both META (Facebook) and TESLA.

--------------------------------------------------------------------------------

>>>>>>>> EXECUTING CODE BLOCK 0 (inferred language is python)...

>>>>>>>> EXECUTING CODE BLOCK 1 (inferred language is sh)...

>>>>>>>> EXECUTING CODE BLOCK 2 (inferred language is python)...
user_proxy (to assistant):

exitcode: 1 (execution failed)
Code output:
Today's date: 2023-12-07

Defaulting to user installation because normal site-packages is not writeable
Collecting yfinance
  Downloading yfinance-0.2.33-py2.py3-none-any.whl (69 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.0/69.0 kB 1.4 MB/s eta 0:00:00
Collecting lxml>=4.9.1
  Downloading lxml-4.9.3-cp310-cp310-manylinux_2_28_x86_64.whl (7.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 8.7 MB/s eta 0:00:00
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.10/site-packages (from yfinance) (2.31.0)
Collecting appdirs>=1.4.4
  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting peewee>=3.16.2
  Downloading peewee-3.17.0.tar.gz (2.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 7.3 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.10/site-packages (from yfinance) (1.26.2)
Collecting multitasking>=0.0.7
  Downloading multitasking-0.0.11-py3-none-any.whl (8.5 kB)
Collecting pytz>=2022.5
  Downloading pytz-2023.3.post1-py2.py3-none-any.whl (502 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 502.5/502.5 kB 10.0 MB/s eta 0:00:00
Collecting frozendict>=2.3.4
  Downloading frozendict-2.3.10-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (115 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.9/115.9 kB 5.4 MB/s eta 0:00:00
Collecting html5lib>=1.1
  Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.2/112.2 kB 14.2 MB/s eta 0:00:00
Collecting pandas>=1.3.0
  Downloading pandas-2.1.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 11.3 MB/s eta 0:00:00
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.10/site-packages (from yfinance) (4.12.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.10/site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Collecting tzdata>=2022.1
  Downloading tzdata-2023.3-py2.py3-none-any.whl (341 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.8/341.8 kB 7.6 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/site-packages (from requests>=2.31->yfinance) (3.6)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/site-packages (from requests>=2.31->yfinance) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/site-packages (from requests>=2.31->yfinance) (2023.11.17)
Building wheels for collected packages: peewee
  Building wheel for peewee (pyproject.toml): started
  Building wheel for peewee (pyproject.toml): finished with status 'done'
  Created wheel for peewee: filename=peewee-3.17.0-cp310-cp310-linux_x86_64.whl size=848717 sha256=8e366956e5851a3fcc9c7818a72ccb9f38042516929902151b9269e744eb2006
  Stored in directory: /home/autogen-dev/.cache/pip/wheels/c7/70/ad/212867e96e7004265a69c4aa5dcff00a95f547a67ba26e7e76
Successfully built peewee
Installing collected packages: pytz, peewee, multitasking, appdirs, tzdata, lxml, html5lib, frozendict, pandas, yfinance
Successfully installed appdirs-1.4.4 frozendict-2.3.10 html5lib-1.1 lxml-4.9.3 multitasking-0.0.11 pandas-2.1.3 peewee-3.17.0 pytz-2023.3.post1 tzdata-2023.3 yfinance-0.2.33

Failed to get ticker 'FB' reason: HTTPSConnectionPool(host='fc.yahoo.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1007)')))
FB: No timezone found, symbol may be delisted
Failed to get ticker 'TSLA' reason: HTTPSConnectionPool(host='fc.yahoo.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1007)')))
TSLA: No timezone found, symbol may be delisted
Traceback (most recent call last):
  File "", line 13, in <module>
    meta_start_price = meta_history.iloc[0]['Close']
  File "/home/autogen-dev/.local/lib/python3.10/site-packages/pandas/core/indexing.py", line 1153, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/autogen-dev/.local/lib/python3.10/site-packages/pandas/core/indexing.py", line 1714, in _getitem_axis
    self._validate_integer(key, axis)
  File "/home/autogen-dev/.local/lib/python3.10/site-packages/pandas/core/indexing.py", line 1647, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds


--------------------------------------------------------------------------------
assistant (to user_proxy):

I apologize for the error. It seems there is an issue with fetching the stock data using the `yfinance` library. Let's try an alternative approach using the `alpha_vantage` library to fetch the stock prices.

First, you need to obtain an API key from Alpha Vantage. Please follow these steps:

1. Go to the [Alpha Vantage website](https://www.alphavantage.co/).
2. Click on "Get your free API key" and sign up for a free account.
3. After signing up, you will receive an API key.

Next, install the `alpha_vantage` library by running the following command:

```sh
pip install alpha_vantage
```

After installing the library and obtaining your API key, execute the following code to fetch the stock prices and calculate the year-to-date gain:

Replace `YOUR_API_KEY` with the API key you obtained from Alpha Vantage.

```python
from alpha_vantage.timeseries import TimeSeries
from datetime import datetime, timedelta

api_key = "YOUR_API_KEY"

today = datetime.now()
start_of_year = datetime(today.year, 1, 1)

ts = TimeSeries(key=api_key, output_format='pandas')

meta_data, meta_history = ts.get_daily_adjusted(symbol='FB', outputsize='full')
tesla_data, tesla_history = ts.get_daily_adjusted(symbol='TSLA', outputsize='full')

meta_history = meta_history.loc[start_of_year.strftime("%Y-%m-%d"):today.strftime("%Y-%m-%d")]
tesla_history = tesla_history.loc[start_of_year.strftime("%Y-%m-%d"):today.strftime("%Y-%m-%d")]

meta_start_price = meta_history.iloc[0]['5. adjusted close']
meta_end_price = meta_history.iloc[-1]['5. adjusted close']
meta_ytd_gain = (meta_end_price - meta_start_price) / meta_start_price * 100

tesla_start_price = tesla_history.iloc[0]['5. adjusted close']
tesla_end_price = tesla_history.iloc[-1]['5. adjusted close']
tesla_ytd_gain = (tesla_end_price - tesla_start_price) / tesla_start_price * 100

print("Today's date:", today.strftime("%Y-%m-%d"))
print(f"Year-to-date gain for META (Facebook): {meta_ytd_gain:.2f}%")
print(f"Year-to-date gain for TESLA: {tesla_ytd_gain:.2f}%")
```

This code will print the current date and the year-to-date gain for both META (Facebook) and TESLA.

--------------------------------------------------------------------------------

>>>>>>>> EXECUTING CODE BLOCK 0 (inferred language is sh)...

>>>>>>>> EXECUTING CODE BLOCK 1 (inferred language is python)...
user_proxy (to assistant):

exitcode: 1 (execution failed)
Code output:
Defaulting to user installation because normal site-packages is not writeable
Collecting alpha_vantage
  Downloading alpha_vantage-2.3.1-py3-none-any.whl (31 kB)
Collecting aiohttp
  Downloading aiohttp-3.9.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 6.9 MB/s eta 0:00:00
Requirement already satisfied: requests in /usr/local/lib/python3.10/site-packages (from alpha_vantage) (2.31.0)
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.4.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (225 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 225.7/225.7 kB 4.6 MB/s eta 0:00:00
Collecting aiosignal>=1.1.2
  Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/site-packages (from aiohttp->alpha_vantage) (23.1.0)
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.0.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.5/114.5 kB 4.9 MB/s eta 0:00:00
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.9.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (301 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 301.6/301.6 kB 8.4 MB/s eta 0:00:00
Collecting async-timeout<5.0,>=4.0
  Downloading async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/site-packages (from requests->alpha_vantage) (2.1.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/site-packages (from requests->alpha_vantage) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/site-packages (from requests->alpha_vantage) (3.6)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/site-packages (from requests->alpha_vantage) (2023.11.17)
Installing collected packages: multidict, frozenlist, async-timeout, yarl, aiosignal, aiohttp, alpha_vantage
Successfully installed aiohttp-3.9.1 aiosignal-1.3.1 alpha_vantage-2.3.1 async-timeout-4.0.3 frozenlist-1.4.0 multidict-6.0.4 yarl-1.9.4

Traceback (most recent call last):
  File "", line 11, in <module>
    meta_data, meta_history = ts.get_daily_adjusted(symbol='FB', outputsize='full')
  File "/home/autogen-dev/.local/lib/python3.10/site-packages/alpha_vantage/alphavantage.py", line 218, in _format_wrapper
    call_response, data_key, meta_data_key = func(
  File "/home/autogen-dev/.local/lib/python3.10/site-packages/alpha_vantage/alphavantage.py", line 160, in _call_wrapper
    return self._handle_api_call(url), data_key, meta_data_key
  File "/home/autogen-dev/.local/lib/python3.10/site-packages/alpha_vantage/alphavantage.py", line 361, in _handle_api_call
    raise ValueError(json_response["Information"])
ValueError: Thank you for using Alpha Vantage! This is a premium endpoint. You may subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly unlock all premium endpoints


--------------------------------------------------------------------------------
assistant (to user_proxy):

I apologize for the inconvenience. It seems that the Alpha Vantage API requires a premium subscription to access the daily adjusted stock prices. In this case, I recommend using the FRED (Federal Reserve Economic Data) API to fetch the stock prices. However, FRED API does not provide stock prices for individual companies like META and TESLA.

As an alternative, you can manually check the year-to-date gain for META and TESLA using financial websites like Yahoo Finance or Google Finance:

1. [META (Facebook) on Yahoo Finance](https://finance.yahoo.com/quote/FB/)
2. [TESLA on Yahoo Finance](https://finance.yahoo.com/quote/TSLA/)

On these websites, you can find the year-to-date gain percentage under the "Performance Outlook" section.

I apologize for not being able to provide a code-based solution for this task. If you have any other questions or need assistance with a different task, please feel free to ask.

--------------------------------------------------------------------------------
user_proxy (to assistant):



--------------------------------------------------------------------------------
assistant (to user_proxy):

TERMINATE

--------------------------------------------------------------------------------
autogen-dev@43ce554b3892:~/autogen$

**Comment by rickyloynd-microsoft** [comment]
Are you using GPT-4 or some other LLM?

**Comment by PriyaBrataSen** [comment]
'model': 'gpt-4-8k'

**Comment by PriyaBrataSen** [comment]
let me run it. Should i use "use_docker":False in the code_execution_config?

**Comment by rickyloynd-microsoft** [comment]
Then this SSL error must be caused by something external to docker and autogen. Which python version are you using? I see several comments on the web about what might cause this error. Search for "SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED".

**Comment by sonichi** [comment]
"alpine" can't install new packages. Try "python:3".

**Comment by PriyaBrataSen** [comment]
I prompted the agent to use 'verify'=False in the get request, so that it bypass the SSL certification issue. It works now. Thanks for your help. @rickyloynd-microsoft @sonichi

**Comment by OlivierBDA** [comment]
Hello, I have the same issue with SSL verification issue. 
How did you resolve it ? Your previous message is not enough explicit to know where to indicate the Agents to use 'verify'=False.
Can you provide your llm_config list ? ie: config_list = [{"model":"xxxx", "api_key":"mykey", "base_url":"myurl"}] ?
or in another part of the code ?
AssistantAgent(name="MyAssistant", system_message="You are an assistant...", llm_config={"config_list" : config_list, "cache_seed":None})
Thanks
Olivier

**Comment by thrivedhG** [comment]
@PriyaBrataSen 
> I prompted the agent to use 'verify'=False in the get request, so that it bypass the SSL certification issue. It works now. 
Hi,
could you please elaborate on this comment on where we need to set verify = false condition, facing similar issue.
Thanks
