### ISSUE TITLE
Trying twoagent.py in Getting Started and it does not run on Windows. Gives WARNING:root:SIGALRM is not supported on Windows.

### ISSUE THREAD

**Issue by radman-x** [microsoft/autogen#91]
I cannot get the twoagent.py script to run under Windows in VSCode (via the "Run | StartDebugging" command). I followed the instructions in the Getting Started docs but get the following error:

  ModuleNotFoundError: No module named 'pandas'

Also, I get the SIGALRM is not supported waring; here is the console output:

`user_proxy (to assistant):

Plot a chart of NVDA and TESLA stock price change YTD.

--------------------------------------------------------------------------------
assistant (to user_proxy):

To plot the chart of NVDA and TESLA stock price change Year-to-Date (YTD), we need to first collect the stock price data 
for both NVDA and TESLA. We can fetch the data from a financial API such as Alpha Vantage. Here is an example of how you 
can plot the chart using Python:

```python
# Required Libraries
import pandas as pd
import matplotlib.pyplot as plt

<edited for brevity>

plt.show()
```

Please note that you need to replace `<your_api_key>` with your API key from Alpha Vantage. Make sure you have the required libraries installed (`pandas`, `matplotlib`, `seaborn`, and `requests`) before executing the code.

Let me know if you need any further assistance.

--------------------------------------------------------------------------------
Provide feedback to assistant. Press enter to skip and use auto-reply, or type 'exit' to end the conversation:

>>>>>>>> NO HUMAN INPUT RECEIVED.

>>>>>>>> USING AUTO REPLY...

>>>>>>>> EXECUTING CODE BLOCK 0 (inferred language is python)...
WARNING:root:SIGALRM is not supported on Windows. No timeout will be enforced.`

Note: of course, I can install pandas, etal. but that defeats the auto-troubleshooting of the UserProxyAgent.
I suspect this is somewhat similar to the problems mentioned in #17, #19 and #38.
Does AutoGen support running on Windows?

pyautogen version: 0.1.6 (from 10/2/2023 build)
Windows specs: Windows 10 Home (64-bit), OS build: 19045.3448
Running in virtual python environment from VSCode.
NOT running in docker (yet).

**Comment by sonichi** [comment]
The warning shouldn't stop the program. Could you wait and see if it finishes with an error?

**Comment by radman-x** [comment]
Thnx for the quick response.

Yes, that does help a lot. Seems one problem I had was while running in vscode, I had "uncaught exceptions" break point turned on and I was just hitting that breakpoint. The SIGALRM warning was not the problem. I am able to progress quick a bit further. It now seems to be installing the correct modules but I am now hitting a tokens limit problem.

Therefore, I will close this issue and re-submit a different one if that is warranted.
