### ISSUE TITLE
[Feature Request]: Callback for openai api

### ISSUE THREAD

**Issue by iplayfast** [microsoft/autogen#930]
### Is your feature request related to a problem? Please describe.

when trying to run locally, I'm finding I'm constantly tripping over everyone going to open ai /api, when I'm trying to run local llm
My request is to be able to assign a callback to the api,
That is, before calling the api, the call back is called. If the callback is handled locally it returns true, and the parameters are updated from the callback instead of going out to the api. 

### Describe the solution you'd like

The callback function would do the equivalent of this c++ code  in python. (Sorry, don't know python well enough)
```
bool Callback(const char *ToApi, char *Result)
{
// if possible, do stuff according to ToApi, and put the resulting value in Result, return true
// if not possible return false, and normal api is called.
}
```

If this feature is already implemented in some way, please let me know.

**Comment by rickyloynd-microsoft** [comment]
@sonichi fyi

**Comment by rysweet** [comment]
closing as stale, please reopen if you disagree.
