### ISSUE TITLE
[Feature Request]: Support specifying deployment-id for Azure

### ISSUE THREAD

**Issue by WiSaGaN** [microsoft/autogen#932]
### Is your feature request related to a problem? Please describe.

Currently for Azure, the reqwest url assumes "model" in it:
https://github.com/microsoft/autogen/blob/9cec541630af22c2e2683d1f44a6ddd1d2e2425f/autogen/oai/client.py#L121

But Azure has below (https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#chat-completions)
```
POST https://{your-resource-name}.openai.azure.com/openai/deployments/{deployment-id}/chat/completions?api-version={api-version}
```
where "deployment-id" is defined by user, and not nessesarily the model name.

### Describe the solution you'd like

In order to support the case when the deployment-id is not the same as model name, we can add support for deployment-id, and use this in the suffix instead of "model" and only fallback to use current method.

**Comment by rickyloynd-microsoft** [comment]
@sonichi fyi

**Comment by sonichi** [comment]
Right now we require the deployment_name to be used as the value of "model" for azure endpoints.

**Comment by WiSaGaN** [comment]
I see. Thanks!
