### ISSUE TITLE
[Issue]:  api key err issue running agentchat_teachability.ipynb

### ISSUE THREAD

**Issue by taozhiyuai** [microsoft/autogen#938]
### Describe the issue

1. when I use Azure key
load key successfully, but err 
![teachability_load azure key successfully](https://github.com/microsoft/autogen/assets/146583103/5a94c502-1a53-4d3d-b631-95a66ed79811)

![teachability_ERR](https://github.com/microsoft/autogen/assets/146583103/e6f101d6-dc58-4093-bd94-0c39a8b21e26)

2.when I use oneapi key

![teachability_ERR_oneapi](https://github.com/microsoft/autogen/assets/146583103/0c78a41e-4459-4a29-8dd8-341c353f83e5)
![teachability_load oneapi key successfully](https://github.com/microsoft/autogen/assets/146583103/48a0e36e-6842-412b-b5d8-d8d8c9ce90ca)

is anyone know how to solve this issue?

**Comment by taozhiyuai** [comment]
relevent issue is https://github.com/microsoft/autogen/issues/939

**Comment by taozhiyuai** [comment]
relevent issue is https://github.com/microsoft/autogen/issues/939

**Comment by rickyloynd-microsoft** [comment]
To match the latest api from openai, `api_base` had been replaced by `base_url`.
