### ISSUE TITLE
[Issue]: ERR info for config_list with different key

### ISSUE THREAD

**Issue by taozhiyuai** [microsoft/autogen#939]
### Describe the issue

when I run code on https://microsoft.github.io/autogen/blog/2023/10/26/TeachableAgent/

1. ok perfectly with Azure key
![Azure perfect](https://github.com/microsoft/autogen/assets/146583103/09023a83-01c0-417c-a0bf-5da9fa3c514e)

2.but not work with OneAPI, load key successfully, but ERR followed.

![load oneapi key OK ERR](https://github.com/microsoft/autogen/assets/146583103/4ec9ac3b-5274-49d3-bdb4-3a31f4264ef3)
![load oneapi key OK](https://github.com/microsoft/autogen/assets/146583103/d9a217e3-0937-4a03-b30a-d4226cc6f464)

relevent issue is  https://github.com/microsoft/autogen/issues/938

**Comment by rickyloynd-microsoft** [comment]
To match the latest api from openai, `api_base` had been replaced by `base_url`.

**Comment by taozhiyuai** [comment]
> To match the latest api from openai, `api_base` had been replaced by `base_url`.

thanks
