### ISSUE TITLE
How to acquire actual terminating message from either UserProxyAgent or AssistantAgent(s)?

### ISSUE THREAD

**Issue by mathematicsofpaul** [microsoft/autogen#943]
I wanted to know how to get the literal terminating message from the Agent that terminates the GroupChat? I need to know the output for my own custom uses, since I intend on changing the terminating message to be either "GOOD" or "BAD" instead. But more importantly, I want to know exactly which of those terms were outputted for the conversation to be terminated.

I understand that prompting the output that mentions "TERMINATE" will terminate the whole process by default or by the given function: 

`is_termination_msg=lambda msg: "TERMINATE" in msg["content"]`

Writing a function like this will get the job done in terms of termination: 

`check_compatibility = lambda msg: "GOOD" in msg["content"] or "BAD" in msg["content"]` 

But how would I find out exactly which term - "GOOD" or "BAD" was outputted by the agent? If it helps, I want the terminating GOOD/BAD message to be delivered by the UserProxyAgent.

What I have tried: 

- I have tried checking `user_proxy.chat_messages` but that only gave me the message history without the terminating message sadly. 
- Attempted to change the `default_auto_reply` to output the actual terminating message based on a conditional function... but I just don't know which variable in the class to reference.

**Comment by rickyloynd-microsoft** [comment]
@afourney fyi

**Comment by thinkall** [comment]
@mathematicsofpaul  The last message either contains the termination string or it reaches the max reply round.

**Comment by rysweet** [comment]
answered in June.

**Comment by Vikramank** [comment]
@mathematicsofpaul @rysweet - any updates on this issue? is it possible to terminate on agent message rather than human input or input from other agent?

**Comment by jackgerrits** [comment]
Please see the docs on termination: https://microsoft.github.io/autogen/stable/user-guide/agentchat-user-guide/tutorial/termination.html

**Comment by Vikramank** [comment]
hi @jackgerrits ,
Thanks for the link. Anywork around for v0.2? I thought this would fix: 
`is_termination_msg = lambda msg: "transferring" in current_agent.last_message()["content"].lower()`
But looks like it is always looking for incoming message only

**Comment by ekzhu** [comment]
@Vikramank I suggest use `register_reply` for customization if you really want to stick with v0.2.

**Comment by Vikramank** [comment]
hi @ekzhu , 
Thank you for suggestion. I looked up the discussion about `register_reply` but unclear about implementation. I am trying in this sequential chat framework(https://microsoft.github.io/autogen/0.2/docs/tutorial/conversation-patterns/#sequential-chats). My goal is to transition from one agent to another when the 'trigger word' is generated by the agent. A lot of notebooks for v0.2 seems missing. Could you please help me with this? With the new version of Autogen, the docs for sequential architecture are missing. Would you say that it is easy to implement this in Autogen 0.4?

**Comment by ekzhu** [comment]
Sequential chat is anti-pattern -- it was complicated to use and error prone. So, we don't support it in 0.4 anymore.

In 0.4, if you want an agent to iterate multiple times, you can (1) call it in a loop until a trigger word is generated as part of its response, or (2) use in a RoundRobinGroupChat.

To chain multiple such agent loops together, just write the Python code to call them in sequence. Your application manages the flow.

Agents and teams support save and load states so you can apply check points anytime during your flow.
