### ISSUE TITLE
[Bug]: GPTAssistantAgent doesn't update instructions if openai_assistant_id is None and retrieve_assistants_by_name is invoked

### ISSUE THREAD

**Issue by lc0rp** [microsoft/autogen#952]
### Describe the bug

autogen/agentchat/contrib/gpt_assistant_agent.py lines 94+ which updates the instructions only gets run if an openai_assistant_id was passed in, but the changes in #718 introduce the ability to retrieve an assistant by name, if openai_assistant_id is None. 

The agent retrieved_by_name will not get instructions updated even if overwrite_instructions=True.

@IANTHEREAL - possible fix is to outdent lines 89 to 105

### Steps to reproduce

1. Create an assistant with a known name and instructions via the playground or API.
	- name=Test
	- instructions=Old instructions
2. Call GPTAssistantAgent(name="Test", instructions="New instructions", overwrite_instructions=True)
3. The instructions will still be "Old instructions

### Expected Behavior

One expects overwrite_instructions to be respected even if the agent is retrieved by name.

**Comment by afourney** [comment]
@gagb for visibility

**Comment by gagb** [comment]
@lc0rp, I agree with @IANTHEREAL -- the name field is not unique, and if you see @IANTHEREAL's PR he added a clarification for `overwrite_instructions` saying "This parameter is in effect only when assistant_id is specified in llm_config."

**Comment by gagb** [comment]
This was addressed.
