### ISSUE TITLE
[Bug]: AgentBuilder does not reload the code_execution_config used by the user proxy agent

### ISSUE THREAD

**Issue by plimantour** [microsoft/autogen#954]
### Describe the bug

When using a custom code_execution_config to build agents using AgentBuilder, the config is used, saved correctly, but the AgentBuilder does not load/reload the code_execution_config used by the user proxy agent from the saved .json configuration file.

### Steps to reproduce

saved_agent_configs = load_json_to_dict(agents_config_path)
print(agent_list[0]._code_execution_config)

This displays the defaut config, not the saved one (e.g. is saved with "use_docker" : True, loads the default "use_docker" : False

### Expected Behavior

load() should reload the _code_execution_config from the .json configuration file

**Comment by rickyloynd-microsoft** [comment]
@LinxinS97 fyi
