### ISSUE TITLE
[Solved]: How to hide redundant messages of github-actions in the PRs

### ISSUE THREAD

**Issue by thinkall** [microsoft/autogen#955]
### Describe the issue

There are too many github-actions messages in the PRs, and reviewers' comments will be hidden. Is it possible to only show the useful comments? Or only hide the redundant comments?

I've created a script to hide the annoy github actions notifications. **Install it on [Greasy Fork](https://greasyfork.org/en/scripts/482085-hide-github-actions-notifications-in-pr-conversations).**

### Screenshots and logs

![image](https://github.com/microsoft/autogen/assets/3197038/744dea0a-ffda-4d6a-998f-6f3d93147170)

**Comment by rickyloynd-microsoft** [comment]
It would be great to fix this somehow!

**Comment by thinkall** [comment]
I created a tampermonkey script for it. One can install it on [Greasy Fork](https://greasyfork.org/en/scripts/482085-hide-github-actions-notifications-in-pr-conversations).
