### ISSUE TITLE
Group Chat Termination When Calling RAGProxyAgent via Admin Agent

### ISSUE THREAD

**Issue by ShaneYuTH** [microsoft/autogen#96]
#### Main Issue:
When posing a question to the Admin agent that involves RAGProxyAgent in a group chat context (e.g., "Provide me with some data," whether explicitly or implicitly stated), the group chat session terminates unexpectedly without any error messages.

---

#### Potential Cause:
This may be because the agent is set to terminate as soon as the code execution succeeds. (Suggested by @sonichi )

---

#### Additional good-to-have:
A notebook example showcasing how the RAG agent operates within a group chat.

**Comment by thinkall** [comment]
Thanks @ShaneYuTH for the feedback, I'll look into it.

**Comment by scdnapier** [comment]
I was able to add RAG to a group chat using a function call that spawned a separate ragproxy chat and returned the results.

I'm sure this is not the intended approach but it worked in the interim

**Comment by thinkall** [comment]
Usually we'll have only one user proxy agent. When we involve Retrieve Agents, the RetrieveUserProxyAgent will be the user proxy agent, so we don't need to have another user proxy agent. In PR #227, there is an example. @ShaneYuTH , @scdnapier would this also work for you?

**Comment by ShaneYuTH** [comment]
> Usually we'll have only one user proxy agent. When we involve Retrieve Agents, the RetrieveUserProxyAgent will be the user proxy agent, so we don't need to have another user proxy agent. In PR #227, there is an example. @ShaneYuTH , @scdnapier would this also work for you?

Thank you so much for your work. I was asking multiple user proxy agent cause I saw similar setup in [https://github.com/microsoft/autogen/blob/main/notebook/agentchat_groupchat_research.ipynb](url), where there were one userproxy as admin and one as code executor. I'll take a look into the example right now.

**Comment by thinkall** [comment]
> > Usually we'll have only one user proxy agent. When we involve Retrieve Agents, the RetrieveUserProxyAgent will be the user proxy agent, so we don't need to have another user proxy agent. In PR #227, there is an example. @ShaneYuTH , @scdnapier would this also work for you?
> 
> Thank you so much for your work. I was asking multiple user proxy agent cause I saw similar setup in [https://github.com/microsoft/autogen/blob/main/notebook/agentchat_groupchat_research.ipynb](url), where there were one userproxy as admin and one as code executor. I'll take a look into the example right now.

Hi @ShaneYuTH , I've added multiple user proxy agent support in #227 as well.
