### ISSUE TITLE
Exception: UnicodeEncodeError: 'charmap' codec can't encode character 

### ISSUE THREAD

**Issue by tyler-suard-parker** [microsoft/autogen#964]
### Describe the bug

Sometimes when the Agent searches for something and tries to print the results, I get this error.  It might be an idea to deal with this right before the agent's print statement in 
\autogen\agentchat\conversable_agent.py", line 417, in _print_received_message
    print(message["content"], flush=True)

**Comment by julianakiseleva** [comment]
@afourney can you look into this please?

**Comment by afourney** [comment]
@tyler-suard-parker Can you provide more information about your setup? Does " when the Agent searches for something" mean you are using retrievechat or RAG?

**Comment by tyler-suard-parker** [comment]
@afourney I am using an assitant agent to download a webpage, and the agent automatically prints the results to the command line in Windows.  Windows uses "Windows-1252" encoding for the strings it renders in the command line, so anything represented in that character set will cause an error.  Because we want to make AutoGen as user-friendly as possible, do you think we could include something in the code that checks to see if the script is running on Windows, and if so then convert the console output to UTF-8?

**Comment by thinkall** [comment]
@tyler-suard-parker has the issue been resolved?

**Comment by tyler-suard-parker** [comment]
I'm sorry but we moved on from downloading web pages months ago, so I don't remember.  I think I was able to fix the issue by just setting encoding to utf-8 or just filtering out the unwanted characters.
