### ISSUE TITLE
Discord Link Has Expired?

### ISSUE THREAD

**Issue by jake-burton** [microsoft/autogen#975]
### Describe the issue

Can't seem to find a valid discord link for the Autogen discord. Is there an updated link anywhere?

**Comment by afourney** [comment]
Hmm, it seems to work for me. What about this one? https://discord.com/invite/pAbnFJrkgZ

**Comment by jake-burton** [comment]
weird, still doesn't work for me. I keep getting a "whoops... unable to accept invite"

**Comment by afourney** [comment]
@sonichi  any idea what's up here? Do we need to re-generate it?

**Comment by julianakiseleva** [comment]
@afourney @jake-burton the link works for me as well

**Comment by sonichi** [comment]
@jake-burton There are people who joined via the same link after your message. Could you ping me on discord?

**Comment by gagb** [comment]
> discord link still not working. maybe generate a non-expiring link...

Can you try aka.ms/autogen-discord? Also ensure you try a different browser if it does not work?
