### ISSUE TITLE
Standardize folder format for benchmarks (Move benchmark-specific READMEs, util scripts, metrics, etc. to appropriate folders)

### ISSUE THREAD

**Issue by afourney** [microsoft/autogen#976]
As we onboard more benchmarks and evaluation datasets, I think it is worth reorganizing the Testbed folder structure. A 1st pass proposed layout would be:

```
./testbed/
./testbed/README.md
./testbed/testbed  <-- Convert `run_scenarios.py` to a module and move it and other global stuff like `Includes` here
./testbed/scenarios <-- Keep as-is
```

Then for each Benchmark within scenarios, (using GAIA as an example):
```
./testbed/scenarios/GAIA/README.md         <-- Readme for running GAIA
./testbed/scenarios/GAIA/Templates             <-- As-is templates for the scenarios
./testbed/scenarios/GAIA/Scripts                  <-- GAIA related scripts (download, collate, etc.)
./testbed/scenarios/GAIA/Tasks                     <-- JSONL files describing the tasks (created dynamically when download script run)
./testbed/scenarios/GAIA/Results                  <-- Results folder produced by run_scenarios.py (created dynamically with run_scenarios)
./testbed/scenarios/GAIA/TaskResources      <-- Files referenced by tasks (created dynamically when download script is run)
```

This pattern would be repeated for HumanEval, MATH, etc.
Moving forward, we might also provide a Docker file and etc. perhaps in the root of each Benchmark as warranted.

@LeoLjl @kevin666aa  You have worked with the Testbed. What do you think of this?

I am willing to do the legwork to make this happen. I am not asking you to modify your contributions, but am asking if it would be ok for me to do so,

**Comment by kevin666aa** [comment]
Where should on put requirements.txt for a dataset? I think it should also be put in corresponding scenarios.

`./testbed/scenarios/GAIA/Scripts` includes py files right? Just a personal preference, I would put these files in`/testbed/scenarios/GAIA/` directly if there are not too many. 

Another idea:
Remove `TaskResources` and add:
```
./testbed/scenarios/GAIA/Tasks/JSONL
./testbed/scenarios/GAIA/Tasks/Downloads
```

**Comment by afourney** [comment]
Yeah requirements will get moved too. I'm trying to decide the best place.

Technically if you put a requirements.txt file in a template folder, it will be copied over with that scenario, allowing. You can also even template it and have control per task instance. Either might be a better option going forward (I'm sort of learning as I go here)

**Comment by afourney** [comment]
Completed in #1048
