### ISSUE TITLE
[Error]: GPTAssistantAgent doesn't work with gpt model from FastChat(Local LLM)

### ISSUE THREAD

**Issue by KAIYI-HSU** [microsoft/autogen#990]
### Describe the bug

May I ask if I cannot use the base_url "localhost:8000/v1" when using the FastChat API on the local end? I encountered an openai.notfounderror with the GPTAssistantAgent, too. The error code is 404.

I have another question:
Is there any difference between running a Python program with GPTAssistantAgent and UserProxyAgent?
It seems like the code interpreter function and the "run Python" function in UserProxyAgent are very similar.
Thank you for your answer.

**Comment by gagb** [comment]
GPTAssistantAgent relies on the openai assistant api: https://platform.openai.com/docs/assistants/overview

Using code interpreter tool in gptassistantagent can be equivalent to using assistant agent + user proxy.

**Comment by KAIYI-HSU** [comment]
Thank you very much
